### ISSUE TITLE
Unable to import IntlShape

### ISSUE THREAD

**Issue by phatv** [formatjs/formatjs#1456]
### Expected behavior

Import and use `IntlShape` for prop type definition like `intlShape` before it.
We followed [the example here](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#typescript-support)

### Current behavior

We get the error that IntlShape doesn't exist.
`"export 'IntlShape' was not found in 'react-intl'`
### Step to reproduce for BUG REPORT

Import and use IntlShape. I don't see it when I use the RunKit through npm.
https://npm.runkit.com/react-intl

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | react-intl@3.1.12  |
|      `npm ls react` | react@16.9.0 |
|     `npm --version` | 5.6.0 |
|    `node --version` | v10.0.0 |

**Comment by DanielaValero** [comment]
I am having the same problem, and in order to continue the configuration of the migration I added `useIntl` to my class components as a mean to wait for a reply to this question.

For now I am ignoring the warnings of react of not using hooks inside classes. Not having this available would make impossible to migrate to the next version for us.

**Comment by DanielaValero** [comment]
Hello @longlho,

How do we consume now `intl` inside of a class component?

**Comment by DanielaValero** [comment]
@longlho  thank you for your answer! I meant more the question of @phatv 

As for the validation, I am now understanding that as the `intlShape` is not available anymore, one option might be just use `PropTypes.Object`. 

I find the idea of creating our own `PropTypes.shape` also good, however it feels too tight to an external library and having that coupling might not be a good idea when we (users) don't know/need to know, the internals of the lib. 

What do you both think?

**Comment by Gnito** [comment]
@longlho This is a big rewrite issue for any large applications which have used `intlShape` for proptype validation. Not cool.

**Comment by Gnito** [comment]
@redonkulus thanks for the suggestion! We ended up wrapping react-intl with our own file - so that we can control all the published exports. (It works as a safe guard against similar future changes.)
