### ISSUE TITLE
Control missing messages also in production.

### ISSUE THREAD

**Issue by javaDeveloperKid** [formatjs/formatjs#1573]
In production environment `onError` prop in `IntlProvider` cannot be leveraged.
Commonly a developer is not the one that translates an app and does not care but people that are tasked to keep translations (eg. remote translations) up to date should be notified that new **ids** showed up and need to be translated. Of course before an app gets deployed it is tested and testers catch raw translation ids but cannot notice everything. We accept this fraction of untranslated messages that gets deployed but want to handle this on production
In our project we want to log missing translations to the API and the other guys would have got daily reports about missing messages.

So far I came up with two ideas:
- opt-in returning here: https://github.com/ghostd/react-intl/blob/2d630742f454f404c842265618a3057e5651a47c/src/format.js#L195
- maybe better solution than opt-in return (because message formatting is expensive as said in comment above if statement) we could add another prop accepting e.g. a callback called before return statement so one can do something e.g. asynchronously log to the API.

**Comment by longlho** [comment]
Can u clarify the use case more? Isn't missing translation a build time issue instead of runtime?

**Comment by javaDeveloperKid** [comment]
I think it's a runtime issue. I haven't found info that this package allows to validate missing or not translated ids on build time. It would have to go through the whole React app, wouldn't it?

My app has also one edge case - in many places it uses parts of data returned from API as translation keys - of course this ones cannot be validated by anything.

**Comment by longlho** [comment]
Hmm given that you have to pass all the translated messages in you would
already know what’s missing right? How are you aggregating messages now?

**Comment by javaDeveloperKid** [comment]
Right now I download translations as csv file from Google Drive, convert to JSON, require inside main component and pass to:
`(<IntlProvider locale={language} messages={language && messages[language]} onError={this.onError}>`
I would like to ommit frontend developer to fill in Google Spreadsheet because it's not he's job to care about translations.

**Comment by longlho** [comment]
How do you aggregate the english strings and their IDs from source right
now?

**Comment by javaDeveloperKid** [comment]
Final object passed to IntlProvider with `messages={language && messages[language]}` is one of the given keys:
```javascript
const messages = {
    'en': {"components.basket.empty":"Basket is empty","components.account.complaints.create":"Make a complaint","components.account.complaints.order_number":"Order number", ...},
    'ru': {"components.basket.empty":"Корзина пуста","components.account.complaints.create":"Подать жалобу","components.account.complaints.order_number":"Номер заказа", ...},
};
```

**Comment by longlho** [comment]
No I mean, say you write
```
<FormattedMessage id="foo" defaultMessage="bar" />
```

How do you know to translate the message `bar` to `baz` with the ID `foo`? Do you manually keep a copy of them elsewhere?

**Comment by javaDeveloperKid** [comment]
We do not use `defaultMessage`, just id `<FormattedMessage id={'pages.users.title'}/>`. Before I took over this project it was done manually what means that frontends were adding ids to the Google Drive Spreadsheet and other guys translated new keys before release. I want to automate this process and exclude frontends from this process.

**Comment by longlho** [comment]
We provide tooling (@formatjs/cli) to aggregate all message IDs from a codebase and based on that you can tell which message ID has not been translated.

**Comment by nobitagit** [comment]
Sorry for jumping in the middle of this thread, but I think this can be relevant to the discussion.

> We provide tooling (@formatjs/cli) to aggregate all message IDs from a codebase and based on that you can tell which message ID has not been translated.

Build time checks are possible when validating against a static file, such as:

```js
// en.json
{
  "first_name": "First name"
}

// profile.js
<FormattedMessage id="first_name" />  // all good
<FormattedMessage id="last_name" />  // broken, but can be determined at build time
```

Let's say that we apply values coming from an api and we interpolate them like so:
```js
// en.json
{
  "error.DUPLICATE_ID": "Duplicate id",
  "error.INSSUFICENT_FUNDS": "Insufficient funds"
}

// profile.js
<FormattedMessage id={`error.${someValueComingFromAnApi}` />  

// then at runtime this would become...
<FormattedMessage id="error.INSSUFICENT_FUNDS" />  // all good
<FormattedMessage id="error.DUPLICATE_ID" />  // all good
<FormattedMessage id="error.GENERIC_ERROR" />  // broken
```

It would be great to be able to - say - log the error event to some tracking service like Sentry and be informed of the error that happened at runtime.

But since, as noted by the OP, [in prod react-intl bails out](https://github.com/ghostd/react-intl/blob/2d630742f454f404c842265618a3057e5651a47c/src/format.js#L194-L196) before logging we can't quite do that.

Happy to hear any sort of suggestion (or open a new issue if this is not relevant).
Not a massive problem by any means, but I would be interested in finding a solution or contributing to it if there's any interest.

**Comment by longlho** [comment]
OK gotcha, I'd be open to a PR to specifically check for this.

**Comment by javaDeveloperKid** [comment]
Is there any docs hot to use this cli? Cannot make it work. Tried:
`yarn run formatjs extract`
and
`yarn run formatjs extract src/app/components/account/Basket.js`
```bash
yarn run v1.15.2
$ /app/node_modules/.bin/formatjs extract src/app/components/account/Basket.js
[]
Done in 0.49s.
```

My Component:
```js
import React from 'react';
import {FormattedMessage} from "react-intl";

class Basket extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return <div className="baskets">
            <div className="basket">
                <div className="basket-header">
                    <div>
                        <a>
                            <i className="sprite-arrow-top"/>
                            <FormattedMessage id={`components.basket.hide`}/>
                        </a>

                        <h3>Your basket name</h3>
                        <div className="owner">
                            <FormattedMessage id={`components.basket.owner`}/>: john.doe
                        </div>
                    </div>
                    <div>
                        <button className="blue"><FormattedMessage id={`components.basket.delegate`}/></button>
                        <button className="red"><FormattedMessage id={`components.basket.remove`}/></button>
                    </div>
                </div>
            </div>
        </div>;
    }
}
```

**Comment by longlho** [comment]
you need to specify `defaultMessage` and `id` has to be string literal, otherwise there's nothing to extract
