### ISSUE TITLE
[FormattedMessage] When no DefaultMessage parameter, display id instead of translation

### ISSUE THREAD

**Issue by luknl** [formatjs/formatjs#1589]
Hello!
A user from our platform (that uses react-intl), sent us a screenshot with string displaying strangely.

### Computer from user with problem
As you can see, for some strings, it actually displays the `id` of `<FormattedMessage>`, because it doesn't have the `defaultMessage` parameter (on search bar, form input fields..)

![screenshot](https://user-images.githubusercontent.com/9930144/75052946-bc75f800-54d0-11ea-8e58-ee7e4804ed37.png)

### My computer
But on my computer and for many other users of the platform, it's working fine.

<img width="1325" alt="screenshot2" src="https://user-images.githubusercontent.com/9930144/75052975-c861ba00-54d0-11ea-9242-c377dad55815.png">

You can check full code source of the page [here](https://gitlab.com/JOGL/frontend-v0.1/-/blob/master/src/Pages/CompleteProfile/CompleteProfile.js), and all string translations in english [here](https://gitlab.com/JOGL/frontend-v0.1/blob/master/src/translations/en.json)

I couldn't reproduce it in other computer or browsers, but this is the second user that complains about this string display problem.
Adding `DefaultMessage` where it's missing would at least show always the english translation instead of the `id` but I'd like it to work in other languages as well! 

Any help would be really appreciated,
Thank you

#### Computer from user with problem (display problem)
| windows 10 pro education | |64 bits|
| chrome browser Version 78.0.3904.97 (Official Build) (64-bits) |

#### My computer (no problem)
| MacOS Mojave 10.14.1 | |64 bits|
| chrome browser Version 80.0.3987.116 (Build officiel) (64 bits) |

**Comment by longlho** [comment]
Do you have stack traces? Are you sure they all got the latest version of the translations?

**Comment by luknl** [comment]
@longlho thanks for the quick answer. No stack traces. And yes, those 2 screenshots were done on the same day.

**Comment by longlho** [comment]
That seems like whatever the messages blob that got sent to that client is missing those IDs

**Comment by luknl** [comment]
Do you have any idea why? Did something similar already happened?

**Comment by longlho** [comment]
what I've seen people typically do is to log missing translations to they can gauge how often this happens, might tie back to https://github.com/formatjs/react-intl/issues/1573

**Comment by longlho** [comment]
We've added more logging in 4.1.1 that can help you debug this

**Comment by luknl** [comment]
Thank you, we'll take a look and let you know!
