### ISSUE TITLE
Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by maystrenkoYurii** [formatjs/formatjs#1596]
"node": "13.10.1",
"react-intl": "4.1.1",
![Снимок экрана от 2020-03-07 16-17-23](https://user-images.githubusercontent.com/23016311/76145120-38566f80-608f-11ea-837c-70ab794ec845.png)
![Снимок экрана от 2020-03-07 16-17-49](https://user-images.githubusercontent.com/23016311/76145121-39879c80-608f-11ea-8d99-b9e87bbf626d.png)

**Comment by jfhenon** [comment]
I don't really like the solution but as a temporary workaround, I added a random key: 
```
values={{
     p: (...chunks) => <p key={Math.random()}>{chunks}</p>,
}}
```

**Comment by czabaj** [comment]
@jfhenon duplicate of https://github.com/formatjs/react-intl/issues/1467

**Comment by longlho** [comment]
duplicate of #1467
