### ISSUE TITLE
preact-i18n <Text> support

### ISSUE THREAD

**Issue by drzraf** [formatjs/formatjs#1604]
I need to integrate components built on preact in a project (a Gutenberg block) based on React.
These preact components make use of [`<Text>`](https://github.com/synacor/preact-i18n#text), but current React `IntlProvider` can't cope with them.

**Describe the solution you'd like**
I'd be more than happy to see react-intl supporting translations from preact-i18n based components and even more if these two i18n implementations could find some room for interoperability.

**Additional context**
https://github.com/synacor/preact-i18n/issues/9

**Comment by longlho** [comment]
The short answer unfortunately is no :( preact-i18n does not use ICU syntax, which makes it incompatible w/ our MessageFormat
