### ISSUE TITLE
Test coverage with FormattedMessage

### ISSUE THREAD

**Issue by naheller** [formatjs/formatjs#1606]
Hello `react-intl`!

I've been using your package to great effect and I appreciate the work you're all doing.

Recently I've been taking advantage of `FormattedMessage`'s function-as-child pattern to render translated text in DOM elements that require attributes like `className`:

```
<FormattedMessage id="greeting">
  {text => <h2 className="myClass">{text}</h2>}
</FormattedMessage>
```

This works great, however Jest/Enzyme reports that code inside the curly braces is not tested, even with snapshots for the whole component. Do you know how I might cover that code with a test?

Thanks!

**Comment by longlho** [comment]
did you shallow render?
