### ISSUE TITLE
FormattedRelativeTime onChange callback

### ISSUE THREAD

**Issue by flangeratlassian** [formatjs/formatjs#1608]
**Is your feature request related to a problem? Please describe.**
I have a FormattedRelativeTime that updates every 30 seconds, and I have a corresponding component that changes color if the time hits several break points (eg change from green to red if time > 10 minutes). Currently it does not change color upon those changes.

**Describe the solution you'd like**
I'd like an onChange callback as a prop to FormattedRelativeTime that is called when it is updated. I know you do some optimizations in it (`src/components/relative.tsx`) such as not rerendering the units when they don't change, so I think this addition to the API is the only way to preserve that while allowing me to update other components as well.

**Describe alternatives you've considered**
An alternative is having my own setTimeout with the same interval and updating my other components there, but this is not as nice and does not capture the intent in the code as well (leading to messier code).

**Additional context**

**Comment by longlho** [comment]
The historical context is that self-update `FormattedRelativeTime` support is primarily for backwards compatibility and not something we're interested in extending ourselves. Self-updating turns `FormattedRelativeTime` into a stateful uncontrolled component which isn't ideal.

With that said I'm open to a PR to add `onChange`, I just don't have the bw rn :)
