### ISSUE TITLE
Ability to call formatting API without wrapping a component with InjectIntl() in class components

### ISSUE THREAD

**Issue by Masahiro2525** [formatjs/formatjs#1609]
**Is your feature request related to a problem? Please describe.**
Our project is fairly huge and already contains wrapped components by one another so we really do **not** want to use InjectIntl() to wrap class components to use formatting API (it also breaks some tests as well). 

**Describe the solution you'd like**
It would be great if we could just import intl from 'react-intl' and "intl.API" to call the API ( like intl.formatMessage) 
**OR**
Is there any way to call Formatting API without using InjectIntl() for class components? possibly with createIntl()?

**Describe alternatives you've considered**
At least simpler and less complicated way to use formatting API in class components 

**Additional context**
This complexity of InjectIntl() makes it very to use React Intl in a big project. We are about to use other libraries just because we do not want to use InjectIntl(), but the rest of the library and related babel-plugins are very good so if possible I would like to keep using React-Intl.

**Comment by longlho** [comment]
you can use our React hook `useIntl` as well.

**Comment by Masahiro-Toyomura** [comment]
> you can use our React hook `useIntl` as well.

I believe useIntl is only for functional component.

**Comment by longlho** [comment]
We do export `IntlContext` so technically you can get the `Consumer` out of that.  Would that work for you?

The `intl` object from `react-intl` is a cached instance of several thing, including `locale` so it's not something we can export out statically. That falls on the user land.
