### ISSUE TITLE
Result of unit test always “Received:0” with "shallowWithIntl"

### ISSUE THREAD

**Issue by wiemkhardani** [formatjs/formatjs#1612]
Unit test code cannot read component "jsx" content the test result is always "Received: 0"
This is a screenshot of the unit test result using enzyme and jest with react.js
[https://stackoverflow.com/questions/60929210/result-of-unit-test-always-received0](url)

**Comment by longlho** [comment]
This is not related to react-intl but rather either enzyme or React issue it looks like.
