### ISSUE TITLE
Use a proxy for messages in order to know when trying to access a missing key

### ISSUE THREAD

**Issue by guico33** [formatjs/formatjs#1618]
**Is your feature request related to a problem? Please describe.**
When a message is missing, if there's no fallback available it crashes your application. Subsequent debugging can be tricky as you don't know which which message is the cause.

**Describe the solution you'd like**
Use a proxy on the messages so we know when there's an attempt to access a missing key.

```js
const messagesProxy = new Proxy(messages, {
  get: (target, key) => {
    if (target[key] === undefined) {
      console.error('MISSING INTL MESSAGE IN FILE:', key);
      // custom error reporting here
    }
    // we can follow the usual behaviour
    // or return something else if the key isn't there
    return target[key];
  },
});
```

I am not at all familiar with the internals of `react-intl` and am unsure at which level this could be implemented. In userland, one can write a wrapper for `defineMessages`. 

**Update**
It seems like the solution I orinally proposed doesn't work, though a similar behaviour can still be achieved another way. See https://github.com/formatjs/react-intl/issues/1618#issuecomment-612137689

**Comment by JustFly1984** [comment]
I have same issue. We have issues when error messages from fetch requests are leaking into <FormattedMessage id prop, and we can't provide default message, since there is no default message possible, cos so much variations. Would love to see the actual value passed in error message, so we could track what is missing. We had tracked down ""Failed to fetch" browser error slipped in as id, but there is definitely much more variants of errors in different languages and different browsers. 
We are using Sentry, and it is not possible to resolve an issue just looking at error messages logs.

+1

Thank you for great work on the project!

**Comment by guico33** [comment]
As a follow-up to my original post, it seems like the solution I suggested is not viable. My build crashes, and I'm guessing it's because of how the calls to `defineMessages` are used to collect messages.

We're still testing but what seems to be working fine is: instead of using directly the object returned by `defineMessages`, use a proxy instead. 
For instance, we normally define messages for each component in a separate file and default export them. Now, instead of `export default messages`, we would write `export default makeSafeMessages(messages)`. `messages` is the object returned by `react-intl`'s `defineMessages`. `makeSafeMessages` returns the proxy.

**Comment by longlho** [comment]
when there's missing translation we trigger `onError` with the MISSING_TRANSLATION error that contains the message descriptor. Is that not what you guys are looking for?

**Comment by guico33** [comment]
Does it let you know which key is missing?

**Comment by longlho** [comment]
It echoes out the message descriptor object so it should have `{id, defaultMessage, description}`

**Comment by guico33** [comment]
That doesn't help, the issue is when the id is missing. That'd happen most of the time when you select a message dynamically based on a variable, in which case it's easy to oversee some possibilities. 
If there's no message for a certain key, by default your application will crash, and as far as I know `react-intl` won't tell you which key is missing.

**Comment by longlho** [comment]
are you talking about [this](https://github.com/formatjs/react-intl/blob/master/src/formatters/message.ts#L137)?

**Comment by guico33** [comment]
The error I am talking about is `Invariant Violation: [React Intl] An id must be provided to format a message.`.

It seems like this issue was already raised in https://github.com/formatjs/react-intl/issues/1059 but nothing actionable came out of it.

**Comment by longlho** [comment]
I don't think I understand your use case. You pass react-intl the `MessageDescriptor` that has the ID so shouldn't you know before passing in whether that `MessageDescriptor` has the ID or not?

**Comment by guico33** [comment]
You do not always know. Code is added, removed. As I explained before, the messages' ids can also be defined dynamically.

I believe in a large scale application this problem is very easy to come by. 
We also use Sentry for error reporting at my company and for our web application the above error is the most common we get in production.

**Comment by longlho** [comment]
I mean I have never seen this issue in both Yahoo and Dropbox and both have large-scale application. If you're dynamically generating ID you'd get a MISSING_TRANSLATION error as I mentioned. If you're not generating an ID at all there seems to be some other issue in your workflow that's outside the scope of this library.

**Comment by guico33** [comment]
I'll try to give a more concrete example in case it is still not clear enough. Your API returns a `schedules` array. Each schedule can have a frequency which can have the value `'DAILY'`, `'WEEKLY'`, `'MONTHLY'`.
Your messages are defined as 
```js
const messages = defineMessages({ DAILY: 'Daily', MONTLY: 'Monthly' })
```
In your component you have something like 
```js
{schedules.map(s => <FormattedMessage {...m[s.frequency]} />)}
```
Here it will likely crash for multiple reasons, `MONTLY` has a typo, `WEEKLY` is absent from messages. If `frequency` is undefined it will also crash.

Exhaustive testing might caught that but you you might still miss something.

**Comment by longlho** [comment]
It'll crash when you don't give it an ID so `m[s.frequency]` would be `undefined`, shouldn't you do `filter` before passing it in? Even in this case, what `FormattedMessage` get would be `undefined` or `{}`, even if we echo that back, you'll get `undefined` or `{}` so I'm not sure how useful that would be?

Do you have a concrete proposal here? `When a message is missing, if there's no fallback available it crashes your application.` is not correct. We only crash when you don't give us an ID. Otherwise the fallback hierarchy is `defaultMessage -> ID -> ''`.

**Comment by guico33** [comment]
> It'll crash when you don't give it an ID so m[s.frequency] would be undefined, shouldn't you do filter before passing it in?

Probably you should have a conditional to display a different copy if the `frequency` is undefined. 
In the real world though, you sometimes forget about edge cases, or you're dealing with a third party API and you're not sure about all the different possibilities. I also gave two more examples of case other than `frequency` being undefined. 
You can indeed check if the messages exist before passing it to your `react-intl` function or component but I'd like to have a way for this to be handle globally.

> When a message is missing, if there's no fallback available it crashes your application. is not correct. We only crash when you don't give us an ID. Otherwise the fallback hierarchy is defaultMessage -> ID -> ''.

My issue is when you pass `undefined` instead of a message. That typically happens when you try to access a missing key on your `messages` object. Then the application will crash. In addition debugging can be difficult as you need to find where that happened. 
Usually that involves checking all the messages used in your component, matching them with the keys in your `messages` object to see if there is any missing. In the case the key is a variable it can be even more tricky.

> Do you have a concrete proposal here?
It's in my first post. I don't know how messages are handled internally by the library but _somewhere_ they could be wrapped in a proxy that will enable logging/error reporting when accessing an undefined property. When setting up `react-intl`, a callback can be passed taking the key as an argument. A function returning a fallback could also be passed (also taking the key as an argument) so it would be used instead of raising an exception (which might or not be wanted depending).
I'd need to get to know more about the library's internal for anything more concrete.

**Comment by guico33** [comment]
I see there's [eslint plugin](https://www.npmjs.com/package/eslint-plugin-formatjs) mentioned in https://github.com/formatjs/react-intl/issues/1059. I'm not sure how helpful it is but it seems like it could help so I'll give it a try.

**Comment by longlho** [comment]
`That typically happens when you try to access a missing key on your messages object.` Hmm that's not how it works. Again as I mentioned, if you give us an ID, even if the message is missing for that ID, it won't crash. If you give us `<FormattedMessage {...a} />` where `a` is `undefined` it will crash and there's nothing we can do. Also you pass us the `messages` object as well so you can proxy there. The library won't instrument `messages` for you.

The linter only helps when you declare messages statically in your source code, not for dynamic cases.

**Comment by JustFly1984** [comment]
Is there a way to set the flag to do not crash an app, and display some fallback string, easily searchable in interface? This could improve DX and UX. Still Error should be thrown, with stack trace included, but it should not crash an app in production.

**Comment by longlho** [comment]
There is currently no way to do that and we haven't received enough asks to support it unfortunately

**Comment by zjye-idealhub** [comment]
> **Is your feature request related to a problem? Please describe.**
> When a message is missing, if there's no fallback available it crashes your application. Subsequent debugging can be tricky as you don't know which which message is the cause.
> 
> **Describe the solution you'd like**
> Use a proxy on the messages so we know when there's an attempt to access a missing key.
> 
> ```js
> const messagesProxy = new Proxy(messages, {
>   get: (target, key) => {
>     if (target[key] === undefined) {
>       console.error('MISSING INTL MESSAGE IN FILE:', key);
>       // custom error reporting here
>     }
>     // we can follow the usual behaviour
>     // or return something else if the key isn't there
>     return target[key];
>   },
> });
> ```
> 
> I am not at all familiar with the internals of `react-intl` and am unsure at which level this could be implemented. In userland, one can write a wrapper for `defineMessages`.
> 
> **Update**
> It seems like the solution I orinally proposed doesn't work, though a similar behaviour can still be achieved another way. See [#1618 (comment)](https://github.com/formatjs/formatjs/issues/1618#issuecomment-612137689)

This help me a lot, thanks !

**Comment by marcesengel** [comment]
> I'll try to give a more concrete example in case it is still not clear enough.
> 
> Your API returns a `schedules` array. Each schedule can have a `frequency` which can have the value `'DAILY'`, `'WEEKLY'`, `'MONTHLY'`.
> 
> Your messages are defined as
> 
> ```js
> const messages = defineMessages({ DAILY: 'Daily', MONTLY: 'Monthly' })
> ```
> 
> In your component you have something like
> 
> ```js
> {schedules.map(s => <FormattedMessage {...m[s.frequency]} />)}
> ```
> 
> Here it could crash for multiple reasons: `MONTLY` has a typo, `WEEKLY` is absent from `messages`. If `frequency` is undefined it will also crash.
> 
> Exhaustive testing might catch that but I believe overseeing a case is not unlikely either. The consequence is quite severe as your application will crash. Fixing the bug isn't always straightforward as you don't know which missing id is responsible.

Just create a missing translation wrapper:
```js
const ensureMessage = (msg) => {
  if (typeof msg === 'object' && typeof msg.id !== 'undefined')
    return msg

  // do error reporting here
  // if wanted return a fallback message
  return {
    id: 'missing_translation_message',
    defaultMessage: 'missing translation'
  }
}
```

> ```js
> {schedules.map(s => <FormattedMessage {...m[s.frequency]} />)}
> ```

Would then be
```js
{schedules.map(s => <FormattedMessage {...ensureMessage(m[s.frequency])} />)}
```

`ensureMessage` should then only be used for dynamic access, static errors should be caught by UI testing.
