### ISSUE TITLE
Unable to use injectIntl in imported components

### ISSUE THREAD

**Issue by joshsylvester** [formatjs/formatjs#1620]
### Simple use case

A React application with a shared component library. Both libraries have `react-intl` as a dependency. The application provides the `IntlProvider`, and the component library passes the `intl` to the form components (or other components) as needed via `injectIntl()`. Everything works as expected with `react-intl@2.9.0`, but completely breaks with `react-intl@3.0.0`. Newer versions (all the way up to current) have the same issue. (tested w/ `3.0.0`, `3.12.1`, `4.0.0`, `4.3.1`)

Simple `index.js`:
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
ReactDOM.render(<App />, document.getElementById('root'));
```

Here's a simplified `App.js`:

```
import React from 'react';
import { IntlProvider } from 'react-intl';
import { IntlTextField } from '@private/component-library';

const intlMessages = {};

const App = () => (
  <IntlProvider locale="en" messages={intlMessages}>
     <IntlTextField name="test" />
  </IntlProvider>
);

export default App;
```

And an extremely simplified component library, which is published as a private npm repository, and shares the same versions of `react`, and `react-intl`
```
import React from 'react';
import { injectIntl } from 'react-intl';
const TextField = ({ name, intl }) => (
  <input type="text" name={name} placeholder={intl.formatMessage({id: 'placeholder'})} /> 
);
export const IntlTextField = injectIntl(TextField);
```

### Expected behavior
Input field renders as expected - if the `messages` object does not contain a key for 'placeholder', `react-intl` throws a warning message in the console, and uses the string instead

### Current behavior
>  [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

### Caveat

The same code - without the imported component (where all the code is in the same codebase) renders fine and works as expected even up to the current version.

```
import React from 'react';
import { injectIntl, IntlProvider } from 'react-intl';

const intlMessages = {};

const TextField = ({ name, intl }) => (
  <input type="text" name={name} placeholder={intl.formatMessage({id: 'placeholder'})} /> 
);
const IntlTextField = injectIntl(TextField);

const App = () => (
  <IntlProvider locale="en" messages={intlMessages}>
     <IntlTextField name="test" />
  </IntlProvider>
);

export default App;
```

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | `2.9.0`, `3.0.0-latest` |
|      `npm ls react` | `16.13.1` |
|     `npm --version` | `6.9.0` |
|    `node --version` | `v10.16.3` |

**Comment by longlho** [comment]
Do you have a codesandbox.io to repro?

**Comment by joshsylvester** [comment]
CodeSandbox: https://codesandbox.io/s/react-intl-imported-injectintl-ol1go

the non working example requires either something published to npm or being able to import from another codesandbox.io sandbox, which codesandbox doesn't support. i'm working on getting something up on npm.

**Comment by czabaj** [comment]
I came across this problem in our monorepo with yarn workspaces.

The shared components library  _must not install `react-intl` as dependency_. I think the reason it worked with older version is old React context API. New React context API rely on _same reference_. You project instantiates react context from different `node_modules` thus contexts are not same reference. This also means you are bundling react-intl twice in your application.

The solution is to remove `react-intl` from shared components repo. Defining it as `peerDependency` is a good convention, but is not necessary. It will just guard version mismatch in end-projects. Your shared component repo also _must not_ install `react`, `react-dom` and other libraries used in end-project. _It shall only install dependencies which are considered private in that library_ e.q. if your component library provides select form input and it relies on `react-select` and you are certain that `react-select` is not imported elsewhere in the end project, you are free to install `react-select` in the shared component library. Other dependencies, which will surely be used in end (dependant) project, must not be installed.

This is big pain for testing, storybook etc. because you are not able to run your library code from the library repo. You must either create sub-project in library, with its own `node_modules` which wont be found by node resolution algorithm, or patch module resolution config in testing or storybook configs (which we are using in our monorepo and I'm not very happy with it, but it servers its purpose).

**Comment by caraclarke** [comment]
Hello, I am running into the same issue as above with a few ongoing issues. I also have a shared component library within a monorepo that is imported into different features. However, my `IntlProvider` lives in my shared components library and we import a component called `AppShell` that includes any needed providers (including intl) that wraps the top level of every feature (combination of imported shared and local unique components in a separate part of the repo).

I followed the advice given above and removed the `react-intl` dependency from my shared component libraries `package.json`. This solved most of my issues with a few caveats. Note, all examples below are using a feature folder with react-intl version 4.5.1, and a shared component library having no version of react-intl installed

### Fix attempt 1
If I try to use the `injectIntl` HOC from `react-intl` the component will not render on the page and I get the following errors
<img width="543" alt="Screen Shot 2020-05-11 at 11 52 14 AM" src="https://user-images.githubusercontent.com/12741704/81584360-a580cc80-9380-11ea-88e1-b5fc959831ca.png">
<img width="553" alt="Screen Shot 2020-05-11 at 11 52 24 AM" src="https://user-images.githubusercontent.com/12741704/81584361-a6b1f980-9380-11ea-850f-b1e67b6681d6.png">


code example (AppShell wrapper component lives in the top level `ReactDOM.render` function):
```
import React, { Component, Fragment } from 'react';
import { FormattedMessage, injectIntl } from 'react-intl';

// shared component library
import { Alert } from '@shared/components/alert';
// component custom to feature, also can contain shared components
import WorkspaceListContainer from './workspaceListContainer';
import messages from './messages';

export class AppLifecycleMenu extends Component {
  static propTypes = {...};
  static defaultProps = {...};

  render() {
    const {
      display,
      name
    } = this.props;

    const deleteAlertTitle = this.props.intl.formatMessage(
      messages.deleteAlertTitle,
      { alertName: name }
    );

    return (
        <Fragment>
            <WorkspaceListContainer />
            <Alert
                show={display}
                title={deleteAlertTitle}
                okButtonText={<FormattedMessage {...messages.deleteOkButton} />}
                cancelButtonText={<FormattedMessage {...messages.deleteCancelButton} />}
            >
                <p>
                    <FormattedMessage {...messages.deleteAlertBody} values={{ alertName: name }} />
                    <FormattedMessage {...messages.deleteAlertBodyTwo} />
                </p>
            </Alert>
      </Fragment>
    );
  }
}

export default injectIntl(AppLifecycleMenu);
```

Note, in a lot of our shared components, `intl` messages can be passed in as props and some components are wrapped in their own `injectIntl` HOC to intl default versions of props (like a default button label).

### Fix attempt 2
However, if I import an `injectIntl` helper we have in our shared resource library, the component renders but still displays an error message:

injectIntlHelper code:
```
// only apply intl in non-test environments
export  default  Component  => process.env.NODE_ENV  ===  TEST_ENV  ?  Component  :  injectIntl(Component);
```

code example (AppShell wrapper component lives in the top level `ReactDOM.render` function):
```
import React, { Component, Fragment } from 'react';
import { FormattedMessage, injectIntl } from 'react-intl';

// shared component library
import { Alert } from '@shared/components/alert';
import injectIntl from '@shared/utilities/injectIntl';
// component custom to feature, also can contain shared components
import WorkspaceListContainer from './workspaceListContainer';
import messages from './messages';

export class DeleteWorkspaceAlert extends Component {
  static propTypes = {...};
  static defaultProps = {...};

  render() {
    const {
      display,
      name
    } = this.props;
    const deleteAlertTitle = this.props.intl.formatMessage(
      messages.deleteAlertTitle,
      { alertName: name }
    );

    return (
        <Fragment>
            <WorkspaceListContainer />
            <Alert
                show={display}
                title={deleteAlertTitle}
                okButtonText={<FormattedMessage {...messages.deleteOkButton} />}
                cancelButtonText={<FormattedMessage {...messages.deleteCancelButton} />}
            >
                <p>
                    <FormattedMessage {...messages.deleteAlertBody} values={{ alertName: name }} />
                    <FormattedMessage {...messages.deleteAlertBodyTwo} />
                </p>
            </Alert>
      </Fragment>
    );
  }
}

export default injectIntl(AppLifecycleMenu);
```
component tree with intlprovider:
<img width="548" alt="Screen Shot 2020-05-11 at 10 25 51 AM" src="https://user-images.githubusercontent.com/12741704/81584152-62bef480-9380-11ea-8445-31d85aa46065.png">

Error message:
<img width="546" alt="Screen Shot 2020-05-11 at 11 54 57 AM" src="https://user-images.githubusercontent.com/12741704/81584301-93069300-9380-11ea-92a1-35d594cb5017.png">

### Fix attempt 3
I also tried only having `react-intl` installed in the shared resource library but that results in this error message
<img width="556" alt="Screen Shot 2020-05-11 at 12 08 28 PM" src="https://user-images.githubusercontent.com/12741704/81584134-59ce2300-9380-11ea-8c1b-0dc5e959366d.png">

### Environment
I have tried going down versions in react-intl, but this issue persists back down into the 3.0 and up versions
Executable | Version
-- | --
npm ls react-intl | 2.3.0 -> 4.5.1
npm ls react | 16.13.1
npm --version | 6.11.2
node --version | v11.10.1

I've been trying different combinations and looking online for a few days, are there any other changes I can make to get rid of these errors? Is anything jumping out as something I am missing adding or updating between versions?

**Comment by nikitarium** [comment]
@czabaj thanks a lot, you saved my day! 👍 🚀

**Comment by lavor** [comment]
If you can ensure that your shared library and your consumer application have the same version of `react-intl`, you can make it working without removing `react-intl` from shared library depedencies.

After call of `npm dedupe` you will have only single instance of the library and that setup is working correctly.

**Comment by MKShwetha** [comment]
Hi @czabaj czabaj & @nikitarium & all ,
I am facing same issue as you both have mentioned. I have a shared component library where I need to use react-intl as translation api, through the main application where react-intl api is initialized. But I am not able to make this work using the suggestions you have provided. Can any of you pls. share an example of how patch module can be done in shared library repo, or how can this be resolved where we can translate text in component library as well as main application using one instance of react-intl? 
Thank you.

**Comment by damiangreen** [comment]
I'm facing this issue with our PNPM monorepo, as soon as we move components into helper packages we get [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
We dont have react-intl installed in child packages however.
