### ISSUE TITLE
RichText: Pass single valid `ReactNode` argument to `formatXMLElementFn`

### ISSUE THREAD

**Issue by czabaj** [formatjs/formatjs#1623]
Index:
* `formatXMLElementFn` -- a function handling rich text formatting, passed to `values`. Name is used as referred in source code,

## The problem

While using RichText, `formatXMLElementFn` are called with possible many arguments (chunks) which could be collected with rest operator and passed to component.

Example

```JavaScript
<FormatMessage
  defaultMessage="This is <i>example</i>."
  values={{
    i: (...chunks) => <i>{chunks}</i> // <- rest operator here
  }}
/>
```

It is said, that

> The reason behind this is that chunks can contain both string & ReactElement so we cannot merge them into a single argument like string concatenation.
— [source ~ Component docs](https://github.com/formatjs/react-intl/blob/master/docs/Components.md#rich-text-formatting)

So more chunks are (probably) only created when rich texts are nested like

```
"This is <b>an example <i>of nested</i> rich texts</b>."
```

Where into `b` is passed result of formatting `an example <i>of nested</i> rich texts` which translates into chunks

```
[
  "an example ",
  React.createElement("i", {}, "of nested"),
  " rich texts",
]
```

If no nested rich text is used, `formatXMLElementFn` could be declared simply without rest operator

```JavaScript
<FormatMessage
  defaultMessage="This is <i>example</i>."
  values={{
    i: (chunk) => <i>{chunks}</i> // <- rest operator is not needed here
  }}
/>
```

This situation has two drawbacks
* decision to use or not to use rest is error prone and hard to catch, when user nests rich text and forgets to change `(chunk)` to `(...chunks)` then translation will work, but will only display first `chunk` and user might miss that,
* using rest operator brings *Each child in a list should have a unique "key"* problem as described in #1467 

So using rest operator brings a great deal of complexity, while don't using rest operator all the time brings great risk of escaped bugs.

## The solution

Merge chunks in `react-inlt` library into single `React.ReactNode`. Then `formatXMLElementFn` will always be called with single argument. No need for rest operator, and we can solve the *Each child in a list should have a unique "key"* problem also.

We can merge the chunks like this

```TypeScript
function mergeChunks(chunks: Array<string | React.ReactElement>): React.ReactNode {
  return chunks.length = 1 ? chunks[0] : React.Children.toArray(chunks)
}
```

NOTE: `React.Children.toArray`
> Returns the children opaque data structure as a flat array with keys assigned to each child.
— [source ~ React Top-Level API](https://reactjs.org/docs/react-api.html#reactchildrentoarray)

This will produce `string | React.ReactElement | Array<string | React.ReactElement>` as a single value with unique keys set when result is an array. Then we need to patch `formatXMLElementFn`.

The `formatXMLElementFn` are passed and handled in `intl-messageformat`, which is React agnostic. Therefor we must solve the problem in `react-intl` library. We can for example create high order `formatXMLElementFn` which merges variadic arguments and wrap all `formatXMLElementFn` with this HO function.

Proposed implementation

```TypeScript
// uses function mergeChunks from above

type VariadicFormatXMLElementFn<T> = (
  ...args: Array<string | T>
) => string | Array<string | T>;

type NonVariadicFormatXMLElementFn = (
  chunk: React.Node,
) => React.Node

function applyFormatXMLElementFn(
  formatXMLElementFnFromValues: NonVariadicFormatXMLElementFn
  ): VariadicFormatXMLElementFn<React.Element> {
  return (...chunks) => formatXMLElementFnFromValues(mergeChunks(chunks))
}
```

This will convert all non-variadic `formatXMLElementFn` into variadic, so users can provide non-variadic functions in values, we transform them into variadic and pass them into intl-messageformat.

## Worth noting
* this would be a breaking change for react-intl, although it should not break existing code, because current usages with or w/o rest operator shall continue to work,
* this will cause API mismatch between `react-intl` and `intl-messageformat` -> signature of `formatXMLElementFn` will vary, which again, shouldn't be big issue, 
* this could have performance implication but I anticipate it very low,

**Comment by longlho** [comment]
Does `wrapRichTextChunksInFragment` config solve this issue?

**Comment by czabaj** [comment]
@longlho I'll test it, but [from the source code](https://github.com/formatjs/formatjs/blob/7bfc5c085b13915be7b95d0a9e2284167faa6375/packages/react-intl/src/formatters/message.ts#L75) it seems it wraps the _result of `formatMessage()` into `ReactFragment`_, but it does not affect the arguments of `formatXMLElementFn` because `formatXMLElementFn` is handled inside `intl-messageformat`.

**Comment by longlho** [comment]
kk I'm open to a PR if you're interested :)

**Comment by czabaj** [comment]
@longlho I created a PR with proposed solution. Sorry for such a long silence. I was drowned in other work (shame on me for prioritizing non open-source work projects).
