### ISSUE TITLE
Pass default values to IntlProvider

### ISSUE THREAD

**Issue by tictcotq** [formatjs/formatjs#1630]
**Is your feature request related to a problem? Please describe.**
In scope of project it's very common to have `{br}`, `<em>...</em>` etc in many localised strings. However, it is currently necessary to pass those as `values` in every occurrence of `<FormattedMessage />` or `formatMessage` where those values are expected. This is quite repetitive.

**Describe the solution you'd like**
Allow to pass default values as prop of `<IntlProvider />`. These default values should be merged with values passed in place of usage.

**Describe alternatives you've considered**

**Additional context**

**Comment by longlho** [comment]
This can actually be solved in user space by either create a wrapper around `FormattedMessage` or create your own `Provider`. I'll keep this open to see if there's enough interests we might consider adding this capability into the library
