### ISSUE TITLE
Possibility to extend formatters?

### ISSUE THREAD

**Issue by erictheswift** [formatjs/formatjs#1636]
Words passed as parameters should be capitalized/lowercased depending on translation.

We're using message formats as the only source of translations.
It would be great to extend built-in formatters `select`, `plural` with own ones, like `lowercased`, `capitalized`.

I see this change would also involve `intl-messageformat-parser` package.
Do you think it's a good idea?

**Comment by longlho** [comment]
This use case should be handled by our skeleton support + numberformat es2020 polyfill

**Comment by anosov-otg** [comment]
@longlho how can I specify currency dynamically using skeleton formatting?

No problem (from documentation):
```
The price of this bagel is {num, number, ::sign-always compact-short currency/GBP}
```

Problem: I don't know the currency at this point, it must be dynamic. This format doesn't work:
```
The price of this bagel is {num, number, ::sign-always compact-short currency/{currency}}
```

**Comment by longlho** [comment]
You cannot. You'll have to format it as a passed in values
