### ISSUE TITLE
Support formatMessage extraction through imported hook

### ISSUE THREAD

**Issue by manuhornung** [formatjs/formatjs#1639]
**Which package?**
`babel-plugin-react-intl`

**Is your feature request related to a problem? Please describe.**
We are using a lot of tooling around react-intl to automatically generate message IDs from defaultMessages so that we don't have to manually clean them up and keep them in sync.

This doesn't yet work for all the imperative, non-Component use-cases which go through `defineMessages` because the message descriptors need to be explicitly named for later reference. This also forces us to keep the `defaultMessage` separated from the point where it is actually referenced.

**Describe the solution you'd like**
Could we use a new custom hook which is an explicit import from `react-intl`, just like the components and `defineMessages`, and then **extend the plugin to also support directly extracting messages from it instead of going through `defineMessages`**?

Something like
```
import { useIntl } from 'react-intl';

function MyComponent() {
  const { formatMessage } = useIntl();

  const formattedLabel = formatMessage({ defaultMessage: 'Click me!' });
  return <Button stringOnlyLabel={formattedLabel} />;
}
```

**Describe alternatives you've considered**
I'm aware that there is already the option to support almost the same, albeit without destructuring, using `extractFromFormatMessageCall` like this:
```
import { useIntl } from 'react-intl';

function MyComponent() {
  const intl = useIntl();

  const formattedLabel = intl.formatMessage({ defaultMessage: 'Click me!' });
  return <Button stringOnlyLabel={formattedLabel} />;
}
```
But I would like to explore the import-based approach because:
- It is **more reliable and could be activated by default** as opposed to the more fragile check for the `intl.` prefix behind `extractFromFormatMessageCall`
- Destructuring is a common pattern also advocated by many eslint presets but isn't usable with the current solution

I also thought about directly going with something like `useFormattedMessage`, which might be much easier to extract, but it could also feel very unintuitive at the same time when combined with conditional rendering:
```
import { useFormattedMessage } from 'react-intl';

function MyComponent({ isLoading, errorWasCaught }) {
  // Rules of hooks force you to always use all possible messages
  const loadingText = useFormattedMessage({ defaultMessage: 'Loading...' });
  const finishedText = useFormattedMessage({ defaultMessage: 'Done!' });
  const errorText = useFormattedMessage({ defaultMessage: 'Error!' });

  if (errorWasCaught) {
    return <Error message={errorText} />;
  }

  return <Progress label={isLoading ? loadingText : finishedText} />;
}
```

**Additional context**
I understand that `defineMessages` is a no-op which was introduced to facilitate extraction of translation keys using this babel plugin. With the introduction of imported hooks, this might not be necessary anymore.

**Comment by longlho** [comment]
I believe this is handled in the latest version of babel-plugin-react-intl & our CLI
