### ISSUE TITLE
FormattedMessage doesn't reflect locales

### ISSUE THREAD

**Issue by stanekpa** [formatjs/formatjs#164]
I have this simple test (locale 'cs-CZ'):

``` javascript
<FormattedMessage
  message="{count, plural, one{# ONE} few{# FEW} many{# MANY} other{# OTHER}}"
  count={2}
/>
```

test returns '2 OTHER', but according to [Language Plural Rules](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#cs) for number between 2-4 it should return '2 FEW'.

Locales are initialised property, because FormattedDate returns date in czech locales.

**Comment by ericf** [comment]
We have an example on the formatjs.io website that works correctly with `cs-CZ`. My bet is that you're not loading the `cs.js` locale data file into the browser. And if you're using a browser like Firefox or Chrome for testing, they already have the locale data built in for number and date/time formatting.

If you are loading the locale data, then please re-open this issue.

**Comment by stanekpa** [comment]
You have right. It was my fault. I forget load locale file.

Thank You.
