### ISSUE TITLE
Translations not found when extracting Formatted Messages - use case Next.js with dynamic paths

### ISSUE THREAD

**Issue by BramDecuypere** [formatjs/formatjs#1646]
**Which package?**
`@formatjs/cli`

**Describe the bug**

Unable to extract component that are under a path with `[square brackets]` inside of it.
This has been used by next.js as a pattern for dynamic routing. Although not perfect, it seems as though the cli is unable to handle 
`<FormattedMessage id="contact.title" defaultMessage="My contact page"/>`

**To Reproduce**

1. Create a path under the scanned source files for abstractions
2. Generate the language files
3. Don't find the message back in the files

The way I checked it was to change my square brackets to a regular path (folder) `[lang] --> lang` to check if it found the formatted messages now and it did.

**Expected behavior**
Find the formatted messages, even under paths with special characters like square brackets

**Additional context**
Next.js version - `"next": "^9.3.3"`

**Comment by longlho** [comment]
stale
