### ISSUE TITLE
intl-messageformat: String formatter

### ISSUE THREAD

**Issue by joeyhub** [formatjs/formatjs#1648]
intl-messageformat 8 and onward removes the ability to format a raw string and instead attempts to parse as HTML.

Not only are not all strings HTML or XML but might look like it, support for HTML is limited so it does not work in all cases.

This is also a major deviation from ICU which does not make assumptions about strings and parses them only as ICU.

Is there any rationale for this change? It makes the library much harder to use.

**Comment by marcesengel** [comment]
To be honest I can understand your concerns; however I think this is not the scope of this package - whether you and I like it or not.

This is a package to use `intl-messageformat` within React, meaning we'll have to stick to what they do.

Are there any problems occurring with the idea of dependency version locking @longlho proposed?

**Comment by longlho** [comment]
fixed in #1699
