### ISSUE TITLE
babel-plugin-react-intl: Allow to override cwd with an option

### ISSUE THREAD

**Issue by bertho-zero** [formatjs/formatjs#1649]
**Which package?**
babel-plugin-react-intl

**Is your feature request related to a problem? Please describe.**
My build webpack build the modules of monorepo directly from the sources, the problem is that the `babel-plugin-react-intl` uses the `process.cwd()` rather than the path of the config used. The construction of the relative path is wrong.

![image](https://user-images.githubusercontent.com/8525267/80110617-29644780-857f-11ea-8c10-7893f520c875.png)

**Describe the solution you'd like**
The solution would be to be able to override the `cwd` from the `.babelrc.js` file with `cwd: __dirname`

**Describe alternatives you've considered**
I made a custom preset to ignore this plugin when the caller is a `babel-loader`.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by pyrocat101** [comment]
@bertho-zero if you are already using `.babelrc.js`, have you tried specifying the absolute path to messagesDir, constructed from `__dirname`?

**Comment by bertho-zero** [comment]
@pyrocat101 Yes i tried but that doesn't solve the problem, I launch webpack (and the babel-loader) from a package of my monorepo and `babel-plugin-react-intl` makes a `path.relative(process.cwd(), filename)`, which has the effect of adding a folder level because of this lines:

https://github.com/formatjs/formatjs/blob/2f60366ff209dd9d50cea88f7d0e7a58a1c45103/packages/babel-plugin-react-intl/src/index.ts#L400

https://github.com/formatjs/formatjs/blob/2f60366ff209dd9d50cea88f7d0e7a58a1c45103/packages/babel-plugin-react-intl/src/index.ts#L413-L417

```js
path.relative('/home/bertho/my-repo/packages/my-app', '/home/bertho/my-repo/packages/agenda-stats/src/app.js') // for example
// '../agenda-stats/src/app.js'

p.join( 
   messagesDir,  // '/home/bertho/my-repo/packages/agenda-stats/lib/messages'
   p.dirname(relativePath), // '../agenda-stats/src'
   basename + '.json' // 'app'
 )

// '/home/bertho/my-repo/packages/agenda-stats/lib/agenda-stats/src/app.json'
```

This `path.relative` should use the path of the .babelrc with the babel plugin as a base rather than the cwd, or we should be able to force this cwd.

**Comment by bertho-zero** [comment]
Keep open, bot.

**Comment by bertho-zero** [comment]
Ok.

**Comment by longlho** [comment]
babel-plugin-react-intl@7.8.0 should support this: https://formatjs.io/docs/tooling/babel-plugin/#workspaceroot
