### ISSUE TITLE
Lots of google search links point to "page not fount"

### ISSUE THREAD

**Issue by pahaz** [formatjs/formatjs#1652]
![image](https://user-images.githubusercontent.com/1394025/80414071-1df38200-88d9-11ea-96db-e91f17c8968b.png)

Query: `formattedmessage react-intl`
Links:
 1. https://github.com/formatjs/react-intl
 2. https://github.com/formatjs/react-intl/blob/master/docs/Components.md
 3. https://github.com/formatjs/react-intl/wiki/Components

It's really painful to try to use intl at the moment.

**Comment by longlho** [comment]
You can search within https://formatjs.io. Google will eventually re-index. The old site has been unmaintained for years and it doesn't even build anymore so we have to get off it.
