### ISSUE TITLE
Broken Documentation Links

### ISSUE THREAD

**Issue by AustinBratcher** [formatjs/formatjs#1653]
**Which package?**
react-intl

**Describe the bug**
It appears that with the recent merge to master, all documentation links are broken.

**To Reproduce**
- Head to https://github.com/formatjs/react-intl/blob/master/docs/README.md (This is the main documentation link in the react-intl package). 
- Notice Github serves a 404

**Comment by frank-shipstation** [comment]
I think the readme url you provided is old and invalid and thus should 404

This is the react-intl readme I found: https://github.com/formatjs/formatjs/blob/master/packages/react-intl/README.md

But the links inside that read me are broken for sure

**Comment by longlho** [comment]
We’ve consolidated all docs to https://formatjs.io

**Comment by longlho** [comment]
We've updated all the relevant links in our docs so lmk if you find any more broken links
