### ISSUE TITLE
packages/react-intl/examples does not run on clean install from master

### ISSUE THREAD

**Issue by fbartho** [formatjs/formatjs#1658]
**Which package?**

packages/react-intl/examples

**Describe the bug**

When running `yarn run examples` we get an error:

```shell
 (master) ~/Code/formatjs/packages/react-intl/examples $  yarn run example
yarn run v1.22.0
$ parcel examples/index.html
Server running at http://localhost:1234 
🚨  /Users/fbarthelemy/Code/formatjs/node_modules/@formatjs/intl-pluralrules/polyfill.js:1:8: Cannot resolve dependency './dist/polyfill' at '/Users/fbarthelemy/Code/formatjs/node_modules/@formatjs/intl-pluralrules/dist/polyfill'
> 1 | require('./dist/polyfill');
    |        ^
  2 | 
```

**To Reproduce**

1. clone formatjs/formatjs
2. `cd packages/react-intl/examples`
3. `yarn install`
4. `yarn run example`

**Expected behavior**

I would expect the example to run as indicated in the README in that directory

**Screenshots**

**Desktop (please complete the following information):**

- *OS:* macOS Catalina 
- *Browser:* N/A
- *Version:* master of this repo

**Smartphone (please complete the following information):**
N/A

**Comment by fbartho** [comment]
As a workaround, I tried creating a blank polyfill file at the targeted path, and that suppressed that error, but I realized a better change was to comment out this line in index.tsx:
https://github.com/formatjs/formatjs/blob/87d77191d297b55437520f580ae83841a9717be0/packages/react-intl/examples/index.tsx#L2

This then led to an error about core-js, which I worked around by commenting out this line:
https://github.com/formatjs/formatjs/blob/87d77191d297b55437520f580ae83841a9717be0/packages/react-intl/examples/index.tsx#L1

Both of these changes were on the presumption that I don't need polyfills for seeing how the Examples work.

This made the server happy with me, but when I went to load localhost:1234, it showed me that it was vending the HTML file, instead of vending the JS file:

![DevTools Screenshot](https://user-images.githubusercontent.com/209712/80743837-8bb6ce00-8ad2-11ea-9e31-e144d3cad3a7.png)

At this point I'm not sure what further workarounds to try!

**Comment by longlho** [comment]
did you `yarn build` at the root?

**Comment by fbartho** [comment]
Thanks @longlho -- turns out that that was a missing step! -- There were a heck of a lot of warnings, but it eventually completed.

I also ran `yarn build` inside `packages/react-intl/` -- not sure if that was needed or not.

Will close this issue!
