### ISSUE TITLE
Missing 'locale' prop error links to a non-existing file in the repo

### ISSUE THREAD

**Issue by Yohanna** [formatjs/formatjs#1663]
**Which package?**
react-intl

**Describe the bug**
The error printed when declaring an `IntlProvider` component without the `locale` prop links to a file that doesn't exist: https://github.com/formatjs/formatjs/blob/master/docs/API.md#intlshape

**To Reproduce**
Declare an `IntlProvider` component without a `locale` prop, then check the browser dev tool for the error message.

**Expected behavior**
Link to the correct documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/6926228/81010050-b0d57480-8e23-11ea-8bc7-5b0aa9216123.png)

**Desktop (please complete the following information):**

- OS: `Win 10`
- Browser: `Chrome Version 81.0.4044.129 (Official Build) (64-bit)`

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
fixed
