### ISSUE TITLE
Allow cli to extract a list of values used for interpolation

### ISSUE THREAD

**Issue by santialbo** [formatjs/formatjs#1665]
**Which package?**
cli

**Is your feature request related to a problem? Please describe.**
I would like to have in my CI a validation step where I check that any call to `<FormattedMessage {...}/>` or `intl.formatMessage({...}, {...})` is being provided the right values. For this to be possible I need the extract method from the cli to also provide me with a list of values used. If I had this I would be able to parse the `defaultMessage` using intl-messageformat-parser, traverse the ast and get which values are necessary and/or missing.

**Describe the solution you'd like**
Maybe just an additional flag `--extract-value-names` or similar which would add the list of used values to the term.

**Describe alternatives you've considered**

**Additional context**
If this is something you think would be a good addition I'm more than happy to work on it.

**Comment by longlho** [comment]
we have a linter for that :) https://formatjs.io/docs/tooling/linter#enforce-placeholders

**Comment by santialbo** [comment]
Awesome! thanks a lot, I just added it tour setup.
