### ISSUE TITLE
Components fetching their own translated messages from a server

### ISSUE THREAD

**Issue by DiegoBM** [formatjs/formatjs#1669]
**Which package?**
react-intl

**Is your feature request related to a problem? Please describe.**
Our architecture provides all the configuration (this includes also translated messages) for each Content component from a remote server , therefore each component might eventually make a request to that server to fetch and use its configuration. the problem is that apparently the only way to fetch translated messages to the application is from a root or nested Provider, and creating one provider per component that uses translations, although it might work, sounds convoluted and overkill, specially since the React team recommends [to not abuse context ](https://reactjs.org/docs/context.html#before-you-use-context)

**Describe the solution you'd like**
It would be desirable to have a way to enrich the existing translated messages passed to the root provider with an API call (maybe a method that could be passed through the main context or through composition) that will be called by each individual component once it has fetched it's own configuration, and therefore it's own copy

**Comment by longlho** [comment]
Right now setting `IntlProvider` is your best bet. Right now IO is out of our scope since its complexity isn't necessarily our concern.

**Comment by DiegoBM** [comment]
Thank you for your answer @longlho, but no IO is required in my suggestion (we fetch the data from our server ourselves), just to provide a way to enrich/extend the already loaded messages. Some sort of "addMessages" API method if you wish, that can be called at different points in time and that appends the passed messages to the existing list of messages that was initially passed to the root IntlProvider.

**Comment by longlho** [comment]
Hmm why can't you modify the root `messages` & just set `Provider` w/ the new bigger `messages`? Performance-wise I haven't seen that being an issue since the `intlCache` is preserved.

**Comment by DiegoBM** [comment]
The components connect to the server themselves to grab their piece of information, therefore in order to modify the root messages from the component level and set the new bigger messages, I'd need some sort of method that sends the component messages up to the root level in order to compose the new bigger messages and update the provider, which is basically what I'd be asking for, does that API or hook exist in react-intl?

**Comment by longlho** [comment]
nope but I imagine you have some centralized state management? `messages` would just be a global state is what I mean

**Comment by DiegoBM** [comment]
I presume that you mean keeping messages in some sort of centralised Redux store, in our case we are using GraphQL and XState so we don't really keep any form of central store. We could create a separate context just for this, but since this was specifically an i18n concern, and react-intl already provides a context API I guess that it made sense to keep it within that domain. I'll explore other possibilities for the time being. Thank you in any case

**Comment by longlho** [comment]
SGTM. Thanks!
