### ISSUE TITLE
babel-plugin-react-intl: defaultMessage with html fails to parse

### ISSUE THREAD

**Issue by robinclaes** [formatjs/formatjs#1671]
**Which package?**
babel-plugin-react-intl

**Describe the bug**
defaultMessages in defineMessages that contain HTML cannot be parsed with following error:
`SyntaxError: Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.`

**To Reproduce**

1. `defineMessages({ 
{ 
  id: 'test',
 defaultMessage: '<a href="www.google.com">Click here</a> to visit Google.'
}  
})`
2. Try to parse the file with babel-plugin-react-intl
3. `SyntaxError: Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.`

**Expected behavior**
The message succesfully parses, because react-intl has the option to create a `<FormattedHtmlMessage>`

**Desktop (please complete the following information):**

- MacOS
- babel-plugin-react-intl 7.5.6

**Comment by longlho** [comment]
do you have a repro? I added a test but couldn't repro it.

**Comment by robinclaes** [comment]
I've updated my issue. Apparently babel-plugin-react-intl can't handle quotes so it's impossible to use an `a href` in a default message, while it should be possible in a FormattedHtmlMessage.

If necessary we can set up a minimal repro but with the snippet above you should get the same error.

**Comment by longlho** [comment]
Oh as of v7 we no longer allow that due to potential XSS risk https://github.com/formatjs/formatjs/blob/master/packages/babel-plugin-react-intl/CHANGELOG.md#700-2020-03-22 so you have to either migrate off that or pin to v6
