### ISSUE TITLE
Better defineMessages typings for typescript

### ISSUE THREAD

**Issue by christophehurpeau** [formatjs/formatjs#1677]
**Which package?**
react-intl

**Is your feature request related to a problem? Please describe.**

I recently upgraded react-intl from 2.8.0, using @types/react-intl, and I found that defineMessages typings changed

now:
```
export declare function defineMessages<T, U extends Record<string, T>>(msgs: U): U;
```

with @types/react-intl:
```
function defineMessages<Names extends keyof any>(messages: Messages<Names>): Messages<Names>;
```

The old function was particularly usefull with Enums:

```
enum Colors {
  Green = 'green',
  Blue = 'blue'
}

const colorMessages = defineMessages<Colors>({
  [Colors.Green]: { id: 'green', defaultMessage: 'Green' },
  [Colors.Blue]: { id: 'blue', defaultMessage: 'Blue' },
});
```

We could be sure that all values of Colors were defined in colorMessages. This does not seems possible with the current typing.

**Describe the solution you'd like**

A better typing for defineMessages, working with Enum. 
Also, it seems we can put anything now in defineMessages, I would have liked something more strict ? Is there a reason why anything is accepted ?

**Describe alternatives you've considered**

None

**Additional context**

**Comment by longlho** [comment]
`defineMessages` is meant to be a compiler macro that we use to tag a set of messages for extraction so it actually doesn't do anything (it just echoes out whatever's passed to it as you can see) so it literally doesn't have any typing restriction.

**Comment by marcesengel** [comment]
@christophehurpeau you can use the following to get the old functionality (typed on mobile, may have minor syntax errors)

```ts
interface Message {
  id: string;
  defaultMessage: string;
}

type Messages<K extends string, T = Message> = {
  [key in K]: T;
};

enum Colors {
  Green = 'green',
  Blue = 'blue'
}

const colorMessages = defineMessages<Message, Messages<keyof Colors>>({
  [Colors.Green]: { id: 'green', defaultMessage: 'Green' },
  [Colors.Blue]: { id: 'blue', defaultMessage: 'Blue' },
});
```

@longlho how about making these the defaults for the generics?

**Comment by christophehurpeau** [comment]
I think it should not go stale?

**Comment by longlho** [comment]
@christophehurpeau do you want to make a PR for this? :)

**Comment by longlho** [comment]
5.3.0 should have this :)

**Comment by thomastvedt** [comment]
But how does it work? This issue is first on google, can't find anything on it in the documentation?

**Comment by longlho** [comment]
```
interface Message {
  id: string;
  defaultMessage: string;
}

type Messages<K extends string, T = Message> = {
  [key in K]: T;
};

enum Colors {
  Green = 'green',
  Blue = 'blue'
}

const colorMessages = defineMessages<Message, Messages<keyof Colors>>({
  [Colors.Green]: { id: 'green', defaultMessage: 'Green' },
  [Colors.Blue]: { id: 'blue', defaultMessage: 'Blue' },
});
```

does the example above work for you? if yes ill add to the docs

**Comment by joshunger** [comment]
@longlho can you please provide an updated example?
