### ISSUE TITLE
Tags inside plural variants

### ISSUE THREAD

**Issue by klimashkin** [formatjs/formatjs#1680]
Up until MessageFormat 8.0.0 it was possible to wrap values in plural section into html tags to style them. After upgrading from 7.8.4 to 8.3.11 using the new syntax it seems to be not possible anymore:
```js
return new IntlMessageFormat("You have {count, plural, =1 {<b>1</b> Message} other {<b>#</b> Messages}}", "en").format({
  count: 1000,
  b: (...chunks) => <strong>{chunks}</strong>,
});
```

<img width="817" alt="Screen Shot 2020-05-17 at 3 02 44 PM" src="https://user-images.githubusercontent.com/576077/82161188-7e7a3d00-984f-11ea-9ab5-87307e5a2bcb.png">

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
