### ISSUE TITLE
intl.formatMessage returns an array instead of a string

### ISSUE THREAD

**Issue by smeijer** [formatjs/formatjs#1681]
**Which package?**
Since this is a monorepo. Please specify which package this bug report is for.
`react-intl: 4.5.5`

**Describe the bug**
When formatting rich text, formatMessage returns an array instead of a string. This gives trouble when rendering the result, a message is now an array without `keys`.

```js
const message = intl.formatMessage({
  id: 1,
  defaultMessage: 'Hello <i>CodeSandbox</i>'
}, {
  i: (...chunks) => <i>{chunks}</i>
});
```

I would expect the type of `message` to be `string`, not to be `array`

**To Reproduce**

https://codesandbox.io/s/react-intl-formatmessage-returning-array-4kl6q?file=/src/App.js

**Expected behavior**

Whatever the input, `intl.formatMessage` should return a single string or object (/react element), not an array.

**Screenshots**
See sandbox above.

**Comment by longlho** [comment]
It’s an array of mixed string & ReactNode. In your case the `<i>` element

**Comment by smeijer** [comment]
Wouldn't it make sense to wrap it in a fragment though? Or make sure that all elements already have a `key`?

**Comment by longlho** [comment]
ah gotcha in that case u should thumb up #1623 so we can get some more signal for feedback

**Comment by andreapiras** [comment]
I'm on version 7.1.8 and I m still experiencing this 
```
const intl. = useIntl();
 intl.formatMessage({
      id: 'aaa',
      defaultMessage: 'AAA',
 })
```
returns
```
['AAA']
```
While I would expect 'AAA'
Is anyone else facing this issue?

Already reported here https://github.com/formatjs/formatjs/issues/4915
