### ISSUE TITLE
本都没发现这个错误，线上频繁出现报警【 invariant(id, '[React Intl] An `id` must be provided to format a message.');】

### ISSUE THREAD

**Issue by leishihong** [formatjs/formatjs#1682]
![image](https://user-images.githubusercontent.com/26375364/82397670-80c4dd00-9a83-11ea-8c59-2bbab6b44ead.png)

**Comment by pyrocat101** [comment]
@leishihong 你有没有可以重复这个错误情况的代码？

**Comment by leishihong** [comment]
@pyrocat101 非常抱歉，内部项目无法公开的，我们客户使用场景是在东南亚地区，中国境内没有那个报错，目前都是收到的客户那边的报错信息

**Comment by leishihong** [comment]
@pyrocat101 目前使用的版本是2.9.0，

**Comment by pyrocat101** [comment]
@leishihong 你不需要公开你们项目的代码，只需要提供一个可以复现这个错误的代码就行。连可复现的环境都没有，我们如何帮助你？

**Comment by leishihong** [comment]
@pyrocat101 目前来看是没法复现这个的

**Comment by pyrocat101** [comment]
Closing unless we have reproduce steps.
