### ISSUE TITLE
react-intl v3→v4 upgrade guide is missing

### ISSUE THREAD

**Issue by iamstarkov** [formatjs/formatjs#1683]
**Which package?**
react-intl

**Describe the bug**
no upgrade guide from v3 to v4. there are upgrade guides for v1→v2 and v2→v3, but none for v3→v4

**To Reproduce**
open react-intl part of the docs. https://formatjs.io/docs/react-intl/

**Expected behavior**
there should be one

**Comment by longlho** [comment]
v4 didn't have a huge list of changes so there's no Upgrade Guide for it. Our Release Notes/Changelog should cover it IMO but let me know if u need help. https://github.com/formatjs/formatjs/blob/master/packages/react-intl/CHANGELOG.md#400-2020-03-05

**Comment by longlho** [comment]
Fixed in https://formatjs.io/docs/react-intl/upgrade-guide-4x

**Comment by iamstarkov** [comment]
@longlho thanks
