### ISSUE TITLE
formatjs extract -> warning Reading source file from TTY

### ISSUE THREAD

**Issue by nebojsanb** [formatjs/formatjs#1686]
When I try to use `formatjs extract` to extract messages to json files, I only get this warning and nothing seems to happen. I tried to google it but that didn't help...

I am using this tool on my mac, and formatjs cli 1.6.18 version.

Thank you for your support.

**Comment by longlho** [comment]
how did u execute it?

**Comment by pyrocat101** [comment]
@nebojsanb did you pass in the glob pattern?

**Comment by nebojsanb** [comment]
Hey guys, thank you for your time and effort, and thank you for removing the bug label as I could not find a way to do it :/.

I tried with:
`formatjs extract --messages-dir /messages`
and some other options, but then I found in formatjs sourcecode (I don't know how I missed that in the documentation) that I need to pass the source file names.

so the one that worked was:
`formatjs extract */*`
that took files from the current folder and one subfolder.

Now the only question I have is there any way to take all files (like find command in mac terminal) or to load files from some txt file or similar so that I don't have to do it manually folder by folder.

Thank you one more time.

**Comment by longlho** [comment]
u're prob looking for `formatjs extract "**/*"`

**Comment by nebojsanb** [comment]
Thank you that is it!
I used `formatjs extract "**/*.js"` and it works perfectly.

**Comment by mkosir** [comment]
I created a script to search only through files in /src folder
`"translate-extract": "formatjs extract 'src/**/*.{js,jsx,ts,tsx}'"`
