### ISSUE TITLE
[Docs] "Runtime environments" page does not exist

### ISSUE THREAD

**Issue by Floriferous** [formatjs/formatjs#1689]
In the docs, on [this page](https://formatjs.io/docs/basic-internationalization-principles#structure-of-code), a "Runtime environments" page is mentioned. This page does not appear to exist.

I was looking for a section that documents how to best determine a user's locale.

**Comment by longlho** [comment]
you're looking for `Accept-Language` header basically: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Accept-Language
or `navigator.language || navigator.browserLanguage`
