### ISSUE TITLE
react-intl 3 with React 15.6.1

### ISSUE THREAD

**Issue by Mossar** [formatjs/formatjs#1691]
### Which package?
react-intl

### Expected behavior

I would like to upgrade react-intl 2 to 3 (because I need it for babel react intl plugin) with React 15.

### Current behavior

1. After upgrading react-intl from 2 to 3 I have few things to change (intlShape occurences, localeData, etc). There is a lot of things to change because we use intlShape in almost every component and it will take some time. So first I would like to know if it's even possible to run react-intl3 on React 15. I didn't find any info about compatibility with React 15. Is it possible? Upgrade article 2->3 doesn't explain it. It says about React 16 but I don't know if it's required or just suggested.

2. I don't know precisely what to do with this intlShape thing. Should I leave `injectIntl(component)` and remove the line `intl: intlShape.isRequired` from every component? What is the proper way of handling it?

**Comment by longlho** [comment]
We don't support React 15 anymore so tbh I don't know :)
You can remove the `intlShape` thing

**Comment by longlho** [comment]
Actually we use React 16 context API so it's not react 15-compatible
