### ISSUE TITLE
Short format rounding bug = 9990 -> 1.0 k

### ISSUE THREAD

**Issue by jSharpWolf** [formatjs/formatjs#1692]
**Which package?**
intl-numberformat

**Describe the bug**
There is a bug when using the short format, that causes numbers such as 9990 or 9999 to be displayed as 1.0 k

**To Reproduce**

            formatted = new NumberFormat('en', {
                notation: "compact",
                compactDisplay: "short"
            }).format(9990);

This will return "1.0 K", and is false in all other locales too.

**Expected behavior**
It should display "10K"

- OS: Windows10
- Browser Chrome  81.0.4044.138

Quick analysis without really trying to understand what's happening:
The issue seems to occur in the method "toRawPrecision", the property of "formattedString" usually behaves like this:
1.1 -> "1.1"
4.4 -> "4.4"
9.9 -> "9.9"
9.99 -> "1.0"
Which results in the call "toRawFixed" to be skipped, which would in turn retrun the correct number

**Comment by pyrocat101** [comment]
Oops. Looking now.

**Comment by pyrocat101** [comment]
Could be a bug in the spec. Filed here -> https://github.com/tc39/ecma402/issues/447

Meanwhile I will think of a workaround.
