### ISSUE TITLE
[intl-getcanonicallocales] cldr-core/supplemental/likelySubtags.json is not found

### ISSUE THREAD

**Issue by VincentLanglet** [formatjs/formatjs#1694]
**Which package?**
@formatjs/intl-getcanonicallocales

**Describe the bug**
When building, I get the error 
```
This dependency was not found:

* cldr-core/supplemental/likelySubtags.json in ./node_modules/@formatjs/intl-getcanonicallocales/dist/canonicalizer.js
```

**Expected behavior**
No error

**Additional context**

We can see here that
https://github.com/formatjs/formatjs/blob/master/packages/intl-getcanonicallocales/src/canonicalizer.ts#L14

We're using this library https://github.com/unicode-cldr/cldr-core
Which is not require in the package.json

**Comment by longlho** [comment]
fixed in d0b72fe398c7017d03e8ee66c98ad88fe3e47657
