### ISSUE TITLE
react-intl - formatTime - doesn't use option 'hourCycle'

### ISSUE THREAD

**Issue by alorek** [formatjs/formatjs#1695]
**Which package?**
react-intl

**Describe the bug**
not possible to use a 24 hour format with midnight as `00:00` when using locale 'en-US'

root cause:
`formatTime` and `formatDate` filter out from options `hourCycle`

**To Reproduce**
While using locale  'en-US' I expect to be able to pass `hourCycle` options to formatTime like:

```
const date = new Date(Date.UTC(2012, 11, 20, 0, 0, 0));
formatTime(date, {hourCycle: 'h23'})
```
to get `00:00`

this works correctly in  `Intl.DateTimeFormat` i.e. 

```
const date = new Date(Date.UTC(2012, 11, 20, 0, 0, 0));
new Intl.DateTimeFormat('en-US', {hour: '2-digit',
  minute: 'numeric', hourCycle: 'h23'}).format(date)
```

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
