### ISSUE TITLE
IntlProvider not recognizing children when wrapped in a HOC

### ISSUE THREAD

**Issue by Klemensas** [formatjs/formatjs#1697]
**Which package?**
`react-intl`

**Describe the bug**
When wrapping `IntlProvider` in a HOC wrapper like redux `connect` it seems like the returned component refuses to accept children resulting in a type error when trying to pass them in.

**To Reproduce**
Here's a codesandbox example https://codesandbox.io/s/stoic-leakey-3hrii?file=/src/index.tsx 
This one uses a minimal HOC but same could be observed using a react-redux

**Expected behavior**
No type error and component accepting children properly

**Additional context**
A potential fix could be explicitly adding `children` to props of `IntlProvider`

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
hmm why don't you wrap `App` or the top level component? Wrapping a Provider in a HOC is kinda odd.

**Comment by Klemensas** [comment]
This is a contrived example and sure, I could change how stuff is wrapped to avoid this. But that seems just like avoiding the underlying issue, no?
