### ISSUE TITLE
FormattedTime showing date

### ISSUE THREAD

**Issue by liemdo** [formatjs/formatjs#1698]
**Which package?**
react-intl

**Describe the bug**
I realize a few timezones are not supported by `formatTime` such as EST.

**To Reproduce**
Output `formatTime(new Date(), { timeZone: 'EST' })}`

Expected: `12:00AM`
Actual: `Wed May 06 2020 19:01:59 GMT-0700 (Pacific Daylight Time)`

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome

**Comment by longlho** [comment]
I think you're looking for `America/New_York`, `EST` is not a valid IANA timezone
