### ISSUE TITLE
[DOCS]: Firefox dark-theme "below the fold" colours inverted

### ISSUE THREAD

**Issue by pwujek** [formatjs/formatjs#1701]
**Which package?**
All pages on formatjs.io.

**Describe the bug**
The area below the initial view is displayed in inverted colours on a dark background.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://formatjs.io
2. Scroll down

**Expected behaviour**
Colours should not be inverted.

**Screenshots**
![image](https://user-images.githubusercontent.com/1900015/83884619-1fec0480-a713-11ea-8c65-11494e12948a.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 12.04
- Browser: Firefox
- Version: 76.01
- Preferences - extensions: dark-theme enabled

**Comment by longlho** [comment]
Hmm this is probably a bug for https://github.com/facebook/docusaurus so can u file a GH issue there?
