### ISSUE TITLE
TypeError: Cannot find function supportedLocalesOf in object function NumberFormat()

### ISSUE THREAD

**Issue by jl-gogovapps** [formatjs/formatjs#1705]
**Which package?**
react-intl

**Describe the bug**

I've seen quite a bit of these in our Sentry integration.  I'm relatively new to react, so I'm not entirely sure what kind of helpful information I can provide, mostly curious if anyone else has run into this.

```
TypeError: Cannot find function supportedLocalesOf in object function NumberFormat() { [native code] }.
```

My component is something along the lines of 
```
 50 const routing = (
 51   <IntlProvider locale="en">
 52     <Provider store={store as any}>
 53       <ConnectedRouter history={history}>
````

**To Reproduce**
Haven't been able to reproduce

**Expected behavior**
Not sure what the side effect is of this error
```

**Desktop (please complete the following information):**

Chrome
Version:81.0.4044

Windows
Version:7

**Additional context**
Add any other context about the problem here.

**Comment by JustFly1984** [comment]
getting similar error `Intl.DateTimeFormat.supportedLocalesOf is not a function` from Sentry.
As sentry reports it originates from browser Firefox 50.0, but MDN says https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/supportedLocalesOf
it is supported since FF29, so could be that.

I have 'intl-pluralrules', '@formatjs/intl-pluralrules/polyfill', '@formatjs/intl-pluralrules/dist/locale-data/en' and `'@formatjs/intl-pluralrules/dist/locale-data/ru'`
What could I miss?

**Comment by jl-gogovapps** [comment]
@JustFly1984 have you been able to reproduce?  Is there any side affect for the user?  I dont think I'm using any intl polyfills, but I'm seeing it in Chrome 81 (Windows 7)
```
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
import 'core-js/es/symbol';
import 'core-js/es/set';
import 'core-js/es/map';
import 'core-js/es/object';
import 'core-js/es/promise';
import 'core-js/es/string';
```

Not sure what else I could/should be doing...

**Comment by pyrocat101** [comment]
> - OS: - All
> - Browser - All

@jl-gogovapps can you double check on which OS and browsers this error is thrown? I believe Sentry will give you the distribution.

**Comment by jl-gogovapps** [comment]
@pyrocat101 thanks for asking me to double check, I'll update my original comment.  It does seem that they are all coming from:
```
Chrome
Version:81.0.4044

Windows
Version:7
```

**Comment by pyrocat101** [comment]
@jl-gogovapps @JustFly1984  sorry for the delay in response -- can you double check if you are using any other Intl polyfills (e.g. Intl.js)?

**Comment by jl-gogovapps** [comment]
@pyrocat101 no worries, thanks for the response.  After taking a look at my package.json, the only references to 'intl' are 

```
 22     "@types/react-intl": "^3.0.0",
```
```
 88     "react-intl": "^4.6.3",
```

I believe this is a list of polyfills I'm using:

```
  1 import 'react-app-polyfill/ie11';
  2 import 'react-app-polyfill/stable';
  3 import 'core-js/es/symbol';
  4 import 'core-js/es/set';
  5 import 'core-js/es/map';
  6 import 'core-js/es/object';
  7 import 'core-js/es/promise';
  8 import 'core-js/es/string';
```
I hope this is helpful, but let me know if theres other info I can provide.  

Thanks!

**Comment by longlho** [comment]
Quick glance you should remove `@types/react-intl`. We support TS natively now.
Do you have a stack trace from sentry?

**Comment by JustFly1984** [comment]
@pyrocat101 yes I have `intl` running first, then `intl-pluralrules`, then `@formatjs/intl-pluralrules/polyfill` then `@formatjs/intl-relativetimeformat/polyfill` in that order.

**Comment by jl-gogovapps** [comment]
The source is minified, I'm not sure why Sentry isn't picking up the map for this particular ticket.  

I'm also seeing a similar error for Safari users
```
Can't find variable: Intl
```

<img width="821" alt="Screen Shot 2020-06-15 at 3 51 00 PM" src="https://user-images.githubusercontent.com/44532602/84699719-0a9b8500-af20-11ea-8d02-26c8b23cb14a.png">

**Comment by jl-gogovapps** [comment]
@pyrocat101 I appreciate we all have a lot going on, but I just wanted to bump this to see if there was any more information I could provide to help?

**Comment by longlho** [comment]
Can u try dropping `intl.js` and use `@formatjs/intl-datetimeformat` & `@formatjs/intl-numberformat` instead?

The order should be:
1. `@formatjs/intl-getcanonicallocales`
2. `@formatjs/intl-pluralrules`
3. `@formatjs/intl-numberformat`
4. `@formatjs/intl-datetimeformat`

**Comment by jl-gogovapps** [comment]
@longlho thanks for the reply.

I'm not exactly sure what you mean here.  I'm using react/webpack.  I'm not using intl.js (afaik).

This is what the top of my index.tsx file looks like:
```
  1 import 'react-app-polyfill/ie11';
  2 import 'react-app-polyfill/stable';
  3 import 'core-js/es/symbol';
  4 import 'core-js/es/set';
  5 import 'core-js/es/map';
  6 import 'core-js/es/object';
  7 import 'core-js/es/promise';
  8 import 'core-js/es/string';
  9
 10 import React from 'react';
 11 import ReactDOM from 'react-dom';
 12 import { IntlProvider } from 'react-intl';
```

package.json:
```
 22     "@types/react-intl": "^3.0.0",
 89     "react-intl": "^4.6.3",
```

**Comment by longlho** [comment]
Is this still happening for you? What's the full User-Agent from Sentry?

**Comment by jl-gogovapps** [comment]
Yes, over 160 events in Sentry:

<img width="319" alt="Screen Shot 2020-06-30 at 12 40 27 PM" src="https://user-images.githubusercontent.com/44532602/86152994-fd10fe00-bace-11ea-9f61-058e8f827269.png">


```

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
--
```

**Comment by awwit** [comment]
Today I got the same error in sentry.

With the same user-agent: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36`

**Comment by longlho** [comment]
Unless we get more info regarding stack traces and such there's nothing much we can assist here. Does anyone have any more details?

**Comment by JustFly1984** [comment]
Issue is not reproducing, let’s keep it open if it will reappear.

**Comment by JustFly1984** [comment]
not stale!

**Comment by longlho** [comment]
I think it's best to open a new issue if this comes back otherwise stalebot will keep marking it

**Comment by jl-gogovapps** [comment]
> I think it's best to open a new issue if this comes back otherwise stalebot will keep marking it

It still happens for me multiple times a day.  I'm not sure if I agree opening a new issue would be helpful, my concern with that concept is that it dilutes the chances finding the right solution amongst many duplicates (when searching for similar issues).

I have some time today, I'll see if I can fire up a virtualbox and reproduce on Windows 7

**Comment by jl-gogovapps** [comment]
Could I expect this to help from https://formatjs.io/docs/runtime-requirements?
```
yarn add yarn add @formatjs/intl-pluralrules @formatjs/intl-numberformat
```

_in index.tsx_

```
...Other imports here...

if (!Intl.PluralRules) {
  require('@formatjs/intl-pluralrules/polyfill');
  require('@formatjs/intl-pluralrules/locale-data/en');
}

...rest of react initialization code
```

**Comment by longlho** [comment]
Not on Chrome though. Those are for older browsers like IE11 or old chrome.

**Comment by birgert** [comment]
Facing the same issue in my sentry logs and also with exactly chrome 81.0.4044.**122**
`Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36`

Did anyone else encounter this with another release version of Chrome 81?
I might be able to track down that specific user, will see if it can be reproduced and if it's gone after upgrading Chrome, seems 81.0.4044.138 was released in the beginning of May.

**Comment by petterroea** [comment]
We are having the same issue with the following user agents:

 * `Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G36` 
 * `Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1`
 * `Mozilla/5.0 (Linux; U; Android 9; he-il; Redmi Note 7 Build/PKQ1.180904.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.1.2`

We are getting around 10k issues of this type on Sentry per 24 hours at the moment. Any progress on resolving the issue?

**Comment by petterroea** [comment]
From some digging, at least in our project, the issue seems to be caused by webpack(?) importing the type definition(`.d.ts`) for `@formatjs/intl-numberformat/polyfill` instead of the compiled javascript file.

**Comment by jl-gogovapps** [comment]
<img width="348" alt="Screen Shot 2020-07-29 at 4 31 43 PM" src="https://user-images.githubusercontent.com/44532602/88850224-0918da00-d1b9-11ea-9595-3fb3c67baf34.png">

Now seeing this in a newer version fo chrome

**Comment by petterroea** [comment]
On our end, it seemed like the issue was incorrect importing of polyfills. Typescripts module resolver would pick the `.d.ts` files over the `.js` files. If you are struggling with this issue, you can see if this is the cause by adding some `console.log` to the `polyfills.js` and corresponding `polyfills.d.ts` file, to see which one is being used.

**Comment by nicolas-damiani** [comment]
I'm having the same issue. However, I cannot reproduce error using BrowserStack, with the same OS and browser specifications. 

![image](https://user-images.githubusercontent.com/31974775/90431593-a91ea080-e09f-11ea-9094-320693e7eb40.png)

**Comment by jl-gogovapps** [comment]
@nicolas-damiani same here
@petterroea I don't think i'm using those types of polyfills, but I dont really

**Comment by longlho** [comment]
The message seems to indicate that `DateTimeFormat` in this case is the native implementation of the browser (thus `[native code]`)

**Comment by akarabach** [comment]
the same on my machine Chrome Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by longlho** [comment]
What’s your stack trace?

**Comment by pyrocat101** [comment]
Interestingly, "Cannot find function" isn't Google Chrome's error message when you call undefined:

```js
(1).toUpperCase()
// Uncaught TypeError: 1.toUpperCase is not a function
```

Can anyone post a full stack trace? Otherwise there is too little information for us to help you.

**Comment by longlho** [comment]
Closing since we don't have any stack trace to debug from. If someone encounters this issue and has a stack trace that'd be great!

**Comment by vladislooove** [comment]
Getting those errors from our users, however we are not able to reproduce it using our devices

Message:
`Error: uncaught TypeError: Cannot find function supportedLocalesOf in object function NumberFormat() {
    [native code]
}`

List of browsers and OS:
Chrome 83 on Windows 7
Chrome 79 on Windows 10
Firefox 68 on Windows 10

**Comment by ilyabo** [comment]
Seeing this error in Sentry with the following stack trace 

react-intl version 6.3.0
Firefox 52.0

![image](https://github.com/formatjs/formatjs/assets/351828/fe809e90-d058-4521-9ee5-40484b70321b)

**Comment by longlho** [comment]
That FF version is too old so you'd need to polyfill it
