### ISSUE TITLE
No error for missing variable, and no fallback to default message

### ISSUE THREAD

**Issue by Tobbe** [formatjs/formatjs#1706]
**Which package?**
react-intl

**Describe the bug**
No error is issued for missing variable when using the imperative api with a defined message, and no fallback is performed to the default message

**To Reproduce**
Fire up a new create-react-app application, with react-intl installed, and then replace everything in App.tsx (or App.jsx) with the code below

```
import React from "react";
import { IntlProvider, FormattedMessage, useIntl } from "react-intl";

function Messages() {
  const intl = useIntl();

  return (
    <div>
      <p>
        <FormattedMessage
          id="test.component_msg"
          defaultMessage="component default message"
        />
      </p>

      <p>
        {intl.formatMessage({
          id: "test.imperative_msg_default",
          defaultMessage: "imperative var (defaultMessage): {var}",
        })}
      </p>

      <p>
        {intl.formatMessage({
          id: "test.imperative_msg",
          defaultMessage: "imperative default message",
        })}
      </p>
    </div>
  );
}

function App() {
  return (
    <IntlProvider
      locale="en"
      messages={{
        "test.component_msg": "component message with {var} var",
        "test.imperative_msg": "imperative msg with {var} var",
      }}
    >
      <Messages />
    </IntlProvider>
  );
}

export default App;
```

**Expected behavior**
I expect the imparative api and the component api to behave the same way in regards to raising errors for missing variables and fallback to default message. So in this case I expect three error messages, one for each of the messages in the example app above, instead of just two as I get now. And I expect the default message to be used when the variable is not provided.

These are the messages I get now
```
Error: [React Intl Error FORMAT_ERROR] Error formatting default message for: "test.imperative_msg_default", rendering default message verbatim 
Locale: en
MessageID: test.imperative_msg_default
Default Message: imperative var (defaultMessage): {var}
Description: undefined 
 
Error: The intl string context variable "var" was not provided to the string "imperative var (defaultMessage): {var}"
 

Error: [React Intl Error FORMAT_ERROR] Error formatting message: "test.component_msg", using default message as fallback. 
Locale: en
MessageID: test.component_msg
Default Message: component default message
Description: undefined 
 
Error: The intl string context variable "var" was not provided to the string "component message with {var} var"
```

I was expecting to also get an error like

``` 
Error: [React Intl Error FORMAT_ERROR] Error formatting message: "test.imperative_msg", using default message as fallback. 
```

And I was expecting to see the default message "imperative default message"

**Screenshots**
![image](https://user-images.githubusercontent.com/30793/84127059-04e50180-aa3f-11ea-9fe6-1793984b0f98.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: latest

**Additional context**
When I started writing this bug report I did so only to report the missing error message, but as I typed it out, and provided the screenshot, I noticed that the default message also wasn't used, so I added that to the report as well.

**Comment by longlho** [comment]
Can you make a codesandbox.io link?

**Comment by Tobbe** [comment]
> Can you make a codesandbox.io link?

No 🙁 

I tried forever before posting the issue, also tried jsfiddle and codepen, but I couldn't get anything running.

For codesandbox I keep getting this error
![image](https://user-images.githubusercontent.com/30793/84192435-45be3400-aa9a-11ea-81ea-e8bdb03df85a.png)

**Comment by longlho** [comment]
I've fixed the differences in the behavior between component & imperative API. The error for missing values is bc we purposefully hot path rendering the message when no `values` is present for performance. This issue also shouldn't be runtime issue and we have https://formatjs.io/docs/tooling/linter/#enforce-placeholders that should catch it.

**Comment by Tobbe** [comment]
Thanks for the fix 🙂 

I tried the eslint rule, but it does not catch the error

```
export const captureMessages = defineMessages({
  liveness__challenges__movement: {
    id: "capture.liveness.challenges.movement",
    description: "Describes how the user should move their head",
    defaultMessage: "Look over your {side} shoulder",
  },
});
```

```
import { captureMessages } from './messages';

const messages = {
  movement: intl.formatMessage(captureMessages.liveness__challenges__movement),
};
```

Running eslint with the code above no errors (or warnings) are printed

Other rules are working. If I have this for example I will get an error

```
export const captureMessages = defineMessages({
  liveness__challenges__movement: {
    id: "capture.liveness.challenges.movement",
    defaultMessage: "Look over your {side} shoulder",
  },
});
```

```
C:\Users\tobbe\dev\path\to\messages.ts
  258:32  error  `description` has to be specified in message descriptor  formatjs/enforce-description
```

**Comment by longlho** [comment]
The linter can only work with inline declaration like `intl.formatMessage({ defaultMessage: 'foo', description: 'bar' })` and `<FormattedMessage/>` since it only looks at the AST and cannot actually evaluate JS.

**Comment by Tobbe** [comment]
Yeah, that's the trade off you make when using eslint. Which is too bad for us, because we never inline our message definitions when using `formatMessage`.

You said you don't print the error message for performance reasons. But you do print the error when using `<FormattedMessage>`. Does that mean `formatMessage` is faster than `<FormattedMessage>`?

**Comment by longlho** [comment]
It's not that we don't print the err message, but rather we hot path the rendering of the message before parsing it (which is when we know there's an issue) if the `values` is not supplied. For example:
```
intl.formatMessage({
	defaultMessage: 'a {placeholder}'
})
```
We assume since u didn't pass in any `values` to format, `a {placeholder}` has no placeholder and should just be rendered verbatim. Doing it this way we optimize for the 90% case which is just straight up translation lookup since parsing message has a fixed cost (we cache afterwards).
`<FormattedMessage/>` just calls `intl.formatMessage` underneath the hood so it's fairly comparable, unless you're doing sub-sec re-rendering like realtime graph or finance realtime stock.
