### ISSUE TITLE
[cli] No error when using same id with different defaultMessage/description in different files

### ISSUE THREAD

**Issue by santialbo** [formatjs/formatjs#1707]
**Which package?**
@formatjs/cli

**Describe the bug**
I'm not sure this has always worked like this or if has been a recent bug, but I'm not getting any errors thrown when using the same `id` with different `defaultMessage` in different files.

**To Reproduce**
Same `id`, different `defaultMessage` in **different files**.
Extract and no errors are thrown.

**Expected behavior**
I would expect the same error I get when the two instances are in the same file:
```
[React Intl] Duplicate message id: "XXX", but the `description` and/or `defaultMessage` are different.
```

**Comment by santialbo** [comment]
I'd be more than happy to fix this if you want. As I understand it some logic would need to go here when merging all the messages from the different files.
https://github.com/formatjs/formatjs/blob/5544cdeb375df64f353a9b3efde55e28fa5616a6/packages/cli/src/extract.ts#L147-L150

**Comment by santialbo** [comment]
Something along the lines of 
```ts
for (const { messages } of extractionResults) {
  if (messages) {
    for (const message of messages) {
      const { id, description, defaultMessage } = message;
      if (extractedMessages.has(message.id)) {
        const existing = extractedMessages.get(id);
        if (
          description !== existing.description ||
          defaultMessage !== existing.defaultMessage
        ) {
          throw new Error(
            `[React Intl] Duplicate message id: "${id}", ` +
              "but the `description` and/or `defaultMessage` are different."
          );
        }
      }
      extractedMessages.set(message.id, message);
    }
  }
}
const results = Array.from(extractedMessages.values());
```

**Comment by longlho** [comment]
I'd be open to a PR for this :) Thanks!

**Comment by shadiabuhilal** [comment]
It will be great, if it can handle different Ids same value error case.

This will make the translation reusable and reduce duplicate translations (reduce translation cost).

e.g:
```
"[React Intl] Duplicate 'defaultMessage' with different 'id's!
${JSON.stringify({
id: currentItem[currentItem.defaultMessage],
defaultMessage: currentItem.defaultMessage
}}
\n
${JSON.stringify({
   id: item.id,
   defaultMessage: item.defaultMessage
})"
```

**Comment by longlho** [comment]
`defaultMessage` by itself yields too many false positive so it has to be in tandem w/ `description`
