### ISSUE TITLE
Update react-intl.md to include a "Getting started" chapter

### ISSUE THREAD

**Issue by flipcc** [formatjs/formatjs#1708]
**Which package?**
react-intl

**Is your feature request related to a problem? Please describe.**
Language switching should be part of a "Getting started" chapter. There are questions around on SO and in the issues. One in particular made me open this issue. It is #243 (or #234), because they even had influence on the docs (see [components > rawintlprovider](https://formatjs.io/docs/react-intl/components#rawintlprovider)). They suggest using a `key` props on `<IntlProvider />` as to enable rerendering, but instead it creates a second tree. In either case, an extra prop like `key`with no real purpose other than being a (somewhat problematic) quick fix, is not the way to go for beginners. Better documentation is needed.

**Describe the solution you'd like**
I think you want users like me to employ React.Context. There is a nice tutorial over at medium.

Link: [Translate Create-React-App with React-Intl](https://medium.com/frontend-digest/translate-create-react-app-with-react-intl-60c782bb7508)

```js
// index.js

import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import { LocaleContextProvider } from './LocaleContext';

ReactDOM.render(
  <React.StrictMode>
    <LocaleContextProvider>
      <App />
    </LocaleContextProvider>
  </React.StrictMode>,
  document.getElementById('root')
);
```

```js
// app.js

import React from "react";
import { IntlProvider } from "react-intl";
import Header from "./components/header";
import { LocaleContext } from './LocaleContext';

function App() {
  const [locale] = React.useContext(LocaleContext);
  return (
    <IntlProvider locale={locale} messages={{ en: [], fr: [] }}>
      <div className="App">
        <Header />
      </div>
    </IntlProvider>
  );
}

export default App;
```` 

```js
// header.js

import React from "react";
import { defineMessages, FormattedMessage } from "react-intl";
import { LocaleContext } from './LocaleContext';

const messages = defineMessages({
  title: {
    id: "Title",
    defaultMessage: "Hello World"
  },
  subtitle: {
    id: "Subtitle",
    defaultMessage: "Welcome to our app"
  }
});

const Header = props => {
  const [locale, setLocale] = React.useContext(LocaleContext);
  const nextLocale = locale === "en" ? "fr" : "en";
  return (
    <header>
      <h1>
        <FormattedMessage {...messages.title} />
      </h1>
      <h2>
        <FormattedMessage {...messages.subtitle} />
      </h2>
      <button onClick={() => setLocale(nextLocale)}>
        Change language to {nextLocale}
      </button>
    </header>
  );
};

export default Header;
```

```js
// LocaleContext.js

import React from "react";

export const LocaleContext = React.createContext();
export const LocaleContextProvider = props => {
  const [locale, setLocale] = React.useState("en");

return (
    <LocaleContext.Provider value={[locale, setLocale]}>
      {props.children}
    </LocaleContext.Provider>
  );
};
```

Thank you very much for your effort in mainting this well thought out i18n package.

**Comment by flipcc** [comment]
I am writing

> I think you want users like me to employ React.Context.

because I really cannot be sure, how you imagine users to implement language switching using react-intl. I think the linked tutorial does a great job, but still: maybe there is already a hook available? Or `RawIntlProvider`should be used in some way as it is a React.Context.Provider? Maybe, but without docs one cannot know.

**Comment by longlho** [comment]
I'd be open for a PR for this :)
