### ISSUE TITLE
extract to single file rather than matching file structure

### ISSUE THREAD

**Issue by reharik** [formatjs/formatjs#1709]
This is neither a bug report nor a feature request, but rather a request for guidance.
I'm wondering if there is a way that babel-plugin-react-intl could output all messages into a single file rather that placing them in the matching file structure.  
Further, it would be nice if I could preform a transform on the messages as they are retrieved before they are placed in said single file. 
I'm not sure what most people do with these messages,  but what we do is basically just what I mentioned, I reduce all the messages into a single file and then out put a object of key:values -> id:defaultMessage. 
I've been looking at the babel-pluging-react-intl/src/index.js file and it does not seem like this would be possible short of forking and sticking my functionality in there.  But I was wondering if anyone had any ideas short of that or any advice if I did do that.
Thanks,
Raif

**Comment by longlho** [comment]
We have https://www.npmjs.com/package/@formatjs/cli
In terms of babel we don't have a mechanism to know what a `project` is or when it's done processing so we can output the file (neither does `babel` AFAIK)

**Comment by reharik** [comment]
Ah so perhaps you can have a running state in the pipe line but there is no "all files processed" event for you to know to dump the state to a file (AFAYK).  Seems like there aught to be a way to tell, but I suspect neither of us has the available mental bandwidth to go studying up on the ASTs right now.
I have a workable solution, it would just be nice to have it a bit more integrated.
Thanks for the response. 
Raif

**Comment by longlho** [comment]
That's the gist of it yeah. That's why we release a separate CLI.
