### ISSUE TITLE
Force sign when formatting numbers

### ISSUE THREAD

**Issue by acontreras89** [formatjs/formatjs#1713]
**Which package?**
react-intl

**Is your feature request related to a problem? Please describe.**
There is no way force the inclusion of the plus sign `+` when formatting positive numbers, even though this is already considered [by `NumberFormat.formatToParts`'s `plusSign` type](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts#Description).

**Describe the solution you'd like**
An additional option for `formatNumber` and `formatNumberToParts`, something like:

```js
formatNumber(123, { alwaysSign: true }) // "+123"
formatNumberToParts(123, { alwaysSign: true }) 
// [{ type: "plusSign", value: "+" }, { type: "integer", value: "123" }]
```

See [ICU `sign-always` Number Skeletons](https://github.com/unicode-org/icu/blob/master/docs/userguide/format_parse/numbers/skeletons.md)

**Describe alternatives you've considered**
This can be achieved manually by checking the number, but does not feel right.

```js
`${n > 0 ? '+' : ''}${intl.formatNumber(n)}`
```

**Additional context**
This may not be something to be addressed at library-level, but rather should be added to [`Intl.NumberFormat`'s](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) spec, so I have also opened [an issue in `formatToParts`'s proposal](https://github.com/tc39/proposal-intl-formatToParts/issues/7).
However, some directions on how this should be properly requested would be much appreciated.

**Comment by longlho** [comment]
you're looking for `signDisplay: always`

**Comment by acontreras89** [comment]
Thanks @longlho, couldn't find it documented anywhere else.

**Comment by longlho** [comment]
yeah MDN lags behind but you can certainly fix it as well if you're motivated to :)

**Comment by acontreras89** [comment]
I've added it to the [`NumberFormat` constructor page](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat) 👍  thanks again @longlho !
