### ISSUE TITLE
Proposal: Use modern syntax in ESM builds

### ISSUE THREAD

**Issue by balloob** [formatjs/formatjs#1715]
**Which package?**
`intl-messageformat`, `intl-format-cache`, `intl-messageformat-parser`

**Is your feature request related to a problem? Please describe.**
I would like to be able to import `intl-messageformat` and all its dependencies written in a modern JS syntax. That way my app, which uses this lib, can decide at build time the level of JavaScript it wants to support and what helpers to include for that.

I have [a branch](https://github.com/formatjs/formatjs/compare/master...balloob:es6-build-intl-messageformat) to include an ES6 build for `intl-messageformat` following the pattern of the other packages, but that will not pull in the ES6 version of `intl-format-cache` and `intl-messageformat-parser`, so it's not very useful.

Bonus benefit of shipping an ES6 build is that Rollup will no longer print warnings when importing `intl-messageformat` for the TypeScript helpers as it does now:

```
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/intl-messageformat/lib/core.js
4: See the accompanying LICENSE file for terms.
5: */
6: var __assign = this && this.__assign || function () {
                  ^
7:   __assign = Object.assign || function (t) {
8:     for (var s, i = 1, n = arguments.length; i < n; i++) {
...and 1 other occurrence
node_modules/intl-messageformat/lib/error.js
1: var __extends = this && this.__extends || function () {
                   ^
2:   var extendStatics = function (d, b) {
3:     extendStatics = Object.setPrototypeOf || {
```

This warning is caused because in `module` context there is no `this`, and so it will always be undefined.

**Describe the solution you'd like**

Publish the module builds of all packages in a more modern JavaScript version. This can be achieved using the `target` setting in `tsconfig` for ESM builds.

This would be a breaking change.

**Describe alternatives you've considered**

Import the TypeScript files directly. This still will pull in the ES5 versions of the `format-cache` and `messageformat-parser` dependencies. Also it means that my app needs to use at least the version of TypeScript that this project uses.

**Additional context**
-

**Comment by pyrocat101** [comment]
To make sure I understand, you want a build target where the files are emitted as ES modules and in ES6 syntax?

**Comment by balloob** [comment]
Yes, and I would want that to be the default when you use `import` to import `intl-messageformat`:

```ts
// This imports an ES6 build.
import IntlMessageFormat from "intl-messageformat";
```

If it's not the default, `intl-messageformat` will still import the ES5 versions of its dependencies (`intl-format-cache` and `intl-messageformat-parser`).

**Comment by longlho** [comment]
Did u config your bundler to prioritize ES6 entry point?

**Comment by balloob** [comment]
If you mean the `module` key in [`intl-messageformat/package.json`](https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat/package.json#L31): yes. However that key points at an ES5 build using import/export. As example, see [`intl-messageformat/lib/error.js`](https://unpkg.com/browse/intl-messageformat@8.3.23/lib/error.js)

**Comment by longlho** [comment]
We used to do that (ESNext in ESM build) but then we got complaints that now you have to transpile transitive dependencies so... there's no really best of both worlds here.

**Comment by balloob** [comment]
That's true. That's why I noted my proposal as a breaking change.

ES6 is also known as ES2015, it was introduced in 2015. That's 5 years ago. It's supported by 94.68% of the browsers that are being used: https://caniuse.com/#feat=es6-class

If there are users that are still targeting IE 11 (itself an unsupported browser), they need a lot more tooling anyway.

**Comment by longlho** [comment]
I'll keep this issue open to see if people actually want it. Like I said last time we did it people didn't like it so it's unlikely we're gonna revisit it.

**Comment by tvvignesh** [comment]
@longlho Got the same error today when bundling with rollup (And this is what they say: https://rollupjs.org/guide/en/#error-this-is-undefined) Should I ignore this? Any ways to make this silent? Everything works though,

<img width="580" alt="Capture" src="https://user-images.githubusercontent.com/1165845/93204641-0fb4de00-f774-11ea-8c24-3146882e4071.PNG">
