### ISSUE TITLE
@formatjs/intl-datetimeformat not published

### ISSUE THREAD

**Issue by mrijke** [formatjs/formatjs#1718]
**Which package?**
@formatjs/intl-datetimeformat

**Describe the bug**
@formatjs/intl-datetimeformat seems to be not published to NPM (https://www.npmjs.com/search?q=%40formatjs%2Fintl-datetimeformat)

**To Reproduce**
Go to https://www.npmjs.com/search?q=%40formatjs%2Fintl-datetimeformat

**Expected behavior**
Expected to be able to download @formatjs/intl-datetimeformat from NPM

**Comment by longlho** [comment]
it's still work-in-progress so u might wanna follow #1702

**Comment by mrijke** [comment]
Ah I see!
Thanks for the quick response, I saw a "Publish" commit in that packages folder so I assumed it was meant to be published :)
I'll subscribe to that PR to keep in the loop!
