### ISSUE TITLE
React-Intl pass translation as string variable and not object

### ISSUE THREAD

**Issue by waynegrigsby** [formatjs/formatjs#1719]
I'm in the process of adding react-intl to a payment app I'm building but hitting a snag. I apologize if this has been addressed somewhere. I scoured the issues and documentation and couldn't find a direct answer on this (probably just overlooking it).

**Use Case**: Once a payment is processed I'd like to give the user the option to tweet a translated message indicating they've donated. 

**Problem**: Twitter uses an iframe to "share tweets", and requires a text field as a string variable. When I pass my translation I get `[object Object] ` in the tweet instead of the translated text. This makes sense based on my understanding of the translation engine. But I cant seem to find a way to pass a string rather than a translation object. 

### what I get when I use `{translate('example_tweet')}`
const translationText = object

### what I need
const translationText = 'this is the translated text'

### Question
How do I get the translated text as a string variable rather than an object to be rendered on a page?

### button
```
import { Share } from 'react-twitter-widgets'
import translate from '../i18n/translate'

export default function TwitterButton () {
  return (
    <Share
      url='https://www.sampleSite.org' options={{
        text: {translate('example_tweet')},
        size: 'large'
      }}
    />
  )
}
```
### translate
```
import React from 'react'
import { FormattedMessage } from 'react-intl'

const translate = (id, value = {}) => <FormattedMessage id={id} values={{ ...value }} />

export default translate
```

**Comment by longlho** [comment]
`<FormattedMessage/>` is a React component so it's an object, not a string. I think u're looking for https://formatjs.io/docs/react-intl/api/#formatmessage
