### ISSUE TITLE
react-intl assigns default properties to custom formats

### ISSUE THREAD

**Issue by nagiek** [formatjs/formatjs#1720]
**Which package?**
react-intl

**Describe the bug**
In FormattedMessage, if a customFormat is missing a property and it shares the same name as a defaultFormat, the property rendered with a default.

i.e. if a "short" format only has _month_ and _day_ properties, a _year_ is still rendered. If the format name is changed, i.e. from "short" to "month-day", is functions correctly.

**To Reproduce**
1. Create IntlProvider with a custom output
```
<IntlProvider 
messages={{"asOf": "as of {date, date, short}"}}
formats={{date: {short: {"month":"short", "day":"numeric" }}}}
> 
```

2. Render result
```
const date = new Date();
<FormattedMessage
id="asOf"
values={{date}}
/>
```

**Expected behavior**
As Of June 16

**Actual behavior**
As Of June 16, 20

**Comment by longlho** [comment]
I think this is by design from the old days (and will be a breaking change as well). At the spec level the recommendation is to use skeleton, e.g:
`as of {date, date, ::yyMMM}` in your use case
