### ISSUE TITLE
Make this error part of onError: [React Intl] An `id` must be provided to format a message.

### ISSUE THREAD

**Issue by johnfrades** [formatjs/formatjs#1722]
**Which package?**
react-intl: 4.6.9

**Describe the bug**
Im getting this error **[React Intl] An `id` must be provided to format a message.**
but this error wasn't thrown in onError of `IntlProvider`

**To Reproduce**

1. create a defineMessage
2. intl.formatMessage(messages.MISSING_MESSAGE_ID)

**Expected behavior**
the `onError` should catch this type of error

**Comment by longlho** [comment]
This is meant to be fatal. It's typically a symptom of some deeper pipelining issue of extracting messages and such that we've seen in large codebases.

**Comment by johnfrades** [comment]
So this can't be done? i know it's human error for this to happened, but would be good if there's a way to catch this so that we can handle it properly

**Comment by longlho** [comment]
It is by design and should have been caught during testing in your app :)

**Comment by longlho** [comment]
My suggestion is to move away from manual ID generation and use an automatic ID gen extraction flow like `@formatjs/cli`

**Comment by johnfrades** [comment]
ohh i see, ok man gonna check that one out!
