### ISSUE TITLE
Suggest how we can integrate formattedMessage with alert() or any javascript variable string value.

### ISSUE THREAD

**Issue by pranay-dev-1** [formatjs/formatjs#1723]
I want to translate text in alert() to any other language, how i can achieve that as normal HTML text we can translate with <formattedMessage> component. 

Please suggest any lead/solutions on this issue.

Thanks in advance.

**Comment by longlho** [comment]
You're looking for https://formatjs.io/docs/react-intl/api/#formatmessage
