### ISSUE TITLE
[react-intl] Support translation string parameter replacement

### ISSUE THREAD

**Issue by kaysonwu** [formatjs/formatjs#1724]
**Which package?**
`react-intl`

**Is your feature request related to a problem? Please describe.**

Support translation string parameter replacement

**Describe the solution you'd like**

I want to use the translation string as id, But the `formatMessage` api will not replace the placeholder.

```js
formatMessage({ id: 'Hello, {name}' }, { name: 'Jack' })
```

I want to use the translation string directly instead of defining the phrase, which can save me a language translation.

**Comment by longlho** [comment]
I'm not sure I understand ur use case. Do u want dynamic ID?

**Comment by kaysonwu** [comment]
Fallback can format ID instead of return as is.

**Comment by kaysonwu** [comment]
Phrases are good, but translating strings as id is more intuitive

**Comment by longlho** [comment]
Hmm that's what `defaultMessage` does. If you don't want to manually specify ID you can use `@formatjs/cli` to autogen IDs

**Comment by kaysonwu** [comment]
I know `defaultMessage` work, but for this I have to write an additional phrase id.

**Comment by kaysonwu** [comment]
Because I have explicitly used translation strings here, I am not going to use phrase.

**Comment by longlho** [comment]
You don't have to write IDs. We have toolchains that automatically extract messages & generate IDs for you

**Comment by kaysonwu** [comment]
If you can upgrade the fallback mechanism, that would be great

**Comment by longlho** [comment]
We don't have any plan to support this in the near future.

**Comment by kaysonwu** [comment]
Okay, but `id` is required.  `@formatjs/cli` does not meet my need.  I prefer translation strings as keys to short keys, In this way, English has become my default backup language, and I do not need to define a translation file for it.
