### ISSUE TITLE
Cannot find module './injectIntl' or its corresponding type declarations

### ISSUE THREAD

**Issue by llh911001** [formatjs/formatjs#1739]
**Which package?**

`packages/react-intl`, version `@4.6.10`.

**Describe the bug**

When compiling a TypeScript project that uses `useIntl` and `defineMessages`, the compilation fails as follows:

```sh
node_modules/react-intl/lib/react-intl.d.ts:95:57 - error TS2307: Cannot find module './injectIntl' or its corresponding type declarations.

95 export declare const FormattedPlural: React_2.FC<import("./injectIntl").WithIntlProps<Props_2>> & {
                                                           ~~~~~~~~~~~~~~
```

**To Reproduce**

1. Any TypeScript projects
2. Run `tsc` to compile the project

**Expected behavior**
No error occurs, projects get compiled successfully.

**Desktop (please complete the following information):**

- OS: [Mac OS v10.15.5]
- NodeJS [v12.16.2]
- react-intl Version [4.6.10]

**Additional context**

Version `4.6.9` doesn't have this issue.
After some digging, I'm guessing the issue was introduced by the `4.6.10` release(2 days ago) that adds children typing to `injectIntl`, the generated `react-intl.d.ts` includes an `import('./injectIntl')` statement, but the`./injectIntl` module stays in `./components/` directory.

**Comment by JustFly1984** [comment]
confirming the bug, @llh911001 thank you for workaround

**Comment by pyrocat101** [comment]
Might be https://github.com/formatjs/formatjs/issues/1716

**Comment by pyrocat101** [comment]
The tsc produced `index.d.ts` has the correct typing, but API extractor produced `react-intl.d.ts` did not correctly rewrite the `import(...)` path. Right now react-intl is using `react-intl.d.ts` as the typing definition.

cc @longlho

**Comment by pyrocat101** [comment]
Upgrading react-intl's API Extractor to 7.8.12 produces the following build error:

```
yarn workspace react-intl build
yarn workspace v1.22.4
yarn run v1.22.4
$ yarn run tsc && yarn run rollup
$ tsc -p tsconfig.json && tsc -p tsconfig.esm.json && api-extractor run --local && api-extractor run --local --config api-extractor.bundled.json

api-extractor 7.8.12  - https://api-extractor.com/

Using configuration from <redacted>/formatjs/packages/react-intl/api-extractor.json

Error: The expression contains an import() type, which is not yet supported by API Extractor:
<redacted>/formatjs/packages/react-intl/lib/index.d.ts:27:51
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/Cellar/node/14.1.0/bin/node
Arguments: /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js build
Directory: <redacted>/formatjs/packages/react-intl
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```
