### ISSUE TITLE
yarn add react-intl fails

### ISSUE THREAD

**Issue by alexander-r-jaimy** [formatjs/formatjs#1743]
**Which package?**
yarn add react-intl fails

**Describe the bug**
When trying to install react-intl 

**To Reproduce**
yarn add react-intl fails

**Screenshots**
![Screenshot from 2020-06-23 10-07-56](https://user-images.githubusercontent.com/60174868/85377707-c587dc00-b539-11ea-8d91-8426e7ca0225.png)

**Comment by csvan** [comment]
Related to this: https://github.com/formatjs/formatjs/issues/1744

**Comment by radumardale** [comment]
As a temporary fix: `react-intl@2.5.0` seems to work

**Comment by evertbouw** [comment]
Use `yarn add react-intl@4.6.9` for now

**Comment by longlho** [comment]
dupe of #1744
