### ISSUE TITLE
@formatjs/intl-datetimeformat breaks yarn installs

### ISSUE THREAD

**Issue by csvan** [formatjs/formatjs#1744]
As of v1.2.1, yarn installs are consistently failing with:

```
Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, link '/Users/csvanefalk/Library/Caches/Yarn/v6/npm-@formatjs-intl-datetimeformat-1.2.1-da53daa6480994259371229925700c797f3cac4b-integrity/node_modules/@formatjs/intl-datetimeformat/temp-zic/US/America/Adak' -> '/Users/csvanefalk/Library/Caches/Yarn/v6/npm-@formatjs-intl-datetimeformat-1.2.1-da53daa6480994259371229925700c797f3cac4b-integrity/node_modules/@formatjs/intl-datetimeformat/temp-zic/US/Aleutian'"
```

We have reproduced this across multiple machines and environments. We have tried fetching both directly from http://registry.npmjs.org and an internal Nexus instance proxying the same registry. Did something go wrong when publishing?

The only version I can find that works with Yarn is 1.1.0.

**Comment by alexander-r-jaimy** [comment]
![Screenshot from 2020-06-23 10-07-56](https://user-images.githubusercontent.com/60174868/85377534-86598b00-b539-11ea-9e9a-0d91f53fe8e3.png)
same error in a fresh docker

**Comment by csvan** [comment]
Seems to be several bad publishes of this package. If I add:

```
"resolutions": {
    "@formatjs/intl-datetimeformat": "1.2.0"
  }
```

I get

```
warning @formatjs/intl-datetimeformat@1.2.0: bad publish
```

**Comment by csvan** [comment]
Seems like this is the only version that works:

```
  "resolutions": {
    "@formatjs/intl-datetimeformat": "1.1.0"
  }
```

**Comment by mattvb91** [comment]
Seeing the same on vercel deployments:

`
10:38:16.235  
error https://registry.yarnpkg.com/@formatjs/intl-datetimeformat/-/intl-datetimeformat-1.2.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, link '/vercel/.cache/yarn/v6/npm-@formatjs-intl-datetimeformat-1.2.1-da53daa6480994259371229925700c797f3cac4b-integrity/node_modules/@formatjs/intl-datetimeformat/temp-zic/US/America/Adak' -> '/vercel/.cache/yarn/v6/npm-@formatjs-intl-datetimeformat-1.2.1-da53daa6480994259371229925700c797f3cac4b-integrity/node_modules/@formatjs/intl-datetimeformat/temp-zic/US/Aleutian'"
`

**Comment by zhanghaoxu** [comment]
any temporary solution for this issue?

**Comment by fmr** [comment]
I managed to do an install with npm. Is it possible `1.2.1` only affected yarn installs?

**Comment by csvan** [comment]
Ping @longlho

**Comment by evertbouw** [comment]
> 
> 
> any temporary solution for this issue?

Stick to version 4.6.9 for now. `yarn add react-intl@4.6.9`

**Comment by longlho** [comment]
Sorry for the breakage, react-intl@4.7.2 should unbreak yarn now.
