### ISSUE TITLE
FormattedTime does not seem to support hourCycle attribute

### ISSUE THREAD

**Issue by TimoKunze** [formatjs/formatjs#1751]
**Which package?**
react-intl

**Describe the bug**
The following code renders as "24:59:59" with en locale. Shouldn't it render as "00:59:59"? The `hourCycle` attribute seems to be ignored.
```
<FormattedTime value={new Date(3599000)} hour="2-digit" hour12={false} hourCycle="h23" minute="2-digit" second="2-digit" timeZone="UTC" />
```

**To Reproduce**

1. Place the code from above in the render method of a React component.
2. Make sure the React app uses en locale.
3. Execute the React app.
4. See error: The time is rendered as 24:59:59.

**Expected behavior**
The time should be rendered as 00:59:59

**Desktop (please complete the following information):**

- OS: Windows 10 1909
- Browser: Electron
- Version: 9.0.5

**Comment by longlho** [comment]
What Node version does Electron use?
Also what version of react-intl are you using?
Do you have a codesandbox.io link?

**Comment by TimoKunze** [comment]
It should be Node 12.14.1. I'm using react-intl 4.7.2.
At the moment I don't have a codesandbox.io link, sorry.

**Comment by longlho** [comment]
If you can create a codesandbox.io link to repro that'd be great.

**Comment by TimoKunze** [comment]
I hope this link works: https://codesandbox.io/embed/elegant-johnson-vb9le

**Comment by longlho** [comment]
You have to remove `hour12={false}`. When that is set, `hourCycle` is ignored per spec (https://tc39.es/ecma402/#sec-initializedatetimeformat step 14)
