### ISSUE TITLE
FormattedList polyfill not working

### ISSUE THREAD

**Issue by mikeplis** [formatjs/formatjs#1753]
**Which package?**

@formatjs/intl-listformat

**Describe the bug**

Importing the @formatjs/intl-listformat polyfill and using FormattedList doesn't render a formatted list in browsers that don't natively support the ListFormat API.

**To Reproduce**

https://codesandbox.io/s/naughty-sun-dng0u?file=/src/App.js

```jsx
import React from 'react';
import { IntlProvider, FormattedList } from 'react-intl';
import '@formatjs/intl-listformat/polyfill';

export default function App() {
  return (
    <IntlProvider locale="en">
      <FormattedList type="conjunction" value={['Me', 'myself', 'I']} />
    </IntlProvider>
  );
}
```

**Expected behavior**

I expect to see "Me, myself, and I" rendered

**Screenshots**

Chrome 83:

<img width="907" alt="Screen Shot 2020-06-25 at 8 40 53 PM" src="https://user-images.githubusercontent.com/1382377/85808988-7eaa0a00-b724-11ea-8361-251a5864d199.png">

Firefox 77:

<img width="1111" alt="Screen Shot 2020-06-25 at 8 42 50 PM" src="https://user-images.githubusercontent.com/1382377/85809093-c92b8680-b724-11ea-9a01-716cafb6f864.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox 77
- Version: 77

**Comment by mikeplis** [comment]
I've also tried using the ponyfill and that's not working either, including Chrome 83

```jsx
import React from 'react';
import { IntlProvider } from 'react-intl';
import IntlListFormat from '@formatjs/intl-listformat';

const formatter = new IntlListFormat('en', {
  style: 'long',
  type: 'conjunction',
});

export default function App() {
  return (
    <IntlProvider locale="en" defaultLocale="en">
      {formatter.format(['Me', 'myself', 'I'])}
    </IntlProvider>
  );
}
```

<img width="1112" alt="Screen Shot 2020-06-25 at 9 14 11 PM" src="https://user-images.githubusercontent.com/1382377/85810382-dea2af80-b728-11ea-86ff-461f749a0dcd.png">

**Comment by longlho** [comment]
You need to give it some locale-data like `import '@formatjs/intl-listformat/dist/locale-data/en';`
Our documentation is wrong it looks like (it doesn't come w/ `en` locale-data) so I'll keep this open until we fix that
