### ISSUE TITLE
Help: How to use FormatJS with NodeJS?

### ISSUE THREAD

**Issue by meness** [formatjs/formatjs#1755]
I imported `intl-messageformat` package. My string contains HTML tags and I don't know how to make it work because it throws following exception: `Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.`

**Comment by longlho** [comment]
you can use the `ignoreTag` option in our latest version of `intl-messageformat` to treat HTML tag as string literal and not parse it

**Comment by meness** [comment]
@longlho It's what I'm looking for, thanks. How can I use that option? I'm using the latest version. Can you please write an example of how to use `intl-messageformat` in NodeJS?

BTW, you can remove the enhancement label from this issue.

**Comment by longlho** [comment]
This doc should help you get started: https://formatjs.io/docs/intl-messageformat/#intlmessageformat-constructor
