### ISSUE TITLE
Escaping issue, double apostrophe

### ISSUE THREAD

**Issue by bertho-zero** [formatjs/formatjs#1761]
**Which package?**
`react-intl` or `intl-messageformat-parser` ?

**Describe the bug**
Since I updated the formatjs packages I have problems with apostrophes, I have certain messages which escape correctly (by replacing the `''` by `'`) and others which display the two quotes.

Is this a bug or should I only put simple quotes?

**To Reproduce**
I don't really know, I can't understand the problem.

**Expected behavior**
The escape must be for all messages.

**Screenshots**

![Screeshot](https://i.imgur.com/I43tG62.png)

**Desktop:**

- OS: Ubuntu 18.04
- Browser chrome
- Version 69.0.3497.100

**Comment by longlho** [comment]
Do you have the sample message? apostrophe escape is only necessary if you're escaping special syntactic char, otherwise it's verbatim. E.g:
```
this isn't bad // this isn't bad
this isn''t bad // this isn''t bad
this '{isn''t}' bad // this {isn't} bad
```

**Comment by bertho-zero** [comment]
I created this sandbox: https://codesandbox.io/s/react-intl-example-gm8zs

I notice that the problem disappears as soon as I add a `values` object, even empty.

**Comment by longlho** [comment]
Ah thanks a lot for the codesandbox link. Yeah when there's nothing to escape, single apostrophe would be just fine.
We have an optimization where if there's no `values` being passed in, we assume the message is just plain translations lookup w/o any placeholder, thus saving parsing time. This is the 90% that's we're optimizing for.

**Comment by bertho-zero** [comment]
I think that even without a placeholder we can transform the double quotes to gain consistency, a simple `.replace (/''/gm,"'")` would be enough, right?

I doubled the apostrophes of all my messages by increasing the version of react-intl and there I should remove some, but not all for it to work properly.

**Comment by longlho** [comment]
Technically that's possible but it'd be an implementation detail that makes your message non-ICU compliant so there's some risks there :)

**Comment by bertho-zero** [comment]
Is it normal to have a different behavior if we pass empty values or not ? because the label remains a label without placeholder.
