### ISSUE TITLE
Missing locale json files in numberformat

### ISSUE THREAD

**Issue by dvh91** [formatjs/formatjs#1768]
According to docs, the way to add the numberformat polyfill is:
```js
import '@formatjs/intl-numberformat/polyfill';

if (typeof Intl.NumberFormat.__addLocaleData === 'function') {
  Intl.NumberFormat.__addLocaleData(
    require('@formatjs/intl-numberformat/dist/locale-data/zh.json') // locale-data for zh
  );

  Intl.NumberFormat.__addLocaleData(
    require('@formatjs/intl-numberformat/dist/locale-data/en.json') // locale-data for en
  );
}
```

And I think the latest changes make it break as there are no JSON files anymore. 

The new way to activate the polyfill is:
```js
import '@formatjs/intl-numberformat/polyfill';
import '@formatjs/intl-numberformat/dist/locale-data/en';
```

Basically, it's a breaking change so I would rather support the two ways or bump version in major.

Version used: `@formatjs/intl-numberformat@^4.2.11`

**Comment by longlho** [comment]
thanks a lot for reporting we'll bump major and update the docs

**Comment by redmundas** [comment]
this is not entirely true. I've been importing this way for a while now. and it broke for me this week, after upgrading.
now docs show that `dist` part isn't needed anymore for locale imports: https://formatjs.io/docs/polyfills/intl-numberformat
so replacing `import '@formatjs/intl-numberformat/dist/locale-data/en';` with `import '@formatjs/intl-numberformat/locale-data/en';` solved the issue for me

**Comment by longlho** [comment]
We've published v5 and updated the doc

**Comment by joshunger** [comment]
@longlho the docs still point to `en.json`. What is the recommended way to add locale-data for `intl-numberformat`?

```
import '@formatjs/intl-numberformat/polyfill';
if (typeof Intl.NumberFormat.__addLocaleData === 'function') {
  Intl.NumberFormat.__addLocaleData(
    require('@formatjs/intl-numberformat/locale-data/zh.json') // locale-data for zh
  );
  Intl.NumberFormat.__addLocaleData(
    require('@formatjs/intl-numberformat/locale-data/en.json') // locale-data for en
  );
}
```

Reference: https://github.com/formatjs/formatjs/blob/master/website/docs/polyfills/intl-numberformat.md

**Comment by longlho** [comment]
ah yeah I've updated the doc. Thanks for reporting!
