### ISSUE TITLE
[@formatjs/intl-relativetimeformat@6.0.1} Can't resolve '@formatjs/intl-pluralrules/dist/locale-data/en' and other locale files in

### ISSUE THREAD

**Issue by JustFly1984** [formatjs/formatjs#1774]
**Which package?**
@formatjs/intl-relativetimeformat

**Describe the bug**
After updating "@formatjs/intl-relativetimeformat" from "5.2.11" to  "6.0.1" webpack build errors with
```sh
 ERROR #98124  WEBPACK

Generating JavaScript bundles failed

Can't resolve '@formatjs/intl-pluralrules/dist/locale-data/en' in '/Users/user/projects/project-gatsby'

If you're trying to use a package make sure that '@formatjs/intl-pluralrules/dist/locale-data/en' is installed. If you're trying to use a local file make sure that the path is correct.
```

for every locale we use in project

**Screenshots**
<img width="570" alt="Screenshot 2020-07-03 19 08 25" src="https://user-images.githubusercontent.com/2255993/86467961-9acf2c00-bd60-11ea-8c49-acf3b6d3db43.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by longlho** [comment]
We moved the `locale-data` location from `dist/locale-data` to just `locale-data`: https://github.com/formatjs/formatjs/blob/master/packages/intl-relativetimeformat/CHANGELOG.md#breaking-changes

**Comment by JustFly1984** [comment]
@longlho are you planing to do the same for `@formatjs/intl-pluralrules/dist/locale-data/en` ?

**Comment by longlho** [comment]
Yeah for all the polyfills basically
