### ISSUE TITLE
build: Migrate intl-locales-supported to bazel

### ISSUE THREAD

**Issue by longlho** [formatjs/formatjs#1789]

**Comment by p-j** [comment]
Hi @longlho 
Thanks for your work on formatjs!

Fixing this issue you deleted `intl-locales-supported` and marked the package on NPM as [deprecated](https://www.npmjs.com/package/intl-locales-supported).
I didn't find info on why this package is being deprecated and what to use instead/how to move forward for people relying on it.
Did I miss something?

Thanks

**Comment by longlho** [comment]
@p-j The package was used to detect old Node (13-) & old IEs lack of support for locales and `Intl` APIs. Given the current landscape it is no longer necessary and often causes confusion because some APIs would support some locales but not other. We deprecated this because we no longer use it & will not make updates to it and it seems to be the only way to freeze the package. `1.8.11` will continue to be there if you need it. Otherwise the package is already integrated with higher-level libs like `intl-messageformat` or `react-intl`.

The other option for you is to just copy the package out. It's literally 50 LOCs that will return `true` for most of the js env nowadays.

**Comment by p-j** [comment]
Hi @longlho 
Thanks for your reply, I've been digging a bit and it seems our use of this package is also a workaround to some oddities dating back several years. I'm looking at those helper functions we had and I'm likely going to remove them or upgrade them using the newer packages you mentioned. 

Thanks again.

**Comment by catamphetamine** [comment]
Breaking a package is just absurd.

We didn't use it anyway.
