### ISSUE TITLE
Add state setter to Intl context

### ISSUE THREAD

**Issue by andyrichardson** [formatjs/formatjs#1802]
## Package
`react-intl`

## About

Hey, first off, thanks for the awesome work :rocket: 

I've been using `react-intl` on a project recently and realised that the locale state can't be updated inside of `react-intl`. This lead to us needing to either:
 - Add a new context to our app to manage the state of the locale and trickle down into the intl provider
 - Create our own context to provide the accessors and setters that aren't provided by `useIntl`

[Here is a code sandbox reproduction](https://codesandbox.io/s/determined-saha-p0b89?file=/src/App.js:274-283) of the latter.

## Proposed solution

It would be pretty great if we were able to set the intl config values at runtime when using `useIntl`. Something like this would be pretty cool:

```jsx
// Parent
// ...
<IntlProvider initialConfig={{ locale, messages }}>
  <Child />
</IntlProvider>
// ...

// Child
// ...
const { setConfig } = useIntl();

const handleConfigChange = useCallback(
  (e) => setConfig({ locale: e.target.value, messages: dictionaries[e.target.value] }),
  [setConfig]
);
// ...
```

> Note: The introduction of state would be purely for ease of use with React and not the core library

## Alternatives

The codesandbox reproduction works - first party support would just be a nice to have for any projects where locale/messages need to change at runtime.

**Comment by longlho** [comment]
Thanks for the suggestion. We generally defer this to the callsite because of several reasons:
- Managing/changing `locale` is not really the responsibility of this library since it typically requires cross-subsystem synchronization especially in a SSR environment.
- There can be multiple `IntlProvider` in the same app, with different `locale`s.
- This turns `IntlProvider` into a controlled component instead of uncontrolled component, which comes w/ inherent state sync issue from reason 1.

**Comment by andyrichardson** [comment]
@longlho thanks for the response! 

I'd argue that the purpose of a provider is to expose state and accessors throughout an application, so to have an uncontrolled provider offsets the responsibility to the user to introduce accessors to state which could otherwise be handled in one place (the intl provider).

I'll close this for now as it seems like it's not on the roadmap. If you ever change your mind, I'd be happy to help get something like this introduced!

**Comment by longlho** [comment]
yeah the issue here is that the `IntlProvider` is not that one place (nor we plan it to be) :) It's not the source of truth for `locale` or `messages`. There can be multiple & even nested `IntlProvider`s.
