### ISSUE TITLE
Warning: Legacy context API has been detected within a strict-mode tree

### ISSUE THREAD

**Issue by Kiran554** [formatjs/formatjs#1804]
**Which package?**
react-intl (version `2.8.0`)

**Describe the bug**
I get this message when using react in StrictMode
```
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: FormattedMessag
```

**To Reproduce**
Use component <FormattedMessage> and wrap it around <React.StrictMode> and run the application to see the error in browser console log.

**Expected behavior**
Should not see the error

**Desktop (please complete the following information):**

- OS: All OS
- Browser: Chrome
- Version: All versions

**Comment by longlho** [comment]
what version of react-intl are you using?

**Comment by Kiran554** [comment]
It's 2.8.0

**Comment by Kiran554** [comment]
Updating to latest version fixed it. But we need to make sure to update tsconfig with following params

```
...
"lib": [
      ...
      "esnext.intl",
      "es2018.intl"
    ],
...
```
