### ISSUE TITLE
Typescript for Intl.NumberFormat

### ISSUE THREAD

**Issue by danielbotn** [formatjs/formatjs#1811]
**Which package?**
@formatjs/intl-numberformat

**Describe the bug**
I am wondering how to fix this typescript bug. See code below

```javascript
import '@formatjs/intl-numberformat/polyfill';

if (typeof Intl.NumberFormat.__addLocaleData === 'function') {
  Intl.NumberFormat.__addLocaleData(
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    require('@formatjs/intl-numberformat/locale-data/zh.json') // locale-data for zh
  );
  Intl.NumberFormat.__addLocaleData(
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    require('@formatjs/intl-numberformat/locale-data/en.json') // locale-data for en
  );
}
```
I am getting an type error on __addLocaleData:

```
Property '__addLocaleData' does not exist on type '{ (locales?: string | string[] | undefined, options?: NumberFormatOptions | undefined): NumberFormat; new (locales?: string | string[] | undefined, options?: NumberFormatOptions | undefined): NumberFormat; supportedLocalesOf(locales: string | string[], options?: NumberFormatOptions | undefined): string[]; }'.ts(2339)
```

**To Reproduce**

**Expected behavior**
I would like to know if there is a way to fix this typescript error.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] WINDOWS 10
- Browser [e.g. chrome, safari] CHROME
- Version [e.g. 22] newest version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by longlho** [comment]
The polyfill instance is a non-standard opaque object so I actually recommend you casting it to `any` like `typeof (Intl.NumberFormat as any).__addLocaleData`
Also we're removing the ponyfill version so you should use `import '@formatjs/intl-numberformat/locale-data/zh.js'`

**Comment by danielbotn** [comment]
@longlho Thanks this works fine :)

When you talk about:

> Also we're removing the ponyfill version so you should use import '@formatjs/intl-numberformat/locale-data/zh.js'

Are you talking about having the code like this:

```javascript
if (typeof (Intl.NumberFormat as any).__addLocaleData === 'function') {
  (Intl.NumberFormat as any).__addLocaleData(
    import '@formatjs/intl-numberformat/locale-data/zh.json' // locale-data for zh
  );
  (Intl.NumberFormat as any).__addLocaleData(
    import '@formatjs/intl-numberformat/locale-data/en.json'// locale-data for en
  );
}
```

Because that gives me an error: 

> Argument expression expected.ts(1135)

**Comment by longlho** [comment]
```tsx
if (typeof (Intl.NumberFormat as any).__addLocaleData === 'function') {
    import '@formatjs/intl-numberformat/locale-data/zh.js' // locale-data for zh
    import '@formatjs/intl-numberformat/locale-data/en.js'// locale-data for en
}
```

**Comment by danielbotn** [comment]
@longlho

I get the following type error because of the import statement:

> An import declaration can only be used in a namespace or module.ts(1232)

I changed it to a require instead just for now.
Thank you.

**Comment by longlho** [comment]
yeah depending on your bundler either `require` or `import` works
