### ISSUE TITLE
Upgrade guide for v3 -> v4 is missing on website

### ISSUE THREAD

**Issue by rcreagha** [formatjs/formatjs#1819]
**Which package?**
The website

**Describe the bug**
v3 -> v4 upgrade guide is missing

The url for 2->3 is "...3x" & the url for 4->5 is "...4x"
so I'm assuming 3->4 & 4->5 both have the same url

 **To Reproduce**
https://formatjs.io/docs/react-intl/upgrade-guide-3x

**Screenshots**
![image](https://user-images.githubusercontent.com/16086702/87059860-325cd080-c1e0-11ea-8fe8-e04489c999e5.png)

**Comment by longlho** [comment]
thanks for reporting we just fixed & redeployed. Give it a few and cache will expire
