### ISSUE TITLE
example cannot run, and how to use the BUILD file in example?

### ISSUE THREAD

**Issue by wishma2013** [formatjs/formatjs#1825]
**react-intl**

**example cannot run**

**To Reproduce**

1. Go to 'formatjs/packages/react-intl'
2. run 'npm install' or 'npm run example'

**Desktop (please complete the following information):**

- OS: [MacOS]
- Browser [Terminal]
- Version [10.13.3]

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
