### ISSUE TITLE
react-intl: updating from 5.0.2 to 5.1.0 breaks typescript definitions

### ISSUE THREAD

**Issue by JustFly1984** [formatjs/formatjs#1839]
**Which package?**
react-intl

**Describe the bug**
breaks typescript definitions. fails for both: vscode and tsc

**To Reproduce**
Update from 5.0.2 to 5.1.0 in react-typescript project, and it will loose type declarations

**Expected behavior**
Do not loose type declarations

**Screenshots**
<img width="586" alt="Screenshot 2020-07-14 15 28 49" src="https://user-images.githubusercontent.com/2255993/87403675-60c71b00-c5e7-11ea-9f26-71a09affc976.png">

Rolling back to 5.0.2 is temporary fixing an issue. Tested in 2 projects.

**Comment by emmenko** [comment]
Confirmed. It seems the `react-intl.d.ts` file is missing in the published package.

https://github.com/formatjs/formatjs/blob/8e433d5afdbf64f7a952d6345e50cad29bbb7083/packages/react-intl/package.json#L133

**Comment by JustFly1984** [comment]
@emmenko 
there is also issues with "@formatjs/intl-utils": "3.7.0" and "@formatjs/intl-displaynames": "3.1.0"

"@formatjs/intl-utils": "3.7.0" and "@formatjs/intl-displaynames": "3.1.0 is installed in dependencies for previous unbroken versions, and break it, so I've pinned it to `resolutions` in package.json as temporary fix.

```json
"resolutions": {
    "@formatjs/intl-utils": "3.6.0",
    "@formatjs/intl-displaynames": "3.0.2"
  },
```

I would recommend to remove `^` from semver of dependencies in package.json in every project, and update dependencies manually, or by using dependabot.

**Comment by emmenko** [comment]
True, we did the same 👌

**Comment by longlho** [comment]
Sorry for the breakage (we recently changed our build system), the newest versions should have those files.
