### ISSUE TITLE
NumberFormat polyfill error: TypeError: undefined is not an object (evaluating 'availableLocales_1.length')

### ISSUE THREAD

**Issue by rbatsenko** [formatjs/formatjs#1840]
**Which package?**
@formatjs/intl-numberformat

**Describe the bug**
Polyfill for @formatjs/intl-numberformat cause an error in React app on Safari.

```
TypeError: undefined is not an object (evaluating 'availableLocales_1.length')
__addLocaleData
src/core.ts:404
  401 | }
  402 | var num = String(Math.pow(10, magnitude));
  403 | var thresholds = Object.keys(thresholdMap); // TODO: this can be pre-processed
> 404 | if (num < thresholds[0]) {
      | ^  405 |     return 0;
  406 | }
  407 | if (num > thresholds[thresholds.length - 1]) {
```
```
./src/polyfills.js
src/polyfills.js:17
  14 | }
  15 | 
  16 | if (typeof Intl.NumberFormat.__addLocaleData === 'function') {
> 17 |   Intl.NumberFormat.__addLocaleData(require('@formatjs/intl-numberformat/locale-data/en.js'));
  18 |   Intl.NumberFormat.__addLocaleData(require('@formatjs/intl-numberformat/locale-data/ar.js'));
  19 | }
  20 |
```

**To Reproduce**

1. Follow the [instructions](https://formatjs.io/docs/polyfills/intl-numberformat) to add the polyfill.
2. Open the app in Safari and see the error in console.

**Expected behavior**
No error.

**Screenshots**
`core.ts`
![image](https://user-images.githubusercontent.com/6410057/87407224-29924300-c5c2-11ea-903c-62646fc787b1.png)

`core.js`
![image](https://user-images.githubusercontent.com/6410057/87407316-49296b80-c5c2-11ea-8b4e-bbf7188b2e24.png)

Breakpoint
![image](https://user-images.githubusercontent.com/6410057/87407368-5b0b0e80-c5c2-11ea-880d-91dbc1dcefc9.png)

**Desktop (please complete the following information):**

- OS: MacOS 10.15.5
- Browser: Safari
- Version: 13.1.1

**Additional context**
I checked `@formatjs/intl-numberformat/src/core.ts` and compiled version `core.js`, trying to somehow modify it to fix this, but with no success for now. Please check on screenshots above.

**Comment by longlho** [comment]
Per our doc https://formatjs.io/docs/polyfills/intl-numberformat/

```ts
import '@formatjs/intl-numberformat/polyfill';
if (typeof Intl.NumberFormat.__addLocaleData === 'function') {
	require('@formatjs/intl-numberformat/locale-data/zh.js'); // locale-data for zh
	require('@formatjs/intl-numberformat/locale-data/en.js'); // locale-data for en
}
```
