### ISSUE TITLE
Dist folder is not present anymore in intl-messageformat 9.1.4

### ISSUE THREAD

**Issue by kemsky** [formatjs/formatjs#1846]
**Which package?**
intl-messageformat 9.1.4

**Describe the bug**
Dist folder is not present anymore i.e. no UMD build.

**Expected behavior**
Was it on purpose?

**Comment by longlho** [comment]
What's ur use case?

Our public asset commitment is the `main`, `module` & `types` field in `package.json` so `dist` is kinda private. However, we'll add back the UMD asset
