### ISSUE TITLE
Remove need for "Version bump only for package" releases

### ISSUE THREAD

**Issue by petersendidit** [formatjs/formatjs#1848]
**Which package?**
All packages in this monorepo.

**Is your feature request related to a problem? Please describe.**
Since all the packages have been put in a monorepo many of the packages will have multiple "Version bump only for package" releases. Having releases that have no value at all add more work for developers without any gain. There is already enough work to keep on top of packages that need to get updated and what actually changed in them. The  "Version bump only for package" releases add noise to the process.

**Describe the solution you'd like**
Only release a package if it actually is needed. The release code has some method of deciding if the release is a "Version bump only for package", rather than creating a release with that message, can it not create a release?

**Comment by longlho** [comment]
This is a `lerna` issue so AFAIK we don't control this process. https://github.com/lerna/lerna/pull/707 might provide some context. Version bump only releases are needed in case A depends on B and B bumps major, thus A needing to bump as well (either patch or minor).

**Comment by petersendidit** [comment]
Maybe I am not understanding something but if A depends on B and wants to use the new major version of B doesn't A's package.json need to change?  If so then it's not a "Version bump only".

**Comment by longlho** [comment]
that's what lerna generates I believe
