### ISSUE TITLE
Switch remaining BSD-licensed packages over to MIT

### ISSUE THREAD

**Issue by lazytype** [formatjs/formatjs#1849]
**Which package?**
babel-plugin-react-intl
intl-format-cache
intl-messageformat-parser
intl-messageformat
react-intl

**Is your feature request related to a problem? Please describe.**
Some companies would be more comfortable with MIT

**Describe the solution you'd like**
See title

**Describe alternatives you've considered**
¯\_(ツ)_/¯

**Additional context**
I'll get you Teazzi when offices reopen

**Comment by longlho** [comment]
lol unfortunately those packages specifically came from the Yahoo days so I'm not sure if they can be changed. cc @redonkulus ?
