### ISSUE TITLE
Attempted import error: 'FormattedRelative' is not exported from 'react-intl'.

### ISSUE THREAD

**Issue by dhebert-dev** [formatjs/formatjs#1852]
**Which package?**
react-intl

**Describe the bug**
I am using box-ui-elements and they are attempting to import FormattedRelative from react-intl. Has FormattedRelative been deprecated and/or replaced by FormattedRelativeTime?

**To Reproduce**

1. Import FormattedRelative from react-intl
2. Build your project
3. Observe error

**Expected behavior**
No error message

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by longlho** [comment]
Yes `FormattedRelative` has been deprecated since v3. `FormattedRelativeTime` is the new spec-compliant component.

**Comment by dhebert-dev** [comment]
Thanks for verifying!
