### ISSUE TITLE
RelativeTimeFormat: missing Math.abs() when selecting the plural rule

### ISSUE THREAD

**Issue by jlowcs** [formatjs/formatjs#1858]
**Which package?**
`@formatjs/intl-relativetimeformat`

**Describe the bug**
The wrong plural rule is applied when the value is negative.

**To Reproduce**

1. run `new window.Intl.RelativeTimeFormat('en-US').format(-1, 'month')` in the JS console

**Expected behavior**
`new window.Intl.RelativeTimeFormat('en-US').format(-1, 'month')` returns `1 months ago` and should be `1 month ago`

**Additional context**
Fix should be pretty straightforward:

Add a `Math.abs` at: https://github.com/formatjs/formatjs/blob/1a6eeac8c59184825968ffddc35374c83f3fe782/packages/intl-relativetimeformat/index.ts#L257

```typescript
const pr = pluralRules.select(Math.abs(value)) as LDMLPluralRule;
```

**Comment by longlho** [comment]
What browser are you using?

**Comment by longlho** [comment]
This is a buggy `Intl.PluralRules` issue with the browser so I suggest you open a bug report with the browser itself. `Intl.PluralRules` is supposed to treat negative & positive number the same
```tsx
new Intl.PluralRules().select(-1) // one
```

**Comment by jlowcs** [comment]
Oh, got it. I'll look into that. Thanks for the help!
