### ISSUE TITLE
React-intl is not found by webpack since 5.1

### ISSUE THREAD

**Issue by VincentLanglet** [formatjs/formatjs#1871]
**Which package?**
`react-intl`.

**Describe the bug**
As shown in the screenshot, when I upgrade to react-intl@5.1 and try to build my js with webpack, I get an error.
I get the same error with the latest version.

I have no error with react-intl@5.0.2.
The dependency is in my package.json and my node_modules.

**Expected behavior**
I expect no breaking change with a minor update.

**Screenshots**
![image](https://user-images.githubusercontent.com/9052536/88306610-3c67ee80-cd0b-11ea-875e-0482b166fa38.png)

**Comment by longlho** [comment]
Can you provide a repro?

**Comment by VincentLanglet** [comment]
Sorry, seems like the issue was on me.

I added this https://github.com/formatjs/formatjs/issues/1433#issuecomment-594812956 a long time and forgot about it.

Removing the alias fix the issue.
