### ISSUE TITLE
Ast parser exception

### ISSUE THREAD

**Issue by roderickhsiao** [formatjs/formatjs#1878]
**Which package?**
`intl-messageformat-parser@5.3.7`

**Describe the bug**
Parsing exception thrown if one escape character is in front of xml tag

**To Reproduce**
[Code sandbox](https://codesandbox.io/s/hardcore-sky-jmgwr?file=/src/index.js)

1. Try to parse string with `'` directly in front of the tag (some language such as French will have sentence like `Télécharger à partir d'Instagram` (upload from Instagram)

```
const messageWithError = `{source, select, a {I select <b>A</b>} b {I select d'<b>B</b>}}`;
```

2. Syntax error thrown
```js
import { parse } from "intl-messageformat-parser";

const message = `{source, select, a {I select <b>A</b>} b {I select <b>B</b>}}`;
console.log(parse(message)); // no error

const messageWithError = `{source, select, a {I select <b>A</b>} b {I select d'<b>B</b>}}`;
console.log(parse(messageWithError));
// SyntaxError: Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.`
```

**Expected behavior**
A string directly in the front of an xml tag should consider valid

**Comment by longlho** [comment]
@pyrocat101 can u take a look?

**Comment by pyrocat101** [comment]
@roderickhsiao This is actually intended. The apostrophe escapes the `<`, which would otherwise be interpreted as the beginning of a HTML tag token.

Look at the ICU spec, it actually mentions not to use straight apostrophe in the message, but instead of the curly one (U+2019): http://userguide.icu-project.org/formatparse/messages (see "Quoting/Escaping" section).

Alternatively, you can use `''` if you MUST use straight apostrophe.

**Comment by pyrocat101** [comment]
As for error message, I admit that PEG.js isn't generating the best ones... because you escaped the opening tag, it chokes on the `</b>` tag.

I do want to keep the behavior that the unmatched closing tag throws the parsing error, since it is a common bug to watch out for.

**Comment by roderickhsiao** [comment]
Thanks for the details explanation! Not sure if its easy for people to avoid using  U+2017 but I think if its by the spec, should be a correct behavior.

Probably a mention in the formatjs documentation will be nice :)

**Comment by pyrocat101** [comment]
@roderickhsiao For sure! I will see if I can add an example in the doc.
