### ISSUE TITLE
[F.Y.I] Browser bugs for Intl.DisplayNames (Android)

### ISSUE THREAD

**Issue by roderickhsiao** [formatjs/formatjs#1879]
### Which package?

`@formatjs/intl-displaynames`

This is not a **bug** of the library, just put it up here in case people are searching for similar issues.
Our recommendation in the library it detect if `Intl.DisplayNames` is available then load the polyfills and intl data, however, Android only ship the method without full ICU data, hence the polyfill fallback won't work as expected.

### Expected behavior

Browser doesn't have full ICU data for `Intl.DisplayNames` when `Intl.DisplayNames` method is available. 
(Only "US" is available even in English)

```
const regionNames = new Intl.DisplayNames(['en'], {type: 'region'}); 
console.log(regionNames.of('US')); // United States
console.log(regionNames.of('CA')); // Canada
```

### Current behavior

```
const regionNames = new Intl.DisplayNames(['en'], {type: 'region'}); 
console.log(regionNames.of('US')); // United States
console.log(regionNames.of('CA')); // CA
```

### Step to reproduce for BUG REPORT

https://bugs.chromium.org/p/chromium/issues/detail?id=1097432
```
1. Intl.DisplayNames // Check if Intl.DisplayNames exists, will return the constructor function
2. Intl.DisplayNames.supportedLocalesOf(['en', 'zh-Hant']); // Check if locales supported, expecting return true
3. const regionNames = new Intl.DisplayNames(['en'], {type: 'region'}); // constructor, expecting no return value (undefined), console.log(regionNames) should return the instance
4. regionNames.of('US') // To show US's region name, expecting "United States" (correct)
5. regionNames.of('CA') // To show CA's region name. expecting "Canada" (wrong, returning "CA")
6. const regionNamesTW = new Intl.DisplayNames(['zh-Hant'], {type: 'region'}); // constructor for locale
7. regionNamesTW.of('US'); // expecting "美國" (wrong, returning "United States")
8. regionNamesTW.of('CA'); // expecting "加拿大" (wrong, returning  "CA")
```

### Workaround

Currently our workaround is to do a false check if `regionNames.of('CA')  === 'CA` conditionally and detect the native method in favor of [polyfill](https://github.com/formatjs/formatjs/blob/main/packages/intl-displaynames/polyfill.ts#L15-L22)

**Comment by longlho** [comment]
u wanna PR to add that to our checks as well? https://github.com/formatjs/formatjs/blob/main/packages/intl-displaynames/polyfill.ts#L15 :)

**Comment by roderickhsiao** [comment]
Ha, not sure if its helpful as I think most of people will do the same prototype type method check in the code base to reduce bundlesize, and if so, the polyfill won't bel load 

```js
if (!Intl.DisplayName) {
  // load polyfill
}
```

**Comment by longlho** [comment]
I think it'd be beneficial regardless. We're mirroring that to https://github.com/Financial-Times/polyfill-library for polyfill.io as well :)
