### ISSUE TITLE
babel-plugin-react-intl and automatic IDs

### ISSUE THREAD

**Issue by robcaldecottvelo** [formatjs/formatjs#1883]
**Which package?**
babel-plugin-react-intl 7.9.1

**Describe the bug**
I am unable to get automatic `FormattedMessage` IDs to work with `babel-plugin-react-intl`.

**To Reproduce**
Until now I have been using `babel-plugin-react-intl-auto` to avoid using message IDs in my `FormattedMessage` components and all works well. However, I noticed that the official `babel-plugin-react-intl` can now do this but I am unable to get it to work.

You can find a sample React project here:

https://github.com/robcaldecottvelo/react-intl-auto

This project uses `react-app-rewired` to allow `.babelrc` file to be used for dev, builds and testing. I then added a couple of `FormattedMessage` components and removed the `id` prop. No matter what plugin settings I use I am always greeted with the same error:

```bash
[React Intl] An `id` must be provided to format a message.
```

My `.babelrc` looks like this:

```json
{
  "plugins": [
    [
      "react-intl",
      {
        "extractFromFormatMessageCall": true
      }
    ]
  ]
}
```

However, if I use `babel-plugin-react-intl-auto` instead then this `.babelrc` does the job:

```json
{
  "plugins": ["react-intl-auto"]
}
```

But I'd rather use the official tools.

Instead of using `.babelrc` I have tried loading the plugin directly (which `react-app-rewired` supports) but to no avail. I just cannot get it to automate the message IDs. I added some `console.log` messages to the `node_modules/babel-plugin-react-intl/index.js` and the plugin is definitely being loaded.

I am obviously missing something here so any ideas are welcome. Note that this is JS code, not TS and I am using the following guide:

https://formatjs.io/docs/guides/bundler-plugins

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.5
- Browser: Any

**Comment by longlho** [comment]
Thanks for reporting. We'll update our docs but you'd need to specify `idInterpolationPattern: '[sha512:contenthash:hex:6]'` or some pattern in your option. See https://formatjs.io/docs/tooling/babel-plugin#idinterpolationpattern for more details.

I'll the issue open until I update the docs.
