### ISSUE TITLE
Typescript module missing after update to babel-plugin-react-intl@7.9.1

### ISSUE THREAD

**Issue by paulincai** [formatjs/formatjs#1884]
**Which package?**
babel-plugin-react-intl

**Describe the bug**
 babel-plugin-react-intl@7.8.2 Meteor project build with no issues
 babel-plugin-react-intl@7.9.1 same project display error on build, however the build continues to success.

Although Meteor supports Typescript, I do not purposely use it and prefer not to.

```
Warning: unable to resolve "react-intl" in plugins of ________________________/app/.babelrc, due to:
Error: Cannot find module 'typescript'
Require stack:
- /Users/paulailincai/Projects/activitree-web/app/node_modules/@formatjs/ts-transformer/src/transform.js
- /Users/paulailincai/Projects/activitree-web/app/node_modules/@formatjs/ts-transformer/index.js
- /Users/paulailincai/Projects/activitree-web/app/node_modules/babel-plugin-react-intl/index.js
.....
```

***.babelrc***
```
{
  "plugins": [
    "transform-class-properties",
    "@babel/plugin-proposal-optional-chaining",
    ["react-intl", {
      "messagesDir": "./imports/ui/translations/",
      "extractFromFormatMessageCall": true
    }],
    ["@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ],
  "presets": [
    ["@babel/env",
      {
        "targets": {
          "node": 12
        }
      }
    ]
  ]
}
```

**To Reproduce**
update from 7.8.2 to 7.9.1

**Expected behavior**
no errors in the build console

**Desktop (please complete the following information):**

- OS:OSX Catalina
- Node 12.16.1
- Meteor 1.10.2

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by vrbarros** [comment]
Same problem here, I have to keep version `7.8.3`.
