### ISSUE TITLE
FormattedMessage and formatMessage not render anything if id is named after one of object prototype methods

### ISSUE THREAD

**Issue by mateuszkrzak** [formatjs/formatjs#1885]
**Which package?**
react-intl 5.3.2 (probably this bug exists from version 2 looking at git history)

**Describe the bug**
For ids named after object prototype methods (like `toString`, `hasOwnProperty` etc.), `FormattedMessage` and `formatMessage` should use id as a fallback, instead of that we got following in console:
```Error: [React Intl Error FORMAT_ERROR] Error formatting message: "toString", using id as fallback. ```
but nothing is rendered. 

If string `__proto__` as a id is used, we got app crash with error:
```Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.```

**To Reproduce**
I made a sandbox with reproduced behavior:
https://codesandbox.io/s/angry-monad-8sjrd?file=/src/index.js

1. Go to [sandbox](https://codesandbox.io/s/friendly-bush-ql8fd?file=/src/index.js)
2. Check the console

**Expected behavior**
For ids named after protopype methods of object `FormattedMessage` and `formatMessage` should use id as a fallback like for any other string.

**Additional context**
The problem lies in [formatMessage](https://github.com/formatjs/formatjs/blob/18ba19c0df64789186d85912548d35bd9baa71e8/packages/react-intl/src/formatters/message.ts#L157) function, on 157LOC id is used as property accessor. Before accessing desired property one needs to check if it's own property or if it comes from prototype chain.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
