### ISSUE TITLE
workspaceRoot option breaks build

### ISSUE THREAD

**Issue by daggmano** [formatjs/formatjs#1890]
**Which package?**
babel-plugin-react-intl

**Describe the bug**
From v7.8.0, the `workspaceRoot` option has been added. For our builds on DevOps, we are running into an issue where a case change in path is breaking our builds. This only occurs occasionally, and depends on the actual machine which Azure uses to build. So, yes, this is an Azure issue as well! (And a ticket has been raised with them)

Of the three machines which may build our code, one uses the path D:\a\1\... while the other two use d:\a\1\... Notice the different case of the drive specifier. The problem appears here: `if (!filename.startsWith(workspaceRoot))...`

On the machine with the lower-case drive specifier, we get:
`D:\a\1\s\Solution\WebUI\<path>: File "D:\a\1\s\Solution\WebUI\<path>" is not under workspace root "d:\a\1\s\Solution\WebUI".`

**To Reproduce**
Specific to Azure DevOps at this point, hard to know how to reproduce locally.

**Expected behavior**
A case-insensitive comparison of `filename` and `workspaceRoot` would fix this, but I'm not sure if this would be detrimental to case-sensitive filesystems.

**Comment by longlho** [comment]
I'm surprised this used to work for you before 7.8. `workspaceRoot` is default to `process.cwd()` so if that returns `d:\` instead that's interesting.
The workflow we recommend is to do [extraction separately](https://formatjs.io/docs/getting-started/message-extraction) and use `babel-plugin-react-intl` to autogenerate message IDs. This is more battle-tested and less err-prone.

**Comment by daggmano** [comment]
We do extract our messages and process them separately for our main build process. It is only our Jest tests that fail. And I guess there is a question as to why `process.cwd()` returns `d:\`, and yet the file spec path uses `D:\`. I suppose it's worth digging into where the file spec path comes from.

Concerning how it worked previous to 7.8, I presume this is because the `filename.startsWith(workspaceRoot)` check did not exist at that point?

**Comment by longlho** [comment]
yeah that didn't exist in `7.8`. If you're not extracting w/ `babel-plugin-react-intl` when removing `messagesDir` would resolve it I believe?

**Comment by longlho** [comment]
closing this since we actually removed extraction from `babel-plugin-react-intl` in v8
