### ISSUE TITLE
How to extract multiple times at different times?

### ISSUE THREAD

**Issue by xianghongai** [formatjs/formatjs#1894]
**Which package?**
`react-intl`

**Is your feature request related to a problem? Please describe.**
- How to extract multiple times at different times?
- Will it overwrite the already implemented?

**Describe the solution you'd like**
Can it be maintained manually? Skip the `declaration` and `extraction` steps.

**Describe alternatives you've considered**
- [AngularJS translate](https://angular-translate.github.io/)
- [react-i18next](https://github.com/i18next/react-i18next/blob/master/example/react/public/locales/en/translation.json)

**Additional context**
More scenes, Declare language files like this, Translation and maintenance within the team.

```json
{
  "MESSAGES": {
    "CREDITCARD": "Invalid creditcard number",
    "DATE": "Please enter a valid date.",
    "MAX": "Please enter a value less than or equal to {{max}}.",
    "MAXLENGTH": "Please enter no more than {{maxlength}} characters.",
    "MIN": "Please enter a value greater than or equal to {{min}}.",
    "MINLENGTH": "Please enter at least {{minlength}} characters.",
    "NUMBER": "Please enter a valid number.",
    "RANGE": "Please enter a value between {{minlength}} and {{maxlength}}.",
  },
  "RESOURCE": {
    "PRECONDITION_FAILED_412": "Precondition Failed",
    "CONFLICT_415": "Unsupported Media Type",
    "GONE_422": "Unprocessable Entity",
    "TOO_MANY_REQUESTS_429": "Too Many Requests",
    "INTERNAL_SERVER_ERROR_500": "Internal Server Error",
    "SERVICE_UNAVAILABLE_503": "Service Unavailable"
  }
}
```

**Comment by longlho** [comment]
@xianghongai yes it can be maintained manually as long as u pass the correct `messages` shape to `react-intl` :)

**Comment by longlho** [comment]
If you convert ur format to the format in https://formatjs.io/docs/getting-started/message-distribution#compiling-messages you can still use our compiler
