### ISSUE TITLE
Have the cli also export the lines where the occurrence happened

### ISSUE THREAD

**Issue by santialbo** [formatjs/formatjs#1897]
**Which package?**
cli

**Is your feature request related to a problem? Please describe.**
On 1.x.x the cli used to export the lines and column where the token was found which was useful to create a reference (e.g: `/path/to/file.tsx:XX:XX`).
After 2.0.0 the cli is only exporting the position in the whole file which makes it harder to build that reference.

**Describe the solution you'd like**
I don't have a preference for the interface as long as the data is available somehow.

**Describe alternatives you've considered**
I have considered modifying the script so that it opens the source files and calculates the line and column.

**Comment by longlho** [comment]
yeah this was a regression since we switched to the `TypeScript` compiler. Some tooling also prefer absolution char positioning since it doesn't deal w/ encoding (e.g byte-based offset vs utf-8 offset).
Thanks for reporting. We'll add an option for this soon.

**Comment by santialbo** [comment]
Thanks a lot!
