### ISSUE TITLE
render time with specific timezone in formatMessage

### ISSUE THREAD

**Issue by avalenti89** [formatjs/formatjs#1898]
I'm using a string message that contains `{time, time, ::HH:mm:ss}` in it;

Using React-intl, defining the message and using the formatMessage method, I provide a UTC Date as ISOstring to the method.

When I run my script, I get the time in Local format instead of UTC.

There is a parameter that can be setted to keep the time as provided without any timezone conversion?

If not, and if cannot be added in a new release, which is the best practice to get my expected result?

**Comment by longlho** [comment]
Unfortunately since JS `Date` carries no inherent timezone with it, you'd have to separate out that format if u want to specify timezone:
```tsx
intl.formatMessage(
	{
		defaultMessage: 'today is {time}',
	}, 
	{
		time: intl.formatTime({ 
			hour: 'numeric', 
			minute: 'numeric', 
			second: 'numeric', 
			timeZoneName: 'UTC' 
		})
	}
)
```
More doc on date time skeleton can be found at http://userguide.icu-project.org/formatparse/datetime

**Comment by bertho-zero** [comment]
`intl.formatMessage` accepts a third argument `options` (`formatters` and `ignoreTag`), could there be an option `timeZone` to override it?

```js
const messages = defineMessages({
  dateRange: {
    id: 'MyPackage.dateRange',
    defaultMessage: 'From {startDate, time, ::yyyyMMdd} to {endDate, time, ::yyyyMMdd}',
  },
});

function MyComponent ({ startDate, endDate }) {
  const intl = useIntl();

  return (
    <div>
      {intl.formatMessage(
        messages.dateRange,
        { startDate, endDate },
        { timeZone: 'Europe/Paris' },
      )}
    </div>
  );
}
```
