### ISSUE TITLE
formatjs/cli unknown option --messages-dir

### ISSUE THREAD

**Issue by Floriferous** [formatjs/formatjs#1899]
When using `@formatjs/cli`, the `--out-file` help description mentions `This flag will ignore --messages-dir`. But this flag is not documented as an available flag, and the CLI fails when you try to use it.

Is it normal that the functionality of `@formatjs/cli` and `babel-plugin-react-intl` have different functionality? The CLI appears to only be able to output a single large .json file, while the babel plugin can only output a hierarchy of files similar to your component hierarchy.

Are they meant to co-exist, or is the CLI package replacing the babel plugin?

**Comment by longlho** [comment]
They're meant to co-exist. `babel-plugin-react-intl` automatically inserts IDs in the transpiled code and `@formatjs/cli` only extracts. I'll update the help messages accordingly.

**Comment by wkerswell-gresham** [comment]
Hey, Seems the `--messages-dir` has been removed from the `babel-plugin-react-intl` is there any way to replicate the plugins behaviour of outputting a hierarchy of files similar to your component hierarchy?
