### ISSUE TITLE
incorrect typescript types in docs

### ISSUE THREAD

**Issue by mudrz** [formatjs/formatjs#1900]
**Which package?**
react-intl

**Describe the bug**
The steps in the docs have incorrect types:
https://formatjs.io/docs/getting-started/message-distribution

```ts
function loadLocaleData(locale: string): Promise<Record<string, string>> {
  switch (locale) {
    case 'fr':
      return import('compiled-lang/fr.json');
    default:
      return import('compiled-lang/en.json');
  }
}
```

**To Reproduce**
The type when loading the compiled (or even non-compiled) JSON file is put s `Record<string, string>`:
> loadLocaleData(locale: string): Promise<Record<string, string>>

But it is not compatible with the actual structure. The actual structure doesn't seem to even be exported?
```
Property 'default' is incompatible with index signature.                   
     3 ||     Type '{ "6674b": { type: number; value: string; }[]; }' is not assignable to type 'string'.
     4 || src/index.ts(8,7): error TS2322: Type '{ default: { "6674b": { type: number; value: string; }[]; }; "6674b": { type: number; value: string; }[]; }' is not as       signable to type 'Record<string, string>'.
     5 ||   Property 'default' is incompatible with index signature.                   
     6 ||     Type '{ "6674b": { type: number; value: string; }[]; }' is not assignable to type 'string'.
```

**Comment by hannahatwork** [comment]
@longlho I took a look at the updates in 3a68c67, but I can't see what actually fixed @mudrz 's issue. Looking at the docs, the `loadLocaleData` example doesn't seem to have a return type anymore, and I can't find any typing for that shape in the types files. Can you point me in the right direction or let me know if I'll need to type it myself? Thanks!

Edit: I see the type `MessageFormatElement` [here](https://formatjs.io/docs/react-intl/components/#intlprovider), which looked promising, but doesn't actually look like it is exported as part of the library.

**Comment by longlho** [comment]
@hannahatwork can u make a separate GH issue? This issue is really old and tbh I can't remember what it was about based on the description.

**Comment by ghost** [comment]
@longlho 
This is still an issue. How to use compiled lang files with Typescript?
