### ISSUE TITLE
Consistent auto-generated ids for Translation management systems?

### ISSUE THREAD

**Issue by Floriferous** [formatjs/formatjs#1907]
There's one part of this translation puzzle that I'm not sure I understand: When you let `@formatjs/cli` and `babel-plugin-react-intl` generate `id`s for you, these ids will change regularly, depending on what your hash generation algorithm is in `idInterpolationPattern`.

_I'm not sure what the default `[contenthash:5]` is, but I assume it's a hash of the file's content..? How does it generate ids for multiple `FormattedMessage` in the same file? This is all pretty obscure from the docs right now._

Most translation management systems let you upload a JSON file containing all your translated strings, and use the ids to check which translations are done or not, based off your single source-language file.

Now if your id for a string changes frequently, how are these tools supposed to keep track of which string belongs to which id, across locales, and decide what needs to be translated? If I reupload a new source-language file for french with different keys, how would that work?

Also, on a side note, no translation management systems directly support the JSON output from `@formatjs/cli`, you have to post-process it into a format that they know about. The closest I've seen, is Transifex's [Structured JSON](https://docs.transifex.com/formats/json/structured-json), though simple, non-hierarchical JSON is the most widely supported format (looked at Phrase, Lingohub, Crowdin, lokalise). While I know the docs here are prefaced with the fact that this is purely about the React side, I'm left wondering how everyone using this library actually manages the translation part? It seems inevitable to write at least 2 JSON formatting scripts (react-intl -> TMS and TMS -> react-intl).

**Comment by longlho** [comment]
Good question. Contenthash is just defaultMessage & description concat together. We'll clarify in the docs.

In terms of output format, we'll add vendor presets to ease this process. As you mentioned every vendor has a different json structure but providing adapter should be fairly easy.

Thanks for the suggestions!

**Comment by Floriferous** [comment]
Okay, so if you edit your defaultMessage or description, the hash changes, and your translation system becomes out of sync with your repo, I'm not sure I see a solution to that problem, except for using 100% explicit ids?

**Comment by longlho** [comment]
TMS is an external system so it'll always be out of sync unless I'm missing something? A matching ID doesn't mean your translations are synced it means you're probably serving old translations and hash prevents that. New msg/desc means a new translation.

**Comment by Floriferous** [comment]
Well, to me changing one word in a sentence, or fixing a typo, or adding punctuation should not mean a new translation. To me, non-developers think about translating the title of that specific section on that specific page, or changing a sentence in the middle of a description somewhere in the website.

You don't want to lose all translations you had for that piece of text and start over. Because if your id changes, your old translations for the previous id are lost.

**Comment by longlho** [comment]
That's unfortunately an unsafe assumption that engineers have for the language they speak. Changing a word/letter in a language doesn't guarantee a trivial change across all languages. Ideally all copy/wording would have gone through editorial to prevent these issues.

In larger engineering team we didn't find any substantial issues with autogen ID and manual ID is a lot worse.

**Comment by longlho** [comment]
> To me, non-developers think about translating the title of that specific section on that specific page, or changing a sentence in the middle of a description somewhere in the website.

> You don't want to lose all translations you had for that piece of text and start over.
I think that's the point. What you're talking about seems to be a difference in requirements/assumptions between non-devs & devs in terms of how a text is supposed to be consumed. We've seen that engineers tend to pattern match fairly aggressively (extracting common texts into a reusable piece) and that's actually a problem. Unless it's branding in some way that requires consistent messaging across the product, it's not safe to reuse strings out of context.

When marketing/writer changes a piece of text assuming it should only change at that exact location, that's the correct behavior and if the implementation differs that's an implementation issue. If the assumption of a piece of text is that when you change it it'll affect more than its intentional location, it should be communicated to the stakeholders that way so proper safeguards are put in place.

For reference, Yahoo and Dropbox teams share at a higher level than texts, or styles, or even components (unless they're foundational like branding related) and share at the feature level instead since it's a coherent unit that comes with everything.

**Comment by longlho** [comment]
@Floriferous Latest `@formatjs/cli` should have [builtin formatters](https://formatjs.io/docs/tooling/cli#builtin-formatters) for the vendors u mentioned (+ Smartling which is what Dropbox uses)

**Comment by wereHamster** [comment]
Any good translation service should detect when the default message has changed and flag translations for review instead of treating them as new strings. The translators then don't have to re-translate the strings, they can review them and decide for themselves what to do (eg. if it's a typo then not do anything and mark the translation as good). I'm using https://www.accent.reviews (a self-hosted translation service) and it implements that workflow well.

FWIW, I decided to use random generated IDs, I have a script in the project which will generate random strings of length 7 and use those. That way the IDs don't carry any meaning, besides being a unique identifier.

**Comment by longlho** [comment]
As you mentioned and from what I have seen, TMSes have translation memory implementation with some fuzz factory to inherently reduce costs of translating new strings for partners.

**Comment by Floriferous** [comment]
_Replying to multiple messages:_

> TMS is an external system so it'll always be out of sync unless I'm missing something?

Most TMSes support pulling translation-data (i.e. new/updated strings) on every commit, and pushing/PRing back to the repo for every edit happening on the TMS, so yes it is slightly out of sync with your local environment, but it should always be in perfect sync with your main branch.

> Changing a word/letter in a language doesn't guarantee a trivial change across all languages. Ideally all copy/wording would have gone through editorial to prevent these issues.

@longlho That's a very good point I hadn't considered. So in some way you'd want to consider translations as "immutable". As @wereHamster mentioned, some TMSes can handle this well (auto-detection with re-translation flag), but I'm not sure they can all do this well (or you might need a pricier plan).

Depending on the scale of your team (ours is very small), you can solve this issue completely with explicit IDs, at the cost of other issues you mentioned of course. No matter which change you make, your TMS always knows which string you're referring to.

FWIW, we've used `ComponentName.stringDescriptor`, like `HomePage.title`, `ImageCarousel.nextButton`, etc. 

Since we have a practice that keeps all of our component names unique, this should hardly ever lead to conflicts. And since the ID is also displayed in your TMS, it gives translators a little hint as to "what" this string is about, as well as where it is displayed. It's not always understandable by non-devs, but it's a good start.

For some categories of strings, we use a consistent prefix and style everywhere: `Form.firstName.label`, `Form.firstName.placeholder` and `Form.email.errors.invalid`. Since all of these string ids are generated in bulk (we have a lot of forms) and programmatically, you can't extract them from our code base anyways. I'm considering creating a huge file filled with `defineMessages` to avoid issues created by this practice (removing a form field currently does not easily remove its related translations..).


> For reference, Yahoo and Dropbox teams share at a higher level than texts, or styles, or even components (unless they're foundational like branding related) and share at the feature level instead since it's a coherent unit that comes with everything.

I'm not sure I understand this, what are teams sharing? Strings? Do you mean the same strings are used in multiple places, and you only translate them once?

> Latest @formatjs/cli should have builtin formatters

That's really awesome, thanks for doing that :) So when the TMS pushes the translated strings back to your repo, it should do so in `simple` key-value pairs  for direct consumption by `react-intl`.


> Any good translation service should detect when the default message has changed

@wereHamster But if the generated ID changes when you make that edit, you re-upload your new strings to the TMS, and it sees one less translation with id1, and a new translation with id2, with a few different words. There's no way it can tell that the first one is in fact the second one, because that could lead to errors? How can it be sure that those 2 strings are the same, and preserve the other locales' versions of it (and flag them for re-translation as you said)? Maybe there is a heuristic to do this, but it can't be 100% accurate.

Again, I'm not sure this is a safe assumption, and it depends on your TMS + pricing plan.

**Comment by wereHamster** [comment]
@Floriferous The generated IDs don't change unless I change them. My workflow is:

 1. I insert `<FormattedMessage id="" defaultMessage="blah blah" />` into the code.
 2. I run `npm run msgid`, which prints a random ID to stdout (eg. `EkgYoxH`).
 3. I copy that ID and paste it into the `id=""` prop, so it reads `<FormattedMessage id="EkgYoxH" … />`

I could optimize all this by creating a plugin or extension into my editor (VS Code), or have a snippet that generates that ID for me and inserts the full `<FormattedMessage … />` expression into the file at my current cursor position, but I just didn't have the need for that yet.

**Comment by longlho** [comment]
@wereHamster we have https://formatjs.io/docs/tooling/linter so we can actually add a rule like `enforce-id` and it'll autofix your code w/ generated ID if the ID isn't there :)

@Floriferous I mean teams don't share strings or even Components (unless it's a Design System). They share standalone features in the form or SDKs.

**Comment by wereHamster** [comment]
@longlho that would be an awesome rule! 🤘🏿

**Comment by longlho** [comment]
@wereHamster `eslint-plugin-formatjs@2.6.0` should have it: https://formatjs.io/docs/tooling/linter#enforce-id so give that a try

**Comment by Amansaxena001** [comment]
@longlho what do you suggest if lets say translator updates the sheet for eg they update the base language ( en in most cases ) , so now our code based on which we created auto id using babel plugin is out of sync as today or tomorrow dev has to go back to update the code in component. To handle this either we make the base language read only for translators but not sure if that would be good. Let me know what do you think? would appreciate

**Comment by longlho** [comment]
yes, code need to be updated. Translators do not have enough context to make copy changes by themselves.
