### ISSUE TITLE
babel plugin throws workspaceRoot error when using npm link

### ISSUE THREAD

**Issue by advl** [formatjs/formatjs#1910]
**Which package?**
`babel-plugin-react-intl`

**Describe the bug**
When using in the project X the dependency D, if both are developped on the same machine, [it is advisable to use npm link](https://www.deadcoderising.com/how-to-smoothly-develop-node-modules-locally-using-npm-link/); `npm link` basically removes the npm version of the D package from 'node_modules/' to replace it with a symlink to the local version of the package, for instance /home/code/D. This allows to code seamlessly two dependent packages at once.

Provided that `workspaceRoot` is left at the default, (the root of X), if the dependency D has messages and translations, this bugs the babel plugin.

The problem is that `babel-plugin-react-intl` understands that when D is symlinked to the local machine, D is outside of the workspaceRoot (which is true, because the symlink origin of D is outside of X). **Instead, the plugin should cover for this use case and consider that symlinks resolved from node_modules as being inside of the workspaceRoot**

**Comment by longlho** [comment]
Thanks for reporting. We'll take a look later but I recommend using `@formatjs/cli` to do extraction instead. See https://formatjs.io/docs/getting-started/message-extraction for more details.

**Comment by longlho** [comment]
Do you have a repro repo?

**Comment by advl** [comment]
You can repo using this small react template
Clone https://github.com/fwrlines/template-react-dashboard
Install following `README.md`
After 'npm run cds', webpack-dev-server should run locally on port 3344

The react template has as a dependency, the library DS https://github.com/fwrlines/ds (An ensemble of react components)
If the dependency is installed through npm, webpack compiles correctly.

To reproduce the bug, you need to clone the DS library locally, outside of the template-react-dashboard.
+ Clone it, cd into it and `npm i`
+ `npm link` still inside of the `ds` directory to add this package to the list of locally available packages, you might need to run it with `sudo` as this taps into the list of global npm installs
+ go back to the `template-react-dashboard` directory, and inside of it start activate the link using `npm link @fwrlines/ds` this time without sudo
+ In the same directory now run the client `npm run cds` and it should fail

**Comment by longlho** [comment]
Can u clarify the issue a bit more? I'm not sure what the expected outcome would be?
I debugged a bit and the issue is that `babel` doesn't tell us it's a symlink so it's kinda moot since there's no way for us to know that.

**Comment by advl** [comment]
Hey, thanks for taking the time to look at this, really

I ran in the bug in the first place while trying to bump my dependencies on a project.

I had my translation flow working properly on `babel-plugin-react-intl@=7.5.20` and `react-intl@=4.6.9` and I tried the bump to the latest version of both packages.

The dependency bump revealed the 'bug', directly. It appears that before, the workspaceRoot was not enforced, or not enforced in the same way.

I precise that when I say ''a translation flow working", in particular, refers to running my React app in development served through webpack-dev-server/babel, so that it automatically creates/appends the correct translation files on every save. I am using `npm link`, which aliases one of the packages in node_modules. In my development flow, using `npm link` is critical since it allows me to quickly proptotype two dependent libraries without having to commit, publish and reinstall the packages all the time.

For the expected output, you can look at this

## Debug Info and expected output

here is the babel config for a project using  the plugin v 7.5.20 in `babel.config.js`. I also share the extractor config, it's not part of the problem, it's just to illustrate my complete workflow.
```
[
  'react-intl',
  {
    messagesDir  :'./src/translations/messages'
  }
],
[
  'react-intl-extractor',
  {
    extractedFile:'./src/translations/aggregated.json',
    langFiles    :[{
      path              :'./src/translations/it.json',
      cleanUpNewMessages:true
    }, {
      path              :'./src/translations/en.json',
      cleanUpNewMessages:false
    }]
  }
],
```

** Expected output **
This is the result after webpack/babel compilation using the previous settings into the `src/translations/messages` dir. 
This is the expected output and works correctly on `7.5.20` but doesn't when I do the version bump. I also precise that I emptied the translations directory prior to compiling, so this is a 100% clean output.

```
779g@merida2 ~/code/project/site/src/translations/messages master* ❯ tree
.
├── fwrlines
│   └── ds
│       └── dist
│           └── es
│               ├── collections
│               │   ├── blog
│               │   │   └── common
│               │   │       └── ArticleCard
│               │   │           └── messages.json
│               │   ├── dashboard
│               │   │   └── Navigation
│               │   │       └── common
│               │   │           └── messages.json
│               │   ├── oauth2
│               │   │   └── OLoginButton
│               │   │       └── messages.json
│               │   └── saas
│               │       └── Plan
│               │           ├── common
│               │           │   └── messages.json
│               │           └── messages.json
│               ├── form
│               │   └── common
│               │       └── common
│               │           └── InputLabel
│               │               └── messages.json
│               └── site
│                   └── Paginator
│                       └── messages.json
└── src
    ├── app
    │   ├── blog
    │   │   ├── components
    │   │   │   ├── LocalFooter
    │   │   │   │   └── messages.json
    │   │   │   └── LocalNavBar
    │   │   │       └── messages.json
    │   │   └── pages
    │   │       ├── List.messages.json
    │   │       └── Single.messages.json
    │   ├── common
    │   │   ├── components
    │   │   │   ├── LatestBlogArticles
    │   │   │   │   └── messages.json
    │   │   │   ├── LocalFooter
    │   │   │   │   └── messages.json
    │   │   │   └── messages.json
    │   │   ├── NavMap.messages.json
    │   │   └── pages
    │   │       └── messages.json
    │   ├── mdx
    │   │   └── pages
    │   │       └── single.messages.json
    │   └── site
    │       └── pages
    │           ├── Contact.messages.json
    │           ├── Home.messages.json
    │           ├── Pricing.messages.json
    │           └── SaaSForm.messages.json
    └── config
        └── siteContext.json


```

As you can note, workspaceRoot is not enforced since we have a symlink in the `node_modules/@fwrlines` directory and the translations message dict structure is created correctly.
```
lrwxrwxrwx    1 779g 779g   60 Aug  4 11:14 ds -> ../../../../../../../usr/local/lib/node_modules/@fwrlines/ds

```

**Comment by longlho** [comment]
The previous version actually had a bug when it resolved that: https://github.com/formatjs/formatjs/blob/e8b1791146fa4f4f86a4e0596e846d3b4d4aa7a7/packages/babel-plugin-react-intl/index.ts#L355

In your case, `p.relative(process.cwd(), filename))` resolves to `../fwrlines/ds/dist/es/collections/blog/common/ArticleCard/messages.json` but then joining `sep` to it (which is `/`) turns it into `/fwrlines/ds/dist/es/collections/blog/common/ArticleCard/messages.json` which is problematic. Because if you have the same folder inside your `code/project/site` like `code/project/site/fwrlines` it'll get clobbered.

We do have a guide on [distributing i18n-friendly libraries](https://formatjs.io/docs/guides/distribute-libraries) that I think your use case could benefit from.

As I mentioned future release of `babel-plugin-react-intl` will remove extraction capability since we have `@formatjs/cli` to replace that.

**Comment by longlho** [comment]
Closing since we've removed extraction from `babel-plugin-react-intl@8` but we can keep discussing.
