### ISSUE TITLE
Document strategies for integrating <IntlProvider> in component libraries

### ISSUE THREAD

**Issue by jonenst** [formatjs/formatjs#1912]
**Which package?**
react-intl

**Is your feature request related to a problem? Please describe.**
When writing a react component in a separate npm package (component library), there are many options to integrate IntlProvider. It would be useful to document guidelines in the two cases:
 * writing a component in a library, 
 * using a component from a library

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
https://formatjs.io/docs/guides/distribute-libraries/ should have more info on this :) Hope that helps

**Comment by jonenst** [comment]
Awesome thanks !
