### ISSUE TITLE
[intl-messageformat] Support of ES modules

### ISSUE THREAD

**Issue by goremikin** [formatjs/formatjs#1913]
**Which package?**
intl-messageformat

**Describe the bug**
In `intl-messageformat@9.2.0` `intl-format-cache` has been replaced with `fast-memoize` (see mr: https://github.com/formatjs/formatjs/commit/1a7eb0210f1a171eb5291a79bb9f3cc855c5e12f). Unfortunately `fast-memoize` supports only UMD.

This has introduced an issue for applications that rely on ES6 module syntax (ESM). Because of that the entire application needs to be bundled by Webpack or similar.

**To Reproduce**
Run the code natively without any transformations or bundling (e.g. `es-dev-server` can bee used). A WebBrowser will throw:

```
ReferenceError: module is not defined at node_modules/fast-memoize/src/index.js:140:1
```

**Expected behavior**
`intl-messageformat` is targeted both: Web Browser and node.js. I expect both to work without bundler.

**Comment by longlho** [comment]
do u have a repro?

**Comment by JustFly1984** [comment]
I have reproduced it in 2 projects. No changes in codebase, just updating react-intl causes this issue.

**Comment by longlho** [comment]
Do you have a repo that reproduce this?

**Comment by goremikin** [comment]
Hi @longlho , I have made a simple repo to reproduce an issue: https://github.com/goremikin/intl-message-format-issue. It does work correctly with `~9.1.0`.

**Comment by moodyjmz** [comment]
Is it possible to use: https://www.npmjs.com/package/nano-memoize

As that supports es6 + seems to be faster than fast-memoize.

**Comment by longlho** [comment]
Ah that seems like a `es-dev-server` issue for not supporting UMD. `nano-memoize` is pretty immature so I'd rather not switch to that.

The other alternative is submit a GH issue upstream at `fast-memoize` as well.

**Comment by goremikin** [comment]
`es-dev-server` serves files as they are without any build steps. In a nutshell it is just a static file server.
ES Modules are natively supported by all modern browsers. I can see it as step backwards to require UMD support.

**Comment by longlho** [comment]
The issue is that this is a private implementation details that we neither officially support nor have test against, so it'll continue to break version to version until the whole ecosystem is on ES module.

**Comment by re-thc** [comment]
ES modules optimize better. Most newer libraries / frameworks are moving to ES modules. Vite and Snowpack both use it for a very fast refresh (hot reloading) experience. Please consider it.

**Comment by longlho** [comment]
Just to clarify that we do support ESM but our transitive dependencies don't and that's outside of our control.

**Comment by pyrocat101** [comment]
@hc-codersatlas If you are using Vite and Snowpack, `react-intl` should work just fine since Rollup will convert the bundle to a ESM. Is that not the case?

**Comment by re-thc** [comment]
@pyrocat101 was using umijs when I tried it. Haven't tried with Vite / Snowpack yet.

**Comment by laurentpellegrino** [comment]
I am experiencing the same issue with version `9.3.6`. Unfortunately, our development flow that does not make use of bundling/transformation steps is broken due to this. Using `~9.1.0` is not enough as it seems that some other dependencies are not ESM compatible:

> The requested module '../../../intl-messageformat-parser/lib/index.js' does not provide an export named 'parseDateTimeSkeleton

**Comment by pyrocat101** [comment]
@moodyjmz

> Is it possible to use: [npmjs.com/package/nano-memoize](https://www.npmjs.com/package/nano-memoize)
> 
> As that supports es6 + seems to be faster than fast-memoize.

nano-memoize does not distribute ES modules as of today. Besides, its API interface and caching semantic is different from `fast-memoize`:

- `intl-messageformat` requires a reference to the memoization cache, which nano-memoize does not provide.
- `nano-memoize` compares multi-arguments call with referential equality check on each arguments, where as `fast-memoize` compared serialized JSON string of each argument (a poor man's comparison by value).

**Comment by pyrocat101** [comment]
@goremikin @hc-codersatlas @lpellegr

As @longlho said, we have no control over other libraries. And it is unfortunate that as of today, the open issue on `fast-memoize` hasn't received any response. Before `fast-memoize` has official support for ESM distribution, you can try this if you are using es-dev-server:

```js
// In es-dev-server.config.js
module.exports = {
  middlewares: [
    function rewriteFastMemoize(context, next) {
      if (context.url === '/node_modules/fast-memoize/src/index.js') {
        context.status = 302;
        context.redirect('https://jspm.dev/fast-memoize');
        return;
      }

      return next();
    },
  ],
};
```

The idea is rewriting the request to fast-memoize to JSPM CDN, which automagically serves a module in ESM format (converted via Rollup). I am pretty sure Vite and Snowpack also support custom rewrite rules, so if you are using those tools, it should be easy to port the middleware over.

**Comment by goremikin** [comment]
Thanks @pyrocat101 .

I have actually developed a plugin that transforms certain modules via Rollup into ESM. Here is an example for `es-dev-server`:

``` js
// keep simple key/value pairs for re-use
const storage = {};

async function build (packageName, moduleName) {
  const rollup = require('rollup');
  const resolve = require('@rollup/plugin-node-resolve').nodeResolve;
  const commonjs = require('@rollup/plugin-commonjs');
  const json = require('@rollup/plugin-json');

  // create a bundle
  const bundle = await rollup.rollup({
      onwarn (warning, warn) {
          // ignore warnings, as cannot do anything with 3rd party packages
      },
      input: {
          [moduleName]: packageName,
      },
      plugins: [json(), resolve(), commonjs({
        sourceMap: false
      })]
  });

  // need to be valid JS name
  const exportsName = moduleName.replace(/-([a-z])/g, g => g[1].toUpperCase());

  const outputOptions = {
      format: 'esm',
      name: exportsName,
      exports: 'named',
      compact: true
  };

  const { output } = await bundle.generate(outputOptions);

  // Output should not contain multiple chunks, as we supply the module
  // If this stops working, we need revisit the approach (e.g. store output in files)
  return output[0].code;
}

const babelTransformPlugin = (config = {}) => {
  const micromatch = require('micromatch');

  const {
      includePackages = []
  } = config;

  const packagesLength = includePackages.length;

  return {
      async transform (context) {
          if (context.response.is('js')) {
              for (let i = 0; i < packagesLength; i += 1) {
                  const packageConf = includePackages[i];
                  if (micromatch.isMatch(context.originalUrl, packageConf[0])) {
                      const packageName = packageConf[1];
                      const moduleName = packageConf[2] || packageName;
                      const code = storage[moduleName] || await build(packageName, moduleName);
                      storage[moduleName] = code;
                      return {
                          body: code
                      }
                  }
              }
          }
      }
  };
};

module.exports = babelTransformPlugin;
``` 

It can be used as:

```
plugins: [
  pluginCommonJs({
    includePackages: [
      [
          '**/node_modules/intl-messageformat/**',
          'intl-messageformat'
      ]
    ]
  })
]
```

The plugin has a few drawbacks, but is OK if just a small number of known modules need to be transformed.

**Comment by tvvignesh** [comment]
@pyrocat101 @longlho The other problem is that json is being imported here `@formatjs/ecma402-abstract/lib/src/NumberFormat/digit-mapping.json` and the browser throws and unexpected mimetype error with web-dev-server with es modules. Any workaround for this? Thanks.

<img width="670" alt="Capture" src="https://user-images.githubusercontent.com/1165845/93045996-56241300-f676-11ea-9cd8-4c33a8fc3519.PNG">

**UPDATE:** Never mind. Got it to work by using this module in the plugin: https://www.npmjs.com/package/es-dev-server-import-json Maybe this can also be imported as a ts file rather than a js file since browsers don't support JSON MIME natively,

My web-dev-server config file looks like this now. Seems very hacky though. Have to see how rollup handles this now.

```ts
import json from 'es-dev-server-import-json';

export default {
  open: false,
  appIndex: 'demo/index.html',
  nodeResolve: {
    customResolveOptions: {
      moduleDirectory: 'node_modules',
    },
  },
  middleware: [
    function rewriteFastMemoize(context, next) {
      if (context.url === '/node_modules/fast-memoize/src/index.js') {
        context.status = 302;
        context.redirect('https://jspm.dev/fast-memoize');
        return;
      }

      return next();
    },
  ],
  plugins: [json()],
  watch: true,
  rootDir: './',
  preserveSymlinks: true,
};

```

**Comment by allyraza** [comment]
I was trying to use this with nodejs v14 as it turns out if you have `"type": "module"` it will also not work because of missing `module.exports` from the bundled files I guess related to bundler
