### ISSUE TITLE
Can't install React-Intl

### ISSUE THREAD

**Issue by necheporenko** [formatjs/formatjs#1932]
**Which package?**
React-intl

**Describe the bug**
Can't install this dependence, because I got this error - " Couldn't find package "@formatjs/intl-getcanonicallocales@^1.3.1" required by "@formatjs/intl-datetimeformat@^2.3.0" on the "npm" registry."

**To Reproduce**

1. yarn add react-intl

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/20722449/89511692-ebf89280-d7da-11ea-93ea-b7d1840dff88.png)

**Desktop (please complete the following information):**

- OS: [Windows]
- NodeJS  Version [12.18.3]

**Comment by fahadsuhaib** [comment]
+1, Similar issue facing from last 1 hr, please update on this.

**Comment by rwenz3l** [comment]
+1, in our case `intl-datetimeformat/-/intl-datetimeformat-2.0.1.tgz` seems to be missing as well.

**Comment by necheporenko** [comment]
https://status.npmjs.org/

**Comment by longlho** [comment]
Seems to be a npm issue.
