### ISSUE TITLE
Document how to import specific functions from `intl-utils`

### ISSUE THREAD

**Issue by Floriferous** [formatjs/formatjs#1934]
Intl utils contains a lot of code, though it's mostly documented as the source of the `selectUnit` function.

In our case, it's the only code we use, yet the import path goes to the `index.js` file which imports everything else.

It looks like `import { selectUnit } from '@formatjs/intl-utils/lib/src/diff';` is the precise import path, but I just wanted to make sure if this was accurate, and if it can safely be used in production? In which case I think it'd helpful to document that for people who don't automatically treeshake the rest.

**Comment by longlho** [comment]
`selectUnit` is a migration tool for people to migrate from the old `FormattedRelative` to `FormattedRelativeTime` so it's not meant to stick around for a long time. `@formatjs/intl-utils` is basically private and isn't meant to be consumed by end user actually. See https://github.com/formatjs/formatjs/blob/main/packages/intl-utils/README.md#caveats as well. What's your use case?

**Comment by Floriferous** [comment]
We're sticking to `react-intl` v3, and I believe v3's `FormattedRelativeTime` doesn't automatically select the unit of a date, so we're using `intl-utils`? (maybe I'm wrong, I don't perfectly remember)

I guess if there's no reason to import `selectUnit` for most people, then we can close this issue.

**Comment by longlho** [comment]
Yes that's correct. In which case you should pin your `@formatjs/intl-utils` version to be totally safe.
Automatic unit selection has a lot of issues and was rejected at the spec level, just FYI.
