### ISSUE TITLE
Remove defaultMessage with babel?

### ISSUE THREAD

**Issue by ephys** [formatjs/formatjs#1936]
**Which package?**

babel-plugin-react-intl

**Is your feature request related to a problem? Please describe.**

While the defaultMessage is useful to us during development, it is redundant in production as the default locale is not treated any differently than the others and is moved to its own lazy-loaded bundle

Removing the defaultMessage for the production build would result in a noticeable reduction in our production bundle sizes

**Describe the solution you'd like**

I think this could be easily solved by adding an option to `babel-plugin-react-intl` to remove `defaultMessage`, like it already does for `description`

NB: If it makes things easier, I can send a PR for it

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by JustFly1984** [comment]
+1

**Comment by longlho** [comment]
It's there :) https://formatjs.io/docs/tooling/babel-plugin/#removedefaultmessage
