### ISSUE TITLE
Extract and Compile Messages via npm scripts

### ISSUE THREAD

**Issue by akash-pal** [formatjs/formatjs#1938]
**Which package?**
`@formatjs/cli`

**Is your feature request related to a problem? Please describe.**
The message extraction and compilation suggested in the docs are via cli.

- https://formatjs.io/docs/getting-started/message-extraction
- https://formatjs.io/docs/getting-started/message-distribution/#compiling-messages

 

**Describe the solution you'd like**
Instead of running via cli it can be used via npm script

**Describe alternatives you've considered**
Similar to below:
```
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "extract-messages": "formatjs extract \"src/**/*.js*\" --out-file lang/en.json --id-interpolation-pattern '[sha512:contenthash:base64:6]'",
    "compile-messages": "formatjs compile lang/en.json --ast --out-file compiled-lang/en.json"
  },
```

**Additional context**
Issue is **lang** folder will have multiple files such as 'en.json', 'fr.json'.
The compile script currently takes just one input path 'lang/en.json'
It needs to consider all the files in **lang** folder and output it to **compiled-lang** folder

**Comment by akash-pal** [comment]
I was able to batch all the compile scripts using a gulp task 
```
var gulp = require('gulp');
var run = require('gulp-run');

var fs = require('fs');
var path = require('path');

const sourcePath = 'src/lang';
const destPath = 'src/compiled-lang';

gulp.task('compile-messages', async function () {
    const directoryPath = path.join(__dirname, sourcePath);
    //passsing directoryPath and callback function
    fs.readdir(directoryPath, function (err, files) {
        //handling error
        if (err) {
            return console.log('Unable to scan directory: ' + err);
        }
        //listing all files using forEach
        files.forEach(function (file) {
            // Do whatever you want to do with the file
            return gulp.src(path.join(sourcePath, file))
            .pipe(run(`formatjs compile ${sourcePath}/${file} --ast --out-file ${destPath}/${file}`))
        });
    });
});
```

It would be better if we can have a script to do this -
`formatjs compile-folder`

**Comment by longlho** [comment]
`@formatjs/cli@2.6` should have this
