### ISSUE TITLE
Make "extract" & "compile" publicly available API functions

### ISSUE THREAD

**Issue by ervasive** [formatjs/formatjs#1939]
**Which package?**
@formatjs/cli

**Is your feature request related to a problem? Please describe.**
I think it would be great to be able to run translations extraction and compilation programmatically through Node API in addition to CLI interface

**Comment by longlho** [comment]
I think the extraction API is there but not documented. I'll take a look!

**Comment by longlho** [comment]
Can you also provide your use case?

**Comment by ervasive** [comment]
I think this can be generally helpful, but in my particular case, I'm working on a gatsby plugin for multilingual support with the idea for it to automatically handle message extraction and later compiling optimized translations resource(s) on production builds.

**Comment by ervasive** [comment]
> I think the extraction API is there but not documented. I'll take a look!

Yeah, it is. But as you said it is not documented, therefore it does not feel like the recommended way of using it.

Thank you

**Comment by longlho** [comment]
Yeah i do export them for testing so I'll document it

**Comment by ervasive** [comment]
> Yeah i do export them for testing so I'll document it

It seems like the "compile" function is tied to the CLI usecase and does not return the compiled output

**Comment by longlho** [comment]
`@formatjs/cli@2.5` should have this

**Comment by bertho-zero** [comment]
@longlho can `compileFolder` also be exported?

**Comment by longlho** [comment]
yeah can you submit a different GH issue?
