### ISSUE TITLE
Optional intl-messageformat-parser

### ISSUE THREAD

**Issue by ivan-kleshnin** [formatjs/formatjs#1945]
#### Which package?

React-Intl

#### Is your feature request related to a problem? Please describe.

`intl-messageformat-parser` dependency is heavier than all the other parts of the library combined.

Here are the build stats from one of my projects:

```
BUILD SIZE CONTRIBUTIONS (ordered by size DESC)

1) @apollo/client: 264.11 KB (8.95%)
2) next: 242.47 KB (8.22%)
3) intl-messageformat-parser: 125.95 KB (4.27%) <-- !!! TOP-3 of my frontend dependencies, heavier than React @_@
4) react-dom: 117.29 KB (3.97%)
...
14) react-intl: 29.77 KB (1.01%) <-- !!!
...
16) @formatjs/intl-utils: 28.66 KB (0.971%) <-- !!!
```

Now the fun part. I use `react-intl` for localization and I don't even rely on message formatting.

Yes, tree-shaking, minification and gzip do remove some of that weight... but it's still loaded in DEV, unnecessary bloating the assets.

#### Describe the solution you'd like

Is there an option to disable `intl-messageformat-parser` or replace it with something more lightweight?
At least for scenarios with L10N and without I18n like mine.

**Comment by longlho** [comment]
Right now the workaround is to stub out `intl-messageformat-parser` when you package and it should just be fine if you don't use that API.
Longer term we want to move message parsing to compile time instead of runtime so parsing is no longer needed and will be replaced w/ AST instead.

**Comment by ivan-kleshnin** [comment]
@longlho could you share a code example of correct and working stubbing if you already have one?

> Longer term we want to move message parsing to compile time instead of runtime so parsing is no longer needed and will be replaced w/ AST instead.

Nice to hear that.

**Comment by longlho** [comment]
What's the bundler you're using?

**Comment by ivan-kleshnin** [comment]
Webpack.

**Comment by longlho** [comment]
https://formatjs.io/docs/guides/advanced-usage/#react-intl-without-parser-40-smaller should have what you're looking for

**Comment by chybisov** [comment]
@longlho hi, I use react-intl in react-native as follows:

`import { defineMessages, useIntl } from 'react-intl';`

how can I get rid of `intl-messageformat-parser` package? Do I need to import react-intl somehow differently or write something in my babel config? All my messages are pre-compiled using extract/compile cli commands.

**Comment by longlho** [comment]
@chybisov I've added some docs on how to do that w/ webpack: https://formatjs.io/docs/guides/advanced-usage/#webpackconfigjs

**Comment by chybisov** [comment]
@longlho could you please add docs for react-native users? I use expo and have only babel config. Thank you!

**Comment by longlho** [comment]
Can you give https://www.npmjs.com/package/babel-plugin-module-resolver a try? I don't use react-native so personally I have not tried it

**Comment by chybisov** [comment]
@longlho thank you, I'll try.
