### ISSUE TITLE
Question about the documentation (IntlShape)

### ISSUE THREAD

**Issue by YoannBuzenet** [formatjs/formatjs#1946]
Hello,

I read this in the documentation about IntlShape, [here ](https://formatjs.io/docs/react-intl/api/#intlshape):

> It's made up of three parts:
> IntlConfig: The intl metadata passed as props into the parent <IntlProvider>.
> IntlFormatters: The imperative formatting API described below.

What is the third part please ? I see two elements in the list just under.

**Comment by longlho** [comment]
I think `three` was a typo, should only be `two` :) Thanks for reporting!
