### ISSUE TITLE
How can I use react-intl in non react file // vanilla js file ?

### ISSUE THREAD

**Issue by YoannBuzenet** [formatjs/formatjs#1948]
**Which package?**
**4.6.4**

**Describe the bug**
Can't find in the documentation how to proceed. Few examples found on stackOverFlow use APIs not available anymore.

Hello,
I'm trying to translate some content on my utils.js file.
I have understood that I should use Imperative API to get my Intl object in my utils file. 
But I couldn't understand how to proceed. I saw a lot of questions around this matter in closed issues or on StackOverFlow but answers are outdated and using old api's.

Could you please indicate me a way to use react-intl and translate vanilla js file in my react app (utils.js) ? What would you use ?

I think this could be a great help to add that info in the doc (and I would be happy to help!), for a lot of people trying. I asked on some react open source Slacks and no one could help me on that particular topic. (I just connected to your slack btw!)

Thank you for your time and your work,
Yoann

**Comment by YoannBuzenet** [comment]
Finally found out. It works well, but if I may, the doc was misleading, at least for a noob like me.

When it's written ([here](https://formatjs.io/docs/react-intl/api#createintl)): 

> // Call imperatively
> intl.formatNumber(20)
> 
> // Pass it to IntlProvider
> < RawIntlProvider value={intl}>{foo}< /RawIntlProvider>

It means you can use one **OR** the other if you want, but you don't have to use both.

So, to use react-intl in a vanilla JS file : 

`import { createIntl, createIntlCache } from 'react-intl';`
`import English from '../../translations/en-US.json'; //your messages translated with id`
`const cache = createIntlCache();`
`const intl = createIntl({
    locale: 'en-US',
    messages: English,
}, cache);`
`const number = intl.formatNumber(2000); //just use imperative way like you would with useIntl() hook or InjectIntl HOC`

I didn't try the JSX way.

**Comment by longlho** [comment]
https://formatjs.io/docs/getting-started/installation#minimal-application should have examples on using app w/o React
