### ISSUE TITLE
Undocumented / unclear option of babel-plugin-react-intl

### ISSUE THREAD

**Issue by cafca** [formatjs/formatjs#1952]
**Which package?**
babel-plugin-react-intl

**Describe the bug**

The docs at https://formatjs.io/docs/tooling/babel-plugin/ contain a (recommended) usage example

```
{
  "plugins": [
    [
      "react-intl",
      {
        "messagesDir": "./build/messages/"
      }
    ]
  ]
}
```

However, the `messagesDir` option is not explained on that page and not contained in [`options.ts`](https://github.com/formatjs/formatjs/blob/main/packages/babel-plugin-react-intl/options.ts).

**Expected behavior**

The option should be documented in the "Options" section of that page or removed from the example.

**Comment by longlho** [comment]
Thanks for reporting yes that option has been removed so we'll update the doc
