### ISSUE TITLE
Broken link, because of markdown syntax problem

### ISSUE THREAD

**Issue by hoschi** [formatjs/formatjs#1955]
https://formatjs.io/docs/react-intl/components/#formatteddisplayname

`You might need a [polyfill][../polyfills/intl-displaynames.md].`

"Edit this page" link to fix it by myself, isn't working :crying_cat_face:

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
Hmm the link works for me. Where does it take you?

**Comment by hoschi** [comment]
> "Edit this page" link to fix it by myself, isn't working

Today it brings me to the right link as well, strange!

**Comment by longlho** [comment]
oh I did fix the edit url I was curious about the polyfill link. Wanna PR to fix it? :)

**Comment by hoschi** [comment]
I thought I did already! But I created only a commit and a branch :facepalm:
Here you go https://github.com/formatjs/formatjs/pull/1960
