### ISSUE TITLE
formatjs-cli extract is not working with custom formatter file

### ISSUE THREAD

**Issue by repl-shenoy-sukumaran** [formatjs/formatjs#1969]
**Which package?**
@formatjs\cli

**Describe the bug**
when you run the **npm run extract** with formatter.js it shows error **Error: Cannot find module '/formatter.js'**
as per https://formatjs.io/docs/getting-started/message-extraction

**To Reproduce**
Clone the repo https://github.com/repl-shenoy-sukumaran/formatjs-cli-formatter

run 
npm install
npm run extract

**Expected behavior**
en.json should generate as per the custom formatter

**Screenshots**
![image](https://user-images.githubusercontent.com/13564819/90234300-18488a80-de3d-11ea-9fcf-6cc9050f1bca.png)

![image](https://user-images.githubusercontent.com/13564819/90234496-62ca0700-de3d-11ea-88e6-f7004cc2d899.png)

**Desktop (please complete the following information):**
- OS: Windows 10

**Smartphone (please complete the following information):**

- N/A

**Additional context**
N/A

Am i missing something? Or its a real bug?

**Comment by longlho** [comment]
Thanks a lot for reporting I'll take a look asap

**Comment by longlho** [comment]
`@formatjs/cli@2.7.3` should have the fix

**Comment by repl-shenoy-sukumaran** [comment]
Thank you for quick fix
