### ISSUE TITLE
Compiling message files with simple id: value structure

### ISSUE THREAD

**Issue by ivan-kleshnin** [formatjs/formatjs#1970]
**Which package?**
@formatjs/cli

**Is your feature request related to a problem? Please describe.**
Rather a question that request. Sorry if it was discussed already. Pretty basic yet my search in docs and github was unsuccessful.

I'd like to be able to store messages in a simple structure like this:

```json
{
  "id1": "message1", 
  "id2": "message2"
}
```

instead of 

```json
{
  "id1": {"defaultValue": "message1"}, 
  "id2": {"defaultValue": "message2"}
}
```

The first variant hovewer can't be compiled:

```
$ /Users/someuser/someproject/node_modules/.bin/formatjs compile l10n/messages/ru.json --ast --out-file l10n/messages/ru-compiled.json
TypeError: Cannot read property 'charCodeAt' of undefined
```

Our team has a convention of using meaningful keys where for example 

`alert.warning`  means "*warning* used in some *alert* context". With this convention we don't really need description fields.
We also fill the initial message file manually and then synchronize few translation files manually. Maybe it's not the best workflow but it works for us.

More important is the fact that some docs section (e.g. https://formatjs.io/docs/core-concepts/basic-internationalization-principles) describe this format as valid. So I'm guessing if it's some current limitation of @formatjs/cli, my misuse of a tool or a determined behavior.

**Comment by longlho** [comment]
Looks like u need `--format simple` https://formatjs.io/docs/tooling/cli#builtin-formatters

**Comment by ivan-kleshnin** [comment]
Yep, that works. Thank you.
