### ISSUE TITLE
[react-intl] "defaultRichTextElements" was specified but "message" was not pre-compiled.

### ISSUE THREAD

**Issue by foucdeg** [formatjs/formatjs#1972]
**Which package?**
react-intl v5.6.2

**Describe the bug**
A console error is printed for every translated message:  

> "defaultRichTextElements" was specified but "message" was not pre-compiled.

But I did not specify the `defaultRichTextElements` option.

**To Reproduce**

This is my IntlProvider config: https://github.com/foucdeg/passe-un-dessin/blob/master/frontend/src/components/Root/Root.tsx#L39

You will see many instances of the error on the homepage of my app: https://passe-un-dessin.fouc.net/

Code for that page: https://github.com/foucdeg/passe-un-dessin/blob/master/frontend/src/pages/Home/Home.tsx

**Expected behavior**
The error should not be triggered because I did not activate the `defaultRichTextElements` option.

**Desktop (please complete the following information):**

- OS: macOS 10.15.5
- Browser: Chrome
- Version: 84

**Additional context**

This probably started happening with a recent new version (I have an automatic version upgrade tool). Most likely since 5.5.0 and the introduction of `defaultRichTextElements`.

**Comment by longlho** [comment]
Thanks for reporting. `react-intl@5.6.3` should have the fix

**Comment by foucdeg** [comment]
Fixed indeed, thanks!
