### ISSUE TITLE
Import error when using react-intl

### ISSUE THREAD

**Issue by MateoKruk** [formatjs/formatjs#1973]
**Which package?**
react-intl

**Describe the bug**
I tried installing `react-intl` on a react project with typescript using create-react-app and when I try to import the component `IntlProvider` I get the following error:

<img width="1074" alt="Screen Shot 2020-08-15 at 20 48 21" src="https://user-images.githubusercontent.com/9438362/90323509-cd13a200-df38-11ea-9a3f-1326ef4decad.png">

**Comment by longlho** [comment]
Looks like your typescript version might be old

**Comment by MateoKruk** [comment]
Yup you're right! Updated typescript to the latest version and it worked. Thanks!
