### ISSUE TITLE
Option to provide default timezone

### ISSUE THREAD

**Issue by RichardLindhout** [formatjs/formatjs#1989]
**Which package?**

@formatjs/intl-datetimeformat

**Is your feature request related to a problem? Please describe.**
I'm using this polyfill as hermes does not support https://github.com/facebook/hermes/issues/23 Intl yet.

**Describe the solution you'd like**
```javascript
var formatjs = require('@formatjs/intl-datetimeformat')
formatjs.setTimeZone('Europe/Amsterdam')
```

E.g. I could require my library users to put this in their index.js file
```javascript
if (!!global.HermesInternal) {
  require('@formatjs/intl-getcanonicallocales/polyfill')

  require('@formatjs/intl-pluralrules/polyfill')
  require('@formatjs/intl-pluralrules/locale-data/nl')

  require('@formatjs/intl-relativetimeformat/polyfill')
  require('@formatjs/intl-relativetimeformat/locale-data/nl')

  require('@formatjs/intl-listformat/polyfill')
  require('@formatjs/intl-listformat/locale-data/nl')

  require('@formatjs/intl-displaynames/polyfill')
  require('@formatjs/intl-displaynames/locale-data/nl') // locale-data for en

  require('@formatjs/intl-numberformat/polyfill')
  require('@formatjs/intl-numberformat/locale-data/nl.js')

  require('@formatjs/intl-datetimeformat/polyfill')
  require('@formatjs/intl-datetimeformat/locale-data/nl.js')

  require('@formatjs/intl-datetimeformat/add-all-tz.js')

  require('@formatjs/intl-locale/polyfill')

  var formatjs = require('@formatjs/intl-datetimeformat')
  formatjs.setTimeZone('Europe/Amsterdam')
}
```

**Describe alternatives you've considered**
Using the timezone option in the formatter, but that does not work as I want since the user would need to provide a timezone to my library which could result in unexpected things on other platforms (since the Date is just the native one and could have another timezone)

**Comment by longlho** [comment]
latest version should have `__setDefaultTimeZone` that allows you to do this

**Comment by RichardLindhout** [comment]
Amazing!!

**Comment by longlho** [comment]
Keep in mind this method is not in the spec so u should check for existence before using it & after you've add timezone data (since it verifies if the timezone is correct/if we have data for it)

https://formatjs.io/docs/polyfills/intl-datetimeformat/#default-timezone for posterity

**Comment by RichardLindhout** [comment]
Thanks a lot for exposing this function!

**Comment by RichardLindhout** [comment]
Example for future reference
```ts
// in your index.js file
if (!!global.HermesInternal) {
  require('@formatjs/intl-getcanonicallocales/polyfill')

  require('@formatjs/intl-pluralrules/polyfill')
  require('@formatjs/intl-pluralrules/locale-data/nl') // use your language files

  require('@formatjs/intl-relativetimeformat/polyfill')
  require('@formatjs/intl-relativetimeformat/locale-data/nl') // use your language files

  require('@formatjs/intl-listformat/polyfill')
  require('@formatjs/intl-listformat/locale-data/nl') // use your language files

  require('@formatjs/intl-displaynames/polyfill')
  require('@formatjs/intl-displaynames/locale-data/nl') // use your language files

  require('@formatjs/intl-numberformat/polyfill')
  require('@formatjs/intl-numberformat/locale-data/nl') // use your language files

  require('@formatjs/intl-datetimeformat/polyfill')
  require('@formatjs/intl-datetimeformat/locale-data/nl') // use your language files

  require('@formatjs/intl-datetimeformat/add-all-tz')

  require('@formatjs/intl-locale/polyfill')

  // https://formatjs.io/docs/polyfills/intl-datetimeformat/#default-timezone
  let RNLocalize = require('react-native-localize')
  if ('__setDefaultTimeZone' in Intl.DateTimeFormat) {
    Intl.DateTimeFormat.__setDefaultTimeZone(RNLocalize.getTimeZone())
  }
}
```

**Comment by ftzi** [comment]
Hey, I don't want to open a new issue now, but __setDefaultTimeZone is throwing error on valid timezone names:

console.log(RNLocalize.getTimeZone()); // 'America/Bahia'

if ('__setDefaultTimeZone' in Intl.DateTimeFormat) {
  (Intl.DateTimeFormat as any).__setDefaultTimeZone(RNLocalize.getTimeZone());
}

throws: Invalid timeZoneName. (using pollyfills in native, can successfully call new Intl.DateTimeFormat())

Edit: Find out that I had to also `import '@formatjs/intl-datetimeformat/add-all-tz.js'`. Now is working
