### ISSUE TITLE
Broken/confusing path on the docs site 

### ISSUE THREAD

**Issue by atomcorp** [formatjs/formatjs#1996]
**Which package?**
website

**Describe the bug**
404 when you visit https://formatjs.io/docs/react-intl. It's one of the top search results for me when searching formatjs react.

**Expected behavior**
I don't know if there was an index page that got removed or it should just forward to https://formatjs.io/docs/react-intl/components

**Comment by longlho** [comment]
Thanks for reporting we'll take a look
