### ISSUE TITLE
[RFC] Enforcing AST at runtime in `FormattedMessage`/`formatMessage`

### ISSUE THREAD

**Issue by longlho** [formatjs/formatjs#1998]
Hello everyone,

This is meant to serve as a discussion thread for the next big change within `react-intl`'s `FormattedMessage`/`formatMessage` that might be backwards incompatible.

## Context

At the core of message formatting in react-intl is our parser: [intl-messageformat-parser](https://formatjs.io/docs/intl-messageformat-parser). The parser accounts for roughly [40% of the package's weight](https://bundlephobia.com/result?p=react-intl@5.6.5) which is not trivial. Besides, parsing a message at runtime also incurs a fairly significant cost **at scale** (7000+ messages for 100ms+) since it is blocking. This thread is meant to propose dropping the parser at runtime and relying on build toolchain to compile instead.

## Goals

- Propose new runtime mechanism for `FormattedMessage`/`formatMessage`

## Non-goals

- Change message syntax

## Decision Matrix

| | Status Quo | Enforcing AST |
|--|--|--|
| Build Process | 🟢 Nothing | 🟡 Requires usage of [@formatjs/cli](https://formatjs.io/docs/getting-started/message-distribution) |
| DevEx | 🟢 Nothing | 🟢 Nothing |
| Runtime Performance | 🔴  Nothing | 🟢 Remove the need to parse at runtime, which is 100ms+ for 7000+ messages |
| Bundle size | 🔴 Nothing | 🟢 Remove parser, which reduce bundle weight by 40% |

For the majority of use cases which is a lot less than thousands of messages, the tradeoff effectively comes down to reduced bundle weight vs extra build step.

## Prior Art

I believe js-lingui also precompile messages.

**Comment by stofolus** [comment]
Hi!

I think that this could be a great change since it's an easy optimisation. The biggest downside in my opinion is that it makes it a bit harder to use for new users / small projects. So an easy way to fix that would be to have the runtime parser as an opt-in feature. 

Maybe as something like this:
```javascript
const messagesInFrench = {
  myMessage: "Aujourd'hui, c'est le {ts, date, ::yyyyMMdd}",
}
const astMessagesInFrench = intlMessageParser(messagesInFrench);

const cache = createIntlCache()

const intl = createIntl(
  {
    locale: 'fr',
    defaultLocale: 'en',
    messages: astMessagesInFrench,
  },
  cache
)
```

Also, do you have any thoughts on how `defaultMessage` would work with the suggested change?

**Comment by longlho** [comment]
`defaultMessage` would also be pre-parsed using https://formatjs.io/docs/tooling/babel-plugin#ast or https://formatjs.io/docs/tooling/ts-transformer#ast

Right now AST is opt-in already so you can already pre-parse (I know some production systems are using it). When doing so you can actually alias `react-intl` to `react-intl/react-intl-no-parser` and get a significantly smaller package.

The documentation right now nudges people towards this behavior and the gist of the RFC is to make this the default behavior. Maybe distributing a dev version with parser & prod version w/o parser is the other option?

**Comment by jquense** [comment]
I am all for removing the parser if possible but how much larger is the message AST format? My naive guess would be that at scale it'd actually be a bundle increase to include the compiled AST directly after a certain number of messages. e.g. the increase diff between the string and AST format will at some point out pace the size of the parser? Any insight on where this line is or how likely it is to matter?

**Comment by longlho** [comment]
Good question @jquense 

| Locale | Original | AST | Diff |
|--|--|--|--|
| en-GB | 314 kB | 391 kB | +77k |
| ru | 548 kB | 542 kB | -6k |
| zh-CN | 357 kB | 406 kB | +49k |

Those are sizes for 13000 messages. Parser size is around 21K consistently. So looks like the breakeven point depends on the complexity of the message, size & locale itself

| Locale | Breakeven |
|--|--|
| en-GB | 4000 messages |
| ru | 0 |
| zh-CN | 6000 messages |

**Comment by roderickhsiao** [comment]
From Tinders's use case, 

we have around 1300 messages 102kb and we dehydrate the message from server side to client side (JSON), after measuring the initial lighthouse score, we decide not to rollout the pre-parsed AST version as it negatively affect the score. 
The increase in page load size seems to be expensive for 3g network conditions and also increase the initial render parsing. 

Not sure if it is worth it to trade a runtime 100ms for connection time for bigger payload?

**Comment by stofolus** [comment]
One thing to take into consideration is that the `babel-plugin`& `ts-transform` won't work in projects created from CRA (and other similar projects). So I think it would be important to have a lot of documentation on why it won't work and what the workaround is (Use the package with the parser included).

Given that you said that the AST solution is already opt-in I'm not sure what the reason would be for changing the default? For me it seems better to have a (maybe) slower but easier solution as the default and keeping the more complicated and maybe better performing one as an opt in. 

It keeps the barrier of entry lower for new users and small projects and gives power users the power too choose.

**Comment by longlho** [comment]
@roderickhsiao thanks a lot for sharing. The AST right now is pretty verbose but can be packed even further. Would you mind sharing some more details regarding your experiment?

@stofolus that's a good point. It's a shame that CRA doesn't allow further toolchain customization. That's kinda a deal breaker then.

Thanks everyone for the feedback :)

**Comment by roderickhsiao** [comment]
Thanks @longlho for the hard work, we actually pretty thrilled to see if we can improve the performance.
Due to the complexity of the app, I'll need some more time to have solid experiment data related to the pre-parsed AST changes, but I'll update team once I have some more concrete details.

Cheers

**Comment by longlho** [comment]
Yeah the primary driver for this came from internal at DBX as well, along with use cases like React Native/Electron since bundling isn't really a concern in those environments.
