### ISSUE TITLE
Fast_glob finds no files on windows because of \ insertion

### ISSUE THREAD

**Issue by vincekieft** [formatjs/formatjs#2009]
**Which package?**
CLI

**Describe the bug**
Hi all,
When im using the CLI compile-folder command on windows, fast-glob cant find .json files in folder because of incorrect path formatting.
In the CLI this line finds the files to compile files = `fast_glob_1.sync(path_1.join(folder, '*.json'))`. But the output of path_1.join is `<YOUR_PATH>\*.json` which results in zero files found. When i change the CLI code to a hardcoded path `<YOUR_PATH>/*.json` the files are found.
I think on windows the back slash is incorrect and a forward slash is needed.

**To Reproduce**
1. Have windows OS
2. Create a folder to compile and add atleast a single *.json file
3. Run the compile-folder
4. Exception will be thrown: No files found

**Expected behavior**
Expected to find files and format paths with `/` instead of `\`

**Desktop (please complete the following information):**

- OS: Windows

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
