### ISSUE TITLE
Missing UMD bundle for multiple packages

### ISSUE THREAD

**Issue by JakeChampion** [formatjs/formatjs#2013]
**Which package?**
@formatjs/intl-datetimeformat
@formatjs/intl-displaynames
@formatjs/intl-getcanonicallocales
@formatjs/intl-listformat
@formatjs/intl-numberformat
@formatjs/intl-pluralrules
@formatjs/intl-relativetimeformat

**Describe the bug**
Up to version 2.0.2 @formatjs/intl-datetimeformat had a UMD bundle at location dist/umd/polyfill.js and it was removed in version 2.1.0 and I don't think has been re-added since then.

Up to version 3.0.2 @formatjs/intl-displaynames had a UMD bundle at location dist/umd/polyfill.js and it was removed in version 3.1.0 and I don't think has been re-added since then.

Up to version 1.2.10 @formatjs/intl-getcanonicallocales had a UMD bundle at location dist/umd/polyfill.js and it was removed in version 1.3.0 and I don't think has been re-added since then.

Up to version 3.0.2 @formatjs/intl-listformat had a UMD bundle at location dist/umd/polyfill.js and it was removed in version 3.1.0 and I don't think has been re-added since then.

Up to version 5.0.2 @formatjs/intl-numberformat had a UMD bundle at location dist/umd/polyfill.js and it was removed in version 5.1.0 and I don't think has been re-added since then.

Up to version 3.0.2 @formatjs/intl-pluralrules had a UMD bundle at location dist/umd/polyfill.js and it was removed in version 3.1.0 and I don't think has been re-added since then.

Up to version 6.0.2 @formatjs/intl-relativetimeformat had a UMD bundle at location dist/umd/polyfill.js and it was removed in version 6.1.0 and I don't think has been re-added since then.

**To Reproduce**

1. Go to https://unpkg.com/browse/@formatjs/intl-datetimeformat@2.0.2/
2. You should see a `dist` folder
3. Go to https://unpkg.com/browse/@formatjs/intl-datetimeformat@2.1.0/
4. You should no longer see a `dist` folder
5. Repeat steps 1 to 4 for the other packages and versions listed above.

**Expected behavior**
I would have expected the UMD bundle to still exist in the packages in minor releases such as these.

**Additional context**
It is also how polyfill-library (https://polyfill.io) can use these package since polybill-library does not use `require` or `import` at all.

**Comment by longlho** [comment]
Thanks for reporting. I didn't know polyfill-library needs UMD actually so will add them back. Tests did pass on the initial PR though so should I submit an issue for that on your side?

**Comment by JakeChampion** [comment]
Yes please 👍
