### ISSUE TITLE
Add minimal react-intl version that does not rely on react dependency

### ISSUE THREAD

**Issue by vincekieft** [formatjs/formatjs#2014]
**Which package?**
react-intl

**Is your feature request related to a problem? Please describe.**
I want to use react-intl to do translations for my backend API error messages in a consistent manner that matches with my frontend. But i dont want to depend on react since it would increase the build size.

**Describe the solution you'd like**
Make it so react-intl doesnt depend on react. I know this is a weird request since the package is called "react-intl".
Maybe a minimal base package could be made that just contains the core functionality like:
- createIntl
- createIntlCache
So it can be used outside react aswell

**Additional context**
![image](https://user-images.githubusercontent.com/22029424/90934731-1ca71180-e402-11ea-9fb8-98e9fa12b4fc.png)

**Comment by longlho** [comment]
If u don't need `React` u can use https://www.npmjs.com/package/@formatjs/intl instead which contains the same imperative API
