### ISSUE TITLE
Add --watch mode to CLI

### ISSUE THREAD

**Issue by nodkz** [formatjs/formatjs#2021]
First of all, you make changes so faaaast ;)

I was super disappointed that you [removed message extraction](https://github.com/formatjs/formatjs/commit/47ca556c1405eec7b7b2660275ae84a019112b2b) from babel-plugin-react-intl 8.0.0. 
Hm, it was really very strange and rash decision while CLI is weak. For example, CLI doesn't have a `--watch` mode for extraction. With babel transpilation I have quite fast extractions, but extracting new messages via CLI with nodemon for 2k files is quite slow.

@longlho have you any plans to add `chokidar` to CLI and provide `--watch` mode?

Tnx.

**Comment by longlho** [comment]
Can you provide some details regarding your workflow and the reasons for running extraction in `watch` mode?
The decision wasn't really rash. There are a couple of reasons that are too long for a commit message:
- babel plugins don't work with `create-react-app` out of the box.
- babel plugins are stacked and are subject to previous plugin modifying AST in a way that results in us not being able to extract/verify.
- We don't know **when** babel plugin are done running through a codebase so we can't aggregate messages, thus reducing our abilities to detect message collision. As a result there are tools built on top of `babel-plugin-react-intl` that manage that.
- Writing out files as a side effect of code transformation (in `babel-plugin-react-intl` case) becomes hard to work with in hermetic build systems like `bazel`.

At the end of the day the difference is in the workflow and [our workflow](https://formatjs.io/docs/getting-started/application-workflow) is modeled after usages at Yahoo & Dropbox which is geared towards huge codebases so I might be missing something here.

**Comment by nodkz** [comment]
Our developers develop services in watch mode using nextjs (with some patch which helps to auto-reload locale files on its change). I wrote scripts that combine all translations into one file and merge new keys to additional languages. So developers may change locales for additional languages during development, and they automatically appear in their apps without app restart.

When developers finish work, they commit components with generated new locales. On commit, our TMS (Weblate is kicked by webhook from GitLab on commit) fetch changes and loads locale files to its database for translation. So we don't have a CI phase where we can extract messages. It must be done before commit.

Of course, I can add [husky](https://www.npmjs.com/package/husky) hook which will generate locales before commit. And it helps to provide all locales to TMS. But we lose hot reloading with new translations obtained via the manual file changes for additional languages or via fetching new translation from repo without restarting dev server.

For keeping hot reload ability I forced to watch src files via nodemon, and if some file is changed then run CLI extract. It will be nice if we can reduce these unnecessary files traversing inside src/ folder.

Watch mode helps to provide better DX.

**Comment by longlho** [comment]
> But we lose hot reloading with new translations obtained via the manual file changes for additional languages or via fetching new translation from repo without restarting dev server.

Hmm how does `babel-plugin-react-intl` help u solve this?

And yes adding precommit hook to run extraction before commit is the equivalence of CI doing extraction. I guess that part I'm not understanding is whether extraction for every file change in real time is necessary for your use case.

**Comment by nodkz** [comment]
Current workflow:
- `babel-plugin-react-intl` v7 is used in nextjs dev server with webpack
- after dev server start, webpack tracks changes in source codes and rebuild scripts using babel
- in such scenario, `babel-plugin-react-intl` exports messages only for changed files
- I wrote a daemon with chokidar which tracks changes in `messageDir`, and if there something changed then regenerate whole combined `locales` files
  - combined base language file it rewrites completely
  - additional language files it just extends. Even more if some files were removed from `messageDir` after daemon start - it removes its keys from additional language files.
- all combined locales' files are watched by nextjs dev server and automatically reloads.

With such workflow developers are able:
- to change any module with React Component
- ensure that everything correctly extracted in the combined locale files
- provide some translations to additional locales
- and watch how they look at the page without restarting dev server

So for source code watcher is webpack with `babel-plugin-react-intl`
For extracted translations watcher is my daemon script
For combined locales watcher in nextjs dev server

With new `babel-plugin-react-intl` i need to launch one more watcher for source code files besides webpack. And for big projects it can be a problem on some weak developers' machines. So the option `messageDir` helps me to reduce the number of watching files.

**Comment by longlho** [comment]
so `provide some translations to additional locales` is the only unsupported workflow right now and I haven't seen it a ton so this is pretty niche. I'll keep this issue open in case there're more asks for this, otherwise stalebot will close this automatically.
