### ISSUE TITLE
react-intl dependencies now require `ESNext` to build in TypeScript projects (a breaking change without changing the version of react-intl)

### ISSUE THREAD

**Issue by dturcotte** [formatjs/formatjs#2023]
**Which package?**

I'm seeing this problem as a consumer of `react-intl`, but it's really a change in any of these packages that now use `@types/es-abstract`, stemming from https://github.com/formatjs/formatjs/commit/03701196379aa0584d0a40dcf1e75095489e171f#diff-e5e546dd2eb0351f813d63d1b39dbc48

**Describe the bug**
In TypeScript projects, `react-intl` now requires `ESNext` `lib` (or up to `es2020`) to build. This is a breaking change seen without even updating the version of `react-intl`- see the repro case below

**To Reproduce**

Here is a repository with two projects - both projects have identical `package.json` and `tsconfig.json` each with a pinned dependency on `react-intl@4.7.6` however one builds and the other does not:
https://github.com/dturcotte/react-intl-ts-lib-repro

I noticed this because old projects who had pre-existing `yarn.lock` files are fine, however new projects will see newer versions of `react-intl`'s indirect dependencies such as `@formatjs/intl-getcanonicallocales`, `@formatjs/intl-numberformat`, `intl-messageformat-parser`, and others - these newer versions now depend on `@types/es-abstract` and won't build in a project with the same setup. This can also be seen if the dependencies in `yarn.lock` are re-resolved for any reason, such as when updating to `react-intl` v5.

**Expected behavior**
Definitely open to suggestions, but here are a few ideas to mitigate this:

1. Use major versions for this change so we can at least stop breaking on indirect dependencies and buy some time
2. Perhaps `@types/es-abstract` can be cleaned up to be more flexible with the TypeScript build environment
3. Can `@types/es-abstract` be a `devDependency` to allow only the necessary usage to be shipped? (admittedly I haven't looked too closely into how you're using this so it may not be a valid solution)
4. Removing the dependency on `@types/es-abstract` would solve the issue, though this is probably my least constructive suggestion

I'd compare this situation to how you approached support for `esnext.intl` and provided polyfills such as `@formatjs/intl-pluralrules` and `@formatjs/intl-relativetimeformat`. We are free to either adjust our TypeScript `lib` or use the polyfills, it's a good solution. However I can't imagine you want to be responsible for all of `ESNext` when much of it has nothing to do with intl.

**Desktop (please complete the following information):**

- OS: OSX High Sierra
- Chrome
- Version 84

**Comment by longlho** [comment]
Thanks for reporting we'll take a look asap

**Comment by longlho** [comment]
latest version should have the fix
