### ISSUE TITLE
@formatjs/intl-numberformat@5.5.5 missing index.d.ts file

### ISSUE THREAD

**Issue by hellatan** [formatjs/formatjs#2031]
**Which package?**
@formatjs/intl-numberformat@5.5.5

**Describe the bug**
When running `tsc`, the following error is thrown:
```
Cannot find module '@formatjs/intl-numberformat' or its corresponding type declarations.
```
I checked 

**To Reproduce**

1. Run `tsc` when this module is installed
2. See error

Simply listing out the directory also shows a lack of `index.d.ts` file:
```
ls -la node_modules/@formatjs/intl-numberformat
total 360
.
..
LICENSE.md
README.md
_validate_dist-base_options.optionsvalid.d.ts
_validate_dist-esm_options.optionsvalid.d.ts
lib
locale-data
package.json
polyfill-force.d.ts
polyfill-force.d.ts.map
polyfill-force.js
polyfill.d.ts
polyfill.d.ts.map
polyfill.js
polyfill.umd.js
polyfill.umd.min.js
should-polyfill.d.ts
should-polyfill.d.ts.map
should-polyfill.js
```

**Expected behavior**
the `index.d.ts` file to be available for type checking

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: osx 10.15.5
- Browser N/A
- Version N/A

**Smartphone (please complete the following information):**
N/A

**Comment by longlho** [comment]
How are you consuming this? There's no index file thus no index.d.ts

**Comment by hellatan** [comment]
I was going off of the package.json thinking that there should be a `index.d.ts` file for the types of this package: https://github.com/formatjs/formatjs/blob/main/packages/intl-numberformat/package.json#L19

It's a dependency of a dependency of a dependency - `intl-messageformat` -> `intl-messageformat-parser` -> `@formatjs/intl-numberformat`

which is using this import:
```
import { NumberFormatOptions } from '@formatjs/intl-numberformat';
```

Was there ever a `index.d.ts` file in versions prior to 5.5.5?

**Comment by longlho** [comment]
Hmm let me double check thanks for reporting

**Comment by longlho** [comment]
What version of intl-messageformat r you using?

**Comment by hellatan** [comment]
`intl-messageformat@8.4.1` which has `intl-messageformat-parser@5.4.2`

**Comment by longlho** [comment]
Do you have a repro?

**Comment by hellatan** [comment]
i do not since i just ran into this on my work account which is private.

**Comment by hellatan** [comment]
it looks like prior to v5, the type def file was pointed to `lib/intl-numberformat.d.ts` - https://github.com/formatjs/formatjs/blob/76e649f2f673c1344fe29ccf739d4b4ebd573ead/packages/intl-numberformat/package.json#L20 (`@formatjs/intl-numberformat@4.2.11`)

**Comment by hellatan** [comment]
oh...looks like v5 has the same actually - https://github.com/formatjs/formatjs/blob/73c37283a24f515ade685f81e3d886f37639914b/packages/intl-numberformat/package.json#L20

it looks like 5.4.0 changed the type def file to just `intl-numberformat.d.t` -
https://github.com/formatjs/formatjs/blame/d110f8e15ea49a416741445ad102340cc3a82d1a/packages/intl-numberformat/package.json#L19 but that's not in the dir with that change.

and then 5.5.5 made the change to `index.d.ts`

**Comment by hellatan** [comment]
running the type checker when `@formatjs/intl-numberformat@5.5.4` is installed passes just FYI.

**Comment by longlho** [comment]
oh we're at `intl-messageformat@9` now so I recommend u upgrading to that.

**Comment by hellatan** [comment]
> oh we're at intl-messageformat@9 now so I recommend u upgrading to that.

oh geez...i think this one is dictated by `react-intl` though (which we are on 4.3.1, which has a dep of `intl-messageformat@8.4.1`) so we'd need to upgrade in order to get to `intl-messageformat@9`.

**Comment by kurtinatlanta** [comment]
This is still a problem, even with intl-messageformat 9.x.

Your package.json points to index.js as the 'main' file for intl-numberformat (lines 18 and 19), but index.js doesn't exist.

I have had to revert to @formatjs/intl-numberformat 5.5.4 as a result.

**Comment by kachkaev** [comment]
```sh
 yarn why @formatjs/intl-numberformat

=> Found "@formatjs/intl-numberformat@5.7.6"
```

```sh
yarn lint:tsc

node_modules/intl-messageformat-parser/src/skeleton.d.ts:2:37 - error TS2307: Cannot find module '@formatjs/intl-numberformat' or its corresponding type declarations.
```

Reverting to `@formatjs/intl-numberformat` to `5.5.4` by pinning it in `package.json` helps.
