### ISSUE TITLE
Handle attribbutes on RichText formatting

### ISSUE THREAD

**Issue by denke8** [formatjs/formatjs#2037]
**Is your feature request related to a problem? Please describe.**
I'm building a widget, and some of the translations can be overwritten by the users on an admin interface, they need to be able to use basic formatting like `<i>text</i>` which works just fine, but they also need to be able to add links aswell: `<a href="/foo" _target="blank">Click Me</a>`.

I use the recently added `defaultRichTextElements` attribbute on IntlProvider to be able to render these components, but I found no solutions to be able to handle sg. like `<a href="/foo" _target="blank">Click Me</a>`.

**Describe the solution you'd like**
The defaultRichTextElements interface could be modified to also return the attribbutes like instead of:
  `defaultRichTextElements: { a: (...chunks) => <a>{chunks}</a> }`
we could use the following interface:
  `defaultRichTextElements: { a: (attribbutes, chunks) => <a {...attribbutes}>{chunks}</a> }`

**Describe alternatives you've considered**
Considered 
- parsing the translation template (prior to providing them as messages to the IntlProvider) with DOMParser
- Extracting the attribbutes to a special (parent) tag
- re-serializing it with XMLSerializer
so `<a href="/foo" _target="blank">Click Me</a>` would be converted to `<WithAttribbutes>base64_coded_attribbutes<a>Click Me</a></WithAttribbutes>`
-Provide a `WithAttribbutes` component as `defaultRichTextElements` too, which could process the base64, `React.cloneElement` the `<a>` and add the required attribbutes

But this solution is messy to say the least

**Comment by hjylewis** [comment]
What's your use-case? Why do your user's need control over the anchor tag attributes?

I'd worry about allowing users control over your widget's HTML. Wouldn't this introduce an XSS vulnerability? The user could change the translation to `<a href="dangerous_web_site.com" _target="blank">Click Me</a>` and your widget would naively render that dangerous link dynamically. 

The point to react-intl's Rich Text Formatting support is to avoid rendering dynamic HTML and thus avoid XSS attacks. The HTML (in the form of JSX) only takes place on the JS side not in the translations.

**Comment by denke8** [comment]
Hi @hjylewis Thanks for the answer!

The widget is controlled by the owner of the site from a webgui external from the site in question. So the "user" who sets these translations in the admin interface is the owner of the site and has to be able to alter the host site's code itself to integrate the widget, so there is no need to protect the site from the user, XSS is not an issue.

**Comment by longlho** [comment]
We neither parse attributes from rich text tags nor allow it embedded in the message so this is not something we'd support.

**Comment by joaogarin** [comment]
> The widget is controlled by the owner of the site from a webgui external from the site in question. So the "user" who sets these translations in the admin interface is the owner of the site and has to be able to alter the host site's code itself to integrate the widget, so there is no need to protect the site from the user, XSS is not an issue.

I agree this is valid, this is also the use case we have. And I would guess that people having the access / permissions to add translations to any site usually are admins and should be allowed e.g. including a link..I think some API to handle this would definitely be of use.
