### ISSUE TITLE
ts-transformer: wrong Typescript version gets installed with TS v4 (should be peer-dependency instead?)

### ISSUE THREAD

**Issue by unframework** [formatjs/formatjs#2043]
**Which package?**
ts-transformer

**Describe the bug**
My project uses the recently-released Typescript 4 (actual installed version is 4.0.2). The ts-transformer package (v2.7.10) relies on TS ^3.8, which results in that older copy of Typescript package to be installed under its node_modules subfolder. Then, because it uses 3.8 helper functions on an AST produced by 4.0 code, it silently fails to work during Webpack compilation.

As an aside, should TS be declared as a peer-dependency of ts-transformer? At least in that case it would not silently try to install an older copy of TS? Anyway, hope this information helps, thanks!

**To Reproduce**

1. Set up a project that uses typescript@^4.0
2. Install ts-transformer dependency
3. Use ts-transformer in Webpack ts-loader config

**Expected behavior**
Normal working behaviour of ts-transformer.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome 84
- Version: 2.7.10

**Comment by longlho** [comment]
fixed in latest. It's actually not `peerDependencies` bc we're not compatible :)
