### ISSUE TITLE
Extracting messages from Flow typed React projects

### ISSUE THREAD

**Issue by steponas** [formatjs/formatjs#2051]
**Which package?**
cli, babel-plugin-react-intl, ts-transformer

**Is your feature request related to a problem? Please describe.**
My situation:
* I am working on projects which use [Flow](http://flowtype.org/) instead of TS for type checks.
* In v8.0.0 of babel-plugin-react-intl, the support for extracting messages to json files was dropped.
* @formatjs/cli seems to support TS only, due to ts-transformer. Running it on my codebase to extract the messages produce typescript parsing errors, which is kinda expected.

**Describe the solution you'd like**
I'd like to find a way to put the extraction back to the webpack pipeline, and honestly for it to be type agnostic (or require pure JS for that to work).

Maybe I am missing something and there's an easy way to use cli with non-ts projects, or use ts-transformer directly in the pipeline, AFTER the flow parser has stripped the types away and the result is plain javascript

I hope someone will enlighten me.

**Comment by longlho** [comment]
Hmm the only option is to run the CLI on plain JS after flow's stripped its type but that's dependent on your pipeline so I think more details would be great.

**Comment by steponas** [comment]
Hey @longlho, thanks for looking into this.

The webpack setup is this:

.babelrc
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    // This is the only Flow entry in the whole webpack/babel config
    "@babel/flow"
  ],
  "plugins": [
    ...
    // This part is still for the <v8 o react-intl
    [
      "react-intl",
      {
        "messagesDir": "./src/client/i18n/messages/"
      }
    ]
  ]
}
```

webpack config, relevant part:
```
module.exports = {
  resolve: {
    extensions: ['.js'],
    alias: require('./resolve-aliases'),
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true,
            cacheCompression: false,
          },
        },
        exclude: /node_modules/,
      },
      {
        enforce: 'pre',
        test: /\.js$/,
        loader: 'source-map-loader',
        exclude: /node_modules/,
      },
      // Other, non-js stuff
      ...
    ],
  },
  ...
};
```

So I suppose my option is to write a custom plugin, which would execute after the Flow execution phase. Talking in [webpack event terms](https://webpack.js.org/api/compiler-hooks/#assetemitted), that would probably be `assetEmitted`. Or I could add it as a processor/transpiler/etc in the webpack config as `module.rules` entry.

**Comment by longlho** [comment]
hmm yeah that's unfortunately what you prob have to do

**Comment by jbaudanza** [comment]
For anyone else having this issue, I created an `extract-strings.sh` shell script in my project. This uses babel to strip away all the flow types before running `formatjs extract`

```sh
TMP_DIR=/tmp/extract-tmp
mkdir -p ${TMP_DIR}
yarn run babel\
    --no-babelrc \
    --plugins "@babel/plugin-syntax-jsx,@babel/plugin-transform-flow-strip-types" \
    --out-dir ${TMP_DIR} \
    js/*.js 
yarn run formatjs extract ${TMP_DIR}/*.js \
     --out-file lang/en.json \
     --id-interpolation-pattern '[sha512:contenthash:base64:6]'
rm -rf ${TMP_DIR}
```

**Comment by longlho** [comment]
closing since there seems to be a solution

**Comment by jquense** [comment]
this isn't a great solution for large apps as it requires we basically build the app an additional time to extract messages Was there an inherent problem with using babel which covered both cases, as well as projects that use syntax that typescript's compile doesn't support. tbh it would be nice to still have extraction work in a babel plugin to avoid all the extra work of parsing the app again.

**Comment by longlho** [comment]
It's KTLO at the end of day. We keep getting bugs filed against how path resolution should behave when we dump out individual JSON files and also asks to aggregate those files together. With large apps separating out extraction actually works better with build pipelines from what I've seen at Yahoo & Dropbox.

**Comment by hjylewis** [comment]
This cli tool makes it easier to remove the flow types: https://github.com/facebook/flow/tree/master/packages/flow-remove-types

No need to mess with babel plugins

```sh
TMP_DIR=/tmp/extract-tmp
mkdir -p ${TMP_DIR}
yarn run flow-remove-types src/ -d ${TMP_DIR}
yarn run formatjs extract ${TMP_DIR}/*.js \
     --out-file lang/en.json \
     --id-interpolation-pattern '[sha512:contenthash:base64:6]'
rm -rf ${TMP_DIR}
```
