### ISSUE TITLE
Missing locale data for locale: "id" in Intl.NumberFormat. Using default locale: "en" as fallback.

### ISSUE THREAD

**Issue by auliakbarh** [formatjs/formatjs#2054]
I have an issue **[Error: [@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "id" in Intl.NumberFormat. Using default locale: "en" as fallback. See https://formatjs.io/docs/react-intl#runtime-requirements for more details**

![Screenshot_1599117282](https://user-images.githubusercontent.com/5032631/92083220-e305db80-edef-11ea-9425-e484cb2eb811.png)

it appears in console/terminal and an error warning in debug app. But my app still works fine.

Is there something I must fix in my code?

---------------
global.Intl = require('intl');

if (!Intl.PluralRules) {
  require('@formatjs/intl-pluralrules/polyfill');
  require('@formatjs/intl-pluralrules/locale-data/en');
  require('@formatjs/intl-pluralrules/locale-data/id');
}

if (!Intl.RelativeTimeFormat) {
  require('@formatjs/intl-relativetimeformat/polyfill');
  require('@formatjs/intl-relativetimeformat/locale-data/en');
  require('@formatjs/intl-relativetimeformat/locale-data/id');
}

if (!Intl.NumberFormat) {
  require('@formatjs/intl-numberformat/polyfill');
  require('@formatjs/intl-numberformat/locale-data/en');
  require('@formatjs/intl-numberformat/locale-data/id');
}

// dictionaries
const idTranslationMessages = require('./translations/id.json');
const enTranslationMessages = require('./translations/en.json');

// default language
const DEFAULT_LOCALE = 'id';

// available languages
// prettier-ignore
const appLocales = [
    'id',
    'en',
];

const formatTranslationMessages = (locale, messages) => {
  const defaultFormattedMessages =
    locale !== DEFAULT_LOCALE
      ? formatTranslationMessages(DEFAULT_LOCALE, enTranslationMessages)
      : {};
  const flattenFormattedMessages = (formattedMessages, key) => {
    const formattedMessage =
      !messages[key] && locale !== DEFAULT_LOCALE
        ? defaultFormattedMessages[key]
        : messages[key];
    return Object.assign(formattedMessages, {[key]: formattedMessage});
  };
  return Object.keys(messages).reduce(flattenFormattedMessages, {});
};

const translationMessages = {
  id: formatTranslationMessages('id', idTranslationMessages),
  en: formatTranslationMessages('en', enTranslationMessages),
};

exports.appLocales = appLocales;
exports.formatTranslationMessages = formatTranslationMessages;
exports.translationMessages = translationMessages;
exports.DEFAULT_LOCALE = DEFAULT_LOCALE;

**Comment by akarabach** [comment]
The same on my machine:
`Chrome Version 85.0.4183.83 (Official Build) (64-bit)`
`"react": "^16.13.1",`
`"react-intl": "^5.8.0",`
`"typescript": "~4.0.2"`

**Comment by longlho** [comment]
Do u have a repro?

**Comment by auliakbarh** [comment]
I got this one. Error message is solved after I add these in my code:

import 'intl';
import 'intl/locale-data/jsonp/en';
import 'intl/locale-data/jsonp/id';

**Comment by longlho** [comment]
intl.js is a dead package though just FYI

**Comment by akarabach** [comment]
> Do u have a repro?

Yup, I created the repo for you 

[https://stackblitz.com/edit/react-vlnkoz?file=src/App.js](https://stackblitz.com/edit/react-vlnkoz?file=src/App.js)

check console on stackblitz

Could you reopen this issue or help me with the code above ?

**Comment by longlho** [comment]
@akarabach looks like browsers don't come w/ `be` locale so you can do
```
import '@formatjs/intl-pluralrules/polyfill-force'
import '@formatjs/intl-pluralrules/locale-data/be'

import '@formatjs/intl-numberformat/polyfill-force'
import '@formatjs/intl-numberformat/locale-data/be'

import '@formatjs/intl-datetimeformat/polyfill-force'
import '@formatjs/intl-datetimeformat/add-all-tz'
import '@formatjs/intl-datetimeformat/locale-data/be'

import '@formatjs/intl-relativetimeformat/polyfill-force'
import '@formatjs/intl-relativetimeformat/locale-data/be'
```

**Comment by akarabach** [comment]
It works, thanks 👍

**Comment by jalik** [comment]
Note that order is important, first import polyfills, then locale data.
Some IDEs reorder imports in a way that polyfills are executed after locale data.
