### ISSUE TITLE
best practise for temporal wordings?

### ISSUE THREAD

**Issue by Frozen-byte** [formatjs/formatjs#2058]
**Which package?**
I will need it for react-intl; but I guess it's a general problem without any ICU Spec?

**Is your feature request related to a problem? Please describe.**
I would like to have a choice where I format my text by temporal decision: 
_"The door is open just now"_  
_"The door will be open tomorrow"_  
_"The door was opened yesterday"_  

**Describe the solution you'd like**
The plural specs look nice for this, but with minor adjustments:
```
The door {timeDelta, temporal,
    now {is open just now}
    past {will be open tomorrow}
    future {was opened yesterday}
}.
```
where `timeDelta` is the difference between now and the target in milliseconds.

**Describe alternatives you've considered**
For my specific case I just need *was published <FormattedRelativeTime />* and *will be published <FormattedRelativeTime />* 
 I used the <FormattedPlural /> component with a zero/one value for past/future.

**Additional context**
Maybe I am just not aware of a feature hiding in the Docs? Or I miss a common best practice? I Cannot imagine that this is not a common problem.

**Comment by longlho** [comment]
you're prob looking for https://formatjs.io/docs/core-concepts/icu-syntax#select-format
Right now there's no such thing as `temporal` and idk if there'll be in the spec. Time delta conversion is subject to timezone & product requirement (e.g from 1am to 11pm sometimes it's `2 hours ago` instead of `yesterday`)

**Comment by Frozen-byte** [comment]
The select syntax only allows exact matches afaik, no approximate-ranges.  
I opened the Ticket because some more cases came to my mind like display "almost done" or "far in the future"

Maybe a simple range-syntax for select-format would be enough:
```
The door {timeDelta, select,
    {<60,>-60} {is open just now}
    <-61 {will be open tomorrow}
    >61 {was opened yesterday}
}
```
will show _The door is open just now_ while the `timeDelta` variable is between -60 and 60, the others are self-explanatory I think 😃

**Comment by longlho** [comment]
So in terms of best practices, we (and also the standard) encourage full sentences, e.g `The door is open just now` & `The door will be open tomorrow`, bc typically tokenization/sentence split like that assumes english, and some locales might place time 1st and subject in the middle, which makes your sentence impossible to translate.

Simple `if/else` is what we recommend basically

**Comment by Frozen-byte** [comment]
Nice catch, that would outsource the decision-logic to javascript and only passes the correlating IDs to a `formatMessage()` function.
