### ISSUE TITLE
Not working with create-react-app

### ISSUE THREAD

**Issue by ShadabFaiz** [formatjs/formatjs#2066]
**Which package?**
react-intl: "^5.8.0",
node: v12.4.0
npm: v6.14.8

**Describe the bug**
Not working with create-react-app with typescript.

**To Reproduce**

1. `npx create-react-app my-app --template typescript`
2. ` npm i -S react react-intl`

**Expected behavior**
It should be working properly.

**Screenshots**
![Screenshot_20200907_200919](https://user-images.githubusercontent.com/8160121/92398660-a49d5300-f146-11ea-8c6f-fb4ced8c5be2.png)

**Desktop (please complete the following information):**

- OS:Manajro
- Browser: Chrome
- Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by longlho** [comment]
You need typescript v4+

**Comment by ShadabFaiz** [comment]
> You need typescript v4+

Thanks that worked, but was it mentioned somewhere in the documentation?

**Comment by longlho** [comment]
No we update that regularly. It should probably be in peerDep though
