### ISSUE TITLE
eslint-plugin-formatjs: enforce-id does not insert the comma correctly into defineMessages

### ISSUE THREAD

**Issue by jguddas** [formatjs/formatjs#2072]
**Which package?**
eslint-plugin-formatjs

**Describe the bug**
`enforce-id` does not insert the comma correctly into `defineMessages`

**To Reproduce**

1. run `eslint --fix` on this file

```js
/* eslint 'formatjs/enforce-id': [ 'error', { idInterpolationPattern: '[contenthash:6]' } ] */

import { defineMessages } from 'react-intl'

defineMessages({ example: { defaultMessage: 'example' } })
```

**Actual behavior**
auto fixes to `{ defaultMessage: 'example'id: '1a79a4', }`

**Expected behavior**
auto fixes to `{ defaultMessage: 'example', id: '1a79a4'}`

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
