### ISSUE TITLE
Pragma is not used for formatting of extraction output

### ISSUE THREAD

**Issue by thuringia** [formatjs/formatjs#2074]
**Which package?**
@formatjs/cli

**Describe the bug**
After setting a `pragma` option, the output of the CLI does not change

**To Reproduce**

1. Extract messages
2. Set `--pragma intl` switch for `yarn formatjs extract`

There is no diff.

From what I could reproduce by injecting `console.log`s, it appears that parsing the pragma itself seems to work but the cli is not using metadata at all here: https://github.com/formatjs/formatjs/blob/main/packages/cli/src/extract.ts#L193

On a possible unrelated note, this looks like inconsistent behavior, as source location metadata is being parsed and extracted into the output file but not as metadata, but as part of the message itself.

**Expected behavior**

The extracted file should have some grouping/nesting or some other change.
The description found in the docs at https://formatjs.io/docs/tooling/cli#--pragma-pragma does not promise anything like that, but can be interpreted that way.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**

n/a

**Additional context**

**Comment by longlho** [comment]
What is your use case & expected output? The `pragma` is extracted if you're using the CLI programmatically, but not output to the JSON yet bc we simply haven't got a use case for it.

If you can clarify `some grouping/nesting or some other change` that'd be great. We can actually just embed the pragma in each message itself.

**Comment by thuringia** [comment]
In previous projects we used fixed IDs to group labels into "bundles" for features. As you're no advocating to use generated IDs, this information is getting lost, this is only compounded by the fact that messages from one module do not have to appear next to each other in the output.
Embedding the pragma in the message itself would be a good stop-gap. It doesn't solve the locality issues in the extracted files.

The translation workflows I have seen so far with clients here in Germany do not use any of the translation services you support directly, or their formats. They are usually centered around features or sections of an app, that are either handled by separate teams or departments, or use custom build tools that use something like this.

Ultimately, reading the docs made me think that, using a pragma, a component like this:
```js
// @intl feature:navigation
import {defineMessages} from "react-intl"

const msg = defineMessages({
  home: { description: "homepage", defaultMessage: "Home" },
  login: { description: "login", defaultMessage: "Login" }
})
```
would create output similar to this:
```json
{
  "features": {
   "navigation": {
      "###": { "description": "homepage", "defaultMessage": "Home" },
      "###": { "description": "login", "defaultMessage": "Login" },
    }
  }
}
```
That way I could reap the benefits of generated IDs without sacrificing on the translation side

**Comment by thuringia** [comment]
Are you sure, that the pragma is exposed, via the node API?
https://github.com/formatjs/formatjs/blob/main/packages/cli/src/extract.ts#L230 uses the `Map` `extractedMessages` but does not add the metadate to the result

**Comment by longlho** [comment]
so what we can do is to embed `meta` in every message, then u can use the custom formatter feature to further massage into the format u like, does that sound good?

**Comment by thuringia** [comment]
That sounds great :)
