### ISSUE TITLE
Whitespace Padding ESLint Rule(s)

### ISSUE THREAD

**Issue by AustinBratcher** [formatjs/formatjs#2082]
**Which package?**
[eslint-plugin-formatjs](https://github.com/formatjs/formatjs/tree/main/packages/eslint-plugin-formatjs)

**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Since the FormatJS CLI extract command removes whitespace padding, it would be helpful to add eslint rule(s) to help catch this kind of whitespace up front. Potential rules: 
- `no-leading-whitespace` to catch whitespace at the front of the string
- `no-trailing-whitespace` to catch whitespace at the end of the string
- `no-padding-whitespace` to catch any whitespace on the ends of the string

I think the last option makes the most sense with the way the extract command currently works, but it might be helpful for some developers if the options were a bit more granular.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by longlho** [comment]
@pyrocat101 I think @AustinBratcher wants to take a stab at this

**Comment by pyrocat101** [comment]
Sounds good.

**Comment by longlho** [comment]
@AustinBratcher do u still plan to tackle this?

**Comment by AustinBratcher** [comment]
@longlho I had planned on it, but I haven't been able to make the bandwidth. I know what to do, just haven't been able to make the time to do it. I'm out all next week, so I'd someone else beats me to it, that's fine by me.

**Comment by tom-nexudus** [comment]
I think this would be helpful still. Seems like it's just been auto-closed, rather than the need has gone away

**Comment by longlho** [comment]
@tom-nexudus it's closed bc there's not enough interest.

**Comment by tom-nexudus** [comment]
Hence my comment, indicating an interest.
