### ISSUE TITLE
Having trouble using ts-transformer in Jest tests

### ISSUE THREAD

**Issue by arawden** [formatjs/formatjs#2088]
**Which package?**
`ts-transformer`

**Describe the bug**
I have a component under test using Jest and React Testing Library. Right now, my tests pass, but I am explicitly setting the ID inside my formatted messages, like so:
```
<FormattedMessage
  id="JJg0q0"
  description="Inspection date" 
  defaultMessage="Inspection date"
/>
```

I would like to use the tooling provided by `ts-transformer` in my application, as well as in my tests. I attempted to set up my jest config, which looks like this:
```
const transform = require("@formatjs/ts-transformer").transform;

module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  globals: {
    'ts-jest': {
      astTransformers: {
        getCustomTransformers() {
          return {
            before: [
              transform({
                extractFromFormatMessageCall: true,
                overrideIdFn: '[sha512:contenthash:base64:6]',
              }),
            ]
          }
        }
      },
    }
  },
  moduleNameMapper: {
    // etc....
  },
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
};
```

However, if I remove the ID from the component and re-run the tests, I get an error that an ID must be provided to format a message. 

The `ts-transformer` documentation links to the `ts-jest` [astTransformers](https://github.com/kulshekhar/ts-jest/blob/master/docs/user/config/astTransformers.md) documentation, but I'm still quite lost as to what could be the problem. 

I believe my error lies in the `astTransformers` block, but I cannot pinpoint the issue. My configuration follows the documentation for using `ts-loader` in Webpack, and while I know that these are two different technologies, I wasn't able to determine how to configure my tests from the documentation provided. 

**To Reproduce**

1. Create a basic application which uses the `FormattedMessage` component and explicitly sets an ID.
2. Create a test against the component.
3. Tests will run, and pass
4. Remove the ID from the component
5. Tests will fail and say that an ID must be provided to format a message
6. Attempt to configure Jest with `ts-transformer` such that the ID is provided to the component.

**Expected behavior**
I want to ensure that my components behave under test as they would in the browser, with IDs provided by the tooling provided by the formatjs team.

**Desktop (please complete the following information):**

- OS: Windows 10
- `@formatjs/ts-transformer`: 2.9.1
- `jest`: 26.4.0
- `ts-jest`: 26.3.0

**Comment by ynotdraw** [comment]
~~Hi @arawden , I'm seeing the same thing as you. What'd you end up doing to get this working?~~

~~I'm still getting `[@formatjs/intl] An `id` must be provided to format a message.`~~

Nevermind - I think I found it.  I ended up following https://formatjs.io/docs/tooling/ts-transformer/#via-ts-jest-in-jestconfigjs as you referenced, but I changed my:

```jsx
const { formatMessage } = useIntl();
```

to what they recommend and tell you to do in the docs:

```jsx
intl.formatMessage()
```

Doh!
