### ISSUE TITLE
Issue with Formatjs intl docs

### ISSUE THREAD

**Issue by tvvignesh** [formatjs/formatjs#2090]
Hi. This is not related to formatjs but the docs. The link https://formatjs.io/docs/intl/ does not work (it throws a React error in console). Thought I should let you know.

<img width="909" alt="Capture" src="https://user-images.githubusercontent.com/1165845/93031630-11828280-f64a-11ea-8de2-8f6175b4b191.PNG">

I will probably look at the repo till its fixed for docs: https://github.com/formatjs/formatjs/blob/main/website/docs/intl.md

Thanks.

**Comment by longlho** [comment]
Which browser are you using?

**Comment by tvvignesh** [comment]
@longlho Chrome Beta: `Version 86.0.4240.30 (Official Build) beta (64-bit)` Works in edge but fails in Chrome Canary as well.

**Comment by longlho** [comment]
Yeah we don't support chrome beta or canary. I can't repro since I don't use/have them

**Comment by pyrocat101** [comment]
@tvvignesh Thanks for catching this! It is actually a breaking change in the Intl.DisplayNames [proposal][]. I will send a fix for this.

[proposal]: https://github.com/tc39/proposal-intl-displaynames

**Comment by pyrocat101** [comment]
@tvvignesh The page should load on Chrome Canary now.
