### ISSUE TITLE
Not able to use IntlShape when upgrading the react-intl from 2.9.0 -> 3.2.4

### ISSUE THREAD

**Issue by mmudunuri** [formatjs/formatjs#2093]

**Comment by mmudunuri** [comment]
![image](https://user-images.githubusercontent.com/69569057/93067062-5c2aeb80-f698-11ea-9a7e-dc7e74f36fe3.png)

**Comment by saadaouad** [comment]
> intlShape has been removed. See TypeScript Support for more details.

Check https://formatjs.io/docs/react-intl/upgrade-guide-3x

**Comment by MadhuMudunuri** [comment]
@saadaouad The documentation is not that informative to be honest. So, I posted here if anything that I'm missing in this context.
