### ISSUE TITLE
selectUnit function doesn't support month and year 

### ISSUE THREAD

**Issue by saadaouad** [formatjs/formatjs#2094]
First, I want to thank you for this great package,

I'd like to upgrade `react-intl` package from v2 to v5, before I was using `FormattedRelative` component to get time since xxx (e.g. "2 months ago"). After migrating to `FormattedRelativeTime` I'm using `selectUnit` function to get the right `value` and `unit` props but this function doesn't support **month** and **year** ref https://github.com/formatjs/formatjs/blob/39848c6cffb5a31634727ad0e2f4498659108291/packages/react-intl/src/components/relative.tsx#L15:L31. Any idea about this please?

**Comment by longlho** [comment]
`month` & `year` are inherently tricky bc from 02/2020 to 12/2019 can either be `3 months ago` or `last year`. `selectUnit` is meant to be a migration tool so I strongly suggest u replace it with something that fits your editorial needs in terms of threshold.

**Comment by saadaouad** [comment]
> month & year are inherently tricky bc from 02/2020 to 12/2019 can either be 3 months ago or last year.

I don't understand what do you mean @longlho , can you please elaborate more

> selectUnit is meant to be a migration tool so I strongly suggest u replace it with something that fits your editorial needs in terms of threshold.

There is no function/component that fixes this problem or what?

**Comment by saadaouad** [comment]
We should have a `timeSince` function or something like that integrated in this package @longlho , what do you think to implement it?
