### ISSUE TITLE
intl-utils package no longer available

### ISSUE THREAD

**Issue by Turbo87** [formatjs/formatjs#2104]
### Which package?

intl-utils

### Is this a BUG REPORT or FEATURE REQUEST? (choose one)

I guess this is more of a question 😅 

### Expected behavior

https://www.npmjs.com/package/@formatjs/intl-utils is linking to this repository and I was expecting to find the source code for this package here, but it looks like https://github.com/formatjs/formatjs/commit/03701196379aa0584d0a40dcf1e75095489e171f removed it for some reason. Now I'm wondering if it got moved somewhere else or if it's gone entirely. The changelogs in this repo don't seem to mention any removal though.

### Current behavior

The intl-utils package is missing

**Comment by longlho** [comment]
yes the package is rather renamed to `@formatjs/ecma-abstract` with some changes in functionality (primarily `selectUnit` is removed and we don't plan to make any changes to it so it's kept in `@formatjs/intl-utils` as an archive).

**Comment by felipecrs** [comment]
@longlho could you please mark the project as deprecated in NPM and add your comment as message so that users know what to do?

**Comment by longlho** [comment]
yup I've marked it as deprecated
