### ISSUE TITLE
react-intl error in typescript & its possible remedy

### ISSUE THREAD

**Issue by shivammcw** [formatjs/formatjs#2111]
**Which package?**
react-intl is the package 

**Describe the bug**
There is a compilation error when I use react-intl in a Typescript environment

**To Reproduce**

I just added the package `react-intl` using yarn and tried to import it and as soon as I import it, my code stops compiling.

**Expected behavior**
When I import it, the code doesn't compile and it shows an error. I remove the import and my code works fine.

**Screenshots**
[Here is the error screenshot](https://i.ibb.co/XCqnmqW/image.png)

```
/opt/build/repo/node_modules/react-intl/src/components/message.d.ts
9:03:45 PM: TypeScript error in /opt/build/repo/node_modules/react-intl/src/components/message.d.ts(2,13):
9:03:45 PM: '=' expected.  TS1005
9:03:45 PM:     1 | import * as React from 'react';
9:03:45 PM:   > 2 | import type { PrimitiveType, FormatXMLElementFn } from 'intl-messageformat';
9:03:45 PM:       |             ^
9:03:45 PM:     3 | import { MessageDescriptor } from '@formatjs/intl';
9:03:45 PM:     4 | export interface Props<V extends Record<string, any> = Record<string, React.ReactNode>> extends MessageDescriptor {
9:03:45 PM:     5 |     values?: V;
9:03:45 PM: error Command failed with exit code 1.
9:03:45 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
9:03:45 PM: ​
```

**Desktop (please complete the following information):**

- OS: Windows
- Browser Every browser
- Version N/A

**Additional context**
I am using create-react-app with typescript enabled. I use Visual Studio Code as my IDE. Package Manager is Yarn

**Important Note**

I removed the word `type` from line 8 of [this file](https://github.com/formatjs/formatjs/blob/main/packages/react-intl/src/components/message.tsx) in my local node_modules folder and my code compiles successfully.

Please also note that the local change I made in my node_modules folder was in `node_modules/react-intl/src/components/message.d.ts`

Thank you!

**Comment by longlho** [comment]
Your typescript version is too old. We need ts3.8+

**Comment by shivammcw** [comment]
@longlho How do I upgrade my project's typescript version?
