### ISSUE TITLE
formatjs issue

### ISSUE THREAD

**Issue by mmudunuri** [formatjs/formatjs#2115]
We're using flowtyped for our codebase and currently are in the phase of upgrading from v2 to v3.2.

We're getting errors while using {IntlShape}. since, it's a typescript we can't directly import it. but how to use it to resolve this issue in a code base with flowtyped support.

Any help is much appreciated!!

**Comment by longlho** [comment]
do u have a repro? I'm not sure I understand what the use case is

**Comment by mmudunuri** [comment]
Sorry it's privately maintained. is there anything else that I can help with?

**Comment by longlho** [comment]
can u clarify what `using {IntlShape}` means? It's a typescript type and not a flowtyped type. Sry I'm not familiar with flow <-> TS interop

**Comment by mmudunuri** [comment]
yeah in the official documentation, it's mentioned that intlShape has been removed in the v3 right?

We're trying to use IntlShape as import {IntlShape} from 'react-intl' as in the docs. https://formatjs.io/docs/react-intl/upgrade-guide-3x#typescript-support.


But it's throwing errors that it's not exported.

**Comment by mmudunuri** [comment]
We're using flow-typed in our codebase and currently the react-intl version that we're trying to migrate to is v3.2.4

**Comment by longlho** [comment]
But that's only for TypeScript, not flow. If you were using `intlShape` as prop-types, u don't need it at all. We don't expose `PropTypes` at all.

**Comment by mmudunuri** [comment]
got you. then can you tell me how to import IntlShape in v3.2 as mentioned here https://formatjs.io/docs/react-intl/upgrade-guide-3x#typescript-support

**Comment by longlho** [comment]
You can ignore that section

**Comment by mmudunuri** [comment]
@longlho 

We were previously using intlShape like this 

```
Main.contextTypes = {
    intl: intlShape,
};
```
but in the v3 since intlShape is deprecated, how to refactor the above the code snippet

**Comment by longlho** [comment]
You can remove that section
