### ISSUE TITLE
Crash using formatDisplayName() in Chrome.

### ISSUE THREAD

**Issue by JohnC-80** [formatjs/formatjs#2122]
**Which package?**
React-Intl -> Intl

**Describe the bug**
If no options parameter is provided to `formatDisplayName()`, the program will crash since it cannot use `in` on the undefined `props` object. at https://github.com/formatjs/formatjs/blob/main/packages/intl/src/utils.ts#L20

**To Reproduce**
https://codesandbox.io/s/staging-smoke-t91wx?file=/src/TestIntl.js

**Expected behavior**
Given descriptions of Intl API, I don't think most developers would expect that they *must include this object (docs I've seen [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNames), And at the formatJS  `options?`  ) The code should probably behave fine without it... or at least not crash.

The updated proposal does say that the options object should contain a `type` field... but it isn't entirely clear whether the options parameter is truthfully required. If you guys have it, clarity around that would be awesome!
Thanks for the great I18n library!!!

**Screenshots**
The offending code with excluded options object...
![image](https://user-images.githubusercontent.com/20704067/93828235-80ef0800-fc30-11ea-98e3-1c262216a7b2.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version 85.0.4183.121

**Comment by longlho** [comment]
`options` is indeed required. If you look at step 4 in the proposal https://tc39.es/proposal-intl-displaynames/#sec-Intl.DisplayNames it calls `ToObject` on `options`, which throws a `TypeError` if `options` is `null` or `undefined`. This is indeed a bug in our implementation though bc that should have failed instead of the `for...in` loop so I'll keep this open until we fix it.

**Comment by zburke** [comment]
@JohnC-80 already took care of the minor changes in our codebase, so this feels pedantic, but if `options` is now required, that's a breaking change. 

In [v3 the examples omit it](https://github.com/formatjs/formatjs/blob/3.x/docs/API.md#formatdisplayname), and it is not mentioned in either the [v3->v4 upgrade guide](https://formatjs.io/docs/react-intl/upgrade-guide-4x) nor the [v4->v5 upgrade guide](https://formatjs.io/docs/react-intl/upgrade-guide-5x/). v5 documentation [shows it is optional](https://formatjs.io/docs/react-intl/api#formatdisplayname):
```
function formatDisplayName(
  value: string | number | object,
  options?: FormatDisplayNameOptions
): string | undefined
```

**Comment by longlho** [comment]
It is a breaking change. However the same code would have broken in new versions of Chrome so we're basically conforming to that. We actually found out about this bug from Chrome Canary. This is unfortunately a risk in using stage-3 APIs.

**Comment by longlho** [comment]
https://github.com/formatjs/formatjs/issues/2090 for posterity

**Comment by zburke** [comment]
Hmmm, I see what you're saying about conforming your library to a spec defined elsewhere. I see there is documentation of this all the way back to the v3 docs ("This uses stage 3 Intl.DisplayNames API so polyfill is required."), but crucially there is no explanation of what "stage 3" actually means, i.e. not only do you need a polyfill, but _this is an unstable API that may change without warning_. 

From my point of view as a consumer of this library, this showed up simply as a breaking change that snuck into a patch release: `formatDisplayName()` used to provide a default second argument of `{ type: 'language' }` when none was provided; now it no longer does that. If you want to stick to the `Intl.DisplayNames` spec, I totally understand that, but another option would be to restore the previous behavior of react-intl until its next major release. 

As above, this is all rather pedantic as we've already patched our own code. And as @JohnC-80 said at the start, this is a great library and I am so so grateful to you for maintaining it!
