### ISSUE TITLE
Possible syntax error in intl-messageformat/ message.d.ts file

### ISSUE THREAD

**Issue by leoavelino7** [formatjs/formatjs#2128]
**Which package?**
Package: intl-messageformat

**Describe the bug**
In file message.d.ts in line  `import type { PrimitiveType, FormatXMLElementFn } from 'intl-messageformat';`
the error happens.

**To Reproduce**

1. Using React with TypeScript, install package `npm install react-intln`
2. Use the package in App.tsx
3. Run `npm run start`
4. See error `> 2 | import type { PrimitiveType, FormatXMLElementFn } from 'intl-messageformat';`

**Expected behavior**
That this error does not happen

**Desktop (please complete the following information):**

- OS: Linux Ubuntu 18
- Browser Chrome
- Version 85.0.4183.102 64 bits

**Additional context**

Is it a possible solution? Because when I remove `type`, execute with success

Change 
`import type { PrimitiveType, FormatXMLElementFn } from 'intl-messageformat';`
to
`import { PrimitiveType, FormatXMLElementFn } from 'intl-messageformat';`

**Comment by longlho** [comment]
U need typescript@3.8+
