### ISSUE TITLE
Intl.DateTimeFormat.formatRange polyfill

### ISSUE THREAD

**Issue by longlho** [formatjs/formatjs#2129]
https://github.com/tc39/proposal-intl-DateTimeFormat-formatRange is stage 3

**Comment by longlho** [comment]
https://github.com/formatjs/formatjs/tree/format-range work tracked in this branch

**Comment by turkus** [comment]
@longlho great job! Do you know a date of the release?

**Comment by longlho** [comment]
Soon we're bug fixing and adding more tests. Spec is changing as well so keep in mind it's not stable

**Comment by longlho** [comment]
2.8.0 should have it (we're releasing it right now)
