### ISSUE TITLE
Use a simple js formatter with the Node API

### ISSUE THREAD

**Issue by bertho-zero** [formatjs/formatjs#2141]
**Which package?**
`@formatjs/cli`

**Is your feature request related to a problem? Please describe.**
By using `extract` and `format` in Node API we should be able to use a formatter directly, an object instead of a string path.

**Describe the solution you'd like**
Modifying this function would do it:
https://github.com/formatjs/formatjs/blob/268d6aef6fc08180a0be691b631eb1cdfb68ca31/packages/cli/src/formatters/index.ts#L8-L30

**Comment by longlho** [comment]
closed by #2143
