### ISSUE TITLE
Support non-Gregorian calendars in `@formatjs/intl-datetimeformat`

### ISSUE THREAD

**Issue by meness** [formatjs/formatjs#2145]
**Which package?**

@formatjs/intl-datetimeformat

**Describe the bug**

Importing `@formatjs/intl-datetimeformat` throws an exception for `fa` locale in iOS.

> Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting date. 
> 
> undefined is not an object (evaluating 'formats[0]')
> 
> BestFitFormatMatcher
> 
> InitializeDateTimeFormat
> 
> 
> [native code]
> 
> 
> variadic
> 
> variadic@[native code]
> 
> formatDate

**To Reproduce**

1. Open the link below in your iPhone, no matter you use Safari or Chrome.
2. Check the console for the exception

**Expected behavior**

It should work as expected, displays a simple date.

**Screenshots**

Please check this out on iOS: https://codesandbox.io/s/datetimeformat-polyfill-ios-exception-for-fa-locale-jj5sn

**Smartphone (please complete the following information):**

- Device: iPhone
- OS: iOS 14.0.1
- Browser: Safari and Chrome
- Version: Chrome v85.0.4183.109

**Additional context**

I tested this with the latest Chrome and iOS versions, and get the same exception. It works fine on Desktop.

**Comment by longlho** [comment]
this is bc `fa` by default uses `persian` calendar which right now we don't support, setting `calendar: "gregory"` would fix this. I have to look into where persian calendar data lives
