### ISSUE TITLE
React intl throw this error if I use intl.formatMessage without explicit id.=> Error: [@formatjs/intl] An `id` must be provided to format a message.

### ISSUE THREAD

**Issue by mdshifut** [formatjs/formatjs#2151]
**Which package?**
React intl 5.8.3

**Describe the bug**
```
intl.formatMessage({
            defaultMessage: "New Password",
            description: "placeholder text",
          }
```
It should produce a dynamic id if I omit explicit id but it throws the flowing error
Error: [@formatjs/intl] An id must be provided to format a message.

I have tried to run this example from the docs but it's not working although explicit ids are discouraged in the docs.

Here are my source codes you may check
Is there any way to omit this error?

**Comment by longlho** [comment]
Can u provide a repro?

**Comment by mdshifut** [comment]
Of course
here you go https://github.com/mdshifut/react-i18n-example
One thing  I notice that if omit an id in FormattedMessage which also produce the same error

**Comment by longlho** [comment]
You need to use either our babel plugin or ts-transformer to generate IDs during transpilation

**Comment by mdshifut** [comment]
I already use babel plugin here you can check:https://github.com/mdshifut/react-i18n-example/blob/master/.babelrc

**Comment by longlho** [comment]
But you're using create-react-app which doesn't allow custom babel config afaik so that config is noop

**Comment by mdshifut** [comment]
@longlho  Thanks for your suggestion. I used  react-app-rewired and customize-cra packages for overeating the CRA Babel config and it's working fine

**Comment by samajammin** [comment]
Hey @mdshifut @longlho so just to confirm what I'm gathering from this discussion - using `formatMessage` without an explicit `id` is not possible with CRA? I've tried the same approach following the docs to produce a dynamic ID & receive that same error: `Error: [@formatjs/intl] An id must be provided to format a message.`

Thanks in advance!

**Comment by longlho** [comment]
not without some rewiring. See https://github.com/formatjs/formatjs/issues/1901#issuecomment-766515227

**Comment by upexconde** [comment]
hey @mdshifut , I tried to run your repo and still facing the same issue. Do you have any suggestion for it?
