### ISSUE TITLE
'Debug failure. False expression' running Jest tests w/ ts-transformer

### ISSUE THREAD

**Issue by arawden** [formatjs/formatjs#2152]
**Which package?**
ts-transformer

**Describe the bug**
I've created a test file to verify that, given a specific locale, the component under test renders with the correct translations.

My jest config:
```
module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom",
  globals: {
    "ts-jest": {
      astTransformers: {
        before: [
          {
            path: "@formatjs/ts-transformer/ts-jest-integration",
            options: {
              // options
              overrideIdFn: "[sha512:contenthash:base64:6]",
              ast: true,
            },
          },
        ],
      },
    },
  },
  // module name mapper and set file here
}
```

A portion of my test file:
```
test("renders in English", () => {
    render(<InspectionRecord />);

    const inspectionStatus = screen.queryByLabelText(/inspection status/i);
    expect(inspectionStatus).toBeInTheDocument();

    const organization = screen.queryByLabelText(/organization/i);
    expect(organization).toBeInTheDocument();
  });

  test("renders in Arabic", () => {
    render(<InspectionRecord />, {
      locale: "ar",
      messages: ar,
    });

    const inspectionStatus = screen.queryByLabelText(/inspection status/i);
    expect(inspectionStatus).not.toBeInTheDocument();

    const arabicOrganization = screen.queryByLabelText(/منظمة/i);
    expect(arabicOrganization).toBeInTheDocument();
```

where `render` is a custom render function done with RTL which uses redux Provider and formatjs IntlProvider, and `ar` is the compiled JSON file containing my translations.

**To Reproduce**

1. Create a component which uses a FormattedMessage, with no explicit ID declared.
3. Add the ts-transformer, following the [documentation](https://formatjs.io/docs/tooling/ts-transformer#via-ts-jest-in-jestconfigjs)
4. Run the tests. When the test runner encounters the file with the FormattedMessage, the test will fail with the message in the title of this issue.

**Expected behavior**
The test runs without needing to explicitly declare IDs.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version:
  - typescript: 4.0.3
  - jest: 26.4.2
  - ts-jest: 26.4.0
  - @formatjs/ts-transformer: 2.11.0

**Additional context**

**Comment by longlho** [comment]
Do u have a repro?

**Comment by arawden** [comment]
I've got a sandbox [here](https://codesandbox.io/s/gracious-nightingale-rlqcq) which should encompass everything. Let me know if this is not sufficient or doesn't replicate and I'll try to expand on it

**Comment by longlho** [comment]
create-react-app doesn't allow custom webpack config so the webpack config in your repro doesn't actually do anything

**Comment by arawden** [comment]
Does the webpack file get used for Jest? I think that file was only left there from when I forked the repro from another repro I had made (which, incidentally, I believe you said the same thing about CRA for that repro, so it's my fault either way). I can remove the file if you would like, assuming it doesn't get used

**Comment by longlho** [comment]
Ok looks like `create-react-app` doesn't allow custom `jest.config.js` so you'd have to eject

**Comment by arawden** [comment]
I've gone ahead and tried to create a repro without create-react-app. You can find it at https://github.com/arawden/formatjs-debug_failure

I explain a little bit in the README as far as where i think the bug lies, but naturally I'm uncertain. Hopefully the issue is easy to spot for you guys.
