### ISSUE TITLE
The cli does not extract strings from JSX property interpolation

### ISSUE THREAD

**Issue by JonLopezGarcia** [formatjs/formatjs#2158]
Thanks for the amazing work!

**Which package?**
`@formatjs/ts-transformer`

**Describe the bug**
The cli does not extract strings from JSX property interpolation

**To Reproduce**
```
<FormattedMessage defaultMessage={`
my long sentence that has to be split
at some point because otherwise 
it would not be fun to read it...
`} />
```

**Expected behavior**
The string literal should be extracted.

**Additional context**
[Here](https://github.com/formatjs/formatjs/blob/main/packages/ts-transformer/src/transform.ts#L206) the `if` statement does not handle when the node is a JSX expression. 
At first glance, adding `
else if(ts.isJsxExpression(initializer)) {
...
}` should do the work.

I would like to specify that it is not a blocking point since we manage to use string literals with `defineMessage(...)`

**Is it an intended behavior to not handle string literals in JSX interpolations ?**

**Comment by narthur** [comment]
I ran into this issue, too, since IntelliJ autocompletes JSX props with curly braces.
