### ISSUE TITLE
Issues with iOS 14

### ISSUE THREAD

**Issue by A-D-E** [formatjs/formatjs#2159]
In iOS 14, no translation when the website is loaded (only defaultMessage). If you change the language via button it will be displayed correctly. 

Tested with Safari, Chrome and EDGE
Android and older iOS work fine

**Comment by longlho** [comment]
I'm not sure I understand what the issue is

**Comment by A-D-E** [comment]
Sorry for my English )

When I open the website with an iOS device (iPhone, iPad), the translation is not loaded, but only the "id" (and defaultMessage if available).
I have a language switch, if I select the language manually, it will be loaded correctly.

**Comment by longlho** [comment]
Do you have a repro?

**Comment by A-D-E** [comment]
https://codesandbox.io/s/react-intl-ios14-issue-ek35t
You must open it in iOS 14

**Comment by A-D-E** [comment]
Okay, I've solved the problem.
iOS 14 uses as navigator.language the pair of two lower case letters
for example:
de-de for de-DE
en-en for en-GB
es-es for es-ES etc.

Thanks anyway for the quick response
