### ISSUE TITLE
[object Object] InternalSlot has not been initialized

### ISSUE THREAD

**Issue by danilofuchs** [formatjs/formatjs#2160]
**Which package?**
`@formatjs/intl-locale`

**Describe the bug**
Running the following code on AWS Lambda, Node 12.x runtime:

```ts
import Locale from "@formatjs/intl-locale";

export const getLanguageCode = (locale: string): string => {
    return new Locale(locale).language;
};
```

I intended to not use the polyfill as `Locale` is only called in this specific code.

Throws the following error: 
```
TypeError: [object Object] InternalSlot has not been initialized
    at getMultiInternalSlots (/var/task/node_modules/@formatjs/ecma402-abstract/src/utils.js:51:15)
    at Object.getInternalSlot (/var/task/node_modules/@formatjs/ecma402-abstract/src/utils.js:41:12)
    at new Locale (/var/task/node_modules/@formatjs/intl-locale/index.js:223:32)
    at Object.t.getLanguageCode (/var/task/index.js:1:20175)
```

**To Reproduce**

When running locally, via `mocha`, I could not reproduce the error.

After deploying, this error occurs.

**Expected behavior**

It shouldn't throw

Also, `[object Object]` should not be in the error message

**Comment by danilofuchs** [comment]
I found the error!
I was using passing a non-compliant object to `new Locale()` instead of a string or a Locale.

I think this is different from other standards:

#### `new Intl.Locale({})`
Node 14: `Uncaught RangeError: Incorrect locale information provided`
Chrome 85: `Uncaught RangeError: Incorrect locale information provided`
@formatjs/intl-locale: `TypeError: [object Object] InternalSlot has not been initialized`

#### `new Intl.Locale("1")`
Node 14: `Uncaught RangeError: Incorrect locale information provided`
Chrome 85: `Uncaught RangeError: Incorrect locale information provided`
@formatjs/intl-locale: `RangeError: malformed language tag`

**Comment by longlho** [comment]
Thanks for reporting! We've fixed the Error type issue. The Error message itself is unspec'ed so it can be whatever but `RangeError` is part of the spec
