### ISSUE TITLE
@formatjs/cli - compile command not outputting results to file specified by --out-file

### ISSUE THREAD

**Issue by wilbooorn** [formatjs/formatjs#2161]
**Which package?**
@formatjs/cli

**Describe the bug**
After running the `compile` command, the result doesn't get written to the file specified by `--out-file`. I don't get any errors, and I see the result in the terminal - but the out file is nowhere to be found

**To Reproduce**
After running the following command
`formatjs compile -- src/strings/en/strings.json --ast --out-file compiled-lang/en.json`

I don't see compiled-lang/en.json created. I tried manually creating it to see if it would write to it, and still nothing. I do see output in the terminal 
```
{
  "8ND89P": "Save",
  ...
}
```

**Expected behavior**
I would expect the command to output the results to the file

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 85.0.4183.102 (Official Build) (64-bit)

**Comment by longlho** [comment]
Try removing -- after compile

**Comment by wilbooorn** [comment]
wow that totally worked lol thank you so much
