### ISSUE TITLE
Pseduo-Localization

### ISSUE THREAD

**Issue by AustinBratcher** [formatjs/formatjs#2165]
**Which package?**
CLI (or potentially `react-intl`)

**Is your feature request related to a problem? Please describe.**
When localizing parts of the app, it's handy to be able to see text displayed (other than the defaultMessage) to verify a string is localized as expected. Currently to do something like this a developer would have to provider a custom format to the `extract` command that hijacks the message to produce some kind of pseduo-localized text. However in so doing, any rich text formatting or placeholders end up being removed. There isn't an easy way to identify them (without some complex regex) to ensure that only the appropriate text is pseduo-localized. 

**Describe the solution you'd like**
A new addition to the CLI to allow for pseudo-localization. This could come in the form of a flag on the existing `extract` command or some new CLI command entirely. 

Some variables to consider: 
- What file should the pseduo-localized text end up in?
- What percentage should the text grow/shrink by?

An example of what I'm picturing: 
```
formatjs extract-dev 'src/**/*.js*' -- out-file lang/dev.json --scale 10 --id-interpolation-pattern '[sha512:contenthash:base64:6]
```
`scale` here would be some kind of percentage (positive or negative) to grow/shrink by. 

**Describe alternatives you've considered**
- Making it a flag on the FormatJS library itself: In theory, this could be some kind of flag when configuring the Intl object when consuming it in the app. You could have a `dev` mode flag (along with a similar `scale` flag) that would ignore the specific locale passed in and instead only use the default message and perform necessary pseudo-localization. 

- Using a TMS: Some TMSs offer pseduo-localization. This, however, doesn't fit well into day to day development workflow. It's a better tool for seeing what _could_ happen if some kind of scaled localization occurred.

**Comment by longlho** [comment]
A couple of pseudo locales used at DBX:
- xx-LS: Append `SSSSSSSSSSSSSSSSSSSSSSSSS` at the end to simulate long string
- xx-AC: `toUpperCase` everything
- xx-HA: Prefix `[javascript]` to the message
- xx-RL: Convert letter to hebrew letter
- en-XA: Convert letter to accented letter

**Comment by longlho** [comment]
accented: `âḃćḋèḟĝḫíĵǩĺṁńŏṗɋŕśṭůṿẘẋẏẓḀḂḈḊḔḞḠḢḬĴḴĻḾŊÕṔɊŔṠṮŨṼẄẌŸƵ`

**Comment by AustinBratcher** [comment]
Looks like this works great when using AST. 

Bonus request: Not requiring the `--ast` option to use the `--pseduo-locale` option.
