### ISSUE TITLE
Node API: extract function do not work properly

### ISSUE THREAD

**Issue by AlexandreMouyen** [formatjs/formatjs#2169]
Hello,

I am trying to use the extract function on my JS code in order to generate my language files.

I use this React code as a base:
![image](https://user-images.githubusercontent.com/27637370/94793100-3d3b9180-03da-11eb-9ad0-2d056fa5d7fe.png)

On my package.json I used this script (it is working perfectly):
` "extract": "formatjs extract src/**/*.jsx --out-file src/translations/en-GB.json"`

But when I am trying to use the extract function, I cannot have the two messages from _intl.formatMessage_ only the first one from the Component _FormattedMessage_.

Here my code:
```javascript
const PATTERN = 'src/**/*.jsx';

const extractTranslation = async () =>
  new Promise((resolve, reject) => {
    glob(PATTERN, (err, files) => {
      if (err) return reject(err);
      return resolve(
        extract(files, {
          idInterpolationPattern: '[sha512:contenthash:base64:6]',
        })
      );
    });
  });
```

The expected result:
```json
{
  "home.button.darkText": {
    "defaultMessage": "Switch to Dark Mode",
    "description": "Toggle dark theme button text"
  },
  "home.button.lightText": {
    "defaultMessage": "Switch to Light Mode",
    "description": "Toggle light theme button text"
  },
  "home.title": {
    "defaultMessage": "Hello World!",
    "description": "Introducing title"
  }
}
```

Do you have an idea?

**Comment by longlho** [comment]
https://formatjs.io/docs/tooling/cli#--extract-from-format-message-call

**Comment by AlexandreMouyen** [comment]
> https://formatjs.io/docs/tooling/cli#--extract-from-format-message-call

Hello longlho,

All my code is extracted from this documentation page that I followed all along. But there is no futher information about my problem.

**Comment by longlho** [comment]
I recommend you using the CLI directly

**Comment by TimDaub** [comment]
> https://formatjs.io/docs/tooling/cli#--extract-from-format-message-call

this link seems to be broken. What happened to this option?

**Comment by longlho** [comment]
it's now always on
