### ISSUE TITLE
Intl.DateTimeFormat: Incorrect timezone conversion during transitions to/from DST

### ISSUE THREAD

**Issue by joncooke-sky** [formatjs/formatjs#2170]
**Which package?**
Intl.DateTimeFormat

**Describe the bug**
DST offset is not correctly applied at the date/time of transition in/out of DST

**To Reproduce**

`
const formatter = new Intl.DateTimeFormat('en-GB', {
    hour: 'numeric',
    hourCycle: 'h23',
    timeZone: 'Europe/Berlin',
});

// transition in to DST at 01:00 UTC
expect(formatter.format(new Date('2019-03-31T00:59:59.999Z')).toEqual(1); //passes
expect(formatter.format(new Date('2019-03-31T01:00:00.000Z')).toEqual(3); //fails 2
expect(formatter.format(new Date('2019-03-31T01:00:00.001Z')).toEqual(3); //passes

// transition out of DST at 01:00 UTC
expect(formatter.format(new Date('2019-10-27T00:59:59.999Z')).toEqual(2); //passes
expect(formatter.format(new Date('2019-10-27T01:00:00.000Z')).toEqual(2); //fails 3
expect(formatter.format(new Date('2019-10-27T01:00:00.001Z')).toEqual(2); //passes
`

On the day of the transition in to DST the implementation behaves as though the local clock reads like this as the transition happens:
01:59.59.999
02:00:00.000 - bug
03:00:00.001

On the day of the transition out of DST the implementation behaves as though the local clock reads like this as the transition happens:
02:59.59.999
03:00:00.000 - bug
02:00:00.001 

**Expected behavior**
All of these cases should pass.

On the last Sunday in March at 01:00Z, CEST (UTC+2) starts, so the return value should be 3
On the day of the transition in to DST, as the transition happens, the local clock should read:
01:59.59.999
03:00:00.000
03:00:00.001 

On the last Sunday in October at 01:00Z, CEST (UTC+2) ends, so the return value should be 2
On the day of the transition out of DST, as the transition happens, the local clock should read:
02:59.59.999
02:00:00.000
02:00:00.001 

**Screenshots**
not applicable

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
The zoneData is correct, at least for the zone I checked, but the rules are not applied correctly.

I believe the fix is to patch ToLocalTime to ensure that DST is applied from the threshold time as well as after

from `if (i === zoneData.length || zoneData[i][0] * 1e3 >= t) {`

to `if (i === zoneData.length || zoneData[i][0] * 1e3 > t) {`

Also, reversing the table and searching from future -> past would be more performant for most applications, which only handle dates from the recent past and near future. Just make the condition <=

**Comment by longlho** [comment]
Sounds like you have an idea of how to fix it and we always welcome PR :)

**Comment by joncooke-sky** [comment]
I'm unable to push my branch to the remote 

```
$ git push --set-upstream origin fix/2170
ERROR: Permission to formatjs/formatjs.git denied to joncooke-sky.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by longlho** [comment]
You'd have to fork the repo
