### ISSUE TITLE
formatDisplayName: opts is not optional (like the others)

### ISSUE THREAD

**Issue by joeax** [formatjs/formatjs#2171]
Got latest of @formatjs/intl imperative API this morning. After a minor refactor, discovered that options arg to formatDisplayName is no longer optional. I'm just wondering if this is by design.

https://github.com/formatjs/formatjs/blob/a8c990e0860c7a1c15befa1bdbfd7d482ee61146/packages/intl/src/types.ts#L137

**Comment by longlho** [comment]
Yes it's in the spec

**Comment by joeax** [comment]
Docs should be updated to reflect this then.
https://formatjs.io/docs/intl#formatdisplayname

**Comment by longlho** [comment]
Good point. Wanna PR real quick? I'll reopen this until it's updated
