### ISSUE TITLE
Africa/Johannesburg is polyfilled as UTC+1:30 instead of UTC+2

### ISSUE THREAD

**Issue by circlingthesun** [formatjs/formatjs#2192]
**Which package?**
@formatjs/intl-datetimeformat

**Describe the bug**
Africa/Johannesburg is polyfilled as GMT+1:30 instead of GMT+2

**To Reproduce**
See `https://github.com/circlingthesun/intl-datetimeformat-bug`

or

```js
import "@formatjs/intl-datetimeformat/polyfill-force.js";
import "@formatjs/intl-datetimeformat/locale-data/en.js";
import "@formatjs/intl-datetimeformat/add-all-tz.js";

const result = new Intl.DateTimeFormat("en-US", {
  locale: "en",
  calendar: "gregory",
  numberingSystem: "latn",
  timeZone: "Africa/Johannesburg", // UTC+2
  year: "numeric",
  month: "numeric",
  day: "numeric",
  hour: "numeric",
  minute: "numeric",
  second: "numeric",
}).format(new Date(Date.UTC(2020, 0, 1, 12, 0, 0)));

console.log(result);

// Result: "1/1/2020, 1:30:00 PM"
// Expected: "1/1/2020, 2:00:00 PM"
```

**Expected behavior**
I expect dates in "Africa/Johannesburg" to be 2 hours after UTC

**Desktop (please complete the following information):**

- OS: All
- Browser All
- Version All versions when polyfill-force is used

**Smartphone (please complete the following information):**

- Device: All
- OS: All
- Browser All
- Version All versions when polyfill-force is used

**Additional context**
When polyfill-force is not used it happens on all platforms where shouldPolyfill evaluates to true. This appears to include all versions of Safari and older version of other browsers.

**Comment by circlingthesun** [comment]
It appears that a historic rule from zdump is being used, see:

https://github.com/eggert/tz/blob/master/africa#L1323

UTC+1:30 ended in 1903

**Comment by longlho** [comment]
Yeah it's prob a bug in our tz data search
