### ISSUE TITLE
Add Intl.ListFormat to FormatMessage

### ISSUE THREAD

**Issue by hlehmann** [formatjs/formatjs#2210]
**Which package?**
intl-messageformat-parser, intl-messageformat

**Describe the solution you'd like**
Accept translate with the `list` syntax using Intl.ListFormat
`Hello {names, list}`
returning `Hello John, John and John`

**Additional context**
This should have the same integration than other formatters.

**Comment by longlho** [comment]
This is not in spec so we don't plan on implementing it. MessageFormat v2 might be addressing this issue https://github.com/unicode-org/message-format-wg
