### ISSUE TITLE
react-intl TypeScript import error.

### ISSUE THREAD

**Issue by mbugerald** [formatjs/formatjs#2217]
**Which package?**
react-intl 

**Describe the bug**
Hi guys, first of all thanks for all the work. I noticed a bug using react-intl with typescript **import type { PrimitiveType, FormatXMLElementFn } from 'intl-messageformat';** breaks because of import error. please can you correct it? I remove the type statement before the {PrimitiveType just after the import statement on line 3, in the latest version. 
**source: react-intl > src > component > message.d.ts**.

**Comment by longlho** [comment]
dupe of #2128
