### ISSUE TITLE
Compile directory of message files

### ISSUE THREAD

**Issue by donovanhiland** [formatjs/formatjs#2218]
I'm using @formatjs/cli and wondering if there's a way I can pass a directory of messages to be compiled? It seems like the only way to do this currently is to run compile on each language file individually.

**Comment by longlho** [comment]
https://formatjs.github.io//docs/tooling/cli take a look at folder compilation

**Comment by donovanhiland** [comment]
😍 Perfect! I was looking at the getting started docs under [Message Distribution](https://formatjs.io/docs/getting-started/message-distribution) and didn't see it there. So happy this exists
