### ISSUE TITLE
CLI: Use-case for scoped IDs for messages

### ISSUE THREAD

**Issue by lucasff** [formatjs/formatjs#2230]
**Which package?**
`@formatjs/cli`

**Is your feature request related to a problem? Please describe.**
So our project follows one approach described [here](https://github.com/react-boilerplate/react-boilerplate-typescript/blob/master/app/containers/HomePage/messages.ts) where every message definition file has a *static* defined scope and it's being used in the template literal interpolation just below.

**Describe the solution you'd like**
Allow `@formatjs/cli` to use this ID and not generate random IDs.

**Describe alternatives you've considered**
Looking at `babel-plugins`

**Additional context**
Happy to answer any questions that might arise.

**Comment by longlho** [comment]
we cannot evaluate JS during build time so scoped ID like that won't be possible
