### ISSUE TITLE
[intl-datetimeformat] 'second' option is ignored when 'timeZoneName' is set

### ISSUE THREAD

**Issue by mrijke** [formatjs/formatjs#2236]
### Which package?

@formatjs/intl-datetimeformat

### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
Bug report

### Expected behavior

When the `second` option is set to `undefined`, I expect to see no seconds in the formatted time.

### Current behavior

Seconds are always rendered if `timeZoneName` is not `undefined`

### Step to reproduce for BUG REPORT

https://codesandbox.io/s/bitter-dream-2l3br?file=/src/App.tsx

### Your Environment

@formatjs/intl-datetimeformat version 2.6.10
Chrome 86

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
