### ISSUE TITLE
enforce-default-message ESLint rule fails to enforce literal when defaultMessage is the only attribute

### ISSUE THREAD

**Issue by bjohn465** [formatjs/formatjs#2238]
**Which package?**
[`eslint-plugin-formatjs`](https://github.com/formatjs/formatjs/tree/main/packages/eslint-plugin-formatjs)

**Describe the bug**
When a [`FormattedMessage` component](https://formatjs.io/docs/react-intl/components#formattedmessage) contains only a `defaultMessage` attribute and the `"literal"` option is used for the [`enforce-default-message`](https://formatjs.io/docs/tooling/linter#enforce-default-message) rule, the ESLint rule will not fail.

**To Reproduce**
In a `react-intl` project:

1. Add `eslint-plugin-formatjs`
2. Configure the `enforce-default-message` rule to error on failure, and use the `"literal"` option
3. Add a `FormattedMessage` component that looks like this: `<FormattedMessage defaultMessage={msg} />`
4. Run ESLint
5. No `enforce-default-message` rule failure
6. Change `FormattedMessage` component to look like: `<FormattedMessage defaultMessage={'test'} />`
7. Run ESLint
8. No `enforce-default-message` rule failure

**Expected behavior**
The `enforce-default-message` rule should fail in both of these instances.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: macOS
- Browser: N/A
- Version: N/A

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Additional context**
The root cause may be in the [`extractMessageDescriptorFromJSXElement` function](https://github.com/formatjs/formatjs/blob/eslint-plugin-formatjs%402.7.15/packages/eslint-plugin-formatjs/util.ts#L110).

[The case for the `defaultMessage`](https://github.com/formatjs/formatjs/blob/eslint-plugin-formatjs%402.7.15/packages/eslint-plugin-formatjs/util.ts#L134-L141) only sets `result.message.defaultMessage` if the value is a literal:
```javascript
result.messagePropNode = prop;
result.messageNode = prop.value;
if (
  prop.value?.type === 'Literal' &&
  typeof prop.value.value === 'string'
) {
  result.message.defaultMessage = prop.value.value;
}
```

If the `defaultMessage` prop is the only attribute, `result.message` will be empty, so `` [will return `undefined`](https://github.com/formatjs/formatjs/blob/eslint-plugin-formatjs%402.7.15/packages/eslint-plugin-formatjs/util.ts#L172-L174):
```javascript
if (!Object.keys(result.message).length) {
  return;
}
```

That means [`msgDescriptorNodeInfo` in `extractMessages`](https://github.com/formatjs/formatjs/blob/eslint-plugin-formatjs%402.7.15/packages/eslint-plugin-formatjs/util.ts#L231-L234) will be `undefined`:
```javascript
const msgDescriptorNodeInfo = extractMessageDescriptorFromJSXElement(node);
if (msgDescriptorNodeInfo) {
  return [msgDescriptorNodeInfo];
}
```

So it will [return an empty array](https://github.com/formatjs/formatjs/blob/eslint-plugin-formatjs%402.7.15/packages/eslint-plugin-formatjs/util.ts#L236):
```javascript
return [];
```

The `checkNode` method of the `enforce-default-message` rule [will get that empty array from `extractMessages` and have nothing to loop over](https://github.com/formatjs/formatjs/blob/eslint-plugin-formatjs%402.7.15/packages/eslint-plugin-formatjs/rules/enforce-default-message.ts#L11-L20), so it won't check that the `defaultMessage` prop is a literal:
```javascript
const msgs = extractMessages(node as TSESTree.Node, importedMacroVars);
// ...
for (const [
  {
    message: {defaultMessage},
    messageNode,
  },
] of msgs) {
```

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
