### ISSUE TITLE
Support concatenated string literals

### ISSUE THREAD

**Issue by halcarleton** [formatjs/formatjs#2252]
**Which package?**
react-intl

**Is your feature request related to a problem? Please describe.**
When defining messages often the default message is long and needs to be split across multiple lines. The intuitive way of doing this would be to concatenate a number of string literals like this:

```js
const myMessage = intl.formatMessage({
  defaultMessage: 'Integer mattis eros cursus eros tempus, mollis '
                + 'ullamcorper justo aliquam. Sed a diam vel eros '
                + 'feugiat malesuada. Aliquam condimentum rhoncus '
                + 'nibh tempus tempus. Nulla eget lobortis massa.',
  id: 'test.loremIpsum'
});
```

The issue is that if you do this the extraction process will ignore the default message. This results is an output file containing:

```json
{
  "test.loremIpsum": {}
}
```

Additionally, this fails silently so there is no warning that the file you are sending out for translation is incomplete.

**Describe the solution you'd like**
The solution I would prefer is support for concatenated string literals. If the default message is defined as in the example above the resulting output file should be as follows:

```json
{
  "test.loremIpsum": {
    "defaultMessage": "Integer mattis eros cursus eros tempus, mollis ullamcorper justo aliquam. Sed a diam vel eros feugiat malesuada. Aliquam condimentum rhoncus nibh tempus tempus. Nulla eget lobortis massa."
  }
}
```

**Describe alternatives you've considered**
I wasn't able to find any documentation that provides a solution to defining very long messages in-line. Currently the only workaround I am aware of is using a multiline template literal.

example:
```js
const myMessage = intl.formatMessage({
  defaultMessage: `Integer mattis eros cursus eros tempus, mollis
                   ullamcorper justo aliquam. Sed a diam vel eros
                   feugiat malesuada. Aliquam condimentum rhoncus
                   nibh tempus tempus. Nulla eget lobortis massa.`,
  id: 'test.loremIpsum'
});
```

This only works because `formatjs` appears to remove extra whitespace from strings before passing it the formatter.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
also you should probably use our eslint-plugin-formatjs to prevent issues similar to this
