### ISSUE TITLE
Is there any way to use an IntlProvider inside another IntlProvider?

### ISSUE THREAD

**Issue by mahdidavoodi7** [formatjs/formatjs#2271]
I want to have 2 levels of abstraction in my site language, so I want to use 2 IntlProvider inside each other...
for example, I want to have my menus in English but I want to have the content in Persian.

is there any way for me to do something like this?
any help would be appreciated <3

**Comment by longlho** [comment]
I think you can just do it right?

**Comment by mahdidavoodi7** [comment]
@longlho so if I have nested IntlProvider, which locale considered as the `formattedMessage` locale?
Parent one or the child one?

**Comment by longlho** [comment]
Should be the child one but you should verify
