### ISSUE TITLE
Flash of plaintext when using FormattedMessage with rich text formatting tags

### ISSUE THREAD

**Issue by federicobond** [formatjs/formatjs#2283]
**Which package?**
react-intl (I guess)

**Describe the bug**

When using rich text formatting tags as described [here](https://formatjs.io/docs/react-intl/components#rich-text-formatting), the `FormattedMessage` component takes a while to apply the tags. During this time, the user sees a flash of "Foo &lt;b&gt;bar&lt;/b&gt;" instead of the expected "Foo **bar**".

Is there a way to avoid this behaviour? BTW, I am using gatsby-react-intl, but I am not sure if it's relevant.

**Comment by longlho** [comment]
That shouldn't be the case. Do you have a repro? It might be gatsby-react-intl problem

**Comment by federicobond** [comment]
> Do you have a repro?

Yes. Check out https://muun.com/v2/

**Comment by longlho** [comment]
that looks like a gatsby server side rendering issue

**Comment by federicobond** [comment]
Thanks, I'll check it out.
