### ISSUE TITLE
@formatjs/ecma402-abstract version1.3 found error: DateTimeFormat/skeleton.d.ts(4,13) ',' expected.  TS1005

### ISSUE THREAD

**Issue by Yuiffy** [formatjs/formatjs#2286]
**Which package?**
Since this is a monorepo. Please specify which package this bug report is for.

**Describe the bug**

13 hours ago the @formatjs/ecma402-abstract publish new version 1.3, make we can not build. my typescript version is "3.8.3",
build found error:
```
> react-app-rewired build

Creating an optimized production build...
Failed to compile.

/data/landun/workspace/node_modules/@formatjs/ecma402-abstract/src/DateTimeFormat/skeleton.d.ts
TypeScript error in /data/landun/workspace/node_modules/@formatjs/ecma402-abstract/src/DateTimeFormat/skeleton.d.ts(4,13):
',' expected.  TS1005

    2 | export declare function processDateTimePattern(pattern: string, result?: Pick<DateTimeFormatOptions, 'weekday' | 'era' | 'year' | 'month' | 'day' | 'hour
' | 'minute' | 'second' | 'timeZoneName'> & {
    3 |     hour12?: boolean;
  > 4 | }): [pattern: string, pattern12: string];
      |             ^
    5 | /**
    6 |  * Parse Date time skeleton into Intl.DateTimeFormatOptions
    7 |  * Ref: https://unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DennisBaekgaard** [comment]
This literally breaks any build pipeline using formatjs (I reckon a fair few use react-intl) and prevents any releases.

**Comment by BenjaBobs** [comment]
It seems for now the workaround (when using yarn: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)
Adding to `packages.json`:
```json
{
	"dependencies": {
		//...
	},
	"resolutions": {
		"@formatjs/ecma402-abstract": "1.2.6"
	}
}
```

**Comment by CTxD** [comment]
Our team was able to override the version of "@formatjs/ecma420-abstract" by using the following in our package.json:

```
{
    "dependencies": {
     ...
     "react-intl": "^5.8.0",
    },
    "resolutions": {
      "@formatjs/ecma402-abstract": "1.2.6"
    }
}
```

**Comment by longlho** [comment]
The resolution is to upgrade your TS to v4. My apology for the breakage we've been on v4 for a while.

**Comment by jimmydjabali** [comment]
How is this going ? Updating TS to v4+ doesn't fix it.

**Comment by longlho** [comment]
It should. TS@4 has labeled tuple elements

**Comment by dl748** [comment]
> The resolution is to upgrade your TS to v4. My apology for the breakage we've been on v4 for a while.

The problem for me is the react-intl is configured way poorly, in a way that forces it to use 1.3 no matter what.  Upgrading to TS 4 isn't feasible as it currently breaks a lot of packages we are using. Since we are also not using yarn.  Here is my fix for the issue (horrible though)

package.json
```
{
...
  "devDependencies": {
    ...
    "@formatjs/ecma402-abstract": "1.2.6"
  }
  "scripts": {
    ...
    "postinstall": "npx rimraf \"node_modules/@formatjs/*/node_modules/@formatjs\""
  }
...
}
```

Unfortunately just setting up your deps to use that version makes the underlying @formatjs function still install the new version.  So I remove them in order to force it to use my dep one.

**Comment by dl748** [comment]
Further investigating

react-intl has `"@formatjs/ecma402-abstract": "^1.2.6",`
which the standard is that 1.2.6 to 1.3 shouldn't have breaking changes, so either @formatjs/ecma402-abstract should have released a 2.0 or react-intl should be changed to ~1.2.6 or all ~ for @formatjs, or do not use ^ or ~ to use a specific version.

if minor versions cause breakage, callers should use ~ or nothing at all.

Edit: take that back, react-intl should not use ~ as  @formatjs/intl  1.3.8 -> 1.3.9 is a break change as it forces the use of 1.3.0 instead of 1.2.6

**Comment by longlho** [comment]
Yeah we just locked down all our deps

**Comment by dl748** [comment]
> Yeah we just locked down all our deps

Which is generally fine, but it broke ALL the old code.  We can't even downgrade, because now every react-intl from 4.0.0 and up fails to compile

Edit: 5.8.6-5.8.8 compiled yesterday, now it fails today. Its not like a new version is broken, old versions are now broken too.

**Comment by PeledYuval** [comment]
For pnpm users who want to force @formatjs/ecma402-abstract to 1.2.6:

Option A:
https://pnpm.js.org/en/package_json#pnpmoverrides
Add this to your workspace's root package.json (if it exists):
```JSON
  "pnpm": {
    "overrides": {
      "@formatjs/ecma402-abstract": "1.2.6"
    }
  }
```

Option B:
https://pnpm.js.org/en/3.6/hooks
Create a `pnpmfile.js` in your workspace root, add this:
```JSON
module.exports = {
  hooks: {
    readPackage (pkg) {
      const brokenFormatJsPkgName = '@formatjs/ecma402-abstract';
      if (pkg.dependencies && Object.keys(pkg.dependencies).includes(brokenFormatJsPkgName)) {
        pkg.dependencies[brokenFormatJsPkgName] = '1.2.6';
      }
      return pkg
    }
  }
}
```

**Comment by syntax-punk** [comment]
Updating typescript to 4 fixed it to me.

**Comment by dborstelmann** [comment]
Would love a resolution to this if anyone knows a non-hacky way for those of us who can't update to TS 4 yet.

**Comment by longlho** [comment]
we'll do a release w/o the usage of labeled tuple element

**Comment by longlho** [comment]
fixed in https://github.com/formatjs/formatjs/commit/8ff12305ff810788844d13e817b08392c9eef9a9

**Comment by longlho** [comment]
fixed in latest `@formatjs/ecma402-abstract` version

**Comment by dborstelmann** [comment]
Thanks that worked, appreciate you cutting a new release so quickly.
