### ISSUE TITLE
Example missing for --format

### ISSUE THREAD

**Issue by sunknudsen** [formatjs/formatjs#2287]
**Which package?**

`@formatjs/cli`

**Describe the bug**

I am unable to find an example of expected function for `formatjs extract --format ...`.

The [documentation](https://formatjs.io/docs/tooling/cli/#--format-path) isn't helpful in this regard.

Can someone please drop one here that would output the following? Thanks for your help. 🤓

Trying to integrate [@formatjs/cli](https://www.npmjs.com/package/@formatjs/cli) with [react-intl-translations-manager](https://www.npmjs.com/package/react-intl-translations-manager).

Perhaps this isn't the right approach?

```json
[
  { "id": "home.foo", "defaultMessage": "Foo" },
  { "id": "home.bar", "defaultMessage": "Bar" }
]

```

**Comment by longlho** [comment]
These are examples of builtin formatters: https://github.com/formatjs/formatjs/tree/main/packages/cli/src/formatters

I don't know about https://www.npmjs.com/package/react-intl-translations-manager it seems abandoned

**Comment by sunknudsen** [comment]
Thanks so much for your help @longlho.

Inspired by the examples, the following is what I was looking for.

```javascript
exports.format = (messages) => {
  let array = []
  Object.keys(messages).forEach(function (key) {
    array.push({
      id: key,
      defaultMessage: messages[key].defaultMessage,
    })
  })
  return array
}
```
