### ISSUE TITLE
@formatjs/intl-datetimeformat: missing am/pm indicator in some locales

### ISSUE THREAD

**Issue by hasyimibhar** [formatjs/formatjs#2291]
**Which package?**
`@formatjs/intl-datetimeformat`

**Describe the bug**
When `hour12` is set to true and `hourCycle` is set to `h12`, the output of `format` is missing the `am/pm` indicator for some locales. From my test (not exhaustive), it's missing for the following locales:
- `en-MY`
- `id-ID`
- `zh-Hant-HK` (`下午` instead of `pm` is missing)
- `ja-JP` (`午後` instead of `pm` is missing)

**To Reproduce**

Run this with Node.js:
https://gist.github.com/hasyimibhar/bc8e17ce4f922253ede90b1070f3c1a1

It outputs `01 Feb 2020, 06:10:10`.

Replace `en-MY` to test with other locales.

**Expected behavior**
On Chrome Version 86.0.4240.111 (Official Build) (x86_64), it outputs `01 Feb 2020, 06:10:10 pm`.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
