### ISSUE TITLE
How to use it with ParcelJS?

### ISSUE THREAD

**Issue by nagyv** [formatjs/formatjs#2292]
**Which package?**

Probably related to:

- babel-plugin-react-intl

**Is your feature request related to a problem? Please describe.**

I prefer to use ParcelJS for compiling my code. I've defined format messages like:

```
<FormattedMessage
        description="Auth page: Sign In"
        defaultMessage="Sign in"
      />
```

When I run `extract` the final json contains the generated ID, but the above code is not updated as I'd like following your [docs](https://formatjs.io/docs/getting-started/message-extraction#automatic-id-generation) and having [babel-plugin-react-intl](https://formatjs.io/docs/guides/bundler-plugins/#using-babel-plugin-react-intl) specified in a `.babelrc`

My whole `.babelrc` is:

```
{
  "plugins": [
    [
      "react-intl",
      {
        "extractFromFormatMessageCall": true,
        "idInterpolationPattern": "[sha512:contenthash:base64:6]",
        "ast": true
      }
    ]
  ]
}
```

**Describe the solution you'd like**

Extend the documentation on how to set up `react-intl` with `parceljs`. I'll be happy to write it, once I get it to work. :) 

**Describe alternatives you've considered**

The best alternative I have at the moment is to use `i18next`.

**Additional context**

-

**Comment by longlho** [comment]
If you beat me to it PR is definitely welcome!
