### ISSUE TITLE
FormattedRelativeTime: select unit if not given

### ISSUE THREAD

**Issue by hnrchrdl** [formatjs/formatjs#2300]
**Which package?**
react-intl

**Describe the bug**
`<FormattedRelativeTime value={-100000} />` for locale `en` should render `1 day ago`, but it renders as `100.000 seconds ago`. It should automatically select the unit if no unit is given as props.

For example `<FormattedRelativeTime value={-100000} updateIntervalInSeconds={60} />` renders `1 day ago` as expected.

**Additional context**
I could help out with a PR if you agree this is a bug.

**Comment by longlho** [comment]
default unit is `second`. The reason `updateIntervalInSeconds` changes this behavior is bc it auto-adjust UP TO hour only, after that it stops so I don't think that's the behavior you want.

Auto `unit` selection has been rejected at the spec level so you can learn about that decision here: https://github.com/tc39/proposal-intl-relative-time/issues/118

**Comment by hnrchrdl** [comment]
thanks for the quick reply.

even though intl does not support auto units for understandable reasons - `react-intl` could still support it. in fact it already does indirectly when setting `updateIntervalInSeconds` to a valid value and no unit.

i think it is confusing that `<FormattedRelativeTime value={-100000} />` renders something different than `<FormattedRelativeTime value={-100000} updateIntervalInSeconds={60} />`, while `<FormattedRelativeTime value={-100000} unit="days" updateIntervalInSeconds={60} />` throws with `Cannot schedule update with unit longer than hour`.

to me, `<FormattedRelativeTime value={-100000} updateIntervalInSeconds={60} />` seems like a hack to achieve what i want.

**Comment by longlho** [comment]
the auto select logic stops at `day` https://github.com/formatjs/formatjs/blob/main/packages/react-intl/src/components/relative.tsx#L15 so I don't know if that's what you're looking for. If it is feel free to copy it and tweak to your usage.

**Comment by hnrchrdl** [comment]
ok thanks.
