### ISSUE TITLE
Allow translation values to include other translations

### ISSUE THREAD

**Issue by pooyarm** [formatjs/formatjs#2303]
**Which package?**
`intl-messageformat`

**Is your feature request related to a problem? Please describe.**
When we have a html element inside the translation and this element needs an attribute which should be localised, for example a URL or a `title` attribute, then we should consider to exclude that `title` and URL into other translation keys and then pass it in values object to render it correctly.

**Describe the solution you'd like**
But I think there can be a feature to be able to use another translation key inside a translation value, for example:
```
"termsAndConditions": "I accept <a href={urls.termsAndConditions}>Terms and conditions</a>.",
"urls.termsAndConditions": "http://example.com/path/to/termsAndConditions",
```

**Additional question**
I know currently it's not possible to set attributes inside html tags (in translation values). I can see the point of not allowing putting variables inside html tags, but I can't understand why can't we have an attribute without using variables.

**Comment by longlho** [comment]
This is being discuss in Message Format v2 https://github.com/unicode-org/message-format-wg so I don't plan to introduce a way of achieving this atm. I suggest you follow that repo as we're working through a new spec.
