### ISSUE TITLE
Support Swiss German

### ISSUE THREAD

**Issue by TimoKunze** [formatjs/formatjs#2304]
**Which package?**
react-intl

**Is your feature request related to a problem? Please describe.**
In my app I would like to support gsw-CH locale, including number formatting, currency formatting, date/time formatting. Currently I can define Swiss German texts, but formatting will be wrong and weekday/month names will be wrong.

**Describe the solution you'd like**
I would like to be able to use gsw-CH locale as easily as e.g. de-CH locale.

**Describe alternatives you've considered**
I've considered defining custom formatters but did not find out how to do this.

**Comment by longlho** [comment]
We do support `gsw`. You'd need to use the polyfills to add support for it though: https://formatjs.io/docs/polyfills

Example: https://codesandbox.io/s/blue-darkness-82t7i?file=/src/App.tsx

**Comment by TimoKunze** [comment]
Thank you, I got it working to some degree. I load the polyfills only if I switch to Swiss German language. This works. But if I switch back to another language, e.g. English, I still get Swiss German weekday and month names. Without loading the polyfills switching between the other languages works fine. It also seems that the problem does not occur if I switch from `gsw` back to any other locale that has been active before. So `de` -> `gsw` -> `de` works fine, but with `de` -> `gsw` -> `en` I get Swiss German month names for English.

Additionally number formatting does not seem to work. I get this error:
[@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "gsw" in Intl.NumberFormat. Using default locale: "en" as fallback. See https://formatjs.io/docs/react-intl#runtime-requirements for more details.

**Comment by TimoKunze** [comment]
Okay, I fixed the `Intl.NumberFormat` issue. I noticed that react-intl does not install `@formatjs/intl-numberformat`, therefore there was no polyfill for `Intl.NumberFormat`. I installed `@formatjs/intl-numberformat` explicitly and now I can use the proper polyfills.

So the remaining problem is that the polyfills break any locale that has not been used before loading the polyfills. I noticed that it is even worse than I thought initially. If I use `de` before loading the polyfills, but avoid using `FormattedNumber` for `de`, then `FormattedNumber` for `de` won't work properly after the polyfills have been loaded.
Probably I can workaround this by using every formatting for each locale once before loading the polyfills. But is there a better solution? Can the polyfills be explicitly unapplied?

**Comment by TimoKunze** [comment]
I've solved this issue. It is important that you don't try to use lazy-loading the polyfills. I have loaded them only before activating `gsw` locale for the first time. But it seems like they must be loaded before using anything like `FormattedNumber`. Also if you use those polyfills, you must also load the locale data for **any** locale that you want to support, not just for that locale that forced you to use polyfills in the first place.

Now I detected that the polyfills somehow change the way months are printed. Applying the polyfills changes `intlProvider.state.intl.formatDate(new Date(2020, 10, 1, 0, 0, 0), { month: "long" })` from `November` to `October`. My time zone is UTC+1 in case this matters. `intlProvider` is created this way:
```
const intlProvider = new IntlProvider({
  defaultLocale: "en",
  locale: "de",
})
```

**Comment by longlho** [comment]
u need to supply the timezone to the polyfilled version because we cannot detect timezone.

In terms of how to "unapply" the polyfill, you should detect supported locales using `Intl.DateTimeFormat.supportedLocalesOf`, then only use the polyfill if that locale isn't supported. If u change locale it's best to just refresh the page, thus resetting your state.

**Comment by TimoKunze** [comment]
Thank you, I managed to make it work. It is a bit tricky that you also need to specify `formats` and `defaultFormats` options when specifying `timeZone`. Otherwise calls to `intlProvider.state.intl.formatMessage` will crash because they attempt to access `.date` of `undefined`.
