### ISSUE TITLE
FormattedRelativeTime does not adjust unit if updateIntervalInSeconds is missing

### ISSUE THREAD

**Issue by jalik** [formatjs/formatjs#2309]
**Which package?**
react-intl

**Describe the bug**
The output of <FormattedRelativeTime /> does not adjust unit automatically when `updateIntervalInSeconds` not defined.

**To Reproduce**
Use the following code:
```jsx
<FormattedRelativeTime value={-600} numeric="auto" />
```

The output is in seconds instead of minutes:
`600 seconds ago`

**Expected behavior**
The output value should be (something like this in english, mine is in french):
`10 minutes ago`

**Desktop (please complete the following information):**

- OS: KDE neon 5.20.3 (ubuntu based)
- Browser Firefox
- Version 82.0.3 (64bit)

**Comment by longlho** [comment]
`updateIntervalInSeconds` is not meant to force auto `unit` conversion. It's by default `second` then every certain interval it tries to update that. That also stops at `hour` and won't tick any further.

You'll have to specify unit explicitly, for reasons mentioned in this issue https://github.com/tc39/proposal-intl-relative-time/issues/118
