### ISSUE TITLE
Extracting message with same ID but only one has defaultMessage

### ISSUE THREAD

**Issue by ghost** [formatjs/formatjs#2321]
### Which package?
FormatJs/CLI

### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
Feature request probably.

### Expected behavior

For example:
In ComponentA
`<FormattedMessage id="Foo.Bar" defaultMessage="A nice foo bar" />`
In ComponentB we want **reuse translation above**
`<FormattedMessage id="Foo.Bar"  />`

but when we try run **formatjs extract** I expect that second use (without defaultMessage and description) will be ignored during extraction, so the second one will be extracted with defaultMessage and description.

### Current behavior

For example:
In ComponentA
`<FormattedMessage id="Foo.Bar" defaultMessage="A nice foo bar" />`
In ComponentB we want **reuse translation above**
`<FormattedMessage id="Foo.Bar"  />`

but when we try run **formatjs extract** we will get warning that **` Duplicate message id:"Foo.Bar", but the `description` and/or `defaultMessage` are different`**

### Your Environment
Package: @formatjs/cli@2.13.12
OS: Ubuntu 18.04

it can be something like this (here is ignored description at all)
```
if (extractedMessages.has(id)) {
  existing = extractedMessages.get(id);
  if (
      ((defaultMessage && existing.defaultMessage) && defaultMessage !== existing.defaultMessage)) {
      error = new Error("[FormatJS CLI] Duplicate message id: \"" + id + "\", " +
          'but the `description` and/or `defaultMessage` are different.');
      if (throws) {
          throw error;
      }
      else {
          console_utils_1.warn(error.message);
      }
  }
  if (existing.defaultMessage)
  extractedMessages.set(id, existing);
  else 
  extractedMessages.set(id, message);
}
else
extractedMessages.set(id, message);
```

**Comment by sebastianrak89** [comment]
it can be something like this (here is ignored description at all)

```
if (extractedMessages.has(id)) {
  existing = extractedMessages.get(id);
  if (
      ((defaultMessage && existing.defaultMessage) && defaultMessage !== existing.defaultMessage)) {
      error = new Error("[FormatJS CLI] Duplicate message id: \"" + id + "\", " +
          'but the `description` and/or `defaultMessage` are different.');
      if (throws) {
          throw error;
      }
      else {
          console_utils_1.warn(error.message);
      }
  }
  if (existing.defaultMessage)
  extractedMessages.set(id, existing);
  else 
  extractedMessages.set(id, message);
}
else
extractedMessages.set(id, message);
```

**Comment by longlho** [comment]
hmm this is a pretty edge use case. Typically if u wanna reuse messages (which we don't encourage since messages are contextual), you'd pull out the whole message instead of relying on pre-declared ID. Can u clarify ur use case?

**Comment by ghost** [comment]
@longlho I think there are some situations where one translation used in few places are acceptable, for eg labels like first name, last name, an unknown error  etc.
One translation means less work for translator, and in my case it is important for my client so its real life case. I think it could be on/off setting by argument in extraction. What do you think?

**Comment by longlho** [comment]
Oh I don't mean they have to be different. They can be the same messages which would yield the same translations. You would just declare the message again instead of just using the ID. They will get deduped during extraction

**Comment by ghost** [comment]
@longlho you mean something like this:

ComponentA
`<FormattedMessage id="Foo.Bar" defaultMessage="Some message with a bit long and boring translation, try to remember it word by word" />`

ComponentB
`<FormattedMessage id="Foo.Bar" defaultMessage="Some message with a bit long and boring translation, try to remember it word by word" />`

but is quite easier to remember the some (simple) ids and use it, instead remember whole translation.

**Comment by longlho** [comment]
I'd recommend sharing at the component level instead of just messages since it's too low of a primitive. Take a look at https://formatjs.io/docs/getting-started/message-declaration for reasons

**Comment by ghost** [comment]
I know that ;) Just in some case it can be a bit easier without this. I understand your point, so if my request is rejected I just will fork ;) So, feel free to close if it is end of discussion.
