### ISSUE TITLE
no-id eslint rule is missing from docs

### ISSUE THREAD

**Issue by hjylewis** [formatjs/formatjs#2322]
**Which package?**
website, eslint-plugin-formatjs

**Describe the bug**
[no-id](https://github.com/formatjs/formatjs/blob/main/packages/eslint-plugin-formatjs/rules/no-id.ts) eslint rule is missing from [docs](https://formatjs.io/docs/tooling/linter#no-id)

**Comment by longlho** [comment]
PR's always welcome :)
