### ISSUE TITLE
How to configure react-intl with storybook using typescript?

### ISSUE THREAD

**Issue by cabello** [formatjs/formatjs#2334]
Hi 👋 

I just integrated my app with react-intl and it's working like a charm 💎 I have yet to figure out how to setup storybook to render accordingly.

I use:
* storybook 6.X
* react-intl 5.X
* typescript 3.8.X
* create-react-app

**Which package?**
formatjs

**Describe the bug**
Part of my react-intl setup for the app included .babelrc and tsconfig changes to include the id generation `[sha512:contenthash:base64:6]`.

In `.storybook/preview.js` I setup decorators:

```js
export const decorators = [
  (Story) => (
    <IntlProvider>
      <Story />
    </IntlProvider>
  ),
];
```

If I try to load the stories (all `tsx` files) I get the following: `[@formatjs/intl] An `id` must be provided to format a message.`, I also tried instead of an empty intl provider:

```js
import messages from 'assets/compiled-lang/en-CA.json';

<IntlProvider
        messages={messages}
        locale={'en-CA'}
        defaultLocale='en-CA'
      >
```

**To Reproduce**

1. Add react-intl to a Typescript application
2. Load storybooks
3. See errors
4. Add IntlProvider to preview.js as a decorator
5. See `[@formatjs/intl] An `id` must be provided to format a message.` error

**Expected behavior**

Either:
* The messages defined in `defaultMessage` to render successfully or have a way to request that behaviour
* The messages in the specified locale with supplied messages to render successfully

**Screenshots**

<img width="1006" alt="Screen Shot 2020-11-20 at 7 33 41 PM" src="https://user-images.githubusercontent.com/60936/99862341-530e3d00-2b67-11eb-84a3-9f651b2f164b.png">

**Additional context**

I think `yarn storybook` needs an additional step where the AST is parsed and ids are generated in order to this to work as expected, I would also for the time being just use the `defaultMessage` for the stories if there is a way to turn that on.

Thank you for sharing this project with the world, I appreciate it 🙇

**Comment by longlho** [comment]
I think u need to use `babel-plugin-react-intl` with storybook like in this instruction: https://storybook.js.org/docs/react/configure/babel

**Comment by cabello** [comment]
Interesting! Docs says:

> If your project has a .babelrc file, we'll use that instead of the default config file.
> You can also place a .storybook/.babelrc file to use a special configuration for Storybook only.

I do have a `.babelrc` file in the root folder, when I launch storybook the output does not say anything about it but if I add a copy of the file to `.storybook/.babelrc` then I see:

```
info => Loading custom babel config
info => Loading custom babel config
```

And it works! 🎉 

It's worth mentioning that I tried a symlink and that did not work.

Thank you for the support and a link that solved my problem! 🙏
