### ISSUE TITLE
Extracting messages in monorepo

### ISSUE THREAD

**Issue by VeraVes** [formatjs/formatjs#2349]
**Which package?**
formatjs

**Describe the bug**
I run the command yarn extract in one of my packages in monorepo
`"extract": "formatjs extract src/**/*.js --out-file lang/en.json --id-interpolation-pattern [sha512:contenthash:base64:6] --format formatter.js"`

In current package I use imported React components from another package. These components include constructions like `<FormattedMessage defaultMessage="Collapse"/>`

I found the way to extract message Collapse: to use as source this path  `../**/*.js` (this path includes all packages in my monorepo). But in this case unused messages get to lang/en.json too.

When I used `"babel-plugin-react-intl": "^4.3.0"` I had an ability to extract all messages in my project including messages from imported components from another packages automatically starting yarn dev.

**Expected behavior**
File lang/en.json contains message Collapse

**Comment by longlho** [comment]
I'm not sure I understand ur use case. Can u put together an example repo?

**Comment by VeraVes** [comment]
> I'm not sure I understand ur use case. Can u put together an example repo?

Unfortunately, my repo is private, but this is it's emulation.
https://github.com/VeraVes/formatJsExample

**Comment by czabaj** [comment]
@VeraVes I do understand your need. With `formatjs extract` you just visit all files specified with a glob and extract all translations, whether with `babel-plugin-react-intl` the build process maintains all dependencies of your entry point files and extracts just the translations you actually use in the mono-repo sub-project.

Well, I have just now noticed that `babel-plugin-react-intl` dropped the `messagesDir` option and it seems that extracting messages via babel is no more an option. So much new stuff here, wow. In that case, I cannot help you.

**Comment by longlho** [comment]
@VeraVes hmm why can't u just extract from `packages/**/*.js`?

**Comment by VeraVes** [comment]
> @VeraVes hmm why can't u just extract from `packages/**/*.js`?

It causes extracting unused messages, which are in another components in Common package.

**Comment by longlho** [comment]
We recommend structuring each feature as package and translation gets extracted along with it: https://formatjs.io/docs/guides/distribute-libraries

We've seen this being scaled easily to large eng orgs. Your use case is unfortunately not supported. Basically you shouldn't lump components into "common".

**Comment by VeraVes** [comment]
> We recommend structuring each feature as package and translation gets extracted along with it: https://formatjs.io/docs/guides/distribute-libraries
> 
> We've seen this being scaled easily to large eng orgs. Your use case is unfortunately not supported. Basically you shouldn't lump components into "common".

Ok. thanks!

**Comment by joshunger** [comment]
You could use https://github.com/dependents/node-dependency-tree
