### ISSUE TITLE
Ability to add custom formatters to intl context

### ISSUE THREAD

**Issue by serhiipalash** [formatjs/formatjs#2355]
**Which package?**
`react-intl`

**Is your feature request related to a problem? Please describe.**

In our app we have `formatCountry` and `formatLanguage` utils. We use them for formatting country and language names. Usually we do it like this

```
import { useIntl } from 'react-intl'
import formatCountry from './utils/formatCountry'

function Sweden() {
  const intl = useIntl()
  
  return formatCountry('SE', intl.locale)
}
```

The problem is that it's too verbose and decoupled from general formatting in the app

**Describe the solution you'd like**

We want to pass a list of custom formatters to `IntlProvider` and then use them in context of app locale with `useIntl` hook

 ```
import formatCountry from './utils/formatCountry'

function App({ children }) {
  return (
    <IntlProvider 
      locale="de" 
      customFormatters={{ formatCountry: appLocale => countryCode => formatCountry(countryCode, appLocale) }}
    >
      {children}
    </IntlProvider>
  )
}
```

 ```
import { useIntl } from 'react-intl'

function Sweden() {
  const { formatCountry } = useIntl()
  
  return formatCountry('SE')
}
```

Thanks in advance!

**Comment by longlho** [comment]
I believe you can just create a separate `Provider` for that. This is not something we plan to support.

**Comment by serhiipalash** [comment]
Ok thanks
