### ISSUE TITLE
@formatjs/intl-numberformat main field of package.json is incorrect

### ISSUE THREAD

**Issue by ValentinH** [formatjs/formatjs#2365]
**Which package?**
`@formatjs/intl-numberformat `

**Describe the bug**
The `main` and `types` field of `package.json` are incorrect. Indeed, they point to the `index.js` and `index.d.ts` files that do not exist. 

See [this file](https://github.com/formatjs/formatjs/blob/main/packages/intl-numberformat/package.json#L18).

**To Reproduce**
- Install the package in a project 
- check your node_modules

**Expected behavior**
These 2 fields should point to the right files (`polyfill.js`?).

**Comment by longlho** [comment]
hmm we can fix this but I'm not sure that'll fix your issue? There's no `main` file in polyfill basically, only `/polyfill`. What's your use case?

**Comment by ValentinH** [comment]
I faced the issue that is referenced above. A tool that is breaking because the main field is pointing to an inexistent file.

Isn't the polyfill.js the main file of the module?

**Comment by longlho** [comment]
It isn't because it doesn't export anything. We'll fix this issue regardless though

**Comment by longlho** [comment]
New version should have the fix. Thanks for reporting!

**Comment by ValentinH** [comment]
Thanks for the quick fix!
