### ISSUE TITLE
what is "typescript": "4"  id the dependecies ?

### ISSUE THREAD

**Issue by youbihi** [formatjs/formatjs#2370]
**Which package?**
react-intl@"^5.10.5"

**Describe the bug**

npm ERR! Could not resolve dependency:
#8 48.17 npm ERR! peerOptional typescript@"4" from react-intl@5.10.6
#8 48.17 npm ERR! node_modules/react-intl
#8 48.17 npm ERR!   react-intl@"^5.10.5" from the root project

**To Reproduce**
npm install

**Expected behavior**
should install properly react-intl. 

**Screenshots**
<img width="778" alt="Capture d’écran 2020-12-03 à 11 50 34" src="https://user-images.githubusercontent.com/5676321/101000160-ca779f80-355d-11eb-9985-2576e487abda.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser : Chrome

**Additional context**
I am runing a project on docker 2.5.0.1

**Comment by longlho** [comment]
Looks like you have a dependency on typescript@3 but we optionally need typescript@4
