### ISSUE TITLE
TypeError: Intl.Locale is not a constructor

### ISSUE THREAD

**Issue by michael-goetz-traversals** [formatjs/formatjs#2372]
**Which package?**
@formatjs/intl-displaynames/locale-data/de

**Describe the bug**
When I try to run tests this error occurs and the tests don't even start. This issue only appeared today, yesterday everything was working perfectly fine.

I deleted the node_modules folder and ran npm install which didn't resolve the issue.

```
TypeError: Intl.Locale is not a constructor

       9 | import '@testing-library/jest-dom';
      10 | import '@formatjs/intl-displaynames/polyfill';
    > 11 | import '@formatjs/intl-displaynames/locale-data/de';
         | ^
      12 | import '@formatjs/intl-displaynames/locale-data/en';
      13 | 
      14 | import TestBase from './TestBase';

      at Function.Object.<anonymous>.DisplayNames.__addLocaleData (node_modules/@formatjs/intl-displaynames/index.js:53:35)
      at Object.<anonymous> (node_modules/@formatjs/intl-displaynames/locale-data/de.js:4:21)
      at Object.<anonymous> (test/AppTesting.js:11:1)
      at Object.<anonymous> (src/page/progress/ProgressPage.test.tsx:8:1)

```

I tried debugging into the Intl.DisplayNames.__addLocaleData function and indeed Intl.Locale is undefined.
The Intl object only contains the following props:

- DateTimeFormat
- NumberFormat
- Collator
- PluralRules
- getCannonicalLocales
- DisplayNames

**To Reproduce**
None of my colleagues are able to reproduce this issue.

**Desktop (please complete the following information):**

- OS: macOS 10.15.5
- Browser: Running tests in Node
- Version: v11.10.1

**Comment by longlho** [comment]
Looks like you're running Node 11. You have to either upgrade to Node 12 or add Intl.Locale polyfill
