### ISSUE TITLE
Selectively install/import locale

### ISSUE THREAD

**Issue by tvvignesh** [formatjs/formatjs#2377]
**Which package?**
`@formatjs/intl`

**Describe the bug**
I was trying to understand which packages were taking up huge amount of space in my `node_modules` folder and reduce it and I noticed that `@formatjs/intl` was using `65M` of space and when I was trying to drill in to see why, I noticed this:

```
1.5M    ecma402-abstract@1.5.0
26M     intl-datetimeformat@3.0.0
29M     intl-displaynames@4.0.0
2.8M    intl-listformat@5.0.0
5.8M    intl-relativetimeformat@8.0.0
336K    intl@1.4.8
```

And when I drilled into it further, I noticed that it was because of `locale-data` folder which includes every locale which tool `26M` in total:

<img width="763" alt="e1" src="https://user-images.githubusercontent.com/1165845/101226622-0ffdaf00-36bb-11eb-96aa-db5f3f7e2645.PNG">

And the thing is the same `locale-data` is also duplicated multiple times. I saw that in `@formatjs/intl-datetimeformat/locale-data` and `@formatjs/intl-displaynames/locale-data` which again doubled the size of the package.

Just getting rid of the locales will free up `52MB` of space from my image.

**Expected behavior**

1. Ability to somehow just download the locales as needed
2. Prevent duplication of `locale-data` across packages especially when using one version of the package (in my case `"@formatjs/intl": "^1.4.8"`)

Thanks.

**Comment by longlho** [comment]
We neither care nor optimize for node modules size. The locale data are also not duplicate
