### ISSUE TITLE
intl-messageformat: unwanted removal of quotes

### ISSUE THREAD

**Issue by EmeraldWeb** [formatjs/formatjs#2388]
**Which package?**
intl-messageformat

**Describe the bug**
Method `IntlMessageFormat.format(values)` of string with markup like `"foo <a href={url} target='_blank'>bar</a>"` leads to removal of the closing quote of the atrtiibute "target"

**To Reproduce**
Example attached to report
npm install
npm run build
node console -> `"foo <a href=https://www.google.com/ target='_blank>bar</a>"`

**Expected behavior**
Method return right string:
`"foo <a href=https://www.google.com/ target='_blank'>bar</a>"`

**Desktop (please complete the following information):**
intl-messageformat: "9.3.20"
node": "10.19.0"

[bug-intl-messageformat.zip](https://github.com/formatjs/formatjs/files/5666875/bug-intl-messageformat.zip)

**Comment by longlho** [comment]
We don't allow full html with attributes in the message, only simple tags.

**Comment by longlho** [comment]
Actually what you're looking for is `ignoreTag` option in https://formatjs.io/docs/intl-messageformat#intlmessageformat-constructor
