### ISSUE TITLE
More specific locales gracefully fallback to general ones

### ISSUE THREAD

**Issue by osdiab** [formatjs/formatjs#2390]
**Which package?**
I use `intl-pluralrules`, so I mostly am posting about that, but it probably applies to others

**Is your feature request related to a problem? Please describe.**
We use the explicit `en-US` locale (and not just `en`) in our codebase; as a result a bug got through where the plural rules polyfill failed on our clients because when you specify `en` it works, but if you specify `en-US` it throws an error caused by the locale not being found—specifically, [this line](https://github.com/formatjs/formatjs/blob/main/packages/intl-pluralrules/index.ts#L44), with `Cannot read property 'fn' of undefined`—presumably since it does a dumb dictionary lookup instead of trying to strip the `-US` segment.

**Describe the solution you'd like**
Strip the `-US` segment in `en-US` if the more specific locale isn't found

**Describe alternatives you've considered**
There could also be explicit locale data includes for these... but that's verbose and potentially bad for bundle size.

**Comment by longlho** [comment]
Do you have a repro?

**Comment by longlho** [comment]
looks like u probably did not add `locale-data` per our [instruction](https://formatjs.io/docs/polyfills/intl-pluralrules)

**Comment by osdiab** [comment]
Thanks for closing this before even letting me respond.

I'm including the `en` locale as instructed (thanks for assuming I can't read), I need to research how I can make a repro for these kinds of issues given that said repro can't run on any modern browsers, and I have no antiquated machines to test on unlike you.

**Comment by osdiab** [comment]
Until I can cloud host an IE 10 machine, this is what my code looks like.

This is how I include the polyfill and locales:

```
import { shouldPolyfill as shouldPolyfillGetCanonicalLocales } from "@formatjs/intl-getcanonicallocales/should-polyfill";
import { shouldPolyfill as shouldPolyfillLocale } from "@formatjs/intl-locale/should-polyfill";
import { shouldPolyfill as shouldPolyfillPluralRules } from "@formatjs/intl-pluralrules/should-polyfill";

export async function installIntlPolyfills() {
  await Promise.all([
    shouldPolyfillLocale() && import("@formatjs/intl-locale/polyfill"),
    shouldPolyfillGetCanonicalLocales() &&
      import("@formatjs/intl-getcanonicallocales/polyfill"),
    ...(shouldPolyfillPluralRules()
      ? [
          import("@formatjs/intl-pluralrules/polyfill"),
          // TODO: decide which locales based on user browser
          import("@formatjs/intl-pluralrules/locale-data/en"),
        ]
      : []),
  ]);
}
installIntlPolyfills().then(() => {
  startApp();
});
```

This is how I use it:

```ts
const suffixes = new Map([
  ["one", "st"],
  ["two", "nd"],
  ["few", "rd"],
  ["other", "th"],
]);

export function ordinalNumberString(number: number): string {
  const pr = new Intl.PluralRules("en", {
    type: "ordinal",
  });

  const rule = pr.select(number);
  const suffix = suffixes.get(rule);
  return `${number}${suffix}`;
}

// somewhere else in React app
ordinalNumberString(4);
```

**Comment by longlho** [comment]
Feel free to reopen once you have a repro. We added unit tests for your case and it seems to be working.

**Comment by longlho** [comment]
Your code shouldn't use Promise.all. That loads things in parallel. You have to polyfill in a specific order.

**Comment by osdiab** [comment]
OK, thanks for letting me know.
