### ISSUE TITLE
Possible Translation error in Malay Relative Time

### ISSUE THREAD

**Issue by ChrisFrench** [formatjs/formatjs#2409]
**Which package?**
All versions I have checked. 

**Describe the bug**
Our professional translators have flagged the Malay translation for  "hours ago" set to "{0} jam lalu" but our translator said it should be "{0} jam yang lalu"

**To Reproduce**
Translation relative time with Malay. 

**Expected behavior**
Update the translation. 

**Screenshots**
N/A

**Comment by longlho** [comment]
So according to CLDR it is [`jam lalu` ](https://github.com/unicode-org/cldr-json/blob/master/cldr-json/cldr-dates-modern/main/ms/dateFields.json#L493) so this is something you might have to bring up to [Unicode](https://unicode-org.atlassian.net/jira/software/c/projects/CLDR/issues).

It might be the difference between standalone phrase vs in the middle of a sentence.
