### ISSUE TITLE
Error formatting time with `timeStyle`

### ISSUE THREAD

**Issue by jeffal** [formatjs/formatjs#2410]
**Which package?**
`@formatjs/intl`, more specifically: https://github.com/formatjs/formatjs/blob/main/packages/intl/src/dateTime.ts

**Describe the bug**
I did not set option `hour` and I receive the following error: `Error formatting time. Can't set option hour when timeStyle is used.`

**To Reproduce**

1. Use `FormattedTime` component
2. Set value
3. Set `timeStyle="short"`

**Expected behavior**
There should be no error. The time should format as expected.

**Screenshots**
https://codesandbox.io/s/fragrant-wildflower-uswse?fontsize=14&hidenavigation=1&theme=dark

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.7
- Browser: Chrome
- Version: 87

**Comment by longlho** [comment]
Thanks for reporting this is indeed a bug historically in how we default certain options. Will fix soon.

**Comment by jeffal** [comment]
I was thinking this may have to do with the following defaults being added here:
https://github.com/formatjs/formatjs/blob/main/packages/intl/src/dateTime.ts#L63-L71

**Comment by longlho** [comment]
Yup removing that might be a breaking change but would be more consistent w native API

**Comment by longlho** [comment]
latest version (being published rn) should have the fix

**Comment by jeffal** [comment]
Thanks for the amazingly quick response and fix!
