### ISSUE TITLE
Safari displaying wrong formatted date

### ISSUE THREAD

**Issue by jeffal** [formatjs/formatjs#2411]
**Which package?**
`@formatjs/react-intl`

**Describe the bug**
Safari displays the wrong date, e.g. `6/21/2003`.

**To Reproduce**

0. Add polyfills
1. Use `FormattedDate` component
2. Set value
3. Set props (view codesandbox.io demo)
4. View difference in Chrome, Firefox, and Safari should display the same date format.

**Expected behavior**
Chrome, Firefox, and Safari should display the same date format, e.g. `6/20/2003`

**Screenshots**
https://codesandbox.io/s/fragrant-wildflower-uswse?fontsize=14&hidenavigation=1&theme=dark

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.7
- Browser: Chrome
- Version: 87

**Comment by longlho** [comment]
You need to specify the timeZone or set the default timeZone. There's no way to access that info from JS automatically

**Comment by jeffal** [comment]
Thanks I will try this now.

**Comment by jeffal** [comment]
@longlho I guess I would expect the default timezone `UTC` to display the same date regardless of browser. Referring to https://formatjs.io/docs/polyfills/intl-datetimeformat/#default-timezone.

**Comment by longlho** [comment]
We default to UTC but browsers default to their respective tz in settings.

**Comment by longlho** [comment]
hmm I tried on Sauce Labs and couldn't repro the issue. They all display `06/20/2003`

**Comment by longlho** [comment]
Oh nvm looks like you set the default tz

**Comment by jeffal** [comment]
Yep, I set it to see the consistent behavior. Thank you for clarifying:

> We default to UTC but browsers default to their respective tz in settings.
