### ISSUE TITLE
Ssr format message show default value 

### ISSUE THREAD

**Issue by andreyradkevich** [formatjs/formatjs#2424]
https://stackoverflow.com/questions/65371060/ssr-react-intl-format-message-doesnt-work-properly

here I've described issue , could you pls check ? maybe I do something wrong

**Comment by longlho** [comment]
Do you have a minimal demo repo? You have to use intl.formatMessage and your intl must have the correct locale

**Comment by andreyradkevich** [comment]
No , I don't ..  it have correct messages , I get locale , by using koa ... and I see in logs , that I have th language for example , I also see that messages which I pass to IntlProvider correct , but when I open my site in view-source chrome , I see that It show there default message ... I've showed on stackoverflow how I solved it , but it doesn't seems well ...

On the client side all works well

**Comment by andreyradkevich** [comment]
If you need more information about some moments , I can attach other code snippets

**Comment by andreyradkevich** [comment]
"react-intl": "4.7.2" - version I use, and koa for ssr

**Comment by longlho** [comment]
Please submit a reproducible repo. Based on tour code snippets it's hard to tell.
