### ISSUE TITLE
Ts-transormer transforms not called in recent versions of ts-jest

### ISSUE THREAD

**Issue by sohara** [formatjs/formatjs#2436]
## Which package?
Since this is a monorepo. Please specify which package this bug report is for.
@formatjs/ts-transformer

## Describe the bug
In the most recent versions of ts-jest, it appears the transform configured in the jest config file is never ran, resulting in runtime errors such as `[@formatjs/intl] An `id` must be provided to format a message.`

### Codesandbox URL
https://codesandbox.io/s/confident-torvalds-r2on8

N.B. It appears to work fine on codesandbox so I believe this may be something platform specific. However I was seeing this error on both my host os (mac os 10.15.6) and in our docker ci containers (a node 14.5 container for Codefresh, presumably ubuntu-based).

### Reproducible Steps/Repo

Github repo here: https://github.com/sohara/react-intl-jest

1. Clone the repo on a host os, e.g. Mac os
2. `yarn install` (node 14.x and 10.x both failed for me)
3. Run `yarn test`
4. Tests error due to the `overrideIdFn` declared in the jest config file not having been ran. 
5. If you pin `ts-jest` to `26.4.0` and run `yarn install` the tests will subsequently pass.

## Expected behavior
The tests should pass regardless of the patch version of `ts-jest`

## Desktop (please complete the following information):

- OS: mac os 10.15.6

## Smartphone (please complete the following information):
N/A

**Comment by longlho** [comment]
hmm I cloned the repo and followed your step but seems like everything passed. Can u double check your versions of things?

**Comment by sohara** [comment]
Thanks for cloning and testing. It seems to have been an issue with yarn. After upgrading to a later yarn version and recreating the lock file I no longer got the errors.
