### ISSUE TITLE
Intl.DateTimeFormat.formatRange polyfill fails with "long" month format

### ISSUE THREAD

**Issue by kumikumi** [formatjs/formatjs#2474]
## Which package?
intl-datetimeformat

## Describe the bug
The formatRange method of DateTimeFormat objects constructed with options that specify `month: "long"`, returns a string containing nothing but an _en dash_ surrounded by spaces (` – `).

## To Reproduce

Viewing the following CodeSandbox shows "Format 2: – " on Firefox. It shows up as "Format 2: January 10 – 20, 2021" on Chrome (not polyfilled). Format 1 with `month: "numeric"` is working properly.

https://codesandbox.io/s/datetimeformat-polyfill-long-month-format-tqq75

## Expected behavior
Maybe similar behavior to Chrome? Or at least fall back to something human readable.

**Comment by kumikumi** [comment]
It appears the polyfill also fails similarly on the following format options:

```
{
  year: "numeric",
  month: "short",
  day: "numeric",
  hour: "numeric",
  minute: "numeric"
}
```

I have added it to the CodeSandbox.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
