### ISSUE TITLE
Custom extractor for CLI tool

### ISSUE THREAD

**Issue by uded** [formatjs/formatjs#2484]
As I couldn't find any information regarding my issue I would like to ask if there is any way to extend the current extractor to support different formats? We use [UmiJS locale plugin](https://github.com/umijs/plugins/tree/master/packages/plugin-locale) as part of UmiJS app. Navigation is generated there by configuration files and names of the navigation links come either from a separated config file or other sources. The current extractor cannot work with such structures. But it should be extremely easy to extend...

**Comment by uded** [comment]
Alternatively, can the tool stop overriding JSON file but rather merge it? We can add missing keys by hand, but then every time we will run the extractor we will lose those.

In a perfect world, that file should be just updated. And if the keys were removed a warning should be issued to a developer.

**Comment by longlho** [comment]
Can u provide a repo that demo what you're trying to achieve?

**Comment by uded** [comment]
Sure. Official AntD ReactJS Pro theme is using localization plugin from UmiJS, which is just wrapping React-Intl.

We have a file with all routes declaration:

https://github.com/ant-design/ant-design-pro/blob/master/config/routes.ts

All routes in those files are identified for translation purposes by `menu.$(name)`, where the `name` parameter comes from this definition. It would be easy for me to _feed_ the list of those with proper formatting, but currently, I couldn't find any hook within the extractor CLI or library for this purpose.

It's one of the examples, I am certain there are more use cases for that...

**Comment by longlho** [comment]
I still don't understand what you're trying to achieve. How are the translations declared? Is there a sample repo that demo what you're trying to do?

**Comment by uded** [comment]
Every route defined has a name property, i.e:

```typescript
export default [
  {
    path: '/',
    component: '../layouts/BlankLayout',
    routes: [
      {
        path: '/user',
        component: '../layouts/UserLayout',
        routes: [
          {
            name: 'login',
            path: '/user/login',
            component: './User/login',
          },
        ],
      },
];
```

The translation key I need to add to a resulting JSON is `menu.login` in the above case. No default translation, unfortunately. There are some additional declarative properties (like `title`) - you can look [here](https://umijs.org/plugins/plugin-locale#build-time-configuration). 

Seems simple, but since I cannot find any extension point I cannot add those to the resulting JSON. And since JSON file will be overwritten every time using CLI is pointless...

**Comment by longlho** [comment]
Sounds like it's best if u would extract those separately. Our CLI only extract from messages declared in the codebase.

**Comment by uded** [comment]
Yes, that is what I meant. Sorry if I haven't myself easier to understand :-(

Since I would really prefer to use your CLI -- as most people would probably -- I see two options only:
* extract should rather add/remove messages from JSON rather than overriding it - this seems to be rather difficult, would require probably a big rewrite of the extractor and CLI tooling
* extend the `extract` method with a hook so I can run additional methods and feed messages to it - this seems simpler, will give a lot of flexibility when it comes to extracting and processing JSON message file

Hence my question/request. I believe that my approach would be the most flexible one, meaning if something comes from an external source I can easily add this to the JSON already created and maintained by your CLI.

**Comment by longlho** [comment]
Yeah so this is pretty unique to your use case unfortunately since we haven't seen it at all. I'd suggest you extract the special stuff out of band and merge in separately. We don't have any plan to expand the CLI for arbitrary json merging anytime soon.
