### ISSUE TITLE
ts-transformer is replacing newlines with normal space

### ISSUE THREAD

**Issue by myjian** [formatjs/formatjs#2485]
## Which package?
ts-transformer

## Describe the bug
When I write the following code
```
intl.formatMessage({
  defaultMessage: 'Please describe the issue you’re experiencing.\nIf relevant, please describe the steps to reproduce this issue.',
})
// \u00a0 = no-break space
intl.formatMessage({
  defaultMessage: '{tax_name}:\u00a0{tax_amount}',
})
```

## Expected behavior
The output will preserve `\n` and no-break space.

## Actual behavior
`\n` and `\u00a0` are replaced with a normal space ` `.

**Comment by longlho** [comment]
This is intentional since most of the time, preserving `\n` and special Unicode character is not i18n-safe. These are often used for styling/layout purposes, which you should use HTML/CSS and such for.
