### ISSUE TITLE
Support concise number skeleton

### ISSUE THREAD

**Issue by SandroMaglione** [formatjs/formatjs#2512]
Hi,

I am trying to display different measure units based on the current locale.
Following [the example of `currency`](https://formatjs.io/docs/intl-messageformat#number-skeleton) and the [specifications](https://github.com/unicode-org/icu/blob/master/docs/userguide/format_parse/numbers/skeletons.md) I did this:
```json
{
  "price": "The price is: {price, number, ::currency/EUR}",
  "unit": "Unit {value, number, ::unit/meter}"
}
```
Unfortunately, it does not seem to work:
![Screenshot 2021-01-18 183053](https://user-images.githubusercontent.com/10065056/104947021-52552400-59bb-11eb-964a-2e8f71e11f93.png)
`currency` works, while `unit` does not display `m` (for meters) as I expect.

Am I doing something wrong? How can I achieve this also for other units (weight)?

**Comment by longlho** [comment]
try the long skeleton version: `measure-unit/length-meter`

**Comment by SandroMaglione** [comment]
Thanks @longlho, it works with the long skeleton.

I can't seem to find the skeleton for how to achieve the same result for weight measures (`kg`, `lbs`, etc.), do you know if a skeleton for weight measures exists and if it is supported?

**Comment by longlho** [comment]
The list of sanctioned units are here: https://402.ecma-international.org/7.0/index.html#table-sanctioned-simple-unit-identifiers
