### ISSUE TITLE
[formatjs extract] Multiple source locations get lost

### ISSUE THREAD

**Issue by hjylewis** [formatjs/formatjs#2523]
## Which package?
cli

## Describe the bug
When using `formatjs extract` with the `--extract-source-location` flag, if the same defaultMessage is used multiple places (and thus the id is the same), the extracted file will only have the source location for one of the locations.

### Reproducible Steps/Repo

1. Create two files
2. In each file, write `intl.formatMessage({ defaultMessage: 'Hello world'});`
3. Run `formatjs extract --extract-source-location` on the files
4. The output file should only have source location data for one of the files

## Expected behavior
It would be great to have an array of source location data per message. 
Looks like the multiple messages with different source location data are being overwritten here: https://github.com/formatjs/formatjs/blob/main/packages/cli/src/extract.ts#L223

**Comment by longlho** [comment]
hmm yeah we can support this & ofc PR's always welcome :)

**Comment by hjylewis** [comment]
Cool, I can work on a PR for this.

Currently when `extract-source-location=true` we output something like this:
```json
{
  "trailing.ws": {
    "col": 21,
    "defaultMessage": "Some whitespace",
    "description": "Whitespace",
    "end": 650,
    "file": "defineMessages/actual.js",
    "line": 20,
    "start": 545,
    "meta" : {
      "baz": "1",
      "foo": "bar"
    } 
  }
}
```

Instead, should we output something like this?
```json
{
  "trailing.ws": {
    "defaultMessage": "Some whitespace",
    "description": "Whitespace",
    "locations": [
      {
        "col": 21,
        "end": 650,
        "file": "defineMessages/actual.js",
        "line": 20,
        "start": 545,
        "meta" : {
          "baz": "1",
          "foo": "bar"
        } 
      }
    ]
  }
}
```
This seems like it would be the correct API. It would be a breaking change.

**Comment by longlho** [comment]
Yeah sgtm we can bump major
