### ISSUE TITLE
Add support for the "integer-width" stem to formatted numbers

### ISSUE THREAD

**Issue by nickiaconis** [formatjs/formatjs#2525]
#### Which package?
intl-messageformat-parser

#### Is your feature request related to a problem? Please describe.
I'd like to zero pad some number values that are passed to a formatted message which is using the number formatter. This would be achievable using the `integer-width` skeleton described in the ICU user guide [here](https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html#integer-width) (linked to from the FormatJS docs [here](https://formatjs.io/docs/core-concepts/icu-syntax#number-type)), but the `integer-width` skeleton is not currently implemented.

#### Describe the solution you'd like
To be able to use the `integer-width` stem in number skeletons, ex: `{value, number, ::integer-width/*000}`

#### Describe alternatives you've considered
One potential workaround is to convert the number to a string before passing it to the formatted message. As a string, it can be padded with leading zeros. If an instance of `Intl.NumberFormat` with the `minimumIntegerDigits` option is used to both convert the number to a string and pad it with zeros, the number will also still receive number formatting.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
Latest version should support `integer-width/*0000` & its concise form `000`. Note that there's no support for max integer digits or exact integer digits. That's something you'd have to propose to ECMA402 1st.
