### ISSUE TITLE
Support multiline template literals

### ISSUE THREAD

**Issue by hjylewis** [formatjs/formatjs#2527]
**Which package?**
ts-transformer, eslint-plugin-formatjs

**Is your feature request related to a problem? Please describe.**
Similar to #2252

Right now if you do something like this with a template literal to split the defaultMessage across multiple lines, `eslint-plugin-formatjs/enforce-default-message` will error since it's not a string literal or concatenation of string literals.
```js
const myMessage = intl.formatMessage({
  defaultMessage: `Integer mattis eros cursus eros tempus, mollis
                   ullamcorper justo aliquam. Sed a diam vel eros
                   feugiat malesuada. Aliquam condimentum rhoncus
                   nibh tempus tempus. Nulla eget lobortis massa.`,
  id: 'test.loremIpsum'
});
```

**Describe the solution you'd like**
Ideally, since this a template literal containing no expressions, it is static and should be treated like a string literal.

Eslint should not error and the developer should be able to extract the message using the cli.

Sure a developer could just use the concatenated string literals solution but I think it would be more intuitive to support both. Unless you can think of a reason not to. Happy to try to open a PR for this.

**Comment by longlho** [comment]
The primary reason is that it intentionally preserves trailing whitespaces in the middle of your sentences so it basically has built-in footgun there. In your example when it got sent to translation vendor it'll become something like `Integer mattis eros cursus eros tempus, mollis (a ton of spaces) ullamcorper justo aliquam. Sed a diam vel eros (a ton of spaces) feugiat malesuada. Aliquam condimentum rhoncus (a ton of spaces) nibh tempus tempus. Nulla eget lobortis massa.`.

**Comment by hjylewis** [comment]
I could be mistaken but it looks like `ts-transformer` replaces those [spaces with a single space](https://github.com/formatjs/formatjs/blob/main/packages/ts-transformer/src/transform.ts#L310).

I just checked and `react-intl` does the same thing with defaultMessage at runtime though I can't find where in the source code that's happening.

**Comment by longlho** [comment]
ts-transformer did it primarily bc of historical reasons. In cases where IDs are autogen as hash from `defaultMessage` & `description`, trimming whitespace results in ID mismatch so we prefer linting the source instead. Otherwise you have to do it both at runtime, everytime, and build time, which is brittle and annoying to debug.

**Comment by hjylewis** [comment]
Fair enough makes sense.

In that case, if the concatenation of string literals is the ordained way to do multi-line `defaultMessage` or `description` that should probably be called out somewhere in the docs.

**Comment by longlho** [comment]
hmm we can't actually extract string literals concat. So it's basically would have to be a long string, or broken up into sentences.

**Comment by hjylewis** [comment]
> hmm we can't actually extract string literals concat. So it's basically would have to be a long string, or broken up into sentences.

Hmm, not sure I follow...

Doesn't this change https://github.com/formatjs/formatjs/commit/24454ba57e76ef9cf9ef75a2c17ee7fd825100d0 add support for extracting static string concat static?

**Comment by longlho** [comment]
You're right. I confused myself. We do support that :)

**Comment by longlho** [comment]
Had a discussion internally. This is something we can support.

**Comment by hjylewis** [comment]
Awesome, thank you!
