### ISSUE TITLE
Set usage isn't IE11-safe

### ISSUE THREAD

**Issue by devnix** [formatjs/formatjs#2529]
Hi. I'm literally getting a `Missing locale data for` without more info, it's literally that message in IE11.

Tested code:
```javascriptr
new Date().toLocaleString("es", {timeZone: "MADRID/EUROPE"});
```

Added dependencies:
```javascript
import '@formatjs/intl-getcanonicallocales/polyfill';
import '@formatjs/intl-locale/polyfill';

import '@formatjs/intl-pluralrules/polyfill'
import '@formatjs/intl-pluralrules/locale-data/en' // locale-data for en

import '@formatjs/intl-numberformat/polyfill'
import '@formatjs/intl-numberformat/locale-data/en' // locale-data for en

import '@formatjs/intl-datetimeformat/polyfill'
import '@formatjs/intl-datetimeformat/add-all-tz' // Add ALL tz data
```

Is there something I'm missing from the docs? I've been banging my head on the keyboard for hours.

**Comment by longlho** [comment]
You have to add `es` locale data instead of `en`. Your timezone also isn't valid

**Comment by devnix** [comment]
@longlho Already tried importing `@formatjs/intl-pluralrules/locale-data/es` and `@formatjs/intl-numberformat/locale-data/es` with same results. Also with `new Date().toLocaleString("en", {timeZone: "MADRID/EUROPE"});` with both required.

Not specifying a timezone (I'm using this polyfill just for that feature that works on Chrome and other browsers) has the same problem: `new Date().toLocaleString("es");`

What annoys me more is that white space at the end of the error string:
![image](https://user-images.githubusercontent.com/1777519/105507133-1f68a400-5ccb-11eb-8f45-bb23b0888bcb.png)

**Comment by longlho** [comment]
Do u have a reproducible repo of some sort? Can you use `Intl.DateTimeFormat`? `Date.toLocaleString` is significantly slower.

**Comment by devnix** [comment]
@longlho same `Missing locale data for`

**Comment by longlho** [comment]
oh u didn't add any locale data for `intl-datetimeformat`...

**Comment by devnix** [comment]
@longlho Didn't I? Look at the last line of the first post:
```js
import '@formatjs/intl-datetimeformat/add-all-tz' // Add ALL tz data
```

**Comment by longlho** [comment]
That's timezone data which is separate from locale-data. See https://formatjs.io/docs/polyfills/intl-datetimeformat#simple

**Comment by devnix** [comment]
*Oh no...* Will test it tomorrow.

Is there any way to load the browser locale automatically?

Thanks for your patience @longlho

**Comment by longlho** [comment]
Unfortunately we do not get access to browser default locale due to fingerprinting privacy issue.

**Comment by devnix** [comment]
@longlho So now it's working, but it does not find the timezone
![image](https://user-images.githubusercontent.com/1777519/105820236-96e34f80-5fb9-11eb-99ff-116e51fb4386.png)
It should work with this configuration, right?

```js
import '@formatjs/intl-getcanonicallocales/polyfill';
import '@formatjs/intl-locale/polyfill';

import '@formatjs/intl-pluralrules/polyfill'
import '@formatjs/intl-pluralrules/locale-data/en' // locale-data for en

import '@formatjs/intl-numberformat/polyfill'
import '@formatjs/intl-numberformat/locale-data/en' // locale-data for en

import '@formatjs/intl-datetimeformat/polyfill'
import '@formatjs/intl-datetimeformat/locale-data/en' // locale-data for en
import '@formatjs/intl-datetimeformat/add-all-tz' // Add ALL tz data
```

**Comment by longlho** [comment]
hmm I can't reproduce this. Do you have a reproducible repo? What versions of things are you using?

**Comment by boschni** [comment]
I was running into the same issue on IE11 and tracked it down to https://github.com/formatjs/formatjs/blob/main/packages/ecma402-abstract/IsValidTimeZoneName.ts .

A Set instance is created by providing an iterable to the constructor, which is not supported in IE11. You can get it working by adding a Set polyfill.

Might be good to change the `IsValidTimeZoneName` implementation or to mention this dependency at https://formatjs.io/docs/guides/runtime-requirements ?

**Comment by longlho** [comment]
thanks for the info @boschni that's something we can fix on our side
