### ISSUE TITLE
Correct Date for en-US and en-GB

### ISSUE THREAD

**Issue by vitaliuststilouski** [formatjs/formatjs#2531]
formatsJS

## Which package?
    "react-intl": "^5.8.4",

## Describe the bug

```javascript
//// 1 component
const App = () => {
    return (
      <IntlProvider locale="de-DE">

      <div className="App">
        <Navbar navTitle="GitHub" icon="fab fa-github"/>

        <div className="container">
          <UserItem />
        </div>
      </div>
      </IntlProvider>

  );
}

export default App;

export const UserItem = ({id, avatarUrl, htmlUrl, login}: userItemProps) => {
  const { formatDate,  } = useIntl();

  const FORMAT_DATE_LOCALE = {
    year: "numeric",
    month: "numeric",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
    timeZone: "UTC",
  };

  const date = formatDate(Date.now(), FORMAT_DATE_LOCALE);


  return (
    <div key={id} className="card text-center">

      {date}
    </div>
  )
}

```
en-US should be M/D/YYYY i.e. 1/24/2021  en-GB DD/MM/YYY ie  24/01/2021.

When I input in locale locale="en-GB" even with numeric it shows correctly 02/01/2021. if I input es-ES or de-DE
it shows as  24/1/202  for ES  24.1.2021 for DE  because of numeric.
I could use 2-digit property but then I will have issues with en-US, nevertheless with en-GB 24/01/2021. it works correctly.

Is it a but of lib?

**Comment by longlho** [comment]
I'm not sure I understand your issue. What's the current & expected output?

**Comment by vitaliuststilouski** [comment]
> I'm not sure I understand your issue. What's the current & expected output?

I have 4 locales en-GB , en-US, es-ES , de-DE

So my expectations is that when I switch locale from  en-GB 24/01/2021 to de-DE there will be 24.01.2021 instead 24.1.2021
and if I swtich locale from de-DE to en-US it will be 1/24/2021.

More details:
works correct for en-US and  en-GB only (no de-DE, es-ES)
```javascript
  const FORMAT_DATE_LOCALE = {
    year: "numeric",
    month: "numeric",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
    timeZone: "UTC",
  };
```
  ------------------------------------------
  works correct for  en-GB, de-DE, es-ES only (no en-US)
```javascript
  const FORMAT_DATE_LOCALE = {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
    timeZone: "UTC",
  };
```

**Comment by longlho** [comment]
Hmm how do you know that it's incorrect? Our pattern data comes from CLDR which is part of unicode. This seems like a bug in Unicode.

**Comment by vitaliuststilouski** [comment]
>  how do you know that it's incorrect? 

please, check the code when month and day are numeric

for en-GB,   24/01/2021
for es-ES,   24/1/2021
for de-DE,   24/01/2021

**Comment by longlho** [comment]
```js
new Intl.DateTimeFormat('de-DE', {
    year: "numeric",
    month: "numeric",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
    timeZone: "UTC",
  }).format(Date.now())

// 25.1.2021, 18:08:33
```

ok this doesn't seem like our issue but rather ECMA402/Unicode issue (if it's actually an issue) since we use that API. I'd recommend you submitting an issue there.

**Comment by vitaliuststilouski** [comment]
ok, thanks

``` javascript
new Intl.DateTimeFormat('en-GB', {
    year: "numeric",
    month: "numeric",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
    timeZone: "UTC",
  }).format(Date.now())

//  "25/01/2021, 18:40:54"
```
