### ISSUE TITLE
No exported type MessageFormatElement

### ISSUE THREAD

**Issue by hannahatwork** [formatjs/formatjs#2559]
## Which package?
react-intl

## Describe the bug
There is no exported type for compiled messages.

## To Reproduce

Implement the code in [the "message distribution" part of the docs](https://formatjs.io/docs/getting-started/message-distribution/#distribution) and try to add a type for `props.messages`.

### Reproducible Steps/Repo

Generate some compiled translations using the `formatjs` command. Resulting object looks roughly like:

```
{
  "2x0bZ6": [
    {
      "type": 0,
      "value": "There "
    },
    {
      "offset": 0,
      "options": {
        "=0": {
          "value": [
            {
              "type": 0,
              "value": "are no clients"
            }
          ]
        },
        "=1": {
          "value": [
            {
              "type": 0,
              "value": "is 1 client"
            }
          ]
        },
// etc...
```

Then implement the code in the "message distribution" step of the FormatJS docs. The `messages` prop of the `AuthProvider` expects the following type: `(JSX attribute) messages?: Record<string, string> | Record<string, MessageFormatElement[]> | undefined` but no `MessageFormatElement` type is exported by `react-intl`.

## Expected behavior
There should be an exported type that can be used to type the compiled messages that are generated by `formatjs`.

## Screenshots
<img width="832" alt="Screen Shot 2021-02-03 at 4 04 55 PM" src="https://user-images.githubusercontent.com/39274364/106821061-b7567e00-6639-11eb-8ac1-7ca56747e29e.png">

Note: It looks like there used to be some type guidance in the docs, but it was wrong, so it was removed. See https://github.com/formatjs/formatjs/issues/1900

**Comment by 2ico** [comment]
This is still an issue when using `createIntl` from '@formatjs/intl'
