### ISSUE TITLE
[babel-plugin-formatjs] MissingValueError not thrown

### ISSUE THREAD

**Issue by daugsbi** [formatjs/formatjs#2563]
## Which package?
I've experienced the issue with the babel-plugin-formatjs package, but other packages could also be affected.

## Describe the bug
The MissingValueError is not thrown during build step. 

## To Reproduce
Create a FormatMessage with interpolations that don't match the values object. 

```ts
  <FormattedMessage id="myMessage" defaultMessage="Hello {name}" values={{ notName: "Denis" }} />
```

No build error is thrown during build step from babel-plugin-formatjs.  Other errors are thrown, i.e. invalid syntax. During runtime the expected error is thrown. 

### Codesandbox URL

Let me know if you need a repository. 

## Expected behavior
I expect that an error is thrown, i.e. a MissingValueError. Maybe this is intentional because you will only have some values during runtime. I would still exepect to have an error if the keys do not exist in a provided values object. 

## Desktop (please complete the following information):

- OS: Linux
- Browser Chrome 88
- Node 14.15

**Comment by longlho** [comment]
babel plugin doesn't do verification. I think you're looking for https://formatjs.io/docs/tooling/linter#enforce-placeholders

**Comment by daugsbi** [comment]
@longlho Thanks for mentioning the linter. Great alternative, also with more useful options :+1:
