### ISSUE TITLE
Default locale is not working

### ISSUE THREAD

**Issue by index325** [formatjs/formatjs#2573]
I'm trying to use the defaultLocale property on IntlProvider, but it's not working as I spected. I want my app returns me a message in english when I'm trying to enter in the app using a locale that my app doesn't have as a translation (like german).

Version: "react-intl": "^5.11.0"

Code: https://gist.github.com/index325/1d428d40e3ab17d12c6db3a4fb84080b

**Comment by longlho** [comment]
Can you elaborate what your expectations are?

**Comment by index325** [comment]
I want a fallback locale when I enter the app. When I log-in using a locale that I doesn't have in my translations file (like german), I want to see the messages in a default locale (english)

**Comment by longlho** [comment]
Did u set `defaultMessage` in your code?

**Comment by index325** [comment]
But I need to put the defaultMessage everywhere in my code?

**Comment by longlho** [comment]
`react-intl` is not aware of how to pull in external resource JSON file. It can only do formatting. You should specify `defaultMessage` and use extraction to generate translation files. See https://formatjs.io/docs/getting-started/message-declaration

I think you've misunderstood how `defaultLocale` works. See https://formatjs.io/docs/react-intl/components/#defaultlocale-and-defaultformats. It's the `locale` that your `defaultMessage` is written in, so that you can have a coherent sentence in a single locale. Otherwise you run into scenario like English sentence with Chinese dates/numbers.

**Comment by kevintap-idemia** [comment]
It seems like there's something missing altogether with react-intl and IntlProvider. For some reason, IntlProvider accepts a locale and defaultLocale, but the messages object passed to IntlProvider must only contain messages for a single locale? Why even bother passing locale and defaultLocale to IntlProvider if you have to manually do the lookup of the appropriate messages and supply only a single locale to IntlProvider?

`    <IntlProvider locale={localeData.locale} defaultLocale={localeData.defaultLocale} messages={messages[localeData.locale]}>
`
Why is react-intl's IntlProvider not accepting a messages object like:
```
const messages = {
  en: {
    'username': 'User name'
  },
  de: {
    'username': 'Benutzer'
  },
  fr: {
    'no_username': '...'
  }
}

```
and doing the lookup itself, searching first for a matching message id in the locale, and then falling back to a message in the defaultLocale?

for example with my messages object above:
```
<IntlProvider locale={'fr'} defaultLocale={'de'} messages={messages}>
...
    <FormattedMessage id='username'>
```
expected output is:
`Benutzer
`
FormattedMessage would first try messages[locale][id] and see there is no 'username' id for 'fr', then try message[defaultLocale][id] and locate the translated message for the supplied id in the defaultLocale (in this case 'de').

**Comment by longlho** [comment]
Because we already have the defaultMessage when you declare using FormattedMessage or intl.formatMessage

**Comment by jlil** [comment]
I agree with @kevintap-idemia. I did expect the same output.

**Comment by yagofrancia** [comment]
Any thoughts on this?
