### ISSUE TITLE
Installing cli should not generate missing peer dependency warning on vue

### ISSUE THREAD

**Issue by aldenquimby** [formatjs/formatjs#2581]
## Which package?
- cli

## Describe the bug
When installing `@formatjs/cli`, I get npm warnings about a missing `vue` dependency, even though my project doesn't use vue.

### Reproducible Steps/Repo
1. `npm i --save-dev @formatjs/cli`

## Expected behavior
- no warnings are generated for missing peer dependencies

## Screenshots
- this warning is generated:
```
npm WARN @vue/compiler-sfc@3.0.5 requires a peer of vue@3.0.5 but none is installed. You must install peer dependencies yourself.
```

## Desktop (please complete the following information):
- OS: Mac
- Browser: N/A
- Version: `@formatjs/cli` 3.0.5

## Smartphone (please complete the following information):
- N/A

## Additional context
- Could the `@vue/*` dependencies be split into a separate vue-extractor package?

**Comment by longlho** [comment]
this seems to be a vue compiler-sfc issue so I put a PR other there
