### ISSUE TITLE
Option to preserve newline/whitespace to ease migration

### ISSUE THREAD

**Issue by skoging** [formatjs/formatjs#2588]
## Which package?
@formatjs/cli

## Describe the bug
v1 of the CLI, and the babel plugin before that, preserved whitespace and newlines in default messages.

v2.0 dropped support for template strings all together, and later in v2.9 added back support but now with whitespace being trimmed.

I get the reasoning behind trimming whitespace, and will not argue against that. My issue is the lack of a gradual migration path. I intend to move away from multiline messages, but that will require some bigger changes to how we handle translations. Having to do this before I can update from v1 of the CLI is not ideal. A simple option to disable trimming would alleviate this issue in my case. This option could then be removed in a future major version.

Similarly, moving away from explicit IDs to generated  ones is on the agenda, but for that at least there's a gradual migration path.

**Comment by longlho** [comment]
Can u provide some example use cases? We can potentially autofix your codebase with our [linter](https://formatjs.io/docs/tooling/linter).

**Comment by skoging** [comment]
We're using `white-space: pre-line` so that we can have a single message with multiple lines of text. From what I can see in discussions here we would have to split these into separate messages, since there's currently no good way to encode a line break in a message.

Migrating away from this while preserving all existing translations will take us some time, and is currently blocking us from upgrading from v1 of the CLI.

We'll be using the linter to catch this going forward, but I don't see how it could autofix our codebase in this case.

**Comment by longlho** [comment]
fixed by #2592
