### ISSUE TITLE
Docs: Recipe for `FormatRelativeTime` and long units (e.g. days)

### ISSUE THREAD

**Issue by czabaj** [formatjs/formatjs#2595]
Suppose we want to display a relative date as "today" and "tomorrow". We will use [FormatRelativeTime](https://formatjs.io/docs/react-intl/components/#formattedrelativetime) for this purpose

```JSX
import { addDays, endOfToday } from "date-fns";
import { FormattedRelativeTime } from "react-intl";

const DAY = 24 * 60 * 60 * 1000;

const RelativeDay = ({ day }) => {
  const dayDiff = (new Date(day) - endOfToday()) / DAY;
  return (
    <FormattedRelativeTime
      value={Math.ceil(dayDiff)}
      unit="day"
      numeric="auto"
    />
  );
};
```

See [CodeSandbox for an interactive experience](https://codesandbox.io/s/react-intl-playground-fk2ky?file=/src/App.js) 🧙‍♂️ 

Note we must use `Math.ceil` to round the fractional `dayDiff` up to render nice `today` or `tomorrow` text, otherwise with fractional value, we would render something like `0.12356 day` which is very ugly.

The component version of formatRelativeTime API has the nice advantage as it is able to automatically self-update on the next _interesting moment_, so over midnight, it is able to automatically change `tomorrow` to `today`. But written like this, the component will probably never update, as we set the unit to `days` and the value is an integer, so the next _interesting moment_ is after 24 hours. The component has no clue about the original `dayDiff`, it obtained only the round-up value.

The `FormattedRelativeTime` also accepts `updateIntervalInSeconds` prop, which sets

> maximum interval that the component will re-render
> -- https://formatjs.io/docs/react-intl/components/#formattedrelativetime

which sets the upper limit for the update, so we are able to shrink the 24 hours interval to our fractional value. But the `updateIntervalInSeconds` must not be larger than 1 hour (we use an outdated version of `react-intl`, maybe this limit is gone, but it makes sense), so if we want to be able to change `tomorrow` to `today` as the midnight passes, we must set `updateIntervalInSeconds` but only if the `dayDiff` is shorter than 1 hour, right?

Or is there a better solution? The approach I have described is very complicated, I think this scenario deserves documentation, is there propper place fur such a recipe?

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by czabaj** [comment]
Actually, achieving auto-update on the next "interesting moment" is more complicated for long units. Using `updateIntervalInSeconds` fixes nothing, as the original `value` supplied is still an integer.

To achieve automatic updates with long units, we must use something like

```JSX
const DAY = 24 * 60 * 60 * 1000;

const RelativeDay = ({ day }) => {
  const dayDiff = (new Date(day) - endOfToday()) / DAY;
  return (
    <FormattedRelativeTime
      value={dayDiff}
      unit="day"
      numeric="auto"
    >
      {() => (
         <FormattedRelativeTime
          value={Math.ceil(dayDiff)}
          unit="day"
          numeric="auto"
        />
      )}
  </FormattedRelativeTime>
  );
};
```

The first `FormattedRelativeTime` receives raw, un-rounded value, thus shall be able to auto-update but we don't want its ugly formatted value, so we use another `FormattedRelativeTime` inside its render prop, which uses a round-up value to render nice `today`, `tomorrow` or `after {integer} days`.

**Comment by longlho** [comment]
Would it help if we just separate out the auto-updating logic so u can effectively make `FormattedRelativeTime` a controlled element & reuse the "interesting moment" detection logic?
