### ISSUE TITLE
@formatjs/intl-datetimeformat skeleton matching adds `at`

### ISSUE THREAD

**Issue by JoeQuattrone** [formatjs/formatjs#2599]
Upon upgrading from V2 to 3.12.1 I found that intl.formatDate adds the word "at" in the date. This is problematic because it breaks all my tests and is an undocumented effect of the upgrade. How do I remove the "at" from the date?

### Steps To Reproduce:

intl =  createIntl( {
    locale: 'en',
    messages: {}
  }),
  createIntlCache()

intl.formatDate(Date.now(), {
        year: 'numeric',
        month: 'long',
        day: '2-digit',
        hour: 'numeric',
        minute: 'numeric'
      })

Version 3.12.1
=> February 12, 2021 **_at_** 10:15 AM

Version 2
=> February 12, 2021, 10:15 AM

Polyfills:
import '@formatjs/intl-locale/polyfill'

/* For the list of polyfills see https://formatjs.io/docs/polyfills */
import '@formatjs/intl-datetimeformat/polyfill'
import '@formatjs/intl-datetimeformat/locale-data/en'
import '@formatjs/intl-datetimeformat/locale-data/es'
import '@formatjs/intl-datetimeformat/locale-data/ja'
import '@formatjs/intl-datetimeformat/add-all-tz' // Add ALL timezonez data

// sets timezone on all <IntlProvider timeZone="America/New_York"> 
if ('__setDefaultTimeZone' in Intl.DateTimeFormat) {
  // tslint:disable-next-line
  Intl.DateTimeFormat.__setDefaultTimeZone('America/New_York')
}

import '@formatjs/intl-numberformat/polyfill'
import '@formatjs/intl-numberformat/locale-data/en'
import '@formatjs/intl-numberformat/locale-data/es'
import '@formatjs/intl-numberformat/locale-data/ja'

import '@formatjs/intl-pluralrules/polyfill'
import '@formatjs/intl-pluralrules/locale-data/en'
import '@formatjs/intl-pluralrules/locale-data/es'
import '@formatjs/intl-pluralrules/locale-data/ja'

import '@formatjs/intl-relativetimeformat/polyfill'
import '@formatjs/intl-relativetimeformat/locale-data/en'
import '@formatjs/intl-relativetimeformat/locale-data/es'
import '@formatjs/intl-relativetimeformat/locale-data/ja'

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by JoeQuattrone** [comment]
I can confirm that the source of this issue is the '@formatjs/intl-relativetimeformat/polyfill' package. Removing it, resolves the issue
