### ISSUE TITLE
intl-datetimeformat polyfill somehow breaks Luxon's timezone support

### ISSUE THREAD

**Issue by kumikumi** [formatjs/formatjs#2605]
## Which package?
intl-datetimeformat

## Describe the bug

Viewing the below Codesandbox on Firefox (I'm trying this on Firefox 85) converts the provided Luxon DateTime to UTC before formatting it. For example, in my timezone I would expect to see "February 15, 2021, 10:00 AM GMT+2" but instead I'm seeing "February 15, 2021 at 8:00 AM UTC" on Firefox. This is especially unexpected when viewing the time using time formats that don't display the timezone.

Commenting out the polyfill imports fixes the problem and produces the expected result. Also viewing the Codesandbox on Chrome produces the expected result, as the polyfill does not activate on Chrome.

### Codesandbox URL

https://codesandbox.io/s/datetimeformat-polyfill-timezone-jipvd?file=/src/index.js

## Expected behavior

User's own local timezone should be displayed, and "hours" should be 10 (as provided in the args).

## Additional context

I need Luxon's formatting to be working and Intl.DateTimeFormat.formatRange to be polyfilled at the same time. 

Also, thanks for all your work, and sorry for reporting this issue in vague terms. I don't know which part of Luxon's internals it breaks and why.

**Comment by longlho** [comment]
We cannot detect user's timezone so you'd have to manually pass it in

**Comment by kumikumi** [comment]
I guess the problem is, that in the codesandbox where I'm passing "hours: 10" to the DateTime constructor, it _does_ at least in some part manage to detect my timezone (UTC+2), otherwise it wouldn't know to rewind the clock 2 hours and display the wrong/unexpected time (8:00).

**Comment by longlho** [comment]
Browser does know its timezone but does not expose that via any JS API that we can use due to privacy/fingerprinting issue.

**Comment by kumikumi** [comment]
But surely, you must agree, that when you construct a DateTime object with "hours: 10" you would expect to see 10:00 when printing it out?

I'm probably missing something obvious, but is there a reason why we can't use `new Date().getTimezoneOffset()` to fix whatever's going on here?

**Comment by longlho** [comment]
Unfortunately no. There are a lot of timezones that have the same offset.

**Comment by longlho** [comment]
See https://formatjs.io/docs/polyfills/intl-datetimeformat#default-timezone for more info as well.
