### ISSUE TITLE
Intl.DateTimeFormat polyfill doesn't support Etc/GMT[+-]{offset} timezones

### ISSUE THREAD

**Issue by kevindetry** [formatjs/formatjs#2609]
## Which package?
@formatjs/intl-datetimeformat

## Describe the bug
Intl.DateTimeFormat polyfill throws an `Invalid timeZoneName` error if the timezone is set to `Etc/GMT+0` (or any other `Etc/GMT[+-]{offset}`).

### Codesandbox URL

https://codesandbox.io/s/wizardly-jones-x9g8s (formatting is broken and error is displayed in console)

## Expected behavior
`Etc/GMT[+-]{offset}` timezones should be supported since they're part of tzdata.

## Additional context
[This change in `luxon` library](https://github.com/moment/luxon/commit/ff17eeac8081753c5a2629a17c3fce6d622d88b3#diff-572c92ef1c461030cf7e47772319dd3db1ec2b880dadca7f88a3d9cee8e22ca3) revealed the issue. There's also a link to the Chrome issue tracker, where they've discussed those timezones.

**Comment by longlho** [comment]
Etc/GMT+0 and such are not valid iana timezone names afaik

**Comment by kevindetry** [comment]
They seem to be valid:
```
$ curl -O https://data.iana.org/time-zones/releases/tzdb-2021a.tar.lz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  481k  100  481k    0     0   633k      0 --:--:-- --:--:-- --:--:--  632k
$ tar xf tzdb-2021a.tar.lz
$ cd tzdb-2021a/
$ make zonenames | grep Etc/GMT
Etc/GMT
Etc/GMT-0
Etc/GMT+0
Etc/GMT0
Etc/GMT-14
Etc/GMT-13
Etc/GMT-12
Etc/GMT-11
Etc/GMT-10
Etc/GMT-9
Etc/GMT-8
Etc/GMT-7
Etc/GMT-6
Etc/GMT-5
Etc/GMT-4
Etc/GMT-3
Etc/GMT-2
Etc/GMT-1
Etc/GMT+1
Etc/GMT+2
Etc/GMT+3
Etc/GMT+4
Etc/GMT+5
Etc/GMT+6
Etc/GMT+7
Etc/GMT+8
Etc/GMT+9
Etc/GMT+10
Etc/GMT+11
Etc/GMT+12
```

**Comment by longlho** [comment]
Hmm you're right we'll take a look

**Comment by gigobyte** [comment]
@longlho `Etc/GMT+0` is not included in the fix even though it's part of the timezone database. Can this be fixed?
