### ISSUE TITLE
ts-transformer not working with ts-loader to generate IDs

### ISSUE THREAD

**Issue by psalv** [formatjs/formatjs#2614]
## Which package?

ts-transformer

## Describe the bug

I have followed the steps in the docs to use ts-transformer in my typescript-react project however when I check the compiled code there are no generated IDs for the `FormattedMessage` components and the descriptions are still present (which indicates to me that the transformer is not being run at all).

### Reproducible Steps/Repo

```
const FormatJsPlugin = require("@formatjs/ts-transformer");

...

{
  // ... other configs
  module: {
    strictExportPresence: true,

    rules: [
      {
        oneOf: [
          {
            test: /\.tsx?$/,
            loaders: [
              {
                loader: "babel-loader",
                options: {
                  cacheDirectory: true,
                },
              },
              {
                loader: "ts-loader",
                options: {
                  transpileOnly: true,
                  getCustomTransformers: {
                    before: [
                      FormatJsPlugin.transform({
                        overrideIdFn: "[sha512:contenthash:base64:6]",
                        ast: true,
                      }),
                    ],
                  },
                },
              },
            ],
          },
          
          // ... other file type loaders (including JS)
        ],
      },
    ],
  },
}
```

I have tested this with the latest version of ts-loader, webpack, and typescript (although my project is currently on typescript v3.9.7, will upgrade if necessary).

This behavior is observed with and without the babel-loader, and I have attempted to combine `babel-plugin-formatjs` with `ts-transformer` without any luck.

## Expected behavior

The ts-loader is sufficient to produce output with ID's

## Additional context

I can get this to work in the following scenarios but not with the ts-loader method described in the documentation:

1. Just using the babel-plugin and removing ts-loader altogether (this is not ideal for my set up)
2. Adding ttypescript and following the ttypescript set up in the documentation, as long as I upgrade typescript to v4.x

**Comment by longlho** [comment]
Do you have a minimal repro setup repo? ts-transformer requires TS4

**Comment by psalv** [comment]
Thanks for the reply and sorry for the delay @longlho, I have an example repo set up here: https://github.com/psalv/formatjs-ts-transformer-example/tree/ts-transformer-ts-loader

I've gotten around this issue by using ttypescript instead, however am running into another issue where ttypescript is not generating ID's for `FormattedMessage` components that have curly braces around the `defaultMessage` prop. I wanted to send this repo over to you first before creating a ticket in case there is something obvious I'm missing that could be linking these two issues.

**Comment by longlho** [comment]
Yeah the config isn't correct. `getCustomTransformers` is a function instead of an object. See https://formatjs.io/docs/tooling/ts-transformer#via-ts-loader for example.

For `<FormattedMessage defaultMessage={"FOO_MESSAGE with braces"} />` yeah we're not supporting it rn bc it's pretty edge, for string literal mostly it's just `<FormattedMessage defaultMessage="FOO_MESSAGE with braces" />`. What's your use case for declaring it this way?

**Comment by longlho** [comment]
ok realized we had a bad example in the getting-started section so I fixed that.

**Comment by psalv** [comment]
Ah! Thank you for updating + your response, it looks like that's working now for the non-curly braces case.

The curly braces issues is coming up due to some edge cases with eslint, ideally I would lint against curly braces and not have this as an issue since they're auto-fixable but there are some edge cases when eslint can't do this:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md#edge-cases

I'm surprised this isn't covered though, it looked like you had a test case for this (https://github.com/formatjs/formatjs/blob/main/packages/ts-transformer/tests/fixtures/FormattedMessage.tsx), which is why I thought there was something else at play.

**Comment by psalv** [comment]
Ah I now see that case is different since it is a template string (which is working)

**Comment by longlho** [comment]
Yeah template string is bc of line break support. Regular string literal shouldn't be wrapped w/ curly braces IMO. Well since we can't inject ID to those it'll crash your tests so make sure to write tests :)

**Comment by psalv** [comment]
Got it, and I agree. Thanks for your help!
