### ISSUE TITLE
injectIntl doesn't work with class components

### ISSUE THREAD

**Issue by mdesantis** [formatjs/formatjs#2617]
## Which package?
react-intl 5.12.3

## Describe the bug
I have two class components, Parent and Child. In the parent I have the `<IntlProvider>` wrap, and I'm trying to wrap Child within `injectIntl` in order to access to `this.props.intl`, but without success. I get the following error:

```
[React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
```

### Codesandbox URL
https://codesandbox.io/s/keen-wildflower-fub3m?file=/src/App.js

### Reproducible Steps/Repo

1. create a class component which wraps another class component with IntlProvider
2. wrap the other class component within injectIntl

## Expected behavior
I shouldn't get the error

## Additional context
Follows the App.js sample as it is in the CoddeSandbox link. I'ts concise so I guess it's a good idea to append straight here for reference

```jsx
import React, { Component } from "react";
import { IntlProvider, injectIntl } from "react-intl";

class Parent extends Component {
  render() {
    return (
      <IntlProvider locale="en" defaultLocale="en">
        {this.props.children}
      </IntlProvider>
    );
  }
}

class App extends Component {
  render() {
    return <Parent>Hello world!</Parent>;
  }
}

export default injectIntl(App);
```

**Comment by longlho** [comment]
`IntlProvider` in this case is a children of `App` so you'd have to move it to App's parent.

**Comment by mdesantis** [comment]
@longlho you're right, I didn't consider that the parent of App is not Parent, but RenderDOM. I have many things to learn about React :-) many thanks!
