### ISSUE TITLE
ts-transformer: move typescript & tslib to peerDependencies. ts-transformer must not install its own copy of typescript.

### ISSUE THREAD

**Issue by nodkz** [formatjs/formatjs#2620]
Pull Request with fix: https://github.com/formatjs/formatjs/pull/2621

## Which package?
@formatjs/ts-transformer

## Describe the bug

`ts-transform` may install its own typescript package version in its own node_modules. And project may use a different copy of typescript package. With such a case AST visitor stops to work.

https://github.com/formatjs/formatjs/blob/811de1798b451e8abd733149aed538c8063f0ca4/packages/ts-transformer/package.json#L19-L23

## To Reproduce

Install typescript 4.1.5 in any project as root dependency and ts-transform stops traversing children.

## Expected behavior
`typescript` should be in peerDependencies - root project should decide which version to install. And `ts-transform` MUST not install its own version.

## Additional context

If AST is created from one version of typescript then your visitor which is using another typescript will have different constants for the node kinds and types. They have the same names but in runtime have different instances/values.

**Comment by longlho** [comment]
I'm not sure i understand. We need TS4 so if your install 4.1.5 npm/yarn would not create 2 copies of TS.

**Comment by nodkz** [comment]
I'm using yarn with workspaces. And on top-level, I have`typescript` 4.1.5. But in workspace yarn install one more typescript copy in @formatjs/ts-transformer/node_modules with version 4.0.5 🤯 And I don't know why it happens. But according to package.json in ts-transformer it's allowable behavior. 

Anyway, it's quite strange to allow this (provide typescript in dependencies) because the transformer is used with an already installed typescript and it should not install its own copy of typescript.

Proposed solution with peerDependencies and devDependencies is widely used in graphql world. I have been using it for 3 years in [graphql-compose](https://github.com/graphql-compose/graphql-compose/blob/e8637117d162d94afd34a7d6ea186bffd0344d9a/package.json#L27-L52) and a myriad of similar tools do the same.

**Comment by longlho** [comment]
if that's the case I think you're having a bigger setup issue, because this doesn't just apply to us and potentially you can have multiple react versions and such. `yarn` is supposed to hoist common packages.

**Comment by nodkz** [comment]
Popular react component libraries use`peerDependencies` for `react` & `react-dom`:
- https://github.com/mui-org/material-ui/blob/next/packages/material-ui/package.json#L48-L49
- https://github.com/react-component/select/blob/master/package.json#L41-L44
- https://github.com/ant-design/ant-design/blob/master/package.json#L289-L292
- https://github.com/ReactTraining/react-router/blob/master/packages/react-router/package.json#L35-L37

They do `peerDependencies` for the proper hoisting of common packages - in their case react. Developers who use these component libraries take control over react version in theirs application `package.json`. 

Developers which are using `ts-transformer` 100% will install their own `typescript` dependency on the top level and with `ttypescript` will call `ts-transformer` code. BUT according to the current package.json in `ts-transformer` it can have own `typescript` installation because it's a production dependency. This is incorrect. In 3rd party libraries `typescript` must be in `peerDependencies`.

If I provided a weak motivation and explanation, probably the following articles can help a little bit more
- https://classic.yarnpkg.com/blog/2018/04/18/dependencies-done-right/
- https://thabo-ambrose.medium.com/peer-dependencies-npm-a0970f60481f

Thanks.
