### ISSUE TITLE
babel-plugin-formatjs and eslint-plugin-formatjs broken

### ISSUE THREAD

**Issue by 97carmine** [formatjs/formatjs#2623]
## Which package?
- babel-plugin-formatjs
- eslint-plugin-formatjs

## Describe the bug
I cannot use the packages listed in the previous point due to #2620

## To Reproduce

Install babel-plugin-formatjs and eslint-plugin-formatjs, Yarn shows:

```
➤ YN0002: │ babel-plugin-formatjs@npm:9.1.1 doesn't provide typescript (pbe039), requested by @formatjs/ts-transformer
➤ YN0002: │ eslint-plugin-formatjs@npm:2.12.2 [3786d] doesn't provide typescript (p094aa), requested by @formatjs/ts-transformer
```

And it gives an error when compiling with webpack

```
Error: @formatjs/ts-transformer tried to access typescript (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```

## Expected behavior
The packages should work correctly

**Comment by longlho** [comment]
ok reverting it and re-releasing
