### ISSUE TITLE
react Intl - How to return a plain translated string instead of return JSX Element(FormattedMessage).

### ISSUE THREAD

**Issue by yuteen-nikhare-ui** [formatjs/formatjs#2634]
We can use FormattedMessage to get component with translated text. Instead of getting component with translated text, I need a plain translated string.

I want something like this:

getTranslatedText(id: string): string {

 it will return a string instead of JSX (COMPONENT)

}

**Comment by longlho** [comment]
You can use [intl.formatMessage](https://formatjs.io/docs/react-intl/api#formatmessage) and the way you get a reference to the `intl` object is via [useIntl](https://formatjs.io/docs/react-intl/api#useintl-hook) or [injectIntl HOC](https://formatjs.io/docs/react-intl/api#injectintl-hoc).
