### ISSUE TITLE
Major: FormattedDate Displays Incorrect Time when TimeZone is specified (CodeSandbox Included)

### ISSUE THREAD

**Issue by JoeQuattrone** [formatjs/formatjs#2636]
## Which package?
react-intl 3.12.1 with pollyfills.

## Describe the bug
FormattedDate Displays Incorrect Time when the TimeZone is specified. It's doing the timezone offset based on your current timezone rather than what's specified.

It's aware of the specified timezone but the conversion formula is wrong. Here is an indicative picture of what's happening:
![image](https://user-images.githubusercontent.com/43793510/108893283-c2138b80-75c5-11eb-9845-eb4b256b2b3d.png)

E.g. 2021-02-23T03:43:30+05:00

### Important
set your timezone on your mac/pc to a different timezone than 'Amerca/Los_Angeles' and view the sandbox.

Switch your mac/pc timezone to 'America/New_York' and you will get the correct Date.

Refresh the code sandbox page upon timezone change to make sure your rendering the timezone specified by your computer.

### Codesandbox URL
https://codesandbox.io/s/unruffled-wescoff-i3dcn?file=/src/App.tsx

**Comment by longlho** [comment]
I think u'd have to set the default timezone: https://formatjs.io/docs/polyfills/intl-datetimeformat#default-timezone

**Comment by longlho** [comment]
Looking at the codesandbox, `new Date(0).getMilliseconds().toString()` is tz sensitive so it's affected by your browser setting. Change to `value={0}` fixes it. You're relying on native Date to parse the time string and that's always subject to your browser setting's timezone, which in this case is being double tz-converted. You should always use UTC milliseconds.

**Comment by JoeQuattrone** [comment]
@longlho it's set with line 23:
```
if ("__setDefaultTimeZone" in Intl.DateTimeFormat) {
  const d = Intl.DateTimeFormat as any;
  d.__setDefaultTimeZone("America/New_York");
}

**Comment by JoeQuattrone** [comment]
@longlho This is an example taken from a codebase that was using react-intl v2 . Since upgrading to react-intl v3 have I seen this problem. This must be a side effect of the upgrade that I would consider a bug because it was supported in a previous major version

**Comment by longlho** [comment]
I switched to react-intl@2 in the codesandbox and the result is the same.

**Comment by JoeQuattrone** [comment]
@longlho I was able to reproduce using react 16.9.0 and react-intl 2.4.0. I also tried react-intl 2.4.0 and react 17 but was not able to reproduce.

```
new Date(0).getMilliseconds().toString();

```
The Date API is not from react so idk why the implementation would change. Do you know why this happens?

sandbox:
https://codesandbox.io/s/unruffled-wescoff-i3dcn?file=/src/App.tsx:1151-1192

**Comment by longlho** [comment]
As I mentioned I don't recommend passing `string` in as Date value bc it's subject to native Date string parser and sensitive to timezone. I suspect you've had this bug for a while. You should pass in a timestamp in millis instead.

Here's to demo the issue:
```js
new Date('0') // Sat Jan 01 2000 00:00:00 GMT-0500 (Eastern Standard Time)
new Date(0) // Wed Dec 31 1969 19:00:00 GMT-0500 (Eastern Standard Time)
```

**Comment by JoeQuattrone** [comment]
I ended up configuring Jest to run in the same timezone for all tests. The dates in my tests became localized according to the timezone upon doing this upgrade. This broke all of my tests that instantiated datesIE `new Date()` I'm not sure why but the solution can be found here https://stackoverflow.com/questions/56261381/how-do-i-set-a-timezone-in-my-jest-config
