### ISSUE TITLE
Tooling for Vue templates

### ISSUE THREAD

**Issue by yrd** [formatjs/formatjs#2643]
## Which package?
`babel-plugin-formatjs`

## Describe the bug

When using `babel-plugin-formatjs` inside a Vue project, only messages which are rendered inside of the Typescript block (for example inside `setup`) are processed by the plugin. Messages which are rendered inside the template are not processed.

### Reproducible Steps/Repo

1. Create a new project with Vue CLI using Typescript and Babel
2. Add `vue-intl`, `babel-plugin-formatjs` dependencies
3. Create some messages without an ID
4. Add the babel plugin to as described in the documentation

See also: https://github.com/yaroedi/formatjs-repro

## Expected behavior

All messages should be given an automatically generated ID at compile time.

**Comment by longlho** [comment]
fixed in 7a3c33fb0b26124a218d15fad203c9d7cb331208

You can remove your `vue.config.js`, upgrade `babel-plugin-formatjs@9.2.0` & everything should work.
