### ISSUE TITLE
I don’t know why the new version reported an error

### ISSUE THREAD

**Issue by KingJeason** [formatjs/formatjs#2645]
## Which package?
intl-messageformat-parser  6.4.0

## Describe the bug

when i update version to  6.4.0, find this error. when i downgrade to 6.3.4, it's greet,Save the child~
[!] Error: '__spreadArray' is not exported by tslib.js, imported by ../../node_modules/intl-messageformat-parser/lib/src/normalize.js

**Comment by maurelio1234** [comment]
I have the same problem with `react-intl`.

I updated from `5.12.5 -> 5.13.0`.

```    TypeError: tslib_1.__spreadArray is not a function```

**Comment by eltiodelsofa** [comment]
> I have the same problem with `react-intl`.
> 
> I updated from `5.12.5 -> 5.13.0`.
> 
> ` TypeError: tslib_1.__spreadArray is not a function`

I fixed the same problem installing tslib

**Comment by klarstrup** [comment]
It's because they forgot to upgrade the `tslib` dependency when they use the new 2.1.0 `__spreadArray` helper

**Comment by longlho** [comment]
Sorry for the breakage we're publishing new versions w/ the fix

**Comment by joetidee** [comment]
I just installed `react-intl` 5.13.1 and received this error:
```
WARNING in ./node_modules/intl-messageformat/lib/src/core.js 103:57-70
"export '__spreadArray' was not found in 'tslib'
 @ ./node_modules/intl-messageformat/lib/index.js
 @ ./node_modules/react-intl/lib/src/components/provider.js
 @ ./node_modules/react-intl/lib/index.js
 @ ./src/components/error-404.jsx
 @ ./src/routes.js
 @ ./src/app.js
 @ multi ./src/app.js
```

I ran `npm list @formatjs/intl-displaynames` and got this:

> └─┬ react-intl@5.13.1 invalid
>   ├── @formatjs/intl-displaynames@4.0.9
>   └─┬ @formatjs/intl@1.8.1
>     └── @formatjs/intl-displaynames@4.0.9 de

**Comment by longlho** [comment]
Can you do npm ls tslib

**Comment by joetidee** [comment]
```
├─┬ @sentry/browser@5.24.2
│ ├─┬ @sentry/core@5.24.2
│ │ ├─┬ @sentry/hub@5.24.2
│ │ │ └── tslib@1.13.0 deduped
│ │ ├─┬ @sentry/minimal@5.24.2
│ │ │ └── tslib@1.13.0 deduped
│ │ └── tslib@1.13.0 deduped
│ ├─┬ @sentry/utils@5.24.2
│ │ └── tslib@1.13.0 deduped
│ └── tslib@1.13.0
├─┬ cypress@6.4.0
│ └─┬ listr@0.14.3
│   └─┬ rxjs@6.6.3
│     └── tslib@1.13.0 deduped
├─┬ react-intl@5.13.1
│ ├─┬ @formatjs/ecma402-abstract@1.6.1
│ │ └── tslib@2.1.0
│ ├─┬ @formatjs/intl-displaynames@4.0.9
│ │ └── tslib@2.1.0
│ ├─┬ @formatjs/intl-listformat@5.0.9
│ │ └── tslib@2.1.0
│ ├─┬ @formatjs/intl-relativetimeformat@8.1.1
│ │ └── tslib@2.1.0
│ ├─┬ @formatjs/intl@1.8.1
│ │ ├─┬ @formatjs/intl-datetimeformat@3.2.11
│ │ │ └── tslib@2.1.0
│ │ ├─┬ intl-messageformat-parser@6.4.1
│ │ │ └── tslib@2.1.0 deduped
│ │ └── tslib@2.1.0
│ ├─┬ intl-messageformat-parser@6.4.1
│ │ └── tslib@2.1.0 deduped
│ ├─┬ intl-messageformat@9.5.1
│ │ ├─┬ intl-messageformat-parser@6.4.1
│ │ │ └── tslib@2.1.0 deduped
│ │ └── tslib@2.1.0
│ └── tslib@2.1.0
├─┬ tidee-life-ui@1.0.0 -> /Users/joe/Sources/tidee-life/packages/tidee-life-ui
│ └─┬ webpack@4.44.2
│   └─┬ chrome-trace-event@1.0.2
│     └── tslib@1.13.0
└─┬ webpack@4.44.2
  └─┬ chrome-trace-event@1.0.2
    └── tslib@1.13.0 deduped
```

**Comment by longlho** [comment]
Looks like you have both tslib@1 & 2 so you'd have to resolve it to 2

**Comment by joetidee** [comment]
Is this a case of casing down the other package owners and getting them to upgrade their version of tslib to v2?

**Comment by longlho** [comment]
Do you have a repro repo?

**Comment by joetidee** [comment]
I do not. I reverted back to v3 to make do.

**Comment by joetidee** [comment]
Installed tslib 2.10 - fixed.
