### ISSUE TITLE
Can I use conditions inside a message text?

### ISSUE THREAD

**Issue by Litvinov1618** [formatjs/formatjs#2652]
I have a situation where the text of the message depends on some conditions, for example:

const text = "You're";

if (authorized) {
    text += 'welcome';
}
else {
    text += 'need to authorize';
}

Can I use condition for messages, like that:

intl.formatMessage(helloMessage, {authorized: true});

{
    "helloMessage": "You're {authorized ? 'welcome' : 'need to authorize'}"
}

**Comment by longlho** [comment]
Nope messages have to be string literals you cannot use concat because different language have different grammar/ordering

**Comment by Litvinov1618** [comment]
Can I use some kind of conditional translation? Like the plural forms, but with Boolean values instead of numbers

**Comment by longlho** [comment]
You can use "select" but i only recommend it for gender pronouns not generic switch logic.
