### ISSUE TITLE
Some code patterns lead to build errors using babel-plugin-formatjs

### ISSUE THREAD

**Issue by jddxf** [formatjs/formatjs#2663]
`babel-plugin-formatjs` throws the "Duplicate message id..." error on build when there're specific code patterns.

```
import { useIntl } from 'react-intl';

function test() {
  const intl = useIntl();

  // Uncomment either of the following 'error' functions and run `npm run build` to see errors.

  // async function error1() {
  //   await intl.formatMessage({ defaultMessage: 'foo', description: 'foo' });
  // }
  async function ok1() {
    const message = intl.formatMessage({
      defaultMessage: 'foo',
      description: 'foo',
    });
    await message;
  }

  // async function error2() {
  //   return intl.formatMessage({ defaultMessage: 'foo', description: 'foo' });
  // }
  async function ok2() {
    const message = intl.formatMessage({
      defaultMessage: 'foo',
      description: 'foo',
    });
    return message;
  }

  // async function error3() {
  //   await console.log(
  //     intl.formatMessage({ defaultMessage: 'foo', description: 'foo' })
  //   );
  // }
  async function ok3() {
    const result = console.log(
      intl.formatMessage({ defaultMessage: 'foo', description: 'foo' })
    );
    await result;
  }
}
```
Here's a [reproduction repo](https://github.com/jddxf/formatjs-issue-2663).

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
hmm I added the test and it seems ok so this might be something w/ create-react-app itself.

Making the fn non-`async` seems to fix it

**Comment by jddxf** [comment]
That makes sense. I should have reproduced it using bare babel. Thanks for your investigation!

**Comment by jddxf** [comment]
@longlho Reproduced the issue with babel only [here](https://github.com/jddxf/formatjs-issue-2663).

**Comment by longlho** [comment]
I opened an issue upstream at babel. For now I think the work around is to not formatMessage in async fn unfortunately, or turn off some settings like I did in the test

**Comment by longlho** [comment]
@jddxf 9.2.3 should have the fix for this

**Comment by jddxf** [comment]
Yes, it does.

**Comment by TikiTDO** [comment]
@longlho It seems that this fix introduced another bug.

Please see this stack trace:

```
SyntaxError: project/packages/react/src/components/app/CpNavHeader.tsx: NodePath has been removed so is read-only.
    at File.buildCodeFrameError (project/node_modules/@babel/core/lib/transformation/file/file.js:240:12)
    at NodePath.buildCodeFrameError (project/node_modules/@babel/traverse/lib/path/index.js:138:21)
    at NodePath._assertUnremoved (project/node_modules/@babel/traverse/lib/path/removal.js:75:16)
    at NodePath.insertBefore (project/node_modules/@babel/traverse/lib/path/modification.js:32:8)
    at PluginPass.visitor (project/node_modules/babel-plugin-formatjs/visitors/jsx-opening-element.js:81:32)
    at newFn (project/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (project/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (project/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (project/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (project/node_modules/@babel/traverse/lib/context.js:116:16)
```

At a glance the issue appears to stem from the fact that [this line](https://github.com/formatjs/formatjs/blob/51b88f1c5fcf89cf2eb274e1977e27888b0cd099/packages/babel-plugin-formatjs/visitors/jsx-opening-element.ts#L129) is doing an `insertBefore`, which is called after [this line](https://github.com/formatjs/formatjs/blob/51b88f1c5fcf89cf2eb274e1977e27888b0cd099/packages/babel-plugin-formatjs/visitors/jsx-opening-element.ts#L109) which removes the element that `insertBefore` is getting called on.

In the previous version of this lib the `insertBefore` was called [before](https://github.com/formatjs/formatjs/blob/6de2d5846bc6f82a11b7b130c3a2c414a5102549/packages/babel-plugin-formatjs/index.ts#L510) the [remove](https://github.com/formatjs/formatjs/blob/6de2d5846bc6f82a11b7b130c3a2c414a5102549/packages/babel-plugin-formatjs/index.ts#L520).

**Comment by longlho** [comment]
@TikiTDO do you have a repro?

**Comment by TikiTDO** [comment]
@longlho Sorry no repro atm. I needed to resolve the issue to fix a broken build for a client as part of firefighting, and there's looks to be a few other issues that I need to look at before I can make a repro repo for this issue. For now we've worked around the issue by setting `removeDefaultMessage: false`.

I should be able to make something in a day or two once I've finished helping roll out this release.

**Comment by longlho** [comment]
kk I've reopened this issue

**Comment by TikiTDO** [comment]
@longlho Repro'd here: https://github.com/TikiTDO/formatjs-issue-2663-part2

Just pull, `npm install` and `npm run build`

**Comment by shaibar** [comment]
@longlho  This issue reproduced on the latest version last working version for me 9.2.2

babel-plugin-formatjs@9.2.2

Code example: 
----------------
import { defineMessages } from 'react-intl';

const prefix = 'wg';
export default defineMessages({
  ARS: { id: `${prefix}.ARS`, defaultMessage: 'AR$ - Argentine Peso' },
  AUD: { id: `${prefix}.AUD`, defaultMessage: 'AUD - Australian Dollar' },
  AZN: { id: `${prefix}.AZN`, defaultMessage: 'AZN - Azerbaijani New Manats' },
  BHD: { id: `${prefix}.BHD`, defaultMessage: 'BHD - Bahrain Dinar' },
  BRL: { id: `${prefix}.BRL`, defaultMessage: 'R$ - Brazilian Real' },
  BGN: { id: `${prefix}.BGN`, defaultMessage: 'BGN - Bulgarian Lev' },
  CAD: { id: `${prefix}.CAD`, defaultMessage: 'CAD - Canadian Dollar' },
})


using the
const {transform} = require('@babel/core');

plugins.push('formatjs')

const result = transformFileSync('mystringsfuile.js', {
    presets,
    plugins,
});
// result.metadata = {}

**Comment by longlho** [comment]
Do you have the err log?

**Comment by shaibar** [comment]
@longlho  Where should i find it ?

**Comment by longlho** [comment]
oh are you using `babel-plugin-formatjs` to extract message? please use `@formatjs/cli` instead. We not longer support extraction in `babel-plugin-formatjs`

**Comment by sergeushenecz** [comment]
I have same issue after 9.2.2 version. could we use api from @formatjs/cli in node? @longlho

**Comment by longlho** [comment]
Yeah I believe that's preferred

**Comment by sergeushenecz** [comment]
@longlho  Could you write example how i can extract messages from cli in the node ?
