### ISSUE TITLE
Struggling to upgrade to v3

### ISSUE THREAD

**Issue by joetidee** [formatjs/formatjs#2670]
## Which package?
react-intl 3.12.1

## Describe the bug
I have followed the migration guide in the docs to the letter. However, I am getting the following 3 console errors...

![Screen Shot 2021-03-06 at 02 08 03](https://user-images.githubusercontent.com/8842431/110191557-f0446700-7e20-11eb-83b0-5ba29cc8c649.png)

... for every message that I am using on the page that is being rendered. At the component level, the message is being used like this:

```
...
import messages from '../../messages';

class LoginPage extends Component {
    constructor(props) {
    ...
    this.messages = {
            'account.activation.error.expired': intl.formatMessage(messages['account.activation.error.expired']),
    }
    ...
}

```

The message file is like this:

```
import { defineMessages } from 'react-intl';

const messages = defineMessages({
    'account.activation.error.expired': {
        id: 'account.activation.error.expired',
        defaultMessage: 'This account requires activating.',
    },
    ...
});
```

Apologies if I am missing something obvious here and happy to update the migration docs if we can resolve this.

## To Reproduce
Unfortunately, this is a fully-fledged application, so not possible to provide a link to a repo.

## Desktop (please complete the following information):

- OS: Mac
- Browser: Chrome
- Version: 88

**Comment by longlho** [comment]
what's the `messages` u pass into the `IntlProvider`?

**Comment by joetidee** [comment]
{
  "account.activation.error": "This activation link is not valid.",
  "account.activation.error.expired": "This account requires activating.",
  "account.activation.error.link.expired": "This activation link has expired."
}

**Comment by longlho** [comment]
It's hard to debug without repro repo of some sort. We're also on v5 I believe

**Comment by lauralouiset** [comment]
How are you compiling the strings and injecting them into your app? I just upgraded a couple weeks ago and switched from the babel plugin to using a file compiled with the formatjs-cli, which i'm passing in to the IntlProvider.

our compiled messages file looks like:
```
  "billing.renewalDate": [
    {
      "type": 0,
      "value": "Renewal Date:"
    }
  ],
  "billing.select": [
    {
      "type": 0,
      "value": "Select"
    }
  ],
```
