### ISSUE TITLE
Intl-NumberFormat is inconsistent from "en-CA" locale Safari to other browsers

### ISSUE THREAD

**Issue by SheaBelsky** [formatjs/formatjs#2674]
## Which package?
https://github.com/formatjs/formatjs/tree/main/packages/intl-numberformat

## Describe the bug
`Intl.NumberFormat` does not have consistent behavior in Canada and on Safari browsers.

The below code will output `$419.99` in Chrome, but produces `CA$419.99` in Safari.

```
Intl.NumberFormat("en-CA", {
    style: "currency",
    currency: "CAD"
}).format(419.99)
```

### Codesandbox URL

https://codesandbox.io/s/focused-leftpad-ib7j2?file=/src/index.js

### Reproducible Steps/Repo

1. Open the above CodeSandbox in Chrome
2. Observe that the price in the browser preview is `$419.99`
3. Open the above CodeSandbox in Safari
4. Observe that the price in the browser preview is `CA$419.99`
5. Comment-out the `intl-numberformat` polyfills from lines 25-29
6. Observe that the price in the browser preview is `$419.99`

## Expected behavior
I would expect that the behavior of the polyfill is the same across browsers: `Intl.NumberFormat` should always return either `$419.99` OR `CA$419.99`, no matter what the browser is.

## Desktop (please complete the following information):

- OS: macOS
- Browser: Safari
- Version: 13.1, 12.1, 11.1 (tested on Browser Stack)

**Comment by longlho** [comment]
That's because you're importing `@formatjs/intl-numberformat/locale-data/en` which is `en-US`. You have to import `@formatjs/intl-numberformat/locale-data/en-CA` instead. See https://unpkg.com/browse/@formatjs/intl-numberformat@6.2.2/locale-data/ for the list of locales

**Comment by SheaBelsky** [comment]
@longlho That did the trick! I'll work my team to resolve this issue. Thank you so much!

**Comment by SheaBelsky** [comment]
@longlho Hey there, I'm still running into issues with this.

These are the polyfills that we have:

```
require('@formatjs/intl-numberformat/polyfill');
require('@formatjs/intl-numberformat/locale-data/en');
require('@formatjs/intl-numberformat/locale-data/en-CA');
require('@formatjs/intl-numberformat/locale-data/pl');
require('@formatjs/intl-numberformat/locale-data/de');
require('@formatjs/intl-numberformat/locale-data/fr');
require('@formatjs/intl-numberformat/locale-data/fr-CA');
```

With these polyfills in place, some devices are formatting the same kind of price incorrectly.

```
Intl.NumberFormat('fr-CA',
{style: 'currency', currency: 'CAD'}
).format(419.99)
```

On Samsung Galaxy S20 devices on Browserstack, this is outputting `CA$419.99`. Are there further adjustments to our setup that are necessary?

**Comment by longlho** [comment]
Do you have a codesandbox?

**Comment by SheaBelsky** [comment]
https://codesandbox.io/s/focused-leftpad-ib7j2?file=/src/index.js

**Comment by SheaBelsky** [comment]
<img width="292" alt="Screen Shot 2021-03-09 at 3 28 18 PM" src="https://user-images.githubusercontent.com/15164473/110533553-194c4c80-80ec-11eb-8780-47ae5725bf99.png">

![Screen Shot 2021-03-09 at 3 28 50 PM](https://user-images.githubusercontent.com/15164473/110533612-29fcc280-80ec-11eb-9d2a-6584d800e23b.png)


Here's a screenshot of how it looks from Browserstack Chrome Samsung Galaxy S20 (1) and CodeSandbox on macOS Chrome (2)

**Comment by SheaBelsky** [comment]
<img width="323" alt="Screen Shot 2021-03-09 at 3 34 32 PM" src="https://user-images.githubusercontent.com/15164473/110534348-f66e6800-80ec-11eb-8d4e-8cab878374ce.png">

This is Browserstack Firefox Samsung Galaxy S20, it looks OK. For what it's worth, I could not produce the bug on a physical Google Pixel 4A, Samsung Galaxy S4, LG G3, or iPhone SE. Those devices look as expected.

**Comment by SheaBelsky** [comment]
Anecdote: BrowserStack on a Pixel 4A has the bug, even though my physical Pixel 4A is fine. so I’m thinking there’s an issue with BrowserStack and not with our devices. If you can't reproduce this with a Galaxy S20, I can close this issue, since it's unlikely it would be related to this library, and is something upstream with Browserstack.

**Comment by longlho** [comment]
So we don't apply the polyfill unless platform doesn't have the capabilities and/or there's a bug in the native impl. This might be the latter. See https://github.com/formatjs/formatjs/blob/main/packages/intl-numberformat/should-polyfill.ts and maybe try the native impl on that browser.

If that platform is buggy we can update the should-polyfill logic to account for that. Any more versioning details would be great.
