### ISSUE TITLE
How to remove unused meesage from defineMessages

### ISSUE THREAD

**Issue by teliu-ez** [formatjs/formatjs#2684]
Hi:
     My messages is getting larger and larger which contains many unused messages. Could you share how to detect these meesges and remove them. There are more than 3000 items.

**Comment by longlho** [comment]
This is why we generally recommend [declaring those messages inline](https://formatjs.io/docs/getting-started/message-declaration) so they are self-managed. In your scenario you're effectively looking for dead code removal which is not really in our scope.
