### ISSUE TITLE
Can I use intl.formatMessage without an id or build steps?

### ISSUE THREAD

**Issue by TimDaub** [formatjs/formatjs#2694]
Hey,

I'm trying to use `@format/intl` without an explicit id like this `intl.formatMessage("hello")`.
But, when I do `formatjs extract "src/js/components/Nav.js" --out-file src/js/locales/raw/en-US/messages.json`, my `messages.json` file is empty. I [asked in another thread](https://github.com/formatjs/formatjs/issues/2169#issuecomment-796875203) if `intl.formatMessage` is detected and a maintainer confirmed it to me. I use parcel, but I haven't set it up to do anything.

What am I doing wrong?

**Comment by longlho** [comment]
the method signature is not correct, you have to do
```ts
intl.formatMessage({
	defaultMessage: 'hello',
	description: 'foo' // optional
})
```

**Comment by TimDaub** [comment]
Thanks
