### ISSUE TITLE
What to substitute now that intlShape is no longer available?

### ISSUE THREAD

**Issue by joetidee** [formatjs/formatjs#2695]
If we previously used:

`intl: PropTypes.intlShape.isRequired,`

what do we use going forward?

**Comment by longlho** [comment]
Take a look at our upgrade guides: https://formatjs.io/docs/react-intl/upgrade-guide-3x#typescript-support

**Comment by joetidee** [comment]
Okay, so we do `import {IntlShape} from 'react-intl'` and find some sort of TypeScript-to-proptypes conversion packages?

When console logging the above `IntlShape`, I get `undefined` - says the element is not accessible.

**Comment by longlho** [comment]
IntlShape is an interface used for typechecking only so it's not a JS object. There's no proptypes replacement. I recommend you just use TypeScript

**Comment by joetidee** [comment]
Isn't Typescript (build time) and proptype (run time) used for different purposes? We use proptype fr run-time checking o async data.

**Comment by longlho** [comment]
IntlShape is a static immutable object so typechecking should be sufficient. We don't support proptypes anymore.

**Comment by joetidee** [comment]
So, when we use `intl` in a component and it complains that we haven't defined it in our `propTypes` object, what do we use:
```
intl: PropTypes.any.isRequired,
```

?

**Comment by longlho** [comment]
I don't know tbh I haven't used proptypes for a while. If that silences your warning then yeah

**Comment by joetidee** [comment]
Not really, because then we have an Eslint warning:
`ESLint: Prop type `any` is forbidden(react/forbid-prop-types`

**Comment by longlho** [comment]
U can disable that warning for that line
