### ISSUE TITLE
esbuild plugin [feature-request]

### ISSUE THREAD

**Issue by AlessandroAnnini** [formatjs/formatjs#2715]
Hi,
do you plan to develop a [plugin for esbuild](https://esbuild.github.io/plugins/)?
It should replace [babel-plugin-formatjs](https://www.npmjs.com/package/babel-plugin-formatjs)

Thanks

**Comment by longlho** [comment]
Yes I was just thinking about that

**Comment by longlho** [comment]
ok unfortunately there's no AST-based plugin API yet and pulling in our own parser would slow down esbuild significantly. See https://github.com/evanw/esbuild/issues/111#issuecomment-767482738 for discussion
