### ISSUE TITLE
The polyfill on Safari 13 breaks the execution

### ISSUE THREAD

**Issue by kud** [formatjs/formatjs#2726]
## Which package?

```js
import { IntlProvider } from "react-intl"
import "@formatjs/intl-pluralrules/polyfill"
import "@formatjs/intl-relativetimeformat/polyfill"
```

```
"dependencies": {
    "@formatjs/intl-pluralrules": "4.0.12",
    "@formatjs/intl-relativetimeformat": "8.1.3",
    "react-intl": "5.13.4",
  }
```

## Describe the bug
When you don't add the polyfill, it works on Safari 13. When you add it, you've got:

```
[Error] TypeError: undefined is not a constructor (evaluating 'new Intl.Locale(_)')
```

## Desktop:

- OS: Catalina
- Browser: Safari
- Version:  13.1

**Comment by longlho** [comment]
You need @formatjs/intl-locale polyfill before them: https://formatjs.io/docs/polyfills/intl-relativetimeformat#requirements

**Comment by kud** [comment]
Thank you :)
