### ISSUE TITLE
@formatjs/cli is unable to extract messages declared in different files in a project

### ISSUE THREAD

**Issue by vinaysharma14** [formatjs/formatjs#2733]
## Which package?
@formatjs/cli

## Describe the bug
**@formatjs/cli** is unable to extract messages declared in different files in a project.

### MCVE URL

https://github.com/vinaysharma14/format-js-mcve/

### Reproducible Steps/Repo

1. Clone the above project.
2. Install dependencies with `npm i` command.
3. Run `npm run extract-messages` command.
4. Check the locale JSON in `src/locales/temp.json`.

## Expected behavior

The generated locale JSON should have messages declared in all three `messages.ts` files.

## Desktop

- OS: macOS Catalina
- Browser: Chrome
- Version: 10.15.7 (19H524)

## Smartphone

Not applicable

**Comment by longlho** [comment]
Please quote your glob in the extract cmd

**Comment by vinaysharma14** [comment]
@longlho how silly of me, thanks!
