### ISSUE TITLE
Make `location` optional in faster-messageformat-parser

### ISSUE THREAD

**Issue by longlho** [formatjs/formatjs#2735]
`location` is useful in debugging but for prod build we definitely don't want to include that in the AST. Since this module is potentially used during runtime, let's have that option.

**Comment by pyrocat101** [comment]
This can be done as in the post-processing step in `intl-messageformat`. I don't want to do it in the parser as it will liter the code with a lot of conditional logics, which degrades readability.

**Comment by longlho** [comment]
fixed in latest
