### ISSUE TITLE
pseudo-locale compile does not pseudo-localize text inside of rich text

### ISSUE THREAD

**Issue by heath-freenome** [formatjs/formatjs#2744]
## Which package?
`@formatjs/cli`

## Describe the bug
When I use the following command on text that is wrapped with rich text, that text is not pseudo-localized

```
formatjs compile lang/en.json --ast --pseudo-locale en-XA --out-file compiled-lang/en-XA.json
```

### Reproducible Steps/Repo

Using the `lang/en.json` file that contains the following:
```
{
  "H3AE6j": {
    "defaultMessage": "Copy",
  },
  "IeHQVT": {
    "defaultMessage": "<bold>Error:</bold> {message}",
  }
}
```

1. Run the `formatjs compile lang/en.json --ast --pseudo-locale en-XA --out-file compiled-lang/en-XA.json` command
2. View the resulting pseudo-localized output file which looks like:

```
{
  "H3AE6j": [
    {
      "type": 0,
      "value": "Ḉŏṗẏ"
    }
  ],
  "IeHQVT": [
    {
      "children": [
        {
          "type": 0,
          "value": "Error:"
        }
      ],
      "type": 8,
      "value": "bold"
    },
    {
      "type": 0,
      "value": " "
    },
    {
      "type": 1,
      "value": "message"
    }
  ]
}
```

## Expected behavior

I expect the translated file to look like:
```
{
  "H3AE6j": [
    {
      "type": 0,
      "value": "Ḉŏṗẏ"
    }
  ],
  "IeHQVT": [
    {
      "children": [
        {
          "type": 0,
          "value": "Ḕŕŕŏŕ:"
        }
      ],
      "type": 8,
      "value": "bold"
    },
    {
      "type": 0,
      "value": " "
    },
    {
      "type": 1,
      "value": "message"
    }
  ]
}
```
## Desktop (please complete the following information):

- OS: iOS
- Browser N/A
- Version N/A

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by heath-freenome** [comment]
Wow, so fast! Thank you!
