### ISSUE TITLE
Node.js usage

### ISSUE THREAD

**Issue by alex-mironov** [formatjs/formatjs#2747]
Not really a bug, just wondering how to use it with node.js. Unfortunately I didn't find any guide or API reference. Basically, I'd like to have the possibility to translate different sms/email messages in node.js before sending them. Is it a valid use case for this library.

**Comment by longlho** [comment]
https://formatjs.io/docs/getting-started/installation#minimal-application there's a Node tab that should help you get started

**Comment by ybelenko** [comment]
Is it possible to use it without compilers?(webpack, rollup etc.) In vanilla node.js I got error:
```console
file:///Library/WebServer/Documents/www/notifier/src/modules/getIntl.mjs:1
import {createIntl, createIntlCache} from '@formatjs/intl'
        ^^^^^^^^^^
SyntaxError: The requested module '@formatjs/intl' does not provide an export named 'createIntl'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```
while my import copied from manual:
```js
import {createIntl, createIntlCache} from '@formatjs/intl';

// This is optional but highly recommended
// since it prevents memory leak
const cache = createIntlCache()

export default () => {
  return createIntl(
    {
      locale: 'ru-RU',
      messages: {},
    },
    cache
  );
};

```

**Comment by ybelenko** [comment]
Works only via CommonJs import in my build without transpilers:
```js
const {createIntl, createIntlCache} = require('@formatjs/intl');
// works with vanilla Node.js
```
