### ISSUE TITLE
Having `.` in variable key throws parser error

### ISSUE THREAD

**Issue by jeggy** [formatjs/formatjs#2749]
## Which package?
I'm not sure which package this would be considered as. But I'm using the `react-intl` package.

## Describe the bug
Whenever I have a plural variable key that contains a `.` in it. It fails to display the text and I get this error in my chrome console log:
```
Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting message: "Text.MyResource", using id as fallback. 
Locale: en
MessageID: Text.MyResource
Default Message: undefined
Description: undefined 
Expected "," but "." found.
```
## To Reproduce
https://codesandbox.io/s/priceless-meadow-zyhfr?file=/src/App.js

## Expected behavior
I would expect both labels to show the same results

## Screenshots
![image](https://user-images.githubusercontent.com/51459/112523459-afdc6700-8d96-11eb-878b-71dd8c7e21cf.png)
![image](https://user-images.githubusercontent.com/51459/112523727-f6ca5c80-8d96-11eb-8f47-ea264c267a79.png)

**Comment by longlho** [comment]
Variable names cannot contain . per ICU spec
