### ISSUE TITLE
Change default idInterpolationPattern to as it’s prone to collisions for medium sized apps

### ISSUE THREAD

**Issue by lensbart** [formatjs/formatjs#2750]
Hello!

Thanks for this software. It works well.

For `formatjs extract` and `babel-plugin-formatjs`, de default value for `--id-interpolation-pattern` / `idInterpolationPattern` is `[contenthash:5]`, which has 16^5 = 1048576 possible values. Applying the [birthday problem](https://en.wikipedia.org/wiki/Birthday_problem), the probability that a medium-sized app with 500 strings has a collision, is [around 11%](https://www.wolframalpha.com/input/?i=1-%281048576%21%29%2F%28%281048576-500%29%21*+1048576+%5E500%29).

This just happened in my app, which has about 500 strings. I think it makes more sense to use `[sha512:contenthash:base64:6]` as a default value. This one has `68_719_476_736` possible values, a number too large for WolframAlpha to calculate the chance of collision.

**Comment by longlho** [comment]
yes I agree. This pattern was chosen as an example and kinda stuck around for historical reasons. Changing it would be a breaking change but we'll bump major. Ofc, PRs are always welcome as well 😄

**Comment by lensbart** [comment]
Done! 🚚

**Comment by longlho** [comment]
fixed in latest

**Comment by lensbart** [comment]
When I try to leave out `idInterpolationPattern` in my babel config, I get a warning that my app bundle doesn’t contain id’s (“Error: [@formatjs/intl] An `id` must be provided to format a message.”). Could it be that [this line](https://github.com/formatjs/formatjs/blob/d517b7beb9cc907e238615f1b12f2587a00b9623/packages/babel-plugin-formatjs/visitors/jsx-opening-element.ts#L105) is the culprit and `&& idInterpolationPattern` should be left out?

As far as I can tell, the desired behaviour for generating id’s should not depend on whether `idInterpolationPattern` is provided, because it has a default value (according to the docs). The only thing that should matter is if `id` is present, and if not, use `idInterpolationPattern`.

Also, because of the default value, the `&& idInterpolationPattern` check is redundant on [this line](https://github.com/formatjs/formatjs/blob/3f4c8c468d8c83efe00491704634c66321f57c8c/packages/babel-plugin-formatjs/utils.ts#L97), but doesn’t otherwise affect the code.

**Comment by lensbart** [comment]
See https://github.com/formatjs/formatjs/pull/2755

**Comment by longlho** [comment]
While this is something we'll fix, I don't recommend you relying on default value regardless. Hashing algo can change version-to-version.
