### ISSUE TITLE
Rendered FormattedMessage components are shown as Anonymous in react dev tools

### ISSUE THREAD

**Issue by heath-freenome** [formatjs/formatjs#2751]
## Which package?
`react-intl`

## Describe the bug
When I look in the react-dev tools at the component structure, I see that my `FormattedMessage` components say `Anonymous`

### Reproducible Steps/Repo

1. From any react app that uses `FormattedMessage` right click on the text provided by that component and select the `Inspect` choice.
2. Click on the React Dev-Tools `Components` tab
3. Observe that the name of the component containing the text says `Anonymous`

## Expected behavior
I would expect the component to have the name `FormattedMessage` not `Anonymous`

## Screenshots

<img width="1220" alt="Screen Shot 2021-03-25 at 1 06 27 PM" src="https://user-images.githubusercontent.com/51679588/112536621-f320e080-8d6a-11eb-8c3b-c4c394c21571.png">

NOTE: the `data-testid` is something we add to our components for testing purpose

## Desktop (please complete the following information):

- OS: MacOs
- Browser  chrome
- Version 89.0.4389.90

**Comment by heath-freenome** [comment]
I'm guessing it has something to do with using `React.createElement` in [message.tsx](https://github.com/formatjs/formatjs/blob/78d35580ccd31f143bc1f3884326ecfe234c6929/packages/react-intl/src/components/message.tsx#L61). Likely just adding a `.displayName = 'FormattedMessage'` to the returned component would fix it.

**Comment by heath-freenome** [comment]
Wow so fast, thanks!

**Comment by heath-freenome** [comment]
Oh no, the main thing about this change is that using the [react-display-name](https://www.npmjs.com/package/react-display-name) function on the imported `FormattedMessage` used to return `FormattedMessage`, but now it returns `Unknown`, so the fix isn't quite correct. It seems that it is necessary to set the `displayName` on the state functional component definition along with the resulting rendered component. And since we use the aforementioned function on `FormattedMessage` in our tests to make sure the shallow rendered component is as expected, this fix is causing them to break.

i.e. This is a simplified version of our test
```
import getDisplayName from 'react-display-name`;
import { FormattedMessage } from 'react-intl`;
...
it('rendered a FormattedMessage as a child', () => {
  expect(wrapper.name()).toEqual(getDisplayName(FormattedMessage));
})'
```

Do I need to file a new issue?

**Comment by heath-freenome** [comment]
See my comments in [613b746](https://github.com/formatjs/formatjs/commit/613b746e5194ae92d28310283c01815521fe4839)

**Comment by andykao1213** [comment]
I agree with the comments from @heath-freenome in 613b746. I have a test that uses the enzyme as below:
```js
wrapper.find("FormattedMessage")...
```
Now I can only query the component with the name `MemoizedFormattedMessage` instead of `FormattedMessage`, which looks unfriendly because we need to dig into the source code or devtools then realize we should use which component name.
