### ISSUE TITLE
Can't resolve '@formatjs/icu-messageformat-parser' error

### ISSUE THREAD

**Issue by thundermiracle** [formatjs/formatjs#2757]
## Which package?
`@formatjs/intl` & `intl-messageformat`

## Describe the bug
I'm using react-intl which throws `Can't resolve '@formatjs/icu-messageformat-parser' in '/Users/liufeng/Code/blog.thundermiracle.com/node_modules/intl-messageformat/lib/src'` error while compiliation.

## To Reproduce

Everyone try to use `@formatjs/intl` package will get this error as the package in import is not include in package.json.

Problem is here:
https://github.com/formatjs/formatjs/blob/main/packages/intl/src/message.ts#L13
https://github.com/formatjs/formatjs/blob/main/packages/intl/package.json#L37

Caused by this commit:
https://github.com/formatjs/formatjs/commit/4362bc5582876f37fdaffe97bc9d8fbb73d83c7a

## Screenshots

<img width="924" alt="スクリーンショット 2021-03-27 13 36 06" src="https://user-images.githubusercontent.com/25689126/112710023-68beb500-8f01-11eb-9863-4e576232d6b0.png">

**Comment by TrejGun** [comment]
same here

<img width="1354" alt="Screen Shot 2021-03-27 at 2 17 07 PM" src="https://user-images.githubusercontent.com/185285/112711965-50519900-8f07-11eb-93f7-2e61f910fc22.png">

**Comment by Foxhound401** [comment]
![image](https://user-images.githubusercontent.com/23480593/112719307-e2b76400-8f2a-11eb-8ef5-7501ca216430.png)
me too

**Comment by dalladirosa** [comment]
Does anyone know how to prevent this error before it's fixed?

**Comment by thundermiracle** [comment]
@dalladirosa Just avoid using the latest version will be the quickest fix.
Like I’m using react-intl@5.14.1 instead of latest 5.15.0

**Comment by dalladirosa** [comment]
> @dalladirosa Just avoid using the latest version will be the quickest fix.
> Like I’m using react-intl@5.14.1 instead of latest 5.15.0

@thundermiracle Thanks, I've already done that but the error still there it's weird

**Comment by longlho** [comment]
Thanks a lot for reporting! Latest version should have this fix for all the relevant packages. Sorry about that.
