### ISSUE TITLE
Wrong month name.

### ISSUE THREAD

**Issue by tomekowal** [formatjs/formatjs#2763]
## Which package?
intl-datetimeformat/polyfill

## Describe the bug
Date.toLocaleString returns "off by one month name". E.g.
```
new Date(2021, 1).toLocaleString('en-US', {month: "long"})
"January"
```
while it should return `"February"`.

### Codesandbox URL
https://codesandbox.io/s/pedantic-river-g46sr?file=/src/index.js

### Reproducible Steps/Repo

1. Check the codesandbox link. It displays the buggy version where month 1 is January.
2. Comment out line 2 `import "@formatjs/intl-datetimeformat/polyfill";` the month changes to correct one: February

## Expected behavior
Polyfill should not change transalation.

## Desktop (please complete the following information):

- OS: [Linux]
- Browser [firefox]
- Version [86.0 (64-bit)]

**Comment by longlho** [comment]
This might be because you didn't set timezone. Our default tz is utc

**Comment by JoeQuattrone** [comment]
@longlho This is similar to the issue I just reported and is certainly a defect. https://github.com/formatjs/formatjs/issues/2768

**Comment by longlho** [comment]
Did you set the timezone?

**Comment by JoeQuattrone** [comment]
Yes and it either errors out or renders the wrong month in Firefox https://codesandbox.io/s/blue-night-qvnnn?file=/src/App.tsx

**Comment by longlho** [comment]
Did you add tz data? https://formatjs.io/docs/polyfills/intl-datetimeformat#adding-iana-timezone-database

**Comment by JoeQuattrone** [comment]
I added it to the sandbox and it still doesn't work

**Comment by longlho** [comment]
Can you update your codesandbox and what result you expect?

**Comment by JoeQuattrone** [comment]
Sure thing, I updated the sandbox and attached screenshots to my issue https://github.com/formatjs/formatjs/issues/2768. Let me know if there's anything else.
