### ISSUE TITLE
@formatjs/intl-pluralrules/polyfill-locales file missing from 4.0.13

### ISSUE THREAD

**Issue by neil-morrison44** [formatjs/formatjs#2765]
## Which package?
@formatjs/intl-pluralrules

## Describe the bug

In v4.0.12 there's a `@formatjs/intl-pluralrules/polyfill-locales` file, in v4.0.13 there's not

## To Reproduce

Install v4.0.13, try to find `@formatjs/intl-pluralrules/polyfill-locales`

Can't spot any commit that seems related.
Could be that importing `@formatjs/intl-pluralrules/polyfill-locale` was never supported?

Feels like a breaking change if it's not accidental

**Comment by longlho** [comment]
It was never supported. We dist the file primarily for testing. I recommend you selectively load the proper locale-data since its size can grow over time (thus causing OOM if load everything)

**Comment by MrChocolatine** [comment]
Sorry to revive this issue you closed @longlho but I am confused.

Few months ago (https://github.com/formatjs/formatjs/issues/2235#issuecomment-715401046) you publicly recommend:

> u can `import @formatjs/intl-pluralrules/polyfill-locales`

But now you say

> It was never supported. We dist the file primarily for testing.

How? Why?

**Comment by longlho** [comment]
Sorry for the confusion. `never` was wrong. We did expose that file (though undocumented I believe) but recently with newer CLDR versions the data got larger so it's no longer efficient to bundle ALL locale data together (the set of locales also can change version to version) due to potential OOM, thus we effectively stopped doing so.

**Comment by MrChocolatine** [comment]
All right, thank you for giving more details.

**Comment by neil-morrison44** [comment]
Definitely sounds like this change should have been made within a breaking release (v5 I guess?) then (and replies to github issues do count as informal documentation)

**Comment by longlho** [comment]
Yup understood. Your feedback is definitely received.

**Comment by MrChocolatine** [comment]
> Definitely sounds like this change should have been made within a breaking release (v5 I guess?) then (and replies to github issues do count as informal documentation)

Can't agree more. With my colleagues we were struggling a little bit to find out why and how this undocumented change happened.

**Comment by MrChocolatine** [comment]
@longlho by any chance, considering the messages here, do you plan to rollback a version that includes the file `intl-pluralrules/polyfill-locales` (but also `intl-relativetimeformat/polyfill-locales`) and apply this change to the next major version?

**Comment by MrChocolatine** [comment]
Or any other change (recommendation in the README?) related to that.

**Comment by longlho** [comment]
I don't plan any rollback. If you do need that file you can always pin to the version that has it.

**Comment by neil-morrison44** [comment]
If more people were effected by this (and there doesn't seem to be, yet anyway) my suggestion would be to release a v4.0.14 with the (old) file reinstated alongside a `console.warn` deprecation notice then a v5.0.0 with the file removed
