### ISSUE TITLE
Intl.DateTimeFormat.formatDate() Is Wrong When Polyfill is Used 

### ISSUE THREAD

**Issue by JoeQuattrone** [formatjs/formatjs#2768]
## Which package?
react-intl 3.12 & @formatjs/intl-datetimeformat/polyfill;

## Describe the bug
The  @formatjs/intl-datetimeformat/polyfill package is causing  Intl.DateTimeFormat.formatDate()  to return an incorrect date formati in browsers that aren't chrome.

## To Reproduce
1. Open up the sandbox link in chrome and notice the format works as expected. Open up the same sandbox in Firefox and notice the date format is different from that of chrome.
2. Comment out the polyfill import and reload the page in Firefox. Notice the day format matches chrome and is correct.
### Codesandbox URL

Please include a codesandbox URL if possible
https://codesandbox.io/s/blue-night-qvnnn?file=/src/App.tsx

## Expected behavior
The polyfill should render the correct date format

## Works With Browsers
1. Chrome (Latest version)

## Doesn't Work With Browsers
1. Firefox (latest)
2. Edge(latest)

## Local Timezone
America/New_York

Chrome:
![image](https://user-images.githubusercontent.com/43793510/112906661-8b47fe00-90ba-11eb-85f7-be63d785b6cc.png)
Firefox:
![image](https://user-images.githubusercontent.com/43793510/112906581-65baf480-90ba-11eb-8bb7-5a10531f55c2.png)

**Comment by longlho** [comment]
Did you set timezone? https://formatjs.github.io//docs/polyfills/intl-datetimeformat

**Comment by longlho** [comment]
don't sort your `import`s, you need `/polyfill` before `/add-all-tz`

**Comment by JoeQuattrone** [comment]
That did the trick. Correct me if I'm wrong, but the limitation of the pollyfill is that it cannot detect timezones? Because of this, we have to specify a default timezone and if a user is accessing the app from a different timezone, the pollyfill will use the default timezone instead of the user's?

**Comment by longlho** [comment]
Yes browsers do not expose default timezone because of fingerprinting issue so our default tz is always `UTC`
