### ISSUE TITLE
Error formatting message: select format keys with special characters

### ISSUE THREAD

**Issue by mtsdalmolin** [formatjs/formatjs#2781]
## Which package?
- `react-intl`

## Describe the bug
`{select}` format is not working properly when selection key has special characters such as `-` or `.`. But it works with `_`.

#### So my question is: Is this a bug or a feature?

The documentation doesn't explicit this limitation. It only says that it has a `switch`-like behavior.

If in fact, this is not a a bug, i can close this issue instantly. But i suggest updating the documentation.

### Codesandbox URL
I made this [codesandbox](https://codesandbox.io/s/react-intl-formatted-message-error-rdvg9?file=/src/App.js) to reproduce this behavior.

## Expected behavior
The rendered message will be its id, throwing the following error:

```
  Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting message: "task-status", using id as fallback. 
```

## Desktop (please complete the following information):

- OS: Ubuntu 20.04
- Browser: Chrome
- Version: 5.15.5

**Comment by longlho** [comment]
Argument variable must follow [Unicode `Pattern_Syntax`](https://www.unicode.org/reports/tr31/tr31-9.html#Pattern_Syntax) spec. Doc update PR's also welcome!

**Comment by mtsdalmolin** [comment]
Oh, makes sense.

I'll update the documentation and make the PR, then.
