### ISSUE TITLE
React-intl installation breaking

### ISSUE THREAD

**Issue by naveenvignesh5** [formatjs/formatjs#2792]
## Which package?
react-intl

## Describe the bug

intl-messageformat has version till 9.6.5 only. So build is breaking.

```
npm WARN using --force Recommended protections disabled.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for intl-messageformat@9.6.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
```

## To Reproduce
```sh
npm i react-intl
```
## Screenshots

<img width="901" alt="Screenshot 2021-04-04 at 8 31 14 AM" src="https://user-images.githubusercontent.com/19146999/113497277-20664f00-9520-11eb-8795-0101eced8701.png">

**Comment by longlho** [comment]
Apology for the breakage. We just published that version

**Comment by wilcoxmd** [comment]
Can confirm our builds our working again. Thanks for the speedy fix.

**Comment by ramsunvtech** [comment]
Timely posted @naveenvignesh5. Good catch !!

Thanks @longlho
