### ISSUE TITLE
react-intl breaks build with the following error import error: 'convertNumberSkeletonToNumberFormatOptions' is not exported from 'intl-messageformat-parser

### ISSUE THREAD

**Issue by whitehatgg** [formatjs/formatjs#2793]
_Originally posted by @bramski in https://github.com/formatjs/formatjs/issues/2005#issuecomment-809788197_

**Comment by longlho** [comment]
do you have a repro?

**Comment by bramski** [comment]
This is easy to repro if you have the following versions in your package.json
```
"intl-messageformat-parser": "^5.1.1",
"react-intl": "^4.6.6",
```

Please just unpublish `5.5.1` given it's incompatibility.

**Comment by longlho** [comment]
The whole package has been deprecated. npm doesn't allow you to unpublish afaik
