### ISSUE TITLE
The constant seems to be wrong in TimeClip

### ISSUE THREAD

**Issue by leij1ang** [formatjs/formatjs#2797]
## Which package?
ecma402-abstract

## Describe the bug
function [TimeClip](https://tc39.es/ecma262/#sec-timeclip), the implement of [Abstract TimeClip](https://github.com/formatjs/formatjs/blob/main/packages/ecma402-abstract/262.ts#L65) should be checked

6.84e+16 => 8.64e+15

**Comment by longlho** [comment]
Thanks for reporting! This is also a super easy fix if you want to put in a quick PR.

**Comment by leij1ang** [comment]
sure, I'll fix this later
