### ISSUE TITLE
Missing EOF newline in output file when using `extract`

### ISSUE THREAD

**Issue by glen-84** [formatjs/formatjs#2803]
## Which package?

`@formatjs/cli`

## Describe the bug

When using `formatjs extract`, the output file is missing an EOF newline.

### Codesandbox URL

n/a

### Reproducible Steps/Repo

1. Run `formatjs extract "src/**/*.vue" --out-file data/lang/en-gb.json`.
2. Open the output file (`data/lang/en-gb.json`).

## Expected behavior

I expected to see an EOF newline.

## Screenshots

![image](https://user-images.githubusercontent.com/261509/113912114-115ef580-97db-11eb-87cf-b2c186c18602.png)

## Desktop (please complete the following information):

n/a

## Smartphone (please complete the following information):

n/a

## Additional context

n/a

---

Workaround: `&& prettier --write data/lang/en-gb.json` (which also adjusts the indentation).

**Comment by longlho** [comment]
hmm this is an issue with https://github.com/jprichardson/node-fs-extra since we use it.

**Comment by glen-84** [comment]
I'm not sure if it's the responsibility of `node-fs-extra`, or if you should just append `\n` to `serializedResult`?

**Comment by longlho** [comment]
Is this causing a parsing issue on your side using some unix tooling? `eof` is optional.

**Comment by glen-84** [comment]
It's not causing any parsing issues (that I know of).

An EOF newline is required in order for a file to be considered valid in Unix environments (at least under the POSIX standard).

See:
- https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/729795
- https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file
- https://thoughtbot.com/blog/no-newline-at-end-of-file

A small example of why it can be annoying:

```sh
Glen@Glen-PC /d/Programming/Projects/*/v4/front-end (master)
$ cat client/src/app/site/lang/vi.json
{
    "Ad/tGA": "Example"
}Glen@Glen-PC /d/Programming/Projects/*/v4/front-end (master) # The prompt should be on the next line.
```

**Comment by longlho** [comment]
So I think `fs-extra`'s `writeFile` should take care of it if it's a common practice. Otherwise we run the risk of double `EOF` if we do it & then they also decide to do it. Maybe create a GH issue on their repo?

**Comment by glen-84** [comment]
Thinking about this more, Node.js's `writeFile` method does not automatically write the EOF newline, so I don't think that `fs-extra` would want to diverge from that behaviour.

Do you know of any popular projects that generate files without an EOF newline?

**Comment by longlho** [comment]
yeah I believe both `js-lingui` & `react-i18next` use `fs-extra` which would suffer from the same issue

**Comment by glen-84** [comment]
`js-lingui`

I tried the `create-react-app` example, and `po` files were generated with an EOF newline, but JSON files were not.

`react-i18next`

I'm not sure how to test extraction, but most of the `translation.json` files have EOF newlines.

---

Somewhat-related SO question [here](https://stackoverflow.com/questions/50622958/how-to-re-write-json-to-a-file-so-as-not-to-get-no-newline-at-end-of-file-di).

**Comment by glen-84** [comment]
Not stale, please label.

**Comment by glen-84** [comment]
@longlho Can you please label this issue to stop it from being marked as stale?
