### ISSUE TITLE
Require an OptionalFormattedMessage or a hideIfEmpty prop on FormattedMessage

### ISSUE THREAD

**Issue by bcowgill** [formatjs/formatjs#2810]
## Which package?
react-intl

## Describe the bug
```
<FormattedMessage id="something" defaultMessage="" />
```

We require the ability to suppress a message and/or related content if the localised value is empty.
Instead, the above will show "something" as the message text.
If we set defaultMessage to " " (space) it still renders a space.
If we set defaultMessage to null or undefined it also shows the ID value instead of suppressing the message completely.

 If we had a hideIfEmpty prop or a separate component `<OptionalFormattedMessage>` it would suit perfectly.
or an event prop onContent() onEmpty()

Without this we are going to have to replicate some of the logic of the internal *formatMessage* function to check if the message for the currently provided locale (from `<IntlProvider>`) is empty and then skip the `<FormattedMessage>` component.

It would also help for debugging if there was a way to have a data-message-id prop added to the rendered content (in develop/test env perhaps) so we could inspect the DOM to see what ID corresponds to the text being displayed whenever react-devtools are not available

## To Reproduce
```
<FormattedMessage id="something" defaultMessage="" />
```
should not render anything if some option provided (or null or something)

### Codesandbox URL

n/a

### Reproducible Steps/Repo

n/a

## Screenshots

See screenshots with empty value for defaultMessage or a single space.

<img width="1440" alt="with-default-empty" src="https://user-images.githubusercontent.com/968686/114204686-6290f580-9951-11eb-9880-ab0cdb26524a.png">

<img width="1440" alt="with-derault-space" src="https://user-images.githubusercontent.com/968686/114204716-6c1a5d80-9951-11eb-9084-c232b8a79ff3.png">

## Desktop (please complete the following information):

n/a

## Smartphone (please complete the following information):

n/a

## Additional context

n/a

**Comment by longlho** [comment]
Hmm so when the content is not translated you don't display the `defaultMessage` instead? I'm trying to understand your use case. Wouldn't that cause layout issues?

Rendering `data-message-id` would increase the serialized HTML payload if you're doing SSR so we prob wouldn't do it by default.

One way is possibly to pass back the message descriptor to FormattedMessage's render function so you can decide to show/hide it.

**Comment by bcowgill** [comment]
Simplified use case: 

We have for example a privacy policy page which is translated into different languages and varies slightly by partner company.  

So there might be say 12 points in the english translation for partner X but only 8 points in chinese for partner Y.

So if we loop through the message Id's (privacy1 .. privacy12) and render FormattedMessage as a list, the 9,10,11,12 items in chinese should render null so nothing shows.

**Comment by longlho** [comment]
hmm so shouldn't the filtering skip ID 9 10 11 12 and not even render `FormattedMessage`? I think conceptually u'd be relying on an internal implementation details from us that might change version to version.

**Comment by bcowgill** [comment]
Correct, The current locale/messages are passed into an IntlProvider way up in the app, which your FormattedMessage consumes to determine what message to display for any ID.

Is there a separate IntlConsumer or hook to useIntlProvider supplied so I can look whether a message for an ID is empty, before trying to create a FormattedMessage ?  I don't see how I can get access to the message content before creating a FormattedMessage.

edit: looking at the source, I think if you exported invariantIntlContext I could do my thing quite easily.

So I'll have to duplicate whatever consumer logic you use or do something tricky like render FormattedMessage in a hidden span then look at innerText to see if it equals the ID to see if there was no related message.

I'm due to implement this now in the next two weeks. (Apr 13-16 2021)

**Comment by longlho** [comment]
I believe `useIntl` returns you an `intl` object with `messages` attribute that has the whole message map. Can you use that one?

**Comment by bcowgill** [comment]
Yes, that is perfect. Thanks ever so much for your assistance.
