### ISSUE TITLE
other types of calendars support

### ISSUE THREAD

**Issue by Stevemoretz** [formatjs/formatjs#2811]
How would you mind telling us when you have plans to add persian and other types of calendar.

```
Right now we only support Gregorian calendar in this polyfill. Therefore we recommend setting calendar: 'gregory' in your options to be safe.
```

based on :
https://formatjs.io/docs/polyfills/intl-datetimeformat

Or maybe is there any hack or anything for adding this feature right now?
I'm using this on the latest version of react-native.

**Comment by longlho** [comment]
Unfortunately implementing other type of calendar is pretty complicated so I don't really have any immediate plan atm.

**Comment by Stevemoretz** [comment]
Implementing?Sorry didn't know that.
So using these stuff that firefox has written is impossible?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/calendar
It has to be reimplemented?


These are the libraries I used before intl, maybe it will help your team :

Here's a library that does this for jalali time.
https://github.com/jalaali/jalaali-js

Here's the implemented moment.js verison
https://github.com/jalaali/moment-jalaali

**Comment by longlho** [comment]
This is a polyfill so yes the assumption is that the functionality is not there in the browser.
`jalaali-js` doesn't seem to deal w/ timezone & daylight savings.

**Comment by Stevemoretz** [comment]
Wow you reimplemented all those stuff, unbelievable.
Kudos on your awesome work!

`jalaali-js doesn't seem to deal w/ timezone & daylight savings.`

No timezone is a separate thing.
Really doesn't matter in a calendar, only Year,Month,Day matter in calendars.

The timezone is the same thing for all the calendars.

I usually end up getting the date and time calculated separately and then glue them together.

**Comment by longlho** [comment]
If you have a specific calendar you're looking for support & some reference materials maybe we can prioritize it
