### ISSUE TITLE
Question : how to formatNumber in a text having characters as well

### ISSUE THREAD

**Issue by Stevemoretz** [formatjs/formatjs#2819]
Hi I'm using the polyfill on react native,It's great and I love it.

But I'm confused how to change:

`Let's have 7 pizzas`

To 

`Let's have ۷ pizzas.`

When Persian is chosen.
My use case is I have some comments which I don't know their format obviously, so I don't know if it contains any digits or not and if it does maybe they are written in Persian already maybe in English maybe in Arabic.

I just want to make all digits Persian.

**Comment by longlho** [comment]
You can change the numberingSystem I believe?

**Comment by Stevemoretz** [comment]
Thanks for the reply,
What do you mean by numberingSystem?

I'm using createIntl, and then use the object with its functions like formatNumbers... From core.

**Comment by Stevemoretz** [comment]
@longlho 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

Saw it here now the problem is not how I make the number Persian I can use local as fa and it gets converted.

The question is how do I use numberformat on a string containing possibly multiple numbers and also characters.

For example here's the user comment :

Hello I have bought 7 shoes from you 1 of them looks a bit off.

**Comment by longlho** [comment]
I'm not sure I understand your setup. You want to parse out the numbers separately and convert to persian?

**Comment by Stevemoretz** [comment]
@longlho
I wanted to see whether there is a way without using regex that handles the numbers in a string manually without me manually separate them, and then format each one.

Also the Persian part is just an example I want it to be converted to the current locale which I already can do for formatting numbers.

**Comment by longlho** [comment]
Yeah I don't think that's within the scope of what we do in this package

**Comment by Stevemoretz** [comment]
Thanks for the answer.
Sorry for the inconvenience.
