### ISSUE TITLE
Improvements to `IntlShape` and `IntlConfig`

### ISSUE THREAD

**Issue by glen-84** [formatjs/formatjs#2821]
https://github.com/formatjs/formatjs/discussions/2804#discussioncomment-598985

1. Set the generic type argument of `IntlShape` to `string` by default, like `IntlConfig`.
2. Mark config fields like `formats`, `defaultFormats`, and `onError` as optional in the `IntlConfig` type.

**Comment by longlho** [comment]
For (2) you can use `OptionalIntlConfig`

**Comment by glen-84** [comment]
@longlho `OptionalIntlConfig` is not exported from `vue-intl`.

**Comment by longlho** [comment]
yeah I think `OptionalIntlConfig` should have been `IntlConfig` and `IntlConfig` should have been `ResolvedIntlConfig` basically :-/ will try to find time to fix this

**Comment by longlho** [comment]
fixed in latest
