### ISSUE TITLE
icu-messageformat-parser - regex unicode flag fallback edge case

### ISSUE THREAD

**Issue by ilikesleeping** [formatjs/formatjs#2822]
## Which package?
@formatjs/icu-messageformat-parser

## Describe the bug
The new fast messageformat parser fails in non-Chromium versions of Edge. The problem specifically is that the legacy version of Edge supports the `u` regex flag, but not the `Pattern_Syntax` character class. This means the regex polyfill/alternative does not get detected properly in that instance.

I am working with a site that must load on the Xbox One browser, which happens to still use the non-Chromium version of Edge. So I realise this particular browser version is on its way out, but it is still "current" in some contexts.

### Codesandbox URL

https://codesandbox.io/s/blazing-pine-kpezq

### Reproducible Steps/Repo

1. Open codesandbox link in modern browser
    * Unicode flag support: supported
    * Pattern_Syntax support: supported
2. Open codesandbox link in legacy Edge or Xbox One browser
    * Unicode flag support: supported
    * Pattern_Syntax support: not supported
3. Codesandbox doesn't work in IE11, but if it did, both would be unsupported.

## Expected behavior
The polyfill tester should check if the full `RE('([^\\p{White_Space}\\p{Pattern_Syntax}]*)', 'yu')` regex is supported, rather than just the `u` and `y` flags alone.

A simple fix could be to simply test that the regex matches an intended string, e.g.
```
let REGEX_SUPPORTS_U_AND_Y = true
try {
  const re = RE('([^\\p{White_Space}\\p{Pattern_Syntax}]*)', 'yu')
  REGEX_SUPPORTS_U_AND_Y = re.exec('a')[0] === 'a'; //Or similar string test
} catch (_) {
  REGEX_SUPPORTS_U_AND_Y = false
}
```

## Additional context
I appreciate there may be limited value in fixing things specifically for legacy Edge, but as mentioned above, there do exist current usages of it (for now).

The fix would be very minor, and help iron out an edge case (pun unintended!) where the regex is detected as supported, when it isn't, so I think it may still be worth handling.

I could attempt a PR if required, but Git isn't my usual VCS, so I'm not totally familiar with how that all works!

**Comment by imguolao** [comment]
But this fix does not work.

#2836

**Comment by ilikesleeping** [comment]
FYI the above fix is not in any published package version yet.

**Comment by imguolao** [comment]
> FYI the above fix is not in any published package version yet.

Sry, i'm not aware that this fix hasn't been released yet. 
You are right!

**Comment by longlho** [comment]
my bad I forgot to release. Latest version should have this fix
