### ISSUE TITLE
ts-transformer: error occurs if "=value" syntax is used when ast option enabled

### ISSUE THREAD

**Issue by mabeyj** [formatjs/formatjs#2823]
## Which package?
@formatjs/ts-transformer

## Describe the bug
When using ts-transformer with ts-loader and `{ast: true}`, an error occurs when using the `=value` syntax in messages:

For example, a message containing `{value, plural, =0 {zero} other {#}}` produces the following error:

```
ERROR in ./src/index.tsx 10:133
Module parse failed: Unexpected token (10:133)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
| var react_intl_1 = require("react-intl");
| react_dom_1["default"].render(react_1["default"].createElement(react_intl_1.IntlProvider, { locale: "en" },
>     react_1["default"].createElement(react_intl_1.FormattedMessage, { id: '', defaultMessage:[{ type: 6, value: "value", options: { =0: { value: [{ type: 0, value: "zero" }] }, other: { value: [{ type: 7 }] } }, offset: 0, pluralType: "cardinal" }], values: { value: 0 } })), document.getElementById("root"));
```

It looks like it is producing code with invalid syntax: `options: { =0: { value: [{ type: 0, value: "zero" }] }, ... }` (the `=0` key)

### Codesandbox URL

https://codesandbox.io/s/old-water-fzz3y

### Reproducible Steps/Repo

I'm not sure how to get CodeSandbox to show build errors, but if you run `yarn build` in a terminal, it produces the error above.

## Expected behavior
There should be no error in this case.

## Additional context
An error doesn't occur if the `ast` option is disabled. Not sure if this issue occurs with other build tools.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
