### ISSUE TITLE
[Feature Request] Allow customization of MessageDescriptor from ambient redeclaration

### ISSUE THREAD

**Issue by quantizor** [formatjs/formatjs#2830]
First, library's awesome. I'm using it in a typescript project and would love to be able to do something like this:

```ts
declare module '@formatjs/intl' {
  interface MessageDescriptor {
    id?: LocaleStrings
  }
}
```

Where `LocaleStrings` is a string union of all my messages. That way you'd get nice autocomplete when using `formatMessage({ id })` for example.

Perhaps abstracting it so the interface looks like this might help:

```ts
type MessageDescriptorId = string | number

interface MessageDescriptor {
  id?: MessageDescriptorId
  description?: string | object
  defaultMessage?: string | MessageFormatElement[]
}
```

And then people could do this if desired:

```ts
declare module '@formatjs/intl' {
  type MessageDescriptorId = LocaleStrings
}
```

**Comment by quantizor** [comment]
The other option I can think of is to make the `MessageDescriptorId` a generic and thread that through the system, but that might be a much larger ask since everything's so interconnected.

**Comment by longlho** [comment]
I'm definitely open to this but have not found the time to wrangle with TypeScript to make it happen. PR's welcome though!

**Comment by quantizor** [comment]
Sweet, I'll have a think

**Comment by quantizor** [comment]
Made this, I don't think it's currently possible via basic augmentation https://github.com/microsoft/TypeScript/issues/43980

One way this could be supported in the library is an API like this:

```ts
const IntlProvider = createIntlProvider<MessageDescriptorIds>()
```

And then bootstrap the whole shebang that way as a generic that falls back to `string | number`.

**Comment by longlho** [comment]
that's possible if you can figure out how to thread it through :)
