### ISSUE TITLE
The `defaultMessage` has different shape when using `ast: true`

### ISSUE THREAD

**Issue by maciej-gurban** [formatjs/formatjs#2832]
I noticed that when using automatic ID generation as defined in the docs, what gets assigned to `defaultMessage` of each entry in `defineMessages()` is different depending on whether we use `ast: true` or not, and I couldn't find explanation for why that's the case, or if there's a way to opt out of this behaviour in the documentation. Here's a more in depth explanation:

**Babel config**
```js
plugins: [
  // ...
  [
    'formatjs',
    {
      idInterpolationPattern: '[sha512:contenthash:base64:10]',
      ast: true,
    },
  ],
]
```

**App code**
```js
export const featureFlagMessages = defineMessages({
  title: {
    defaultMessage: 'My Page Title',
  },
});

// Running inside any component the following:
console.log(messages.title) 

// With ast: true will log:
{ title: {id: "LQG34RQEZO", defaultMessage: "My Page Title"}}

// With ast: false will log:
{ title: { id: "LQG34RQEZO", defaultMessage: [{type: 0, value: "My Page Title"}]}
```

The reason this is disruptive, is that in some cases, we'll need to write assertions like:
```js
expect(wrapper.find(PageHeader).props()).toMatchObject({
  title: messages.title.defaultMessage,
});
```

Having to write `title: messages.title.defaultMessage[0]` looks like a much more implementatic-specific syntax rather than regular check prop to value check.

**Comment by longlho** [comment]
when you do `expect` test you should always use `formatMessage` instead of raw `.defaultMessage`. The `ast` option pre-parses the messages at build time so that it's more performant at runtime. So in your case you should get a reference to `intl` and match against `intl.formatMessage(messages.title)`.
