### ISSUE TITLE
Consider bringing back moduleSourceName

### ISSUE THREAD

**Issue by mimecuvalo** [formatjs/formatjs#2835]
## Which package?
@formatjs/babel-plugin-formatjs

## Describe the bug
In a recent commit https://github.com/formatjs/formatjs/commit/e310baf561b0313f251d16e9b97109cd40cbcf0e `moduleSourceName` was removed from the extraction cli. The comment on the diff said it wasn't used much but it's used in the package that I maintain: https://www.npmjs.com/package/react-intl-wrapper

@longlho I used to work at Dropbox (on Dropbox Paper) where we used the formatjs/react-intl packages and created our own wrappers (you've probably seen :) - I hear you've made a wrapper too at Dropbox internally!)

The react-intl-wrapper package that I maintain adds some niceties that I created at Dropbox (the short `F` tag, adding a `fallback`, and some other things).

Lemme know if there's a better way to do extraction without `moduleSourceName` but it'd be great to have it back :D

**Comment by longlho** [comment]
Can you clarify how that affects your use case?

**Comment by mimecuvalo** [comment]
> Can you clarify how that affects your use case?

Sure @longlho and thanks for the consideration. Since I maintain an npm package called [react-intl-wrapper](https://www.npmjs.com/package/react-intl-wrapper) that wraps around `react-intl` and provides extra functionality, the developers import `FormattedMessage` tags like this:
```
import {F} from 'react-intl-wrapper'
```

I'm able to get the extraction tool to find the `F` tags via `--additional-component-names` but it won't see the `F` tags unless I am able to specify that the module is called `react-intl-wrapper` (not `react-intl`) - this was previously possible with `moduleSourceName`.

**Comment by mimecuvalo** [comment]
To that point, in general the use case is: if somebody wraps the `react-intl` library internally at their company, and then imports become something like `import {FormattedMessage} from '../../util/our-internal-i18n-library'` to provide a layer of abstraction, it'll make it difficult in general for people to use the formatjs/cli extraction tool.

**Comment by mimecuvalo** [comment]
Huh, trying it out again it looks like it works actually just fine. I think I was confused by the documentation here: https://formatjs.io/docs/tooling/babel-plugin/ that says:
"This Babel plugin only visits ES6 modules which import React Intl."
and
"By default we check for the fact that FormattedMessage are imported from moduleSourceName to make sure variable alias works. This option does not do that so it's less safe."

Looking at the documentation, I think it may be out-of-date and why I was confused.

I'll close this out - sorry for the noise. Glad to see that some of the i18n work at Dropbox Paper has become folded back into formatjs properly! Glad you're working on it @longlho !

**Comment by longlho** [comment]
yeah sorry the doc is definitely out of date.

**Comment by kyrstenkelly** [comment]
I'm running into this exact same problem. I'm creating a wrapper at my company, and I cannot get the extractor to work even with `--additional-component-names`, I'm guessing because it doesn't know the write `moduleSourceName`. 

I'm doing something like this:
```jsx
...
// T wraps FormattedMessage, and useTranslate wraps useIntl
import { T, useTranslate } from '@udacity/ureact-i18n';

const MyComponent: React.FC<Props> = () => {
  const t = useTranslate();
  return (
    <div>
     <T id="someMessage" defaultMessage="My Message" />

     {t.formatMessage({
       id: 'pageTitle',
       defaultMessage: 'Demo Application',
     })}
    </div>
  );
};
```

Interestingly, it finds the message from `t.formatMessage`, (probably because the method name is the same?), but it does not find any messages in the `<T>` component. 

Any suggestions on how to get the `extract` CLI to work for me?

Here's an example of the command I'm running that doesn't work:
```
formatjs extract --additional-component-names ['T'] "src/**.tsx"

// Outputs:
{
  "pageTitle": {
    "defaultMessage": "Demo Application"
  }
}
```

**Comment by kyrstenkelly** [comment]
Okay...I figured I was just doing something stupid. The docs are a bit misleading, because `--additional-component-names` says:
> Additional component names to extract messages from, e.g: `['FormattedFooBarMessage']`

Which lead me to try and pass `--additional-component-names ['T']` above. 

However, this works:
`formatjs extract --additional-component-names T "src/**.tsx"`
