### ISSUE TITLE
Question: is there any way to extract message from custom prop name?

### ISSUE THREAD

**Issue by SanichKotikov** [formatjs/formatjs#2838]
Hi,

For example, I have my own translation component:

```jsx
<Text
  id="some.id"
  message={'Hello {name}!'}
  name={user.name}
/>
```

Is there any way to extract messages from `message` prop, not from `defaultMessage`?

Thanks.

**Comment by longlho** [comment]
not atm afaik but we'll see if this has enough traction we can consider adding it
