### ISSUE TITLE
Unable to import intl-messageformat as standard ESM module

### ISSUE THREAD

**Issue by tirithen** [formatjs/formatjs#2841]
First of all, thanks creating the super useful package intl-messageformat! :)

## Which package?

`intl-messageformat` version ^9.6.7

## Describe the bug

Importing intl-messageformat as standard ESM modules fails:

```bash
$ npm test

> translated-text@0.0.0 test
> web-test-runner --coverage


test/translated-text.test.js:

 🚧 Browser logs:
      SyntaxError: The requested module './../../../@formatjs/icu-messageformat-parser/index.js' does not provide an export named 'isArgumentElement'

 ❌ Could not import your test module. Check the browser logs or open the browser in debug mode for more information. 

Chrome: |██████████████████████████████| 1/1 test files | 0 passed, 0 failed

View full coverage report at coverage/lcov-report/index.html

Error while running tests.
```

The problems seem to be related to `@web/test-runner` expecting standard ESM modules, but parts of formatjs not using ESM exports?

I have tested the `intl-messageformat` package with vite dev server without problems, but for the popular test runner `@web/test-runner` some of the magic transformations between CJS? and ESM fails.

The failing file "./node_modules/@formatjs/icu-messageformat-parser/index.js" seem to be written in the older CJS format.

## To Reproduce

1. Start a new project with `npm init @open-wc`
2. Add dependency `npm install --save intl-messageformat`
3. Edit the component to import the package with `import IntlMessageFormat from 'intl-messageformat';`
4. Run tests with `npm test`
5. Import errors are generated as above

I put a basic project setup in a git repository in case that makes the problem more clear https://github.com/tirithen/esm-problems-with-intl-messageformat

### Component example

Example of the import that fails on testing:

```javascript
import { LitElement, html, css } from 'lit-element';

// Import IntlMessageFormat below
import IntlMessageFormat from 'intl-messageformat';
console.log(IntlMessageFormat);

export class TranslatedText extends LitElement {
  static get properties() {
    return {
      title: { type: String },
    };
  }

  render() {
    return html`
      <main>
      </main>
    `;
  }
}
```

## Expected behavior

Adding standard ESM import `import IntlMessageFormat from 'intl-messageformat';` to a JavaScript file should import the `IntlMessageFormat` constructor without the need for added special code transformers.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
latest version should have the fix for this

**Comment by tirithen** [comment]
Many thanks for fixing this issue, now the imports works perfectly!

Thanks for your great work with this package! :)
