### ISSUE TITLE
UMD builds are missing starting 5.13

### ISSUE THREAD

**Issue by or-else** [formatjs/formatjs#2843]
## Which package?

react-intl

## Describe the bug

There are no UMD builds anymore (since 5.13.0):
https://cdn.jsdelivr.net/npm/react-intl@5.16.0/react-intl.umd.min.js -> "Couldn't find the requested file /react-intl.umd.min.js in react-intl."

The last one exists in 5.12.5

## To Reproduce

Visit https://cdn.jsdelivr.net/npm/react-intl@5.16.0/react-intl.umd.min.js or https://unpkg.com/browse/react-intl@5.16.0/react-intl.umd.min.js

### Codesandbox URL

N/A

### Reproducible Steps/Repo

Visit https://cdn.jsdelivr.net/npm/react-intl@5.16.0/react-intl.umd.min.js or https://unpkg.com/browse/react-intl@5.16.0/react-intl.umd.min.js

## Expected behavior

I expect the UMD builds to be present.

## Screenshots

N/A

## Desktop (please complete the following information):

N/A

## Smartphone (please complete the following information):

N/A

## Additional context

None

**Comment by longlho** [comment]
Are you looking for UMD or just IIFE version?

**Comment by or-else** [comment]
I prefer UMD, but anything which can be included into an HTML header would work for me

```html
<script crossorigin="anonymous" 
   src="https://cdn.jsdelivr.net/npm/react-intl@5.12.5/react-intl.umd.min.js"></script>
```

**Comment by longlho** [comment]
https://cdn.jsdelivr.net/npm/react-intl@5.17.0/react-intl.iife.min.js should work now

**Comment by or-else** [comment]
Great, thanks a lot!
