### ISSUE TITLE
intl-datetimeformat polyfill typing issues

### ISSUE THREAD

**Issue by jeremyVignelles** [formatjs/formatjs#2850]
## Which package?
`@formatjs/intl-datetimeformat`

## Describe the bug
When trying to import the [Dynamic import + capability detection sample code](https://formatjs.io/docs/polyfills/intl-datetimeformat/#dynamic-import--capability-detection) into a typescript projects, the compiler complains about missing typings for the following files:
- `@formatjs/intl-datetimeformat/add-all-tz`
- `@formatjs/intl-datetimeformat/add-golden-tz`
- `@formatjs/intl-datetimeformat/locale-data/en`
- `@formatjs/intl-datetimeformat/locale-data/fr`

Additionally, it doesn't find the `Intl.DateTimeFormat.polyfilled` property.

## To Reproduce

Create a typescript project, and paste the code given at  : https://formatjs.io/docs/polyfills/intl-datetimeformat/#dynamic-import--capability-detection

### Codesandbox URL

None

### Reproducible Steps/Repo

1. Create a new typescript project
2. Open a `.ts` file and paste the code inside
3. See error `Could not find a declaration file for module`

## Expected behavior
No typing errors

## Screenshots
![image](https://user-images.githubusercontent.com/3399355/116087630-56bb6800-a6a1-11eb-94fe-e5bbfecca46c.png)

## Desktop (please complete the following information):

- OS: Windows
- Typescript: 4.0.3
- Version: `"@formatjs/intl-datetimeformat": "^3.3.2",`

**Comment by anark** [comment]
I am seeing the same issues
`polyfilled does not exist on type`
and
`could not find a declaration file for module` on the locale-data 

for the `@formatjs/intl-relativetimeformat` and `@formatjs/intl-numberformat` packages as well
