### ISSUE TITLE
Fails to transform FormattedMessage with TSDX

### ISSUE THREAD

**Issue by danielstreit** [formatjs/formatjs#2854]
## Which package?
babel-plugin-formatjs

## Describe the bug
I'm using tsdx to manage the build for my project and am having an issue transforming messages.

* When I use `intl.formatMessage` transformation works as expected.
* When I use `<FormattedMessage />`, the message does not get transformed.

### Git Repro URL

https://github.com/danielstreit/tsdx-formatjs-repro

### Reproducible Steps/Repo

1. Bootstrap [tsdx](https://tsdx.io/#quick-start) project: `npx tsdx create mylib`
2. Run `yarn add react-intl babel-plugin-formatjs`
2. [Add babelrc with babel-plugin-formatjs](https://github.com/danielstreit/tsdx-formatjs-repro/blob/main/.babelrc)
3. [Add messages to the code](https://github.com/danielstreit/tsdx-formatjs-repro/blob/main/src/index.tsx)
4. Run `yarn build`

## Expected behavior

Messages in the build output should:
* Include an id
* `defaultMessages` should be compiled
* `description` should be omitted

See build output here: https://github.com/danielstreit/tsdx-formatjs-repro/blob/main/dist/testintl.esm.js.
* [`intl.formatMessage` is transformed as expected](https://github.com/danielstreit/tsdx-formatjs-repro/blob/main/dist/testintl.esm.js#L6)
* [`FormattedMessage` is not transformed at all](https://github.com/danielstreit/tsdx-formatjs-repro/blob/main/dist/testintl.esm.js#L12)

**Comment by longlho** [comment]
hmm I personally don't use `tsdx` and other toolchains have been working so this is probably an issue on their side. Have you tried creating a GH issue on their side?

**Comment by danielstreit** [comment]
Yes, I've cross-posted to both projects.

The thing that is odd to me is that it works for the functions, but not the
component. Have you seen anything similar before?

**Comment by longlho** [comment]
yeah JSX/TSX might be transpiled differently before getting passed to our plugin which is why we can't detect those Nodes. Can you link this issue to their side as well?

**Comment by danielstreit** [comment]
Here is the issue opened in the tsdx repo: https://github.com/formium/tsdx/issues/1025

**Comment by longlho** [comment]
@danielstreit tsdx looks unmaintained to me. Last commit was Nov 2020

**Comment by danielstreit** [comment]
Yeah, unfortunately, that seems to be the case.

I really liked the concept, but it's becoming difficult to stick with
at this point
