### ISSUE TITLE
[react-intl] Default behavior for undefined values

### ISSUE THREAD

**Issue by RemyMachado** [formatjs/formatjs#2855]
## Which package?
react-intl

## Describe the bug
This is not a bug, but a behavior problem. Thus, a feature or workaround request.

## To Reproduce
https://codesandbox.io/s/react-intl-forked-r7stf

## Expected behavior
When no values are provided to the component, the `{keys}` are not formatted. They are just printed out with the curly brackets.

It would be nice to have a DEFAULT value that would handle this case.

## Proposal
`"{gender, select, male {Tous} female {Toutes} default {Tous}}"`

In french, when no gender is given, the male is used by default, but I don't want to pass a value object everytime I use a `<FormattedMessage id="gender-word" />`. Most of the time it should use the default word.

## Question
Is it a pertinent request or do you already have a workaround for this ?

**Comment by longlho** [comment]
Thanks for reporting. Looks like icu4j enforces the declaration of `other` so the fix here for us is actually to enforce that as well.

```
jshell> MessageFormat msg = new MessageFormat("{a, select, male{1} female{2}}");
|  Exception java.lang.IllegalArgumentException: Missing 'other' keyword in select pattern in "{a, select, male{1}  ..."
|        at MessagePattern.parsePluralOrSelectStyle (MessagePattern.java:1228)
|        at MessagePattern.parseArg (MessagePattern.java:1112)
|        at MessagePattern.parseMessage (MessagePattern.java:995)
|        at MessagePattern.parse (MessagePattern.java:186)
|        at MessagePattern.<init> (MessagePattern.java:171)
|        at MessageFormat.applyPattern (MessageFormat.java:483)
|        at MessageFormat.<init> (MessageFormat.java:381)
|        at (#2:1)
```

We already support `other` as the default option.

**Comment by RemyMachado** [comment]
> Thanks for reporting. Looks like icu4j enforces the declaration of `other` so the fix here for us is actually to enforce that as well.
> 
> ```
> jshell> MessageFormat msg = new MessageFormat("{a, select, male{1} female{2}}");
> |  Exception java.lang.IllegalArgumentException: Missing 'other' keyword in select pattern in "{a, select, male{1}  ..."
> |        at MessagePattern.parsePluralOrSelectStyle (MessagePattern.java:1228)
> |        at MessagePattern.parseArg (MessagePattern.java:1112)
> |        at MessagePattern.parseMessage (MessagePattern.java:995)
> |        at MessagePattern.parse (MessagePattern.java:186)
> |        at MessagePattern.<init> (MessagePattern.java:171)
> |        at MessageFormat.applyPattern (MessageFormat.java:483)
> |        at MessageFormat.<init> (MessageFormat.java:381)
> |        at (#2:1)
> ```
> 
> We already support `other` as the default option.

I'm not sure you are truly getting my problem. `other` doesn't work when no values are specified, because the whole string isn't formatted at all. I Improved the example so you can see (I use `other` and it doesn't default the values).

https://codesandbox.io/s/react-intl-forked-r7stf

tl,dr;

`other` is not solving the problem.

**Comment by longlho** [comment]
ah thanks for clarifying, and no we don't support that natively. Missing values is considered an error. You can write wrapper on top of our components and just inject ambient values in to solve your issue.
