### ISSUE TITLE
`--id-interpolation-pattern` option does not support base62

### ISSUE THREAD

**Issue by ysc3839** [formatjs/formatjs#2857]
## Which package?
`@formatjs/cli`

## Describe the bug
According to [document](https://formatjs.io/docs/tooling/cli/), the `--id-interpolation-pattern` is using `webpack/loader-utils`. But actually it doesn't support base62.

### Codesandbox URL

N/A

### Reproducible Steps/Repo

Execute `formatjs extract test.ts --id-interpolation-pattern "[sha512:contenthash:base62:6]"`
And the result string contains non printable characters:
```
{
  "�\u0014#T\u0001J": {
    "defaultMessage": "test",
    "description": "desc"
  }
}
```

## Expected behavior
The ID should be base62.

## Additional context
According to source code, it's not using `webpack/loader-utils`' implementation of `getHashDigest`.
https://github.com/formatjs/formatjs/blob/0eb8e9a7ebb05b200c5433a7242abad1aa219154/packages/ts-transformer/src/interpolate-name.ts#L24-L33
It just pass `digestType` to `hasher.digest()`, which doesn't support base62.

**Comment by longlho** [comment]
yes this is an old documentation issue. Any particular reason for picking `base62`?

**Comment by ysc3839** [comment]
I just want to prevent `/+` from appear in generated ID.

**Comment by longlho** [comment]
so starting Node15+ you can use `base64url` that will be URL-safe: https://datatracker.ietf.org/doc/html/rfc4648#section-5
