### ISSUE TITLE
[Feature request] Built-in formatter for XLIFF .xlf

### ISSUE THREAD

**Issue by jeerbl** [formatjs/formatjs#2858]
Hi and thanks for the great work on this plugin :)

Right now when I extract translations, I extract as JSON files or `simple` JSON files which is great, but translation agencies do prefer to work with XLIFF. Is there a plan to add an extractor formatter for the XLIFF format? Is this something you'd consider?

Jerome

**Comment by longlho** [comment]
I think there might be external tool to convert json to xliff. We don't have any plan of supporting `xliff` right now but might be in the future.
I'm converting this to a discussion as well.
