### ISSUE TITLE
select type message dont work

### ISSUE THREAD

**Issue by JamesHemery** [formatjs/formatjs#2860]
## Which package?
react-intl

## Describe the bug

Currently I use react-intl 5.12.1 and I have no problems. I've update to react-intl 5.17.4 and suddenly all my `select` messages are not translated and the translation string is displayed raw on the front.

## To Reproduce

Works in 5.12.1: https://codesandbox.io/s/react-intl-select-bug-5121-70x2d
Breaks in 5.17.4: https://codesandbox.io/s/react-intl-select-bug-5174-s1pwr

It seems that it also works in 5.17.3: https://codesandbox.io/s/react-intl-select-bug-5173-b97l3

Compare 5.17.3 and 5.17.4: https://github.com/formatjs/formatjs/compare/react-intl@5.17.3...react-intl@5.17.4

I think that this is due to the version change of `@formatjs/icu-messageformat-parser` (1.2.1 => 2.0.0)

In 5.17.4 if I add a default case (`other`) to the `select`, it works, but originally it not required, at least not in previous versions and no BC was declared?

**Comment by longlho** [comment]
yeah apology for the breakage. This was a transitive dep breaking change so unfortunately `lerna` doesn't auto bump major of dependents. The fix is so that we're more consistent with icu4j and also functionally `other` is required as a catch-all for invalid values.

**Comment by JamesHemery** [comment]
@longlho Yes, but this change may break many projects . Especially since in some cases the other is not necessary.

**Comment by emmenko** [comment]
Hi, first of all thanks for all the work you are doing in this project. Really appreciate it!

Regarding this issue, we're also evaluating what to do in our project with this "unexpected" breaking change, as it requires work both from us devs, translators, etc.

I understand and agree on being consistent with the original spec.

In our messages we also don't use `{other}` and it might get a bit tricky to suddenly "come up" with fallback messages.

Is there a way maybe to opt-out from this behavior? So by default the check is on but people would be able to turn it off. I think this would also ease the transition process of migrating the messages.

Thanks 🙏

**Comment by longlho** [comment]
Most of the time `other` is the same as 1 of the option (e.g for gender the default gender is typically `male` in a lot of languages). So 1 thing I can do is make a linter rule autofix this behavior by inserting `other` with the same message as the 1st option. Would that work?

**Comment by emmenko** [comment]
Thanks for the suggestion.

From my perspective migrating the messages to use `other` is not the main problem. Instead, the fact itself that the message changed is for us a problem.

**Background**

To give you a bit more context: we use Transifex as our translation service. Whenever a source message changes, Transifex removes all translations for that message (which kind of makes sense).

So for us the main effort in this migration would be to manually re-translate all those messages.

**Workaround**

At the moment, we have a workaround in place using `patch-package` to turn off the option again.
This should give us some time to organize the work for migrating the messages and translations.

**Comment by longlho** [comment]
kk I can thread up a deprecated option to turn it off.

**Comment by JamesHemery** [comment]
I don't think all messages should require a catch-all (`other`), but that's a matter of opinion and if you think it's necessary, the linter solution is still an interesting solution.

In the best world, we have an option to choose whether or not we want to require catch-all, otherwise a major version update and a linter rule would be a good solution.

**Comment by tdeekens** [comment]
Hi,

thanks for the great project.

Today I stumbled across the same issue of the latest release "silently" demanding an `other` clause on all translations. 

Is there any progress on making this an opt-in or opt-out behaviour?

Thanks!

**Comment by longlho** [comment]
I'm debating on how to do this basically. Long term there will be no opt-out so the introduction of the opt-out option will be immediately `deprecated`, at which point it's probably better for you guys to just pin to `5.17.3` until you're ready to upgrade.

**Comment by JamesHemery** [comment]
> I'm debating on how to do this basically. Long term there will be no opt-out so the introduction of the opt-out option will be immediately `deprecated`, at which point it's probably better for you guys to just pin to `5.17.3` until you're ready to upgrade.

On our side we have opted for this solution and we will do a progressive migration. Thanks.
