### ISSUE TITLE
Update typescript-eslint in eslint-config-formatjs

### ISSUE THREAD

**Issue by christophehurpeau** [formatjs/formatjs#2863]
Hello,

## Which package?
eslint-config-formatjs

## Describe the bug

https://github.com/formatjs/formatjs/blob/main/packages/eslint-plugin-formatjs/package.json#L27
> "@typescript-eslint/typescript-estree": "^3.6.0",

Latest version of is "@typescript-eslint/typescript-estree" 4.22.1.
It's not really a bug but results in two versions of @typescript-eslint/typescript-estree installed.

Do you plan to update it ?

**Comment by longlho** [comment]
yeah so looks like at the monorepo level we're already using v4. Care for a quick PR?
