### ISSUE TITLE
react-intl with twilio unable to resolve dependancy 

### ISSUE THREAD

**Issue by rahulmistrystackfee** [formatjs/formatjs#2882]
## Which package?
react-intl

## Describe the bug
Could not resolve dependency:
npm ERR! peerOptional typescript@"^4.2" from react-intl@5.17.5

## To Reproduce
Step 1:Follow the same instruction defined over [here](https://www.twilio.com/docs/flex/quickstart/getting-started-plugin) with typescript. 
Step 2: Do npm i react-intl

## Screenshots
![image](https://user-images.githubusercontent.com/80984688/117993196-23453280-b35d-11eb-888e-9bc932a22f11.png)

**Comment by longlho** [comment]
Looks like they're using an old version of typescript. We only support typescript@4

**Comment by rahulmistrystackfee** [comment]
> Looks like they're using an old version of typescript. We only support typescript@4

Did you try to get react-intl plugin working with twilio flex ui?

**Comment by longlho** [comment]
No idk what twilio flex is
