### ISSUE TITLE
cache is not clearly documented

### ISSUE THREAD

**Issue by adjenks** [formatjs/formatjs#2884]
## Which package?
`@formatjs/intl`

## Describe the bug
I don't know the limitations of the object produced by `createIntlCache()`
In particular, can I share instances of it between createIntl() functions? What happens if I don't use it? etc. Is there any reason to not use it? How exactly does it cache? Does it use any sort of long term browser storage or is it just for that one page load?

## Expected behavior
More documentation

The same ticket was opened before: https://github.com/formatjs/formatjs/issues/1441
But I think that a ticket should be left open until it's been documented a bit better.

**Comment by longlho** [comment]
It's an in-memory cache that caches `Intl.*` constructors as mentioned in https://github.com/formatjs/formatjs/issues/1441#issuecomment-523512846. The comment also indicates that you can share it across `createIntl`. Therefore it's not serializable and doesn't use persistent storage. As all caches work it's optional and the benefit is performance.

**Comment by adjenks** [comment]
Thank you for clearing that up.
I should have omitted some of my questions after having discovered the other ticket but I forgot to remove them, my apologies.
Thank you also for responding so quickly.
