### ISSUE TITLE
TypeError: react__WEBPACK_IMPORTED_MODULE_1__.memo is not a function

### ISSUE THREAD

**Issue by rahulmistrystackfee** [formatjs/formatjs#2886]
## Which package?
react-intl

## Describe the bug
TypeError: react__WEBPACK_IMPORTED_MODULE_1__.memo is not a function

## Screenshots
![image](https://user-images.githubusercontent.com/80984688/118192305-933de080-b463-11eb-8c5a-ac8e0aed4d5e.png)

**Comment by longlho** [comment]
do you have a repro?

**Comment by rahulmistrystackfee** [comment]
> do you have a repro?

Issue came up with "react": "16.5.2","react-dom": "16.5.2",

**Comment by longlho** [comment]
Do you have a repro repo or codesandbox?
