### ISSUE TITLE
Feature request - Support for Intl.ListFormat.formatToParts()

### ISSUE THREAD

**Issue by MMauro94** [formatjs/formatjs#2901]
Hi, first of all, awesome library!

In [the docs](https://formatjs.io/docs/intl#formatlist) it's only mentioned `formatList`. However, `Intl` also supports the `formatToParts()` function for lists, as per the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/formatToParts) with what seems good browser support. Is there a reason why it's not supported in this lib?

I'd love to see a `formatListToParts` to reflect this (and also an addition in the polyfill).

**Comment by longlho** [comment]
yeah this shouldn't be too hard to add. PR's also welcome as well. You would basically add a method at https://github.com/formatjs/formatjs/blob/main/packages/intl/src/list.ts & make a binding at https://github.com/formatjs/formatjs/blob/main/packages/react-intl/src/components/createFormattedComponent.tsx#L36
