### ISSUE TITLE
Intl.DateTimeFormat.formatRange polyfill crashes with numeric hour and minute format

### ISSUE THREAD

**Issue by kumikumi** [formatjs/formatjs#2909]
## Which package?
intl-datetimeformat

## Describe the bug
The formatRange method of DateTimeFormat objects constructed with options that specify nothing but `hour: "numeric", minute: "numeric"` crashes with the error "rangePattern is undefined" when formatting a date range whose start and end times take place in different dates.

## To Reproduce

Viewing the following CodeSandbox on Firefox (tried with version 88) crashes the page and shows the error. On Chrome (not polyfilled) it works without crashing the page.

https://codesandbox.io/s/datetimeformat-polyfill-error-4g73w

## Expected behavior
It should not crash

**Comment by longlho** [comment]
I've fixed the crash but uncovered another issue captured in https://github.com/formatjs/formatjs/issues/2915. For now you can work around with specifying date fields
