### ISSUE TITLE
babel-plugin-formatjs no longer ignores messages without defaultMessage

### ISSUE THREAD

**Issue by chrisdchow** [formatjs/formatjs#2910]
## Which package?
`babel-plugin-formatjs`:  version "10.2.14"

## Describe the bug

Messages without `defaultMessage` are not being ignore and instead appear as build errors. Specifically:
`[React Intl] Messages must be statically evaluate-able for extraction`. 
```
<FormattedMessage id={`common.prefix.${variable}`}/>
```

### Reproducible Steps/Repo

Full steps, can ignore the middle steps if you've got a `react-intl` ready app already setup.

1. Install `babel-plugin-formatjs`:  version "10.2.14"
2. Install `react-intl` (v 5.16.0)
3. Installed via CRA + CRACO. 
4. Add the following to craco.config
    ```
      babel: {
        plugins: [
          [
            'formatjs',
            {
              idInterpolationPattern: '[sha512:contenthash:base64:6]',
              ast: true,
            },
          ],
        ],
      },
    ```
5. Setup an IntlProvider, etc ...
6. Declare a message with just an ID, in this case interpolated template string.
    ```
    <FormattedMessage id={`common.prefix.${variable}`}/>
    ```

## Expected behavior

I have  messages with just IDs, no defaultMessages or any other props/args. According to historical behavior formatjs/babel-plugin-react-intl#62, the plugin should just ignore them. 

## Desktop (please complete the following information):

- OS:  masOC Catalina 10.15.7
- Browser: Chrome
- Version: 90

## Additional context
See discussion for additional context: https://github.com/formatjs/formatjs/discussions/2905

**Comment by longlho** [comment]
Can you clarify your use case? If you don't have `defaultMessage` there's really no point using our babel plugin.

**Comment by zinovev** [comment]
Hi! I have the same issue. We use `defineMessages` function call to declare our messages and then use babel plugin to extract them. In `FormattedMessage` we sometimes use non statically evaluate-able props (id) and get this problem. It seems we could just skip extraction if the `defaultMessage` prop isn't provided.
@longlho what would you say?

**Comment by longlho** [comment]
We don't support extraction using the babel plugin. Please use @formatjs/cli instead

**Comment by zinovev** [comment]
I need to remove `defaultMessage` and `description` from build, so I use babel plugin and it fails because of non statically evaluate-able props

**Comment by longlho** [comment]
ah kk. Can you either add a test to your PR or make a repro repo?

**Comment by zinovev** [comment]
yep, done

**Comment by Floriferous** [comment]
This is still happening to me when I use this:

```js
// [React Intl] Messages must be statically evaluate-able for extraction.
intl.formatMessage({ id: `NonStaticKey.${variable}` });
```

Was it only fixed for the React component?

Version 10.3.2

**Comment by hellocreep** [comment]
According to https://github.com/formatjs/formatjs/blob/aaeeae463db1f38a3c3b81bb24fdf6fb433990cb/packages/babel-plugin-formatjs/visitors/call-expression.ts#L104
I did a "trick" for this, just leave the `defaultMessage` to [].
Here is a workaround for me.
```
intl.formatMessage({ id: `dynamic.${id}`, defaultMessage: [] })
```
