### ISSUE TITLE
Typescript type validation error with simple jsx components wrapped in injectIntl not assignable to type

### ISSUE THREAD

**Issue by scottdickerson** [formatjs/formatjs#2920]
## Which package?

react-intl 5.18.1

## Describe the bug
We are in the process of migrating an existing javascript to a Typescript repo, legacy components wrapped with injectIntl are throwing Typescript errors and failing our compile.    Since we have lots of legacy components, I would like to not be forced to port all of the components to TSX

Here's the compilation error.  
```
/Users/scottdickerson/Documents/GitHub/test-intl/src/App.tsx
TypeScript error in /Users/scottdickerson/Documents/GitHub/test-intl/src/App.tsx(26,24):
Type '{ string: string; }' is not assignable to type 'IntrinsicAttributes & Omit<WrappedComponentProps<"intl">, "intl"> & { forwardedRef?: Ref<any> | undefined; } & { ...; }'.
  Property 'string' does not exist on type 'IntrinsicAttributes & Omit<WrappedComponentProps<"intl">, "intl"> & { forwardedRef?: Ref<any> | undefined; } & { ...; }'.  TS2322

    24 |       </header>
    25 |       <section>
  > 26 |         <TestComponent string="my test" />
       |                        ^
    27 |       </section>
    28 |     </div>
    29 |     </IntlProvider>

```

If I remove the injectIntl from the component, the compilation succeeds.

At some point in the future, we will be porting these components to TSX, but we need to be able to continue to use them until that time.

### Codesandbox URL

Unfortunately since this is a type validation error, I can't reproduce on a codesandbox, but I have committed a public git project that shows the error here:
https://github.com/scottdickerson/test-intl

please pull and `yarn install` `yarn start` to see the compilation error

**Comment by scottdickerson** [comment]
I see this as a possible workaround: https://stackoverflow.com/questions/40784817/react-intl-use-api-with-typescript

It would be good though to either document the WrappedComponentProps in an error message or recommend migrating to useIntl when using with Typescript

**Comment by longlho** [comment]
to ease migration you can prob use `// @ts-expect-error` or `@ts-ignore`?

**Comment by scottdickerson** [comment]
thanks, like I said I'm pretty new at typescript.  I also realized you probably can't control the error message from typescript so I'll close this bug and just leave it for future searches
