### ISSUE TITLE
Migrating from babel-plugin-react-intl to babel-plugin-formatjs stops writing out JSON files to filesystem

### ISSUE THREAD

**Issue by scottdickerson** [formatjs/formatjs#2925]
## Which package?
babel-plugin-formatjs

## Describe the bug
In previous versions of babel-plugin-react-intl I was able to specify a messagesDirectory where the JSON files would be output.  This was critical to our translation process as I would aggregate those files and send them to our translators for translation for use in our IntlProvider.  Is there any way in babel-plugin-formatjs to accomplish this?

### Reproducible Steps/Repo

Add a new message to defineMessages and run a development compilation

## Expected behavior
 I expect some JSON file to be written to the filesystem that contains all the messages for that component (including the new message) so I can aggregate it

Here was my previous babel.config.js snipped to configure the babel-plugin-react-intl

```  
plugins: [
        // This is an older version of babel-plugin-react-intl I would love to upgrade the babel-plugin-react-intl to the new version but I can't get it to work yet
        [
          'react-intl',
          {
            messagesDir: './src/lang/',
          },
        ],
      ],
```

**Comment by scottdickerson** [comment]
I see this guidance here: https://formatjs.io/docs/guides/distribute-libraries. but setting the package.json props doesn't seem to write out the message files at build time to that path.  Here's what I tried
```
"lang": "src/lang",
  "supportedLocales": [
    "cs",
    "da",
    "de",
    "en",
    "es",
    "fi",
    "fr",
    "hr",
    "hu",
    "it",
    "ja",
    "ko",
    "nb",
    "nl",
    "no",
    "pl",
    "pt-BR",
    "ru",
    "sk",
    "sl",
    "sv",
    "tr",
    "zh-TW",
    "zh"
  ],
```

I expected the formatjs babel plugin to look for that and based on my changes to defaultMessages write out en.json files

**Comment by longlho** [comment]
we no longer support extracting from babel-plugin so u'd have to use https://formatjs.io/docs/tooling/cli

**Comment by scottdickerson** [comment]
Thanks for the pointer
