### ISSUE TITLE
Plural dont works on Android with react-native | {count, plural, one {lorem} other {ipsum}}

### ISSUE THREAD

**Issue by t1gu1** [formatjs/formatjs#2926]
## Which package?
`react-intl` with react-native

## Describe the bug
With react-native on Android the plurial don't works. (works on IOS)

On Android only, I got that error message:
```bash
[@formatjs/intl Error FORMAT_ERROR] Error formatting message: "Unit.progress.part2", using id as fallback. 
Locale: fr
MessageID: Unit.progress.part2
Default Message: undefined
Description: undefined 

undefined is not a constructor (evaluating 'new Intl.Locale(noExtensionLocale)')
...
```
 

undefined is not a constructor (evaluating 'new Intl.Locale(noExtensionLocale)')

## To Reproduce
Example of the translation string: 
`'Unit.progress.part2': '{count, plural, one {#\u00A0unit} other {#\u00A0units}}'`

**In my component:**
```javascript
const { formatMessage } = useIntl();

const text = `${formatMessage(
    { id: `Unit.progress.part2` },
    { count: remainingUnits },
  )} lorem ipsum!`;
```

**On IOS it looks perfect.** I got the word `unit` or `units` depending the number of `remainingUnits`.
**On Android i see that:** `{count, plural, one {#\u00A0unit} other {#\u00A0units}} in the screen.`

## Expected behavior
Get the same result as IOS

## Smartphone :

- Device: Google Pixel 2XL
- OS:Android
- Version: 11

**Comment by t1gu1** [comment]
I also try that way:

```javascript
<FormattedMessage
   id="Unit.progress.part2"
  values={{ count: remainingUnits }}
/>
```

I got the same result.

**Comment by t1gu1** [comment]
Exact same thing for that:

```javascript
<FormattedPlural
  value={number}
  one={<Text>test1</Text>}
  other={<Text>test2</Text>}
/>
```

It works on IOS but not on Android

**Comment by longlho** [comment]
Did you follow our instructions for react-native on formatjs.io?

**Comment by t1gu1** [comment]
> Did you follow our instructions for react-native on formatjs.io?

Which one? The one talking about pluralrules polyfill here: https://formatjs.io/docs/polyfills/intl-pluralrules/ ?
- Yes

Translation works fine and others Formatted comps or function too.
This is really and only the Plural thing that dont works on Android. (On IOS it works great!)

**Comment by longlho** [comment]
I'm talking about https://formatjs.io/docs/guides/runtime-requirements/#react-native-on-ios

Looking at the stack trace you're missing lower level polyfills (particularly `Intl.Locale`) (see this graph for stuff you need to polyfill: https://formatjs.io/docs/polyfills)

**Comment by t1gu1** [comment]
Thanks @longlho!
This is it!

I had just included `import '@formatjs/intl-pluralrules/polyfill';` before.
Now that I add the missing lower level polyfills, as you say -> `import '@formatjs/intl-locale/polyfill';` everythig works! :D

**Comment by longlho** [comment]
Make sure you polyfill Intl.getCanonicalLocales as well

**Comment by catarinamateus** [comment]
Hi guys! 

I had the same issue in Android using i18next-icu and react-i18next,  and it solved importing pluralrules polyfills and its dependencies, but I am facing a new issue and I was wondering if it happened to you!

When I use plural labels with it breaks without throwing any error if it has the "#'. :

```
import i18n, { InitOptions } from 'i18next';
import ICU from 'i18next-icu';
import { initReactI18next } from 'react-i18next';
import '@formatjs/intl-getcanonicallocales/polyfill'
import '@formatjs/intl-locale/polyfill'
import '@formatjs/intl-pluralrules/polyfill'
import '@formatjs/intl-pluralrules/locale-data/en'

//In my app init
 i18n.use(languageDetector(cfg))
        .use(ICU)
        .use(initReactI18next)
        .init({
              fallbackLng: 'en',
               debug: true,
               nsSeparator: ':',
               keySeparator: '.',
               interpolation: {
                  escapeValue: false,
                  formatSeparator: ',',
                },
              react: {
                  wait: true,
                  useSuspense: false,
               },
            resources: {
                en: {
                     success: '{count, plural, one {Recording canceled.} other {Canceled # recordings.}',
                },
            },
        });

```

```
t('success', {count : 1})
//OUTPUT:  Recording canceled.
t('success', {count : 9})
//OUTPUT: {count, plural, one {Recording canceled.} other {Canceled # recordings.}}
//EXPECTED OUTPUT: Canceled 9 recordings.
```

Is it working for you?

Libs used in project:

"react-native": "0.61.2",
"i18next": "17.2.0",
"i18next-icu": "2.0.3",
"intl-messageformat": "9.4.6",
 "@formatjs/intl-getcanonicallocales": "1.8.0",
 "@formatjs/intl-locale": "2.4.41",
  "@formatjs/intl-pluralrules": "4.2.0",

**Comment by longlho** [comment]
That seems like a i18next issue so not related to this repo
