### ISSUE TITLE
intl-messageformat produces incorrect results for compact-short and compact-long skeletons

### ISSUE THREAD

**Issue by CyberAP** [formatjs/formatjs#2930]
## Which package?
`intl-messageformat`

## Describe the bug
`intl-messageformat` should support formatting numbers with the following skeletons: https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html#examples
But in reality it does not support the full list, specifically compact-short and compact-long skeletons fail to correctly format.

### Codesandbox URL

https://codesandbox.io/s/formatjs-forked-id6l2?file=/src/index.js

### Reproducible Steps/Repo

1. Create a message with a `compact-short` or `compact-long` number formatting skeleton
2. Format that message
3. The value passed to the formatter does not produce a correct result

## Expected behavior

For values greater than 1000 it should print a compact-short or compact-long version of the passed value.

## Desktop (please complete the following information):

- OS: Windows 10
- Browser: Chrome
- Version: 91

## Additional context

Also, it completely fails to produce any result when used in a node environment, which completely destroys SSR for me.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
In your example you have to prefix your skeleton with `::` so `"{value, number, ::compact-short}"`: https://codesandbox.io/s/formatjs-forked-e4dee?file=/src/index.js

**Comment by CyberAP** [comment]
@longlho thank you so much! I couldn't find what double colon does in the docs unfortunately, will dig deeper into the ICU docs.

**Comment by longlho** [comment]
> To use a skeleton in MessageFormat, use the “number” type and prefix the skeleton with ::
