### ISSUE TITLE
It's heavy!

### ISSUE THREAD

**Issue by scazzy** [formatjs/formatjs#2933]
We're using `formatjs-cli` for some pre-bundle tooling to extract translations. We used [@formatjs/cli](https://www.npmjs.com/package/@formatjs/cli), but every time we install dependencies, it takes lot of time to resolve.
FormatJS dependencies seems huge looking at the [package.json](https://github.com/formatjs/formatjs/blob/main/package.json), which includes webpack, vue and plenty other things.
Can there be a lighter `cli-version` that doesn't have many deps just for the individual operations?
Or if you can add some pointers, I can try to create a monorepo which can be added to formatjs org.

**Comment by longlho** [comment]
package.json contains all deps for everything including devDeps. You should look at packages/cli package.json
