### ISSUE TITLE
Unable to use react-intl as external dependency with index.html

### ISSUE THREAD

**Issue by or-else** [formatjs/formatjs#2939]
## Which package?

react-intl
This is a followup on https://github.com/formatjs/formatjs/issues/2843

## Describe the bug

Unable to use `react-intl` as an external dependency by including https://cdn.jsdelivr.net/npm/react-intl@5.18.0/react-intl.iife.js into an `index.html`:

`index.html`:
```html
<script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/react@17.0.1/umd/react.production.min.js"></script>
<script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/react-dom@17.0.1/umd/react-dom.production.min.js"></script>
<script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/react-intl@5.18.2/react-intl.iife.js"></script>
```
Javascript console:
```
react-dom.production.min.js:141 Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react-intl.iife.js:1068)
    at Object.useContext2 (react-intl.iife.js:1074)
    at useIntl (react-intl.iife.js:4285)
    at FormattedMessage (react-intl.iife.js:4583)
    at Le (react-dom.production.min.js:100)
    at Pj (react-dom.production.min.js:231)
    at di (react-dom.production.min.js:168)
    at Nj (react-dom.production.min.js:168)
    at sc (react-dom.production.min.js:168)
    at gf (react-dom.production.min.js:162)
Ye	@	react-dom.production.min.js:141
Mh.c.callback	@	react-dom.production.min.js:141
dh	@	react-dom.production.min.js:80
Bj	@	react-dom.production.min.js:145
Qj	@	react-dom.production.min.js:176
unstable_runWithPriority	@	react.production.min.js:24
Za	@	react-dom.production.min.js:73
eb	@	react-dom.production.min.js:170
gf	@	react-dom.production.min.js:162
Pa	@	react-dom.production.min.js:157
yd	@	react-dom.production.min.js:188
(anonymous)	@	react-dom.production.min.js:191
bi	@	react-dom.production.min.js:163
zd	@	react-dom.production.min.js:191
M.render	@	react-dom.production.min.js:243
e	@	index.js:31
(anonymous)	@	startup:5
(anonymous)	@	index.prod.js:1
```

It works perfectly fine with https://cdn.jsdelivr.net/npm/react-intl@5.12.5/react-intl.umd.min.js

### Codesandbox URL

N/A: I can build react-intl into the package without issues. The problem is with making it an external dependency and including it into the `index.html`.

### Reproducible Steps/Repo

1. Build any react js package with `react-intl` as an external dependency. 
2. Include `<script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/react-intl@5.18.2/react-intl.iife.js"></script>` into your `index.html`. 
3. Observe the breakage in js console.

## Expected behavior

I expect https://cdn.jsdelivr.net/npm/react-intl@5.18.2/react-intl.iife.js to work without breakage.

## Screenshots

N/A

## Desktop (please complete the following information):

Chrome latest, Firefox latest.

## Smartphone (please complete the following information):

N/A

## Additional context

N/A

**Comment by longlho** [comment]
Do you have a repro repo?

**Comment by or-else** [comment]
This is the app:
https://github.com/tinode/webapp
This is where it's used:
https://github.com/tinode/webapp/blob/master/index.html

**Comment by or-else** [comment]
Just closing without even a simple curtesy of a comment?

**Comment by or-else** [comment]
Thanks!

**Comment by longlho** [comment]
react-intl@5.18.3 should have the fix
