### ISSUE TITLE
[vue] Argument of type 'typeof import("xxxx/node_modules/vue-intl/index")' is not assignable to parameter of type 'Plugin_2'

### ISSUE THREAD

**Issue by mashirozx** [formatjs/formatjs#2940]
## Which package?
Since this is a monorepo. Please specify which package this bug report is for.
vue-intl

## Describe the bug
TypeScript error:
`Argument of type 'typeof import("xxxx/node_modules/vue-intl/index")' is not assignable to parameter of type 'Plugin_2'.`

## To Reproduce

```ts
import { createApp } from 'vue'
import VueIntl, { intlKey } from 'vue-intl'
const app = createApp(App)
app.use(VueIntl, {
  locale: 'en',
  defaultLocale: 'en',
  messages: {
    foo: 'bar',
  },
})
```

### Codesandbox URL

Please include a codesandbox URL if possible

## Screenshots
![image](https://user-images.githubusercontent.com/16148054/120457506-1601ed80-c3c9-11eb-849e-faa71658b4a6.png)

## Desktop (please complete the following information):

- OS: [e.g. iOS] macos
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] 80

## Additional context

This happen on vscode editor

Update:

Dev deps:
"vue": "^3.0.5",
"typescript": "^4.3.2",
"@formatjs/intl": "^1.11.2",
"vue-intl": "^6.0.0",

**Comment by longlho** [comment]
What versions of things are you using? cc @glen-84

**Comment by mashirozx** [comment]
Sorry forgetting paste them.

"vue": "^3.0.5",
"typescript": "^4.3.2",
"@formatjs/intl": "^1.11.2",
"vue-intl": "^6.0.0",

**Comment by glen-84** [comment]
https://github.com/formatjs/formatjs/blob/main/packages/vue-intl/CHANGELOG.md#breaking-changes-1

```ts
app.use(
  createIntl({
    locale: 'en',
    defaultLocale: 'en',
    messages: {
      foo: 'bar',
    },
  })
);
```

**Comment by longlho** [comment]
ok looks like this can be closed then

**Comment by mashirozx** [comment]
Oh, it is. Maybe there should be a update of documents.
https://formatjs.io/docs/vue-intl/

**Comment by longlho** [comment]
ah yeah I just published the new docs. Thanks for reminding!
