### ISSUE TITLE
numberingSystem is filtered out in formatNumber

### ISSUE THREAD

**Issue by salzhrani** [formatjs/formatjs#2952]
## Which package?
Since this is a monorepo. Please specify which package this bug report is for.
intl

## Describe the bug
`formatNumber` does not pass the `numberingSystem` option to `getFormatter`, it is filtered out since it is not included in `NUMBER_FORMAT_OPTIONS` [here](https://github.com/formatjs/formatjs/blob/9bb76bb489c772674987d8f03afdb5d425ba2765/packages/intl/src/number.ts#L6)

### Codesandbox URL

https://codesandbox.io/s/react-intl-forked-7g2mj?file=/src/index.js

### Reproducible Steps/Repo

there are two lines with different `numberingSystem` values yet display the same string

## Expected behavior
the line that start with `latn` should have displayed `15%` instead of `١٥٪`

**Comment by mantasstikleris** [comment]
@longlho when you are planning to release the fix? 🙏

**Comment by longlho** [comment]
doing it now so should be up in like 15'

**Comment by mantasstikleris** [comment]
Thanks a lot for the quick turnaround!
