### ISSUE TITLE
Id auto-generation does not work for custom wrapper of "defineMessages"

### ISSUE THREAD

**Issue by vu-dao-93** [formatjs/formatjs#2965]
## Motivation
We have some messages that are scattered across our app that are internal and we don't want them to get extracted and would always use the default message. However we still want those messages to be created with `defineMessages()` and formatted with `formatMessage()`

To do that, we created a wrapper for `defineMessages()` called `defineAdminMessages()`. The problem is, the id auto-generation at `babel-plugin-formatjs` does not work for `defineAdminMessages()`. We would want to be able to add it as a valid callee identifier for id auto-generation but filter it out when extracting strings.

## Suggestion
We found that adding `callee.isIdentifier({ name: 'defineAdminMessages' })` [here](https://github.com/formatjs/formatjs/blob/d374ed37e1a126f81259f8a870d844de1869212e/packages/babel-plugin-formatjs/visitors/call-expression.ts#L165) would fix our issue. So as a suggestion, are you open to adding a setting in `babel-plugin-formatjs` so users can add custom callee for the id auto-generation, similar to `additionalFunctionNames` setting? We can make a pull request ourselves if you see the value in this.

![image](https://user-images.githubusercontent.com/7025841/121325411-417d5e80-c91a-11eb-8034-caf768b19b68.png)

**Comment by longlho** [comment]
yeah I think that's reasonable. PR's definitely welcome!

**Comment by longlho** [comment]
so circling back to this after giving it some thought: Can you just manually set IDs to those messages and still use `defineMessages`?

**Comment by vu-dao-93** [comment]
@longlho technically yes, but we want to standardize the automatic ID approach within our team, so we would prefer adding the custom callee instead.

**Comment by longlho** [comment]
I think you can also declare `defineUnextractedMessages` to inject dummy ID to like `Math.random()` or something. The method signature should be the same, e.g:
```
function defineUnextractedMessages (msgs) {
	return Object.keys(msgs).reduce((all, k) => {
		all[k] = {
			...msgs[k], 
			id: String(Math.random())
		}
		return all
	}, {});
}
```

**Comment by vu-dao-93** [comment]
Thanks for your suggestion. We ended up using the function to inject dummy ID ourselves
