### ISSUE TITLE
FormattedMessage is not defined when using Storybook

### ISSUE THREAD

**Issue by WalkingPizza** [formatjs/formatjs#2966]
## Which package?
react-intl

## Describe the bug
I have been trying to use my components (which rely on react-intl's FormattedMessage) on Storybook, but despite having added a decorator with the IntlProvider, my components don't work because FormattedMessage is not defined.

Error: `Unexpected error while loading ./AuctionCard/AuctionsCard.stories.js: ReferenceError: FormattedMessage is not defined`

### Codesandbox URL
https://codesandbox.io/s/staging-night-h5vt1

### Reproducible Steps/Repo

1. Go to CodeSandbox
2. Run `npm run sb`
3. Check console for error

## Expected behavior
Visualize comonents on Storybook with translated messages.

## Desktop:

- OS: Ubuntu 20.10
- Browser: Google Chrome
- Version 91.0.4472.77

## Additional context
`storybook-addon-intl` does not seem to work with the latest version of react-intl either.

**Comment by longlho** [comment]
Was it a setup issue on your side?
