### ISSUE TITLE
eslint-plugin-formatjs doesn’t support additionalFunctionNames

### ISSUE THREAD

**Issue by andersk** [formatjs/formatjs#2967]
In [Zulip](https://github.com/zulip/zulip) we’re using the Babel plugin with `additionalFunctionNames: ["$t", "$t_html"]`, and `formatjs extract` with `--additional-function-names=$t,$t_html`, but there’s no corresponding option in the ESLint plugin, so we can’t check our `$t` and `$t_html` calls with ESLint. Can a setting for this be added to `eslint-plugin-formatjs`?

Perhaps the [shared settings](https://eslint.org/docs/user-guide/configuring/configuration-files#adding-shared-settings) mechanism could be used to avoid the need to configure it separately for each plugin.

**Comment by longlho** [comment]
latest version should support this. Doc: https://formatjs.io/docs/tooling/linter#shared-settings
