### ISSUE TITLE
npm run extract doesn't catch syntax error(plural,data,html closing tag)

### ISSUE THREAD

**Issue by jitendrachopra** [formatjs/formatjs#2973]
i want to catch plural, date and html tag syntax error during compile time.
following command doesn't throw syntax error while build. i tried with --throws parameter as well.
does formatjs suppose to throw syntax error during build? it replace all string as is currently

e.g. https://formatjs.io/docs/intl-messageformat#common-usage-example : trying this one in local
```
npm run extract -- 'src/**/*.ts*' --out-file src/assets/locale/en-US.json --format=simple
```

following is my dependencies.
```
        "@formatjs/cli": "~4.2.19",
        "vue": "~3.1.1",
        "@formatjs/intl": "~1.12.1",
        "intl-messageformat": "~9.6.18"
```

**Comment by longlho** [comment]
looks like you should use our [linter](https://formatjs.io/docs/tooling/linter).

**Comment by jitendrachopra** [comment]
Thanks for for response.
eslint-plugin-formatjs is not enforcing rules.
it seems linter only works with react-intl not with formatjs/intl. following my implementation.

```
Util.ts
import { createIntl, createIntlCache, defineMessage } from "@formatjs/intl";
import type { MessageDescriptor, IntlCache, IntlShape } from "@formatjs/intl";

this._intlCache = createIntlCache();
    formatMessage = (descriptor: MessageDescriptor, values?: FormatMessageValues) => {
        if (this._intl) {
            return this._intl.formatMessage(descriptor, values);
        }

        this.logger?.error("Attempt to format message before initialization, falling back to default!", { descriptor });
        return String(descriptor.defaultMessage || descriptor.id || "");
    };

my UI file:
      const formatMessage = this.intlStore.formatMessage;

        return html`
                <div class="coordinates">
                    <authored-textfield
                        label=${formatMessage({ id: "XXXX", defaultMessage: "helllo" })}
                    ></authored-textfield>
```

**Comment by longlho** [comment]
do you have a repro? our linter should work for `@formatjs/intl`

**Comment by jitendrachopra** [comment]
@longlho : It is working as expected. i didn't apply linter properly on my code earlier.
Thanks for your help.
