### ISSUE TITLE
Node v16 error when using Intl.Locale polyfill

### ISSUE THREAD

**Issue by JustJenFelice** [formatjs/formatjs#2976]
## Which package?
`@formatjs/intl-locale` and `intl-getcanonicallocales`

## Describe the bug
When attempting to use Intl.Locale polyfill, the following error is encountered:
```
RangeError: Malformed extension type
 at parseExtensions (node_modules/@formatjs/intl-getcanonicallocales/src/parser.js:222:27)
      at Object.parseUnicodeLocaleId (node_modules/@formatjs/intl-getcanonicallocales/src/parser.js:241:45)
      at applyOptionsToTag (node_modules/@formatjs/intl-locale/index.js:37:149)
      at new Locale (node_modules/@formatjs/intl-locale/index.js:215:15)
```
Possibly the same issues referenced in https://github.com/formatjs/formatjs/issues/2423 and https://github.com/Financial-Times/polyfill-service/issues/2484

## To Reproduce
```
// in file.ts
import { Locale } from '@formatjs/intl-locale';

const intlLoc = new Locale(validatedLocale);
```

## Expected behavior
Successful instantiation of Intl.Locale object, without errors.

## Additional context
Node v16.2.0
NPM v7.13.0

"@formatjs/intl": "^1.13.0",
"@formatjs/intl-getcanonicallocales": "^1.7.0",
"@formatjs/intl-locale": "^2.4.32",
"@formatjs/intl-pluralrules": "^4.0.27",
"@formatjs/intl-relativetimeformat": "^9.1.6",

**Comment by longlho** [comment]
What is the locale that you passed in?

**Comment by JustJenFelice** [comment]
Passing in the following string for locale: `en-US-u-ca-gregory-hc-h24`

**Comment by longlho** [comment]
I can't repro it. Do you have a repro?
```sh
~/s/random ❯❯❯ node
Welcome to Node.js v16.1.0.
Type ".help" for more information.
> const {Locale} = require('@formatjs/intl-locale')
undefined
> let a = new Locale('en-US-u-ca-gregory-hc-h24')
undefined
> a.baseName
'en-US'
```

**Comment by JustJenFelice** [comment]
Oof. @longlho - this must have been something in our code - I can't repro now. Thank you for the quick response. Closing.
