### ISSUE TITLE
Suggestion: Make typescript a peer-dependency (rather than a dependency)

### ISSUE THREAD

**Issue by longlho** [formatjs/formatjs#2991]
### Discussed in https://github.com/formatjs/formatjs/discussions/2964

<div type='discussions-op-text'>

<sup>Originally posted by **FrozenKiwi** June  8, 2021</sup>
I recently lost a fair bit of time debugging why ts-transformer was not extracing ids in my toolchain.  In the end, it turned out it was because I was using a different version (4.2) of typescript than formatjs.  FormatJS lists TS4.0 as a dependency, so yarn gave it it's own version and formatjs imports those definitions, while the rest of the compile step came from TS4.2.

The meant the internal typescript types were not consistent.  In between 4.0 and 4.2 the typescript team changed some of the internal definitions. Basically, a number that meant "FileUnit" in TS4.2 AST means something completely different in TS4.0 - and this meant that your parser existed immediately for every file (didn't parse any files - so no ID's injected).

Because TS is listed as a dependency, and not a peer dependency, this mismatch was pretty invisible.  Even when stepping through the code, the input would come in from my TS, then pass through to your version of TS.  If it was a peer dependency, your calls to TS would go back to my version (at 4.2) where they would either succeed or throw an error.

I think somewhere in the docs you state you only support 4.0. The problem is `only support` is pretty vague.  It often means just 'not-tested'.  Even though user-beware, it's nicer to have a great big exception to draw attention to where things aren't working as expected.</div>

**Comment by kevinxh** [comment]
Moving dependencies into a peerDependencies is a BREAKING change, you need a major version bump. @longlho

**Comment by longlho** [comment]
Semantically yes, but why are you using ts-transformer without typescript as a devDep?

**Comment by kevinxh** [comment]
@longlho we use formatjs and `babel-plugin-formatjs` is one of our dependencies, our build pipeline just failed because `Cannot find module typescript`..... we'd have to install typescript even if we don't use it at all 😞

**Comment by kevinxh** [comment]
> Semantically yes, but why are you using ts-transformer without typescript as a devDep?

because it's not in our code, ts-transformer is a hard dependency of `babel-plugin-formatjs` https://github.com/formatjs/formatjs/blob/main/packages/babel-plugin-formatjs/utils.ts#L3

**Comment by longlho** [comment]
can you submit a separate ticket? that we can fix
