### ISSUE TITLE
tooling/cli docs should be updated with correct run commands

### ISSUE THREAD

**Issue by braaar** [formatjs/formatjs#2992]
Hiya!

When following the instructions at [tooling/cli](https://formatjs.io/docs/tooling/cli/), running `formatjs extract --help` results in `formatjs: command not found`.

The solution here is to run `npm run extract --help` or `yarn run extract --help` and so on (replacing `--help` with the actual parameters as explained further down in the instructions).

A [previous commit](https://github.com/formatjs/formatjs/commit/605cb1562cb6f0bd36d573ce1264c7e2756063f0) addressed this in part, but it seems the correct instructions for running these scripts was left out of this page specifically.

Was thinking I would do a PR for this and update `website/docs/tooling/cli.md`, using a [tabgroup with the same groupId](https://docusaurus.io/docs/next/markdown-features/tabs) as the one at the top so you don't have to switch to the yarn tab several times.

**Comment by longlho** [comment]
PR's always welcome :)

**Comment by LoganDark** [comment]
`npx @formatjs/cli` works for me

**Comment by braaar** [comment]
> `npx @formatjs/cli` works for me

Indeed this works. The issue is simply that the docs should reflect that one needs to precede the `formatjs` command with `yarn`, `npm` or `npx`.

**Comment by braaar** [comment]
I'll make a PR when I get around to it 😅
