### ISSUE TITLE
[Feature request] Ability to use plural and Intl.NumberFormat compact notation at the same time

### ISSUE THREAD

**Issue by mashirozx** [formatjs/formatjs#3012]
Can we do such display as below in one formatMessage with formatjs?

```
0 => 0 unit
1 => 1 unit
2 => 2 units
2000 => 2k units
```

It's a combination of `Intl.NumberFormat(locales, {  notation: 'compact',  }` and plural number unit handling.

I'm not sure if there is already a method to do so directly with formatjs, sorry for any bothering.

**Comment by longlho** [comment]
yeah like 
```
{num, plural, 
	one{{num, number, ::compact-short} unit} 
	other{{num, number, ::compact-short} units}
}
```

**Comment by mashirozx** [comment]
Thank you!
