### ISSUE TITLE
Typescript errors when binding multiline objects in Vue components

### ISSUE THREAD

**Issue by yrd** [formatjs/formatjs#3018]
It seems some recent change affected the way TypeScript gets compiled in Vue components. When binding an object the the `class` property, typescript raises some errors. Here is an example: https://github.com/yrd/formatjs-repro/commit/87095d6a3abf16a10d2710360c4789d58e7c0aeb

The App is run by Vue as expected, but extracting messages doesn't work:

```
$ formatjs extract -- 'src/**/*.vue' --id-interpolation-pattern '[sha512:contenthash:base64:6]'
warning Error: src/App.vue:3:7 - error TS1109: Expression expected.

3       }
        ~

{
}
```

In the example, it only fails when the Object bound to `class` spans multiple lines. When replaced with `:class="{ toggled: toggle }"` (in one line), it runs just fine,

I'm not sure which component (or version) exactly is causing this problem. If it helps, it is occuring since I updated as follows (according to my lockfile):
- `@formatjs/cli`: 4.2.16 to 4.2.23
- `babel-plugin-formatjs`: 10.2.15 to 10.3.1
- `@formatjs/ts-transformer`: 3.3.15 to 3.4.4

**Comment by longlho** [comment]
thanks a lot for the repo! We've fixed this in the latest version

**Comment by yrd** [comment]
No problem - thanks!
