### ISSUE TITLE
formatjs extract generates empty file with upgrade to 4.2.24

### ISSUE THREAD

**Issue by heath-freenome** [formatjs/formatjs#3022]
## Which package?
formatjs/cli

## Describe the bug
I have a make file that runs the following command:

```
formatjs extract "src/**/*.{js,jsx}" --ignore="src/{__stories__,__tests__,scaffolding}/**/*.js*" --ignore="src/**/index.js" --out-file "$(OUTPUT_DIR)/lang/en.json" --id-interpolation-pattern '[sha512:contenthash:base64:6]'
```

With version 4.2.21 it was producing a `lang/en.json` file with all of the react-intl strings extracted from my source code, this release generates an essentially empty file (i.e. it contains `{}`)

### Reproducible Steps/Repo

1. Clone this [repo](https://github.com/heath-freenome/busted-format-cli)
2. `npm install`
3. `npm run extract`
4. See the generated `{}`

## Expected behavior
I expect my strings to be extracted from my .js(x) files

## Desktop (please complete the following information):

- OS:Mac OS Big Sur
- Node 14.16.0

## Additional context
If you `npm install --save-def typescript@4` and run it again, things work

**Comment by longlho** [comment]
Do you have a repro?

**Comment by heath-freenome** [comment]
Well there are my company's 3 private repos that all stopped working at the same time... but I haven't had time to build a small test case yet. I was kind of hoping that it was an obvious issue that others have encountered as well

**Comment by longlho** [comment]
hmm we do have integration tests that are supposed to catch these but looks like we missed your case somehow so a repro would be great.

**Comment by heath-freenome** [comment]
@longlho so it turns out that my repos were using typescript@3 rather than typescript@4... Not sure if its possible to detect an unsupported typescript version

**Comment by longlho** [comment]
hmm `@format/cli` has TS4 as ~peerDep so there should have been a warning yeah~ dep so it should have worked. I'm also surprised it doesn't throw an Error straight up. That's an issue on our side.

**Comment by heath-freenome** [comment]
Here's a small [repo](https://github.com/heath-freenome/busted-format-cli) that reproduces it... if you upgrade typescript to @4 it works

**Comment by longlho** [comment]
latest version should have the fix for this
