### ISSUE TITLE
"Missing locale data for locale: "qps-ploc" in Intl.NumberFormat. Using default locale: "en" as fallback."

### ISSUE THREAD

**Issue by LoganDark** [formatjs/formatjs#3024]
## Which package?
`@formatjs/intl`

## Describe the bug
Can't specify locale data for custom locales, or alternatively: [pseudo-locales](https://docs.microsoft.com/en-us/windows/win32/intl/pseudo-locales) are not supported

## To Reproduce
Use a locale formatjs doesn't recognize, such as `qps-ploc`

## Expected behavior
Either I should be able to specify custom locales, or `qps-` locales should be supported natively

## Screenshots
![image](https://user-images.githubusercontent.com/4723091/124161566-6a44cf80-da52-11eb-97a1-dea45a82c6fe.png)

## Desktop (please complete the following information):

- OS: [e.g. iOS] Windows 10 Home 2004
- Browser [e.g. chrome, safari] Google Chrome 91.0.4472.77 (Official Build) (64-bit) (cohort: Stable)

## Additional context
Pseudolocales are extremely useful in development to make sure of two things:

- All text strings in your app are translatable
- All text strings in your app can accept slightly longer strings for languages like German that have long words

Having this error message in the console is not a _problem_, in fact it works out in my favor since it defaults to English, but it's annoying.

**Comment by longlho** [comment]
Take a look at https://formatjs.github.io//docs/tooling/cli/
Base language has to be a real language for number and datetime to work.

**Comment by LoganDark** [comment]
> Take a look at https://formatjs.github.io//docs/tooling/cli/
> Base language has to be a real language for number and datetime to work.

What do you mean "base language"? You mean the `lang` option that I pass to intl as opposed to the messages object?

**Comment by LoganDark** [comment]
Specifying `lang` to `en-US` despite the `messages` object being pseudolocalized seems to have worked, thanks!
