### ISSUE TITLE
Upgrading react-intl from 3.x to 5.x triggers errors involving FormattedMessage/MemoizedFormattedMessage?

### ISSUE THREAD

**Issue by SylvainFI** [formatjs/formatjs#3026]
## Which package?
"react-intl": "^5.20.4"

## Describe the bug
Updating the react-intl package from 3.12.1 to 5.20.4 generates errors when running jest tests with enzyme.

## To Reproduce
in myComp.test.tsx
```
test("test intl upgrade", () => {
   const myComp = shallow(
    <MyComponent 
       prop1="bla"
    />
  );
  expect(myComp).toMatchSnapshot();
});
```

in myComp.tsx
```
const MyComponent: React.FC<IProps> = props => {
   return (
        <FormattedMessage id="MyApp.Description" />
   );
};
```

in en.ts
```
export const English: Record<string, string> = {
    'MyApp.Description': 'This is the description of my app'
};

```

### Reproducible Steps/Repo

```
npm test jest

// outputs:

    -     <FormattedMessage
    +     <MemoizedFormattedMessage
            id="idLabel"
    -       values={Object {}}
/> 
```

it expects MemoizedFormattedMessage instead of FormattedMessage in the snapshots.

I can't find any documentation about MemoizedFormattedMessage.
I don't think updating all my snapshots with MemoizedFormattedMessage is a good idea.

## Desktop

- OS: Windows 10
- Npm: 6.14.6
- Node: 12.18.3
- Jest: 27.0.6
- Enzyme: 3.11.0

Thank you.

**Comment by longlho** [comment]
Yeah we wrap `FormattedMessage` with `React.memo` that's why it has that name. You can update your snapshot files accordingly

**Comment by SylvainFI** [comment]
thank you
