### ISSUE TITLE
The description property of a message as an object

### ISSUE THREAD

**Issue by maciej-gurban** [formatjs/formatjs#3038]
I looked through the code and couldn't find the answer. The docs say that `description` field of message, as defined in defineMessages() can be not only a string, but also an object. Are there any restrictions or suggestions as to what that object should or has to contain? I was wondering whether this would be right way of adding information like max length of a string plus actual description.

**Comment by longlho** [comment]
It is basically `any` and can be used to instruct vendor TMS for things like string length and such. The extraction process should technically not care and just extract that out. LMK if that isn't true.

**Comment by zzt1224** [comment]
when i use a custom format function for extraction, passed in msg do not contain description as object

**Comment by longlho** [comment]
that sounds like a bug then, do you have a repro?

**Comment by rudyorre** [comment]
> It is basically any and can be used to instruct vendor TMS for things like string length and such. The extraction process should technically not care and just extract that out. LMK if that isn't true.

I feel like this should probably be made more obvious in the docs / source code. For now I'm just casting the `description` property to a `string`. Here's the property OP is talking about:

https://github.com/formatjs/formatjs/blob/946d03a2ff4d355a12ff737920276a776721d142/packages/intl/src/types.ts#L264-L268
