### ISSUE TITLE
Loading datetimeformat polyfill changes Intl.DateTimeFormat defaults

### ISSUE THREAD

**Issue by jalik** [formatjs/formatjs#3046]
## Which package?
@formatjs/intl-datetimeformat

## Describe the bug
Before v3.2.1, loading the polyfill for @formatjs/intl-datetimeformat was not changing the current Intl.DateTimeFormat object.
But after that version and until now, loading the polyfill causes the object to be reset with unwanted values.
For example, my browser has this defaults:
```
{
  "locale": "fr-FR",
  "calendar": "gregory",
  "numberingSystem": "latn",
  "timeZone": "Pacific/Tahiti",
  "year": "numeric",
  "month": "2-digit",
  "day": "2-digit"
}
```

But loading the polyfill, changes defaults to:
```
{
  "locale": "en",
  "calendar": "gregory",
  "numberingSystem": "latn",
  "timeZone": "UTC",
  "year": "numeric",
  "month": "numeric",
  "day": "numeric"
}
```

### Codesandbox URL

Working version 3.2.0
https://codesandbox.io/s/react-intl-datetimeformat-polyfill-ym85j?file=/src/App.js

Breaking versions 3.2.1 to 4.1.6 (latest)
https://codesandbox.io/s/react-intl-datetimeformat-polyfill-latest-treec?file=/src/App.js

### Reproducible Steps/Repo

Compare the two sandboxes.
In the working one, both dates are the same.
In the non working one, both dates are different.
The code is the same, only the version of the polyfill is different.

## Expected behavior

Loading the polyfill should not change the defaults of Intl.DateTimeFormat.

## Desktop (please complete the following information):

- OS: KDE neon User Edition 5.22 x86_64 
- Browser Mozilla Firefox
- Version 89.0.2

## Notes

I am aware of this section in the doc https://formatjs.io/docs/polyfills/intl-datetimeformat#default-timezone,
but it feels like a regression bug to me since not only the timezone, but also the locale is changed.

**Comment by longlho** [comment]
yeah we have no way of detecting default locale or anything from the browser (fingerprinting concern) so we basically default to `en`, `UTC`, `latn` and such.

**Comment by jalik** [comment]
@longlho the thing I don't understand is that the polyfill was not doing this before v3.2.1, it is a patch version but it clearly includes breaking changes.

About "having no way of detecting locale from the browser", I am thinking about this:
To get the locale: `navigator.language`
To get the timezone (offset): `new Date().getTimezoneOffset()`

Don't know what to do from here, maybe removing the polyfill...

**Comment by longlho** [comment]
`navigator.language` is different from [DefaultLocale](https://402.ecma-international.org/8.0/#sec-defaultlocale) which is not exposed.
There're many timezones having the same offset.
You can look at https://github.com/formatjs/formatjs/blob/main/packages/intl-datetimeformat/CHANGELOG.md to see the changes. Looks like v3.2.1 adds `formatRange` feature detection which your browser prob doesn't have.
