### ISSUE TITLE
DateTimeFormat formatting stand-alone dates

### ISSUE THREAD

**Issue by BarryThePenguin** [formatjs/formatjs#3067]
## Which package?

`@formatjs/intl-datetimeformat`

## Describe the bug

With the polyfill installed I am seeing the following

```js
new Intl.DateTimeFormat('en-AU', { month: 'short', day: 'numeric' }).format(new Date('2020-6-1'))
// 1 June ✅

new Intl.DateTimeFormat('en-AU', { month: 'short' }).format(new Date('2020-6-1'))
// June ❌ 
```

From what I can see, the expected output should be

```js
new Intl.DateTimeFormat('en-AU', { month: 'short' }).format(new Date('2020-6-1'))
// Jun ✅ 
```

From what I can gather, this may be referring to the [Standalone form](http://cldr.unicode.org/translation/date-time-1/date-time-patterns#TOC-Standalone-vs.-Formatting-in-Flexible-formats) of the value?

https://github.com/formatjs/formatjs/blob/4183fdac6441878198925e60b004af7233b6c2b5/packages/intl-datetimeformat/scripts/extract-dates.ts#L305-L309

Looks to be using the format values, but I can also see `cldr-dates-full` has additional `"stand-alone"` values too 👀 

https://github.com/unicode-org/cldr-json/blob/39205fdc027c935e52a268afcf01cd240f3c442d/cldr-json/cldr-dates-full/main/en-AU/ca-gregorian.json#L59-L102

### Codesandbox URL

https://codesandbox.io/s/stoic-drake-vclo0?file=/src/index.js

### Reproducible Steps/Repo

I was able to reproduce in Firefox v90, and was not able to reproduce in Chrome v92 which I think has the correct implementation

**Comment by longlho** [comment]
Thanks for reporting! While ICU handles this correctly I have to check the spec to see if this is actually possible. It might be a spec bug.

**Comment by BarryThePenguin** [comment]
No worries 👍🏻 Took me a while to understand what was happening..

It would be good to know what the correct behavior should be, then I can test for that and patch it on my end

**Comment by longlho** [comment]
looks like the spec is being vague about it: https://tc39.es/ecma402/#sec-formatdatetimepattern clause `15.f.x`
> Else if f is "narrow", "short", or "long", then let fv be a String value representing v in the form given by f; the String value **depends upon the implementation** and the effective locale and calendar of dateTimeFormat.

**Comment by longlho** [comment]
we'll try to fix this but timeline TBD

**Comment by davidnum** [comment]
any news here?
