### ISSUE TITLE
@formatjs/cli extraction doesn't resolve HTML entities

### ISSUE THREAD

**Issue by SyntaxBlitz** [formatjs/formatjs#3072]
## Which package?
@formatjs/cli

## Describe the bug
Babel transforms HTML entities in JSX props, but these transformations aren't similarly resolved in string extraction. Because the transformation is done by Babel, the React component sees the string with the actual Unicode character inserted; it doesn't do any runtime work to unescape the string, so the extracted `defaultMessage` also needs to include the raw Unicode character.

### Codesandbox URL

https://codesandbox.io/s/upbeat-grass-jo526?file=/src/App.js:153-220

### Reproducible Steps/Repo

Run `npx formatjs extract` on code with an HTML entity in the `defaultMessage` prop, like this:

`<FormattedMessage id="its.here" defaultMessage="It&#8217;s here" />`

This extracts as:

```json
{
  "its.here": {
    "defaultMessage": "It&#8217;s here"
  },
}
```

## Expected behavior
Extracts to

```json
{
  "its.here": {
    "defaultMessage": "It’s here"
  },
}
```

## Additional context
Our workaround for now will probably be to use another representation of the character in the source code, but ideally @formatjs/cli would be able to handle this so we don't have to ban certain (valid) string representations in the codebase.

For reference, [this is the Babel code](https://github.com/babel/babel/blob/b3e2bcda73dea7d68b4c82bfabb92acb11b1ed90/packages/babel-parser/src/plugins/jsx/index.js#L198-L232) that handles this transformation.

**Comment by longlho** [comment]
@formatjs/cli has post-processing after extraction so you can do the conversion there. We don't make assumptions about the string (besides very basic tag support) so it's outside of the core of what we do.

**Comment by SyntaxBlitz** [comment]
@longlho That's what I was thinking at first, but because the transformation is actually happening in Babel (and, implicitly, as part of the JS+JSX language itself), I figured it makes more sense to include by default, because that's the actual "content" of the string literal; this is made evident by the actual Babel translation, which converts the string literal so that it actually contains the Unicode character before it gets passed to React (or _jsx):

```javascript
import { FormattedMessage } from "react-intl";

const A = () => {
        return <FormattedMessage id="a" defaultMessage="a&#8217;b" />;
};

// babel translation:

import { FormattedMessage } from "react-intl";

const A = () => {
  return /*#__PURE__*/React.createElement(FormattedMessage, {
    id: "a",
    defaultMessage: "a\u2019b"
  });
};
```

(TypeScript does this too in [jsx.ts](https://github.com/microsoft/TypeScript/blob/663b19fe4a7c4d4ddaa61aedadd28da06acd27b6/src/compiler/transformers/jsx.ts#L496-L510), and it calls this entity decode function before passing JSX attributes into `factory.createStringLiteral`, unlike @formatjs/ts-transformer).

The Unicode character _is_ correctly extracted when I use a `\u` escape sequence, like `defaultMessage={"a\u2019b"}` (in this case, we need braces around the string, because this escape sequence isn't supported in these `JSXAttributeValue` literals). That makes sense, since the content of the string legitimately includes the Unicode character according to the JS compiler. I think it makes sense to use the same logic for the HTML entity escape inside JSX attributes, since the content of the string also includes the Unicode character according to the JSX compiler(s).

Because the extraction script processes strings differently than Babel/TypeScript, the result is that using the script to extract messages and then passing the generated translation map to an `IntlProvider` will cause components to render differently than if they had just been falling back to `defaultMessage`. I think it would make sense for the extraction script to have an objective of perfectly replicating the `defaultMessage` behavior. This isn't a function of my configuration; it's the canonical content of the string according to the compiler implementation, so it feels like a reasonable "assumption" to make about the string.

In fact, this is a regression from `babel-plugin-react-intl`, which does extract these strings with the Unicode characters inserted.

Thanks for hearing me out!

**Comment by longlho** [comment]
I'm curious why you're using HTML entities instead of unicode?

**Comment by SyntaxBlitz** [comment]
JSX attribute strings don't directly support the `\u` sequence; they use HTML escape sequences so that they behave the same way as normal HTML (like in `<span title="It&#8217;s here"></span>`). Using `\u` requires switching to a JS expression container so I can use JavaScript's string syntax (`<span title={"It\u2019s here"}></span>`). Not only are HTML entities supported, they're the _correct_ (and only) way to include Unicode directly in JSX strings.

Using JS expression containers is tolerable, but in a larger project I would worry that it's not obvious why the code is written like this; I don't want to risk other developers coming along and making changes without realizing that we're using an obscure syntax as a workaround for the inconsistent FormatJS extraction. This also adds another restriction preventing HTML from being copy-pasted directly into JSX (which is mostly fine to do, save for a few exceptions like self-closing tags, `className`, and `htmlFor` imposed by JSX).

Indeed my biggest concern is that it adds extra complexity to i18n onboarding for other developers; it's just one more thing I have to make sure everyone on the team knows before localizing their code. I'm looking to futureproof the process, and for me that means ideally the extraction process will be able to handle any syntax a developer will want to use in their own corner of the codebase, whether that's HTML entities or JS-style Unicode escapes, without having to spend too much time learning the trivialities of the i18n infrastructure. Since i18n is something that tends to make its way into every part of an application, every quirk needs to be communicated to every developer on a project, which adds more potential points of failure.

**Comment by longlho** [comment]
kk that's fair, I'd be open to having this behavior opt-outable in the CLI. PR's always welcome ofc.
