### ISSUE TITLE
Is there any method for translating strings coming from the backend?

### ISSUE THREAD

**Issue by JimmyBlundell** [formatjs/formatjs#3080]
This is more of a question I'm searching for an answer for. We are i18n-ing our application, and it's rather large. We have a lot of strings that we display that come from responses, or are given directly from the backend (some tables, for example, are html served up from the backend. This occurs in some older places in our app).<br>
Is there any possible way to get such strings translated? Let's say I have a simple toast that displays some message from a response:<br>
```
toast.success(response?.data?.message);
```
We do many such things across our app, but I'm not seeing a way to utilize formatjs to translate such strings. Might there be another method / recommendation, or is there indeed a way to do so that I'm missing?

**Comment by longlho** [comment]
nope strings have to be declared statically. If those strings come from BE they have to be translated already.
