### ISSUE TITLE
Numeric tags trigger syntax error in @formatjs/icu-messageformat-parser

### ISSUE THREAD

**Issue by kachkaev** [formatjs/formatjs#3083]
## Which package?
@formatjs/icu-messageformat-parser

## Describe the bug

I’m using [`react-i18next`](https://www.npmjs.com/package/react-i18next) and [`i18next-icu`](https://www.npmjs.com/package/i18next-icu), the latter of which [mentions](https://github.com/i18next/i18next-icu/blob/324e4df034a153c9bdf08d461c6d3382b59d163c/package.json#L18) `"intl-messageformat": "^9.0.0"` as a peer dependency. Here is how my translation file and its usage look like:

```js
{
  "myMessage": "<0>Hello</0> <1>world</1>"
}
```

```jsx
<Trans i18nKey="myMessage"><CustomComponentA /><CustomComponentB someProp={42} /></Trans>
```

_See [docs on `<Trans />` component](https://react.i18next.com/latest/trans-component) where numeric tags are justified_

To parse I18n messages, `react-i18next` [calls](https://github.com/i18next/i18next-icu/blob/324e4df034a153c9bdf08d461c6d3382b59d163c/src/index.js#L62-L66) `new IntlMessageFormat`, which in turn uses [`parse()`](https://github.com/formatjs/formatjs/blob/41159d780ea37c9af0d6137ff2dcb559c120c8a4/packages/icu-messageformat-parser/index.ts#L36) from `@formatjs/icu-messageformat-parser`. When `react-i18next` invokes the ICU parser, it passes `{ ignoreTag: true }` and then ‘opens’ the tags separately via [`html-parse-stringify`](https://www.npmjs.com/package/html-parse-stringify). All works fine.

I was writing a small linting script for my translation files and decided to use `@formatjs/icu-messageformat-parser` as a validator of the ICU messages. It turned out that strings like `"<0>Hello</0> <1>world</1>"` ended up throwing `SyntaxError: UNMATCHED_CLOSING_TAG`. This looks like a bug to me.

## To Reproduce

https://codesandbox.io/s/long-platform-d63z8?file=/pages/index.js

### Option A (numeric tags are completely ignored)

Given that an opening tag is already ignored, a closing tag is also ignored and so there is no syntax error. The resulting AST for `<0>Hello</0>` is:

```
[{"type":0,"value":"<0>Hello</0>"}]
```

### Option B (numeric tags are supported)

In this scenario, `parse()` returns the same result for numeric tags as for ‘normal’ tags. The resulting AST for `<0>Hello</0>` is:

```
[{"type":8,"value":"0","children":[{"type":0,"value":"Hello"}]}]
```

Option B would even `@formatjs/icu-messageformat-parser` with [`html-parse-stringify`](https://www.npmjs.com/package/html-parse-stringify) and [`format-message`](https://www.npmjs.com/package/format-message), both of which already support numeric tags.

To achieve this behaviour, we’ll need to replace [`_isAlpha`](https://github.com/formatjs/formatjs/blob/41159d780ea37c9af0d6137ff2dcb559c120c8a4/packages/icu-messageformat-parser/parser.ts#L1298) with `_isAlphaNumeric`. I’m happy to submit a PR with the fix if nobody sees any downsides  🙂

In the meantime, I’m using `format-message` for my small linting script. It works fine, but because the implementation is different, there may be some edge case discrepancies between the linter and the actual app.

**Comment by longlho** [comment]
`<0></0>` unfortunately is not a valid tag name (spec: https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name) so IMO react-i18next should fix this on their side. If the rationale is to display the index I think `<i0>` would work (or `[a-z]0` is also valid). 
cc @jamuhl

**Comment by jamuhl** [comment]
It's a string that looks like HTML -> it's not HTML!!! It's a string that gets converted to react elements.

If the current parser has issues with that - there is not much we can do (i18next has it's own syntax - using ICU message format is just an option).

Workaround...do not use the numbered tags - use the named once we added few months ago, like: https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0

**Comment by kachkaev** [comment]
Thanks for pointing to the new named tags feature @jamuhl 🙌 That's definitely a good way around numeric tags in `react-i18next`!

@longlho thanks for your reply too! AFAIU the issue with numeric tags is somewhat disconnected from `react-i18next.` I’ve mentioned that library to explain how I have found the problem, but it exists even in isolation.

If the decision is to not support numeric tags in `@formatjs/icu-messageformat-parser`, I’d expect both `<0>` and `</0>` to be parsed as ‘normal text’. However, it looks like there is some asymmetry in the behaviour at the moment. An opening tag is treated as text, while a closing tag makes the parser throw an exception.

| input | current output | expected output
|---|---|---|
| `<span>Hello</span>` | `[{"type":8,"value":"span","children":[{"type":0,"value":"Hello"}]}]` | ✅ same
| `<span>Hello` | `SyntaxError: UNCLOSED_TAG` | ✅ same
| `<0>Hello` | `[{"type":0,"value":"<0>Hello"}]` | ✅ same
| `<0>Hello<0>` | `[{"type":0,"value":"<0>Hello<0>"}]` | ✅ same
| `<0>Hello</0>` | `SyntaxError: UNMATCHED_CLOSING_TAG` | ⚠️ `[{"type":0,"value":"<0>Hello</0>"}]`
| `</0>Hello` | `SyntaxError: UNMATCHED_CLOSING_TAG` | ⚠️ `[{"type":0,"value":"</0>Hello"}]`

Sandbox link: https://codesandbox.io/s/formatjsformatjsissues3083-d63z8

I understand that we are dealing with a very rare edge case here 🙂 WDYT?

**Comment by longlho** [comment]
I do see some inconsistent behavior here but at the same time this behavior is basically unspecced so it's basically non-deterministic and can change anytime.
```js
let span = document.createElement('span')
span.innerHTML = '<0>bar</0>' // <span>"<0>bar"<!--0--></span>
span.innerHTML = '<0>bar<0>' // <span>"<0>bar<0>"</span>
span.innerHTML = '<0>bar' // <span>"<0>bar"</span>
span.innerHTML = '</0>bar' // <span><!--0-->"bar"</span>
```

**Comment by kachkaev** [comment]
Hmmm that’s interesting! Would you say that it’s fair to throw an exception when stumbling upon `</0>` then? Assuming that numeric tags are not supported, having `</0>` in input seems to be quite useless 🤔

Just tried the above snippet in FF, the result is the same (`<!--0-->` for `</0>`) 👀

**Comment by longlho** [comment]
I think my point is that unfortunately throwing or not throwing is basically the same because it is unspec'ed and is subject to change version to version. I can technically throw right now but will not commit to having that as part of the API expectation.

**Comment by kachkaev** [comment]
IC. Feel free to close this issue if you don’t think that it can be actioned on 👍 My practical problem has been solved by jamuhl’s suggestion to [use component lookup in `<Trans />`](https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0), so this issue has moved to a theoretical ream (at least for me). Good to have it though for the future reference 🙂
