### ISSUE TITLE
FormattedPlural not works as expect.

### ISSUE THREAD

**Issue by poc7667** [formatjs/formatjs#3085]
## Which package?
"react-intl": "^5.20.6"

## Describe the bug

I always get the same value (5 clicks) from FormattedPlural component.
Even, manually put the value manually.

Is this a bug? If not, any possible to improve the API format design. So ambigous.

```
<IntlProvider locale={locale} messages={messages} defaultLocale="en-US">
            <FormattedPlural value={0} zero="no click" one="1 click" other="5 clicks" />
<IntlProvider/>
```

**Comment by longlho** [comment]
I think you're misunderstanding what `zero` means. `zero` is a plural category and for English, when you specify `0` it's `0 clicks` (same as plurality of `5 clicks`) so `0` is of `other` category, not `zero` category.
The doc should clarify that for you: https://formatjs.io/docs/core-concepts/icu-syntax#plural-format
