### ISSUE TITLE
ecma402-abstract type error in v5

### ISSUE THREAD

**Issue by tofutree23** [formatjs/formatjs#3093]
I'm using react-intl and I'm going to upgrade from 3.12.1 to 5.20.6. Everything seemed fine, but when I build a project through yarn build, the error as the image below appears. How do I fix it?

For your information, I am using the react 17.0.2 version.

![B803A43B-BFAD-4C55-8E7E-28FDA828F0EF](https://user-images.githubusercontent.com/44552838/127959334-3a5df0f8-3c88-4038-b15e-94e300ab5f0f.png)

**Comment by longlho** [comment]
seems like you're using an old version of `typescript`?

**Comment by tofutree23** [comment]
@longlho true. Thanks. I updated Typescript to 4.3.5, and there's no more problem. 😓
