### ISSUE TITLE
Extract cli command not saving to json file

### ISSUE THREAD

**Issue by cesarvarela** [formatjs/formatjs#3107]
## Which package?
@formatjs/cli": "^4.2.30

## Describe the bug
Seems like when I run the extract command as the documentation says the JSON file with the ids/translations doesn't get updated

## To Reproduce

I've got this component in my `index.js`

```jsx
 <FormattedMessage id="landing-title" description="Welcome" />
```

Added this to the `scripts` section on my package.json: 

```json
    "extract": "formatjs extract -- 'src/**/*.js*' --out-file i18n/react-intl/es.json --id-interpolation-pattern '[sha512:contenthash:base64:6]'"
```

And then I run:

```sh
npm run extract
```

The command output shows this:

```sh
> formatjs extract -- 'src/**/*.js*' --out-file i18n/react-intl/es.json --id-interpolation-pattern '[sha512:contenthash:base64:6]'

{
  "landing-title": {
    "description": "Welcome "
  }
}
```

but my `i18/react-intl/es.json` remains empty.

## Expected behavior
I guess it should add new extracted keys?

## Desktop (please complete the following information):

- OS: Windows 11

**Comment by longlho** [comment]
you should drop the `--` after `extract`

**Comment by cesarvarela** [comment]
thanks
