### ISSUE TITLE
Compiling translated files in a merge fashion?

### ISSUE THREAD

**Issue by JimmyBlundell** [formatjs/formatjs#3113]
With our approach, we are trying to keep the extracted translation files right next to the component they're used in. For example:<br>
|- packages
|- components
. . . .|- component1
. . . . . .|- lang
. . . . . . . .|-en-US.json
. . . . . . . .|-pt-BR.json
. . . .|- component2
. . . . . .|- lang
. . . . . . . .|-en-US.json
. . . . . . . .|-pt-BR.json
. . . .|- component3
. . . . . . .|- lang
. . . . . . . .|-en-US.json
. . . . . . . .|-pt-BR.json
|- compiledLangues'
. . . .|- en-US-compiled.json
. . . .|- pt-BR-compiled.json
<br>
So despite keeping our extracted translation files next to the component that we get the strings from, I'd still like to compile these translations files into one big compilation file that I can pass to the top of my app.<br>
We split it up this way as we have volunteers within the company that are doing the translations for us- no actual 3rd party service. Therefore, we can't give them one giant file of 2000+ strings. So to re-itereate, I'd like to take all these files and essentially aggregate them when compiling to result in one large compiled json which I pass to the root of my app. Is there a way to do this that I'm missing, perhaps? I get nervous having to manually merge these files, plus it's just more overhead for the devs.

**Comment by longlho** [comment]
looks like we already supported combining multiple translation files
```
Usage: formatjs compile [options] <translation_files>

Compile extracted translation file into react-intl consumable JSON
We also verify that the messages are valid ICU and not malformed.
<translation_files> can be a glob like "foo/**/en.json"

Options:
  --format <path>                 Path to a formatter file that converts `<translation_file>` to `Record<string, string>`
  so we can compile. The file must export a function named `compile` with the signature:
  \`\`\`
  type CompileFn = <T = Record<string, MessageDescriptor>>(
    msgs: T
  ) => Record<string, string>;
  \`\`\`
  This is especially useful to convert from a TMS-specific format back to react-intl format

  --out-file <path>               Compiled translation output file.
                                  If this is not provided, result will be printed to stdout
  --ast                           Whether to compile to AST. See https://formatjs.io/docs/guides/advanced-usage#pre-parsing-messages
                                  for more information
  --skip-errors                   Whether to continue compiling messages after encountering an error. Any keys with errors will not be included in the output file.
  --pseudo-locale <pseudoLocale>  Whether to generate pseudo-locale files. See https://formatjs.io/docs/tooling/cli#--pseudo-locale-pseudolocale for possible values.
                                  "--ast" is required for this to work.
  -h, --help                      display help for command
```

**Comment by batjaa** [comment]
I don't think this combines multiple files in under the same locale into a single resource file.
