### ISSUE TITLE
Confusion between types and documentation for FormattedMessage Function as the child

### ISSUE THREAD

**Issue by ilyagru** [formatjs/formatjs#3117]
## Which package?
Since this is a monorepo. Please specify which package this bug report is for.

react-intl 5.20.8

## Describe the bug

There is confusion between 
- TypeScript types and 
<img width="500" alt="Screenshot 2021-08-16 at 15 13 47" src="https://user-images.githubusercontent.com/18074511/129562275-dd060783-4a03-4809-8931-03173e9d53e2.png">

- documentation for the `FormattedMessage` render function.
https://formatjs.io/docs/react-intl/components/#function-as-the-child
<img width="500" alt="Screenshot 2021-08-16 at 15 16 18" src="https://user-images.githubusercontent.com/18074511/129562382-0e4243b0-557b-42bb-84ab-5d94912de1c8.png">

It seems it should be 

```
children?(nodes: React.ReactNodeArray): React.ReactElement | null;
```

because otherwise if using it like so

```tsx
<FormattedMessage
  id="..."
  defaultMessage="..."
  values={{...}}
>
  {(...chunks) => {
    return chunks.map(chunk) => React.cloneElement(chunk, { key: index });
  }}
</FormattedMessage>
```

 might produce an error _Element type is invalid: expected a string ... but got undefined_.

### Codesandbox URL

Please include a codesandbox URL if possible

**Comment by longlho** [comment]
thanks for reporting, latest version should have the fix for this :)

**Comment by ilyagru** [comment]
@longlho Awesome, thanks! What is the version which includes the fix?

**Comment by longlho** [comment]
react-intl@5.20.9

**Comment by popuguytheparrot** [comment]
The error is still in 5.20.10
