### ISSUE TITLE
Remove tslib from dependencies in package.json

### ISSUE THREAD

**Issue by Dangoo** [formatjs/formatjs#3121]
## Which package?
- @formatjs/ecma402-abstract
- @formatjs/fast-memoize
- @formatjs/icu-messageformat-parser
- @formatjs/icu-skeleton-parser
- @formatjs/intl-localematcher
- intl-messageformat

## Describe the bug
Hello, when upgrading `@react-spectrum/overlays@3.7.1` to `3.7.2` we saw that `tslib@2.1.0` is all of a sudden being included in the webpack bundle output - probably since referenced by some of the above packages.

I couldn't find which package exactly is actually referencing/importing `tslib` at runtime, but why is it necessary to have it in the dependencies list at all?

The dependency chain is the following:
- @react-aria/overlays
- @react-aria/i18n
- @internationalized/message
- intl-messageformat (and others from above)
- tslib

## Screenshots
![image](https://user-images.githubusercontent.com/1252204/129760897-426de99a-d9bc-44ab-bffe-71b638d0f934.png)

## Desktop (please complete the following information):

- OS: OSX/Ubuntu

## Additional context
Similar request: #2620

**Comment by longlho** [comment]
tslib is a runtime requirement from typescript (that polyfills things like spread and import interop) so basically it's always needed
