### ISSUE TITLE
Missing prop definition in React components

### ISSUE THREAD

**Issue by ksocha** [formatjs/formatjs#3130]
## Which package?
react-intl 5.20.10

## Describe the bug
I've noticed that after latest changes (specifically linked to #3122, using native DateTimeFormatOptions instead of custom one) causes type errors in TypeScript project.
Seems that properties such as `hourCycle`, `dateStyle`, `timeStyle` are not longer valid, TS reports errors if any of them is being used. However, the components are still working as expected, so this must be types definitions bug.

### Codesandbox URL

https://codesandbox.io/s/eager-kirch-t7jj3?file=/src/App.tsx

## Expected behavior
TS does not report errors if listed properties are being used.

**Comment by longlho** [comment]
Do you have esnext.intl in your tsconfig lib?

**Comment by ksocha** [comment]
@longlho Thanks for reply!
I did not, however, setting this does not help.
I've also done the same in the sandbox example above and it does not help either.

**Comment by longlho** [comment]
@ksocha looks like that was using older version of TS. TS@4.3+ ES2020.intl does have `hourCycle`: https://unpkg.com/browse/typescript@4.3.5/lib/lib.es2020.intl.d.ts

**Comment by ksocha** [comment]
@longlho Thanks, but changing TS to the newest version (4.3.5 atm) does not help either. As you can see in the sandbox.

**Comment by longlho** [comment]
The sandbox version is locked at 4.1.2 for some reason. I verified it locally.

**Comment by ksocha** [comment]
That indeed works, but shouldn't enforcing users to update TS/TS config be considered as a breaking change? And as such, shouldn't this change cause a major version bump to indicate this?

**Comment by longlho** [comment]
It's tricky because literally most type changes are breaking in some fashion. In general we don't bump major for type changes. We can bump `TS` requirements but that's a devDep so that won't help.
