### ISSUE TITLE
Type Errors with Angular app

### ISSUE THREAD

**Issue by godhand1607** [formatjs/formatjs#3133]
## Which package?
- `intl-messageformat@9.9.1`

## Describe the bug
- We have an Ionic Angular app and we are in the process of upgrading to the latest stable Angular version which is 12. After fixing the other issues/deprecations we are seeing a build error on the int-messageformat plugin. 

### Reproducible Steps/Repo

1. Clone this repo https://github.com/godhand1607/ionic-angular-intl-messageformat-issue
2. Run `npm install`
3. Run `npm start`
4. See the build error

## Screenshots
![Screen Shot 2021-08-26 at 11 04 13 AM](https://user-images.githubusercontent.com/7845870/130894164-db4dc083-3634-4f7d-814d-38812b16738b.png)

## Additional context
1. As seen on this [commit](https://github.com/godhand1607/ionic-angular-intl-messageformat-issue/commit/a85b27acaff89c0cf71260fc583488600bb0e1f5), we've tried the fix as suggested in https://github.com/formatjs/formatjs/issues/1593 but it still doesn't work
2. If we comment out [this line](https://github.com/godhand1607/ionic-angular-intl-messageformat-issue/commit/a85b27acaff89c0cf71260fc583488600bb0e1f5#diff-884f7f49640e5923f6bcac4c51d90340330a178f662defbe61e5f5aac1c512deR3), the app builds properly so we are sure that the cause is within the plugin

**Comment by longlho** [comment]
you need latest typescript, `es2018.intl`, `es2020.intl`, `esnext.intl`

**Comment by godhand1607** [comment]
Thanks @longlho , that fixed it. Didn't need to update to the latest typescript (or maybe i am on it already), i just included all 3 intl libs in tsconfig
