### ISSUE TITLE
Issue in the documentation for `Core FormatJS Intl`

### ISSUE THREAD

**Issue by mahyarmirrashed** [formatjs/formatjs#3134]
I believe I found an error on the docs: https://formatjs.io/docs/intl/

`-S` is not an option for `yarn` AFAIK. This might have been a misclick for `-D` which makes more sense.

**Comment by mahyarmirrashed** [comment]
Same with the installation command for `npm` I believe.

**Comment by longlho** [comment]
yup that was bad copy pasta for `yarn`. `npm i -S` is the same as `npm i --save`. PR's welcome as well if you're interested :)
