### ISSUE TITLE
Move @types/react from deps to devDeps 

### ISSUE THREAD

**Issue by kyriiherman** [formatjs/formatjs#3138]
## Which package?
react-intl

## Describe the bug
I use react v16 so I don't need @types/react v17 in my node_modules. And since react-intl is compatible with react v16 and v17 I think it's not a problem to move it to devDeps.

**Comment by longlho** [comment]
is this causing a compilation issue?

**Comment by kyriiherman** [comment]
Yes, I have types/react@16 the the root of node_modules and there is a bug in TS that in such cases I have to set the path to types explicitly in tsconfig if these types are not in the node_modules/@types folder
[
<img width="1165" alt="Screenshot 2021-09-09 at 17 06 13" src="https://user-images.githubusercontent.com/9069967/132701528-2547cbfa-8b9d-4894-a99f-35d472740967.png">
](url)

**Comment by longlho** [comment]
do you have a codesandbox?

**Comment by kyriiherman** [comment]
No, this problem can't be reproduced in code sandbox, but I found an original issue: https://github.com/microsoft/TypeScript/issues/42873. 
Do you need typings for React@17 in dependencies for any reason?

**Comment by longlho** [comment]
Yeah we rely on react types for a bunch of stuff

**Comment by kyriiherman** [comment]
I mean why these types can't be moved to devDependencies? And according to package.json react-intl can be used with react@16 as well: https://github.com/formatjs/formatjs/blob/c4d2f6a9676d455b3be8a742e4eb901ce97b8df6/packages/react-intl/package.json#L143

**Comment by longlho** [comment]
because if you use TS and you use react-intl, we reference react types
