### ISSUE TITLE
Incorrect parsed results when a string has an apostrophe next to a tag

### ISSUE THREAD

**Issue by cungminh2710** [formatjs/formatjs#3142]
## Which package?
@formatjs/icu-messageformat-parser version 2.0.11

## Describe the bug
When a string with arguments has an apostrophe next to a tag, only literal string is returned 

For example:

Both: 
- `parser.parse("Veuillez contacter l'<a>assistance {0}</a>.")`
- `parser.parse("Veuillez contacter l'<a>assistance {0}</a>.", {ignoreTag: true})` 
 
return:

`[{"type":0,"value":"Veuillez contacter l<a>assistance {0}</a>."}]`

### Codesandbox URL

https://codesandbox.io/s/small-lake-892eq?file=/src/index.js

## Expected behavior

Arguments should be returned correctly

For example, expected results for this string `Veuillez contacter l'<a>assistance {0}</a>.`:

`[{"type":0,"value":"Veuillez contacter l'"},{"type":8,"value":"a","children":[{"type":0,"value":"assistance "},{"type":1,"value":"0"}]},{"type":0,"value":"."}]`

**Comment by longlho** [comment]
Apostrophe is the escape character for icu message format. See https://formatjs.github.io//docs/core-concepts/icu-syntax for more info
