### ISSUE TITLE
Errors when parsing strings with non-breaking spaces

### ISSUE THREAD

**Issue by cungminh2710** [formatjs/formatjs#3144]
## Which package?
@formatjs/icu-messageformat-parser v2.0.11

## Describe the bug
Some languages like Korean require non-breaking spaces in strings to correctly display the wording intent. 

- `@formatjs/icu-messageformat-parser@2.0.11` yields errors on strings with non-breaking spaces.
- `intl-messageformat-parser@6.4.4` gives these strings a pass

### Codesandbox URL

https://codesandbox.io/s/small-lake-892eq?file=/src/index.js

To see non-breaking spaces, simple search (Ctrl+F) for regex `\xa0`

## Expected behavior
No error should be given

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
Non-breaking spaces can be used in message literal, not ICU syntax clauses, e.g:
`Pro {0, plural, one {# člena}\xa0few\xa0{# členy} many {# členů} other {# členů}}` is not valid
`Pro {0, plural, one {#\xa0člena} few{#\xa0členy} many {#\xa0členů} other {#\xa0členů}}` is valid

ICU syntax clauses don't get printed out so it doesn't matter if it's i18n-safe.

**Comment by cungminh2710** [comment]
cc @b3n
