### ISSUE TITLE
Percentage and currency use the wrong white space

### ISSUE THREAD

**Issue by gossi** [formatjs/formatjs#3145]
## Which package?
`@formatjs/intl-numberformat`

## Describe the bug
Percentage and currency style use the wrong whitespace width to separate the symbol from the formatted number. They use a _normal_ width whitespace, whereas a thin white space shall be used.

Notes:

- I'm seeing this with [`ember-intl`](https://github.com/ember-intl/ember-intl) (which uses formatjs under the hood).
- I'm seeing this on _german_ - but I think typography rules are the same/ssimilar in other languages, too.

### Codesandbox URL

https://codesandbox.io/s/hungry-darkness-b06pr?file=/src/index.js

## Expected behavior

Formatted outputs look like this:

```
1.000,00&#8239;€
45&#8239;%
```

## Additional context

Some wikipedia articles on this one:

The best one is in german to be honest. You don't need to understand german for this. Have a look at the first table there, it's explaining it very well: https://de.wikipedia.org/wiki/Schmales_Leerzeichen

More english references

- https://en.wikipedia.org/wiki/Whitespace_character
- https://en.wikipedia.org/wiki/Non-breaking_space
- https://en.wikipedia.org/wiki/Thin_space

**Comment by longlho** [comment]
This comes from CLDR https://github.com/unicode-org/cldr-json/blob/master/cldr-json/cldr-numbers-modern/main/de/numbers.json#L101 so I think you gotta submit an issue there.
