### ISSUE TITLE
FormatDate returning for some locale as M09, M08 (M + month number) only on android

### ISSUE THREAD

**Issue by erAdnan** [formatjs/formatjs#3153]
- on using formatDate for some locale the month name is coming as M01, M02.... anyone face this issue? or any solution to this?
- i had fixed for one Mongolia locale using jsc-android library but it again reported for other locale (Norway). it may be reported for some other locale as well. 
- any permanent fix to this?

**Comment by adnana-hrbl-v** [comment]
> * on using formatDate for some locale the month name is coming as M01, M02.... anyone face this issue? or any solution to this?
> * i had fixed for one Mongolia locale using jsc-android library but it again reported for other locale (Norway). it may be reported for some other locale as well.
> * any permanent fix to this?

- need fix for this

**Comment by longlho** [comment]
You can use our polyfill @formatjs/intl-datetimeformat or https://github.com/react-native-community/jsc-android-buildscripts#international-variant

**Comment by adnana-hrbl-v** [comment]
> You can use our polyfill @formatjs/intl-datetimeformat or https://github.com/react-native-community/jsc-android-buildscripts#international-variant

I am using this already, it resolved for Mongolia locale, but for Norway locale its not working.

**Comment by longlho** [comment]
Which one r you using?

**Comment by adnana-hrbl-v** [comment]
> Which one r you using?

https://github.com/react-native-community/jsc-android-buildscripts#international-variant

jsc-android, I am using

**Comment by longlho** [comment]
looks like you should submit a GH issue over at that repo

**Comment by adnana-hrbl-v** [comment]
> looks like you should submit a GH issue over at that repo

raised. commenting here for relating the issues:
https://github.com/react-native-community/jsc-android-buildscripts/issues/156#issue-992369255

**Comment by longlho** [comment]
In the mean time you can use our polyfill if necessary

**Comment by adnana-hrbl-v** [comment]
> In the mean time you can use our polyfill if necessary

thanks, will try using polyfill, I had tried earlier with polyfill but it didn't worked, hence I used jsc-android. will try again.
