### ISSUE TITLE
FormattedMessage children is Breaking types

### ISSUE THREAD

**Issue by popuguytheparrot** [formatjs/formatjs#3180]
### Discussed in https://github.com/formatjs/formatjs/discussions/3179

<div type='discussions-op-text'>

<sup>Originally posted by **popuguytheparrot** September 23, 2021</sup>
How to fix Error with types ReactNodeArray? Its breaking, but i dont find major update

```jsx
<FormattedMessage id='loginForm.enterPassword'>
                    {(msg) => (
                        <Input
                            onChange={(event, data) => setCredential({ ...credential, password: data?.value || null })}
                            placeholder={msg}
                            value={password || ''}
                            type='password'
                        />
                    )}
                </FormattedMessage>
```

**Comment by longlho** [comment]
do you have a repro codesandbox or sum?

**Comment by popuguytheparrot** [comment]
@longlho https://codesandbox.io/s/peaceful-bouman-ux0ro?file=/src/App.tsx

**Comment by longlho** [comment]
looks like you should have used `intl.formatMessage` in this case instead. The reason it's returning `ReactNodeArray` is because if it's rich text then we actually return text + `ReactNode`

**Comment by popuguytheparrot** [comment]
@longlho do you suggest using a hook that will re-render all components instead of isolated rendering?

**Comment by longlho** [comment]
I mean you can use useIntl hook in the parent and use intl.formatMessage.

**Comment by popuguytheparrot** [comment]
This is not a solution to the problem

**Comment by longlho** [comment]
https://codesandbox.io/s/modest-mclean-ql6rk?file=/src/App.tsx why not?

**Comment by popuguytheparrot** [comment]
Hmm. I extended example with WDYR and check the **placeholder** reference is preserved

https://codesandbox.io/s/ecstatic-morning-mji6q?file=/src/App.tsx

**Comment by longlho** [comment]
hmmm it's not preserved, if you wanna cache it you can use `useMemo` or such. Why is this a problem I guess? `intl.formatMessage` is cheap.

**Comment by popuguytheparrot** [comment]
the codebase is getting more complex because places with different behavior are created on top of the tool

**Comment by longlho** [comment]
again, we don't have any guarantee `intl.formatMessage` returns the same reference. I'm not sure what you're looking for specifically.
