### ISSUE TITLE
Unable to extract messages from Vue.js SFCs using script setup syntax

### ISSUE THREAD

**Issue by glen-84** [formatjs/formatjs#3181]
## Which package?
@formatjs/cli

## Describe the bug
Since switching to [script setup syntax](https://v3.vuejs.org/api/sfc-script-setup.html) in our Vue.js SFCs, it seems as though `@formatjs/cli` is unable to extract messages from the script blocks.

### Codesandbox URL

It won't be possible to test extraction here (I don't think), but I can create a simple test repo if that helps.

### Reproducible Steps/Repo

1. Create a Vue.js project with a component that uses script setup syntax.
2. Use `intl.formatMessage(...)` in that code.
3. Try to extract the messages using `formatjs extract`.

## Expected behavior
All messages should be extracted.

## Screenshots
n/a

## Desktop (please complete the following information):

- OS: Windows
- Browser: n/a
- Version: n/a

## Smartphone (please complete the following information):

- Device: n/a
- OS: n/a
- Browser: n/a
- Version: n/a

## Additional context

n/a

**Comment by longlho** [comment]
do you have a sample repo I can check out?

**Comment by glen-84** [comment]
https://github.com/glen-84/formatjs-extract-issue

`npm run extract` -> `src/lang/en-gb.json` (only shows 1 of the 2 messages).
