### ISSUE TITLE
react-intl.iife.js is broken at 5.20.12 (5.20.11 is fine)

### ISSUE THREAD

**Issue by or-else** [formatjs/formatjs#3188]
## Which package?

react-intl.iife.js

## Describe the bug
```
react-intl.iife.js:747 Uncaught ReferenceError: __window is not defined
    at react-intl.iife.js:747
    at react-intl.iife.js:3584
```

## To Reproduce

Try using https://cdn.jsdelivr.net/npm/react-intl@5.20.12/react-intl.iife.js (5.20.11 is fine). The crash is immediate.

## Desktop (please complete the following information):

Chrome Version 93.0.4577.82 (Official Build) (x86_64) on Mac

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
