### ISSUE TITLE
Does formatjs support ICU69?

### ISSUE THREAD

**Issue by longlho** [formatjs/formatjs#3191]
### Discussed in https://github.com/formatjs/formatjs/discussions/3190

<div type='discussions-op-text'>

<sup>Originally posted by **b0g3r** September 28, 2021</sup>
I tried to use `trailingZeroDisplay` from [ICU69](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4j/com/ibm/icu/number/NumberFormatter.TrailingZeroDisplay.html), but found it doesn't work with formatjs intl-messageformat. Do you have any plans to implement it?
</div>

**Comment by anton-yakovlev** [comment]
Hello! trailingZeroDisplay is working now for numbers, thank you. But when I try to use in with currency it still doesn't work. For example `{cents, number, ::.##/w scale/0.01 current/USD}`. Do you have any plans to fix it too?

**Comment by longlho** [comment]
do you mean `currency/USD`?

**Comment by anton-yakovlev** [comment]
Yes, right

**Comment by longlho** [comment]
can you make a new GH issue btw? this keeps slipping from my inbox
