### ISSUE TITLE
FRACTION_PRECISION_REGEX doesn't detect some valid skeletons

### ISSUE THREAD

**Issue by BigBadAlien** [formatjs/formatjs#3193]
## Which package?
icu-skeleton-parser

## Describe the bug

```
const msg = new IntlMessageFormat('{value, number, ::.####}').format({
  value: 1234.12345678901,
});
console.log(msg);
```

The result is `1,234.123` but must be `1,234.1234`

## Additional info

According to [the docs](https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html#fraction-precision)

> Note that the stem . is considered valid and is equivalent to precision-integer.

`.` is a valid skeleton as well as `.#`, but the regexp [FRACTION_PRECISION_REGEX](https://github.com/formatjs/formatjs/blob/31345e4c103c3dbd0f33d1c852fa4210b8b382b2/packages/icu-skeleton-parser/number.ts#L46) doesn't detect it.

```
const FRACTION_PRECISION_REGEX = /^\.(?:(0+)(\*)?|(#+)|(0+)(#+))$/g
```

```
(/^\.(?:(0+)(\*)?|(#+)|(0+)(#+))$/g).test('.#')
```
is `false` but expected `true`

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
@BigBadAlien I added test and looks like `.` & `.##` works just fine.
```
/^\.(?:(0+)(\*)?|(#+)|(0+)(#+))$/g.test('.#') // return true
```

**Comment by BigBadAlien** [comment]
Looks like we use an outdated version (7.8.4) and my initial description is wrong, we have the constant

```
const FRACTION_PRECISION_REGEX = /^\.(?:(0+)(\+|#+)?)?$/g;
```

Sorry for the confusion.

ok, thanks for the feedback and tests
