### ISSUE TITLE
Can not use a typescript formatter

### ISSUE THREAD

**Issue by abderrahmaneMustapha** [formatjs/formatjs#3200]
## Used package
[@formatjs/cli](https://www.npmjs.com/package/@formatjs/cli)

## Describe the bug
for example when try to run formatjs extract src/apps/main/**/*.ts* --out-file  extracted.json --id-interpolation-pattern '[sha512:contenthash:base64:6]' --format formatter.ts

formatter.ts : 
```
exports.format = function (msgs : any[]) {
    const results :  any[] =[]
    for(const [id, msg] of Object.entries(msgs)) {
      results.push({
        id : id,
        defaultMessage: msg.defaultMessage,
        description: msg.description,
      })
    }
    return results
  }
```

**i get this error  :** 
SyntaxError: Unexpected token ':'

## To Reproduce
just follow the steps mentioned in the  bug descritption part

all i want is to use a typescript formatter

## Desktop (please complete the following information):

- OS: Windows
- Browser:  Chrome
- Version:  94.0.4606.61

**Comment by longlho** [comment]
yeah u'd have to transpile your formatter code.
