### ISSUE TITLE
429 Too Many Requests - GET https://skimdb.npmjs.com/registry/react-intl

### ISSUE THREAD

**Issue by SandHani45** [formatjs/formatjs#3206]
## Which package?
5.13.2

## Describe the bug
Im trying to install package in local getting this issue 
## To Reproduce
![image](https://user-images.githubusercontent.com/30631105/136435063-8ba829a2-adef-47ba-a053-3c3ece51d0ba.png)

### Codesandbox URL

Please include a codesandbox URL if possible

**Comment by longlho** [comment]
npm is having an outage
