### ISSUE TITLE
formatjs polyfill's all the method of a package or only which are not supported ?

### ISSUE THREAD

**Issue by m-nathani** [formatjs/formatjs#3218]
## Which package?
`Intl.NumberFormat`

## Describe the bug
 I want to use `Intl.NumberFormat` as a polyfill to support `formatToPart` as its not supporting in the older version of safar after 13..
 
Moreover, i want to use the all the methods from NumberFormat from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat  and polyfil only `formatToParts`  

## Expected behavior

Only polyfill which is not supported and rest use from mdn ?

## Additional context

I checked the `should-polyfill.ts` file and found that it replaces all of NumberFormat based on checking if that not present and some other condition...

So was thinking is it possible to add a check if a method in a package is not support then only polyfill this method like `Intl.NumberFormat.prototype.formatToParts` and rest use which already supported in the browser by default ? 🤔

**Comment by longlho** [comment]
No that's not possible. Browsers don't expose locale data for us to use.
