### ISSUE TITLE
DateTimeFormat Welsh locale in Chrome missing

### ISSUE THREAD

**Issue by longlho** [formatjs/formatjs#3245]
### Discussed in https://github.com/formatjs/formatjs/discussions/3240

<div type='discussions-op-text'>

<sup>Originally posted by **florianwiech** October 26, 2021</sup>
## Which package?

`@formatjs/intl-datetimeformat`

## Describe the problem

Using the `Intl.DateTimeFormat` with the Welsh locale does not work in Chrome:

```js
let date = new Date(Date.UTC(2020, 11, 20));

const welshFormat = new Intl.DateTimeFormat("cy", {
  day: "2-digit",
  month: "long",
  year: "numeric"
}).format(date);

console.log(welshFormat) // should return "20 Rhagfyr 2020" but is "20 December 2020"
```

The support locale check from DateTimeFormat also shows that Crome does support the Welsh locale:
(Firefox and Safari on the other hand support it)

```js
console.log(Intl.DateTimeFormat.supportedLocalesOf(['en-GB', 'cy']));
```

At this point I'm thinking I should be able to extend the locale by providing the polyfill with the locale data.
Unfortunately adding the proposed polyfill imports does not solve the missing locale.

```js
import "@formatjs/intl-datetimeformat/polyfill";
import "@formatjs/intl-datetimeformat/add-all-tz";
import "@formatjs/intl-datetimeformat/locale-data/cy";
```

### Codesandbox URL

https://codesandbox.io/s/intl-datetimeformat-welsh-problem-chrome-1613j?file=/src/index.js

## Expected behavior

After importing the polyfill I expect that Chrome uses the provided locale data and formats the message in the defined locale.

## Screenshots

Does not work in chromium:
<img width="1014" alt="brave" src="https://user-images.githubusercontent.com/26004755/138853887-3509fea4-3e31-48f5-8820-c9e6f5d5b803.png">

Does work in Firefox:
<img width="975" alt="firefox" src="https://user-images.githubusercontent.com/26004755/138853894-b1a8c336-c47b-42de-be0a-6d8371951302.png">

Does work in Safari:
<img width="1051" alt="safari" src="https://user-images.githubusercontent.com/26004755/138853900-f5318b77-11f7-4623-92d1-9e52a6f7d702.png">

## Desktop (please complete the following information):

- OS: macOS 11.6
- Browser: Chrome
- Version 95.0.4638.54

## Additional context

I did not open an issue since I am not sure if this is a problem of the polyfill or a problem in chromium.
Should the polyfill provide the missing locale?
</div>

**Comment by BloodBaz** [comment]
This issue does require a solution.  Its causing problems when generating dates on certificates when in Welsh (writes out dates in English rather than Welsh).  Ref: https://formatjs.io/docs/polyfills/intl-datetimeformat/

**Comment by longlho** [comment]
@BloodBaz ok so this is because `import "@formatjs/intl-datetimeformat/polyfill"` doesn't do a locale check, but rather only do capability check. In order to fix this you should follow our guide here: https://formatjs.io/docs/polyfills/intl-datetimeformat/#dynamic-import--capability-detection

**Comment by fwiech** [comment]
@longlho Thank you for providing the `polyfill-force` import!
I've updated my CodeSandbox sample and it solves the problem. 🎉

**Comment by tb-jake** [comment]
Solution in the codesandbox seems to no longer work, it is always Welsh now, and doesn't change back to English. What's a good solution/fix?

**Comment by longlho** [comment]
Did u add en locale data?
