### ISSUE TITLE
Stricter check for missing dates in `IntlMessageFormat`

### ISSUE THREAD

**Issue by amannn** [formatjs/formatjs#3249]
## Which package?

`intl-messageformat`

## Describe the bug

`IntlMessageFormat` accepts `undefined` as valid value for dates and uses the current date in this case. Since you get an error message when the property within `values` is completely absent, I'd expect to get the same error when the property is `undefined`. I think it would be safer to warn the user about a potentially overlooked value.

### Codesandbox URL

https://codesandbox.io/s/vibrant-leakey-swqos?file=/src/index.js

### Reproducible Steps/Repo

Invoke this code:

```js
new IntlMessageFormat("Date: {date, date, long}").format({
  date: undefined
})
```

## Expected behavior

The following error should be printed:
```
FORMATTING_ERROR: The intl string context variable "date" was not provided to the string "Date: {date, date, long}"
```

## Desktop (please complete the following information):

- OS: macOS
- Browser: Chrome
- Version: 95

## Additional context

I think this is the check that we'd need to update:

https://github.com/formatjs/formatjs/blob/d435ce1afc59907849748427ea066cc75a4504a9/packages/intl-messageformat/src/formatters.ts#L139

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap but PR's welcome as well

**Comment by amannn** [comment]
Sure, I can create a PR! I mostly wanted to confirm first that this is a bug and not by design 🙂.

**Comment by longlho** [comment]
so to be fair `icu4j` (Java) if you pass `null` it'd just print our the word `null`. I think throwing is ok
