### ISSUE TITLE
Valid ICU string not parsed properly.

### ISSUE THREAD

**Issue by cibernox** [formatjs/formatjs#3250]
## Which package?
@formatjs/icu-messageformat-parser

## Describe the bug
Nested plural expressions inside select expressions don't parse properly, while they did and function properly using `intl-messageformat-parser` ^6.0.0.
Currently they throw a `SyntaxError: unknown: MISSING_OTHER_CLAUSE` error.

## To Reproduce

Parse this ICU string that contains a plural inside a select:
```
This year { gender, select, male {he made {count, plural,=0 {no kilometres} one {one kilometre} other {{count} kilometres}}} female {she made {count, plural,=0 {no kilometres} one {one kilometre} other {{count} kilometres}}} other {they made {count, plural,=0 {no kilometres} one {one kilometre} other {{count} kilometres}}}}
```

There is a very similar nested example in the test suite verifying that nested plurals inside selects work, so there must be some edge case I'm hitting. The main difference is that my translation contains bits of plain text outside the braces.

Here's the example in the current test suite:

```
{gender_of_host, select,
  female {
    {num_guests, plural, offset:1
      =0 {{host} does not give a party.}
      =1 {{host} invites {guest} to her party.}
      =2 {{host} invites {guest} and one other person to her party.}
      other {{host} invites {guest} and # other people to her party.}}}
  male {
    {num_guests, plural, offset:1
      =0 {{host} does not give a party.}
      =1 {{host} invites {guest} to his party.}
      =2 {{host} invites {guest} and one other person to his party.}
      other {{host} invites {guest} and # other people to his party.}}}
  other {
    {num_guests, plural, offset:1
      =0 {{host} does not give a party.}
      =1 {{host} invites {guest} to their party.}
      =2 {{host} invites {guest} and one other person to their party.}
      other {{host} invites {guest} and # other people to their party.}}}}
```

here's my failing example formatted in a similar way for better readability.
```
This year 
{gender, select, 
  male {
    he made 
    {count, plural,
      =0 {no kilometres} 
      one {one kilometre} 
      other {{count} kilometres}}} 
  female {
    she made 
    {count, plural,
      =0 {no kilometres} 
      one {one kilometre} 
      other {{count} kilometres}}} 
  other {
    they made 
    {count, plural,
      =0 {no kilometres} 
      one {one kilometre} 
      other {{count} kilometres}}}}
```

### Codesandbox URL

Please include a codesandbox URL if possible

## Expected behavior

Pluras nested inside select expressions should parse

## Desktop (please complete the following information):

Irrelevant

## Smartphone (please complete the following information):

Irrelevant

**Comment by longlho** [comment]
I just tried this on our live code editor in https://formatjs.io/docs/intl-messageformat and it works. Do you have a codesandbox?

**Comment by cibernox** [comment]
Indeed I verified the code above and it did work this time. I thought I was going crazy and started debugging myself what was going on and turns out I had a non-breakable space in my ICU string (charcode 160) instead of a regular space (charcode 32) in one spot.
It was invisible to the eye. 
That is what was causing
```js
const { parse } = require("@formatjs/icu-messageformat-parser");
parse(icuString);
```
to blow in my face.

I'll close this as the issue wasn't accurate. 
Now, I do not know if the ICU syntax is supposed to support non-breakable spaces.

I leave up to you to decide wether this is a bug that should be fixed. My hunch is that non-breakable spaces should allowed and probably treated as regular spaces. The old intl-messageformat-parser seemed to behave this way.

Sorry for misreporting it.

**Comment by longlho** [comment]
It does support it in literal blocks and not placeholder blocks. E.g in one{any unicode char is ok} but not between special syntax like {dt, date}

**Comment by cibernox** [comment]
@longlho that was exactly the situation. It was placed between `other` and the opening brace.

**Comment by longlho** [comment]
Yup that is considered invalid

**Comment by cibernox** [comment]
@longlho Perhaps a console warning could help detect this issues? I probably copied that inadvertently from some web or tool.
