### ISSUE TITLE
Add support for self-closing elements in messages.

### ISSUE THREAD

**Issue by funkybob** [formatjs/formatjs#3254]
Or, at the very least, provide a rationale for why they're not supported.

Related to https://github.com/formatjs/formatjs/issues/1616

The comments on that PR do nothing to explain the design decision to not support valid HTML - namely self closing elements like `<br />`

They only reiterate that since there is a work-around / hack (of fudging them into our messages using substitution syntax), that this is a "solved" problem.

Again, the fact `{br}` can be fudged to produce the desired result is a work-around. It leverages the fact that `{foo}` will be substituted, and if `foo` in values is a function, it will be called.

Whereas actually supporting HTML properly would remove the need for anyone to implement this fudge.

So please, provide the community with a reason why you don't support this valid HTML.

**Comment by longlho** [comment]
We don't support HTML. We support XML-like tags to decorate chunks of text, thus does not handle things like attributes, unbalanced tags, self-closing tags and all the stuff that HTML supports. We don't have a full HTML parser.

**Comment by funkybob** [comment]
Thank you. This explanation clarifies things significantly.
