### ISSUE TITLE
How to know if polyfill locale data exists or needs to be trimmed to base?

### ISSUE THREAD

**Issue by longlho** [formatjs/formatjs#3255]
### Discussed in https://github.com/formatjs/formatjs/discussions/3248

<div type='discussions-op-text'>

<sup>Originally posted by **klimashkin** November  2, 2021</sup>
Hello, 

I'm dynamically importing the polyfill for `Intl.DisplayNames`, but have stumbled upon the problem of choosing the right file from the locale-data folder.

Let's say users locale is 'en-US' or 'ru-RU', how do I know that I need to trim them down to 'en' or 'ru' respectively when importing a file from the locale-data folder, but do not trim 'en-GB'? If I don't trim certain locales then the following code will error out, but manually listing locales for all the available files in the switch statement is not feasible.

```js
if ((await import('@formatjs/intl-displaynames/should-polyfill')).shouldPolyfill(locale)) {
  try {
    await import(
      // webpackChunkName: "intlpolyfill-display"
      '@formatjs/intl-displaynames/polyfill'
    );

    // How to load ru in case of locale="ru-RU"?
    await import(
      // webpackChunkName: "intlpolyfill-display-[request]"
      `@formatjs/intl-displaynames/locale-data/${locale}.js`
    );
  } catch (error) {
    console.error('Failed to load intl-displaynames polyfill', error);
  }
}
```</div>

**Comment by klimashkin** [comment]
@longlho Bumping the issue to make sure it's not auto-closed

**Comment by Techn1x** [comment]
@longlho should your commit have been a major / breaking change? the API's of `shouldPolyfill()` functions have changed (and my app's break on older browsers that call it)

**Comment by longlho** [comment]
How are you calling it? It should be backwards compat unless you call it with an array

**Comment by Techn1x** [comment]
> How are you calling it? It should be backwards compat unless you call it with an array

Exactly..

Is calling it with an array not supported? Seems like it was based on the function signature/types. I guess the docs only use a single locale string...

What would you suggest updating affected code to? Something like
`if(locales.some((locale) => shouldPolyfill(locale))) // doPolyfill()`

**Comment by Techn1x** [comment]
> How are you calling it? 

to answer your question, it was being called with an array of fallback locales like this;
`['en-au', 'en']`

**Comment by longlho** [comment]
you shouldn't have to supply the fallback since `shouldPolyfill` deals with that for you (e.g if you pass in `en-AU` and we don't have `en-AU` data we'd give you back `en`). In that case there's rarely a use case to pass in multiple locales unless you really have a multi-lingual app that loads multiple locales in the same session?
Check out https://formatjs.io/docs/polyfills/intl-datetimeformat#dynamic-import--capability-detection for example
