### ISSUE TITLE
create-react-app v4 + formatjs : "[React Intl] An `id` must be provided to format a message."

### ISSUE THREAD

**Issue by amangeot** [formatjs/formatjs#3260]
Hello, to anyone looking for a solution to use create-react-app v4 (CRA v4) along with formatjs and react-intl without having to eject, the simplest solution is to use craco configs to override babel plugins.

You can install and run craco following these installation instructions:
https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#installation

and then add a craco.config.js file to your root folder:

`module.exports = {
  babel: {
    plugins: [
      [
        "formatjs",
        {
          "idInterpolationPattern": "[sha512:contenthash:base64:6]",
          "ast": true
        }
      ]
    ]
  },
}`

This prevented this error on my CRA when I started using generated IDs:

> [React Intl] An `id` must be provided to format a message.

Hopefully it helps,

**Comment by longlho** [comment]
is this meant to be a bug? you can prob submit a PR to update the doc

**Comment by paveldvorak5** [comment]
Hello,
it doesn't work for me. I have tried all the combinations I think.
Here's my config
[craco.config.js.txt](https://github.com/formatjs/formatjs/files/9159459/craco.config.js.txt)
.
