### ISSUE TITLE
Regression with FormattedMessage

### ISSUE THREAD

**Issue by nspector** [formatjs/formatjs#3263]
## Which package?
intl-messageformat

## Describe the bug
I believe after this change: https://github.com/formatjs/formatjs/pull/3256 formatted messages where the values are not passed are now returning the string rather than emptying them out. Previously a message of `{foo} - {bar}` would be become ` - `. Now it is `{foo} - {bar}`. This is leaking the strings incorrectly to the client.

**Comment by longlho** [comment]
Apology for the behavior change, although neither behavior is ideal because missing param behavior is not guaranteed and undocumented. The new behavior aligns more with how `icu4j` does it when there're missing param.
```java
import com.ibm.icu.text.MessageFormat;

MessageFormat mf = new MessageFormat("invalid {date}")
mf.format(new HashMap<>()); // "invalid {date}"
```

**Comment by nspector** [comment]
Thanks for getting back to me @longlho! I should probably clarify, we are actually passing the values they are evaluating to undefined, rather than not passing them at all. Example:

### Message
```
{foo} - {bar}
```

### React
```
<FormattedMessage id="MESSAGE" values={{
  foo: someVariable?.someTree?.someValue,
  bar: someVariable?.someTree?.someOtherValue
}} />
```

**Comment by longlho** [comment]
yup understood. The behavior change is intentional so I'm not sure we'll necessarily revert at this point. I guess is there something specific you're looking for/have suggestions for?

**Comment by nspector** [comment]
Ok, good to know it is intentional. We'll have to add a lot of `|| ''` to our code then going forward. My only thought would be it would make sense for: 
```
<FormattedMessage id="MESSAGE" />
```
to do as you described, where-as what I showed we did explicitly pass the value, so it is odd to me for it to determine that in fact the value was not passed and therefore not fill it in.  Can you humor me (not sure what shell you are using, and my java is well out of date) and see what happens with this (or well, something like it):
```
jshell> import com.ibm.icu.text.MessageFormat;
jshell> MessageFormat mf = new MessageFormat("invalid {date}")
jshell> mf.format(new HashMap<>().put('date', undefined));
```

**Comment by longlho** [comment]
if `date` is specified, but `null`, Java coalesce that to the string `null`
```java
import com.ibm.icu.text.MessageFormat;

MessageFormat mf = new MessageFormat("invalid {date}")
Map<String, String> values = new HashMap<>();
values.put("date", null);
mf.format(values); // "invalid null"
```
there's no `undefined` in java so empty `Map` is basically that. All in all I think it's basically a grey area.

**Comment by nspector** [comment]
Interesting, so the current way isn't consistent with `icu4j` either. I guess it's up to you what you want to do, my 2c if it is a grey area is to not change functionality (as it currently has) without a major version bump. However it is your choice and I won't push it.

**Comment by josegl** [comment]
This behavior changes should be integrated in major version changes, not in patch versions.

**Comment by longlho** [comment]
kk I've reverted that commit, will publish a new version that restored the old behavior

**Comment by jrjohnson** [comment]
Thanks @longlho, 9.9.6 doesn't seem to have [published to NPM](https://www.npmjs.com/package/intl-messageformat).

**Comment by longlho** [comment]
apology for the delay it just got publishee
