### ISSUE TITLE
Formatjs not extracting some messages 

### ISSUE THREAD

**Issue by abderrahmaneMustapha** [formatjs/formatjs#3267]
## Which package?
formatjs

## Describe the bug
formatjs is not extracting some messages when i assign a variable (the type of this variable is string but i don't put my string directly in id or defaultMessage) you can see an example in the screenshots section 

## Screenshots
```javascript

 {questions.map(({ question, answer }, index) => (
              <Accordion key={`faq-${index}`} variant="outlined" style={{ marginBottom: -1 }}>
                <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                  <Typography className={classes.question}>
                    <FormattedMessage id={`faq.question.${index}`} defaultMessage={question} />
                  </Typography>
                </AccordionSummary>
              </Accordion>
))}
```

**Comment by longlho** [comment]
Non literal values cannot be extracted

**Comment by abderrahmaneMustapha** [comment]
but i really need to extract it ?? how can i do that ??

**Comment by longlho** [comment]
You need to declare it as a string literal
