### ISSUE TITLE
react-intl: provide a default xml function set for xml element

### ISSUE THREAD

**Issue by MarvelSQ** [formatjs/formatjs#3271]
## Which package?
react-intl@5.21.2

## Describe the bug
```js
intl.formatMessage({
  id: 'not_exist',
  defaultMessage: 'this is a {placeholder}, should look like <a>some link</a>',
  values: {
    placeholder: 'MY TEXT'
  }
})
```
expect the result should be `this is a MY TEXT, should look like <a>some link</a>`

But received an unformatted message `this is a {placeholder}, should look like <a>some link</a>`.

because values lack of element function for `a`

## Expected
should Intl provide a `default formatter` for tag.
```
import { formatRichReact, formatRichString } from 'react-intl/presets/formatter'

// this made <b>text</b> as string
formatRichString

// this made <b>text</b> as React Element
formatRichReact

```

**Comment by longlho** [comment]
you can use https://formatjs.io/docs/react-intl/components/#defaultrichtextelements

**Comment by MarvelSQ** [comment]
> you can use https://formatjs.io/docs/react-intl/components/#defaultrichtextelements

@longlho i wonder is there a default object map, include all tag such as `span: chunks => <span>{chunks}</span>`;

**Comment by longlho** [comment]
not that I know of
