### ISSUE TITLE
Needed to manually install @formatjs/intl to get react-intl to work

### ISSUE THREAD

**Issue by brmscheiner** [formatjs/formatjs#3275]
Encountered this issue upon upgrading from a really old version to react-intl `5.21.2`. 

After `npm install`, @formatjs/intl was mysteriously missing from node_modules even though it's definitely listed as a dependency of react-intl. My app failed to compile with 

> Uncaught error module build failed error ENOENT no such file /code/node_modules/@formatjs/intl/lib/index.js

System info:
```
% node --version
v15.8.0
% npm --version
7.5.1
```

After manually installing the missing package everything works as it should. Hotfix:

```
npm install @formatjs/intl -D
```

**Comment by longlho** [comment]
I think that's specific to your setup unless you have a repro?
