### ISSUE TITLE
Problem with plural option few in Russian Language

### ISSUE THREAD

**Issue by rusakov** [formatjs/formatjs#3282]
## Describe the bug
Problem with Russian language. Plural. 
https://codesandbox.io/s/bug-react-intl-formatted-message-o3z4k?file=/src/App.js
When we use defaultMessage, in Russian we see `2 голосов` with option `few`. 

### Codesandbox URL
https://codesandbox.io/s/bug-react-intl-formatted-message-o3z4k

## Expected behavior
Right behavior with option `few` is `2 голоса`

## Additional context
https://codesandbox.io/s/bug-react-intl-formatted-message-o3z4k?file=/src/index.js
If we remove comment in messages:8 array for `<IntlProvider locale={locale} messages={messages[locale]}>`
We will see right behavior. with option `few` we will see `2 голоса`

**Comment by longlho** [comment]
you have to set `defaultLocale` as well if your `defaultMessage` is not `en`.  See https://formatjs.io/docs/react-intl/components/#defaultlocale-and-defaultformats for docs
