### ISSUE TITLE
Newlines in messages not extracted to json

### ISSUE THREAD

**Issue by jebax** [formatjs/formatjs#3286]
## Which package?
`@formatjs/cli`

## Describe the bug
I'm trying to migrate from the deprecated `babel-plugin-react-intl` package and use `@formatjs/cli` instead. With the deprecated babel plugin, newlines get put into the extracted json, but with the formatjs CLI it seems this doesn't happen.

## To Reproduce

In my message files I have e.g.
```js
{
  myMessage: {
    id: 'MyMessages.MyMessage',
    defaultMessage: `This is some text. \n\nThis is some more text in a new paragraph`
  }
}
```

I have an extraction script: `yarn run extract './src/**/*.{js,jsx}' --out-file './lang/messages.json --format message-formatter.js`

I have this formatter:
```js
const format = msgs => {
  const results = []
  Object.entries(msgs).forEach(([id, msg]) => {
    results.push({
      id,
      defaultMessage: msg.defaultMessage,
      description: msg.description
    })
  })

  return results
}

exports.format = format
``` 

The extracted json at `./lang/messages.json` then contains the following:
```js
[
  {
    "id": "MyMessages.MyMessage",
    "defaultMessage": "This is some text. This is some more text in a new paragraph."
  }
]
```

The CLI command strips out the newlines when extracting to the json file.

## Expected behavior
Newlines are included in the json file. 

## Additional context
If this is intentional please let me know. Can't find anything else about this particular problem online. Thanks!

**Comment by longlho** [comment]
Yup it's intentional. Newlines are i18n-sensitive

**Comment by antoinerousseau** [comment]
Any clue on how to not ignore newlines anyway? Adding `{br}` and replacing with `<LineBreak />` is boring

**Comment by evert** [comment]
What does "Newlines are i18n-sensitive" actually mean here? I just want to use formatjs to format a text email. Is the solution to split each line into its own message? Seems excessive

**Comment by bapjiws** [comment]
Have you guys tried using the `--preserve-whitespace` flag? It's not mentioned in the docs, but it's actually in the [source code](https://github.com/formatjs/formatjs/blob/4a0b8bb19e0a5f13d9e8980a3baab68dca8ed5f6/packages/cli-lib/src/cli.ts#L108-L111), and to me it seemed to do the trick 🙂
