### ISSUE TITLE
Different license info in fast-memoize

### ISSUE THREAD

**Issue by hotdi** [formatjs/formatjs#3299]
The license file for the 'fast-memoize' package contains a the MIT license text.
https://github.com/formatjs/formatjs/blob/main/packages/fast-memoize/LICENSE.md

But the the 'package.json' state a ISC license.
https://github.com/formatjs/formatjs/blob/main/packages/fast-memoize/package.json

Please unifi the license information for that package.

**Comment by longlho** [comment]
Wanna PR right quick?
