### ISSUE TITLE
@formatjs/cli: Cannot find module `vue/compiler-sfc`

### ISSUE THREAD

**Issue by themgoncalves** [formatjs/formatjs#3324]
## Which package?
`@formatjs/cli` v4.6.0

## Describe the bug

After upgrade `@formatjs/cli` to its latest version (v4.6.0), the string extraction and compilation got broken. It attempts to load an external module, which is not listed as requirement in any document.

```bash
> formatjs extract './src/**/*.i18n.ts' --out-file ./build/i18n/en.json --format simple

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'vue/compiler-sfc'
Require stack:
- /Users/.../node_modules/@formatjs/cli/src/vue_extractor.js
- /Users/.../node_modules/@formatjs/cli/src/extract.js
- /Users/.../node_modules/@formatjs/cli/src/cli.js
- /Users/.../node_modules/@formatjs/cli/bin/formatjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/.../node_modules/@formatjs/cli/src/vue_extractor.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/.../node_modules/@formatjs/cli/src/vue_extractor.js',
    '/Users/.../node_modules/@formatjs/cli/src/extract.js',
    '/Users/.../node_modules/@formatjs/cli/src/cli.js',
    '/Users/.../node_modules/@formatjs/cli/bin/formatjs'
  ]
}
```

### Codesandbox URL

Please include a codesandbox URL if possible

### Reproducible Steps/Repo

Try to extract and compile the `string` through:

```bash
formatjs extract './src/**/*.i18n.ts' --out-file ./build/i18n/en.json --format simple
```

## Expected behavior
1) Strings to be extracted and compiled without error;
2) if required/necessary, documentation to be updated to include this new module requirement `vue/compiler-sfc`

## Desktop (please complete the following information):

- OS: macOS Big Sur (11.6.2)
- Browser: N/A.
- Version v4.6.0

## Smartphone (please complete the following information):

N/A

## Additional context

In my application, I do use `react-intl@5.24.1`

**Comment by jbpenrath** [comment]
From my understanding, `@vue/compiler-sfc` is now embedded in `vue` package but formatjs do not install this package but `@vue/compiler-core`. So since version 4.6.0, `@vue/compiler-sfc` has been removed from dependency list of formatjs but it does not exist within `@vue/compiler-core` package.

**Comment by longlho** [comment]
Vue 3.2.23+ has compiler-sfc built in. I'll take a look

**Comment by Guid75** [comment]
from vue_extractor.js :
```
const compiler_core_1 = require("@vue/compiler-core");
const compiler_sfc_1 = require("vue/compiler-sfc");
```

Is there any reason why the second require does not use @vue/compiler-sfc?
In my case, I have to add the **entire vue** project as a dependency in my rollup project to generate my bundle.
