### ISSUE TITLE
eslint-plugin-formatjs type error since 2.20.0

### ISSUE THREAD

**Issue by jbpenrath** [formatjs/formatjs#3325]
## Which package?
**eslint-plugin-formatjs**

## Describe the bug
Since, eslint-plugin-formatjs 2.20.0, I'm unable to build my project successfully. A typescript error occured, `Duplicate identifier 'Prepend.'`

After some investigations, I identified error comes from `eslint-plugin-formatjs` or one of its dependencies since version 2.20.0.

### Reproducible Steps/Repo

- Create a new project with `typescript`, `eslint` and `eslint-plugin-formatjs>=2.20.0` configured
- Run `tsc`

## Expected behavior
The build should pass.

## Desktop (please complete the following information):

- OS: Mac OS 12.0.1
- Browser : N/A

## Related development dependencies
- Yarn version : 1.22.17
- Typescript version: 2.5.4
- Eslint 8.3.0
- Webpack 5.65.0

## Additional context

Error output on build
```
node_modules/@types/eslint-scope/node_modules/@types/eslint/helpers.d.ts:1:6 - error TS2300: Duplicate identifier 'Prepend'.

1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends ((
       ~~~~~~~

  node_modules/@types/eslint/helpers.d.ts:1:6
    1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
           ~~~~~~~
    'Prepend' was also declared here.

node_modules/@types/eslint/helpers.d.ts:1:6 - error TS2300: Duplicate identifier 'Prepend'.

1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
       ~~~~~~~

  node_modules/@types/eslint-scope/node_modules/@types/eslint/helpers.d.ts:1:6
    1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends ((
           ~~~~~~~
    'Prepend' was also declared here.


Found 2 errors.
```

**Comment by longlho** [comment]
Try removing your package-lock and reinstall?

**Comment by jbpenrath** [comment]
Good catch, that's do the job 🙏
