### ISSUE TITLE
Moving typescript to devDepencies in react-intl

### ISSUE THREAD

**Issue by achaniotis** [formatjs/formatjs#3343]
## Which package?
react-intl

## Describe the bug
We are only using react-intl in our project that uses Typescript 3.9 and since typescript 4.5 is listed as a peer dependency, even though it's optional, it is forcing us to run `npm i --legacy-peer-deps` otherwise the npm install fails.

Can typescript be safely moved to a dev dependency in the react-intl library? 

## To Reproduce
Use npm v7 and Typescript < 4.5 in your project and try to install react-intl ... it will fail.

## Expected behavior
Allow react-intl to be installed in projects where the Typescript version is < 4.5 and are using npm v7.

**Comment by longlho** [comment]
we require TS 4.5 because it comes with newer `esnext.intl` type definitions. Without that your project won't compile

**Comment by achaniotis** [comment]
We are not compiling the react-intl library, just consuming the compiled version.  Why would the type definitions matter in this case?

**Comment by longlho** [comment]
because it relies on things like new `Intl.DateTimeFormat` types globally which is only available in `esnext.intl.d.ts` in TS4.5

**Comment by achaniotis** [comment]
Thanks for the details on this!
