### ISSUE TITLE
CLI only accepts parameters in double quotes

### ISSUE THREAD

**Issue by emkayy** [formatjs/formatjs#3345]
## Which package?
CLI

## Describe the bug
On Windows 10 / Powershell in npm scripts extract won't work if parameters are not in escaped double quotes (\")

Won't work:
`"extract:i18n": "formatjs extract '{pages,components,sections}/**/*.{js,ts,tsx}' --format simple --id-interpolation-pattern '[sha512:contenthash:base64:6]' --out-file lang/en.json",`

This will produce only an empty object ({}) in lang/en.json. So the out-file parameter seems to work without quotes.

Does work:
`"extract:i18n": "formatjs extract \"{pages,components,sections}/**/*.{js,ts,tsx}\" \"--id-interpolation-pattern\" \"[sha512:contenthash:base64:6]\" \"--out-file\" \"lang/en.json\""`

## To Reproduce
See commands above

## Desktop (please complete the following information):
- OS: Windows 10
- Powershell

**Comment by longlho** [comment]
this seems to be a windows-specific problem.

**Comment by emkayy** [comment]
... yet still a problem. It took me ages to figure it out. And it never happened with any other CLIs I used so far. 
And it only seems to be the case with the glob patterns. So there must be a difference between this parameter and all the others.

**Comment by longlho** [comment]
Every shell interprets globs differently. Some auto expands them and some pass them verbatim. That's not something we can control

**Comment by AAWESOMEUSERNAME** [comment]
Take me hours to find out why the output is empty,thanks for the issue T_T
