### ISSUE TITLE
List of vendors accepting formatjs extract format 

### ISSUE THREAD

**Issue by francois-pasquier** [formatjs/formatjs#3361]
In the documention, it is said that the défaut extract format is this one :

```json
{
  "[id]": {
    "string": "[message]",
    "comment": "[description]"
  }
}
```

Is there a list of vendors taking this format; or at least a few examples?

What I am looking for is vendors who care about the description as I believe it's important to pass the right meaning and have the best translations.

If I am following formatjs documentation and not hardcoding id's, if my vendor only gets the defaultmessage and a hashed ID, I guess the translations won't be so great.

Thank you.

**Comment by longlho** [comment]
https://formatjs.io/docs/tooling/cli#builtin-formatters should have the list you're looking for. Any vendor that supports `simple` is just doing key-value, the others support `description` and/or some form of context.
