### ISSUE TITLE
swc-plugin can't use in CallExpression

### ISSUE THREAD

**Issue by 729993031** [formatjs/formatjs#3362]
## Which package?
@formatjs/swc-plugin 1.1.4

## Describe the bug
![image](https://user-images.githubusercontent.com/13050361/149267429-53b16ea4-841c-4754-8fc2-a940c5283299.png)

swc-plugin overrideIdFn can't run in placeholder2 but can run in placeholder
![image](https://user-images.githubusercontent.com/13050361/149267504-b75c2d6c-1db1-4e10-a575-b429c43026e4.png)

### Codesandbox URL

Please include a codesandbox URL if possible
https://codesandbox.io/s/dazzling-kilby-cj4ee?file=/src/index.js

**Comment by longlho** [comment]
`1.1.5` should have the fix for this

**Comment by 729993031** [comment]
sorry @longlho ，he has other error 
then can't run in  2 and 5
https://codesandbox.io/s/dazzling-kilby-cj4ee?file=/src/index.js
![image](https://user-images.githubusercontent.com/13050361/149495607-e88fadb0-d989-4a7d-99ae-bfaa2fb280b9.png)
![image](https://user-images.githubusercontent.com/13050361/149495620-e3eaa077-7ce8-4cf4-abc5-7bb46a232246.png)

**Comment by longlho** [comment]
latest version should have this fix

**Comment by 729993031** [comment]
@longlho in the 1.1.6 version  they can't run in id is 1
https://codesandbox.io/s/dazzling-kilby-cj4ee?file=/src/index.js
![image](https://user-images.githubusercontent.com/13050361/149695682-8899cd69-1680-43e3-a89c-f6b7f8601d23.png)
