### ISSUE TITLE
Support for ICU 69 within currency format

### ISSUE THREAD

**Issue by peter-mouland** [formatjs/formatjs#3368]
## Which package?
`intl-messageFormat`

## Describe the bug
related: https://github.com/formatjs/formatjs/issues/3191
ICU 69: https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html#trailing-zero-display

Would it be possible to allow `/w` to work for currency skeletons e.g. `precision-currency-standard/w`?

### Codesandbox URL

Please include a codesandbox URL if possible

### Reproducible Steps/Repo

```js
const IntlMessageFormat = require('intl-messageformat').default
new IntlMessageFormat(
            `{initialFee, number, :: .00/w currency/GBP} annual fee for the first {years, plural,
              =1 {year}
              other {# years}
            }, then {yearlyFee, number, :: .00/w currency/GBP}`,
            'en-GB',
        ).format({
            initialFee: 1.23,
            years: 3,
            yearlyFee: 1.00,
        })
```

returns:

```js
£1.23 annual fee for the first 3 years, then £1.00
```

## Expected behavior
```
£1.23 annual fee for the first 3 years, then £1
```

**Comment by longlho** [comment]
looks like this is a chrome issue actually
```js
new Intl.NumberFormat('en-GB', {"currency": "GBP",
  "maximumFractionDigits": 2,
  "minimumFractionDigits": 2,
  "style": "currency",
  "trailingZeroDisplay": "stripIfInteger"}).format(1)
// '£1.00'
```

**Comment by peter-mouland** [comment]
Appologies, I didn't mention I am using this on node 14.17.6 and node v16.13.0

Sorry, but from your comment I'm unsure of how to get the desired result, or are you saying it's now fixed/not an issue?

**Comment by longlho** [comment]
I'm saying we don't actually do the formatting, we just convert those to native `Intl` API so this is effectively a `Intl` API issue. I think https://github.com/tc39/ecma402 is the more appropriate repo to report this

**Comment by peter-mouland** [comment]
Just post this here to make the trail easier to follow : https://github.com/nodejs/node/issues/41568

**Comment by flip-it** [comment]
I don’t think it's a Chrome issue. 

See https://codesandbox.io/embed/musing-fog-n0zdp2

It outputs `$20.00` when using FormattedNumber and `$20` when using native Intl.NumberFormat given the same options.

Same behaviour in Safari too.

**Comment by flip-it** [comment]
Posted a new issue https://github.com/formatjs/formatjs/issues/3985.
