### ISSUE TITLE
HTML entities cause translations to get distinct IDs

### ISSUE THREAD

**Issue by cabello** [formatjs/formatjs#3369]
Hello 👋 

## Which package?

"react-intl": "^5.24.3",

## Describe the bug

I was getting this error: 

```
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "MOGAbo" for locale "en-CA", using default message as fallback. 
```

I checked my translation file for missing translations and could not find one, then I noticed the following, the only ones causing this error had html entities in them `&#39;`:

```
"PIhMKo": {
"defaultMessage": "... You&#39;ll find it in ..."
}
```

Once I replaced that by a regular single quote, the ID started to match:

```
"MOGAbo": {
  "defaultMessage": "...You'll find it in..."
},
```

## To Reproduce

1. Put HTML entities in `<FormattedMessage`
2. Extract translations
3. Notice that you get "missing translation" errors in the console
4. Replace HTML entities
5. Extract translations
6. Notice errors are gone

## Expected behavior

ID should match even with HTML entity, no missing translation error.

## Desktop

macOS, Chrome

## Additional context

I am using Typescript and my `tsconfig.json` has:

```
"plugins": [
      {
        "transform": "@formatjs/ts-transformer",
        "import": "transform",
        "type": "config",
        "overrideIdFn": "[sha512:contenthash:base64:6]",
        "ast": true
      }
    ]
```

my `.babelrc` has:

```
{
  "plugins": [
    [
      "react-intl",
      {
        "idInterpolationPattern": "[sha512:contenthash:base64:6]",
        "extractFromFormatMessageCall": true,
        "ast": true
      }
    ]
  ]
}
```

My `package.json` has the following dependencies:

```
"@formatjs/cli": "^2.13.12",
"@formatjs/ts-transformer": "^2.12.7",
"babel-plugin-react-intl": "^8.2.17",
"eslint-plugin-formatjs": "^2.9.7",
```

Please, let me know if you need anything else.
Thank you for this awesome library. 🙇

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
`babel-plugin-react-intl` is deprecated, can you try `babel-plugin-formatjs`?

**Comment by cabello** [comment]
I just tried that, the issue remain as soon as I add HTML entities, the resulting IDs still mismatch. 
I can try other things that you can think of. Let me know. 😉

**Comment by longlho** [comment]
do you have a repro?

**Comment by cabello** [comment]
I don't have a minimal repository disclosing the issue, this is happening in my app, medium size private codebase.

**Comment by cabello** [comment]
I still have this issue, closing this issue because I am not expecting it to be fixed and don't want to cause a burden on the OSS maintainers of this project, the workaround is simple (e.g. avoid HTML entities).
