### ISSUE TITLE
swc-plugin option `overrideIdFn` does not provide the same filepath as the babel-plugin

### ISSUE THREAD

**Issue by rametta** [formatjs/formatjs#3375]
## Which package?
swc-plugin

## Describe the bug
In the swc-plugin there is an option for `overrideIdFn`, I recently opened a [PR](https://github.com/formatjs/formatjs/pull/3371) to add the filename as the 4th arg to match how the babel-plugin behaves, but it turns out that in the swc-plugin, the filename is just an empty string `''` or the provided `option.fileName`, whereas in the babel-plugin the fileName passed to overrideIdFn is the actual file path of the `visitor`. So for projects that try to migrate from babel to swc, this is a breaking because it's not behaving the same way and there is no workaround as far as i can tell

### Reproducible Steps/Repo

1. Provide options to the swc-plugin
2. use the `overrideIdFn` with a callback with 4 args
4. console.log all the args to see what you get

## Expected behavior
The 4th arg to `overrideIdFn` should be the filename of the file holding the messagem not the filename passed in as option to swc-plugin

## Desktop (please complete the following information):

- OS: MacOs
- Browser Firefox
- Version 95.0.2

**Comment by longlho** [comment]
That's a swc problem unfortunately. How are you running your swd pipeline?

**Comment by rametta** [comment]
Through webpack with the swc-loader

**Comment by longlho** [comment]
yeah that seems like a swc-loader issue

**Comment by rametta** [comment]
Correct me if I'm wrong, but it seems like inside the FormatTransformer, the way it's resolving the filename is just by taking the passed in option and if nothing is passed in, it just defaults to an empty string -> https://github.com/formatjs/formatjs/blob/main/packages/swc-plugin/src/transform.ts#L592
 
If that is the case, it doesn't seem like swc-loader issue

**Comment by longlho** [comment]
Yeah but it's supposed to be passed in is the problem. Babel-loader passes it in

**Comment by rametta** [comment]
Okay, do you have any suggestions on how to get around this? I'm not sure swc will add that feature

**Comment by longlho** [comment]
No I don't unfortunately. For reference `babel` does it.

**Comment by rametta** [comment]
I've opened a bug with swc-loader https://github.com/swc-project/swc-loader/issues/36 to help address this
