### ISSUE TITLE
::eeee show a short weekDay instead of long one

### ISSUE THREAD

**Issue by maxgenest** [formatjs/formatjs#3384]
## Which package?

intl-messageformat

## Describe the bug

When I use `::eeee` in a FormattedMessage it shows a short weekDay instead of a long one. 
I saw this bug in a french locale.

Same bug for `::cccc` and `::EEEE`

Exemple : 
`<FormattedMessage defaultMessage='Tous les {valueDate, date, ::eeee}' values={{valueDate: date}} />`
return "Tous les jeu." instead of "Tous les jeudis"

## To Reproduce

Use a date in a FormattedMessage with the ::eeee format.

## Desktop (please complete the following information):

- OS: macOS 12.1 
- Browser: Chrome
- Version: 97.0.4692.71

**Comment by leggomuhgreggo** [comment]
Did this get solved?

EDIT: here's a alternative in case anyone stumbles across this someday:
```
intl.formatDate(Date.now(), {
  weekday: 'long',
})
```

**Comment by leggomuhgreggo** [comment]
Oh I guess this is the limitation that's meant by these [notes here](https://formatjs.io/docs/intl-messageformat/#datetime-skeleton):
![image](https://user-images.githubusercontent.com/2213636/156701098-fee3a21d-2072-48f4-aff3-0dd38e7fb8c0.png)

I found the [relevant code](https://github.com/formatjs/formatjs/blob/main/packages/icu-skeleton-parser/date-time.ts#L62-L64) and was fixin to open a PR when I remembered the caveat above -- but I'd be happy to move forward with that if its useful. 

Thanks!

**Comment by longlho** [comment]
Oh PR is always welcome!
