### ISSUE TITLE
babel-plugin-formatjs preserveWhitespace option isn't documented

### ISSUE THREAD

**Issue by ofagbemi** [formatjs/formatjs#3389]
## Which package?
babel-plugin-formatjs

## Describe the bug
It looks like babel-plugin-formatjs has a [preserveWhitespace option](https://github.com/formatjs/formatjs/blob/c29db02fee342964e42fda2bd224a48df92e474b/packages/babel-plugin-formatjs/types.ts#L45) that isn't documented. It looks like a similar feature exists in and is documented in both the [ts-transformer plugin](https://formatjs.io/docs/tooling/ts-transformer/#preservewhitespace) and [swc-plugin](https://formatjs.io/docs/tooling/swc-plugin).

## To Reproduce

View babel-plugin docs: https://formatjs.io/docs/tooling/babel-plugin — preserveWhitespace option isn't documented.

### Codesandbox URL

N/A

### Reproducible Steps/Repo

N/A

## Expected behavior

preserveWhitespace option is documented on babel-plugin docs page: https://formatjs.io/docs/tooling/babel-plugin

## Desktop (please complete the following information):

- OS: Mac OS
- Browser Chrome
- Version 97

**Comment by longlho** [comment]
mind submitting a PR?
