### ISSUE TITLE
Allow for providing terse plain string instead of full verbose MessageDescriptor

### ISSUE THREAD

**Issue by alex-kowalczyk** [formatjs/formatjs#3390]
Now, when providing message id is unnecessary and even not recommended, it would be great to allow just to provide simple plain string instead of verbose MessageDescriptor.
This would make formatjs to follow simplicity and beauty of traditional i18n systems like GNU gettext, where the only thing you had in the code to make the string i18nized was `_noop("A message")` (counterpart of `defineMessage`) or `_("A message")`  (counterpart of `formatMessage`). 

## To Reproduce
Currently even for a trivial case it is an effort to i18nize a single string. It is also errorprone (because of {many brackets and longComplicatedIdentifiers:})
```
defineMessage({defaultMessage: "A message"});
intl.formatMessage({defaultMessage: "A message"});
<FormattedMessage defaultMessage="A message"/>
```

Shortened optional syntax if someone does not need ids or descriptions or long identifiers.
```
defMsg("A message");
intl.fmtMsg("A message");
<FmtMsg msg="XYZ"/>   {/* Ideally to have msg just in the tag body, but I believe it's not possible in React */}
```

**Comment by longlho** [comment]
`description` is almost always required to provide translation context. In terms of error prone I'd recommend using IDE or some type system for autocomplete

**Comment by anilanar** [comment]
@longlho 

In our case, `description` is almost never required, and my team finds `{ defaultMessage: '...' }` annoyingly verbose. Is there any way we can help to make this happen?

97% of our translations look like `intl.formatMessage({ defaultMessage: '...' })`, we can shorten `intl.formatMessage` by using additional function names.

For the remaining 3%, we'd use the verbose overload to provide description.

**Comment by alex-kowalczyk** [comment]
@anilanar switching to https://react.i18next.com/ seems the best solution.
