### ISSUE TITLE
Consider renaming "blacklist-elements" to "blocklist-elements" for inclusive tech

### ISSUE THREAD

**Issue by TheEvilDev** [formatjs/formatjs#3399]
We currently use the "blacklist-elements" rule to prevent usages of ICU MessageFormat features that aren't supported by our translation provider. Our company has internal scanners that flag this as an issue because the use of the term "blacklist" is not inclusive.

Suggest consider renaming this rule in future versions.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
