### ISSUE TITLE
Why does shouldPolyfill for intl-displaynames return `und` and not `en`?

### ISSUE THREAD

**Issue by longlho** [formatjs/formatjs#3405]
### Discussed in https://github.com/formatjs/formatjs/discussions/3404

<div type='discussions-op-text'>

<sup>Originally posted by **sean256** February  4, 2022</sup>
I'm trying to get dynamic imports working, but when the locale is `en` or `en-us` the returned value from `shouldPolyfill` is `und`. This causes all output from `Intl.DisplayNames` to not work as expected.

Here is a runkit showing the output: https://runkit.com/embed/59hzxn8qcry8

```js
import {shouldPolyfill} from '@formatjs/intl-displaynames/should-polyfill';
console.log(shouldPolyfill('en')); // logs out `und`
```</div>

**Comment by Haraldson** [comment]
@longlho What was the solution here?
