### ISSUE TITLE
intl-numberformat: "RangeError: Maximum call stack size exceeded" exception for some Safari versions

### ISSUE THREAD

**Issue by denisraslov** [formatjs/formatjs#3413]
## Which package?
`@formatjs/intl-numberformat`

## Describe the bug
The `RangeError: Maximum call stack size exceeded.` exception is being thrown from `@formatjs/ecma402-abstract/node_modules/@formatjs/intl-localematcher/abstract/BestFitMatcher.js`(18 line, `availableLocales.forEach(function (locale) {`) if call the `formatToParts` method of `Intl.NumberFormat` object for some Safari browser versions.

## Call stack screenshot

![Callstack](https://user-images.githubusercontent.com/4654180/153206206-c4c80a06-f7e3-4d4b-b286-a64ac87337b9.png)

## To Reproduce

Use the `formatToParts` method of `Intl.NumberFormat` object, e.g. `new Intl.NumberFormat('en-GB', { currency: 'GBP' }).formatToParts(12.12)` in mentioned Safari browser versions

## Desktop:

- OS: Mac OS X
- Browsers: Safari 12.1.2, Safari 12.1.1, Safari 12.1, Safari 12.0.3, Safari 12.0

## Smartphone:

- Device: iPad
- OS: iOS 12.5.5
- Browser: Mobile Safari 12.1.2

**Comment by longlho** [comment]
do you have a repro?

**Comment by shunxing** [comment]
Is there any update on that ?
