### ISSUE TITLE
Missing GMT timezone for @formatjs/intl-datetimeformat/polyfill

### ISSUE THREAD

**Issue by hstemplewski** [formatjs/formatjs#3429]
## Which package?
Since this is a monorepo. Please specify which package this bug report is for.
@formatjs/intl-datetimeformat/polyfill

## Describe the bug
After add @formatjs/intl-datetimeformat/polyfill for react-native and try to run 

```ts
Intl.DateTimeFormat(undefined, {
      timeZone: 'GMT'
    })
```

Returns 'RangeError'

### Codesandbox URL

Please include a codesandbox URL if possible
I can't add sandbox for RN

### Reproducible Steps/Repo

1. Run code from description with polyfill

## Expected behavior
Add GMT zone to parse make Intl.DateTimeFormat running like in a browser

## Screenshots

```
 ERROR  RangeError: Invalid time value
 ```

## Smartphone (please complete the following information):

- OS: [e.g. iOS15.2]
- Browser [React-native app]

**Comment by hstemplewski** [comment]
@longlho I saw you're one of the contributors, is it possible to take a look at this issue?

**Comment by longlho** [comment]
yeah sry will take a look as soon as I got a chance

**Comment by longlho** [comment]
ok so `GMT` is not a valid timezone name, you need to specify `Etc/GMT`.
