### ISSUE TITLE
formatjs extracted messages are not always in alphabetical order by id-interpolation-pattern 

### ISSUE THREAD

**Issue by joshunger** [formatjs/formatjs#3443]
## Which package?
formatjs extract

## Describe the bug
We're noticing that the formatjs extracted messages are not always in alphabetical order by id-interpolation-pattern.

## To Reproduce
It is intermittent. Any ideas what might be causing this? Here is a diff of a message added -

![image](https://user-images.githubusercontent.com/2301847/155884090-ebfec363-700a-40d1-9e08-32ee2406ac88.png)

Shouldn't this be in alphabetical order?

Here is another example, why did this message move in order?

![image](https://user-images.githubusercontent.com/2301847/155884159-35f6e3e7-9d33-4aa4-8a6c-accad1d41b57.png)

**Comment by longlho** [comment]
hmm we do stable ordering when we stringify extracted messages. This does seem to be a bug

**Comment by joshunger** [comment]
Yeah that is a weird one. Sorry I don't have consistent repro steps.
