### ISSUE TITLE
Usage of defaultRichTextElements causes console warnings

### ISSUE THREAD

**Issue by mcnally** [formatjs/formatjs#3454]
## Which package?
react-intl

## Describe the bug
We retrieve translations from an API at runtime so pre compiling messages is not an option. We also use the defaultRichTextElements prop on the intlProvider. This results in a console warning with a hint about pre compiling the messages, causing a lot of log spam that we cannot action.

The warning is coming from here https://github.com/formatjs/formatjs/blob/eb9f193e084328f5471b183ec36eadba0edf3cf6/packages/intl/src/create-intl.ts#L35-L44
and we have no way of suppressing it.

## To Reproduce
Use IntlProvider with defaultRichTextElements, the console warning is then received

## Expected behavior
We should be able to handle whether the console warning occurs, similarly to how onError can be used to prevent console errors from happening. 

## Additional context
I found another issue with some discussion here: https://github.com/formatjs/formatjs/issues/2258

**Comment by eugenemachine** [comment]
We are encountering this problem in our unit tests, where each unit test sets up a new IntlProvider, and so we see tons of console.warn messages which we can't easily suppress.

I'm a bit confused. So I see there is already a mechanism for logging errors, and suppressing errors if desired, via the property onError: https://formatjs.io/docs/react-intl/components#onerror

Would it be better to just leverage that feature i.e. convert the console.warn -> onError function call?

This way, we still get the error/warning by default, but there would be a way to suppress them if desired.

**Comment by eugenemachine** [comment]
Sorry, me again. On the other hand, it truly is a warning rather than an error (since nothing is broken, just a performance hit), so to be totally correct, I think the right approach would be to implement a similar onWarning function that can be overridden as needed.

**Comment by longlho** [comment]
I'd be open to adding `onWarn` if anyone wants to make a PR

**Comment by mcnally** [comment]
> I'd be open to adding `onWarn` if anyone wants to make a PR

I'll take a look at this, thanks
