### ISSUE TITLE
Missing compact notation localization for FormattedNumber 

### ISSUE THREAD

**Issue by kovacszsoltizsolt** [formatjs/formatjs#3458]
## Which package?
`react-intl`

## Describe the bug
The compact notation localization doesn't work for some languages like in other cases, so far I encountered this problem in italian, and german languages.

## To Reproduce
```js
<IntlProvider locale="it">
  <FormattedNumber value={1000} style="currency" notation="compact" currency="USD" />
</IntlProvider>
```
```js
<IntlProvider locale="de">
  <FormattedNumber value={1000} style="currency" notation="compact" currency="USD" />
</IntlProvider>
```

## Expected behavior
It should format the numbers as in other languages. The outcome should be `1KUSD`(or the localized version of this), not `1000USD`.

```js
<IntlProvider locale="en">
  <FormattedNumber value={1000} style="currency" notation="compact" currency="USD" />
</IntlProvider>

```

## Desktop (please complete the following information):

- OS: macOS
- Browser: chrome, firefox, safari
- Version: `react-intl: 5.24.6`

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by daweido** [comment]
Hey, is there any news concerning this issue?

**Comment by longlho** [comment]
do u have a codesandbox?

**Comment by katzielinska** [comment]
hey @longlho, I'm having this exact issue in version 6.6.8
