### ISSUE TITLE
Request to bring back UMD builds

### ISSUE THREAD

**Issue by Phoenixmatrix** [formatjs/formatjs#3462]
## Which package?
`react-intl`, though I assume most of the packages are affected

## Describe the bug
Some versions ago, UMD builds were removed (from what I can tell from the PRs, this was by design) from the builds. I assume the intention was that if you have an IIFE build, a CommonJS build, and an ES6 build, UMD is redundant.

It's not the case though. For example if trying to load with es6 imports in modern browsers without bundling, having a single file to link to via unpkg is quite handy. I also hit a case where loading the IIFE with SystemJS is quite hacky/difficult because of dependency ordering (have to ensure React comes first by doing manual System.imports). Worse, in Safari this method doesn't seem to work.

The old UMD build however, works perfectly in those scenarios. If keeping it around as part of FormatJS's publishing cycle isn't too expensive for the maintainers, it would be great to bring it back.

## To Reproduce

Importing react-intl from a single script where an IIFE won't work or is less than ideal (eg: SystemJS) will surface the issue.

## Expected behavior
UMD builds are published to npm

## Desktop (please complete the following information):

- OS: Any, but particularly annoying on Macs because of Safari
- Browser Any, but worse in Safari
- Any version, but I hit the biggest issue in Safari 15 (though thats related to SystemJS and not react-intl)

## Additional context
My workaround right now is to make my own ES6 or UMD build with webpack or rollup. I assume this will work fine, but it would likely be a lot easier to maintain this upstream than in a fork.

**Comment by longlho** [comment]
I'll keep this issue open until stalebot marks them and see how popular this request is

**Comment by Phoenixmatrix** [comment]
Thanks! I expect this to be rather niche, but we'll see.
