### ISSUE TITLE
Creating a react components library with its own translations.

### ISSUE THREAD

**Issue by PetrShchukin** [formatjs/formatjs#3465]
I'm trying to create a custom react library, but I'm a bit confused how to do that. I want translations reside in my custom library, Let's say I have 10 buttons that I export. Does it mean that I need to wrap each component into its own IntlProvider? Wouldn't be an issue? As each instance of IntlProviderwould have same messages.
This is what I'd expect
```
import {MyButton, MyForm} from 'my-components'

function MyFeature(props: Props) {
  const intl = useIntl();
  return (
    <div>
      <MyButton locale={intl.locale} />
      <MyForm locale={intl.locale} />
    </div>
  )
}
```
But it means that I'll need to add IntlProvider in MyButton and in MyForm and each instance of IntlProvider would have messages for all other components. If I define messages in a component, not in a separate file, then parent application won't be able to extract messages.

**Comment by longlho** [comment]
This should have some info: https://formatjs.io/docs/guides/distribute-libraries
Top level app should aggregate those messages together and pass then in `IntlProvider`

**Comment by PetrShchukin** [comment]
@longlho It means that if a message has been change in a new version of a library, it's not enough to simply update the version of a library. On every library change, the top level app, should do extraction and compilation of translations?

**Comment by longlho** [comment]
Combination yes but not extraction. The messages are versioned and packaged with the library so you should extract before distributing a new version

**Comment by PetrShchukin** [comment]
Makes sense. To clarify when a change to a message in the library has been made, in the top app we do:
- update the library with the newest version (`npm install/update`)
- run `formatjs extract`, to get all messages from app and from dependencies, including our library
- run `formatjs compile` in order to compile messages into ast format (if we already use ast format, otherwise it's an optional step)
- commit changes

**Comment by longlho** [comment]
No all those steps should be done before you commit a change that bumps the library's version in the library itself.
The too app only aggregates all its libraries' translations together.
Translation data is the an asset just like img or icons or fonts. It follows the same lifecycle and library owns the piece of translation data it declares.

**Comment by PetrShchukin** [comment]
Ah, right, I was wrong about extraction, but we do need to do `formatjs compile`. If we have
```
top level app
|- src
|- lang
    |- en.json
    |- es.json
|- node_modules
    |- library1
        |- lang
            |- en.json
            |- es.json
```
There's no need to compile translations in the feature library as it's going to be aggregated in the top app, so it will be:

feature library:
- code change (a translation change)
- `formatjs extract` (implies changes to en.sjon and es.json)
- commit

top app:
- `npm install/update`
- `formatjs compile` (it will parse dependencies, if we correctly declared lang in package.json)
-  commit

**Comment by longlho** [comment]
yup that looks rigght

**Comment by PetrShchukin** [comment]
Thanks a lot, now it makes perfect sense =) Will close the ticket
