### ISSUE TITLE
$formatList not defined in VueJS template

### ISSUE THREAD

**Issue by daviesdoclc** [formatjs/formatjs#3488]
## Which package?
vue-intl

## Describe the bug
$formatList doesn't seem to be defined in a Vue template.  I can use $formatMessage just fine.

## Expected behavior
I would expect $formatList to be defined

## Desktop (please complete the following information):

- OS: MacOS 12.2.1
- Browser: Chrome

## Additional context
If I pass "intl" into the template from my setup then I can use intl.formatList.

Is this Vue package being maintained?  I have concerns about using it because I don't see any active development.  Is there another compatible project that is providing the Intl functionality for Vue?

**Comment by fkm** [comment]
Seems it's missing in the setup function.
https://github.com/formatjs/formatjs/blob/main/packages/vue-intl/plugin.ts

There is vue-i18n which is missing ICU :frowning_face:
