### ISSUE TITLE
[@formatjs/swc-plugin] typeerror: this.visitexpressionorsuper is not a function [Bug caused by @swC /core version upgrade ]

### ISSUE THREAD

**Issue by huskylengcb** [formatjs/formatjs#3494]
## Which package?

"@swc/core": "1.2.160"

"@formatjs/swc-plugin": "^1.3.2"

## Describe the bug

"@swc/core": "1.2.100"

<img width="719" alt="屏幕快照 2022-03-24 18 18 15" src="https://user-images.githubusercontent.com/28557953/159895260-409571c9-75ce-4879-836d-6b13b1c1aa5b.png">

<img width="670" alt="屏幕快照 2022-03-24 18 17 53" src="https://user-images.githubusercontent.com/28557953/159895283-0ae33871-b4cb-48f6-8273-7bd070b332ba.png">

"@swc/core": "1.2.160"

![屏幕快照 2022-03-24 18 18 08](https://user-images.githubusercontent.com/28557953/159895448-63c2c483-4fa6-421f-87ad-93c8de9145b2.png)

![屏幕快照 2022-03-24 18 17 39](https://user-images.githubusercontent.com/28557953/159895472-bc31110f-9fed-401e-ac2a-0b1f0e765f40.png)

## To Reproduce

@swc/core between 1.2.100 and 1.2.110 replaced the visitExpressionOrSuper method with another method and removed the visitExpressionOrSuper method, The visitExpressionOrSuper method is unavailable when @formatjs/ swc-plugin is used.

![屏幕快照 2022-03-24 17 51 29](https://user-images.githubusercontent.com/28557953/159896101-e7e6c244-6497-4dde-86ef-6dab45968268.png)

## Expected behavior

I look forward to updating the @formatJS/SWc-plugin to accommodate the bugs caused by the @SWC/core upgrade

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
