### ISSUE TITLE
TypeError caused by wrong data format in intl-datetimeformat/locale-data/haw.js

### ISSUE THREAD

**Issue by OlivierFreyssinet** [formatjs/formatjs#3503]
## Which package?
`intl-datetimeformat@5.0.x` (tried on both 5.0.0 and 5.0.1)

## Describe the bug

When importing `"@formatjs/intl-datetimeformat/locale-data/haw"`, a `TypeError` is thrown here as `.replace` is being called on a plain object instead of a `string`:

```
TypeError: skeleton.replace is not a function
    at parseDateTimeSkeleton
```
https://github.com/formatjs/formatjs/blob/be7a86d7a2fd2069c1063f97314766523075192a/packages/intl-datetimeformat/src/abstract/skeleton.ts#L319
https://github.com/formatjs/formatjs/blob/be7a86d7a2fd2069c1063f97314766523075192a/packages/intl-datetimeformat/src/core.ts#L343

This is happening because the argument is not a string as expected: (see `"short"` key)
`"dateFormat":{"full":"EEEE, d MMMM y","long":"d MMMM y","medium":"d MMM y","short":{"_value":"d/M/yy","_numbers":"M=romanlow"}}`

I don't really know where the locale data is coming from (the file is generated at build time for this package I understand) so unfortunately I cannot make a PR for the moment...

### Codesandbox URL

https://codesandbox.io/s/formatjs-polyfill-haw-repro-tb77x9?file=/src/index.js

## Expected behavior
This should not throw a TypeError
```
import "@formatjs/intl-getcanonicallocales/polyfill";
import "@formatjs/intl-locale/polyfill";
import "@formatjs/intl-numberformat/polyfill";
import "@formatjs/intl-datetimeformat/polyfill";
import "@formatjs/intl-datetimeformat/locale-data/haw";
```

## Smartphone (please complete the following information):

This is happening in React Native in my case
- OS: iOS 14.5 and Android API 31
- Browser: N/A, this is happening in `react-native@0.67.3` with `hermes-engine@0.9.0`

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
