### ISSUE TITLE
Is there a plan to support React 18 ?

### ISSUE THREAD

**Issue by pandanoir** [formatjs/formatjs#3510]
I have tried to update React to 18, but I couldn't update React since my project installs react-intl. React-intl requires React to be `^ 16.3.0 || 17` now.

Is there a plan to support React 18 ??

**Comment by longlho** [comment]
react 18 is very new so give everyone some time :) feel free to PR as well

**Comment by chegger** [comment]
@longlho Can you think of something that needs to be done, other than adding react 18 to the `package.json`? 

As I understand react 18, there should be no problem with upgrading to v18, as Concurrent React is opt in, since it has to be used explicitly via the `startTransition` and `useTransition` function/hook.

**Comment by nstepien** [comment]
https://github.com/formatjs/formatjs/blob/main/packages/react-intl/package.json#L137
The `@types/react` dependency should at the very least allow version `18`. Right now I have conflicting types because of this.

**Comment by jbaldassari** [comment]
I'm getting this error when I try to use React 18:
```
TS2786: 'IntlProvider' cannot be used as a JSX component.
  Its instance type 'IntlProvider' is not a valid JSX element.
    Types of property 'refs' are incompatible.
```
Hopefully it's just due to the `@types/react` version mismatch

**Comment by tombelieber** [comment]
> I'm getting this error when I try to use React 18:
> 
> ```
> TS2786: 'IntlProvider' cannot be used as a JSX component.
>   Its instance type 'IntlProvider' is not a valid JSX element.
>     Types of property 'refs' are incompatible.
> ```
> 
> Hopefully it's just due to the `@types/react` version mismatch

Same

**Comment by MattyBalaam** [comment]
There are a few breaking changes in the types for React 18, so the react-intl types will need to be updated.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

**Comment by longlho** [comment]
I'll try to get to it but unfortunately haven't got the time
