### ISSUE TITLE
babel-plugin-formatjs does not work with Vite @vitejs/plugin-react babel

### ISSUE THREAD

**Issue by nerijusgood** [formatjs/formatjs#3519]
## Which package?
babel-plugin-formatjs

## Describe the bug
Babel does not transpile and no Ids are being set. 
`Uncaught (in promise) Error: [@formatjs/intl] An `id` must be provided to format a message. `

## To Reproduce
Create Vite react app with this vite config:

import react from '@vitejs/plugin-react';
import path from 'path';

`export default {
	resolve: {
	plugins: [
		react({
			configFile: true,
		}),
	],
};`

### Codesandbox URL

Running simple vite app with all proper intl setup. ID do not get generated with babel.

### Reproducible Steps/Repo

1. Creat Vite app wiht config that is above
2. Do translatetion in ui without setting ID
3. On runtime it gets the above error.

**Comment by nerijusgood** [comment]
Have the same issue.

**Comment by GuillaumeBec** [comment]
@nerijusgood hi, currently running into the same issue here. Did you find a solution ?

**Comment by longlho** [comment]
is there a codesandbox?

**Comment by arantespp** [comment]
Hi! I'm also getting this issue. Did anybody find a solution?
