### ISSUE TITLE
NumberFormat with style: 'unit' on iphone10 is not correctly polyfilled

### ISSUE THREAD

**Issue by Speedy1991** [formatjs/formatjs#3522]
## Which package?
@formatjs/intl-numberformat": "^7.4.2"

## Describe the bug
Calling `Intl.NumberFormat` with `style:'unit'` causes an error on an iphone 10

## To Reproduce
```
new Intl.NumberFormat('de-DE', {
    style: 'unit',
    unit: 'kilometer',
    maximumFractionDigits: 0,
    minimumFractionDigits: 0,
  }).format(Number(value));
```

## Expected behavior
Should be polyfilled

## Error
```
RangeError NumberFormat([native code])
style must be either "decimal", "percent", or "currency"
```
## Device
Mobile Safari Version:14.0.3
iOS Version:14.4.2
IPhone 10

**Comment by Speedy1991** [comment]
This should not go stale, becaus this is a bug!

**Comment by longlho** [comment]
for such old devices you should use https://polyfill.io/v3/ which also polyfill `NumberFormat`'s deps
