### ISSUE TITLE
How to disable `rich text` feature in intl-messageformat

### ISSUE THREAD

**Issue by cwtuan** [formatjs/formatjs#3527]
## Which package?
intl-messageformat

### Reproducible Steps/Repo

From `intl-messageformat@8`, it supports [rich text](https://formatjs.io/docs/intl-messageformat/#rich-text-support).
However it's a break change.
I would like to upgrade to last version of `intl-messageformat` to fix some security problems.
But I don't want the `rich text` feature. 
Could you please provide a way to disable `rich text` feature?

**Comment by batjaa** [comment]
Are you looking to escape the HTML/XML tags?
`ignoreTag` might be what you're looking for.

re: https://formatjs.io/docs/intl-messageformat/#public-api

**Comment by pyrocat101** [comment]
`ignoreTag: true` is what you are looking for.
