### ISSUE TITLE
@formatjs/cli direct dependency on vue.js forces supply chain risks onto end users

### ISSUE THREAD

**Issue by ArkadyDR** [formatjs/formatjs#3547]
## Which package?
`@formatjs/cli`

## Describe the bug
The direct dependency on the vue.js package forces developers not using vue to pull in the whole framework, with two major issues:
- Supply chain issues/risk (licensing issues, packages being compromised)
- Subtantial increase in the download size for the tool, slowing down CI pipelines

The above might sound like a nitpick, but as an organization managing our cybersecurity risks, the first one about supply chain management makes using the CLI package a dealbreaker for us.

## To Reproduce

Install the package. See https://github.com/formatjs/formatjs/blob/0ed217e9e7a03769364aa7109fbecaa13683d99d/packages/cli/package.json#L49 for the dependency on vue.

## Expected behavior
I expect to be able to install the core @formatjs/cli tooling, and then if it's necessary to give the tooling framework-specific support, to have those be plugin/extension packages that I install separately as required. (Eg, `@formatjs/cli-plugin-react`, `@formatjs/cli-plugin-vue`).

## Note

I understand from some previous issues (eg https://github.com/formatjs/formatjs/issues/3173) that there was some flip/flopping as to whether to make vue a peer dependency or not - neither of the proposed solutions sounds like they are ideal. Architecturally if the CLI tooling needs framework-specific capabilities, providing it as an additional package to install seems like the most scalable way to manage it.

**Comment by Kristin-at-Fountain** [comment]
Any news on this? We'd like to get our application updated, but are not using vue.

**Comment by longlho** [comment]
how about we just prepackage into a single binary and dist that? I'm not a fan of the plugin mechanism it's just basically introducing versioning hell.

**Comment by ArkadyDR** [comment]
> it's just basically introducing versioning hell.

Depends on how often the two need to change together I suppose.

> how about we just prepackage into a single binary and dist that?

That would help as it would avoid the possibilities of postInstall scripts getting compromised etc.

**Comment by Kristin-at-Fountain** [comment]
Bump?

**Comment by longlho** [comment]
I took a look and got into some complication with packaging vue stuff so I'll likely move vue deps to peerDeps and lazy load the vue parser.
