### ISSUE TITLE
[@formatjs/intl] uninteded declaration of a few types

### ISSUE THREAD

**Issue by rodrigofariow** [formatjs/formatjs#3548]
## Which package?
@formatjs/int

## Describe the bug
Wrong usage of `Exclude` on several type declarations on https://github.com/formatjs/formatjs/blob/main/packages/intl/src/types.ts

```tsx
export type FormatRelativeTimeOptions = Exclude<
  Intl.RelativeTimeFormatOptions,
  'localeMatcher'
> &
  CustomFormatConfig
```

Since `RelativeTimeFormatOptions` is an object, using `Exclude` here won't do anything. Was this meant to be an `Omit`?
I was trying to understand if `localeMatcher` was a valid prop for `FormattedRelativeTime` and I noticed this.

## Screenshots
<img width="492" alt="image" src="https://user-images.githubusercontent.com/22502084/164272086-916b74cc-cb1a-4da6-af18-cdd35f6ecf10.png">

Thank you for your time

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
