### ISSUE TITLE
Missing 'narrowSymbol' in older Safari browsers not detected by should-polyfill.ts in intl-numberformat

### ISSUE THREAD

**Issue by floratmin** [formatjs/formatjs#3551]
## Which package?
intl-numberformat

## Describe the bug
In older Safari browsers (from version 10 up to 14) the option `currencyDisplay: 'narrowSymbol'` throws an error. Therefore it should be tested for in the file `should-polyfill.ts`

## To Reproduce
``` 
new Intl.NumberFormat('en', {
      currencyDisplay: 'narrowSymbol',
    })
```
throws on Safari 13

## Expected behavior
Should not throw.

## Desktop (please complete the following information):

- OS: macOs 10.13 High Sierra
- Browser safari
- Version 13

## Additional context
[caniuse](https://caniuse.com/mdn-javascript_builtins_intl_numberformat_numberformat_options_currencydisplay_parameter)

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap or PR's always welcome

**Comment by fknop** [comment]
Also having this issue with `8.2.0`

**Comment by regalstreak** [comment]
same issue in react-native
