### ISSUE TITLE
Wrong number of decimals for IQD (Irakian dinar) when formatting currency

### ISSUE THREAD

**Issue by lonchen-mirakl** [formatjs/formatjs#3560]
## Which package?
intl-numberformat

## Describe the bug
When formatting a numeric value to the IQD (Irakian Dinar) currency, I expect to get 3decimals. However, I get 0 decimal.
In the `https://github.com/formatjs/formatjs/blob/main/packages/intl-numberformat/src/currency-digits.generated.ts`, for IQD, it is indeed marked 0 for IQD, however, on the iso-4217 (https://en.wikipedia.org/wiki/ISO_4217), there should be 3decimals.

## To Reproduce
`<FormattedNumber value={1000} style="currency" currency="IQD" />`

## Expected behavior
`1000.000 IQD`

## Desktop (please complete the following information):

- OS: macOS
- Browser: chrome 
- Version: 100.0.4896.88

**Comment by longlho** [comment]
it's 0 according to CLDR https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-core/supplemental/currencyData.json#L118 which is the authority, not wiki
