### ISSUE TITLE
react-intl 5.25.1: Format error with argument on Android

### ISSUE THREAD

**Issue by theofournier** [formatjs/formatjs#3579]
## Which package?
react-intl, v5.25.1

## Describe the bug
Since version 5.25.1, on React Native project, on Android 11.0, there is an error for messages with argument, i.e. 

```ts
intl.formatMessage(
   {
       id: 'test',
       defaultMessage: '{arg} example',
   },
   {
      arg: 'bar'
   }
)
```

`[@formatjs/intl Error FORMAT_ERROR] Error formatting the default message for: "test", rendering message verbatim.`

**NB**:
- Not occurring on v5.25.0
- Not occurring on iOS
- Not occurring for messages without argument

## To Reproduce

On a React Native Cli project, running on Android:

```tsx
// App.tsx

import 'intl'
import 'intl/locale-data/jsonp/en'
import { IntlProvider } from 'react-intl';
import { useIntl } from 'react-intl';

export const App = () => (
   <IntlProvider>
      <AppContainer />
   </IntlProvider>
)

const AppContainer = () => {
   const intl = useIntl();

   const text = intl.formatMessage(
      {
          id: 'test',
          defaultMessage: '{arg} example',
      },
      {
         arg: 'bar'
      }
   )
   
   return <Text>{text}</Text>
}
```

- We get in the text: `{arg} example`
- - We get the error above

## Expected behavior
- We want: `bar example`

## Smartphone:

- Device: Pixel 4
- OS: Android 11.0, API 30
- React Native Cli

**Comment by longlho** [comment]
`intl.js` is deprecated so I suggest you use something else and/or remove that dependency

**Comment by theofournier** [comment]
@longlho I am talking about `react-intl`, are you saying that this package is also deprecated because it relies on `intl.js`?

**Comment by longlho** [comment]
no `intl.js` polyfills the global `Intl` so wanna make sure it doesn't mess up a `Intl` API we use

**Comment by driq** [comment]
Commenting to prevent automatic closing.  This issue is still an issue.

**Comment by Pablosornp** [comment]
Same here. What was the last working version?

**Comment by longlho** [comment]
is there a repro for this using https://expo.dev/ or something
