### ISSUE TITLE
Working 9.12.0 constructor for IntlMessageFormat  fails in 9.13.0

### ISSUE THREAD

**Issue by robopzet** [formatjs/formatjs#3582]
In version 9.12.0 this code works: 

    new IntlMessageFormat.IntlMessageFormat(msg, [], {}, {ignoreTag: true}) .format(args)

A test in my code that checks the function with this code passes.

in version 9.13.0 the test fails with this error:
_TypeError: First argument to Intl.Locale constructor can't be empty or missing._

In the release notes I could not find anything about such a change. I don't know if this project follows semver, but I did not expect a breaking change.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap. As a workaround does passing `undefined` for locales work?

**Comment by robopzet** [comment]
My workaround is to keep using 9.12.0. The reason to update is to keep up to date with external dependencies, not to get the new features.
