### ISSUE TITLE
IntlDateTime Format Polyfill is not working on IE 10 and IE 11

### ISSUE THREAD

**Issue by supreethmr** [formatjs/formatjs#3585]
## Which package?
Since this is a monorepo. Please specify which package this bug report is for.
Intl-DateTime-Format

## Describe the bug

IntlDateTimeFormat Polyfill will not work when we use `import '@formatjs/intl-datetimeformat/polyfill'` in IE 10 and IE 11.
IE 10 and IE 11 needs `import '@formatjs/intl-datetimeformat/polyfill-force'` to make it work.

Along with polyfill-force it would also need `import '@formatjs/intl-locale/polyfill'` to be loaded before a intl-datetimeformat polyfill, Else it will throw error `no locale data found` on IE browsers.

This would require us to explicitly add import for all the locales that we need one after another like below. Instead of using the locale data available on browser.
 
`import '@formatjs/intl-datetimeformat/locale-data/fr';`
`import '@formatjs/intl-datetimeformat/locale-data/en';`

When intl-datetimeformat is consumed we see there are lots of locale data gets shipped with it by default. So can we restrict this by shipping only those locale data that are required by project. This would reduce the package size and improve the performance of page load time. As there will be less locale data files to be extracted.

## To Reproduce
```js
// polyfill.js

import '@formatjs/intl-datetimeformat/polyfill';
import '@formatjs/intl-datetimeformat/locale-data/fr';
import '@formatjs/intl-datetimeformat/locale-data/en';

Or

require('@formatjs/intl-datetimeformat/polyfill');
require('@formatjs/intl-datetimeformat/locale-data/fr');
require('@formatjs/intl-datetimeformat/locale-data/en');
```
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Date Formatting Test</title>
    <script src="polyfill.js" type="text/javascript"></script>
</head>
<body>
    Date Format Test
    <script>
        function test(){
            var date = new Date();
            // // out of the box
            alert("toLocaleDateStringResult:  " + date.toLocaleDateString('en-Us', {
                month: '2-digit',
                day: '2-digit',
                year: 'numeric'
            }));
            alert("date.toLocaleDateString: " + date.toLocaleDateString);
            alert("Intl: " + Intl);
            var date = new Date();
            alert("Intl.DateTimeFormat: " + Intl.DateTimeFormat);
            alert("Intl.DateTimeFormat Result: " + Intl.DateTimeFormat("en-US", {
                month: "2-digit",
                day: "2-digit",
                year: "numeric"
            }).format(date));
        }
        test();
    </script>    
</body>
</html>
```
We can see that in IE 10 the alert box will display the date in 5/6/2022 format instead of 05/06/2022. 

### Codesandbox URL

Please include a codesandbox URL if possible

## Desktop (please complete the following information):

- OS: [e.g. iOS] Windows
- Browser [e.g. chrome, safari] Internet Explorer
- Version [e.g. 22] 10 and IE 11 Compatibility mode.

**Comment by longlho** [comment]
for browsers that old I'd suggest using https://polyfill.io/v3/

**Comment by supreethmr** [comment]
Pollyfill-Library has limited support for locales. polyfill.io is not working for some of the locales like `fr`, `en-AU`, `de` and few more. [pollfyfill-libarary](https://www.npmjs.com/package/polyfill-library) is quite a large in size 
(132MB) compared to formatJS - [IntlDateTimeFormat ](https://www.npmjs.com/package/@formatjs/intl-datetimeformat).

Is there any way that we can make formatJS (should-Polyfill) to work with IE 10 Browser

**Comment by supreethmr** [comment]
It works after including the following polyfills along with @formatjs/intl-datetimeformat/polyfill.
- @formatjs/intl-getcanonicallocales/polyfill
- @formatjs/intl-locale/polyfill

Thanks @longlho for looking into this :)
