### ISSUE TITLE
New react-intl "v5.25.1" and React 18 with IE 11 does't work with value replacement 

### ISSUE THREAD

**Issue by hernanif1** [formatjs/formatjs#3588]
## Which package?
 react-intl "v5.25.1"

## Describe the bug
IE 11 does't work with values replacement 

## To Reproduce
https://github.com/hernanif1/intl-test-ie11

### Codesandbox URL
Codesandbox doesn't work with ie 11

### Reproducible Steps/Repo
git clone git@github.com:hernanif1/intl-test-ie11.git
yarn install
yarn start

### Steps to reproduce the behavior:
with browserstack ie 11 or ie 11 open the url 
https://intl-test-ie11-1nfakdy47-hernanif1.vercel.app/
 
1.the message shows the original variable name instead of the value
![Screenshot 2022-05-09 at 16 37 46](https://user-images.githubusercontent.com/1771727/167434263-8ac22612-aec0-42eb-9587-e698f22f5cef.png)

## Expected behavior
a variable replacement like in other newer browsers
  
![Screenshot 2022-05-09 at 16 37 14](https://user-images.githubusercontent.com/1771727/167434446-b1157b4a-23c9-43fc-847e-14ef1443437d.png)
---

⚠️  It still works with version 5.25.0

**Comment by longlho** [comment]
@batjaa this is likely due to the dependency in `Intl.Locale` so we prob would have to check for that

**Comment by sklawren** [comment]
This bug is in every browser, not just IE11. This is a broken release.
