### ISSUE TITLE
    TypeError: reactIntl.defineMessages is not a function

### ISSUE THREAD

**Issue by selvam-murugan-nu** [formatjs/formatjs#3596]
## Which package?
Since this is a monorepo. Please specify which package this bug report is for.
    "react-intl": "^5.25.0",
## Describe the bug
when i run the test case i am getting below error
TypeError: reactIntl.defineMessages is not a function
### Codesandbox URL

Please include a codesandbox URL if possible

**Comment by longlho** [comment]
repro please?

**Comment by selvam-murugan-nu** [comment]
using this library to defineMessages when i run the test case i am getting this error.
we are using commerce tool 
https://github.com/commercetools/merchant-center-application-kit/issues/2600

**Comment by longlho** [comment]
this seems to be an issue w/ either mocking or multiple versions of `react-intl` being used
