### ISSUE TITLE
Using react-intl with browserify

### ISSUE THREAD

**Issue by santiagoaguiar** [formatjs/formatjs#36]
The react-intl node js module does a:

```
require('./lib/locales');
```

Which includes all locales by default on the module. 

When bundling with [browserify](http://browserify.org/) all the locale data is included on the bundle, which makes the bundle huge.

I think the standard way to fix it is to provide a different entry point for the browser on the packages.json, like: 

```
"browser" : "browser.js"
```

and in browser.js have the same content that in index.js but without the `require('./lib/locales')`.

There are similar issues for intl-relativeformat & intl-messageformat modules.

Would such a fix be ok?

**Comment by steffenmllr** [comment]
Also trying to get this to work with browserify. Is there an example on how to switch and set languages with browserify ?

**Comment by kyleboyle** [comment]
This links will probably be helpful:
https://github.com/gpbl/react-locale-hot-switch
https://github.com/rackt/react-router/issues/484#issuecomment-67749163

**Comment by steffenmllr** [comment]
Thanks @kyleboyle I saw the `react-locale-hot-switch`. I still don't get how to load and or change a local. It there a sample app using browserify and react-intl somewhere?

**Comment by kyleboyle** [comment]
In that project, take a look in i18n/index.js. You just need to use browserify in the same way that webpack is being used to split bundles and async load. Specifically in webpack, require.ensure introduces a bundle split point and does async loading of the split bundle. I'm sure browserify would have a similar mechanism. You can see how the individual language files in that directory are loaded as separate bundles.

**Comment by gpbl** [comment]
The idea behind react-locale-hot-switch is to create a chunk for each language, containing the required files: your localized messages and the various locale-data needed by react-intl. 

When a user changes the language, the relative chunk is injected into the browser (with webpack) and the new localized messages are passed as props to the component tree, forcing the components to re-render. (I have no idea how browserify manages this code injection nor how to create chunks with it)

Anyway I understand it's not a simple task: a fastest way is just to reload the page and let the server include the proper `<script>`s with the localized data.

**Comment by steffenmllr** [comment]
Thanks guys for the help! I took the easy way and just reloaded the page for now :)
