### ISSUE TITLE
[Proposal] Api formatMessage should be simplify

### ISSUE THREAD

**Issue by georgezouq** [formatjs/formatjs#3622]
Since this is not a bug, So I am not following the template.

The API `formatMessage` is too complicated and I think it should be simpler.

From:

```js
intl.formatMessage({ id: 'explicit-id' })
```

To (like a syntactic sugar):

```js
intl('explicit-id')

// and with options
const options = {defaultMessage: 'Confirm Password'}
intl('explicit-id', options)
```

I18n is complicated work, especially for existing projects. I try so hard to replace those words with this API. If it is simpler and smaller, not only my replacement job will easier, but so the code should more easy to read.

If this is ok, I can start a PR for this.

**Comment by petersendidit** [comment]
You can easily create your own hook that simplifies it for you

```js
function useSimpleIntl() {
  const { formatMessage } = useIntl();
  return (message, options) => formatMessage({ id: message, ...options });
}
```

```jsx
function MyComponent() {
  const intl = useSimpleIntl();

  const options = {defaultMessage: 'Confirm Password'}
  return <div title={intl('explicit-id')}>intl('explicit-id', options)</div>;
}
```

**Comment by georgezouq** [comment]
> You can easily create your own hook that simplifies it for you
> 
> ```js
> function useSimpleIntl() {
>   const { formatMessage } = useIntl();
>   return (message, options) => formatMessage({ id: message, ...options });
> }
> ```
> 
> ```js
> function MyComponent() {
>   const intl = useSimpleIntl();
> 
>   const options = {defaultMessage: 'Confirm Password'}
>   return <div title={intl('explicit-id')}>intl('explicit-id', options)</div>;
> }
> ```

@petersendidit Yes, but official support will be easier

**Comment by longlho** [comment]
this is something we're open to but needs to decide on the semantics + a non-trivial amount of work to update our CLI + linters + extractors to support the new syntax.
