### ISSUE TITLE
Generated ID mismatch with the runtime ID. Missing translation issue

### ISSUE THREAD

**Issue by gokatz** [formatjs/formatjs#3624]
## Which package?
Since this is a monorepo. Please specify which package this bug report is for.
formatjs-cli

## Describe the bug
When I use string interpolation in the description field, the output json file don’t have the description field.

App.js:
```
const id = 'foo';

defineMessages({
  foo: {
    defaultMessage: 'foo',
    description: `${id} bar`,
  },
})
```

messages.json
```
{
  "9/u6bg": {
    "defaultMessage": "foo"
  }
}
```

Interestingly, the ID generated in the output json file ('9/u6bg') is different from the one generated by the babel plugin when running the code in browser. This leads to missing translation.

## Expected behavior
The ID generated using the plugin when extracting the messages should be same as the ID generated in runtime using babel

## Desktop (please complete the following information):

- OS: MacOS
- Browser: Chrome
- Version: 100

**Comment by longlho** [comment]
I'd recommend using static string for `description`
