### ISSUE TITLE
formatjs/enforce-id changes double quotes to single quotes with no escape causing parsing error

### ISSUE THREAD

**Issue by zarehb** [formatjs/formatjs#3652]
## Which package?
Since this is a monorepo. Please specify which package this bug report is for.

## Describe the bug
formatjs/enforce-id with
```
idInterpolationPattern: '[sha512:contenthash:base64:6]',
```

`eslint --fix`

input: `defaultMessage: "If you are an agency, enter the client's information.",`
output: `defaultMessage: 'If you are an agency, enter the client's information.', id: 'KvreRI',`

The output has Parsing error

### Codesandbox URL

Please include a codesandbox URL if possible

## Expected behavior
"eslint-plugin-formatjs": "^3.1.5",

**Comment by zarehb** [comment]
I there is an existing id, it auto corrects properly if there is no id it messes with quotes

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by zarehb** [comment]
thanks! @longlho please check this PR for a change proposal https://github.com/formatjs/formatjs/pull/3664

**Comment by zarehb** [comment]
@longlho I tried addressing this but getting the following while setting up the project to run the tests, 

```
ERROR: Analysis of target '//packages/intl-numberformat:generated-test-files_17_test' failed; build aborted: 
INFO: Elapsed time: 38.015s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (805 packages loaded, 13037 targets configured)
FAILED: Build did NOT complete successfully (805 packages loaded, 13037 targets configured)
```

I followed instructions from https://github.com/formatjs/formatjs/blob/main/CONTRIBUTING.md 

This is blocking to setup some automation on my project, appreciate any help
