### ISSUE TITLE
@formatjs/cli depends on tslib

### ISSUE THREAD

**Issue by garycourt** [formatjs/formatjs#3673]
## Which package?
@formatjs/cli

## Describe the bug
This package has a dependency on `tslib`. However, it is not listed in the dependency list in `package.json`.

It's possible to have a hoisted package that is the wrong version.

For example, on my system, I had `tslib@2.0.4` hoisted to the root of my `node_modules` directory. I then got this error when running code from `@formatjs/cli`.

```
TypeError: (0 , tslib_1.__spreadArray) is not a function
    at node_modules/@formatjs/cli/src/extract.js:31:137
    at step (node_modules/tslib/tslib.js:140:27)
    at Object.next (node_modules/tslib/tslib.js:121:57)
    at node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at __awaiter (node_modules/tslib/tslib.js:110:16)
    at processFile (node_modules/@formatjs/cli/src/extract.js:25:34)
    at node_modules/@formatjs/cli/src/extract.js:119:59
    at step (node_modules/tslib/tslib.js:140:27)
    at Object.next (node_modules/tslib/tslib.js:121:57)
```

## To Reproduce
```
yarn add tslib@2.0.4
yarn add @formatjs/cli@5.0.2
npx formatjs extract
```

## Expected behavior
Most other packages in this monorepo have `tslib@2.4.0` listed as a dependency. I believe this package needs it as well.

**Comment by longlho** [comment]
how are you using it?

**Comment by garycourt** [comment]
For my use case, I'm actually calling the APIs from the CLI directly. Something like this:
```ts
import { extract } from '@formatjs/cli';

export const extractFromPaths = async (
  files: string[],
  locale: Locale = 'en',
): Promise<string> => {
  return await extract(files, {
    ...formatjsConfig,
    format: createFormatter(locale),
  });
};
```

The script is being executed by `ts-node@10.8.1` and `typescript@4.7.4`.

**Comment by longlho** [comment]
we package the CLI in a single binary which is why there's no dep. Any reason why you cannot use the binary?

**Comment by garycourt** [comment]
The inputs and outputs to the extract function are business logic dependent in my case, making this is the most convenient way of consuming this tool.

Regardless, what I am raising is a dependency issue. If a user has this package, as well as an older `tslib` package, installed in their development environment, they will run into this issue.

**Comment by longlho** [comment]
we prob would have to make a new package that has deps declared because it's not just tslib, closing this since it's the same issue as #3625
