### ISSUE TITLE
Formatters are not assignable to each other

### ISSUE THREAD

**Issue by garycourt** [formatjs/formatjs#3676]
## Which package?
`@formatjs/intl@2.3.0` and `intl-messageformat@10.1.0` and `typescript@4.7.4`

## Describe the bug
I discovered that the Formatters type between these 2 packages are not consistent or assignable to each other. I was able to produce the follow Typescript error with the below example code:
```
error TS2322: Type 'import("node_modules/@formatjs/intl/src/types").Formatters' is not assignable to type 'import("node_modules/intl-messageformat/src/formatters").Formatters'.
  The types returned by 'getDateTimeFormat(...).formatRangeToParts(...)' are incompatible between these types.
    Type 'IntlDateTimeFormatPart[]' is not assignable to type 'DateTimeFormatPart[]'.
      Type 'IntlDateTimeFormatPart' is not assignable to type 'DateTimeFormatPart'.
        Types of property 'type' are incompatible.
          Type 'IntlDateTimeFormatPartType' is not assignable to type 'DateTimeFormatPartTypes'.
            Type '"unknown"' is not assignable to type 'DateTimeFormatPartTypes'.
```

Based on the names and signatures of these 2 types, I believe they are meant to be compatible with each other. I suspect this is just a typing error, but could possibly be indicative of an obscure bug.

## To Reproduce
I suspect you need to have `strict` mode enabled in your `tsconfig.json` file to reproduce this.

```typescript
import type { Formatters } from 'react-intl';

const formatters = {/*...*/} as Formatters;

formatters.getMessageFormat('', 'en', undefined, {
  formatters, // error TS2322
});
```

**Comment by longlho** [comment]
can you make a codesandbox pls?
