### ISSUE TITLE
Allow default value for arguments

### ISSUE THREAD

**Issue by MortezaT** [formatjs/formatjs#3684]
This is more of a feature request than a bug report

I'm trying to implement some overridable translation which allows user to edit the label in their very own language. 
For example we have this message `"From {price}"` and the user wants to change it to `"Starting from {price}"`.

I found a workaround by using `select` however, I'll need to apply a default key wherever I'm using this translation.
`"{ prefix, select, default { From } other {{ prefix }} } ..."`

It'd be great to have an option like `"{ argument: Default value if empty } ..."`.

**Comment by longlho** [comment]
since this is not in the ICU MessageFormat spec you should make a feature request there https://github.com/unicode-org/message-format-wg
