### ISSUE TITLE
[intl-displaynames] shouldPolyfill crash because of missing Intl

### ISSUE THREAD

**Issue by olessavluk** [formatjs/formatjs#3701]
## Which package?
`@formatjs/intl-displaynames/polyfill` (and others too)

## Describe the bug
After changes from https://github.com/formatjs/formatjs/commit/eb589dbf048fd549d186e87a011a9c767ed94d98 shouldPolyfill check depends on `Intl` which is missing in old Safari 12

## Codesandbox URL

https://codesandbox.io/s/intl-polyfill-bug-i6nf9l?file=/src/index.js

## Screenshots
![image](https://user-images.githubusercontent.com/1577804/177806979-c29dbd94-a479-4a6b-8235-6e3fce883f07.png)

## Additional context

Guess instead it should be wrapped in try/catch and return `true` when the error happens?

**Comment by pyrocat101** [comment]
Will take a look tomorrow.

**Comment by pyrocat101** [comment]
@longlho It looks like you made `shouldPolyfill` depends on the locale matcher, which depends on `Intl.Locale`.

**Comment by longlho** [comment]
yeah prob just have to try catch it
