### ISSUE TITLE
Question: useIntl vs createIntl

### ISSUE THREAD

**Issue by jchabotamica** [formatjs/formatjs#3704]
I understand semantically the difference between these, but are there are any true pros and cons?
We have the need to both render messages outside the component tree (ie in utils functions) and also render messages in things like input placeholders.
In an  attempt to establish some standards in our project, I'd like to understand if we already have the createIntl functionality, is there really any need or benefit to use the useIntl() hook?

Note: We also use the  <FormattedMessage /> component when possible.
We  have a fairly high user base.  Currently use client side rendering (possibly doing a transition in the near future to server side rendering)

**Comment by longlho** [comment]
You can use `createIntl` outside of react, then pass that into https://formatjs.io/docs/react-intl/components/#rawintlprovider and then use `useIntl` in your React tree.
I'd recommend calling `createIntl` only when the params change. With that said, as long as it uses the same cache it prob doesn't make a whole lot of difference in terms of perf

**Comment by jchabotamica** [comment]
Thanks for the response @longlho.  Can you expand on what you mean by "only when the params change"?  
Right now, I'm considering using `<FormattedMessage /> `when applicable, and if you need to use the api (set placeholder text, or use in a utils file, etc.) then just import `formatMessage()` from `createIntl`: 

![image](https://user-images.githubusercontent.com/52013619/178333634-9de5098a-8050-404b-b5c9-fc64512b67ed.png)
Any downsides to doing this and just not using the useIntl() hook?
Again - just trying to set some boundaries and provide our devs with some black and white guidance of what to use when.

Thank you for pointing me in the direction to use RawIntlProvider with the same instance of createIntl by the way!  I will make sure to do that as well.

**Comment by longlho** [comment]
You can do that in environment where `locale` never changes like browser. On the server side you need to maintain 1 instance of `intl` per `locale` and figure out how to pass that to your component properly.

**Comment by titenis** [comment]
@longlho but is there a way to change a `locale` and `messages` of previously created intl object with `createIntl`?
Seems like altering intl objects' locale has no effect and calling `intl.formatMessage` returns default message which was defined as createInlt config.

**Comment by longlho** [comment]
Nope you have to create a new one
