### ISSUE TITLE
intl.formatMeassage type error when passing ReactElement (chunks) 6.0.5

### ISSUE THREAD

**Issue by maxgertzen** [formatjs/formatjs#3707]
Hey, I'm using react-intl version 6.0.5 with react 18.2.
I'm getting the same error as described while using intl.formatMessage (of type IntlShape).

`Type '(item: string[]) => Element' is not assignable to type 'PrimitiveType | FormatXMLElementFn<string, string>'.`

Note that I use the object which `useIntl()` returns.

![image](https://user-images.githubusercontent.com/34470211/178464994-02a39e2c-53d5-4a1f-8f22-4ce7834a0f46.png)

_Originally posted by @maxgertzen in https://github.com/formatjs/formatjs/issues/3633#issuecomment-1181623008_

**Comment by rouliane** [comment]
Exact same problem here, with react-intl 6.0.4 and React 17 :
```typescript
intl.formatMessage(
      {
          defaultMessage: '<b>{filename}</b> was sucessfully shared.',
          id: '+4C9Ii',
      },
      {
          filename,
          b: chunks => <b>{chunks}</b>,
      }
  )
```

**Comment by maxgertzen** [comment]
> Hey, I'm using react-intl version 6.0.5 with react 18.2. I'm getting the same error as described while using intl.formatMessage (of type IntlShape).
> 
> `Type '(item: string[]) => Element' is not assignable to type 'PrimitiveType | FormatXMLElementFn<string, string>'.`
> 
> Note that I use the object which `useIntl()` returns.
> 
> ![image](https://user-images.githubusercontent.com/34470211/178464994-02a39e2c-53d5-4a1f-8f22-4ce7834a0f46.png)
> 
> _Originally posted by @maxgertzen in [#3633 (comment)](https://github.com/formatjs/formatjs/issues/3633#issuecomment-1181623008)_

Last working version - 5.24.8

**Comment by longlho** [comment]
do you have a codesandbox?

**Comment by samwrigley** [comment]
I'm running into the same issue with the following versions: 

```json
"react-intl": "6.0.5",
"react": "18.2.0",
"react-dom": "18.2.0"
"@types/react": "18.0.15",
"@types/react-dom": "18.0.6",
```

I've managed to recreate it in a CodeSandbox @longlho: https://codesandbox.io/s/stoic-murdock-1zkbeq?file=/src/App.tsx

The error seems to be present when using `intl.formatMessage`, but not when using the `FormattedMessage` component:

![Screenshot 2022-07-28 at 20 44 55](https://user-images.githubusercontent.com/17161173/181624207-f5d0fb6d-320f-48ba-b66c-3b49c79f458f.png)

The full TS error message is:

```
const formatMessage: (descriptor: MessageDescriptor, values?: Record<string, PrimitiveType | FormatXMLElementFn<string, string>> | undefined, opts?: Options | undefined) => string (+1 overload)
No overload matches this call.
  Overload 1 of 2, '(descriptor: MessageDescriptor, values?: Record<string, PrimitiveType | FormatXMLElementFn<string, string>> | undefined, opts?: Options | undefined): string', gave the following error.
    Type '(chunks: string[]) => Element' is not assignable to type 'PrimitiveType | FormatXMLElementFn<string, string>'.
      Type '(chunks: string[]) => Element' is not assignable to type 'FormatXMLElementFn<string, string>'.
        Type 'Element' is not assignable to type 'string'.
  Overload 2 of 2, '(descriptor: MessageDescriptor, values?: Record<string, string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | ... 5 more ... | undefined> | undefined, opts?: Options | undefined): ReactNode', gave the following error.
    Type '(chunks: string[]) => Element' is not assignable to type 'string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal | Date | FormatXMLElementFn<...> | null | undefined'.
      Type '(chunks: string[]) => Element' is not assignable to type 'FormatXMLElementFn<ReactNode, ReactNode>'.
        Types of parameters 'chunks' and 'parts' are incompatible.
          Type 'ReactNode[]' is not assignable to type 'string[]'.
            Type 'ReactNode' is not assignable to type 'string'.
              Type 'undefined' is not assignable to type 'string'.
```

**Comment by sct** [comment]
Any updates on this? Experiencing the same issues as above when using `intl.formatMessage`

**Comment by longlho** [comment]
so the workaround is to do 
```
{b: (chunks: React.ReactNode[]) => <b>{chunks}</b>}
```

looks like react 18 removes the recursive part of `ReactNode` decl

**Comment by longlho** [comment]
@pyrocat101 any idea?

**Comment by paularmstrong** [comment]
This is not stale.

**Comment by longlho** [comment]
yeah I took a look but was having a hard time fixing it :-/ no luck so far without dropping some types to `any` which isn't great

**Comment by KontrolG** [comment]
Having the same issue, but with <FormatMessage />

![image](https://user-images.githubusercontent.com/43476781/192319834-331baba5-0e3f-4ec5-a8be-a2746bd4b774.png)


"react-intl": "5.25.0",
"react": "18.0.0",
"react-dom": "18.0.0"
"@types/react": "18.0.6",
"@types/react-dom": "18.0.2",

**Comment by RemyMachado** [comment]
> Having the same issue, but with
> 
> ![image](https://user-images.githubusercontent.com/43476781/192319834-331baba5-0e3f-4ec5-a8be-a2746bd4b774.png)
> 
> "react-intl": "5.25.0", "react": "18.0.0", "react-dom": "18.0.0" "@types/react": "18.0.6", "@types/react-dom": "18.0.2",

Same error:
```
Type error: Type '(chunks: string[]) => JSX.Element' is not assignable to type 'ReactNode'.
  Type '(chunks: string[]) => Element' is missing the following properties from type 'ReactPortal': key, children, type, props
```
But I'm still using v17 of react.js:
"react": "17.0.2",
"react-dom": "17.0.2",
"react-intl": "5.25.1",

I wonder if it's related to #3856

**Comment by jamespearson** [comment]
It doesn't look like this was completed, as the completing PR was later deleted. This issue remains.

**Comment by jrnail23** [comment]
@longlho I'm still having this problem as well.  Can this issue be re-opened, per https://github.com/formatjs/formatjs/issues/3707#issuecomment-1348121598 ?
