### ISSUE TITLE
Support for ICU rounding modes?

### ISSUE THREAD

**Issue by markfswe** [formatjs/formatjs#3716]
## Which package?
`icu-skeleton-parser` I guess? or `icu-messageformat-parser`

## Describe the bug

message-format doesn't respect rounding modes:
 - `rounding-mode-ceiling`
 - `rounding-mode-floor`
 - `rounding-mode-down`
 - `rounding-mode-up`
 - `rounding-mode-half-even`
 - `rounding-mode-half-down`
 - `rounding-mode-half-up`
 - `rounding-mode-unnecessary`
 
 https://unicode-org.github.io/icu/userguide/format_parse/numbers/rounding-modes.html
 https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html#rounding-mode

## To Reproduce

```
new IntlMessageFormat(
  'The price is: {price, number, ::@ rounding-mode-floor}',
  'en-GB'
).format({price: 16})
```

## Expected behavior

10

## Actual behavior

20

## Desktop:

- OS: macOS 12.2.1
- Browser: Firefox 103

**Comment by longlho** [comment]
this has a dependency on https://tc39.es/proposal-intl-numberformat-v3/#new-roundingprecision-options-ecma-402-286 which is neither stage-4 nor polyfilled

**Comment by markfswe** [comment]
Thank you! So.. Should this issue be closed? Or it will be opened intil proposal will be polyfilled?

**Comment by longlho** [comment]
we can keep it open
