### ISSUE TITLE
Custom options for date formatting in messages

### ISSUE THREAD

**Issue by Lukas-Kullmann** [formatjs/formatjs#3728]
Hey there,

in the [documentation](https://formatjs.io/docs/core-concepts/icu-syntax#date-type), it says that

> Internally [the `date` message syntax] uses the `Intl.DateTimeFormat` API. You can define custom values for the format element, which are passed to the `Intl.DateTimeFormat` constructor.

However, there is no example on how to actually do that. I would like to do a full date time formatting with `{ dateStyle: 'medium', timeStyle: 'medium' }` is that possible? And if so, how?

**Comment by pyrocat101** [comment]
Theoretically you can achieve that with skeletons (e.g. `{value, date, ::yyyyMMh}`). But it looks like [none](https://github.com/formatjs/formatjs/blob/3171c3f3867fe5c2e79545f655c0abb6dc40d626/packages/icu-skeleton-parser/date-time.ts) of the skeleton sequence maps to medium.

cc @longlho

**Comment by longlho** [comment]
hmm you can define a custom format. See https://github.com/formatjs/formatjs/blob/main/packages/react-intl/tests/unit/components/message.tsx#L349 for an example
