### ISSUE TITLE
Intl fails to format month as `numeric`

### ISSUE THREAD

**Issue by JesusTheHun** [formatjs/formatjs#3746]
## Which package?

`@formatjs/intl@2.3.1`

## Describe the bug

`formatDate(date, { ..., month: 'numeric' })` should format the month accordingly but it doesn't.
It also fail to format the day as numeric when the month is numeric.

## To Reproduce
```js
const date = Date.UTC(2022, 7, 5);
createIntl({ locale: 'fr-FR' }).formatDate(date, { year: 'numeric', month: 'numeric', day: 'numeric' });

// KO
// Expected : 5/8/2022
// Actual : 05/08/2022

createIntl({ locale: 'fr-FR' }).formatDate(date, { year: 'numeric', month: 'long', day: 'numeric' });

// OK
// Expected : 5 août 2022
// Actual : 5 août 2022
```
### Codesandbox URL

https://codesandbox.io/s/magical-hugle-vx3nl0?file=/src/index.ts

**Comment by longlho** [comment]
This is consistent with how Chrome & FF format it so not a bug.
```
const date = Date.UTC(2022, 7, 5);
new Intl.DateTimeFormat('fr-FR',  { year: 'numeric', month: 'numeric', day: 'numeric' }).format(date)
// '04/08/2022'
```

**Comment by JesusTheHun** [comment]
For posterity and anyone reading this. After searching into Mozilla bugs, I found this : https://bugzilla.mozilla.org/show_bug.cgi?id=1751833#c3 .

> the translator decision should override the developer decision from the components bag

The browser can decide you're wrong and display the date in the format he likes more.
Apparently we've learned nothing from history.

**Comment by longlho** [comment]
Everyone uses CLDR as the data source which is contributed by translators so I suggest you submit a bug there

**Comment by JesusTheHun** [comment]
My issue is not the format presets from CLDR. 
It's perfectly fine -even desirable- to offer presets, "I want a date in a short format for language X => here you go". 

My issue is that the function supports an argument that allow you to somewhat-precisely define the format you want (here `numeric`) and yet ignores your decision as a developer. Like the browser knows better than you what you need... 

This is not a CLDR issue, it's a governance issue. Someone else decides what is best for you. 
Like we've not seen how that turns out before...
