### ISSUE TITLE
Performance regression in `DateTimeFormat`

### ISSUE THREAD

**Issue by romainmenke** [formatjs/formatjs#3747]
_I don't currently have much capacity to investigate or provide a lot of extra info :/_

We received a request to bump `DateTimeFormat` to `5.0.2` in the polyfill-library : https://github.com/Financial-Times/polyfill-library/pull/1186

After this change our test suite which checks for polyfill interop issues (which includes all possible polyfills) no longer passes.
Tests in IE, Firefox and Chrome have timeouts.

Interestingly Edge and iOS seem unaffected.

I am unsure how to provide a reproduction other than running the test suite of the polyfill library with `5.0.2`.

The url to run the test suite in this mode is : http://bs-local.com:9876/?includePolyfills=yes&always=no&polyfillCombinations=yes

We upgraded from `4.1.0` to `5.0.2` : https://github.com/formatjs/formatjs/compare/a5b84584c7fbfa961a6a191be928c799e19b8271...1bf7bad888618e43b1ded8bdccc82612e44fbd57

`4.1.0`: https://github.com/formatjs/formatjs/commit/a5b84584c7fbfa961a6a191be928c799e19b8271
`5.0.2`: https://github.com/formatjs/formatjs/commit/1bf7bad888618e43b1ded8bdccc82612e44fbd57

**Comment by longlho** [comment]
Thanks for reporting I'll take a look as soon as I can

**Comment by romainmenke** [comment]
@longlho said :

hmm it seems weird that IE9 is ok but not IE10/11? I'd say perf regression is expected to a certain degree, since CLDR & IANA data only gets bigger over time. Those 2 are the only major changes from 4.1.0 to 5.0.0 and it's not something we can fix/revert.

Algorithm-wise it's stable cause the spec hasn't changed

------

_I've moved the discussion back here because I fear I will lose track of it in a closed PR_

------

IE9 passes because its test suite was split together with IE8 a while back to work around out of memory issues.

But it had a huge increase in duration: `180s` vs `700s`

IE9 has 102 features, so it needs to process the polyfill bundle 102 times _(I/O, parsing, ...)_.

The overhead on average of including all the polyfills in all the tests used to be ±`1.2s` per test.
After the update it became ±`6.3s`.

What worries me is that this is a multiple of what it was before.
Was so much data added between `4.1.0` and `5.0.2`?


```
 • Browser: ie/9.0 Test config: targeted /          / shard 2   ✓ 922 tests  60 seconds to complete
 • Browser: ie/9.0 Test config: targeted / combined / shard 2   ✓ 924 tests  173 seconds to complete
```

```
• Browser: ie/9.0 Test config: targeted /          / shard 2   ✓ 925 tests  76 seconds to complete
• Browser: ie/9.0 Test config: targeted / combined / shard 2   ✓ 927 tests  719 seconds to complete
```

**Comment by romainmenke** [comment]
Seems to have been introduced in `4.3.0`

https://github.com/formatjs/formatjs/compare/ffa3ca0c28d34ea769aa52920fc55a8dba8a2d7c...202a7a984de558c5b0034a646b43659cdf638152

**Comment by romainmenke** [comment]
Best guess at the moment : 

- `shouldPolyfill` uses `match` from `intl-localematcher` (introduced in `4.3.0`).
- This seems to have a lot of `Set` operations.
- The `Set` implementation in `polyfill-library` has a performance issue

The performance issues with `Set` are known : https://github.com/Financial-Times/polyfill-library/issues/636

That this is the cause is speculation.
I don't know if the `Set` operations are numerous enough to have this impact.

**Comment by romainmenke** [comment]
@longlho I am more and more convinced that this is an issue with another polyfill (like `Set`).
Something that wasn't used much before, is now and has a performance issue.

So going to close this issue here.
If we do find out it is something in formatjs we can always reopen :)

Thank you for checking anyway!
