### ISSUE TITLE
Extraction gets an empty en.json

### ISSUE THREAD

**Issue by moonerr** [formatjs/formatjs#3757]
## Which package?
formatjs/cli I think

## Describe the bug
Recently our application has upgraded the typescript and React 18. Formatjs has also been kept up to date, version 5.0.8.
But when I run the cmd `yarn extract 'src/**/*.ts*' --ignore='**/*.d.ts' --out-file lang/en.json --id-interpolation-pattern '[sha512:contenthash:base64:6]'` 
The file produced en.json is empty with only a { }
![image](https://user-images.githubusercontent.com/56371692/184058611-bbb75ba4-8a50-4798-b8a5-b4c48df83f14.png)

Sorry I could not reproduce it. Just wondering if anybody knows what can cause this issue.

## Desktop (please complete the following information):

- OS: [Win10
- Browser: Chrome
- Version: 104

## Additional context
typeScript 4.3.5
React 18.2.0

**Comment by pyrocat101** [comment]
We won't be able to do anything about it unless you have a repro case.
