### ISSUE TITLE
@formatjs/cli 5.0.8 is exported to npm without bin folder

### ISSUE THREAD

**Issue by sharifhh** [formatjs/formatjs#3776]
## Which package?
@formatjs/cli 5.0.8

## Describe the bug
There is no bin folder when I upgrade to 5.0.8 and it doesn't work anymore, I had to downgrade to 5.0.7

### Reproducible Steps/Repo

1. yarn add @formatjs/cli@5.0.8
2. yarn formatjs
3. see the error.

**Comment by atarek12** [comment]
Same here, I got `error Command "formatjs" not found.` after upgrading to @formatjs/cli 5.0.8

**Comment by longlho** [comment]
Yeah we had a bad publish will fix tonight

**Comment by longlho** [comment]
fixed in 5.0.9
