### ISSUE TITLE
Cannot auto generate translation ids with Jest

### ISSUE THREAD

**Issue by plourenco** [formatjs/formatjs#3789]
## Which package?
"react-intl": "6.1.0"

## Describe the bug
Hi,

I've setup formatjs with a couple translations and used `babel-plugin-formatjs` for automatic generation of translation ids. This would avoid setting an explicit id on every single translation. 

The following has worked flawlessly in development, however, as I've started **testing** components that included translations I noticed Jest seems to be ignoring the plugin.

### Codesandbox URL

https://codesandbox.io/s/admiring-currying-0phokz

### Reproducible Steps/Repo

1. Run `yarn dev`: The app will render as expected.
2. Run `yarn test`: Jest will not be able to compile as formatjs will throw:
```
[@formatjs/intl] An `id` must be provided to format a message.
```

**Comment by longlho** [comment]
this seems to be a `next/jest` issue. Using raw `jest` config w/o `next/jest` works

**Comment by sethbro** [comment]
I am not using Next.js but encountered this problem. I wound up upgrading all `@babel` packages (including `babel-jest` & `babel-plugin-formatjs`), but only after I upgraded to jest 29 did the issue go away.
