### ISSUE TITLE
Feature request: flag to keep existing messages in extracted files

### ISSUE THREAD

**Issue by jakubriedl** [formatjs/formatjs#3800]
Hi,
we have a case where some of our message ids are (semi)dynamic and because of that they can't be extracted. That's expected, but when we add them manually to the `en.json` messages file they'll get removed next time when we run `extract`

example (very simplified) component:
```tsx
const Component = () => {
   const { variant, label } = useData()

   return <FormattedMessage id={`component.${variant}`} defaultMessage={label} />
}
```

we would appreciate if there was a flag on `extract` cli to keep existing messages, for example
```
formatjs extract 'src/**/*.ts*' --out-file locales/en.json --format smartling --keep-old-messages
```

Nice to have feature on top of that could be to list those keys so developer can review which can be manually deleted

And the nicest solution that would be if the extractor could detect that `component.*` is used and keep those matching the pattern but delete other, but I'm not sure if it's possible. Maybe using some pragma we could add?

**Comment by jakubriedl** [comment]
For now I've workaround this by using Node API and custom script to merge the files before writing

```ts
#!/usr/bin/env node

import { extract as extractMessagesAsString } from "@formatjs/cli-lib"
import { compareMessages } from "@formatjs/cli-lib/src/formatters/smartling.js"
import glob from "fast-glob"
import { readFileSync, writeFileSync } from "fs"
import jsonStringify from "json-stable-stringify"
import { resolve } from "path"

const OUT_FILE = resolve(process.cwd(), "./locales/en.json")

const readStaleMessages = (): Record<string, { message: string }> => {
  try {
    return JSON.parse(readFileSync(OUT_FILE).toString())
  } catch (e) {
    return {}
  }
}

async function extract() {
  const files = await glob("src/**/*.ts*", { ignore: ["**/*.d.ts"] })
  const extracted = await extractMessagesAsString(files, {
    format: "smartling",
  })

  const messages = JSON.parse(extracted)
  const staleMessages = readStaleMessages()

  const oldKeys = Object.keys(staleMessages).filter(key => !(key in messages))
  if (oldKeys.length) {
    console.warn(
      "Old translations were found in `en.json`, please check if they're still relevant and delete obsolete.\n - " +
        oldKeys.join("\n - ")
    )
  }

  const result =
    jsonStringify(
      { ...staleMessages, ...messages },
      { space: 2, cmp: compareMessages }
    ) + "\n"

  writeFileSync(OUT_FILE, result)
}

extract()
```

**Comment by longlho** [comment]
yeah the Node API is exactly for this purpose. Or you don't wanna write a custom script you can use https://github.com/mikefarah/yq to merge those files together

**Comment by jakubriedl** [comment]
Yes this work and is sufficient for us now, but would be great if formatjs had a way how to specify keys that should be kept in the codebase. Ideally parsed out form the template string, or through some pragma. But now all meta tags are added to all messages so it makes it very impractical.

If for example we could do something like this and keep all the matched keys in the file it would be much better as it would automatically clean the old messages

```tsx
const Component = () => {
   const { variant, label } = useData()

   // @intl id:component.* defaultMessage: description:"Component with dynamic label"
   return <FormattedMessage id={`component.${variant}`} defaultMessage={label} />
}
```

**Comment by Demetri0** [comment]
I wanna up this question, I was really surprised that formatjs doesn't merge existing translations with new one during extraction and just override everything that was already translated.

**Comment by longlho** [comment]
cause the defeats the whole purpose of automatically managed catalog file, e.g if u delete a string usage it's also gone from the catalog file. If u have a static set of messages u wanna inject in, you can merge them separately outside of this tool.
