### ISSUE TITLE
intl-messageformat does not take number skeleton into account

### ISSUE THREAD

**Issue by loudjanilef** [formatjs/formatjs#3848]
## Which package?
intl-messageformat

## Describe the bug
Any ICU skeleton specified after the number format in a message doesn't seem to be taken into account

With the following message :

`"This value should be displayed with the .# format (At most 1 fraction digit) : {value, number, .#}"`

The output of the following function :

```ts
new IntlMessageFormat(
  "This value should be displayed with the .# format (At most 1 fraction digit) : {value, number, .#}",
  "en-GB"
).format({ value: 0.524251 })
```

should be : `This value should be displayed with the .# format (At most 1 fraction digit) : 0.5`.
It is : `This value should be displayed with the .# format (At most 1 fraction digit) : 0.524`.

Any other skeleton written according to [this documentation](https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html) produces the same output.

### Codesandbox URL

https://codesandbox.io/s/sad-panka-k9cuwe?file=/src/index.ts

### Reproducible Steps/Repo

1. Go to '/src/index.ts'
2. Check that the skeleton is correct (.#)
3. See error: The output displayed in the preview tab is not formated according to the skeleton (.###)

## Expected behavior
The output should be formated according to the skeleton.
Here, the output always has the same .### format

## Desktop (please complete the following information):

- OS: Windows10
- Browser: Firefox
- Version: 104.0.2

## Additional context
I mentionned this problem at first on the `next-intl` repo : https://github.com/amannn/next-intl/issues/127 and it appeared that the problem comes from the `intl-messageformat` package

**Comment by carrot-sticks** [comment]
@loudjanilef You have a bug (or we could say that docs should be imporved). 

You need to put `::` before you write custom format. i.e.

```ts
let test = new IntlMessageFormat(
  "This value should be displayed with the .# format (At most 1 fraction digit) : {value, number, ::.#}",
  "en-GB"
).format({ value: 0.524251 });
```

**Comment by loudjanilef** [comment]
Oh, I am very sorry 😐
It is indeed in the "overview" part of your documentation, I missed that.
Thank you for your answer
