### ISSUE TITLE
Extract will replace two single quotes with one

### ISSUE THREAD

**Issue by candunaj** [formatjs/formatjs#3870]
When you run the following command with flatten then two single quotes are replaced with one. When flatten is not used then everything works as expected.
```
npm run extract --flatten .....
```
In the following example, all variables are suddenly escaped because they are inside single quotes.
```
formatMessage( { 
  defaultMessage: "Peter''s brother {name1} is taller than {name} who is Peter''s friend." 
});
```
is extracted to
```
"c59qW5": {
  "translation": "Peter's brother {name1} is taller than {name} who is Peter's friend."
}
```

Another example. After extraction, the name variable is escaped.
```
formatMessage( { 
  defaultMessage: "Name: ''{name}''." 
});
```
is extracted to
```
"c59qW5": {
  "translation": "Name: '{name}'."
}
```

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
for example 1, you don't need to escape `Peter''s` because apostrophe escape only works if it's actually escaping something (e.g `{` or `#`). `Peter's` is just fine.
