### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by CodeAndWeb** [formatjs/formatjs#3876]
Hi,

I've created 2 pull requests which update the documentation. They unfortunately fail - but this is because the main branch does not work at the moment. They don't touch any code.

- https://github.com/formatjs/formatjs/pull/3875
- https://github.com/formatjs/formatjs/pull/3874

Can you maybe accept them directly?

Best
Andreas

**Comment by CodeAndWeb** [comment]
Thanks for the merge. How long does it take until the changes appear in the documentation?

**Comment by longlho** [comment]
Tbd our doc pipeline isn't working currently

**Comment by CodeAndWeb** [comment]
Is there any update when the pipeline will be fixed?

I've made some more changes: https://github.com/formatjs/formatjs/pull/3891/commits
