### ISSUE TITLE
FormattedDate not localizing to pt-PT using month="short"

### ISSUE THREAD

**Issue by ruinobreferreira** [formatjs/formatjs#3877]
## Which package?
`react-intl`

## Describe the bug
While trying to localize a date to `pt-PT` with `month="short"` locale it does not work properly.

### Codesandbox URL

https://codesandbox.io/s/crazy-wind-8mo05c

## Expected behavior

The output of the date with the `pt-PT` locale using `month="short"` isn't localized.<br>
We see other formats like `month="long"` working and the `month="short"` should be an abbreviated form of that month.

## Screenshots

There's a Codesandbox

## Desktop (please complete the following information):

- OS: macOS Monterey version 12.6 (21G115)
- Browser: Chrome
- Version:  Version 106.0.5249.103 (Official Build) (x86_64)

## Additional context

We can also see an example working of the `pt-BR` locale also present in the Codesandbox and the result should be pretty close.

**Comment by longlho** [comment]
this looks like a chrome issue 
```
new Intl.DateTimeFormat('pt-PT', {year: 'numeric', month: 'short', day: 'numeric'}).format(new Date()) 
// 17/10/2022
```

**Comment by ruinobreferreira** [comment]
It's an issue wiith CLDR `dateFormats` for **pt-PT** locale.

```json
"dateFormats": {
    "full": "EEEE, d 'de' MMMM 'de' y",
    "long": "d 'de' MMMM 'de' y",
    "medium": "dd/MM/y",
    "short": "dd/MM/yy"
},
```

**Comment by longlho** [comment]
That's not the right databag btw. I'd start w Chrome first

**Comment by ruinobreferreira** [comment]
https://unicode-org.atlassian.net/browse/CLDR-16093
