### ISSUE TITLE
Add `exports` map or `"type": "module"`

### ISSUE THREAD

**Issue by benmccann** [formatjs/formatjs#3878]
## Which package?
I encountered it in `intl-messageformat`, but it's probably present in additional packages

## Describe the bug
The ESM version is referred to only with the `module` field, but that is not part of the Node.js spec and will only work if you first bundle the code. You must include `exports` for the ESM version to be accessible in an unbundled Node program

https://nodejs.org/api/packages.html#package-entry-points

## To Reproduce
Load `intl-messageformat` from a Node script without a bundler and it will load the CJS version rather than the ESM version

**Comment by dominikg** [comment]
see https://publint.bjornlu.com/intl-messageformat@10.2.0

note that adding type:module and/or and exports map can be a breaking change for current users that rely on cjs.
It is possible to improve the current situation in a non-breaking way by using the `.mjs` extension for esm files.

see https://github.com/sheremet-va/dual-packaging or https://antfu.me/posts/publish-esm-and-cjs for ways to do proper dual packaging for cjs and esm.

**Comment by benmccann** [comment]
> It is possible to improve the current situation in a non-breaking way by using the .mjs extension for esm files.

That would have no effect without also adding an `exports` map or setting `"type": "module"`. The `.mjs` extension is a Node thing, but Node isn't using the ESM files at the moment

**Comment by longlho** [comment]
what issues are you having and do you have a codesandbox to repro? TBH I don't wanna waste anymore time on changing module stuff unless something's breaking?

**Comment by benmccann** [comment]
It's not broken, but it will not load the ESM version which limits the benefit of distributing an ESM version. Longer-term, it'd be best to drop the CJS version altogether and just set `"type": "module"`, but that would be a breaking change, so you'd probably want to do it as part of a major version bump.

**Comment by longlho** [comment]
kk I'll close this as there doesn't seem to be any reproducible issues.
