### ISSUE TITLE
Intl.DateTimeFormat for bs locale does not respect local culture 

### ISSUE THREAD

**Issue by binlinseattle** [formatjs/formatjs#3886]
## Which package?
Intl.DateTimeFormat

## Describe the bug
The short datetimeformat for bs(Bosnian) is shown as  2020-12-19 instead of 19.12.2020, see below screenshot for details.

Codesandbox URL
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

1, open a web browser(Edge, Chrome or Safari).
2, go to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat
3, change language to bs
4, click "run" to see the result.

## Expected behavior

    the short date should be:   18. 10. 2022.

## Screenshots
![image](https://user-images.githubusercontent.com/461266/196499110-9c806667-8664-426c-99a2-20392f4dab70.png)

## Desktop (please complete the following information):

- OS: [Windows, iOS]
- Browser [Edge chrome, safari]
- Version [all versions]

**Comment by longlho** [comment]
This is a chrome/cldr issue so you can file a report against them
