### ISSUE TITLE
Wrong currency mappings for 'unit-width-short' and 'unit-width-iso-code'

### ISSUE THREAD

**Issue by JohnBrinkman** [formatjs/formatjs#3887]
## Which package?
icu-skeleton-parser

## Describe the bug
number.ts maps unit-width stems to currencyDisplay options [here](https://github.com/formatjs/formatjs/blob/main/packages/icu-skeleton-parser/number.ts#L237-L251)
However the mappings for 'unit-width-short' and 'unit-width-iso-code' are reversed.  'unit-width-iso-code' should map to `currencyDisplay: 'code'` and 'unit-width-short' should map to `currencyDisplay: 'symbol'`.

Reference the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#currencydisplay)

## To Reproduce

Parse a skeleton such as "unit-width-iso-code currency/USD".  it produces:
```
{
  currency: "USD"
  currencyDisplay: "symbol"
  style: "currency"
}
```

## Expected behavior
The skeleton: "unit-width-iso-code currency/USD"
should produce: 
```
{
  currency: "USD"
  currencyDisplay: "code"
  style: "currency"
}
```

## Desktop (please complete the following information):

- OS: all
- Browser all
- Version 1.3.14

## Smartphone (please complete the following information):

- Device: all
- OS: all
- Browser all

**Comment by rjensen** [comment]
This is still a valid bug.
