### ISSUE TITLE
intl-messageformat crashes for locales ['ph-fil']

### ISSUE THREAD

**Issue by PoltP** [formatjs/formatjs#3894]
*intl-messageformat* _issue_

`intl-messageformat` crashes for locales ['ph-fil']

Our app uses Phillipinian 'ph-fil' locale for localisation. It crashes after updating `intl-messageformat` from version "9.3.6" to "9.13.0" because of `Intl.NumberFormat.supportedLocalesOf` or `new Intl.Locale('ph-fil') ` crashes for this locale.

To reproduce it, please run `Intl.NumberFormat.supportedLocalesOf(['ph-fil'])` or `new Intl.Locale('ph-fil')` inside the browser console - it will crash, but you are using corresponding code inside the `formatjs/packages/intl-messageformat/src/core.ts` to resolve locale:
```
static resolveLocale = (
    locales: string | string[]
  ): Intl.Locale | undefined => {
    if (typeof Intl.Locale === 'undefined') {
      return
    }
    const supportedLocales = Intl.NumberFormat.supportedLocalesOf(locales)
    if (supportedLocales.length > 0) {
      return new Intl.Locale(supportedLocales[0])
    }

    return new Intl.Locale(typeof locales === 'string' ? locales : locales[0])
  }
  ```
  
Our app does not require to resolve it, we are using `ember-intl` and `intl-messageformat` is a dependency for this package.
Could you please do something to exclude this method and allow library work as earlier?

**Comment by longlho** [comment]
![Screen Shot 2022-10-28 at 11 11 51 PM](https://user-images.githubusercontent.com/198255/198797700-3502d925-e436-4c0d-ae5d-3da4c1854795.png)
it doesn't crash for me
