### ISSUE TITLE
[intl-displaynames] shouldPolyfill has different and unexpected return value

### ISSUE THREAD

**Issue by Haraldson** [formatjs/formatjs#3895]
## Which package?
`intl-displaynames`

## Describe the bug
I’m currently using 4 different `Intl` packages:

```javascript
import { shouldPolyfill as shouldPolyfillPluralRules } from '@formatjs/intl-pluralrules/should-polyfill'
import { shouldPolyfill as shouldPolyfillDisplayNames } from '@formatjs/intl-displaynames/should-polyfill'
import { shouldPolyfill as shouldPolyfillDateTimeFormat } from '@formatjs/intl-datetimeformat/should-polyfill'
import { shouldPolyfill as shouldPolyfillRelativeTimeFormat } from '@formatjs/intl-relativetimeformat/should-polyfill'
```

The result of calling these functions looks like this:
```javascript
shouldPolyfillPluralRules() // -> undefined
shouldPolyfillDisplayNames() // -> 'en'
shouldPolyfillDateTimeFormat() // -> undefined
shouldPolyfillRelativeTimeFormat() // -> undefined
```

Having `'en'` returned to me instead of `undefined` makes me unable to use the `shouldPolyfill()` method in an if test to determine whether I need to import polyfills.

## To Reproduce
Import and call `intl-displaynames`’ `shouldPolyfill()` method.

### Codesandbox URL
https://codesandbox.io/s/laughing-grass-b3iwio?file=/src/index.js

## Expected behavior
I expect `intl-displaynames`’ `shouldPolyfill()` method to work like those of the other packages.

## Desktop (please complete the following information):

- OS: macOS Ventura 13.0
- Browser Version 106.0.5249.119 (Official Build) (x86_64)
- Version 6.1.4

**Comment by Haraldson** [comment]
With the response time in this repo, you might want to tweak your GitHub actions, @formatjs team.

**Comment by Haraldson** [comment]
Bad bot.

**Comment by Haraldson** [comment]
Naughty bot! No Christmas presents for you this year.

**Comment by Haraldson** [comment]
That's not how to wish a happy new year, bot.

**Comment by Haraldson** [comment]
Down, Bot. Not before a human maintainer has acknowledged this issue's existense in some form.

**Comment by longlho** [comment]
hmm not sure I understand your issue. `shouldPolyfill` returning a truthy value means you should polyfill it. In this case looks like you should polyfill `Intl.DisplayNames`

**Comment by Haraldson** [comment]
@longlho I have no idea why I can’t use just the `Intl.DisplayNames` module as the other ones. but looking at its source code, I am seeing a lot more hacks in it than in the other modules.

I’m not really using the ‘does this module support this specific locale’ way of testing for polyfilling needs – if `shouldPolyfill()` (without specifying `locale`) returns truthy I just polyfill for all my app’s languages as I need the support loaded before loading any of the other languages anyway.

What I’m experiencing is that this bit of code, which asynchronously imports the locale-data for specified locales, simply doesn’t work when it comes to `Intl.DisplayNames`. For all I know this is due to how just that module is set up with export paths or whatnot, but it’s simply not working:

```js
const imports = ['en', 'nb']
    .map(locale => import(`@formatjs/intl-displaynames/locale-data/${locale}`))

await Promise.all(imports)
```

`en.js` and `nb.js` exist – just as they do in the other modules’ `locale-data` folders.

**Comment by Haraldson** [comment]
@longlho What I also don't get is that support for this is reported to be 100% in all major modern browsers – so why would it report back that English needs polyfilling?

**Comment by longlho** [comment]
That means they have a bug that we detected and haven't shipped the fix yet.
