### ISSUE TITLE
FormattedDateTimeRange not working on Safari

### ISSUE THREAD

**Issue by MoSattler** [formatjs/formatjs#3903]
See the docs website

![Screenshot 2022-11-10 at 14 49 36](https://user-images.githubusercontent.com/64152453/201109017-dc911755-632c-4717-b03d-0d5650180708.png)

**Comment by MoSattler** [comment]
It's still a current issue

**Comment by pyrocat101** [comment]
Do you have a repro codesandbox?

I cannot repro on website from your example:

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/541540/205214231-13fb6c13-292f-47ca-8413-ef77712c6d47.png">

**Comment by MoSattler** [comment]
@pyrocat101 On Chrome it works for me. It seems to be an issue on Safari only. You can reproduce it by looking at the docs in Safari.
<img width="870" alt="Screenshot 2022-12-02 at 09 37 51" src="https://user-images.githubusercontent.com/64152453/205251550-608aec1b-2e01-44d3-8e29-674eb7becc35.png">
<img width="870" alt="Screenshot 2022-12-02 at 09 38 01" src="https://user-images.githubusercontent.com/64152453/205251577-802892f2-dce7-44f1-9b12-61e435512f97.png">

**Comment by MoSattler** [comment]
It's still an issue in safari

**Comment by MoSattler** [comment]
It's still an issue in safari

**Comment by MoSattler** [comment]
Looks like this issue of formatjs not working in safari Is a wontfix, so I close this issue.
