### ISSUE TITLE
Redudancy removal opportunities

### ISSUE THREAD

**Issue by igorgatis** [formatjs/formatjs#3951]
It seems that produced translation code has a significant amount of redundancy.

Regarding the Id: each ID appears (1 + N) times in the output, where n is the number of locales. There is also a lot of repeated id prefix redundancy as well (eg. `app.components.foo` and `app.components.bar`).

Regarding the translated message, it often get's repeated at least once in the default locale and the value of `defaultMessage`. The `defaultMessage` field by itself is quite long (14 characters) and gets repeated for every message.

Are there any plans to improve this?

**Comment by longlho** [comment]
Hmm this is exactly what gzipping solves

**Comment by igorgatis** [comment]
Well... not really. Final JS is full of repetition which slows down parsing and execution and uses a lot of memory.

**Comment by longlho** [comment]
Do u have any numbers or perf stats? U don't have to bundle defaultMessage there's an option to remove that

**Comment by igorgatis** [comment]
The company I work for has a handful of PWAs and translations occupy in average ~15% of the total JS downloaded. We're trying to optmize FID numbers and translations poped up in our bundle-analyzer-report.html.

IMO, if gzip fixed all redudancy issues, why do we bother minifying JS?

**Comment by longlho** [comment]
U can try enabling defaultMessage removal in our plugins

**Comment by igorgatis** [comment]
I'd like to get rid of IDs as well.  The optimization I had in mind was to remove global IDs from *final* bundle.

The `messages.js` and `some-locale.json` files would still exist just as they are today, including the IDs. During build time, these files would be used to generate a new file called `translation-table.js` which includes all the translations listed in order (sorted by their ids). Build also generates a new file called `messages.min.js` which is optimized version of `messages.js`, very small, pointing to strings under `translation-table.js` using their list index, instead of the id.

This way, all changes would be made to `babel-plugin-formatjs`.

Here is an example:

`messages.js`
```javascript
export default = definedMessages({
    hello: {
        id: 'app.hello',
        defaultMessage: 'Hello'
    },
    goodbye: {
        id: 'app.goodbye',
        defaultMessage: 'Goodbye'
    },
})
```
`en-US.json`:
```json
{
    "app.hello": "Hello",
    "app.thanks": "Thanks",
}
```
`pt-BR.json`:
```json
{
    "app.hello": "Olá",
    "app.thanks": "Obrigado",
}
```

The new asset, `translation-table.js` would look like:
```javascript
const NAMESPACE = '<some-generated-digest-hash>.';
const TRANSLATIONS = [
  /*0:headers*/ ['default', 'en-US', 'pt-BR'],
  /*1:app.goodbye*/ ['Goodbye', null, null],
  /*2:app.hello*/ ['Hello', null, 'Olá'],
];
// Notice translation for "hello" in en-US was removed because it is equal to default.
// Also notice that app.thanks was removed since it was never referenced.

export function getMessage(index) {
  return {
    id: NAMESPACE + index,
    defaultMessage: TRANSLATIONS[index][0],
  };
}

export function getTranslations(locale) {
  let column = TRANSLATIONS[0].indexOf(locale);
  if (column < 0) column = 0;
  let map = new Map();
  for (let i = 1; i < TRANSLATIONS.length; ++i) {
    map[NAMESPACE + i] = TRANSLATIONS[i][column];
  }
  return map;
} 
```

`messages.min.js` would look like:
```javascript
import { getMessage as M } from "/path/to/translation-table";

export default {
  hello: M(2),
  goodbye: M(1),
};
```

During `IntlProvider` construction, a call to `getTranslations(locale)` should be made.

**Comment by longlho** [comment]
U can specify a custom id gen fn to do it. But IDs need to be deterministic and fairly unique, otherwise your rollback would be painful due to deployment skew between assets.
Sort order isn't really uniquely identifying a string so when u have deployment skew it'll render the wrong string

**Comment by igorgatis** [comment]
Actually, `NAMESPACE` + index is unique as long as `NAMESPACE` is unique among builds.

Anyways, `overrideidfn` and `removeDefaultMessage` should help. Thanks for the tip. It would be nice to remove dependency on explicit ids though.
