### ISSUE TITLE
Dynamically change locale with vue-intl

### ISSUE THREAD

**Issue by mediafreakch** [formatjs/formatjs#3954]
Hello,

I got here coming from [vue-i18n](https://kazupon.github.io/vue-i18n/), which dropped support for ICU message format in the latest version (v9). They suggest to use vue-intl as a replacement.

I attempt to migrate my code base using the following steps:

1. Transform locales to a flat JSON structure using `npx flat src/locales/en.json > src/locales/en-flat.json`
2. Use a custom plugin that transforms vue-18n's `$t('myKey')` function into `$intl.formatMessage({ id: 'myKey' })`
3. **(missing / how?)** Dynamically switch locale

I'm stuck on the third step. The `$intl` object doesn't seem to provide any function to dynamically switch its messages. And since it has been installed as a plugin, I don't understand how to re-create it at runtime.

Made a stackblitz example that shows my (simplified) setup: 
https://stackblitz.com/edit/vitejs-vite-hba5fi?file=src/components/HelloWorld.vue

Could you provide some guidance?

**Comment by mediafreakch** [comment]
From the following [discussion](https://github.com/formatjs/formatjs/discussions/2464#discussioncomment-256012) it became clear, that changing locales intentionally isn't currently supported: 

> Switching locale sounds really handy in theory but in practice it's pretty rare that u need locale hot reloading. From the production usage I've seen a locale switch comes with a lot of rebootstrapping (new assets, new translations, new polyfills, region locking...) so if u want to hot reload locale u basically have to hot reload a ton of things. At that point it leaks memory easily if u don't clean up properly so reloading the page becomes much easier to manage.

Switching from `vue-i18n` this was unexpected for me and might be a reason not to switch for others.  
For myself, I'll try to continue without this feature at the moment. I noticed thought, that as soon as you rely on application logic to determine the locale (such as retrieving it from a vuex store), you'll need to be able to switch locale dynamically.

**Comment by mediafreakch** [comment]
One scenario I can think of is when you have a single page application with a login screen (or a callback route for Open ID Connect flow), where you first determine the language based on the browser settings, and once the user has successfully authenticated, you want the UI to be displayed in the language configured by the user's profile settings. 

When the browser locale is different from the user's profile settings, this would require a flag, e.g. in localStorage, and a page reload after login at the moment.

**Comment by longlho** [comment]
If that's the case u should just reload. SPA isn't gonna provide u w that much value if user flow deviates so much. You're just accumulating memory from the login page w/o proper GC

**Comment by mediafreakch** [comment]
I updated my example to include a reload functionality when changing the language:  
https://stackblitz.com/edit/vitejs-vite-f5zoyb?file=src/components/HelloWorld.vue

**Comment by Petri-Oosthuizen** [comment]
@mediafreakch, are you still using [formatjs](https://github.com/formatjs/formatjs) for your ICU messages in vuejs?

**Comment by mediafreakch** [comment]
@Petri-Oosthuizen Yes. Together with the custom components for rich text formatting [I posted here](https://github.com/formatjs/formatjs/discussions/3961), it works flawlessly.

**Comment by Petri-Oosthuizen** [comment]
@mediafreakch, thank you for the quick response!

I've been playing around with formatjs for a few hours now and just wanted to make sure it is worth it going forward. It is working fine so far here as well. The `globalProperties.$t` override and the rich text component are both pretty neat, thanks!

I was, however, having difficulty in augmenting the component instance type to support the custom global properties. 

![image](https://user-images.githubusercontent.com/4954611/215712471-3c69c446-e80c-4778-8f96-2533c9da2e27.jpeg)

I saw that it is defined in `vue-intl/plugin.d.ts` but for some reason, I can't get my IDE (IntelliJ) to pick it up. 

After redefining the `ComponentCustomProperties` for "@vue/runtime-core" instead it started working:  

```js
import { IntlFormatters, IntlShape } from "@formatjs/intl";
import { FormatXMLElementFn, PrimitiveType } from "intl-messageformat";

declare module "@vue/runtime-core" {
  interface ComponentCustomProperties {
    $t: (key: string, values?: Record<string, PrimitiveType | FormatXMLElementFn<string, string>>) => string;
    $intl: IntlShape;
    $formatMessage: IntlFormatters["formatMessage"];
    // ... omitted for brevity
  }
}

export {};
```

![image](https://user-images.githubusercontent.com/4954611/215714978-18773d8d-eb17-4c48-9945-54c1f843229a.jpeg)

**Comment by mediafreakch** [comment]
@Petri-Oosthuizen It looks like a bug in `vue-intl`. If you change `declare module 'vue'` to `declare module "@vue/runtime-core"` in `plugin.d.ts` it should work. Had to do the same for the `$t` function augmentation. Maybe you find the time to create a PR?

**Comment by Petri-Oosthuizen** [comment]
Hopefully, I find some time today for the PR.

One last thing, have you found a replacement for 
```js
import i18n from "@/plugins/i18n";
const { t } = i18n.global;
``` 

basically using formatjs outside of vue components?

**Comment by mediafreakch** [comment]
No, I had no need for this. You can either

a) pass `$t` as a function parameter, assuming this function is called from a vue component
b) write your own plugin that attaches `$t` to `window`:

```ts
// intl-plugin.ts
export function globalIntlPlugin(app: any) {
  app.config.globalProperties.$t = window.$t = (key: string, values: any) =>
    app.config.globalProperties.$intl.formatMessage({ id: key }, values)
}

// main.ts
app.use(createIntl({ ... })).use(globalIntlPlugin)
```

**Comment by Petri-Oosthuizen** [comment]
Just as I was about to change the module declaration I had a look at the file history and saw that it has recently been changed from `declare module "@vue/runtime-core"` to `declare module "vue"` in [#3919](https://github.com/formatjs/formatjs/pull/3919/files#diff-bd53f74de454b76c1b33335ba16d7fd47618f9b22e4220e8da4f0fde57abe51fL10) by (and pulling in) @pyrocat101. 

@pyrocat101, I think the types to extend are in `"@vue/runtime-core"` and not in `"vue"`, why did you change it? I know the [vue docs](https://vuejs.org/api/utility-types.html#componentcustomproperties) use `"vue"` but most of the other sources I can find use `"@vue/runtime-core"`.

**Comment by pyrocat101** [comment]
PRs are welcome.
