### ISSUE TITLE
absence of updateIntervalInSeconds will break numeric prop for FormattedRelativeTime

### ISSUE THREAD

**Issue by vicdus** [formatjs/formatjs#3960]
## Which package?
[@formatjs/intl-relativetimeformat](https://www.npmjs.com/package/@formatjs/intl-relativetimeformat)

## Describe the bug
For component `FormattedRelativeTime`, 

absence of `updateIntervalInSeconds` will break `numeric` prop and always assume `numeric=always` even if set it to `auto`

### Codesandbox URL

https://codesandbox.io/s/react-intl-formatrelativedate-broken-forked-bo0mh4?file=/src/index.js

### Reproducible Steps/Repo

go to url above
observe that two FormattedRelativeTime component with same value but different in absence/precence of `updateIntervalInSeconds` render different content

```
With updateIntervalInSeconds
3 hours ago
Without updateIntervalInSeconds
10,000 seconds ago
```

## Expected behavior
`updateIntervalInSeconds` should not affect the content it rendered

## Screenshots
n/a

## Desktop (please complete the following information):

- OS: mac 13.0.1 (22A400)
- Browser chrome
- Version: latest

**Comment by longlho** [comment]
hmm we don't assume `numeric=always`, the behavior of `updateIntervalInSeconds` is every tick it'll try to update to the smallest unit, in your case instead of 10000 seconds it's 3 days. `numeric=always` or `auto` dictates things like `1 day ago` or `yesterday`
