### ISSUE TITLE
Better translation in the documentation

### ISSUE THREAD

**Issue by augnustin** [formatjs/formatjs#3962]
In this page https://formatjs.io/docs/getting-started/installation the basic example translates `Today is {ts, date, ::yyyyMMdd}` into French `Aujourd'hui, c'est le {ts, date, ::yyyyMMdd}`.

It is not correct in French. We would translate it to `Aujourd'hui, nous sommes le {ts, date, ::yyyyMMdd}`.

It wouldn't matter on any other website, but since this website is about a translation tool, it feels cheap and not professional and tends to depreciate the tool itself so I would encourage a fix. :relaxed:

**Comment by cungminh2710** [comment]
hi @longlho, seems like the docs page hasn't been updated. can you double check? 👍
