### ISSUE TITLE
specifying `DateTimeFormatOptions.timeZoneName` not working and ignores other styles

### ISSUE THREAD

**Issue by unional** [formatjs/formatjs#3969]
## Which package?

react-intl > @formatjs/intl I think

## Describe the bug

```ts
function Foo() {
  const intl = useIntl()

  intl.formatDate(new Date(), {
    dateStyle: 'short',
    timeStyle: 'short',
    timeZoneName: 'short'
 }
}
```

Renders:
![image](https://user-images.githubusercontent.com/3254987/213264808-d0218b9b-1e68-4b75-986e-d2c347de0fec.png)

### Codesandbox URL

https://codesandbox.io/s/formatjs-timezonename-issue-ht6jnx?file=/src/App.js

Occurs also in `react-intl` v5, which is what I use in my project

**Comment by longlho** [comment]
`dateStyle` & `timeStyle` have specific built in `timeZoneName` so you can't override it. Natively browser would throw you an error:
```
ncaught TypeError: Can't set option timeZoneName when dateStyle is used
```

**Comment by unional** [comment]
thx. Should `formatjs` do the same to avoid confusion?
