### ISSUE TITLE
Time format is different locally and in CI

### ISSUE THREAD

**Issue by jesperenglund92** [formatjs/formatjs#3970]
## Which package?
react-intl/formatjs/formatDate/formatTime

## Describe the bug
When running jest tests locally and in gerrit, mocking formatTime is displayed with as space between the time and AM/PM e.g. 00:00 AM. But when building later in the CI, the time is displayed without the space, such as 00:00AM, which makes our tests fail.

## To Reproduce
I'm using MacOS, I have version 5.25.1 of react-intl and formatjs/intl: 2.2.1, react: ^17.0.2, node: 19.4.0

## Expected behavior
I would expect the tests to generate the same format both locally and in CI

## Desktop (please complete the following information):

- OS: MacOS
- Browser: Chrome

## Additional context
I don't know if there's been any changes on your end that could cause this issue but I would appreciate some help!
Although, I should say that we haven't updated formatjs recently and it worked the day before yesterday. So it's probably not got anything to do with formatjs directly, but maybe if you use any third party dependencies to generate those timestamps?

**Comment by longlho** [comment]
does your CI have the same Node version as your local? We just use Node's `Intl` API so it's likely a Node version difference between your CI & your local. I'd recommend using a hermetic build system for that.
