### ISSUE TITLE
Custom time format in FormattedMessage ignores time zone from provider

### ISSUE THREAD

**Issue by carrot-sticks** [formatjs/formatjs#3971]
## Which package?
`react-intl`

## Describe the bug

You can put prop `timeZone` to `IntlProvider`. This time zone is used correctly in `FormattedDate/Time/Range` components, and in `FormattedMessage` if predefined time format is used (i.e. `{xy, time, short}`). But when custom time format is used (i.e. `{xy, time, ::hhMM}`) browser time zone is used instead.

### Codesandbox URL

https://codesandbox.io/s/confident-feistel-z7eyih?file=/src/_app.js

### Reproducible Steps/Repo

1. Open code sandbox
2. Click on "Next time zone"
3. First line will change, and second won't 

## Expected behavior

If `timeZone` is set to the `IntlProvider`, it should always be picked over browser time zone.

## Desktop (please complete the following information):

- MacOS 12.4
- Firefox Developer Edition 110.0b3
- react-intl@6.2.5

**Comment by longlho** [comment]
yeah this is certainly a shortcoming of using skeletons. It does not merge ambient configs in and that's basically how icu4j `MessageFormat` works as well so I don't know if we actually plan to change that behavior. I'll fix the doc to call this out specifically.
Keeping this open until I fix the doc
