### ISSUE TITLE
Pseudo localization for non ast output

### ISSUE THREAD

**Issue by roderickhsiao** [formatjs/formatjs#3979]
## Which package?
fomatjs cli https://formatjs.io/docs/tooling/cli#--pseudo-locale-pseudolocale

## Describe the bug
Not necessarily a bug, it seems like pseudo localization compile only works for ast output, for other output the strings remain the same.

https://github.com/formatjs/formatjs/issues/2165#issuecomment-702320922

We could probably update the documentation if we are not currently supporting it.  

### Codesandbox URL

Please include a codesandbox URL if possible

**Comment by longlho** [comment]
we can do non-AST but caveat is that string -> AST -> string is a lossy process because it's not a CST.
