### ISSUE TITLE
self-closing tag in defaultRichTextElements broken in last version

### ISSUE THREAD

**Issue by antoinerousseau** [formatjs/formatjs#3982]
## Which package?
`@fornatjs/intl` 2.6.5

## Describe the bug

With `react-intl` pulling `@formatjs/intl` 2.6.3, I used to have this
```ts
<IntlProvider
  // ...
  defaultRichTextElements={{
    // ...
    strong: text => <strong>{text}</strong>,
    br: () => <br />,
}}>
```

Which allows for messages like `blabla <strong>blabla</strong> blabla.{br}blablabla`

But now I have to replace `br: () => <br />` with `br: <br />` to make it work, but this is not what the typings say.

### Codesandbox URL

https://codesandbox.io/s/formatjs-intl-br-bug-r31etx

## Desktop:

- OS: macOS 13.2
- Browser: Chrome (Brave)
- Version: Chromium 109

**Comment by apuntovanini** [comment]
Also, it seems Safari breaks when using latest version along with defaultRichTextElements

```tsx
export const defaultRichTextElements = {
  b: (chunks: string) => <b>{chunks}</b>,
  strong: (chunks: string) => <strong>{chunks}</strong>,
  i: (chunks: string) => <i>{chunks}</i>,
  em: (chunks: string) => <em>{chunks}</em>,
  br: () => <br />,
};

<IntlProvider
      key={locale}
      locale={locale}
      defaultLocale={DEFAULT_LOCALE}
      messages={messages}
      defaultRichTextElements={defaultRichTextElements}
/>
```

Chrome works, Safari complains for `Invalid regular expression: invalid group specifier name`

**Comment by antoinerousseau** [comment]
it's not fixed
