### ISSUE TITLE
FormattedNumber as currency doesn't honor trailingZeroDisplay: "stripIfInteger"

### ISSUE THREAD

**Issue by flip-it** [formatjs/formatjs#3985]
## Which package?
intl-numberformat

## Describe the bug
Option `trailingZeroDisplay` seems to not get passed on to the native `Intl` API when `style="currency"`.

## To Reproduce
```jsx
<FormattedNumber
  value={20}
  style="currency"
  currency="USD"
  trailingZeroDisplay="stripIfInteger"
/>

// -> Outputs $20.00
```

```js
new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  trailingZeroDisplay: "stripIfInteger"
}).format(20)

// -> Outputs $20
```

### Codesandbox URL

https://codesandbox.io/embed/musing-fog-n0zdp2

## Expected behavior
`FormattedNumber` should output the same as `Intl.NumberFormat` given the same options. In this case `$20` without fraction digits since they are all zero.

When removing currency style it works as expected.

## Desktop

Tested on Chrome 109 and Safari 16.2.

**Comment by flip-it** [comment]
ping

**Comment by amk221** [comment]
Hi,

wondering if this could be reopened?

I’m experiencing this via ember-intl: https://github.com/ember-intl/ember-intl/issues/1775

**Comment by amk221** [comment]
@longlho Found you on the Contributors tab, I don't suppose you have rights to re-open this issue? (I didn't want to raise a duplicate)
