### ISSUE TITLE
Import Locale Data on mobile web

### ISSUE THREAD

**Issue by Prince-Mendiratta** [formatjs/formatjs#3986]
## Which package?
`@formatjs/intl-numberformat`, `@formatjs/intl-pluralrules`

## Describe the bug
Hi, I've been working on an application where the currency `XAF` is used. The currency symbol for XAF on a chrome browser on desktop returns `FCFA`, which is the required result. On a mobile chrome however, the symbol returned is `XAF`. The code I have used for the same is -
```js
let out = new Intl.NumberFormat("en", {
      style: "currency",
      currency: "XAF",
      maximumFractionDigits: 2
    }).format(69000);
console.log(out)
```

This led me to the conclusion that I need to polyfill the locale data for all platforms. I have used the following code for the same;
```
import "@formatjs/intl-getcanonicallocales/polyfill";
import "@formatjs/intl-locale/polyfill";
import "@formatjs/intl-pluralrules/polyfill";
import "@formatjs/intl-numberformat/polyfill";

import "@formatjs/intl-numberformat/locale-data/en";
```
With these, the expected result should be that `FCFA` currency is displayed on mobile browsers as well. However, no change occurs. What am I doing wrong here or is this functionality not supported?

### Codesandbox URL

To reproduce the issue - https://codesandbox.io/p/github/Prince-Mendiratta/intl-api/main
After using formatjs - https://codesandbox.io/s/format-js-polyfill-vg2utn

### Reproducible Steps/Repo

1. Open the above mentioned sandboxes, one by one.
2. Visit the sandbox link on a desktop browser. Notice that the symbol displayed is FCFA.
3. Visit the sandbox link on a mobile browser. Notice that symbol displayed is XFA.

Even using the second sandbox, the issue persists. Thus, the locale data is not polyfilled by format-js.

## Expected behavior
The locale data should be polyfilled for all platforms.

## Screenshots
**Desktop**
![Screenshot_20230208_141636](https://user-images.githubusercontent.com/54077356/217479778-a4447bd5-55ba-4c59-84f7-cfea3056248a.png)

**Mobile**
![WhatsApp Image 2023-02-08 at 2 17 25 PM](https://user-images.githubusercontent.com/54077356/217479998-bb87e236-8dc0-47c9-aad0-a75a054d953d.jpeg)

## Desktop (please complete the following information):

- OS: Linux
- Browser: Chrome
- Version: 108.0.5359.124

## Smartphone (please complete the following information):

- Device: OnePlus 8T
- OS: Android 13
- Browser: Chrome
- Version: 109.0.5414.118

**Comment by longlho** [comment]
polyfill won’t kick in if the platform supports those APIs already. This is an issue with Mobile Chrome potentially using an older version of ICU. 1 option is to detect that browser specifically and do a `polyfill-force` instead.

**Comment by Prince-Mendiratta** [comment]
Thanks for the follow up, @longlho! Any resources on how I can detect if a browser uses an older version of ICU? I have tried looking up for something online but was unable to do so. Should I instead polyfill for all browsers?

**Comment by longlho** [comment]
Polyfills are pretty heavy so I don't think u should polyfill them all. There's no easy way to tell browser's ICU version but you can basically selectively load the polyfill if u detect an undesirable result, e.g if format something with XAF and it doesn't yield cfaf then load the polyfil

**Comment by Prince-Mendiratta** [comment]
@longlho Noted, thank you so much for your help!
