### ISSUE TITLE
Docs Update

### ISSUE THREAD

**Issue by cungminh2710** [formatjs/formatjs#3987]
It seems like the few recent updates of docs website haven't been deployed. ie. new eslint rules docs are not found

**Comment by longlho** [comment]
ack I'm still trying to find some time to actually do it

**Comment by cungminh2710** [comment]
not stale 👍

**Comment by cungminh2710** [comment]
not stale

**Comment by cungminh2710** [comment]
not stale

**Comment by cungminh2710** [comment]
Hi @longlho, do you have any updates? let me know if there is any way I can help
