### ISSUE TITLE
Constructing `IntlMessageFormat` with an invalid locale throws

### ISSUE THREAD

**Issue by marekdedic** [formatjs/formatjs#3989]
## Which package?
`intl-messageformat`

## Describe the bug
Since version `9.13.0`, constructing an `IntlMessageFormat` with an invalid locale throws an error

## To Reproduce

```js
new IntlMessageFormat("invalid")
```

## Expected behavior
Well, I agree that this is a corner case, but I don't thing throwing is an ideal way to handle this error. Until version 9.12.0, the constructor would not throw and would still successfully format the message.

## Desktop (please complete the following information):

- OS: Debian testing
- Browser: Electron
- Version 106

## Additional context
I got here by debugging kaisermann/svelte-i18n#209
The issue was introduced in #3544 and is caused by the following line:

https://github.com/formatjs/formatjs/blob/7173e297a229254dd9faed4abe25db17fb96dc68/packages/intl-messageformat/src/core.ts#L208

**Comment by marekdedic** [comment]
Not stale.

**Comment by marekdedic** [comment]
Not stale.

**Comment by marekdedic** [comment]
Not stale.

**Comment by longlho** [comment]
@marekdedic what is the invalid locale that you're passing in? throwing is consistent with other Intl API

**Comment by marekdedic** [comment]
I am passing a locale that gets autofilled by the server via source code replacement (oh, the "joys" of using Google Apps Script...), however this does not happen e.g. in unit tests, which then fail.

I mean, throwing is actually a pretty reasonable thing to do, however that wasn't the behaviour until 9.13.0, so I wasn't sure this was an intended change as it isn't listed in the changelog. I think before that update, the original string was returned.

**Comment by marekdedic** [comment]
Not stale

**Comment by marekdedic** [comment]
Not stale

**Comment by marekdedic** [comment]
Not stale

**Comment by marekdedic** [comment]
Not stale

**Comment by marekdedic** [comment]
Closing as this is probably intended behaviour (I would recommend adding it to the changelog, though ;) )
