### ISSUE TITLE
Can’t use `@formatjs/fast-memoize` in isomorphic code

### ISSUE THREAD

**Issue by remcohaszing** [formatjs/formatjs#3999]
## Which package?

`@formatjs/fast-memoize`

## Describe the bug

The `main` property of `@formatjs/fast-memoize` is a CommonJS module that specifies `module.exports.default`. There is no (real) ESM support. That means that usage in CommonJS is as follows:

```js
const memoize = require('@formatjs/fast-memoize')

memoize.default(/* … */)
```

and usage in ESM is:

```js
import memoize from '@formatjs/fast-memoize'

memoize.default(/* … */)
```

IMO this is not pretty, but it works.

The problem is that `@formatjs/fast-memoize` does specify the `module` field. This points to a **faux** ESM module. Many bundlers use this field, so correct use with a bundler is:

```js
import memoize from '@formatjs/fast-memoize'

memoize(/* … */)
```

This means it’s not possible to use `@formatjs/fast-memoize` in isomorphic code.

### Codesandbox URL

N/A

### Reproducible Steps/Repo

1. Create the following script named test.mjs:
   ```js
   import memoize from '@formatjs/fast-memoize';

   console.log(memoize);
   ``

2. Run the following script using Node.js:
   ```sh
   node test.mjs
   ```

Notice that `memoize` is a module with the property `default`. `memoize` itself is not a function.

## Expected behavior

I would expect at least one of the following:

1. `@formatjs/fast-memoize` supports proper dual packaging using package exports.
2. `@formatjs/fast-memoize` removes support for CommonJS.
3. `@formatjs/fast-memoize` removes support for faux ESM.
4. `@formatjs/fast-memoize` uses a named export instead of a default export.
5. `@formatjs/fast-memoize` gets deprecated in favour of [`fast-memoize`](https://www.npmjs.com/package/fast-memoize).

## Screenshots

N/A

## Desktop (please complete the following information):

- OS: Pop!_OS
- Browser: Node.js
- Version: 18

## Smartphone (please complete the following information):

- Device: N/A
- OS: N/A
- Browser N/A
- Version N/A

## Additional context

`@formatjs/fast-memoize` was created because of a very niche issue (#1913). `fast-memoize` uses CommonJS (not UMD, as is claimed in that issue). Node.js native ESM and bundlers can consume CJS just fine. A lot of ESM packages have CJS dependencies.

**Comment by remcohaszing** [comment]
It's still relevant

**Comment by pyrocat101** [comment]
Reopen until we have better way to handle this.
