### ISSUE TITLE
Error when loading via requirejs

### ISSUE THREAD

**Issue by judholliday** [formatjs/formatjs#4]
The example works fine when loading via a script tag, but when trying to move this over to load via requirejs there is an error:
Line 98: Uncaught type error: undefined is not a function
It appears to be trying to call methods on MessageFormat (this._mergeFormats) which don't exist yet.

Here is a stripped down example which shows the error:

```
<body>
    <div id="content">
    </div>

    <script src="../requirejs/require.js"></script>

    <script>
        require.config({
            baseUrl: '',
            paths: {
                "react": "../react/react",
                "react-intl": "../react-intl/dist/react-intl"
            }
        });

        require(['react', 'react-intl'], function (React, ReactIntlMixin) {

        });

    </script>
</body>
```

Should this be able to load via require as-is or is there something else I am missing?

**Comment by badeball** [comment]
> You can probably tweak the shim to get a handle of React and set it global as window.React, and that will work.

@caridy, no, I believe you cannot. React is an AMD compatible module, which means it invokes define(). Any module that invokes define is in principle not non-AMD-compatible and RequireJS will not invoke any configured init method in its shim ([source](https://github.com/jrburke/requirejs/issues/534#issuecomment-10536670)).

This seems to makes it incredibly tedious to use React & ReactIntl with RequireJS.

**Comment by badeball** [comment]
I solved the issue by creating a small utility that simply populates the global variable with the loaded module, by accessing the internals of RequireJS (using a solution suggested on [StackOverflow](http://stackoverflow.com/questions/11756483/require-js-access-all-loaded-modules)).

```javascript
requirejs.config({
  shim: {
    "react-globalizer": {
      deps: ["react"]
    },

    "react-intl": {
      deps: ["react-globalizer"],
      exports: "ReactIntl"
    }
});
```

```javascript
// react-globalizer.js
(function (window) {
  var r;

  if (typeof requirejs !== "undefined") {
    r = requirejs;
  } else if (typeof require !== "undefined") {
    r = require;
  } else {
    throw "RequireJS is not loaded!";
  }

  window.React = r.s.contexts["_"].defined.react;
})(this);
```

**Comment by caridy** [comment]
thanks for sharing the solution @badeball, we will eventually revisit this to make easier for people to use it with requirejs.

**Comment by xjamundx** [comment]
Struggling with the same here.....@badeball thanks for your tips, did you have to do anything special to get this working with the require.js optimizer?

**Comment by badeball** [comment]
@xjamundx, I have unfortunately not tried using it with the require.js optimizer. I'm sure I will eventually though, and may get back to you at that point.

**Comment by xjamundx** [comment]
Okay, I'm sure I'll get it (eventually) and post how I got it to work. Frankly, React could just also solve this by creating a special AMD build that also posted a global

**Comment by ericf** [comment]
> Okay, I'm sure I'll get it (eventually) and post how I got it to work. Frankly, React could just also solve this by creating a special AMD build that also posted a global

Ideally React offers up ES6 modules and CommonJS for back compat. That way the ES6 modules could be bundled into any format including AMD.

**Comment by xjamundx** [comment]
`r.s.contexts["_"].defined` is populated asynchronously (there's some `setTimeout(fn, 4)` type stuff in there, so basically if react-intl is not being fetched over the network your fix won't work. I'm just going to fork react-intl (localy) and add AMD support. If it works well enough I'll post it to github.

**Comment by ericf** [comment]
That seems very brittle :cry:

**Comment by adibsaad** [comment]
@xjamundx locally adding AMD support is what working at the moment.

**Comment by xjamundx** [comment]
@adibsaad Yeah it works, but it's lame. I really vote for a properly supported AMD build.

**Comment by ericf** [comment]
> I really vote for a properly supported AMD build.

The source is ES6 so an AMD build can be derived. Instead of shipping an AMD dist, we'll likely contribute to tools to make sure you can create one.
