### ISSUE TITLE
Update Intl.DurationFormat polyfill to current Stage 3 spec

### ISSUE THREAD

**Issue by sffc** [formatjs/formatjs#4000]
## Which package?

intl-durationformat

## Describe the bug

The Intl.DurationFormat polyfill currently uses options that were discussed during Stage 2 but eliminated before the proposal went to Stage 3, and it is missing options that were added when the proposal went to Stage 3. The polyfill should be updated to reflect the current Stage 3 proposal.

## To Reproduce

N/A

## Expected behavior

Intl.DurationFormat should use all current options, such as `hourDisplay`, instead of obsolete options, like `hideZeroValues`.

## Additional context

https://github.com/tc39/proposal-intl-duration-format

**Comment by longlho** [comment]
This has been resolved. The `@formatjs/intl-durationformat` polyfill now uses the current Stage 3 spec options (`hoursDisplay`, `minutesDisplay`, `secondsDisplay`, etc. with `'always' | 'auto'` values). The obsolete Stage 2 `hideZeroValues` option is no longer used.
