### ISSUE TITLE
no-complex-selectors can crash eslint

### ISSUE THREAD

**Issue by pyrocat101** [formatjs/formatjs#4005]
## Which package?

`eslint-plugin-formatjs`

## Describe the bug

`no-complex-selectors` rule will now complain about not being able to hoisting plural/select past the tag element. But it does so by throwing an error that will crash ESLint, instead of being part of the linter result.

### Codesandbox URL

N/A

### Reproducible Steps/Repo

N/A
## Expected behavior

`no-complex-selectors` should not crash the ESLint when processing messages where there are surrounding tags around the plural/select element.

**Comment by longlho** [comment]
fixed in latest
