### ISSUE TITLE
Different behavior of standalone formatting

### ISSUE THREAD

**Issue by davidnum** [formatjs/formatjs#4012]
## Which package?
`@formatjs/intl-datetimeformat`

## Describe the bug
With the polyfill installed I am seeing the following
```js
new Intl.DateTimeFormat("ru", { day: "numeric", month: "long" }).format(new Date('2022-03-07'))
// 7 марта  ✅

new Intl.DateTimeFormat("ru", { month: "long" }).format(new Date('2022-03-07'))
 // марта ❌ 
```

 From what I can see, the expected output should be

 ```js
new Intl.DateTimeFormat("ru", { month: "long" }).format(new Date('2022-03-07'))
// март  ✅
```

### Codesandbox URL

https://codesandbox.io/s/romantic-flower-qv3pvi?file=/src/index.js

### Reproducible Steps/Repo

```js
import "@formatjs/intl-locale/polyfill";
import "@formatjs/intl-datetimeformat/polyfill-force";
import "@formatjs/intl-datetimeformat/locale-data/ru";

const dtf1 = new Intl.DateTimeFormat("ru", { day: "numeric", month: "long" });
const dtf2 = new Intl.DateTimeFormat("ru", { month: "long" });

const d = new Date();
console.log("Relative:", dtf1.format(d), "Standalone:", dtf2.format(d));
// Relative: 7 марта Standalone: марта ❌ 
```

## Expected behavior
It should correct format standalone month

```js
// Relative: 7 марта Standalone: март  ✅
```

**Comment by longlho** [comment]
It's the Date parser that's inconsistent.

**Comment by davidnum** [comment]
> It's the Date parser that's inconsistent.

Can you explain, please? Do you think that problem is in ```new Date('2022-03-07')```?

**Comment by longlho** [comment]
Yup

**Comment by davidnum** [comment]
But in Chrome, for example, its working as expected:
<img width="558" alt="Снимок экрана 2023-03-08 в 16 10 07" src="https://user-images.githubusercontent.com/7981854/223721591-f42445e4-8a72-40e0-ba63-285f8a9f2c74.png">
