### ISSUE TITLE
Support typescript ^5.0.0

### ISSUE THREAD

**Issue by alexeymolchan** [formatjs/formatjs#4029]
please add support of typescript ^5.0.0 

https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/

sorry for bug label, dunno how to change it or remove

**Comment by longlho** [comment]
Not until all our deps support it

**Comment by felixfbecker** [comment]
Is there a reason `react-intl` needs a peer dependency on `typescript` at `^4.9`? That includes any minor release of TypeScript after `4.9`, but TypeScript doesn't actually follow semver, it simply increases the major version number after every `.9` minor release. So it doesn't really make sense to me why `5.0` would not be allowed but any other minor release is allowed – TypeScript does small breaking changes in any non-bugfix release.

Is a `peerDependency` on TypeScript even necessary at all?

**Comment by longlho** [comment]
Yeah our AST transformer relies on TS compiler API which breaks between minor releases so we pin it

**Comment by pyrocat101** [comment]
@longlho Looks like only `ts-transformer` need to have a dependency on the TypeScript, but not the `react-intl` itself?

**Comment by longlho** [comment]
We can try relaxing for react-intl but we can't test though. Also type def changes that comes w new TS versions always breaks things in a non backward compat way

**Comment by heath-freenome** [comment]
@longlho what needs to happen to get the `ts-transformer` upgraded? And can I help somehow?

**Comment by longlho** [comment]
Yeah basically try bumping the typescript version in the repo & see what failed

**Comment by folt** [comment]
Faced the same error.

**Comment by mattcasey** [comment]
In the meantime, for others I was able to fix it by adding this override to my package.json:

```
{...
  "overrides": {
    "typescript": "$typescript"
  }
}
```
More info: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by folt** [comment]
@longlho should i wait for a solution?

**Comment by heath-freenome** [comment]
> Yeah basically try bumping the typescript version in the repo & see what failed

@longlho Since I wrote that, I've been totally slammed with work and will be so for a good long while. If someone else it open to pushing PRs I'd appreciate it

**Comment by kachkaev** [comment]
@folt has started https://github.com/formatjs/formatjs/pull/4045 a few hours ago 👍 The PR needs a few tweaks AFAIU.

**Comment by longlho** [comment]
fixed & released
