### ISSUE TITLE
Upgrade tzdata to 2022g

### ISSUE THREAD

**Issue by adam-felix-shopify** [formatjs/formatjs#4036]
## Which package?

@formatjs/intl-datetimeformat

## Describe the bug

The above package is using stale tzdata (2022f) instead of the recent tzdata (2022g) which is causing crashes with the new timezone `America/Ciudad_Juarez` on React Native.

## To Reproduce

I'm not sure how to reproduce any issue without a React Native setup using polyfills.

## Expected behavior

Someone using the `America/Ciudad_Juarez` timezone has no issues when using this package

**Comment by davidseek** [comment]
I have created Pull Request https://github.com/formatjs/formatjs/pull/4043

**Comment by longlho** [comment]
fixed & released

**Comment by adam-felix-shopify** [comment]
`America/Ciudad_Juarez` appears to be missing from 2022g data changes ([commit f06575e9af4437dc71e0a10346598a04d3a1c95f](https://github.com/formatjs/formatjs/commit/f06575e9af4437dc71e0a10346598a04d3a1c95f)

**Comment by longlho** [comment]
That likely needs to be added to the list of tz we ingest. If you search around for other timezones there should be a list in the repo

**Comment by davidseek** [comment]
I was under the impression, that this would be automatically added by the Bazel script. The Contributions Wiki asks to update the `tzdata`, the `sha` and then run the Bazel script. No words mentioned of having to manually add new Timezones? 

I'm gonna look into this and see, if I can raise a PR to add `America/Ciudad_Juarez` manually.

**Comment by longlho** [comment]
Yeah that's def a missing step since new timezones don't appear all that often. I'll add a test to catch it

**Comment by adam-felix-shopify** [comment]
There's a few others I noticed based on [python/tzdata](https://github.com/python/tzdata):

1. America/Ciudad_Juarez ([2022g](http://mm.icann.org/pipermail/tz-announce/2022-November/000076.html))
1. Europe/Kyiv formerly Europe/Kiev([2022b](http://mm.icann.org/pipermail/tz-announce/2022-August/000071.html))
1. Pacific/Kanton formerly Pacific/Enderbury ([2021b](http://mm.icann.org/pipermail/tz-announce/2021-September/000066.html))
1. America/Nuuk formerly America/Godthab ([2020a](http://mm.icann.org/pipermail/tz-announce/2020-April/000058.html))

2, 3 and 4 the former names are now links to the new names.

**Comment by davidseek** [comment]
Based on that comment, I assume that [this is the file](https://github.com/formatjs/formatjs/blob/main/index.bzl) that needs updating. Will be pushing a PR ASAP

**Comment by longlho** [comment]
Yup that's it

**Comment by davidseek** [comment]
Hey team, 

I have updated my PR https://github.com/formatjs/formatjs/pull/4065 to update `tzdata` to `2023c`. I have added the [Commit](https://github.com/formatjs/formatjs/pull/4065/commits/d29cb6534d335958fac3727eb16dbc425167ba1b) to update the outdated TimeZones as discussed. Additionally, I have updated the Contribution Wiki with a hint to do the same next time, when updating to a new `tzdata` version.

Please review and merge @longlho

**Comment by davidseek** [comment]
@adam-felix-shopify, I have not been able to identify an issue with "America/Nuuk formerly America/Godthab ([2020a](http://mm.icann.org/pipermail/tz-announce/2020-April/000058.html))". `America/Nuuk` was and is part of the [array](https://github.com/formatjs/formatjs/blob/main/index.bzl#L163).
