### ISSUE TITLE
 [React Intl] An `id` must be provided to format a message.

### ISSUE THREAD

**Issue by KGX10** [formatjs/formatjs#4050]
## Which package?
@formatjs/ts-transformer

## Describe the bug
I have been using the package over the past 8-9 months and it was working fine with my nextjs project, the issue began after the latest release of **3.13.0** today. While running the next build, it throws an error of _"[React Intl] An `id` must be provided to format a message."_. I am attaching the screenshots of the error and my configuration in next.config.js.

Build error:
![image](https://user-images.githubusercontent.com/54179637/232505322-02004744-9a48-486a-ad7e-316db702729d.png)

Configuration in next.config.js
![image](https://user-images.githubusercontent.com/54179637/232505661-0903299f-2e2f-44f8-9bd3-5f10ab6cd7cd.png)

Package information from package.json:
![image](https://user-images.githubusercontent.com/54179637/232505880-98a78668-b4f4-4507-9c7c-68d1e127eb4a.png)

**A fast response would be very helpful guys as my work is stuck.**

**Comment by longlho** [comment]
do u have 2 versions of TypeScript or such?

**Comment by KGX10** [comment]
![image](https://user-images.githubusercontent.com/54179637/232520065-f8eea501-3e09-4ec6-910f-2ab197e404b9.png)
Got only this version in my package.json
