### ISSUE TITLE
`@format/intl` `IntlShape<T>` is incompatible with `react-intl` `IntlShape`

### ISSUE THREAD

**Issue by unional** [formatjs/formatjs#4074]
## Which package?

`@formatjs/intl`, `react-intl`

## Describe the bug

The type `IntlShape` in `@formatjs/intl` and `react-intl` are different.

This causes issue like the following:

```sh
Type 'IntlShape' is not assignable to type 'IntlShape<string>'.
  The types returned by 'formatters.getMessageFormat(...)' are incompatible between these types.
```

## To Reproduce

- install react-intl
- install @formatjs/intl
- write a function with `useIntl()` and pass it to a function expecting `IntlShape<string>` from `@formatjs/intl`.

## Expected behavior

Should work.

## Additional context

`react-intl` should reuse and re-export the type from `@formatjs/intl`.

**Comment by longlho** [comment]
We generally don't major version bump for type changes. It happens all the time & same with TypeScript

**Comment by unional** [comment]
I have updated the issue. It is actually not about major bump, it's about type incompatibility.

**Comment by unional** [comment]
update?

**Comment by unional** [comment]
update?

**Comment by unional** [comment]
still an issue.
