### ISSUE TITLE
Unable to suppress warning about missing unique key prop on an element while using rich text formatting

### ISSUE THREAD

**Issue by NikaBuligini** [formatjs/formatjs#4085]
## Which package?
`@formatjs/intl`, `react-intl`

## Describe the bug
When I try using rich text formatting I'm getting a warning from React about missing a unique key for an element.

### Codesandbox URL

https://codesandbox.io/s/peaceful-browser-je5f94?file=/src/App.tsx

### Reproducible Steps/Repo

1. Go to [codesandbox URL](https://codesandbox.io/s/peaceful-browser-je5f94?file=/src/App.tsx)
2. Open the console for a preview
3. You will see an error coming from react with a message: "Warning: Each child in a list should have a unique "key" prop."

## Expected behavior
I expect `wrapRichTextChunksInFragment` to work on `@formatjs/intl` and `react-intl` side

## Screenshots
![image](https://user-images.githubusercontent.com/7580677/233984820-443aa79c-83ca-42c1-ab84-a18442663ba7.png)

## Desktop (please complete the following information):

- OS: Windows 11
- Browser Google Chrome
- Version 112.0.5615.138 (Official Build) (64-bit)

## Additional context
I checked the documentation for `react-intl` and it seems [wrapRichTextChunksInFragment](https://formatjs.io/docs/react-intl/components/#wraprichtextchunksinfragment) is supposed to help me suppress warnings. I'm not using `react-intl` directly so I tried checking configuration types for `@formatjs/intl`. It seems it doesn't accept such a configuration option. You can take a look at its config type [here](https://github.com/formatjs/formatjs/blob/5493185bb2d02f1a7334d6b53f1bd4d1b1524117/packages/intl/src/types.ts#L66).

I searched a bit and I found out that even though `react-intl` accepts `wrapRichTextChunksInFragment` and passes it to `createIntl`, it is never really used on the `createIntl` side. I assume it was supported before and then it got removed.

**Comment by NikaBuligini** [comment]
I'm willing to contribute if someone sets the direction. It's not clear whether this section from the documentation needs to let go or functionality needs to be added.

**Comment by zbuttram** [comment]
Having this same issue, I've had to just generate keys for each of my rich text elements to silence the warnings.

**Comment by t-moennich** [comment]
Having this same issue, please reopen 🙌🏼

**Comment by jozef-mikusinec-kiwicom** [comment]
Is there a reason `wrapRichTextChunksInFragment` is an option and not the only setting? It seems to me there is no reason for it to ever be false. Esp. now that its absence produces React warnings (which can also break tests when updating React).
