### ISSUE TITLE
@babel-plugin-formatjs Node API not working.

### ISSUE THREAD

**Issue by sergeushenecz** [formatjs/formatjs#4088]
## Which package?
babel-plugin-formatjs  version  10.5.0

on 9.2.2 version works good.

![image](https://user-images.githubusercontent.com/7217517/234364211-c0af099a-fbef-406f-9c4e-8cdb95152813.png)

## Describe the bug
Node API not working 

## To Reproduce

In the documentation write 

```
require('@babel/core').transform('code', {
  plugins: ['formatjs'],
}) 
```

## Expected behavior
In the documentation write return object with metadata 

`metadata['formatjs'].messages, metadata['formatjs'].meta `

but metadata always empty

When I use babel-plugin-react-intl and code 

```
require('@babel/core').transform('code', {
  plugins: ['react-intl'],
}) 
```

work all good.

**Comment by valeeum** [comment]
I'm having the same exact issue.

**Comment by sergeushenecz** [comment]
I think they forgot mention about changes for node api.

**Comment by sergeushenecz** [comment]
@longlho  Maybe do you know about this problem for node api ?

**Comment by Reeywhaar** [comment]
Metadata missing in @babel/core 7. Plugin should write messages to `this.file.metadata.messages` and not to `this.messages`
https://github.com/formatjs/formatjs/blob/c063f7bc4530af7ec6c5b68000887a3f55948f6e/packages/babel-plugin-formatjs/visitors/call-expression.ts#L76


```ts
const result = transformSync(
    `
  import { defineMessages } from 'react-intl';

  function some() {
    formatMessage({ id: 'foo', defaultMessage: 'bar'});
    defineMessages({foo: { id: 'foo', defaultMessage: 'bar' }});
  }
  `,
    {
      plugins: [require('babel-plugin-formatjs')],
    }
  )

  console.log('RESULT', result)
  process.exit(0)
```

```
RESULT {
  metadata: {},
  options: {
    assumptions: {},
    targets: {},
    cloneInputAst: true,
    babelrc: false,
    configFile: false,
    browserslistConfigFile: false,
    passPerPreset: false,
   ...
```

**Comment by Reeywhaar** [comment]
Oh, I see. Now you should use `onMsgExtracted: (filename, messages) => {}` option
https://github.com/formatjs/formatjs/blob/c063f7bc4530af7ec6c5b68000887a3f55948f6e/packages/babel-plugin-formatjs/index.ts#L82

Documentation is outdated.
