### ISSUE TITLE
@formatjs/cli-lib Missing message id for message:

### ISSUE THREAD

**Issue by sergeushenecz** [formatjs/formatjs#4089]
## Which package?
@formatjs/cli-lib

## Describe the bug
I have some code 

```
import { defineMessages } from 'react-intl';

const path = 'test';

defineMessages({
  phone: {
    id: `${path}.test`,
    defaultMessage: 'test phone',
  },
})
```

when i set id  without variable

```
defineMessages({
  phone: {
    id: `test_2132`,
    defaultMessage: 'test phone',
  },
})
```
then it work. When i use variable in id then not working.

and call 

` await extract([filename], {throws: true});`

```
Error: [FormatJS CLI] Missing message id for message: 
{
  "id": "",
  "defaultMessage": "test phone"
}
```

## Expected behavior
Take id from message declare with variable.

**Comment by longlho** [comment]
yeah extractor can't evaluate js, so no way we're able to resolve what that variable meant

**Comment by sergeushenecz** [comment]
@longlho  thanks for the reply. but early i use babel plugin for extract messages with id and works good.  After i migrated to new babel-plugin but in the newest plugin not working https://github.com/formatjs/formatjs/issues/4088. How i can use id with variable and extract messages maybe you know solutions?
