### ISSUE TITLE
React-Native Android: [Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting number.

### ISSUE THREAD

**Issue by stefandbd** [formatjs/formatjs#4096]
## Which package?

- react-intl
- @formatjs/intl-numberformat

## Describe the bug
Happening only on React-Native on Android:

[Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting number.
com.facebook.hermes.intl.JSRangeErrorException: Invalid number value !
RangeError: com.facebook.hermes.intl.JSRangeErrorException: Invalid number value !

## To Reproduce

`import {FormattedNumber, useIntl} from 'react-intl';`

```
                  <FormattedNumber
                      maximumFractionDigits={2}
                      value={40.5}
                      style="currency"
                      currency="GBP"
                  />
```

**Have to mention that if I remove style="currency" the error is gone - but of course it doesn't show anymore the GBP currency sign.**

## Polyfills integrated in index.js

```
import '@formatjs/intl-getcanonicallocales/polyfill';
import '@formatjs/intl-locale/polyfill';
import '@formatjs/intl-numberformat/polyfill';
import '@formatjs/intl-numberformat/locale-data/en';
import '@formatjs/intl-datetimeformat/polyfill';
import '@formatjs/intl-datetimeformat/locale-data/en';
import '@formatjs/intl-datetimeformat/add-all-tz';
```

## Bundle

Tried both options:

```
// def jscFlavor = 'org.webkit:android-jsc:+'
def jscFlavor = 'org.webkit:android-jsc-intl:+'
```

## Libraries/tools/packages/versions used

- Device: Android
- OS: API 33, Android 13
-  "@formatjs/intl-datetimeformat": "^6.8.0",
    "@formatjs/intl-getcanonicallocales": "^2.2.0",
    "@formatjs/intl-locale": "^3.3.0",
    "@formatjs/intl-numberformat": "^8.5.0",
    "@formatjs/intl-pluralrules": "^5.2.2",
    "@formatjs/cli": "^6.1.1",
    "react-intl": "^6.4.2",
    "react-native": "0.70.6",

**Comment by longlho** [comment]
Based on the stack trace it's a hermes bug and not us actually

**Comment by tmikov** [comment]
We are really not experts in all these packages and polyfills. So can you please narrow this down to one or two lines of JavaScript code, invoking the broken with API with fixed arguments, to demonstrate the error?

**Comment by stefandbd** [comment]
Some places had **maximumFractionDigits={0}** that was the issue.
We can close this
Thanks!
Cheers
