### ISSUE TITLE
Use as static methods

### ISSUE THREAD

**Issue by klimashkin** [formatjs/formatjs#41]
Hello! 
Is it possible to use format methods in static component methods?

**Comment by steffenmllr** [comment]
I'm also struggling with this - is there a way to access the translations outside of the component? Without the mixin? I'm trying get some model validation messages translated that don't live inside a component and couldn't find something in the docs

**Comment by steida** [comment]
@steffenmllr Have you succeeded? I suppose for formating outside component, we can bypass whole react-intl.

**Comment by DmitryAuine** [comment]
Oh i'm stuck... how i can use it outside component? I need translate message on action creator
```
export const fetchNotificationsFailure = () => ({
  type: appConstants.SHOW_ERROR,
  message: 'Please try to the refresh page. Error code: #n1.',
});
```

**Comment by steida** [comment]
It's easy. First, you have to realize everything happen in component, at least in app component
https://github.com/este/este/blob/master/src/common/app/start.js

You will render message on UI sooner or later, directly or with side effects helper. Check [Este](https://github.com/este/este) https://github.com/este/este/blob/master/src/browser/auth/LoginError.react.js

**Comment by zabojad** [comment]
Not being able to translate messages outside of components is just a pain, I have to move controller code to views just because of that... And for things that do not concern views at all like generating emails, etc...

**Comment by ericf** [comment]
@zabojad React Intl builds on a set of core libraries: http://formatjs.io/github/#core

**Comment by zabojad** [comment]
@ericf I know that. I've tried to used `Intl MessageFormat` outside of my react components but when I do so, I have to give it all the app messages and locale data as it's another instance of intl than the one used by my IntlProvider at the root of my App component... IMO, there should be a way to use the same intl instance for both...

**Comment by ericf** [comment]
@zabojad 

Everything goes through `IntlProvider` have you tried creating an instance of that?
```js
import {IntlProvider} from 'react-intl';
const {intl} = new IntlProvider({
  locale: 'en',
  messages: {},
}, {}).getChildContext();

intl.formatNumber(1000); // "1,000"
```

**Comment by lizhenhua86** [comment]
@ericf  your solution is work for me. thank you very much.

**Comment by cwtuan** [comment]
@klimashkin, Try alibaba/react-intl-universal, it Internationalize React apps not only for React.Component but also for Vanilla JS. It's just the right tool for your question.

**Comment by mschipperheyn** [comment]
If you use React 16, this is now possible simply with a little sugar. The reason it is possible is that React 16 allows you to return text directly from a component now. The difference with FormatMessage is that FormatMessage returns a `<span>Result text</span>` around your result text.

```
import React from 'react';
import { injectIntl } from 'react-intl';

const GetMessage = ({ id, params, intl }) => intl.formatMessage({ id, params });

export default injectIntl(GetMessage);

```

```
<GetMessage id="ui.key"/>
```

**Comment by MarcoNicolodi** [comment]
Hey guys.

Its been three years since this issue has been opened.

Considering the fact that the current user language is stored in the redux store, have you guys come up with common pratices to vanilla js intl with react-intl ?

For example i have this validation library which my file-uploader component uses to validate a given file:
```javascript
const maxSize = (file, size) => {
    if (file.size > size) {
        return 'File size is bigger than the max allowed';
    }
}
``` 

This is not the whole code, but should i just return a messageId, which makes my client code dependent on react-int, or should i turn this .js file into a .jsx file and return a `FormattedMessage`? Both of them dont look any good, but which approach have you guys done lately?

**Comment by adyz** [comment]
@ericf  - do you think that creating a function out of your code like this


```js
import { FormattedMessage, IntlProvider } from 'react-intl';
import { language, messages } from '../../i18nSetup';

const {intl} = new IntlProvider({locale: language, messages}, {}).getChildContext();

const translate = (id: string, values?: {}) => {
    return intl.formatMessage({id}, values);
};

export default translate;
``` 

and using it all over a react app

```
// a react component
import translate from '../translate';

// a react class
<h1>{translate('key.id')</h1>
```

would create any performance issues compared with the recommended way `<FormatMessage id="">`?

**Comment by veddermatic** [comment]
@adyz : Have you been using your solution, and if so, how does it perform?

**Comment by Masahiro-Toyomura** [comment]
@adyz Any update on the performance of this code?

**Comment by longlho** [comment]
this issue is very old, what r you looking for specifically?

**Comment by Masahiro-Toyomura** [comment]
@longlho I have 2 questions. 
First thing is for use React-Intl API outside of React components. I know we can now use 'createIntl' to achieve this, and I'm wondering whether it is okay to make a util file with the custom functions like the following and use it everywhere. I did not want to call createIntl() and getLocale, message again and again everywhere. 

`
import { createIntl, createIntlCache } from 'react-intl';
const locale = getLocale(); // this is my func
const messages = getMessage(); // this is my func 
const cache = createIntlCache();
const intl = createIntl({locale, messages}, cache);

export function formatMessage(message) {
    intl.formatMessage(message);
}

`

**Comment by Masahiro-Toyomura** [comment]
Also, secondly, I know for the class component, we need to call injectIntl() to wrap the class component and preferably I do not want to wrap so many components just to have the access to the props of Intl. So is there any way to being able to use Intl without calling injectIntl()?

**Comment by longlho** [comment]
> @longlho I have 2 questions.
> First thing is for using React-Intl API outside of React components. I know we can now use 'createIntl' to achieve this, and I'm wondering whether it is okay to make a util file with the custom functions like the following and use it everywhere. I did not want to call createIntl() and getLocale, message again and again everywhere.
> 
> ```ts
> import { createIntl, createIntlCache } from 'react-intl';
> 
> const locale = getLocale(); // this is my func
> const messages = getMessage(); // this is my func 
> const cache = createIntlCache();
> const intl = createIntl({locale, messages}, cache);
> 
> export function formatMessage(message) {
>     intl.formatMessage(message);
> }
> ```

Yes you can do that, we're doing at at Dropbox.

**Comment by Masahiro-Toyomura** [comment]
@longlho Sorry the discussion is kind of everywhere. Yes, I would like to use this custom formatMessage in react class component as well, and it seemed like its working fine. 

Do you see any potential issue with this approach of creating the util file like above rather than calling InjectIntl() for every class component?

**Comment by Masahiro-Toyomura** [comment]
The discussion is related to https://github.com/formatjs/react-intl/issues/1609

**Comment by Masahiro-Toyomura** [comment]
@longlho just before closing this old thread and moving to the new one, could you answer the question about the potential issue with using this custom function in class components when you get chance? Thank you so much

**Comment by longlho** [comment]
Since `locale` & `messages` are global you'd have to make sure your code operate in a runtime where those variables never change, which is generally the correct assumption for code in browser (but not SSR). Other than that it's ok.

**Comment by Masahiro-Toyomura** [comment]
@longlho sorry i'm a bit confused by 'operate in a runtime where those variables never change'. Why they should not change when you use this approach?

We allow users to choose a language on a setting page and we set ```locale``` to the chosen language so ```locale``` does change sometimes.

**Comment by longlho** [comment]
Every time you change locale or messages or config you need to re-create `intl` object. Based on your code snippet above it looks like you don't?
