### ISSUE TITLE
@formatjs/cli-lib node export() `ignore` opt is skip

### ISSUE THREAD

**Issue by mvidalgarcia** [formatjs/formatjs#4116]
## Which package?
@formatjs/cli-lib

## Describe the bug
Opt `ignore` is being ignored in the `extract` Node API.

The `ignore` opt is only being computed at the [CLI level](https://github.com/formatjs/formatjs/blob/51a42952e3898b2a00e1560d8accf1368c0eb52a/packages/cli-lib/src/cli.ts#L123). When using the `extract`  function directly, as stated [here](https://formatjs.io/docs/tooling/cli/#extraction-1), this opt is not being taken into account, even though [is exposed](https://github.com/formatjs/formatjs/blob/51a42952e3898b2a00e1560d8accf1368c0eb52a/packages/cli-lib/src/extract.ts#L52) as TS type.

## To Reproduce

Create a small script to extract translations and pass an ignore pattern.

```js
import { extract } from "@formatjs/cli-lib";

extract(myFiles, {
  format: tuaFormatter,
  ignore: "./**/*.{test,spec,d}.{ts,tsx,js,jsx}"
})
```

The test files are not ignored.

## Expected behavior
The test files  should be ignored.

**Comment by longlho** [comment]
If you're explicitly passing in your files using this lower level lib that list should already ignores things you don't want.
