### ISSUE TITLE
typescript warning about `@typescript-eslint/unbound-method` for `useIntl`

### ISSUE THREAD

**Issue by Morriz** [formatjs/formatjs#4133]
## Which package?

`react-intl@6.2.10`

## Describe the bug

just using the `useIntl` hook produces the following warning:
```
Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead.
```

## To Reproduce

```ts
const { formatMessage } = useIntl()
```

## Expected behavior

No warnings.

## Screenshots

<img width="1119" alt="Screenshot 2023-06-19 at 10 45 22" src="https://github.com/formatjs/formatjs/assets/941865/7a649840-b9bc-46bb-a6a2-ef79f1370dd0">

## Desktop (please complete the following information):

- OS: OSX

## Additional context

`react-intl` version: `6.2.10`

**Comment by boazpoolman** [comment]
I've got the same issue.

**Comment by KarafiziArtur** [comment]
Got same issue

**Comment by TrejGun** [comment]
hey guys I guess you have to see this https://github.com/typescript-eslint/typescript-eslint/issues/2245

**Comment by jrnail23** [comment]
@longlho, would you accept a PR that resolves this?  It should be a non-breaking type change where `this: void` is added to the parameter list of methods explicitly bound to `intl`.
