### ISSUE TITLE
docs: missing @formatjs/intl-segmenter

### ISSUE THREAD

**Issue by mrienstra** [formatjs/formatjs#4137]
_links below point to 61bb35e, which is currently the latest commit to `main`_

https://github.com/formatjs/formatjs/tree/61bb35e/packages/intl-segmenter#readme
and
https://www.npmjs.com/package/@formatjs/intl-segmenter

point to:
https://formatjs.io/docs/polyfills/intl-segmenter
> Page Not Found

Which is odd, because [website/docs/polyfills/intl-segmenter.md](https://github.com/formatjs/formatjs/blob/61bb35e/website/docs/polyfills/intl-segmenter.md) exists, and it appears that the docs have been re-published in the last 5 months, but maybe I'm mistaken. Perhaps because it's not linked to from an existing page?

Looks like it needs to be added to the following:
* [README.md?plain=1#L24-L31](https://github.com/formatjs/formatjs/blob/61bb35e/README.md?plain=1#L24-L31)
* [website/sidebars.js#L41-L49](https://github.com/formatjs/formatjs/blob/61bb35e/website/sidebars.js#L41-L49)
* [website/docs/polyfills.md?plain=1#L10-L17](https://github.com/formatjs/formatjs/blob/61bb35e/website/docs/polyfills.md?plain=1#L10-L17)
* [BUILD#L99-L104](https://github.com/formatjs/formatjs/blob/61bb35e/BUILD#L99-L104)

May or may not sense to mention it here:
* [website/docs/react-intl.md](https://github.com/formatjs/formatjs/blob/61bb35e/website/docs/react-intl.md)

Happy to open a PR.

**Comment by mrienstra** [comment]
CCing @matijagaspar, @longlho, @micheleriva since y'all were involved with #3917, and may therefore have an above-average amount of context to bring to bear. No rush.

**Comment by felixfbecker** [comment]
It would be nice to have this exposed as a method on the `IntlShape` too

**Comment by felixfbecker** [comment]
This is still relevant, segmenting is a very important use case for i18n

**Comment by mrienstra** [comment]
Decided to just go for a PR. Fixed 2 missing references to `Intl.LocaleMatcher` while I was at it.

Planning to open a new issue re: missing docs for `intl-durationformat` & `intl-enumerator`.
