### ISSUE TITLE
Escaping not working (https://formatjs.io/docs/core-concepts/icu-syntax/#quoting--escaping)

### ISSUE THREAD

**Issue by apetrus20** [formatjs/formatjs#4139]
Hi, I am trying to escape curly braces, custom html tag and a link with href and target. I looked over this documentation https://formatjs.io/docs/core-concepts/icu-syntax/#quoting--escaping and it's not working. For the curly braces, the escaping lets me to compile the translations but it keeps the escaping element in the message. 

Here is a codesandbox (https://codesandbox.io/s/adoring-chihiro-6tmjm8?file=/src/App.js) where I added exactly the values which I am trying to escape. 

**### Expected behavior**
`Curly braces ({}) are not allowed` - works fine with defaultMessage but doesn't work when messages are passed to intlProvider

**### Actual result** 
`Curly braces ('{}) are not allowed`

Executable | Version
-- | --
npm ls react-intl | "^6.4.4"
npm ls react | "^18.2.0"
npm ls  @formatjs/cli | "6.0.1"

**Comment by Atrue** [comment]
Hi. It looks like I have similar issue with escaping tags and formatjs/cli. Here are some details that might be helpful:

I defined a messsage according to the article https://formatjs.io/docs/core-concepts/icu-syntax#quoting--escaping
```
const definedMessages = defineMessages({
    test1: {
        id: 'test1',
        defaultMessage: "No tag '<notATag>"
    },
});
```
### Issue 1
`extract` and `compile` command give the result:
```
{
  "test1": "No tag '<notATag>"
}
```
But formatting gives the result with `'`:
```
console.log(intl.formatMessage(definedMessages.test1))
// No tag '<notATag>
```
### Issue 2
Using `--flatten` argument with the `extract` command gives another result (no escaping `'`):
```
{
  "test1": {
    "defaultMessage": "No tag <notATag>"
  }
}
```
But using `compile` for this result gives the error:
```
[@formatjs/cli] [WARN] Error validating message "No tag <notATag>" with ID "test1" in file "temp.json"
SyntaxError: UNCLOSED_TAG
```
### Issue 3
If I create the final translation file manually without escaping it works fine, but it conflicts the docs:
```
{
  "test1": "No tag <notATag>"
}
```
Then format the message
```
console.log(intl.formatMessage(definedMessages.test1))
// No tag <notATag>
```

**Comment by jaredkrinke** [comment]
I'm also hitting this. Why did this bug get closed without any response?

**Comment by jaredkrinke** [comment]
Is there an older version where this was working as expected?
