### ISSUE TITLE
tsc not generating message id

### ISSUE THREAD

**Issue by kamathgopal** [formatjs/formatjs#4141]
I have been developing a project and transpiling my code using tsc. I have added below code in my tsconfig.json

`
{
  "compilerOptions": {
    "plugins": [
      {
        "transform": "@formatjs/ts-transformer",
        "import": "transform",
        "type": "config",
        "overrideIdFn": "[sha512:contenthash:base64:6]",
        "ast": true
      }
    ]
  }
}
`

and I simply build the project using tsc (not using webpack bundler). When I checked build output I couldn't see any id being generated.

![Screenshot 2023-06-29 at 16 31 26](https://github.com/formatjs/formatjs/assets/7930153/8bf8ddc1-c7fe-44e0-a66b-4b8b482b4762)

However if I build same code using webpack (with ts-loader) id gets generated. What I could be missing here?

**Comment by longlho** [comment]
Ts compiler has no plugin support so you have to use some other tools like ttypescript or webpack...
