### ISSUE TITLE
`@formatjs/cli` Can't use a custom formatter to extract messages to a non-JSON format

### ISSUE THREAD

**Issue by jrnail23** [formatjs/formatjs#4149]
## Which package?

`@formatjs/cli`

## Describe the bug

The extract script runs `stringify` on the formatted extracted result, which produces invalid results for non-JSON based formats. In my case, I created a custom formatter to convert the extracted messages to CSV, since none of the JSON-based formats that our TMS (Phrase) accepts as an import/push source supports message descriptions.

As a workaround, I had to write an additional script to transform the output file's content to CSV format.

## Expected behavior

I expected the resulting formatted file to contain the exact content produced by my custom formatter.

To address this issue while avoiding a breaking change to existing users, perhaps an optional flag can be introduced for the `extract` command to indicate that the supplied formatter's output should be written directly as an unformatted string (bypassing the `stringify` call).

**Comment by jrnail23** [comment]
FWIW, @longlho, if you're open to accepting a PR to address this, I'd be willing to submit one.

**Comment by longlho** [comment]
Yeah i'd be open to that

**Comment by jrnail23** [comment]
@longlho, do you have any preference for the naming of the CLI flag?

**Comment by jrnail23** [comment]
Actually, another way to go here might be that if the formatter result is a string, just return that string directly with no `stringify`, etc.  That's simpler (no CLI flag needed) and seems unlikely to break existing usages.  What do you think, @longlho?

**Comment by longlho** [comment]
I guess we can infer based on output extension?

**Comment by jrnail23** [comment]
that's not a bad idea.  Are you thinking anything with `*.json` would be stringified, and anything else would not?

**Comment by longlho** [comment]
I think json should be the default and then *.csv uses the csv formatter

**Comment by jrnail23** [comment]
I wasn't looking to add a CSV formatter to the core project -- different usages might need different column names and CSV generation options.
I just wanted to be able to use my own custom CSV formatter.

Also, doing CSV correctly would probably require adding a new dependency, which I'm sure you don't take lightly.

**Comment by longlho** [comment]
Hmm I thought we already support custom formatter?

**Comment by jrnail23** [comment]
you do, but the point here is that the result of the custom formatter currently gets stringified by the extract function, which prevents it from working with non-JSON output formats (contaminates a valid CSV string).

https://github.com/formatjs/formatjs/blob/main/packages/cli-lib/src/extract.ts#L250

**Comment by longlho** [comment]
Kk hmm then maybe I can extend the formatter API to allow custom stringify? Does that work for u?

**Comment by jrnail23** [comment]
absolutely!

**Comment by jrnail23** [comment]
(bumping to keep the stale bot away)

**Comment by jrnail23** [comment]
@longlho, thanks for addressing this!
