### ISSUE TITLE
A message didn't get extracted if the id is not plain string

### ISSUE THREAD

**Issue by mmeqbel-wiley** [formatjs/formatjs#4162]
## Which package?

CLI

## Describe the bug

if a message have a string template in the id property, then it would not be extracted using the cli tool

## To Reproduce

``` 
export const prefix = '@'
defineMessages({
  foo: {
    id: `${prefix}id`,
    defaultMessage: 'foo',
    description: 'bar',
  },
})

```

then run `formatjs extract` will not produce this message

## Expected behavior

A message should be extracted normally

**Comment by longlho** [comment]
Yeah non-lietral fields cannot be extracted

**Comment by mmeqbel-wiley** [comment]
@longlho this should be documented somewhere right?
