### ISSUE TITLE
Rich text formatting with apostrophe before tag breaks resolution

### ISSUE THREAD

**Issue by vsobotka** [formatjs/formatjs#4173]
## Which package?
reactt-intl@6.4.4

## Describe the bug

When using rich text formatting with apostrophe before the tag, the apostrophe is ignored and the rest of the message is not processed.

## To Reproduce
```
<FormattedMessage
  id="app.new"
  defaultMessage="L'<b>eau</b> et les <b>Semences</b>"
  values={{ b: (chunk) => <b>chunk</b> }}
/>
```
Notice the apostrophe before the first tag. When you remove it, both tags are processed. If not, neither is processed. Possible workaround is to use double apostrophe.

## Expected behaviour

The apostrophe does not break tag resolution, and does not need to be doubled to work.

**Comment by blicksky** [comment]
We're also seeing this with react-intl@6.4.2. In our situation, the `defaultMessage` was in English and did not have a apostrophe, but when the translator provided the French translation, they added an apostrophe before the rich text placeholder and it exhibited the behavior described above by @vsobotka.

**Comment by longlho** [comment]
they can either use HTML entities or escape it, or rather the TMS they use should automatically handle it
