### ISSUE TITLE
ts-transformer doesnt inject id in conditions

### ISSUE THREAD

**Issue by v0l** [formatjs/formatjs#4175]
## Which package?
`"@formatjs/ts-transformer": "^3.13.3",`

## Describe the bug
ts-transformer doesn't create id for ternary if in component
**Doesnt work**
```js
<FormattedMessage defaultMessage={ev ? "Save" : "Start Stream"} />
```
**Works**
```js
{ev ? <FormattedMessage defaultMessage="Save" /> : <FormattedMessage defaultMessage="Start Stream" />}
```

Which seems fair enough until you're greeted with the missing id error message and you spend hours messing with webpack trying to figure out what's wrong

### Codesandbox URL

Please include a codesandbox URL if possible

**Comment by longlho** [comment]
Yeah defaultMessage has to be a string literal

**Comment by v0l** [comment]
Understandable, but can we get an error in ts-transformer instead of just ignoring it and wasting hours wondering what is wrong?
