### ISSUE TITLE
ESLint errors are not issued for intl.$t function calls

### ISSUE THREAD

**Issue by apiel51** [formatjs/formatjs#4182]
## Which package?

eslint-plugin-formatjs

## Describe the bug

The various ESLint rules in the plugin apply to `intl.formatMessage()` but not `intl.$t()` despite [$t being shorthand for formatMessage](https://github.com/formatjs/formatjs/blob/d63e778d4900728d4b2f6710f11af683ed5c4bc7/packages/intl/CHANGELOG.md?plain=1#L168).

Thinking that we should update [this line](https://github.com/formatjs/formatjs/blob/main/packages/eslint-plugin-formatjs/util.ts#L71) from:
```typescript
node.callee.property.name === 'formatMessage' &&
```
to:
```typescript
(node.callee.property.name === 'formatMessage' || node.callee.property.name === '$t') &&
```

Happy to cut a PR for this.

### Reproducible Steps/Repo

1. Enable the `formatjs/enforce-description` ESLint rule
2. Call `intl.$t()` without a description
3. Observe that no error is issued

## Expected behavior

An error should be issued in the above case.

**Comment by longlho** [comment]
Yup PR is always welcome
