### ISSUE TITLE
IntlMessageFormat throws EXPECT_SELECT_ARGUMENT_SELECTOR_FRAGMENT when select value have dash

### ISSUE THREAD

**Issue by iaroslavshvets** [formatjs/formatjs#4190]
## Which package?

intl-messageformat@10.5.2

## Describe the bug

passing value with `-` for `select` throws error. For instance:

`{id, select, id_value_1 {{id}} other {other}}` => works
`{id, select, id_value-1 {{id}} other {other}}` => throws

## To Reproduce

[Codesandbox URL](https://codesandbox.io/s/nostalgic-fermat-n3fly2?file=/src/index.mjs)

### Reproducible Steps/Repo

```
import {IntlMessageFormat} from 'intl-messageformat';

const messageFormat = new IntlMessageFormat('{id, select, id_value-1 {{id}} other {other}}', 'en');

messageFormat.format({id: 'id_value-1'})
```
## Expected behavior

I expect any value can be passed. There are no restrictions for values in ICU format itself AFAIK. 
https://format-message.github.io/icu-message-format-for-translators/editor.html - such message would work just fine. 
And it worked some time ago in previous `intl-messageformat` versions. For instance, 2.2.0 will parse it just fine.

## Additional context

This library is used in other packages, such as `i18next-icu` and similar. All in all - it leads to getting unparsed messages, because of parsing error in this lib and we can't do anything about it on our side as ICU formatting is completely delegated to intl-messageformat.

**Comment by longlho** [comment]
The site you linked is not ICU-compliant. ICU variable name explicitly ban -

**Comment by iaroslavshvets** [comment]
> The site you linked is not ICU-compliant. ICU variable name explicitly ban -

So if I understand correctly ICU standard bans such values and behaviour in intl-messageformat@2.2.0 was a rather bug then a feature? And we should not expect this to work, right?

**Comment by longlho** [comment]
Yes that's correct

**Comment by iaroslavshvets** [comment]
Thanks for the explanation )
