### ISSUE TITLE
<FormattedDate> display a date one day earlier than input in timezone with negative offset and format YYYY-MM-DD

### ISSUE THREAD

**Issue by jojoman2** [formatjs/formatjs#4191]
## Which package?
react-intl

## Describe the bug
If you set your computer to a timezone with negative offset from UTC (I used Buenos Aires - Argentina) and use a string on the format to YYYY-MM-DD as a parameter to `<FormattedDate>`, the date becomes one day earlier than the input.

## To Reproduce
First  change your computers timezone to a timezone with negative offset from UTC, such as Buenos Aires - Argentina.
Codesandbox: https://codesandbox.io/s/quizzical-dust-p4xhvp?file=/src/App.tsx
Code:  `<FormattedDate value="2023-10-15" />` (you will need an IntlProvider as well)

### Reproducible Steps/Repo
Look at the date displayed. It will say 14th of October

## Expected behavior
The date should shown should be the 15th of October, since that was the input

## Desktop (please complete the following information):

- OS: Mac
- Browser: Chromium
- Version 116.0.5845.179

## Additional context

This is likely the result of this odd behaviour of the date constructor:
![image](https://github.com/formatjs/formatjs/assets/2865861/c49ad202-7416-41ec-97fc-e3f7c0ceb07f)

**Comment by longlho** [comment]
This is because you're using native Date parser when passing in a string. The fix is to pass in a Date object
