### ISSUE TITLE
Currency dropping trailing zero in decimal

### ISSUE THREAD

**Issue by andrewholt** [formatjs/formatjs#42]
With a message like this:

`sampleMessage: '<strong>{amount, number, usd}</strong> was charged to your credit card.'`

with a custom format like so:

`number: {
      usd: { style: 'currency', currency: 'USD' }
}`

and the component displaying the message with:

`<div dangerouslySetInnerHTML={{__html:
              this.formatMessage(this.getIntlMessage('Messages.sampleMessage'), {
                amount:35.50,
              })
}} />`

The currency is displaying as `$35.5`. This did not seem to be resolved in the last push. Is this something  we're doing on our end incorrectly?

**Comment by ericf** [comment]
@andrewholt just a note on a workaround until Chrome fixes this, you can specify a value for `minimumFractionDigits` and set it to `0` if you want all env to render like Chrome, or `2` if you want to show cents. I would recommend using a named format for this so it's easier, e.g.:

```jsx
var Component = React.createClass({
    mixins: [ReactIntl.Mixin],
    
    render: function () {
        return <ReactIntl.Number format="USD">{100}</ReactIntl.Number>;
    }
});

var intlData = {
    locales: 'en-US',
    formats: {
        number: {
            USD: {
                style: 'currency',
                currency: 'USD',
                minimumFractionDigits: 2
            }
        }
    }
};

React.render(
    <Component {...intlData} />,
    document.getElementById('example')
);
```
