### ISSUE TITLE
npm install issues with typescript 5.2.2

### ISSUE THREAD

**Issue by The-Lord-of-Owls** [formatjs/formatjs#4201]
## Description

Unable to install into existing project due to dependancy issues with typescript 5.2.2. Log output below

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-scripts@5.0.1
npm ERR! Found: typescript@5.2.2
npm ERR! node_modules/typescript
npm ERR!   peer typescript@">= 2.7" from fork-ts-checker-webpack-plugin@6.5.3
npm ERR!   node_modules/fork-ts-checker-webpack-plugin
npm ERR!     fork-ts-checker-webpack-plugin@"^6.5.0" from react-dev-utils@12.0.1
npm ERR!     node_modules/react-dev-utils
npm ERR!       react-dev-utils@"^12.0.1" from react-scripts@5.0.1
npm ERR!       node_modules/react-scripts
npm ERR!         react-scripts@"5.0.1" from the root project
npm ERR!   peer typescript@">=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta" from tsutils@3.21.0
npm ERR!   node_modules/tsutils
npm ERR!     tsutils@"^3.21.0" from @typescript-eslint/eslint-plugin@5.62.0
npm ERR!     node_modules/@typescript-eslint/eslint-plugin
npm ERR!       @typescript-eslint/eslint-plugin@"^5.5.0" from eslint-config-react-app@7.0.1
npm ERR!       node_modules/eslint-config-react-app
npm ERR!         eslint-config-react-app@"^7.0.1" from react-scripts@5.0.1
npm ERR!         node_modules/react-scripts
npm ERR!       1 more (eslint-plugin-jest)
npm ERR!     tsutils@"^3.21.0" from @typescript-eslint/type-utils@5.62.0
npm ERR!     node_modules/@typescript-eslint/type-utils
npm ERR!       @typescript-eslint/type-utils@"5.62.0" from @typescript-eslint/eslint-plugin@5.62.0
npm ERR!       node_modules/@typescript-eslint/eslint-plugin
npm ERR!         @typescript-eslint/eslint-plugin@"^5.5.0" from eslint-config-react-app@7.0.1
npm ERR!         node_modules/eslint-config-react-app
npm ERR!         1 more (eslint-plugin-jest)
npm ERR!     1 more (@typescript-eslint/typescript-estree)
npm ERR!   3 more (the root project, react-intl, @formatjs/intl)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"5.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"5.0.1" from the root project
npm ERR!

## To Reproduce

Existing project using the following packages listed below. Project does not introduce any non-public libraries that could be interfering with anything. Simply posting the full dependancy list just in case, I don't think anything here will actually be helpful other than the typescript version.
@emotion/react ^11.11.1
@emotion/styled ^11.11.0
@emotion/types ^0.7.0
@mui/icons-material ^5.14.9
@mui/material ^5.14.9
@mui/types ^7.2.4
@reduxjs/toolkit ^1.9.5
@testing-library/jest-dom ^5.17.0
@testing-library/react ^13.4.0
@testing-library/user-event ^13.5.0
@types/enzyme ^3.10.13
@types/jest ^29.5.5
@types/node ^20.6.2
@types/react ^18.2.21
@types/react-dom ^18.2.7
@types/react-redux ^7.1.26
@types/react-router ^5.1.20
@types/react-router-dom ^5.3.3
axios ^1.5.0
enzyme ^3.11.0
formik ^2.4.4
moment ^2.29.4
react ^18.2.0
react-dom ^18.2.0
react-redux ^8.1.2
react-router ^6.16.0
react-router-dom ^6.16.0
react-scripts 5.0.1
typescript ^5.2.2
web-vitals ^2.1.4

## Screenshots

![image](https://github.com/formatjs/formatjs/assets/119661891/ab9b8e78-f581-4549-9710-b887339a7247)

## Desktop (please complete the following information):

- OS: Windows 10

**Comment by longlho** [comment]
this' been fixed in latest version
