### ISSUE TITLE
CLI extraction doesn't preserve new line characters

### ISSUE THREAD

**Issue by brawaru** [formatjs/formatjs#4203]
## Which package?

`@formatjs/cli`

## Describe the bug

When extracting strings with CLI, new line characters (`\n`) are not preserved in the resulting file, instead being replaced with spaces.

### Codesandbox URL

https://stackblitz.com/edit/node-bz5cjc?file=package.json

### Reproducible Steps/Repo

1. When defining a message using `defineMessages`, put `\n` in `defaultMessage`
2. Run extraction (in linked StackBlitz repro above it's done with `pnpm intl:extract`)
3. Look at the resulting file (in repro `locales/en-US/index.json`)

## Expected behaviour

Your message is exported with new lines.

## Screenshots

N/A

## Desktop (please complete the following information):

- OS: Windows 10, Linux 6.2.0
- Node.js: 18.18.0, 20.6.1
- Browser: N/A
- Version: N/A

## Smartphone (please complete the following information):

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

## Additional context

N/A

**Comment by longlho** [comment]
Yeah that's expected. Newlines are effectively layout control and you should use html for it

**Comment by brawaru** [comment]
I don't think that's a good expectation. You can use `white-space: pre` or `<pre>` in HTML to preserve new lines, and you can also use `formatMessage` outside the HTML (e.g., in Node.js app). Passing line break via a variable doesn't sound like a good idea and will be annoying to translators. Because they will have to translate one line of `Some text{newline}Other text` when they could've translated
```
Some text
Other text
```
instead.

**Comment by brawaru** [comment]
Ooh, there's `--preserve-whitespace` argument, this works for us. Sorry, should've looked at the code.
