### ISSUE TITLE
Please update the docs

### ISSUE THREAD

**Issue by CodeAndWeb** [formatjs/formatjs#4227]
There are several changes in the documentation markdown files which do not show up on the webpage.
Please update the webpage!

**Comment by events-jonas-chrisw** [comment]
also now has peer dependency of typescript 5

**Comment by cungminh2710** [comment]
it has been a while 😢 #3987

**Comment by longlho** [comment]
Yeah apology for the delay. We use docusaurus and there have been a ton of breakin changes so itll take us a while to get that up & running again. If anyone wants to contribute you're more than welcome as well. It's all under website folder

**Comment by CodeAndWeb** [comment]
I might take a look... could you provide a rough outline how the docs were built in the past?
Starting from a fresh git clone? What had to be done?

**Comment by cungminh2710** [comment]
the BUILD file for website is gone for some reasons. Any context around that one?

**Comment by longlho** [comment]
yeah it was a PITA to get docusaurus to work w/ bazel so that folder operate as an indenpendent project now

**Comment by cungminh2710** [comment]
Cool. So I assume if we can reintroduce a BUILD file, or refactor with different framework to support Bazel, it should fix the issue. 

Is there anything else for deployment? 

I might make some progress this weekend 👍

**Comment by longlho** [comment]
Doc's been updated
