### ISSUE TITLE
Html entities displayed as strings in FormattedMessage

### ISSUE THREAD

**Issue by WoodenPC** [formatjs/formatjs#4239]
Hi trying to upgrade react-intl version in project from v3 to last version, facing some difficulties. 

## Which package?
**react-intl**

## Describe the bug
I have some legacy messages with html entities. and  html entities such as **\&nbsp; \&lt; \&gt**; etc displayed **as is** in FormattedMessage . But in version 3.1.11 they were rendered correctly as html entities not as string https://codesandbox.io/s/ig2g4 

react-intl 6.4.4 message is Domain:\&nbsp; {domain}
![image](https://github.com/formatjs/formatjs/assets/25397745/4037ac77-8675-433f-8f69-11ee167fa02d)
react-intl 3.1.11
![image](https://github.com/formatjs/formatjs/assets/25397745/de08d460-4d1d-48c1-9260-2aef78d9ba1a)

**Comment by aeifn** [comment]
I'm facing the same problem.

**Comment by aeifn** [comment]
HTML entities seem to be intentionally unsupported by `formatjs` as not safe: https://github.com/formatjs/formatjs/discussions/3487

**Comment by aeifn** [comment]
One way around this is to replace all `&nbsp;` substrings with `{nbsp}`, and then set `nbsp` as the value for `FormattedMessage`.
