### ISSUE TITLE
The naming of $t causes a conflict

### ISSUE THREAD

**Issue by msobiecki** [formatjs/formatjs#4241]
## Which package?

[babel-plugin-formatjs](https://github.com/formatjs/formatjs/tree/main/packages/babel-plugin-formatjs)

## Describe the bug
I have a rather specific problem with the babel-plugin-formatjs library. After updating the package, the code stopped building, I found the change that causes this:  https://github.com/formatjs/formatjs/commit/f55cd1dadc0f01aba7a461357b061abae86d1d41

When I run a test of an application that loads another library built by esbuild, the following problem occurs. This plugin treats this code as if it was related to react-intl and tries to use it, which ends in the following error, e.g. when I try to run a test using this package:
```
Test suite failed to run

    TypeError: /home/projects/x/packages/lib/dist/cjs/index.js: Cannot read properties of undefined (reading 'isObjectExpression')
      at PluginPass.visitor (../../node_modules/.pnpm/babel-plugin-formatjs@10.5.7/node_modules/babel-plugin-formatjs/visitors/call-expression.js:120:31)
```

If the code is not minified, everything works. But when the minify flag is set, esbuild minifies the code using the $t nomenclature as well.
https://www.npmjs.com/package/rollup-plugin-esbuild?activeTab=readme#standalone-minify-plugin

Before minify:
```
const _exp$3 = () => Container;
const Box$2 = /* @__PURE__ */ react.styled(_exp$3())({
  name: "Box",
  class: "header_b1oqj4ug",
  propsAsIs: true
});
```

After minify:
```
$t = () => R,
Mt = n.styled($t())({
    name: "Box",
    class: "header_b1oqj4ug",
    propsAsIs: !0
}),

```

### Codesandbox URL

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/msobiecki/repro-formatjs?file=src%2Fhooks%2FuseTestHook.ts)

### Reproducible Steps/Repo

```
npm i & npm test
```

## Expected behavior

The code should better check whether the actual function is a react-intl function.

## Screenshot

![image](https://github.com/formatjs/formatjs/assets/9337412/1beffec8-d572-41ac-982e-58a02719afb6)

**Comment by longlho** [comment]
hmm why does your babel run on minified code?

**Comment by idoodler** [comment]
I do have the exact same issue using this package in storybook

**Edit**
I worked around it by excluding the `@storybook/components` package from babel

**Comment by PSniezak** [comment]
If anyone has the same issue, you need to upgrade `babel-preset-formatjs` to at least `10.5.14` (see https://github.com/formatjs/formatjs/releases/tag/babel-plugin-formatjs%4010.5.14)
