### ISSUE TITLE
NumberFormatOptions not assignable to Intl.NumberFormatOptions

### ISSUE THREAD

**Issue by vktrl** [formatjs/formatjs#4245]
## Which package?

intl-messageformat

## Describe the bug

`getNumberFormat` in `Formatters` has a customized `NumberFormatOptions` argument type that is not assignable to `Intl.NumberFormatOptions`.

> Types of property 'useGrouping' are incompatible.
        Type 'UseGroupingType | undefined' is not assignable to type 'boolean | undefined'.
Type '"auto"' is not assignable to type 'boolean | undefined'.

### Codesandbox URL

[Codesandbox](https://codesandbox.io/s/musing-chihiro-r24qwt?file=/src/index.ts)

**Comment by longlho** [comment]
yeah that's intended. TS type always lag behind
