### ISSUE TITLE
UNCLOSED tag error when using a single quote and no white space @formatjs/icu-messageformat-parser

### ISSUE THREAD

**Issue by Georgegriff** [formatjs/formatjs#4247]
## Which package?
@formatjs/icu-messageformat-parser

Since this is a monorepo. Please specify which package this bug report is for.

## Describe the bug

I have a translation service which ended up giving me some Italian that resulted in a trailing single quote inside of a html tag which seems to break the parser.

```js
import {parse} from "@formatjs/icu-messageformat-parser";

// works
parse("Hello <span>World' </span>")
// errors
parse("Hello <span>World'</span>")
```

If it helps here is the exact machine translation that broke us

```
Di seguito è riportato un elenco di scorciatoie per aiutarti a navigare nel laboratorio quando il focus della tastiera è <span>esterno all'</span>editor di codice
```
`<span>esterno all'</span>` without spacing being the key problem

## To Reproduce

Here is a reproduction: https://codesandbox.io/s/crazy-resonance-5yd85c?file=/src/index.mjs:0-148

### Codesandbox URL

Please include a codesandbox URL if possible

Here is a reproduction: https://codesandbox.io/s/crazy-resonance-5yd85c?file=/src/index.mjs:0-148

## Expected behavior

Message is parsed

## Screenshots

<img width="595" alt="image" src="https://github.com/formatjs/formatjs/assets/9056958/a51a868c-b58c-40b9-968d-6cf2c2d5df5f">

**Comment by longlho** [comment]
apostrophe is used as the escape character in ICU so you either should double escape it, or use HTML entities

**Comment by Georgegriff** [comment]
Thanks for the reply, i had missed that in the spec, I'll see about ensuring our machine translations are escaped accordingly
