### ISSUE TITLE
[Feature request]: plural format helper

### ISSUE THREAD

**Issue by enagy27** [formatjs/formatjs#4250]
Working with the standard ICU format while developing can be tricky, especially across a large team I find myself referring to previous instances frequently in order to get the syntax nailed down.

To solve this I've implemented a helper function:
```ts
/**
 * Note that I was having some trouble with typing this as an extension of `Record<`=${number}`, string>`
 * so this is currently using a limited set of exact value types
 */
interface PluralMatches {
  zero?: string
  one: string
  two?: string
  few?: string
  many?: string
  other: string
  "=0"?: string
  "=1"?: string
  "=2"?: string
  "=3"?: string
  "=4"?: string
  "=5"?: string
  "=6"?: string
  "=7"?: string
  "=8"?: string
  "=9"?: string
  "=10"?: string
}

/**
 * Creates a set of plural rules for use with `intl.formatMessage`
 *
 * @example
 * ```ts
 * intl.formatMessage(
 *   {
 *     id: "user.workspaces",
 *     description: "The number of workspaces the user has access to.",
 *     defaultMessage: plurals("workspaces", {
 *       one: "{workspaces} workspace",
 *       other: "{workspaces} workspaces",
 *     }),
 *   },
 *   { workspaces: spaces.length }
 * )
 * ```
 */
export function plural<TKey extends string>(key: TKey, matches: PluralMatches) {
  const matchesArg = Object.entries(matches)
    .map(([value, text]) => `${value} {${text}}` as const)
    .join(" ")

  return `{${key}, plural, ${matchesArg}}` as const
}

```

This feels like a useful abstraction, but it comes with some added challenges for static analysis during extraction that I'm currently working to resolve. The main one is that I could use a hook for transforming the source of a file in memory before extraction to enable all of the current tooling to work properly. Similarly that tooling could be helpful for getting each of the existing lint rules to work as expected.

I'll file separate issues for the supporting behaviors, but in the meantime I wanted to propose this syntax and gauge interest in submitting a PR for this change. Thanks!

**Comment by enagy27** [comment]
Supplementally I've created the following lint rule to apply to `plural` calls, which can catch:
- Variables that aren't within `values`
- Variables outside of the current `plural` call

[ESLint rule gist 🔗 ](https://gist.github.com/enagy27/1a1de1b8c3e5a79573b9cc9602f07de4)

**Comment by longlho** [comment]
I haven't seen this issue especially since source language is typically English and only has 2 plural forms. I personally haven't seen =0/1/2... being used much because most TMSes don't even support them.
This syntax also prevents nested plurals/selects?

**Comment by enagy27** [comment]
We also haven't used anything other than `one` and `other` to my knowledge. To be fair some of this has been because of my limited familiarity with the syntax so this is coming from a place of curiosity and trying to understand better some of these challenges.

When you say that this prevents nesting could you give me an example? My thinking was that it could be done as:
```ts
defaultMessage: select("gender", {
  male: plural("respondents", { one: "# Man", other: "# Men" }),
  female: plural("respondents", { one: "# Woman", other: "# Women" }),
  other: plural("respondents", { one: "# Respondent", other: "# Respondents" }),
})
```

Is there another format that you were considering which could pose other problems?

**Comment by longlho** [comment]
So you'd have to declare the sentences multiple times? An example is something like
`The rate associated with {n, plural, one{# store} other{# stores}} is: {rate, number, ::percent}. Click <link>here</link> to edit`

**Comment by enagy27** [comment]
Thanks for the example! That helps a bit to flesh this out. My hope is that this is functionally equivalent because it's outputting a string at the end of the day, so we should be able to compose it. This is how I imagine that could look:
```ts
`The rate associated with ${plural("n", { one: "# store", other: "# stores" })} is: ${number("rate", "percent")}. Click <link>here</link> to edit`
```

**Comment by longlho** [comment]
ah kk now I understand. Tbh it's equivalent to the ICU syntax and the embedded ICU syntax is easier to do static analysis on so I don't think this is necessarily any better.
I think it also gave the wrong impression that you CAN do string concat/tokenization while you shouldn't, since it's not i18n-safe.

**Comment by enagy27** [comment]
That definitely makes sense and may just be the kind of thing to keep downstream if folks want it and are ok with the tradeoffs as I am.

In order to do this downstream though I could use a hook to transform the code in memory before it’s extracted. Is that something you’d be open to me posting a PR for?

**Comment by longlho** [comment]
I'm not sure I understand. Since your syntax is different our extractor can't extract it anw let alone transform.

**Comment by enagy27** [comment]
I'm thinking that if I was able to send down something that could modify the source in-memory within `transformWithTs` that could do the trick

**Comment by longlho** [comment]
The extractor doesn't modify the source it only parses & extract. If u need to modify source u need a linter and if u wanna modify build output it's likely a plugin in your build tool.

**Comment by enagy27** [comment]
I don't truly want to do either of those, really. I want to modify the source before extraction is run on the file in order to transform the output of the `plural` call into the string that's expected by the extractor
