### ISSUE TITLE
__setDefaultTimeZone does not handle "America/Indiana/Indianapolis" timezone

### ISSUE THREAD

**Issue by parondeau** [formatjs/formatjs#4254]
## Which package?

@formatjs/intl-datetimeformat

## Describe the bug

__setDefaultTimeZone can not handle timezone passed as "America/Indiana/Indianapolis" and throws "Invalid timeZoneName" error. This is a valid timezone according to the @formatjs timezone polyfills and calling `Intl` in a modern browser.

<img width="523" alt="image" src="https://github.com/formatjs/formatjs/assets/1735851/1a423513-dfff-4244-8011-57598d4124a4">
<img width="560" alt="image" src="https://github.com/formatjs/formatjs/assets/1735851/9e3d2d2f-92fc-461f-9ce4-e49eb5140215">

### Codesandbox URL

Please include a codesandbox URL if possible

### Reproducible Steps/Repo

```
Intl.DateTimeFormat.__setDefaultTimeZone('America/Indiana/Indianapolis') // throws
```

## Expected behavior

No exception to be thrown.

## Screenshots

See attached screenshots

## Desktop (please complete the following information):

- OS: Tizen OS (Samsung display)
- Browser: Chrome
- Version 56

## Additional context

Similar to issue #2951

**Comment by longlho** [comment]
ok looks like `America/Indiana/Indianapolis` is only in `all-tz` and not in the `golden` set since it's a deprecated tz. The fix here is to import all tz instead

**Comment by longlho** [comment]
looks like we can technically accept it since it's reversed linked to a golden tz

**Comment by longlho** [comment]
should be fixed by https://github.com/JakeChampion/polyfill-library/pull/1317
