### ISSUE TITLE
intl-messageformat 10.5.5 is changing esm exports

### ISSUE THREAD

**Issue by mathbruyen** [formatjs/formatjs#4255]
It sounds that intl-messageformat release 10.5.5 should not have been categorized as a patch because it actually changed exports of the ESM module. In `intl-messageformat.esm.js` for 10.5.4:

```
var lib_esnext_default = IntlMessageFormat;
export {
  ErrorCode,
  FormatError,
  IntlMessageFormat,
  InvalidValueError,
  InvalidValueTypeError,
  MissingValueError,
  PART_TYPE,
  lib_esnext_default as default,
  formatToParts,
  isFormatXMLElementFn
};
```

And in 10.5.5:

```
var require_lib_esnext = __commonJS({
  "../../../../../../../../execroot/formatjs/bazel-out/darwin_arm64-fastbuild/bin/packages/intl-messageformat/lib_esnext/index.js"(exports) {
    Object.defineProperty(exports, "__esModule", { value: true });
    var tslib_1 = (init_tslib_es6(), __toCommonJS(tslib_es6_exports));
    var core_1 = require_core();
    tslib_1.__exportStar(require_formatters(), exports);
    tslib_1.__exportStar(require_core(), exports);
    tslib_1.__exportStar(require_error2(), exports);
    exports.default = core_1.IntlMessageFormat;
  }
});
export default require_lib_esnext();
```

We now have `does not provide an export named 'IntlMessageFormat'` errors for `import {IntlMessageFormat} from '/libs/intl-messageformat.js';` (which our server resolves as `intl-messageformat.esm.js` without bundling/minification/...).

We were probably not importing it correctly and will switch to default import with `import IntlMessageFormat from '/libs/intl-messageformat.js';` (no brackets to take default export) but you might want to mark the release as something else than a patch or add in release notes something else than `version bump`.

The only change that I found to be potentially relevant is on [tsconfig.json](https://github.com/formatjs/formatjs/compare/intl-messageformat@10.5.4...intl-messageformat@10.5.5#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0) from [commit dfec7e07aeabe22883cf623e76eb7366f763bf9a](https://github.com/formatjs/formatjs/commit/dfec7e07aeabe22883cf623e76eb7366f763bf9a).

**Comment by longlho** [comment]
apology for the breakage, but tbh ESM is a mess, esp w/ TS compiler. Latest version should fix this
