### ISSUE TITLE
Any plans for `Intl.DurationFormat` ?

### ISSUE THREAD

**Issue by khawarizmus** [formatjs/formatjs#4257]
I was looking at the [DurationFormat](https://github.com/formatjs/formatjs/blob/d95d21f1ea10a190f45968e909323e9af6992921/packages/intl-durationformat/index.ts) package. and both the implementation and the docs seems missing.

What's the plan on having an implementation for `DurationFormat` since the proposal is already at Stage 3?

**Comment by longlho** [comment]
nope not yet. I just haven't found the time to do it
