### ISSUE TITLE
intl-localematcher's `match` produces weird results when provided with very different input languages

### ISSUE THREAD

**Issue by Lukas-Kullmann** [formatjs/formatjs#4258]
## Which package?

@formatjs/intl-localematcher

## Describe the bug

Since version 0.5.0, the locale matcher produces weird results when provided with a bunch of different languages.

Example:

```js
match(
  ['de-DE', 'fr'],
  ['en', 'en-US', 'fr-FR'],
  'en-US'
);

// result: 'en'
```

## Expected behavior

The matcher produces a more sensible output if the input (i.e. `requestedLocales`) has more than one element.
In the example above, I would expect the result to be `fr-FR` (which it was in 0.4.2).

I think the problem is that the matcher goes through the requested locales one-by-one and matches them against the available locales. If a match is close enough, it then stops and does not go through the other requested locales to see if there is an even better match.
But also: Why is `en` considered "close enough" for `de-DE`?

**Comment by longlho** [comment]
`0.5.1` should have the fix for this
