### ISSUE TITLE
`shouldPolyfill('fr')` returns incorrect value in `intl-displaynames@6.6.2`

### ISSUE THREAD

**Issue by gzurbach** [formatjs/formatjs#4267]
## Which package?

`intl-displaynames`

## Describe the bug

After upgrading `intl-displaynames` from 6.6.1 to 6.6.2 I cannot use the library with locale `fr`. Same issue arises with 6.6.3 and above.

## To Reproduce

This works as expected:
```js
npm install @formatjs/intl-displaynames@6.6.1

const languageNames = new Intl.DisplayNames(['fr'], { type: 'language' });
```

However, this fails:
```js
npm install @formatjs/intl-displaynames@6.6.2

const languageNames = new Intl.DisplayNames(['fr'], { type: 'language' });
```

Error message:
```
Error: Missing locale data for 
```

**Comment by longlho** [comment]
can u provide a codesandbox?

**Comment by gzurbach** [comment]
Sure thing: https://codesandbox.io/s/javascript-forked-h5d7yz?file=/src/index.js

It seems like the issue comes from this particular call:
```js
import { shouldPolyfill } from "@formatjs/intl-displaynames/should-polyfill";

const foo = shouldPolyfill("fr");
```
With 6.6.1 I am getting `foo = "fr"` which is expected.
With 6.6.2 I am getting `foo = "br"` which is the short code for a regional French language (breton). This is not correct.

Because of this bug my app is not loading `@formatjs/intl-displaynames/locale-data/fr`.

**Comment by gzurbach** [comment]
Long story short, I had to replace:
```js
const foo = shouldPolyfill("fr");
await import(`@formatjs/intl-displaynames/locale-data/${foo}`);
```
by:
```js
const foo = shouldPolyfill("fr");
await import(`@formatjs/intl-displaynames/locale-data/fr`);
```

**Comment by gzurbach** [comment]
As far as I know this issue is not resolved, and should not be closed.

**Comment by longlho** [comment]
kk this issue is due to the list of `supportedLocales` is assumed to be ordered which for polyfills they aren't. Will fix soon.

**Comment by longlho** [comment]
For posterity, the problem is the list of supported locales have both `br` & `fr` but was sorted alphabetically. `fr` - `br` has a match score of 250 but because `fr`'s index was more than 250 below `br`, the penalty kicks in and knock it down to `259`.
