### ISSUE TITLE
`timeZone` not applied when using date skeletons in messages

### ISSUE THREAD

**Issue by amannn** [formatjs/formatjs#4279]
## Which package?

- `@formatjs/intl`

## Describe the bug

When a time zone is provided, it is merged into formats before formatting:

https://github.com/formatjs/formatjs/blob/58d6a7b398d776ca3d2726d72ae1573b65cc3bef/packages/intl/src/message.ts#L15-L29

However, this only applies to format names (e.g. `full`) and not to skeletons (e.g. `::yyyyMdHm`).

### Codesandbox URL

[CodeSandbox](https://codesandbox.io/p/sandbox/react-intl-bug-skeletons-9qcfsy?file=%2Fsrc%2FApp.tsx%3A7%2C31)

### Reproducible Steps/Repo

1. Go to [the CodeSandbox](https://codesandbox.io/p/sandbox/react-intl-bug-skeletons-9qcfsy?file=%2Fsrc%2FApp.tsx%3A7%2C31)
2. Check the rendered output: For named formats as well as `FormattedDate` the output is correct. For the skeleton `::yyyyMdHm` this is not the case.

## Expected behavior

The time zone should be taken into account when using date skeletons.

## Screenshots

<img width="328" alt="image" src="https://github.com/formatjs/formatjs/assets/4038316/2073496d-c26b-44aa-a8b9-9e658e46a3b1">

## Additional context

I think it's a bit odd that the time zone can only be set as part of formats. Shouldn't there be an option to set it as part of `messageFormat.format(...)`?

Thank you very much for your consideration!

**Comment by amannn** [comment]
@longlho any chance this could be fixed in Format.JS? Seems like quite a subtle issue that can break the assumptions of developers.

**Comment by amannn** [comment]
@longlho Do you have a comment on this issue?

**Comment by longlho** [comment]
yeah `skeleton` format is not designed to have any hierarchy or inheritance. It's meant to literally be the format the placeholder's meant to be formatted verbatim.
