### ISSUE TITLE
Remove/replace `ttypescript` recommendation in transformer

### ISSUE THREAD

**Issue by Viicos** [formatjs/formatjs#4280]
## Which package?

`@formatjs/ts-transformer`

## Describe the bug

Documentation [gives instructions](https://formatjs.io/docs/tooling/ts-transformer/#via-ttypescript) for `ttypescript` which is deprecated. It could be replaced with https://github.com/cevek/ttypescript

### Codesandbox URL

Please include a codesandbox URL if possible

**Comment by cungminh2710** [comment]
@Viicos this should be closed now 👍

**Comment by Viicos** [comment]
Thanks!
