### ISSUE TITLE
FormattedNumber output when using percentages has an inappropriate default scale

### ISSUE THREAD

**Issue by samkelleher** [formatjs/formatjs#4283]
## Which package?

`intl-messageformat-parser`

## Describe the bug

An input number of `25` is formatted as `2,500%` instead of `25%` because, for some reason, the scale is defaulting to `100`.  In the examples as per [the spec](https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html), the default scale is `1`. The multiplier would only be added if explicitly defined.  Additionally, adding a `scale/1` directive doesn't do anything.

## See Also
<img width="865" alt="165429690-5b998593-1ff7-457a-97e8-76c9c402a28d" src="https://github.com/formatjs/formatjs/assets/277884/313ecf34-7cc9-4128-8577-7b6cce7ab6bd">

> Why `{value, number, ::percent}` applies `scale/100` by default?
>
> _Originally posted by @ZerdoX-x in https://github.com/formatjs/formatjs/issues/1072#issuecomment-1110475972_

Relates to:
* https://github.com/formatjs/formatjs/issues/2414
* https://github.com/formatjs/formatjs/issues/1072

**Comment by longlho** [comment]
can u provide a codesandbox?

**Comment by cungminh2710** [comment]
in my PR https://github.com/formatjs/formatjs/pull/4315 which introduces a live icu editor, you can see the default scale is 100

<img width="692" alt="image" src="https://github.com/formatjs/formatjs/assets/8063319/cd2fba39-90ce-4e33-9374-b68f92133dad">

**Comment by longlho** [comment]
hmm the default `scale` is basically the ECMA-402 behavior, which conflicts with ICU. This unfortunately is a breaking change so I'm kinda reluctant to fix it.
