### ISSUE TITLE
DurationFormat Polyfill returns the wrong translations (fr-FR duration returned in Arabic, not French)

### ISSUE THREAD

**Issue by aglunndexcom** [formatjs/formatjs#4290]
## Which package?

intl-durationformat package

## Describe the bug

DurationFormat returns the wrong duration strings. In my project, it returns the strings for ar-SA. In the sandbox, it returns the English strings.

## To Reproduce

Run:
`new Intl.DurationFormat("fr-FR", { style: "short" }).format({ hours: 1, minutes: 1 });`

### Codesandbox URL

https://codesandbox.io/p/sandbox/javascript-forked-wcf8p7?file=%2Fsrc%2Findex.js%3A9%2C1

### Reproducible Steps/Repo

1. In any environment with the DurationFormat polyfill, run: 
`new Intl.DurationFormat("fr-FR", { style: "short" }).format({ hours: 1, minutes: 1 });`

2. See:
`'1 س, 1 د'`
or `1 hr, 1 min`

## Expected behavior

Expect to see: `1 h et 1 mn`

That would match the behavior in the Safari browser:
<img width="945" alt=" 2023-12-29 at 3 10 32 PM" src="https://github.com/formatjs/formatjs/assets/65632235/96d0cc7c-028c-445f-930b-2de3857ce8b0">

And the polyfill behavior for other French locales:
`new Intl.DurationFormat("fr-CA", { style: "short" }).format({ hours: 1, minutes: 1 });`
See: `1 h et 1 mn`

## Additional context

In addition to the duration strings for fr-FR being incorrect, I'm curious why there isn't consistent default/error behavior. Really appreciate any help fixing this and am more than happy to answer questions if I can... thank you!

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
is `Intl.DurationFormat` the only polyfill you're loading? I'm not seeing the issue from the codesandbox. This is likely a locale matcher issue though :-/ but try to repro
