### ISSUE TITLE
Intl.supportedValuesOf is undefined when loading polyfill using script tag

### ISSUE THREAD

**Issue by ajdalshov** [formatjs/formatjs#4292]
## Which package?

intl-enumerator

## Describe the bug

Console error:

```
TypeError: Intl.supportedValuesOf is not a function. (In 'Intl.supportedValuesOf("timeZone")', 'Intl.supportedValuesOf' is undefined)
```

Polyfill is included using script tag as described in docs: https://formatjs.io/docs/polyfills/intl-supportedvaluesof

Also tried to include Intl.DateTimeFormat and Intl.NumberFormat (with locales) as polyfills since they are listed as requirements, but Intl.supportedValuesOf still remains undefined.

## To Reproduce

```
<html>
  <head>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=Intl.supportedValuesOf"></script>
  </head>
  <body>
    <script>
      console.log(Intl.supportedValuesOf("timeZone"));
    </script>
  </body>
</html>
```

## Expected behavior

Output array of time zone strings.

## Desktop:

- OS: macOS High Sierra 10.13.6
- Browser: Safari
- Version: 13.1.2

**Comment by longlho** [comment]
This seems to be a doc issue, polyfill.io doesn't support `Intl.supportedValuesOf` yet
