### ISSUE TITLE
`serialize` should not be mandatory when defining a custom formatter

### ISSUE THREAD

**Issue by TommyMoscatelli** [formatjs/formatjs#4293]
## Which package?

cli-lib

## Describe the bug

The [current Formatter interface](https://github.com/formatjs/formatjs/blob/58d6a7b398d776ca3d2726d72ae1573b65cc3bef/packages/cli-lib/src/formatters/index.ts#L12C1-L17) requires to define a custom serialize function.
```
export interface Formatter {
  serialize: SerializeFn
  format: FormatFn
  compile: CompileFn
  compareMessages?: Comparator
}
```
But the [current code](https://github.com/formatjs/formatjs/blob/58d6a7b398d776ca3d2726d72ae1573b65cc3bef/packages/cli-lib/src/extract.ts#L250-L256) is already checking if `serialize` is a function, otherwise it applies the default serialization:
```
if (typeof formatter.serialize === 'function') {
  return formatter.serialize(formatter.format(results as any))
}
return stringify(formatter.format(results as any), {
  space: 2,
  cmp: formatter.compareMessages || undefined,
})
```

## Expected behavior

To apply the default serialization, the formatter interface should be:
```
export interface Formatter {
  serialize?: SerializeFn
  format: FormatFn
  compile: CompileFn
  compareMessages?: Comparator
}
```

**Comment by longlho** [comment]
this should be fixed in latest version
