### ISSUE TITLE
Quoting / Escaping does not work correctly with multiple interpolations

### ISSUE THREAD

**Issue by jarvispact** [formatjs/formatjs#4317]
## Which package?

`react-intl`

## Describe the bug

The documentation about quoting / escaping [here](https://formatjs.io/docs/core-concepts/icu-syntax/#quoting--escaping) states the following: **A single apostrophe escapes one syntax character immediately following it**

So i would expect the following behaviour:

- `Hello {firstname} {lastname}` ✅
    - expected: `Hello Tony Stark` 
    - actual: `Hello Tony Stark`
- `Hello '{firstname} {lastname}` ❌
    - expected: `Hello {firstname} Stark`
    - actual: `Hello {firstname} {lastname}`
 - `Hello '{firstname}' {lastname}` ✅
    - expected: `Hello {firstname} Stark`
    - actual: `Hello {firstname} Stark`

### Codesandbox URL

[Link](https://codesandbox.io/p/sandbox/react-new?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrb2a9500006356h189od7th%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrb2a9500002356h7wriiyl4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrb2a9500003356hmr6iq1w3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrb2a9500005356hprbqv4wg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrb2a9500002356h7wriiyl4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrb2a9500001356hyfl0pyz1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clrb2a9500002356h7wriiyl4%2522%252C%2522activeTabId%2522%253A%2522clrb2a9500001356hyfl0pyz1%2522%257D%252C%2522clrb2a9500005356hprbqv4wg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrb2a9500004356higobvuho%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrb2a9500005356hprbqv4wg%2522%252C%2522activeTabId%2522%253A%2522clrb2a9500004356higobvuho%2522%257D%252C%2522clrb2a9500003356hmr6iq1w3%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrb2a9500003356hmr6iq1w3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

## Screenshots

![image](https://github.com/formatjs/formatjs/assets/38507990/bafd86a5-3a50-4f6f-ba91-66a5f36b242e)

## Desktop (please complete the following information):

- OS: Windows 11
- Browser Chrome
- Version 120.0.6099.201 (Official Build) (64-bit) (cohort: Control)

**Comment by longlho** [comment]
hmm the codesandbox link just points to a new codesandbox. Can u fix that?

**Comment by longlho** [comment]
Based on the example above, the issue seems to be in the docs. Our behavior is consistent with ICU's escaping behavior so I'll update the docs so say so.

![Screenshot 2024-01-15 at 10 47 38 PM](https://github.com/formatjs/formatjs/assets/198255/6b423edc-2a01-4a14-9b0f-351fcf7f1bd8)

**Comment by jarvispact** [comment]
I saw the documentation on the website updated already. Thanks for the clarification.
