### ISSUE TITLE
Importing intl-displaynames polyfill/locale-data dynamically in Next app bloats bundle size

### ISSUE THREAD

**Issue by joeldotsh** [formatjs/formatjs#4339]
Not sure what's happening here, hoping the team can help shed some light.

I have a minimal repro of a starter NextJS app with only react-intl installed. Here's my `_app`:

```javascript
import { useEffect } from "react";
import { IntlProvider } from "react-intl";
import { shouldPolyfill } from "@formatjs/intl-displaynames/should-polyfill";

async function polyfill(locale: string) {
  if (!shouldPolyfill(locale)) {
    return;
  }

  await import("@formatjs/intl-displaynames/polyfill-force");
  await import(`@formatjs/intl-displaynames/locale-data/${locale}`);
}

export default function App({ Component, pageProps }) {
  useEffect(() => {
    polyfill("en");
  }, []);

  return (
    <IntlProvider locale={"en"} messages={{ foo: "bar" }}>
      <Component {...pageProps} />
    </IntlProvider>
  );
}
```

After building the app, if I don't include the `polyfill` function above, I see:

<img width="922" alt="before-polyfill" src="https://github.com/formatjs/formatjs/assets/135879115/b5017cd8-6d28-4fcd-a936-3a1457b79996">

But including it, I see:

<img width="972" alt="after-polyfill" src="https://github.com/formatjs/formatjs/assets/135879115/6f417391-4fa7-4c53-a4ee-97de2ad4fbfc">

The problem is that `_app` is now twice the size, and there's a new chunk of 17.8 kB which appears to be the manifest (which I think has now been split into its own chunk because of how large it's become due to how many different locale-data chunks have been generated).

Here's the bundle analyzer client bundle: [client.html.zip](https://github.com/formatjs/formatjs/files/14089036/client.html.zip)

Specifically, here's the questionable part:

<img width="821" alt="bundle-analyzer" src="https://github.com/formatjs/formatjs/assets/135879115/2f4ce1b7-f0a3-4c2c-87b2-0c6a71cb6331">

So there are 2 problems I'm trying to figure out:

1. Why is _app's size increasing even though the polyfill and locale data are imported dynamically?
2. Is there a recommended way to limit the amount of chunks generated for the locale data to only the supported locales?

I was able to get much more reasonable chunk sizes using an alternative approach with hardcoded locale-data paths:

```javascript
async function polyfill(locale: string) {
  if (!shouldPolyfill(locale)) {
    return;
  }

  await import("@formatjs/intl-displaynames/polyfill-force");
  if (locale === "en") {
    await import(`@formatjs/intl-displaynames/locale-data/en`);
  }
  if (locale === "es") {
    await import(`@formatjs/intl-displaynames/locale-data/es`);
  }
  if (locale === "fr") {
    await import(`@formatjs/intl-displaynames/locale-data/fr`);
  }
  ...
}
```

Which does address issue number 2 above. So if there's no better solution to that, it is what it is. But even still with this approach, `_app`'s size increases by at least 10 kB - I don't understand why it's increasing at all if the polyfill/locale-data imports are dynamic? `shouldPolyfill` is imported statically, but that function/file is quite small and nowhere near the size increase I'm seeing.

I know this possibly goes a bit beyond formatjs, but if anyone has some insight I'd be very grateful.

Thanks!

**Comment by longlho** [comment]
yeah I'm not sure how nextjs handle dynamic import so not really a formatjs problem
