### ISSUE TITLE
Update translation of 'last year' for Swedish locale

### ISSUE THREAD

**Issue by Shan3103** [formatjs/formatjs#4344]
We are using  FormattedRelative from 'react-intl' package in our project and we have a request from clients to update the translation of 'last year' from "I fjol" to "förra året". 

I found that the translations are present in a folder called locale-data in react-intl. Is it possible to update this translation or override it from our end?  I've attached the screenshots for reference. 

<img width="369" alt="Screenshot 2023-10-23 at 1 30 43 PM" src="https://github.com/formatjs/formatjs/assets/139950100/ac5fbd10-06a6-4528-ae98-a00ac604fe31">
 
<img width="448" alt="Screenshot 2024-02-02 at 4 56 09 PM" src="https://github.com/formatjs/formatjs/assets/139950100/36301f68-bb46-4dc1-828c-bc802f07aa75">

**Comment by longlho** [comment]
our data comes from CLDR so you gotta fix it there

**Comment by Shan3103** [comment]
@longlho We recently got to know that this change was done by the CLDR and it should be available in the **v48 CLDR data.** Do you know on what version of "react-intl" package it'll be available for us to consume?

**Comment by longlho** [comment]
We just updated to v48 so u should use latest version
