### ISSUE TITLE
INVALID_TAG when parsing regular HTML tag with attribute

### ISSUE THREAD

**Issue by abejfehr** [formatjs/formatjs#4366]
## Which package?

`@formatjs/icu-messageformat-parser`

## Describe the bug

I get an `INVALID_TAG` error when parsing certain strings

## To Reproduce

```
const icuMessageFormatParser = require('@formatjs/icu-messageformat-parser');

icuMessageFormatParser.parse(`<a></a>`); // [ { type: 8, value: 'a', children: [] } ]

icuMessageFormatParser.parse(`<a b="c"></a>`); // Uncaught [SyntaxError: INVALID_TAG ...
```

I get that `b` isn't necessarily a valid attribute of a literal 'a' tag, but I still don't see why that's an issue 🤔 

### Reproducible Steps/Repo

Just run the above code in a node console

## Expected behavior

I didn't expect any error for this HTML string

**Comment by longlho** [comment]
We don't support HTML. We only support XML tags without any attributes. It's not meant to support full HTML spec
