### ISSUE TITLE
Can't catch error

### ISSUE THREAD

**Issue by wangjiaojiao77** [formatjs/formatjs#4367]
## Which package?

```js
 "@formatjs/intl": "2.2.5"
```

## Describe the bug

```js
import {createIntl, createIntlCache} from '@formatjs/intl'

const cache = createIntlCache()
const intl = createIntl({ locale: 'en-US', messages: {}, }, cache)

try {
      intl.formatNumber(1, {
        style: 'currency',
        currency: 'USDT', // non-standard currency, I need catch error, but @formatjs/intl report the error directly, I can't catch it
        currencyDisplay: 'narrowSymbol',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0,
      })
} catch (error: any) {
    console.log(error)
}
```

## Expected behavior

I can catch error, or you could provide a method I can know if there is an error, thanks.

## Screenshots

<img width="633" alt="image" src="https://github.com/formatjs/formatjs/assets/24351082/af9f0548-33c9-4d30-b799-8d24cd77e7d4">

## Desktop (please complete the following information):

- OS: [Mac]
- Browser [chrome]
- Version [120.0.6099.234]

## Additional context

Please reply as soon as possible, thanks!

**Comment by longlho** [comment]
there's a `onError` param in `createIntl` https://formatjs.io/docs/intl#intlshape
