### ISSUE TITLE
Feature request: allow units greater than `day` in `FormattedRelativeTime` with `updateIntervalInSeconds` to be picked

### ISSUE THREAD

**Issue by bug-brain** [formatjs/formatjs#4368]
For example
```ts
<FormattedRelativeTime value={-14} unit="day" updateIntervalInSeconds={1} />
```
and
```ts
<FormattedRelativeTime value={-14 * 24} unit="hour" updateIntervalInSeconds={10} />
```
should both render "2 weeks ago". Currently the first is an error and the second shows "14 days ago".
If there are not technical limitations it would also be nice if the updates were scheduled even for times over a day. That would be useful for dashboard applications that live in browser tabs that never get closed.

**Comment by longlho** [comment]
PR's welcome :)
