### ISSUE TITLE
@formatjs/intl-locale/polyfill-force TypeError: Error uninitialized locale     at Locale2.getWeekInfo

### ISSUE THREAD

**Issue by smiffp** [formatjs/formatjs#4375]
## Which package?

`@formatjs/intl-locale`

## Describe the bug

I need to polyfill `Intl.Locale` for `getWeekInfo`. Calling `getWeekInfo` throws an the following error: `TypeError: Error uninitialized locale     at Locale2.getWeekInfo`

### Codesandbox URL

[Code sandbox](https://codesandbox.io/p/sandbox/pensive-ace-3xzggj?file=%2Fsrc%2Findex.tsx%3A2%2C41)

### Reproducible Steps/Repo

* import `@formatjs/intl-locale/polyfill-force`
* call `getWeekInfo`

## Expected behavior

I expect to get the week info.

## Screenshots

![Screenshot 2024-03-17 at 1 08 11 PM](https://github.com/formatjs/formatjs/assets/70444396/5a98fc9b-62e9-4f13-bc15-a3bfdd69869e)

## Desktop (please complete the following information):

- OS: macOs Sonoma 14.0
- Browser: Chrome
- Version: 122.0.6261.129 (Official Build) (arm64)

## Smartphone (please complete the following information):

N/A

## Additional context

N/A

**Comment by longlho** [comment]
is the codesandbox public? I got a 404

**Comment by smiffp** [comment]
> is the codesandbox public? I got a 404

I do not use codesandbox frequently 😅. It should be public now.

**Comment by smiffp** [comment]
@longlho Any progress on this?

**Comment by smiffp** [comment]
@longlho Have you had time to check this out?

**Comment by longlho** [comment]
latest version should have the fix for this

**Comment by smiffp** [comment]
I have verified via CodeSandbox that this issue is resolved. Thanks @longlho !
