### ISSUE TITLE
.formatMessage is not working when provided messages has object with `type: 1`

### ISSUE THREAD

**Issue by duc-gp** [formatjs/formatjs#4377]
## Which package?
`react-intl`

## Describe the bug
`intl.formatMessage({id: 'fooKey'})` is working when messages provided by IntlProvider has type: 0 but barKey is not working when type is 1

That is the messages passed to the provider:
```
{
  fooKey: [
    { type: 0, value: "value foo translated", label: "some label" },
  ],
  barKey: [
    { type: 1, value: "value bar translated", label: "some label" },
  ],
}
```
## To Reproduce
- visit https://codesandbox.io/p/sandbox/react-intl-bug-r2t3mm
- you see that one translation with type: 0 is working, the other with type: 1 is not
- see index.js for setup
- see App.js for usage

### Codesandbox URL
https://codesandbox.io/p/sandbox/react-intl-bug-r2t3mm

### Reproducible Steps/Repo
see above To Reproduce

## Expected behavior
the barKey translation should display "value bar translated"

## Desktop (please complete the following information):

- OS: all
- Browser all
- Version 6.6.2, 5.*

**Comment by longlho** [comment]
I'm confused. Are you trying to specify messages in ICU AST form?
`type: 1` is argument, your `value` is just a string

**Comment by duc-gp** [comment]
> I'm confused. Are you trying to specify messages in ICU AST form? `type: 1` is argument, your `value` is just a string

What is this ICU AST form you are talking about? Can you please provide a documentation? Type 0 is working, type 1 not. You can see it in my codepen example

**Comment by longlho** [comment]
https://formatjs.io/docs/react-intl/components#intlprovider

you wanna pass in `Record<string, string>` to `messages` in your Provider

**Comment by duc-gp** [comment]
> https://formatjs.io/docs/react-intl/components#intlprovider
> 
> you wanna pass in `Record<string, string>` to `messages` in your Provider

Thank you but I mean the documentation for this type: 0 and type: 1 thing. Have you checked my codesandbox? If not, please see my codesandbox. There you can see that type: 0 is working but type: 1 is not.

Why is that? Can you provide a documentation for that?

**Comment by longlho** [comment]
The payload form you're passing in is a list of MessageFormatElement chunks. Type 0 is a literal chunk. Type 1 is a argument chunks but those are implementation details.
You should pass in strings instead of passing in map of string to array. Where in the documentation do you get that param shape?

**Comment by duc-gp** [comment]
> The payload form you're passing in is a list of MessageFormatElement chunks. Type 0 is a literal chunk. Type 1 is a argument chunks but those are implementation details. You should pass in strings instead of passing in map of string to array. Where in the documentation do you get that param shape?

Okay I see.. so this is officially not recommended and never was or is that some kind of legacy thing how it was used to be used?

I'm working on legacy code and all the translation were like that passing arrays of objects with that type and value keys :(

**Comment by longlho** [comment]
Those have never been supported AFAIK. The array form is our internal AST format which isn't technically public.

**Comment by duc-gp** [comment]
Ok, then nevermind and thanka a lot for the clarification. This issue can be closed then
