### ISSUE TITLE
`LocaleMatcher` doesn't work on propietary tags

### ISSUE THREAD

**Issue by ImUrX** [formatjs/formatjs#4384]
## Which package?

`intl-localematcher`

## Describe the bug
I was previously using an old version (0.2.32) which properly matched to proprietary tags if they were used but now with the latest version (0.5.4) it doesn't

## To Reproduce
```js
const { match } = require('@formatjs/intl-localematcher')
console.log(match(["en-x-owo"], ["en","en-x-owo"], "en")) // outputs "en" on newer version and "en-x-owo" on the old version
```

## Expected behavior

For it to return the proprietary tag if it's the one being matched

**Comment by ImUrX** [comment]
Why stale issues 😭

**Comment by longlho** [comment]
This behavior is consistent with ICU4J so the fix here is to put `en-x-owo` before `en` in your available locale list
