### ISSUE TITLE
eslint-plugin-formatjs and eslint v9 support

### ISSUE THREAD

**Issue by beaussan** [formatjs/formatjs#4388]
## Which package?

eslint-plugin-formatjs

## Describe the bug

API changes were [announced in september 2023](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/) and eslint 9 is now out since [v9.0.0](https://github.com/eslint/eslint/releases/tag/v9.0.0) since a couple of days ago.

Additionally, there are [some rule structure changes outlined separately](https://eslint.org/blog/2023/12/eslint-v9.0.0-alpha.0-released/#changes-to-how-you-write-rules) that may be worth ensuring are in compliance.

## To Reproduce

1. upgrade to eslint 9
2. test should fail

## Expected behavior

Eslint 9 should work with this plugin

**Comment by lensbart** [comment]
Not stale

**Comment by longlho** [comment]
this likely won't happen until typescript-eslint supports eslint v9

**Comment by lensbart** [comment]
Just a heads-up, `typescript-eslint@rc-v8` supports ESLint v9

**Comment by longlho** [comment]
yeah I saw, just waiting for them to officially release v8

**Comment by michaelfaith** [comment]
> yeah I saw, just waiting for them to officially release v8

Looks like that was release yesterday.

**Comment by cungminh2710** [comment]
Looking at [the changes](https://eslint.org/blog/2023/12/eslint-v9.0.0-alpha.0-released/#changes-to-how-you-write-rules), the rules should support eslint v9 after upgrading `typescript-eslint`

Happy to take a look and upgrade in a couple of weeks

**Comment by michaelfaith** [comment]
I wouldn't mind helping with this,  But a quick clone and install showed that this repo uses bazel, and I always have a hell of a time getting bazel to work well on my personal windows machine.  I don't suppose there's an easier way to run tests in just the eslint package of the repo?

**Comment by cungminh2710** [comment]
The repo use [bazelisk](https://github.com/formatjs/formatjs/blob/main/package.json#L32), it should help running bazel easier. Simply run `yarn test` or `yarn bazel test <target>`

**Comment by michaelfaith** [comment]
Yeah, I tried `pnpm bazel test packages/eslint-plugin-formatjs` and unfortunately that just throws a bunch of build errors.  And I downgraded pnpm to v8 like the `CONTRIBUTING.md` advises.  

```
INFO: Invocation ID: 025a6564-3790-4acd-bd58-201f45e5dd18
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/025a6564-3790-4acd-bd58-201f45e5dd18
INFO: Analyzed target //packages/eslint-plugin-formatjs:eslint-plugin-formatjs (0 packages loaded, 0 targets configured).                                                                                                                                         
INFO: Found 1 target...                                                                                                                                                                                                                                           
ERROR: C:/users/michael/src/formatjs/packages/intl-localematcher/BUILD:26:11: TsValidateOptions packages/intl-localematcher/dist-base.optionsvalid.d.ts failed: (Exit 1): validator.bat failed: error executing command (from target //packages/intl-localematcher:dist-base)
  cd /d C:/users/michael/_bazel_michael/ovtv4cxf/execroot/formatjs
  SET BAZEL_BINDIR=bazel-out/x64_windows-fastbuild/bin
  bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm_typescript\validator.bat tsconfig.json packages/intl-localematcher/dist-base.optionsvalid.d.ts @//packages/intl-localematcher:dist-base packages/intl-localematcher {"allow_js":false,"composite":false,"declaration":true,"declaration_map":false,"emit_declaration_only":false,"incremental":false,"preserve_jsx":false,"resolve_json_module":true,"source_map":false,"ts_build_info_file":""}
# Configuration: 4c09dfc4a5dd3067cae0c350e06d6622a4701de1632f0d114afa13ee300433fd
# Execution platform: @local_config_platform//:host
FATAL: aspect_rules_js[js_binary]: the entry_point '/c/Users/michael/_bazel_michael/ovtv4cxf/execroot/formatjs/bazel-out/x64_windows-fastbuild/bin/external/npm_typescript/ts_project_options_validator.js' not found
ERROR: C:/users/michael/src/formatjs/packages/intl-localematcher/BUILD:26:11: Transpiling & type-checking TypeScript project @//packages/intl-localematcher:dist-esm [tsc -p tsconfig.esm.json] failed: (Exit 1): tsc.bat failed: error executing command (from target //packages/intl-localematcher:dist-esm)
  cd /d C:/users/michael/_bazel_michael/ovtv4cxf/execroot/formatjs
  SET BAZEL_BINDIR=bazel-out/x64_windows-fastbuild/bin
  bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm_typescript\tsc.bat --project tsconfig.esm.json --outDir packages/intl-localematcher/lib --rootDir packages/intl-localematcher --declarationDir packages/intl-localematcher/lib
# Configuration: 4c09dfc4a5dd3067cae0c350e06d6622a4701de1632f0d114afa13ee300433fd
# Execution platform: @local_config_platform//:host
FATAL: aspect_rules_js[js_binary]: the entry_point '/c/Users/michael/_bazel_michael/ovtv4cxf/execroot/formatjs/bazel-out/x64_windows-fastbuild/bin/external/npm_typescript/node_modules/.aspect_rules_js/typescript@5.2.2/node_modules/typescript/bin/tsc' not found
```

Sorry, this is totally off-topics.  I was just wanting to help out.

**Comment by michaelfaith** [comment]
In case anyone else has this issue when trying to contribute, I worked around it by just (temporarily) changing the top-level test script to use `jest` directly.
`"test": "jest packages/eslint-plugin-formatjs/tests --config jest.config.js",`

**Comment by michaelfaith** [comment]
I put up a PR for this, though with it being the first time I've contributed to this repo and my inability to run the full `bazel` setup, I'd greatly appreciate another set of eyes on it, before I publish.  All unit tests are green on the eslint-plugin package.

**Comment by titenis** [comment]
is it possible to add a flat version of eslint v9 configuration?

**Comment by michaelfaith** [comment]
> is it possible to add a flat version of eslint v9 configuration?

Already done: https://github.com/formatjs/formatjs/pull/4706
