### ISSUE TITLE
intl-localematcher: Incorrect locale information provided with '*'

### ISSUE THREAD

**Issue by tkrotoff** [formatjs/formatjs#4405]
## Which package?

@formatjs/intl-localematcher

## Describe the bug

```JS
import { match } from "@formatjs/intl-localematcher"

match(['*'], ['en'], 'en');

// => Throws "RangeError: Incorrect locale information provided"
```

**Comment by longlho** [comment]
'*' is not a valid locale

**Comment by tkrotoff** [comment]
Yes

`new Intl.Locale('*')` => RangeError: Incorrect locale information provided

However

HTTP header Accept-Language can be `*` cf https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language#sect1


So you would expect code like this to work:

```TS
import { match } from "@formatjs/intl-localematcher"

// Derived from HTTP header Accept-Language
// For example using https://github.com/jshttp/negotiator
// const preferredLocales = new Negotiator({ headers }).languages();
const preferredLocales = ['*'];

const availableLangs = ['nl', 'fr', 'de'];
const defaultLang = availableLangs[0];

match(preferredLocales, availableLangs, defaultLang);
// => 'nl' (defaultLang)
```

**Comment by longlho** [comment]
Conceptually your client expects any locale, so there's no need to locale match you can just return any of the locales you support.

**Comment by longlho** [comment]
Again, the locale we expect is Unicode Locale Identifier and * is not a valid locale
