### ISSUE TITLE
Getting singular currency name seems unachievable. 

### ISSUE THREAD

**Issue by sherif-saleh** [formatjs/formatjs#4414]
Using `intl.formatNumber` in this example. 

```
const localizedCurrencyName = intl.formatNumber(0, {
  style: 'currency',
  currency: 'EUR',
  currencyDisplay: 'name',
 });
```

It seems unachievable to get the output as `Euro` rather than`Euros`. I wonder why this isn't something FormattedNumber can take care of out of the box to return a singular currency name instead of the plural in case of 1 and 0 values.

**Comment by longlho** [comment]
you're looking for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames#currency_code_display_names
