### ISSUE TITLE
extract messages with --flatten causes issues when there are multiple plural rules using hash placeholder

### ISSUE THREAD

**Issue by aquark** [formatjs/formatjs#4419]
This is a copy of https://github.com/formatjs/formatjs/issues/4202 which was closed prematurely. This bug still exists and is fairly serious since it results in the wrong content being displayed with no error or warning.

## Which package?
`@formatjs/cli-lib@6.1.3` Tested with `@formatjs/cli-lib@6.2.0` too and issues is still there

## Describe the bug
We have a message that looks like this which contains 2 plural rules and each makes use of the `#` hash placeholder to have the plural value as part of the message

```
<FormattedMessage
  id="reproduction.example"
  defaultMessage="{topicCount, plural, one {# topic} other {# topics}} and {noteCount, plural, one {# note} other {# notes}}"
  description="Show when manager has completed all items for the upcoming 1-1"
  values={{
    topicCount: 1,
    noteCount: 4,
  }}
/>
```

When `flatten` is disable, we get the correct message Here is the extracted message

```
"reproduction.example": {
  "description": "Show when manager has completed all items for the upcoming 1-1",
  "message": "{topicCount, plural, one {# topic} other {# topics}} and {noteCount, plural, one {# note} other {# notes}}"
}
```

And this is what is rendered on the page ![image](https://private-user-images.githubusercontent.com/23372284/270201196-3e16efd0-c18f-46b2-a051-204a23dbda9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzQ0ODQsIm5iZiI6MTcxNTc3NDE4NCwicGF0aCI6Ii8yMzM3MjI4NC8yNzAyMDExOTYtM2UxNmVmZDAtYzE4Zi00NmIyLWEwNTEtMjA0YTIzZGJkYTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDExNTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkM2M1ZGU5Mzg1MDBhM2U1MzU0NGI3ZmViMGQ5NzE4NjkxOGFmODA0ODQ3MDA5NTA1NTk2MjA0Y2Y3NjIwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IwoOeuzkFQURQsbRuZIZi_NKbHuGkmKmYYU1amVrn0k)

When `flateen` is enable, the message is incorrect Here is the extracted message. Note that the extracted message became plural rules nested within plural rules

```
"reproduction.example": {
  "description": "Show when manager has completed all items for the upcoming 1-1",
  "message": "{topicCount,plural,one{{noteCount,plural,one{# topic and # note} other{# topic and # notes}}} other{{noteCount,plural,one{# topics and # note} other{# topics and # notes}}}}"
}
```

And this is what is rendered on the page for that message. It looks like because in the extracted message, as hash placedholer is being used, `#` ended up using the value of `noteCount` as we have plural rule nested in another one ![image](https://private-user-images.githubusercontent.com/23372284/270201383-66fd9861-65e9-4284-9c57-7bea4a6c05d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzQ0ODQsIm5iZiI6MTcxNTc3NDE4NCwicGF0aCI6Ii8yMzM3MjI4NC8yNzAyMDEzODMtNjZmZDk4NjEtNjVlOS00Mjg0LTljNTctN2JlYTRhNmMwNWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDExNTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YTJjMjFiNGIxYTJiMWY0YjkzNGE5ODFhODcyZmZlZTk1MmIwNTVkZWIxOTc3N2FhM2FmMzUyNWUwMTEwY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M82byAAxKl4eRGcSsxOUrWXPQJ7LFtctHfKduhxVmTY)

For your reference, this is how we are using `@formatjs/cli-lib`. This is a small portion of the code that we have as we don't want to share everything for security reasons but should be enough.

```
import { extract } from "@formatjs/cli-lib"

const files = await glob("{src,pages}/**/*.ts*", {
  ignore: ["**/*.d.ts", "**/*.{spec,test}.tsx"],
})
const extracted = await extract(files, {
  format: "smartling",
  flatten: true,
})
```

## To Reproduce
You can reproduce based on the above information

### Codesandbox URL
Please include a codesandbox URL if possible

### Reproducible Steps/Repo
Steps to reproduce the behavior: This is included in the description.

## Expected behavior
We expect after `flatten`, the messages should still work with hash placeholder with multi plural rules

## Screenshots
I have attached screenshots above as it is easier to follow the sequence there

## Desktop (please complete the following information):
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by longlho** [comment]
`@formatjs/cli` throws an error when `--flatten` is used with multiple `plural` or `select`. Since you're using it programmatically maybe you wanna set `throws: true` as well?
This is something we don't plan to support in the near future since multiple plurals are not supported by most TMSes. In your example, `smartling` purposefully also does not support multi-plurals: https://help.smartling.com/hc/en-us/articles/360008030994-ICU-MessageFormat
Multiple plurals yield a LOT of resulting strings since it basically has to explode all the combos of plural forms, take `ru` for example:
1 plural = 4 different sentences
2 plurals = 16 (4^2) different sentences
3 plurals = 64 different sentences

I'd suggest you rewrite your message.
