### ISSUE TITLE
Forced polyfill of de-AT locale for Intl.NumberFormat is using incorrect currency group separator

### ISSUE THREAD

**Issue by briavicenti** [formatjs/formatjs#4422]
## Which package?

@formatjs/intl-numberformat

## Describe the bug

We are using the FormatJS forced polyfills in an number formatting internal library to ensure that our frontend, backend, and testing environments all have consistent behavior when calling Intl.NumberFormat and Intl.DateTimeFormat.

However, `de-AT` is a required locale for us and the force polyfill is resulting in incorrect output according to both real browser behavior and [this CLDR spec](https://unicode-org.atlassian.net/browse/CLDR-9644). 

I can see the correct `currencyGroup` in the generated `de-AT.js` file in my node_modules folder:

<img width="596" alt="image" src="https://github.com/formatjs/formatjs/assets/5926129/131ef2f6-8b2c-405d-b607-a90681db1460">

However, this correct separator doesn't seem to be getting applied as expected and we are seeing the non-currency group separator (a non-breaking space) applied to currency instead.

## To Reproduce

1. `npm add @format-js/intl-numberformat@latest`
2. Add the following imports:
```
import "@formatjs/intl-numberformat/polyfill-force";
import "@formatjs/intl-numberformat/locale-data/de-AT";
```
3. Run the following code, and observe the incorrect output:
```
console.log(
    new Intl.NumberFormat("de-AT", {
      style: "currency",
      currency: "EUR",
    }).format(1234567)
  );
```

### Codesandbox URL

Code sandbox can be found [here](https://codesandbox.io/p/sandbox/wild-snowflake-hp975x?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvvfswp300063b6ldmqvz0y5%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvvfswp300023b6l6h2tecuq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvvfswp300033b6liahlhtu1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvvfswp300053b6libs9qo2z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B59.84217720889772%252C40.15782279110228%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvvfswp300023b6l6h2tecuq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvvfswp300013b6lq2llkvtc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvvfswp300023b6l6h2tecuq%2522%252C%2522activeTabId%2522%253A%2522clvvfswp300013b6lq2llkvtc%2522%257D%252C%2522clvvfswp300053b6libs9qo2z%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvvfswp300043b6ljn0hu8fa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvvfswp300053b6libs9qo2z%2522%252C%2522activeTabId%2522%253A%2522clvvfswp300043b6ljn0hu8fa%2522%257D%252C%2522clvvfswp300033b6liahlhtu1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvvfswp300033b6liahlhtu1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A12.701037443114316%257D). You can comment out the import for the force polyfill and refresh the code sandbox browser to see that this is indeed an issue with that import.

## Expected behavior

Currency formatted for the `de-AT` locale should use periods as a group separator. i.e.:

Current incorrect output: `€ 12 345 678,00`
Expected correct output: `€ 12.345.678,00`

**Comment by briavicenti** [comment]
As an aside we are on a time crunch here to get a fullstack `de-AT` formatter working for an internationalized demo, and so I would absolutely love a workaround if anyone knows one, even if we can't get an actual fix right away!

**Comment by longlho** [comment]
Thanks for reporting. Latest version should have this fix.

**Comment by briavicenti** [comment]
@longlho thanks so much for the prompt fix! Just pulled it in and I can attest that it works as expected now.
