### ISSUE TITLE
`@formatjs/intl-localematcher`: Order of items in `availableLocales` make a difference

### ISSUE THREAD

**Issue by amannn** [formatjs/formatjs#4469]
## Which package?

`@formatjs/intl-localematcher`

## Describe the bug

I'd expect that the second argument that's passed to `match`, the `availableLocales`, should not rely on the order of items in the array.

## To Reproduce

```tsx
const {match} = require("@formatjs/intl-localematcher")

// "de"
console.log(
  match(
    ['de-DE', 'de', 'en-US'],
    ['en', 'de', 'de-DE'],
    'en'
  )
)

// "de-DE"
console.log(
  match(
    ['de-DE', 'de', 'en-US'],
    ['en', 'de-DE', 'de'],
    'en'
  )
)
```

## Expected behavior

Same output, regardless of the input order. Note that this was the case with `@formatjs/intl-localematcher@^0.2.32`.

## Desktop (please complete the following information):

- Environment: Node.js
- Version: 18

**Comment by amannn** [comment]
@longlho Could you help and have a look at this? I think this is a bug.

**Comment by longlho** [comment]
It is actually not a bug. If you look at icu4j it actually takes in a PriorityList but such data structure doesn't exist in JS, so we take in just an ordered list.

**Comment by amannn** [comment]
Hmm I see, thanks for clarifying Long!
