### ISSUE TITLE
Thousands separator does not work well in Spanish

### ISSUE THREAD

**Issue by Borjaapi** [formatjs/formatjs#4477]
## Which package?

react-intl

## Describe the bug

the thousands separator works only when the number has at least four digits

### Codesandbox URL

https://codesandbox.io/p/sandbox/quirky-tristan-5r8fjx

### Reproducible Steps/Repo

if you click on the “EN” button you can see the English thousands separator.
if you click on the “ES” button you can no longer see the thousands separator for Spanish.

## Expected behavior

It should be possible to read "3.566 números"

## Screenshots

![image](https://github.com/user-attachments/assets/569a7a66-5156-47a9-8f99-784fe1864e85)
![image](https://github.com/user-attachments/assets/309d1531-a3b8-4208-bac8-d131f3185e42)

## Desktop (please complete the following information):

- OS: Windows 10
- Browser Edge
- Version  126.0.2592.102 (Official build) (64-bit)

**Comment by longlho** [comment]
this is a native Intl issue, not react-intl
