### ISSUE TITLE
Feature request for eslint-plugin-formatjs: lint rule to require placeholders for numbers in all branches of ICU plurals

### ISSUE THREAD

**Issue by dgoldstein0** [formatjs/formatjs#4478]
Today, a lot of engineers I work with will write ICU strings like `{numThings, plural, one{1 thing}, other{# things}}`.  The lack of a placeholder in the one case `1 thing` causes problems downstream for our localization team, as the translation platform only lets the translators use the placeholders which are present in the source string.  Slavic languages like Russian and Polish, unlike English, reuse the "one" form of the plural for multiple numbers - in Russian, the one form is also used for 21, 31, 41 - etc - so when they are translating the one form, they need the placeholder in the original string.  So the original string should be  `{numThings, plural, one{# thing}, other{# things}}`; other variants like  `{numThings, plural, one{{numThings} thing}, other{{numThings} things}}` would also be acceptable.

A lint rule should be able to catch this, and ideally recommend an autofix.

**Comment by longlho** [comment]
yeah that shouldn't be too bad

**Comment by cungminh2710** [comment]
@longlho I've already have this eslint rule in-house, will push a fix upstream

**Comment by cungminh2710** [comment]
@longlho I've pushed the rule as a pull request. Can you please review that whenever possible? 🙏

**Comment by dgoldstein0** [comment]
I believe there is in progress work for this.  The request still remains
valid either way

**Comment by dgoldstein0** [comment]
solved by 0fa83d47efc04e65acacb6cad8fc585b8882a77f (implemented in #4500)
