### ISSUE TITLE
intl-datetimeformat default timezone is not UTC

### ISSUE THREAD

**Issue by xdoer** [formatjs/formatjs#4480]
## Which package?

package: @formatjs/intl-datetimeformat
version: [6.12.5](https://www.npmjs.com/package/@formatjs/intl-datetimeformat/v/6.12.5)

## Describe the bug

intl-datetimeformat default timezone is not UTC

## To Reproduce
```javascript
import "@formatjs/intl-datetimeformat/polyfill-force";
import "@formatjs/intl-datetimeformat/locale-data/en";

new Intl.DateTimeFormat('en', {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
    hourCycle: "h23"
  }).format(new Date("2024-07-01T00:00:00")
```
It's outout "Jun 30, 16:00"

Remove the polyfill package

It's output "Jul 1, 00:00"

## Desktop (please complete the following information):

- OS: MacOS
- Browser Chrome
- Version 126.0.6478.183 (x86_64)

**Comment by xdoer** [comment]
It's seems use device timezone

**Comment by longlho** [comment]
yeah, that's in the spec https://tc39.es/ecma262/#sec-systemtimezoneidentifier
