### ISSUE TITLE
FormattedMessage incorrectly formats value when single quote (') used directly before closing HTML element.

### ISSUE THREAD

**Issue by adamayres** [formatjs/formatjs#4483]
## Which package?

react-intl

## Describe the bug

When using a text key/value with `FormattedMessage` and the text value contains a quote character right before the ending of an HTML entity, the value is not properly transformed.

### Codesandbox URL

https://stackblitz.com/edit/stackblitz-starters-qcr2oa?file=src%2FApp.tsx

### Reproducible Steps/Repo

1. Create a `messages` object that contains a key/value where the value has a single quote right before the closing 

```js
const messages = {
  fails: "<strong>It breaks if there is a single quote at the end'</strong>"
};
```

2. Create a `FormatedMessage` that references the message id.

```js
<IntlProvider messages={messages}>
  <FormattedMessage
    id="fails"
    values={{
      strong: (chunks) => <strong>{chunks}</strong>,
    }}
  />
</IntlProvider>
```

## Expected behavior

The expected output HTML output would be:

```html
<strong>It breaks if there is a single quote at the end'</strong>;
```

The actual outputted HTML is:

```html
&lt;strong&gt;It breaks if there is a single quote at the end'&lt;/strong&gt;
```

## Desktop (please complete the following information):

- OS: MacOS 14.5
- Browser Chrome
- Version 126

## Additional context

This issue can be workaround by adding an additional character after the single quote and the before the closing of the HTML entity, such as a space.

**Comment by longlho** [comment]
apostrophe is an escape character in ICU, so you need to double escape it with `''`
