### ISSUE TITLE
Feature request – support numeric tags w/ MessageFormat parser

### ISSUE THREAD

**Issue by maisano-patreon** [formatjs/formatjs#4488]
## Context

I'm trying to use `@formatjs/icu-messageformat-parser` to validate and process a number of translations in one of my projects. There are a number of historic strings with numeric tags in them (e.g. `Hello, <0/>`).

When attempting to parse this, I get the `UNMATCHED_CLOSING_TAG` syntax error. It would be great if there was a config option to allow for numerically named tags (e.g. `<0/>`). If I wrote a PR for this, would it likely be accepted?

**Comment by cungminh2710** [comment]
have you tried `ignoreTag: true` yet? https://formatjs.io/docs/intl-messageformat/#intlmessageformat-constructor

**Comment by maisano-patreon** [comment]
@cungminh2710 yes, though I _want_ the tags to be parsed.

**Comment by cungminh2710** [comment]
I don't think `<0 />` is a valid ICU right. WDYT @longlho?

You probably can use `ignoreTag: true` and `<{0} />` if you need to migrate. hope that helps

**Comment by longlho** [comment]
<0/> is valid in neither ICU nor HTML.
