### ISSUE TITLE
IntlShape type mismatch between @formatjs/intl and react-intl

### ISSUE THREAD

**Issue by cungminh2710** [formatjs/formatjs#4491]
## Which package?

@formatjs/intl and react-intl

## Describe the bug

When importing `IntlShape` from `@formatjs/intl`, I saw a type mismatch with the one in `react-intl`

- `react-intl`

![image](https://github.com/user-attachments/assets/dc7257d3-437d-45cb-88b5-68ee9cd5778b)

- `@formatjs/intl`

![image](https://github.com/user-attachments/assets/b8fe442c-96f4-4f6a-920d-847175d56086)

Therefore, when passing the result of `createIntl` from `@formatjs/intl` to `RawIntlProvider` from `react-intl`, typescript 5.5.4 complaining about the type mismatch

![image](https://github.com/user-attachments/assets/3eb84bce-3d24-48e5-8998-ceaadc7c07d1)

## Expected behavior

`IntlShape` type should be interchangable between `@formatjs/intl` and `react-intl`

**Comment by longlho** [comment]
yeah react-intl IntlShape has React-specific stuff and `@formatjs/intl` is React-agnostic
