### ISSUE TITLE
Sharable eslint rule config

### ISSUE THREAD

**Issue by cungminh2710** [formatjs/formatjs#4501]
[ESLint shareable configurations](https://eslint.org/docs/latest/developer-guide/shareable-configs) exist to provide a comprehensive list of rules settings that you can start with.

It would be nice to predefine a sharable configuration for developers to start using the linter quickly with recommended practices.

I created this ticket so that I can remember and work on it later

## Which package?

eslint-plugin-formatjs

**Comment by longlho** [comment]
yeah I'd be down for that

**Comment by cungminh2710** [comment]
will work on this soon

**Comment by michaelfaith** [comment]
@cungminh2710 still thinking of doing this?

**Comment by cungminh2710** [comment]
Hi @michaelfaith , I'd been busy with work and on parental leave now. Didn't have a chance to have a go. 

I was thinking of something like this 

```
rules: {
    "formatjs/no-invalid-icu": "error",
    "formatjs/enforce-description": "error",
    "formatjs/enforce-default-message": ["error", "literal"],
    "formatjs/enforce-placeholders": "error",
    "formatjs/no-id": "error",
    "formatjs/no-emoji": "error",
    "formatjs/no-useless-message": "error",
    "formatjs/no-multiple-plurals": "error",
    "formatjs/no-offset": "error",
    "formatjs/blocklist-elements": [2, ["selectordinal"]],
    "formatjs/no-complex-selectors": "error",
    "formatjs/no-missing-icu-plural-one-placeholders": "error"
  },
```

**Comment by michaelfaith** [comment]
@longlho This isn't compatible with the new flat config format, it would only work with the deprecated legacy/rc configs.  For instance, the `plugin` entry can't be set as a string anymore https://github.com/formatjs/formatjs/commit/a4fc4379700283448350b6982338f169f15d9bba#diff-f106795198066833ac5475a8edd7489760647e7587a4d76812c9120b8595c4c5R70

Happy to help correct it, if you need.

**Comment by HarrisonLeach1** [comment]
@michaelfaith, please do. Our team needs it too 🙏

**Comment by michaelfaith** [comment]
I'll try and have a PR up sometime tomorrow.

**Comment by michaelfaith** [comment]
Issue: https://github.com/formatjs/formatjs/issues/4705
PR: https://github.com/formatjs/formatjs/pull/4706
