### ISSUE TITLE
Incorrect single quote parsing after formatMessage call

### ISSUE THREAD

**Issue by WoodenPC** [formatjs/formatjs#4504]
Since this is a monorepo. Please specify which package this bug report is for.

react-intl: "6.6.8"

Try to call intl.formatMessage for this example  `<a href={href} target='_blank'>some link</a>` and pass values { href: 'google.com' } after formattedMessage call single quote before **>** is dissapeared

### Codesandbox URL

https://codesandbox.io/p/sandbox/react-intl-demo-forked-qlgwyy?file=%2Fsrc%2FApp.js%3A21%2C37

Please include a codesandbox URL if possible

### Reproducible Steps/Repo

open code sandbox
look at formatMesage call in app.jsx

![image](https://github.com/user-attachments/assets/05f11f33-df27-4c09-8795-e7a6bf1f69c7)

## Expected behavior

Single quotes parsed correctly

**Comment by cungminh2710** [comment]
[single quote](https://formatjs.io/docs/core-concepts/icu-syntax#quoting--escaping) is an escaping character, hence the issue you are facing. I recommend `<a href={href} target=''_blank''>some link</a>` for your message

**Comment by longlho** [comment]
you should format this using the rich text API https://formatjs.io/docs/react-intl/components/#rich-text-formatting
