### ISSUE TITLE
If multiple microservices form a system, different microservices are independent and use different React versions, some errors are reported.

### ISSUE THREAD

**Issue by wandou0427** [formatjs/formatjs#4507]
错误信息：
1.app_main.js:50 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
2.Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.[missing argument]
问题分析和处理：
文件packages/react-intl/src/components/injectIntl.tsx的这个变更
https://github.com/formatjs/formatjs/commit/e0dfde6af4210808f08aad32b54707f79f6f88fc是有风险的
应该还原10到24行的代码declare global {
  interface Window {
    __REACT_INTL_CONTEXT__: React.Context<IntlShape> | undefined
  }
}

// This is primarily dealing with packaging systems where multiple copies of react-intl
// might exist
const IntlContext =
  typeof window !== 'undefined'
    ? window.__REACT_INTL_CONTEXT__ ||
      (window.__REACT_INTL_CONTEXT__ = React.createContext<IntlShape>(
        null as any
      ))
    : React.createContext<IntlShape>(null as any)为原来的10到11行代码
// TODO: We should provide initial value here
const IntlContext = React.createContext<IntlShape>(null as any)。
因为如果是微服务架构，不同微服务的React版本可能不一样，而不同版本的React，执行React.createContext(null)得到的结果是不一样的，如果切换微服务，那么在React版本变化，环境改变的情况下，可能无法识别。出现报错。

**Comment by wandou0427** [comment]
https://github.com/formatjs/formatjs/commit/e0dfde6af4210808f08aad32b54707f79f6f88fc问题出现在这个变更

**Comment by wandou0427** [comment]
https://github.com/formatjs/formatjs/commit/e0dfde6af4210808f08aad32b54707f79f6f88fc

**Comment by longlho** [comment]
you can set `window.__REACT_INTL_BYPASS_GLOBAL_CONTEXT__ = true` to bypass this behavior

**Comment by wandou0427** [comment]
> you can set `window.__REACT_INTL_BYPASS_GLOBAL_CONTEXT__ = true` to bypass this behavior

ok，thanks。

**Comment by wandou0427** [comment]
> you can set `window.__REACT_INTL_BYPASS_GLOBAL_CONTEXT__ = true` to bypass this behavior

Sorry, I suggest that global sharing is not used by default. If you want to use global sharing, set it to true because setting global sharing is only an optimization point. We need to ensure that no error is reported even if no special settings are performed.
