### ISSUE TITLE
Performance issues with `formatDateParts`

### ISSUE THREAD

**Issue by Fox32** [formatjs/formatjs#4510]
## Which package?

`@formatjs/intl-datetimeformat`

## Describe the bug

While debugging a performance issue in our react-native app I noticed that resolving the locale in `intl-localematcher` is quite a slow operation. This is a know issue and noted in other tickets here https://github.com/formatjs/formatjs/issues/4276. In general it's recommended to cache new intl.*format instances and re-use them. 

My problem is that in `DateTimeFormat.formatDateParts`, or more precise in `FormatDateTimePattern`, there are two to three new instances of `Intl.NumberFormat` created which are not cached. To improve performance, I think these should be cached.

### Codesandbox URL

See code in https://github.com/formatjs/formatjs/blob/main/packages/intl-datetimeformat/src/abstract/FormatDateTimePattern.ts#L83-L95

**Comment by longlho** [comment]
can you cache `DateTimeFormat` when you initialize it?

**Comment by Fox32** [comment]
Yes, I'm already caching the `DateTimeFormat`, but it creates additional `NumberFormat` instances internally on every call.

I can prepare a PR next week.

**Comment by longlho** [comment]
fixed
