### ISSUE TITLE
Babel plugin / ts transformer break build when codebase includes a symbol named `$t`

### ISSUE THREAD

**Issue by kprist** [formatjs/formatjs#4511]
## Which package?

`babel-plugin-formatjs` and `@formatjs/ts-transformer`

## Describe the bug

When using either of the two packages in a pipeline, while also using an unrelated function named `$t` in your project's codebase, an error occurs with a message similar to

```
[React Intl] Message Descriptors require an `id` or `defaultMessage`.
```

### Reproducible Steps/Repo

1. Setup a react project using either of the two packages
2. Include a file in the project codebase that uses `$t` as a function name
3. Build the project
4. See errors ``[React Intl] Message Descriptors require an `id` or `defaultMessage`.``

## Expected behavior

I should have the option to disable the `$t` shorthand. Alternatively, an option to specify any files that the plugin should ignore.

## Additional context

This occurred originally in a project using the babel plugin that was also importing a compiled library that happened to use the `$t` alias for `React.useRef`. Renaming the alias in the external library removed all errors.

**Comment by longlho** [comment]
hmm why are you running babel on transpiled code?

**Comment by kprist** [comment]
@longlho well that happened by mistake, the library in question was a dependency, and it and the project using it was using `react-intl`, so I was using the babel plugin while developing (it's actually a vite project). I only realized it was processing the transpiled code after bumping into this issue.

I think this issue is more of a feature request maybe, it's just that I think that enabling this shorthand by default without an option to at least disable it is not ideal.

**Comment by robmosca** [comment]
@longlho: in an ejected react application the webpack config from react-config applies by default the babel-loader to transpiled code. See it [here](https://github.com/facebook/create-react-app/blob/dd420a6d25d037decd7b81175626dfca817437ff/packages/react-scripts/config/webpack.config.js#L466-L504)
We also experienced the same problem.

**Comment by robmosca** [comment]
We experienced the same problem. In the webpack config, the rule applying babel-loader had an `exclude: /node_modules/` condition, but packages linked internally in our monorepo by pnpm are resolved to their full path, which does not include `node_modules`, therefore we ended up applying babel to transpiled code. It might end up being more common than expected, and the `$t` can easily collide with other functions...
