### ISSUE TITLE
`Intl.NumberFormat.prototype.formatRange()` implementation differs from real browsers when using currencies

### ISSUE THREAD

**Issue by chrisvltn** [formatjs/formatjs#4521]
## Which package?

`@formatjs/intl-numberformat`

## Describe the bug

When formatting currency ranges, the result differs from what browser returns and looks weird for people reading localized text.

## To Reproduce

```js
const nf = new Intl.NumberFormat('es', {
  style: 'currency',
  currency: 'EUR',
  maximumFractionDigits: 0,
});

console.log(nf.formatRange(10, 100)); // Chrome: 10-100 €. Polyfill: 10 €-100 €
```

## Expected behavior

Display the range as `10-100 €` and also respect the other options passed in `Intl.NumberFormat`.

## Desktop (please complete the following information):

- OS: maxOS
- Browser: Chrome and Firefox
- Version: Firefox 129.0.2 and Chrome 128.0.6613.120

## Additional context

`Intl.NumberFormat.formatRange` specification: https://tc39.es/ecma402/#sec-intl.numberformat.prototype.formatrange

**Comment by longlho** [comment]
related issue in the spec as well: https://github.com/tc39/ecma402/issues/935
I pushed a fix that made it closer to web reality
