### ISSUE TITLE
DurationFormat.format is very slow and blocking JS thread

### ISSUE THREAD

**Issue by AlixH** [formatjs/formatjs#4522]
## Which package?

    "@formatjs/intl-durationformat": "^0.2.4",

## Describe the bug

I am using formatJS in my React Native app. I am importing several polyfills for each locales as described here: https://formatjs.io/docs/polyfills/intl-durationformat

When using DurationFormat.format method, my UI is blocked for few seconds, preventing user from navigating away from the screen

### Reproducible Steps/Repo

    import {DurationFormat} from '@formatjs/intl-durationformat';
    const formatter =  new DurationFormat(I18n.locale, options);
    return formatter.format({seconds: 232324453463465});

## Expected behavior

I don't expect this method to take so much time and resources

## Desktop (please complete the following information):

- OS: MacOS Sonoma 14.1
- Browser Chrome

## Smartphone (please complete the following information):

- Device: Samsung S22
- OS: Android 14

**Comment by AlixH** [comment]
It occurs that it's not the call to format, but the initilalization of the DurationFormat instance that takes time

**Comment by AlixH** [comment]
Also, why this constructor is not callable from Intl namespace object ? How to cache it ?

**Comment by longlho** [comment]
You can use `https://formatjs.io/docs/intl#createintl` and initiate `@formatjs/intl-durationformat` as the polyfill instead of using it directly

**Comment by AlixH** [comment]
Could clarify what you mean by 'initiate as the polyfill' ? Duration is not part of the core package unfortunately.

**Comment by longlho** [comment]
I mean https://formatjs.io/docs/polyfills/intl-durationformat#simple

**Comment by AlixH** [comment]
I still can't figure a out a way of having it working smoothly. Just removing the durations from my app increase performances hugely.
