### ISSUE TITLE
parserServices error in recent eslint v9 changes

### ISSUE THREAD

**Issue by wuz** [formatjs/formatjs#4524]
## Which package?

eslint-plugin-formatjs

## Describe the bug

Getting this error when using typescript-eslint v8.5.0 and eslint v9. 

```error
TypeError: Error while loading rule 'formatjs/enforce-description': Cannot read properties of undefined (reading 'defineTemplateBodyVisitor')
```

It appears like `getParserServices` can return undefined at times, which I think is happening from the [`return context.sourceCode.parserServices`](https://github.com/formatjs/formatjs/blob/main/packages/eslint-plugin-formatjs/context-compat.ts#L12C1-L12C43) line in context-compat.ts. I can't find any documentation of that existing from eslint.

## To Reproduce

I'm pretty sure this happens when using eslint v9 with just plain JS linting. I can try to get a reproducible CodeSandbox tomorrow.

**Comment by longlho** [comment]
yeah a repro would be great. Thanks!

**Comment by trikadin** [comment]
I've got the same error, but with a different rule:
```
TypeError: Error while loading rule 'formatjs/enforce-default-message': Cannot read properties of undefined (reading 'defineTemplateBodyVisitor')
```
I'll try to make a repro, but it's kinda difficult to catch...

**Comment by michaelfaith** [comment]
Were you able to create a repro?  Also, what parser are you using?
