### ISSUE TITLE
Difference between of understanding between "Rich Text support" documentation and real life

### ISSUE THREAD

**Issue by astik** [formatjs/formatjs#4527]
## Which package?

Probably not a bug but something related to documentation

## Describe the bug

In https://formatjs.io/docs/intl-messageformat/#rich-text-support it is stated: `Any attributes on the HTML tag are also ignored`.
Currently, when having markup in translations:
- translations are processed without any attribute in markup
- translations are not processed with any attribute in markup

### Codesandbox URL

https://codesandbox.io/p/sandbox/react-intl-demo-forked-xxmld2

![Capture d’écran 2024-09-12 à 11 42 39](https://github.com/user-attachments/assets/91ad4d8b-0189-4ee2-bcfe-257a6fc7cd05)
![Capture d’écran 2024-09-12 à 11 42 41](https://github.com/user-attachments/assets/685a3e43-b9e7-4254-9f4f-ea7e8a135357)

### Reproducible Steps/Repo

Define markup in translation messages, with and without attribute.

## Expected behavior

I would expect: 
```
<FormattedMessage
  id="test"
  defaultMessage="bla <span>bla</span> blo"
  values={{
    span: (...chunks) => <strong>{chunks}</strong>,
  }}
/>
```

To have the same behavior as:
```
<FormattedMessage
  id="test"
  defaultMessage="bla <span data-test='woot'>bla</span> blo"
  values={{
    span: (...chunks) => <strong>{chunks}</strong>,
  }}
/>```

## Desktop (please complete the following information):

- OS: [e.g. iOS] macOS 14.6.1 (23G93)
- Browser [e.g. chrome, safari] Chrome Version 128.0.6613.114 (Build officiel) (arm64)
- Version [e.g. 22] "react-intl": "6.6.8",

**Comment by astik** [comment]
Still relevant though from my POV :)

**Comment by longlho** [comment]
We don't parse attributes in tag and treat them as just literal.

**Comment by astik** [comment]
As i said in the demo above, i'm not expected attribute to be parsed but i would expect them to be ignored in order for the markup to be processed with or without attribute.
Right now:
- if you don't set any attribute -> markup is processed perfectly
- if you add any attribute -> the whole string is processed as literal without fallback on "markup without attribute"

The documentation is not clear on this point if it is expected like this -> documentation should reflect that
If the fallback is not the one expected, then we've got an issue in the processing -> thus issue should be kept open to track the problem
