### ISSUE TITLE
formatjs/enforce-default-message does not honor /* eslint-disable */

### ISSUE THREAD

**Issue by dkreft-termly** [formatjs/formatjs#4532]
## Which package?

[eslint-plugin-formatjs](https://www.npmjs.com/package/eslint-plugin-formatjs)

## Describe the bug

Wrapping a rule-violating block of JS code with `/* eslint-disable */` or `/* eslint-disable formatjs/enforce-default-message */` does not work—errors are still reported.

### Reproducible Steps/Repo

1. Use the following eslint config file:

```
// File: .eslintrc.TEST.js

module.exports = {
  plugins: [
    'formatjs',
  ],
  rules: {
    'formatjs/enforce-default-message': ['error', 'literal'],
  },
}
```

2. Create the following file:

```js
// File: locale.js

import { defineMessages } from 'react-intl'


export default defineMessages({
  /* eslint-disable */
  pluralizedWebsites: {
    id: 'blah-blah.foo',
    one: 'website',
    other: 'websites',
  },
  /* eslint-enable */
})
```

(Note: this is intended to be used with `<FormattedPlural />`, if you're wondering.)

3. Run eslint on the file:

```js
❯ yarn eslint -c ./.eslintrc.TEST.js locale.js

[redacted]/locale.js
  4:16  error  `defaultMessage` has to be specified in message descriptor  formatjs/enforce-default-message

✖ 1 problem (1 error, 0 warnings)
```

## Expected behavior

No errors or warnings should be generated for disabled lines/blocks.

## Desktop (please complete the following information):

- OS: `Darwin mclappy 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6031 arm64` (MacOS Sonoma 14.6.1 on an M3 Max chip)
- Browser N/A

## Additional context

* Eslint version: `8.53.0` (I'm not ready to move up to v9)
* Yarn version : `4.3.1`
* Node version: `20.1.0`
* `react-intl` version: `5.25.1`

**Comment by longlho** [comment]
this honestly looks like a eslint issue rather than our plugin. There's also no repro link.

**Comment by dkreft-termly** [comment]
@longlho if it were an eslint issue, wouldn't *all* of my `eslint-ignore` and `eslint-ignore-next-line` directives fail?

I've given you all you need to repro. The bug report template indicates that a link to a Code Sandbox is optional:
<img width="351" alt="image" src="https://github.com/user-attachments/assets/3ac8f8da-871a-479f-ac52-c9270192adbd">

**Comment by pablobirukov** [comment]
Not a bug.

To suppress an error, eslint directive is to be a line above the erroring node:
```ts
// eslint-disable-next-line formatjs/enforce-default-message
  default export defineMessages({
    pluralizedWebsites: {
      id: 'blah-blah.foo',
      one: 'website',
      other: 'websites',
    },
  });
```

**Comment by dkreft-termly** [comment]
@pablobirukov Thank you.
