### ISSUE TITLE
react-intl typescript error with formatMessage type inference

### ISSUE THREAD

**Issue by SudoCat** [formatjs/formatjs#4538]
## Which package?

react-intl

## Describe the bug

Type inference does not work correctly when passing a `FormatXMLElementFn` in the values of formatMessage. 

## To Reproduce

```
import { useIntl } from 'react-intl';
function Test() {
  const intl = useIntl();

  return intl.formatMessage({
      id: 'app.greeting',
      defaultMessage: 'Hello, <link>{name}</link>!',
      description: 'Greeting to welcome the user to the app',
    }, {
    name: 'example',
    link: (children) => <a href="/test">{children}</a>,
  });
}

```

### Codesandbox URL

[Please include a codesandbox URL if possible](https://codesandbox.io/p/sandbox/gzzvg4)

### Reproducible Steps/Repo

Error instantly present in code editor.

## Expected behavior

The formatMessage function should infer the type from the usage. 

## Screenshots

<img width="1066" alt="image" src="https://github.com/user-attachments/assets/e2543710-c8f3-4f28-abba-6d76e1726b75">

## Additional context

The issue is caused by the non-generic overloads available for formatMessage. I have not tested, but presume the same issues occur for $t and formatList as well, as these also have both a generic and non-generic version that support ReactNode.

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/8a045e79-0b35-4bd8-9cdb-08f9d2c94b27">

If the non-generic formatMessage method is commented out, the error is resolved.

If the user explicitly provides type arguments, the error is resolved.

**Comment by benjamindulau** [comment]
Same issue since I upgraded to react-intl@6.7.0
