### ISSUE TITLE
intl-messageformat: 10.6.0 is untagged

### ISSUE THREAD

**Issue by mook-as** [formatjs/formatjs#4552]
## Which package?

intl-messageformat

## Describe the bug

Version 10.6.0 appears to have been pushed to npm, but there is no release / tag for it on GitHub.

### URL

https://www.npmjs.com/package/intl-messageformat/v/10.6.0

https://github.com/formatjs/formatjs/releases?q=intl-messageformat&expanded=true

https://github.com/formatjs/formatjs/releases/tag/intl-messageformat%4010.6.0

### Reproducible Steps/Repo

1. Go to the first URL and note that intl-messageformat 10.6.0 has been published on npm.
2. Go to the second URL and note that there is no corresponding release on GitHub.
3. Go to the third URL and confirm that there is no git tag listed on GitHub.

## Expected behavior

Ideally, there should be a release on GitHub (for changelogs). Failing that, a tag would be good to know what sources went into the release.

## Desktop (please complete the following information):

- OS: macOS
- Browser Firefox
- Version 131.0.2

## Smartphone (please complete the following information):

N/A

## Additional context

Sorry to abuse the issue report form, this is more about confirming process than an actual issue with the code… just making sure that's a real release, for supply chain silliness reasons. Thanks!

(I blame dependabot for triggering bumps)

**Comment by longlho** [comment]
yeah something broke in our tooling so needed to just get this out. You can take a look at CHANGELOG.md for changelogs as well.

**Comment by longlho** [comment]
kk we sorted this out so published a newer one. Closing this
