### ISSUE TITLE
DOCS: FormattedRelativeTime - doesnt appear to be working?

### ISSUE THREAD

**Issue by christopherreay** [formatjs/formatjs#4573]
## Which package?
no idea

## Describe the bug
units of FormattedRelativeTime do not change when like the value is "100324092304983098" days, I guess its supposed to change into "years" or "decades" or something

## To Reproduce
on this docs page
https://formatjs.io/docs/react-intl/components

### Codesandbox URL
n/a

### Reproducible Steps/Repo
I changed the number, the units did not change

## Expected behavior

the units change

## Screenshots

![Screenshot from 2024-10-13 17-11-54](https://github.com/user-attachments/assets/caab19bd-fa24-4d60-bcbd-136a390b8101)

## Desktop (please complete the following information):
brave-beta latest on linux

**Comment by longlho** [comment]
Nope you have to calculate that yourself. We only format the result.

**Comment by christopherreay** [comment]
I'm not sure we are talking about the same thing.

so... what is being formatted if i give it a number in minutes and it
outputs minutes regardless of how big the number is?

(I'm not talking in an accusatory way, I've been a developer for 30 years,
I'm just curious to understand because i really don't!)

**Comment by longlho** [comment]
Yes that's correct. Auto conversion is very editorial and ambiguous, some people consider Jan -> Dec last year and some consider last month. You have to give it the unit you want to format.

**Comment by christopherreay** [comment]
Cheers for your time :)

Be prepared to have your predictions come true
