### ISSUE TITLE
`getTextInfo().direction` is returning an incorrect value for maximized locales

### ISSUE THREAD

**Issue by SimpleCreations** [formatjs/formatjs#4575]
## Which package?

`@formatjs/intl-locale`

## Describe the bug

`getTextInfo().direction` is returning `"ltr"` instead of `"rtl"` for some locales that have been `maximize()`d.

I believe this is because the polyfill uses the internal locale code to look up values for `direction`, and after calling `maximize()` this internal locale code becomes different and causes a miss and a fallback to `ltr`.
## To Reproduce

```
import '@formatjs/intl-getcanonicallocales/polyfill-force'
import '@formatjs/intl-locale/polyfill-force'

// `"rtl"`
console.log(new Intl.Locale('ar-SA').getTextInfo().direction);

// Oops! `"ltr"`
console.log(new Intl.Locale('ar-SA').maximize().getTextInfo().direction);
```

**Comment by longlho** [comment]
do you have a repro link?

**Comment by SimpleCreations** [comment]
Here you go: https://codepen.io/befv/pen/LYweLQw?editors=0011
