### ISSUE TITLE
Certificate error when accessing online documentation website

### ISSUE THREAD

**Issue by Olzindel** [formatjs/formatjs#4588]
## Which package?

website

## Describe the bug

Online documentation on https://formatjs.io/docs/react-intl/ seems to be unaccessible because of a certificate error.

### Reproducible Steps/Repo

1. Go to https://formatjs.io/docs/react-intl/

## Desktop (please complete the following information):

- OS: iOS
- Browser: firefox

**Comment by project0** [comment]
Same, it looks like there was a takeover for scam or even worse a hacking attempt to me: 
![Screenshot 2024-10-18 at 15-09-58 Did Not Connect Potential Security Issue](https://github.com/user-attachments/assets/5c0ea7da-a86c-4054-b1bb-9d22d352b50e)

**Comment by longlho** [comment]
yeah there are currently some cert issues that Yahoo IT is figuring out.
cc @redonkulus

**Comment by longlho** [comment]
you guys can go to https://formatjs.github.io for now

**Comment by longlho** [comment]
looks like this's been resolved :)
