### ISSUE TITLE
@formatjs/intl formatDisplayName does not work

### ISSUE THREAD

**Issue by AlixH** [formatjs/formatjs#4642]
## Which package?

@formatjs/intl

## Describe the bug

When using formatDisplayNames from this package, I get:

<img src="https://github.com/user-attachments/assets/a035c65a-2282-4d72-814e-325a05ea7a25" width="350" />

## To Reproduce
File I18nManager.ts
```ts
import {createIntl, createIntlCache} from '@formatjs/intl';
const intlCache = createIntlCache();
const currentLocaleIntl = createIntl(
  {
    locale: 'en',
    messages: {},
  },
  intlCache
);

export default class I18nManager {

  public static formatCountryName(countryName: string): string {
    return  currentLocaleIntl.formatDisplayName(countryName, {type: 'region'});
  }
}
```

### Reproducible Steps/Repo

```ts
I18nManager.formatCountryName('AD')
```

## Expected behavior

I expect the method to be able to format a country name without error

## Smartphone (please complete the following information):

- Device: Google Pixel 6 emulator
- OS: Android

## Note:

It is working if I use directly Intl.DisplayNames (and import the polyfill ofc), e.g : 
```ts
export default class I18nManager {

  public static formatCountryName(countryName: string): string {
    return new Intl.DisplayNames(I18n.locale, {type: 'region'}).of(countryName);
  }
}
```

**Comment by longlho** [comment]
React-intl uses native API so looks like you need the polyfill.

**Comment by AlixH** [comment]
> React-intl uses native API so looks like you need the polyfill.

I am not using react-intl. the core intl method does not work even with the polyfill

**Comment by longlho** [comment]
Do you have a repro link? How are you loading the polyfill?

**Comment by AlixH** [comment]
I am loading the polyfill in the index.js with -force
```js
require('@formatjs/intl-displaynames/polyfill-force');
require('@formatjs/intl-displaynames/locale-data/en.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT
require('@formatjs/intl-displaynames/locale-data/it.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT
require('@formatjs/intl-displaynames/locale-data/es.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT
require('@formatjs/intl-displaynames/locale-data/pt.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT
require('@formatjs/intl-displaynames/locale-data/de.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT
require('@formatjs/intl-displaynames/locale-data/fr.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT
require('@formatjs/intl-displaynames/locale-data/cs.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT
```

**Comment by longlho** [comment]
Do you have a repro link?

**Comment by AlixH** [comment]
here https://codesandbox.io/p/sandbox/typescript-playground-export-forked-nhq4st
But it works. Thing is, I am having the issue on Android, not a browser

**Comment by longlho** [comment]
Looks like your polyfill is loaded after createIntl is called.

**Comment by AlixH** [comment]
> Looks like your polyfill is loaded after createIntl is called.

Very good catch ! it works now 😇  . But can you explain why the polyfill of int-displaynames is required for using method of intl core package ?

**Comment by longlho** [comment]
It uses native Intl APIs as I mentioned. Android webview doesn't ship with any Intl APIs so the polyfill polyfills it.

**Comment by AlixH** [comment]
> It uses native Intl APIs as I mentioned. Android webview doesn't ship with any Intl APIs so the polyfill polyfills it.

I see, (weirdly I can use formatDate without loading datetime-format)
Thanks !
