### ISSUE TITLE
@formatjs/cli-lib v6.5.2 bumped chalk to 5, an ESM-only package

### ISSUE THREAD

**Issue by zburke** [formatjs/formatjs#4647]
## Which package?

@formatjs/cli-lib

## Describe the bug

041b324503fcc4dd9ddbd3b9783c9d5d2a1c0311 bumped chalk from `^4.0.0` to `5` but [chalk v5 is ESM-only](https://github.com/chalk/chalk/releases/tag/v5.0.0). Thus, a non-ESM package with a dependency like `"@formatjs/cli-lib": "^6"`, which ran cleanly up through v6.5.1, fails when v6.5.2 is pulled in:
```
/Users/zburke/projects/folio-org/stripes-core/node_modules/@formatjs/cli-lib/src/console_utils.js:10
const chalk_1 = require("chalk");
                ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/zburke/projects/folio-org/stripes-core/node_modules/@formatjs/cli-lib/node_modules/chalk/source/index.js from /Users/zburke/projects/folio-org/stripes-core/node_modules/@formatjs/cli-lib/src/console_utils.js not supported.
Instead change the require of index.js in /Users/zburke/projects/folio-org/stripes-core/node_modules/@formatjs/cli-lib/src/console_utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/zburke/projects/folio-org/stripes-core/node_modules/@formatjs/cli-lib/src/console_utils.js:10:17) {
  code: 'ERR_REQUIRE_ESM'
}
```
### Codesandbox URL

https://codesandbox.io/p/devbox/lively-morning-v5zhds

### Reproducible Steps/Repo
```
// package.json
  "dependencies": {
    "@formatjs/cli-lib": "^6"
  }
// index.js
const foo = require('@formatjs/cli-lib');
console.log('foo');
```

## Expected behavior

v6.5.2 is usable in the same manner as v6.5.1 was. 

## Desktop (please complete the following information):
```
$ uname -a
Darwin EIS-208ML85 23.6.0 Darwin Kernel Version 23.6.0: Wed Jul 31 20:48:44 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_X86_64 x86_64
```
```
$ uname -a
Linux v5zhds 6.1.43 #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023 x86_64 GNU/Linux
```

**Comment by longlho** [comment]
fixed in https://github.com/formatjs/formatjs/commit/5fb690f62e1a42b0626b506a9c756b6c624a394e, latest version should have the fix

**Comment by zburke** [comment]
Gonna have to change your id from longlho to wacokid. That was fast! Thank you!
