### ISSUE TITLE
`@formatjs/intl-numberformat` - `roundingMode: "trunc"` doesn't work

### ISSUE THREAD

**Issue by mozzius** [formatjs/formatjs#4678]
## Which package?

`@formatjs/intl-numberformat` 

## Describe the bug

When using the NumberFormat polyfill in React Native, Intl.NumberFormat always rounds numbers up, even when a `roundingMode` is specified.

This is what we want to use:

```
Intl.NumberFormat('en-US', {
    notation: 'compact',
    maximumFractionDigits: 1,
    roundingMode: 'trunc',
  }).format(1050)
// should be 1k, but is 1.1k when using the polyfill
```

### GitHub URL

Sorry, React Native project! Configured for Expo Go, so should be easy enough to run

https://github.com/mozzius/numberformat-roundingmode-repro

### Reproducible Steps/Repo

Steps to reproduce the behaviour:

1. Observe that the number is 1.1k and thus is not rounded correctly

## Expected behaviour

Should be rounded to 1k

## Screenshots

<img src="https://github.com/user-attachments/assets/c13fb69b-90d7-46c9-a814-d5d31cb6c234" width=200>

## Desktop (please complete the following information):

- OS: n/a
- Browser n/a
- Version n/a

## Smartphone (please complete the following information):

- Device: iPhone 14
- OS: 18.1
- Browser n/a
- Version n/a

## Additional context

none

**Comment by GPHemsley** [comment]
Based on this and #4359 and possibly #4717, it looks like NumberFormat v3 support (started in #3853) was never finished.

Spec changes:
* https://github.com/tc39/proposal-intl-numberformat-v3?tab=readme-ov-file#rounding-modes-ecma-402-419
* tc39/ecma402#753
* https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/diff.html
* https://github.com/tc39/ecma402/commit/42571609c588395600c8a9a585e38a410266c06f#diff-97d3056f53cd33b921cf1453a74674051e3752e742587ccd7ee35ff658390155

In particular, support is missing for `RoundingMode`, `RoundingIncrement`, and `TrailingZeroDisplay`.

So in this case, behavior is just defaulting to the originally-only rounding mode of `halfExpand`.

**Comment by longlho** [comment]
Latest version should be ES2025 compliant. https://github.com/formatjs/formatjs/blob/main/packages/intl-numberformat/tests/misc.test.ts#L343 should have a test for this

**Comment by vovkasm** [comment]
Hey folks, I apologize for bringing this up, but given that an external library dependency has been added, I'm wondering if any additional analysis was conducted regarding the impact [this change](https://github.com/formatjs/formatjs/commit/50bd498a45952ad69e62d19a55b19846f33d91e9) may have on application performance and bundle size?

**Comment by longlho** [comment]
yeah [`decimal.js`](https://www.npmjs.com/package/decimal.js) is quite popular and low level to deal w/ floating point issue. While its size isn't necessarily small (https://bundlephobia.com/package/decimal.js@10.4.3), it doesn't make sense for us to basically re-implement its functionalities.
