### ISSUE TITLE
@formatjs/swc-plugin-experimental does not support Rich Text Formatting

### ISSUE THREAD

**Issue by JSMD-maintainers** [formatjs/formatjs#4683]
## Which package?

**@formatjs/swc-plugin-experimental@0.6.1**

## Describe the bug

We migrated our application using from **babel-plugin-formatjs** plugin to **@formatjs/swc-plugin-experimental** and had `FormattedMessage` components like the following documentation described in place: https://formatjs.github.io/docs/react-intl/components#rich-text-formatting

Our example
````js
                                <FormattedMessage
                                    defaultMessage="<b>Es gab einen Fehler beim Abrufen der Verfügbarkeitsdaten vom Server</b>. Bitte versuchen Sie es später noch einmal."
                                    values={{
                                        b: chunks => <strong>{chunks}</strong>,
                                    }}
                                />
````

However when using swc as transpiler with the @formatjs/swc-plugin-experimental I get the following error:

````
ERROR in ./src/client/components/App/App.tsx
  × Module build failed:
  ╰─▶   ×   ⚠
        │   │                     [React Intl] Message failed to parse.
        │   │                     See: https://formatjs.io/docs/core-concepts/icu-syntax
        │   │                     \n {:#?}
        │   │
        │   × SyntaxError: UNCLOSED_TAG
        │
      
 @ ./src/client/components/StrictModeWrapper.tsx
 @ ./src/client/dev.ts

````

## Expected behavior

This feature should be supported as mentioned in the docs

**Comment by JSMD-maintainers** [comment]
@longlho I apologize for the direct tagging - but may be you can directly help out on this. I found a way how to reproduce this issue very easily. So basically if I wrap a german char inside a rich-text element it starts to crash. So basically something like this causes the crash:
```tsx

const BoldComponent = chunks => <b>{chunks}</b>;

<FormattedMessage
                defaultMessage="<b>ööööö</b>" // does crash
                values={{ b: BoldComponent }}
            />
```

```tsx
const BoldComponent = chunks => <b>{chunks}</b>;

<FormattedMessage
                defaultMessage="<b>oe oe oe oe</b>" // does work
                values={{ b: BoldComponent }}
            />
```

**Comment by longlho** [comment]
This plugin has been moved to swc project itself per https://github.com/formatjs/formatjs/issues/3589#issuecomment-2475690731
