### ISSUE TITLE
Missing source map files

### ISSUE THREAD

**Issue by mmamedel** [formatjs/formatjs#4693]
Starting with intl-messageformat version 10.7.4, source map files have been added to package releases. However, source files are not included. As a result we are getting these issues when using packages with Vite:
![image](https://github.com/user-attachments/assets/eb1b0afe-665b-4b23-966d-3dde4e99bd27)
Do you think we could either have source files (in this case the TS files) included in release packages or not include source maps (the .js.map files) that are pointing to them?
My only workaround to avoid this issue right now has been revert to 10.7.3 or silence warning messages.
Thank you

**Comment by longlho** [comment]
is there a way to repro this?
