### ISSUE TITLE
Incorrect value for `['en-GB', 'sv']` with available locales `['en', 'sv']` in `intl-localematcher`

### ISSUE THREAD

**Issue by oskstr** [formatjs/formatjs#4701]
## Which package?

`intl-localematcher`

## Describe the bug

With the requested locales `['en-GB', 'sv']` and the available locales `['en', 'sv']` I would expect the result to be `'en'` but the actual result is `'sv'`. 

### Codesandbox URL

https://codesandbox.io/p/sandbox/youthful-rosalind-thqnd9

### Reproducible Steps/Repo

Here are the test cases provided above, some of which have the expected behavior while some don't. The difference is not immediately clear to me.

```ts
test('en, sv', function () {
  expect(match(['en', 'sv'], ['en', 'sv'], 'en')).toEqual('en')
})
// PASS

test('en-US, sv', function () {
  expect(match(['en-US', 'sv'], ['en', 'sv'], 'en')).toEqual('en')
})
// PASS

test('en-GB, sv', function () {
  expect(match(['en-GB', 'sv'], ['en', 'sv'], 'en')).toEqual('en')
})
// FAIL

test('en-GB-oxendict, sv', function () {
  expect(match(['en-GB-oxendict', 'sv'], ['en', 'sv'], 'en')).toEqual('en')
})
// FAIL

test('en-GB, en-GB-oxendict, sv', function () {
  expect(match(['en-GB', 'en-GB-oxendict', 'sv'], ['en', 'sv'], 'en')).toEqual('en')
})
// PASS
```

## Expected behavior

Various variants of the English locale should match closer to the generic `en` compared to `sv`. 

This appear to be the case already for some variants, like "English (United States)", or combinations of multiple locales, like "English (United Kingdom)" and "English (United Kingdom, Oxford English Dictionary spelling)". 

But this is not the case for "English (United Kingdom)" and "English (United Kingdom, Oxford English Dictionary spelling)" individually.

**Comment by longlho** [comment]
This is expected. `sv` matching with `sv` has a higher score than `en-GB` & `en` (which is an alias for `en-Latn-US`).
The reason the last one passes is because `sv` is ranked lower (index 2 instead of index 1) and that affected the scoring.

**Comment by oskstr** [comment]
> This is expected. `sv` matching with `sv` has a higher score than `en-GB` & `en` (which is an alias for `en-Latn-US`). The reason the last one passes is because `sv` is ranked lower (index 2 instead of index 1) and that affected the scoring.

Ah, alright, thanks 🙌 Sorry, I didn't know that. TIL
