### ISSUE TITLE
Webpack build error

### ISSUE THREAD

**Issue by aradzie** [formatjs/formatjs#4725]
## Which package?

`@formatjs/fast-memoize`

## Describe the bug

Webpack is unable to load sourcemap for file `./node_modules/@formatjs/fast-memoize/lib/index.js`:

<pre>  <font color="#A2734C"><b>WARNING</b></font> in <b>./node_modules/@formatjs/fast-memoize/lib/index.js</b>
  <b>Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):</b>
<b>  </b><font color="#C01C28"><b>Failed</b></font><b> to parse source map from &apos;/home/user/project/node_modules/@formatjs/fast-memoize/index.ts&apos; file: </b><font color="#C01C28"><b>Error</b></font><b>: ENOENT: no such file or directory, open &apos;/home/user/project/node_modules/@formatjs/fast-memoize/index.ts&apos;</b>
   @ ./node_modules/@formatjs/intl/lib/src/utils.js 2:0-61 79:28-35 88:18-37 90:26-33 99:18-37 101:25-32 110:18-37 115:26-33 123:22-41 125:31-38 133:22-41 136:23-30 144:22-41 146:25-32 154:22-41
   @ ./node_modules/@formatjs/intl/lib/index.js 8:0-115 8:0-115 8:0-115 8:0-115 8:0-115 8:0-115
   @ ./node_modules/react-intl/lib/index.js 10:0-226 10:0-226 10:0-226 10:0-226 10:0-226 10:0-226 10:0-226 10:0-226 10:0-226
</pre>

## Expected behavior

Weback should successfully build a project which depends on `formatjs`.

## Additional context

The reason of error is that a sourcemap JSON file refers to a non-existing TypeScript file. Looking at the contents of the file `node_modules/@formatjs/fast-memoize/index.js.map`:

```
{
  "version": 3,
  "file": "index.js",
  "sourceRoot": "",
  "sources": [ "index.ts" ], 
  "names": [ ],
}
```

we see that the `sources` field refers to file `index.ts`, which is missing. Tested with the most recent package versions:

* `react-intl` : `7.0.1`
* `@formatjs/fast-memoize` : `2.2.3`

**Comment by aradzie** [comment]
Reverting to the previous version 2.2.2 of fast-memoize fixes the error:

```
  "overrides": {
    "@formatjs/fast-memoize": "2.2.2"
  }
```

There are no source maps in that version, so a webpack build completes successfully.

**Comment by kunlongxu** [comment]
I have same issue with 2.2.3, because I use yarn, so I fixed it by

```json
  "resolutions": {
    "@formatjs/fast-memoize": "2.2.2"
  }

```

**Comment by jbpenrath** [comment]
As a workaround, until you really need source map of this package, you can prevent `source-map-loader` to look for source map for this package.

```js
// In your webpack config
// ...
{
          enforce: 'pre',
          test: /\.js$/,
          loader: 'source-map-loader',
          options: {
            filterSourceMappingUrl: (url, resourcePath) => {
              return !/@formatjs\/fast-memoize/i.test(resourcePath);
            },
          },
        },
}
// ...
```
