### ISSUE TITLE
`@​formatjs/intl-numberformat` incorrect precision rounding for larger values

### ISSUE THREAD

**Issue by kristersd** [formatjs/formatjs#4771]
## Which package?

`formatjs/formatjs (@​formatjs/intl-numberformat)`

## Describe the bug

`Intl.NumberFormat` polyfill has rounding precision error, when using larger values.

### CodeSandbox URL

https://codesandbox.io/p/sandbox/formatjs-timezone-america-detroit-forked-nj7ghg?file=%2Fsrc%2Findex.mjs

### Reproducible Steps/Repo

1. Check the preview of formatted value in CSB.

## Expected behavior

The value does not have rounding precision error, and is shown as `$1,234,567,891,234,567.35`.

## Additional context

The issue was introduced in https://github.com/formatjs/formatjs/commit/50bd498a45952ad69e62d19a55b19846f33d91e9 .

**Comment by longlho** [comment]
hmm I just checked v7 and it has the same issue. Are you sure this was a regression?
