### ISSUE TITLE
Inconsistent API for date formatting

### ISSUE THREAD

**Issue by apieceofbart** [formatjs/formatjs#4777]
I am using react-intl@6.4.2.
What I noticed is that when I use intl object by calling `createIntl` it will expose `formatDate` function that actually allows passing string as argument, so for example this works fine:
```
formatDate("2010-12-12")
```
The same when using <FormattedDate> component. 
However, this not aligned with `Intl.DateTimeFormat` which only accepts `number | Date`. It's also not aligned with the docs, which clearly state that value should be `number | Date`: https://formatjs.github.io/docs/react-intl/api/#formatdate

**Comment by apieceofbart** [comment]
@longlho hey, thanks for closing the ticket. If I understand correctly you still support passing the string but it's just nowhere documented?
Wouldn't it actually make sense to align with Intl - and that would be a breaking change - or keep this API but make it clear in the docs?

**Comment by longlho** [comment]
I updated the docs in the commit linked.
